### ISSUE TITLE
Another (likely) Hadoop-BAM bug

### ISSUE THREAD

**Issue by davidadamsphd** [broadinstitute/gatk#1098]
The symptom is that I'm getting an invalid record when using the Hadoop-BAM probabilistic splitter. I wrote a small program to verify the bug and the record it's happening on.

To run this, check out da_key_bug and run something similar to my command
```
gcloud beta dataproc jobs submit spark \
  --cluster high-mem-16-8-sd  \
  --properties  spark.executor.memory=38g,spark.executor.instances=15,spark.executor.cores=7 \
  --class org.broadinstitute.hellbender.Main \
  --jar  build/libs/gatk-all-4.pre-alpha-*-spark.jar \
  KeyReadsSpark \
  -I hdfs:///user/davidada/CEUTrio.HiSeq.WGS.b37.NA12878.bam \
  --bps 4194304 \
  --sparkMaster yarn-clien
```
The important bits are the BAM (`gsutil cp gs://jpmartin/hellbender-test-inputs/CEUTrio.HiSeq.WGS.b37.NA12878.bam . ` should work to grab it) and the bps being set to `4194304`. It doesn't happen with a different split. (Yet more evidence pointing to Hadoop-BAM).

The bad record is on chromosome 1 and starts at 801305857. I imagine that making a small input would work to find this issue (instead of needing to use the 300 GB BAM).

Assigning to Uri (I'd assign it to Tom, but I don't know when he's back).
If you need help cutting down that BAM @droazen and @lbergelson can give some advice.

**Comment by tomwhite** [comment]
I've started looking at this. I managed to reproduce on a cluster and narrow it down to a particular split:

```
15/11/12 06:29:34 INFO executor.Executor: Running task 519.0 in stage 0.0 (TID 562)
15/11/12 06:29:34 INFO rdd.NewHadoopRDD: Input split: hdfs://bottou01.sjc.cloudera.com/user/tom/bam/CEUTrio.HiSeq.WGS.b37.NA12878.bam:142662628213169-142936511676415
15/11/12 06:29:34 ERROR executor.Executor: Exception in task 519.0 in stage 0.0 (TID 562)
java.lang.RuntimeException: found the bad record: 1,801305857
     at org.broadinstitute.hellbender.tools.spark.pipelines.Utils.key(KeyReadsSpark.java:43)
     at org.broadinstitute.hellbender.tools.spark.pipelines.KeyReadsSpark.lambda$runTool$72eaf22$1(KeyReadsSpark.java:28)
     at org.broadinstitute.hellbender.tools.spark.pipelines.KeyReadsSpark$$Lambda$11/1228804001.call(Unknown Source)
     at org.apache.spark.api.java.JavaPairRDD$$anonfun$pairFunToScalaFun$1.apply(JavaPairRDD.scala:1002)
     at org.apache.spark.api.java.JavaPairRDD$$anonfun$pairFunToScalaFun$1.apply(JavaPairRDD.scala:1002)
     at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
     at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:219)
     at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)
     at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:68)
     at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
     at org.apache.spark.scheduler.Task.run(Task.scala:64)
     at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     at java.lang.Thread.run(Thread.java:745)
```

This start offset is 2176858951 (142662628213169L>>>16) - i.e. around 2GB in. I've managed to reproduce with a local program now. This reveals the following problem:

```
Caused by: java.lang.IllegalArgumentException: Unrecognized CigarOperator: 11
	at htsjdk.samtools.CigarOperator.binaryToEnum(CigarOperator.java:143)
	at htsjdk.samtools.BinaryCigarCodec.binaryCigarToCigarElement(BinaryCigarCodec.java:87)
	at htsjdk.samtools.BinaryCigarCodec.decode(BinaryCigarCodec.java:63)
	at htsjdk.samtools.BAMRecord.getCigar(BAMRecord.java:243)
	at htsjdk.samtools.SAMRecord.getUnclippedStart(SAMRecord.java:482)
	at org.seqdoop.hadoop_bam.TestBAMInputFormat.getUnclippedStart(TestBAMInputFormat.java:130)
	at org.seqdoop.hadoop_bam.TestBAMInputFormat.getStrandedUnclippedStart(TestBAMInputFormat.java:122)
	at org.seqdoop.hadoop_bam.TestBAMInputFormat.key(TestBAMInputFormat.java:89)
	... 27 more
```

If I shift this offset manually by 1 then the error goes away - which confirms that the split guess is wrong. So we need to strengthen the criteria for a match somehow.

**Comment by droazen** [comment]
@tomwhite Do we need to rely on a guessing approach here? (https://github.com/broadinstitute/gatk/issues/1091)

**Comment by davidadamsphd** [comment]
@droazen, after talking with some of the Google engineers here I think the answer is yes (unless we require having the bam index). However, the checks can be made strict enough to make it improbable for this to happen.

**Comment by droazen** [comment]
@davidadamsphd We should just require a bam index if there's any (ie., non-zero) possibility of this sort of thing happening.

**Comment by droazen** [comment]
Or patch it to create an index in memory of the BGZF block boundaries

**Comment by davidadamsphd** [comment]
@droazen :+1: for requiring a BAM index (once we verify that it indeed solves all of our problems). @jean-philippe-martin said exactly the same thing yesterday to me. So, I think for GATK 4 that's probably the right solution.

It's not a problem of block boundaries. It's a problem of finding the first record within a BGZF block. A record from the previous block _can_ trail onto the next block with no clear indication of how much is left. That requires "guessing" for where the next record starts.

**Comment by droazen** [comment]
@davidadamsphd To clarify, by "BAM index" do we mean a standard `.bai` index, or some custom index format? Can we create the index we need in-memory as a fallback option if it's not present on disk?

Could you comment on https://github.com/broadinstitute/gatk/issues/1091 with your findings, and close that issue if you think it's resolved?

**Comment by droazen** [comment]
What should we do about this issue for alpha?

**Comment by davidadamsphd** [comment]
I'd like to get it fixed before alpha. I think all we need is a cut of Hadoop-BAM (see https://github.com/HadoopGenomics/Hadoop-BAM/issues/30). It limits our ability to use Hadoop-BAM until we codify a path to generate and use the two headers.

**Comment by droazen** [comment]
Ok @davidadamsphd I've reassigned this one to you -- can you take care of revving our Hadoop-BAM dependency?

**Comment by droazen** [comment]
@davidadamsphd This one will be fixed as soon as we rev Hadoop-BAM, right? Could you make a PR for this, and close this ticket once it's in? Thanks!

**Comment by davidadamsphd** [comment]
Hadoop-BAM has been reved.
