### ISSUE TITLE
NPE in FlagStatsSpark if --OUTPUT is not specified

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1202]
--OUTPUT should be required for FlagStatsSpark or it should check if it's specified before trying to write to it

**Comment by lbergelson** [comment]
```
$gatk FlagStatSpark -I src/test/resources/org/broadinstitute/hellbender/engine/reads_data_source_test1.bam

...
...

java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at org.broadinstitute.hellbender.tools.spark.pipelines.FlagStatSpark.runTool(FlagStatSpark.java:39)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:254)
	at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:41)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:98)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:146)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:165)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:71)
```
