### ISSUE TITLE
comparing queryname-ordered cram blows up

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1271]
printreads test using `print_reads.sorted.queryname.sam` and printing to `print_reads.sorted.queryname.cram`

it may be a htsjdk bug

```
htsjdk.samtools.util.RuntimeEOFException: java.lang.RuntimeException: Slice mapped outside of the reference.

	at htsjdk.samtools.CRAMIterator.hasNext(CRAMIterator.java:270)
	at htsjdk.samtools.SamReader$AssertingIterator.hasNext(SamReader.java:568)
	at htsjdk.samtools.util.PeekIterator.hasNext(PeekIterator.java:45)
	at htsjdk.samtools.SecondaryOrSupplementarySkippingIterator.skipAnyNotprimary(SecondaryOrSupplementarySkippingIterator.java:36)
	at htsjdk.samtools.SecondaryOrSupplementarySkippingIterator.advance(SecondaryOrSupplementarySkippingIterator.java:31)
	at org.broadinstitute.hellbender.utils.read.SamComparison.compareQueryNameSortedAlignments(SamComparison.java:218)
	at org.broadinstitute.hellbender.utils.read.SamComparison.compareAlignments(SamComparison.java:70)
	at org.broadinstitute.hellbender.utils.read.SamComparison.<init>(SamComparison.java:44)
	at org.broadinstitute.hellbender.utils.test.SamAssertionUtils.samsEqualLenient(SamAssertionUtils.java:144)
	at org.broadinstitute.hellbender.utils.test.SamAssertionUtils.assertSamsEqualLenient(SamAssertionUtils.java:48)
	at org.broadinstitute.hellbender.utils.test.SamAssertionUtils.assertSamsEqualLenient(SamAssertionUtils.java:92)
	at org.broadinstitute.hellbender.tools.PrintReadsIntegrationTest.testFileToFileCRAM(PrintReadsIntegrationTest.java:50)
...
Caused by: java.lang.RuntimeException: Slice mapped outside of the reference.
	at htsjdk.samtools.cram.structure.Slice.alignmentBordersSanityCheck(Slice.java:74)
	at htsjdk.samtools.cram.structure.Slice.validateRefMD5(Slice.java:84)
	at htsjdk.samtools.CRAMIterator.nextContainer(CRAMIterator.java:185)
	at htsjdk.samtools.CRAMIterator.hasNext(CRAMIterator.java:263)
```

**Comment by cmnbroad** [comment]
The print_reads.sorted.queryname.sam file has an unmapped read following a mapped read, so the resulting cram file has the same thing. Closing as a dup of #1259 and its htsjdk mate https://github.com/samtools/htsjdk/issues/404.
