### ISSUE TITLE
Bad input filename/path (nonexistent file) leads to FileNotFoundException

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#1290]
We should handle this common case better. "gatk-launch CompareSAMs foo bar" ->

htsjdk.samtools.util.RuntimeIOException: java.io.FileNotFoundException: foo (No such file or directory)
	at htsjdk.samtools.FileInputResource$1.make(SamInputResource.java:178)
	at htsjdk.samtools.FileInputResource$1.make(SamInputResource.java:172)
	at htsjdk.samtools.util.Lazy.get(Lazy.java:24)
	at htsjdk.samtools.FileInputResource.asUnbufferedSeekableStream(SamInputResource.java:201)
	at htsjdk.samtools.FileInputResource.asUnbufferedInputStream(SamInputResource.java:206)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:250)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:134)
	at org.broadinstitute.hellbender.tools.picard.sam.CompareSAMs.doWork(CompareSAMs.java:32)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:98)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:146)
	at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgram.instanceMain(PicardCommandLineProgram.java:61)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:66)
	at org.broadinstitute.hellbender.Main.main(Main.java:81)
Caused by: java.io.FileNotFoundException: foo (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at htsjdk.samtools.seekablestream.SeekableFileStream.<init>(SeekableFileStream.java:47)
	at htsjdk.samtools.FileInputResource$1.make(SamInputResource.java:176)
	... 12 more

**Comment by droazen** [comment]
This just needs to be wrapped in a `UserException`

**Comment by droazen** [comment]
alpha

**Comment by akiezun** [comment]
other Picard tools fail with `htsjdk.samtools.SAMException: Cannot read non-existent file:`. For now I'll make it consistent with the other picard tools in gatk.

**Comment by lbergelson** [comment]
closed by #1332
