### ISSUE TITLE
bad argument value shows up as IllegalArgumentException

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1292]
passing `--secondsBetweenProgressUpdates 0` results in

```
java.lang.IllegalArgumentException: secondsBetweenUpdates must be > 0.0
	at org.broadinstitute.hellbender.engine.ProgressMeter.<init>(ProgressMeter.java:129)
	at org.broadinstitute.hellbender.engine.ProgressMeter.<init>(ProgressMeter.java:112)
	at org.broadinstitute.hellbender.engine.GATKTool.onStartup(GATKTool.java:297)
	at org.broadinstitute.hellbender.engine.ReadWalker.onStartup(ReadWalker.java:44)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:96)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:146)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:165)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:66)
	at org.broadinstitute.hellbender.Main.main(Main.java:81)
```

this should be handled by the CLI somehow and show up as a UserException with clean indication that the argument has a bad value (and doc stating what a good value is)

**Comment by lbergelson** [comment]
relevant issue here #143 to add min/max parameters to numeric arguments.

**Comment by droazen** [comment]
beta

**Comment by ldgauthier** [comment]
@cmnbroad  it's actually not entirely obvious how to do this as `minValue` is implemented in Barclay today because `minValue` is inclusive.  Should the minValue in this case be some positive epsilon?

**Comment by cmnbroad** [comment]
@ldguthier Yes, a small epsilon would be the way to go. I'll take this, as I just tested it and I noticed a formatting error in the Barclay code. But I'm planning to do a Barclay release in the next week or so anyway.
