### ISSUE TITLE
blow up on ./gatk-launch ApplyBQSR --help 

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1300]
` ./gatk-launch ApplyBQSR --help`

```
org.broadinstitute.hellbender.exceptions.GATKException: Invalid argument definition in source code.  staticQuantizationQuals doesn't match any known argument.
	at org.broadinstitute.hellbender.cmdline.CommandLineParser.makeArgumentDescription(CommandLineParser.java:492)
	at org.broadinstitute.hellbender.cmdline.CommandLineParser.printArgumentUsage(CommandLineParser.java:433)
	at org.broadinstitute.hellbender.cmdline.CommandLineParser.lambda$usage$3(CommandLineParser.java:201)
	at org.broadinstitute.hellbender.cmdline.CommandLineParser$$Lambda$11/335580595.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.broadinstitute.hellbender.cmdline.CommandLineParser.usage(CommandLineParser.java:201)
	at org.broadinstitute.hellbender.cmdline.CommandLineParser.parseArguments(CommandLineParser.java:258)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.parseArgs(CommandLineProgram.java:187)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:161)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:66)
	at org.broadinstitute.hellbender.Main.main(Main.java:81)
```

**Comment by akiezun** [comment]
same error on BQSRPipelineSpark, ReadsPipelineSpark, ApplyBQSRSpark

**Comment by droazen** [comment]
alpha
