### ISSUE TITLE
blow up on gatk-launch DownSampleSam --help 

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1303]
`gatk-launch DownsampleSam --help`

```
    /local/dev/akiezun/alphaTesting/gatk/build/install/gatk/bin/gatk DownsampleSam --help                                             |
org.broadinstitute.hellbender.exceptions.GATKException$CommandLineParserInternalException: [R, reference] has already been used.      |
        at org.broadinstitute.hellbender.cmdline.CommandLineParser.handleArgumentAnnotation(CommandLineParser.java:620)               |
        at org.broadinstitute.hellbender.cmdline.CommandLineParser.createArgumentDefinitions(CommandLineParser.java:149)              |
        at org.broadinstitute.hellbender.cmdline.CommandLineParser.<init>(CommandLineParser.java:134)                                 |
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.parseArgs(CommandLineProgram.java:186)                            |
        at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgram.instanceMain(PicardCommandLineProgram.java:41)              |
        at org.broadinstitute.hellbender.Main.instanceMain(Main.java:66)                                                              |
        at org.broadinstitute.hellbender.Main.main(Main.java:81)
```

**Comment by droazen** [comment]
alpha
