### ISSUE TITLE
SortVcf can't read v3.3 vcf file but CountVariants and SelectVariants can

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#1304]
CountVariants and SelectVariants both read the same file successfully.

gatk-launch SortVcf --input /humgen/test.filtered.maf_annotated.vcf --output sortvcf.vcf

htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: Your input file has a malformed header: This codec is strictly for VCFv4; please use the VCF3 codec for VCFv3.3, for input source: /humgen/test.filtered.maf_annotated.vcf
	at htsjdk.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:226)
	at htsjdk.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:92)
	at htsjdk.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:103)
	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:89)
	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:66)
	at htsjdk.variant.vcf.VCFFileReader.<init>(VCFFileReader.java:58)
	at org.broadinstitute.hellbender.tools.picard.vcf.SortVcf.collectFileReadersAndHeaders(SortVcf.java:92)
	at org.broadinstitute.hellbender.tools.picard.vcf.SortVcf.doWork(SortVcf.java:76)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:98)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:146)
	at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgram.instanceMain(PicardCommandLineProgram.java:61)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:66)
	at org.broadinstitute.hellbender.Main.main(Main.java:81)
Caused by: htsjdk.tribble.TribbleException$InvalidHeader: Your input file has a malformed header: This codec is strictly for VCFv4; please use the VCF3 codec for VCFv3.3
	at htsjdk.variant.vcf.VCFCodec.readActualHeader(VCFCodec.java:100)
	at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:88)
	at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:41)
	at htsjdk.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:224)
	... 12 more

**Comment by cmnbroad** [comment]
Looks like the VariantWalkers benefit from the Feature codec discovery, but SortVcf is a Picard tool.

**Comment by droazen** [comment]
This is because walkers like `SelectVariants` use file format auto-detection via the `FeatureManager`, whereas picard tools like `SortVcf` hardcode the codec they want to use.

**Comment by droazen** [comment]
beta
