### ISSUE TITLE
gatk-launch blows up when run with the combination --sparkRunner SPARK --sparkMaster local[1]

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1315]
We blow up with the following scary error:

org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost): java.io.IOException: unexpected exception type
	at java.io.ObjectStreamClass.throwMiscException(ObjectStreamClass.java:1538)
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1110)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1810)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:69)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:95)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:58)
	at org.apache.spark.scheduler.Task.run(Task.scala:70)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:230)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1104)
	... 31 more
Caused by: java.lang.IllegalAccessError: no such method: org.broadinstitute.hellbender.tools.FlagStat$FlagStatus.add(GATKRead)FlagStatus/invokeVirtual
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:448)
	at org.broadinstitute.hellbender.tools.spark.pipelines.FlagStatSpark.$deserializeLambda$(FlagStatSpark.java:20)
	... 40 more
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "org.broadinstitute.hellbender.tools.FlagStat$FlagStatus.add(Lorg/broadinstitute/hellbender/utils/read/GATKRead;)Lorg/broadinstitute/hellbender/tools/FlagStat$FlagStatus;" the class loader (instance of org/apache/spark/util/ChildFirstURLClassLoader) of the current class, org/broadinstitute/hellbender/tools/spark/pipelines/FlagStatSpark, and the class loader (instance of org/apache/spark/util/ChildFirstURLClassLoader) for the method's defining class, org/broadinstitute/hellbender/tools/FlagStat$FlagStatus, have different Class objects for the type org/broadinstitute/hellbender/utils/read/GATKRead used in the signature
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:965)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:990)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1387)
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1739)
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:442)
	... 41 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1273)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1264)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1263)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1263)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:730)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:730)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:730)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1457)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1418)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)

**Comment by droazen** [comment]
alpha

**Comment by laserson** [comment]
Wait, how do you run `local[1]` if not with this combination of options?

**Comment by lbergelson** [comment]
@laserson using --sparkMaster 'local[1]' and --sparkRunner DIRECT or nothing at all

**Comment by lbergelson** [comment]
strangely
```
./gatk-launch FlagStatSpark -I src/test/resources/org/broadinstitute/hellbender/tools/flag_stat.bam -o stats.stats --sparkRunner DIRECT --sparkMaster 'local[1]'
```
fails with this explosion, but 

```
./gatk-launch CountReadsSpark -I src/test/resources/org/broadinstitute/hellbender/tools/flag_stat.bam -o stats.stats --sparkRunner SUBMIT --sparkMaster 'local[1]'
``` 

seems to run just fine.  Both run fine when not using spark-submit.  A bit mysterious.

**Comment by laserson** [comment]
Ah, I think I was confused.  IMO, I find `DIRECT` => Spark with `local[*]` to be a bit confusing, especially since most docs out there specify that running Spark locally still uses `spark-submit` with `local[*]`.  I would recommend that `DIRECT` be used only for walkers, and anyone that wants to run locally use the `spark-submit` path.  I wish we could also eliminate the extra `--sparkMaster` arg for the Spark tools.

**Comment by droazen** [comment]
Will have to figure this one out in beta

**Comment by droazen** [comment]
This is a serious issue. Here's another error I've seen when running with `--sparkRunner SPARK` and `--sparkMaster local[*]`:

    ./gatk-launch PrintReadsSpark -I src/test/resources/org/broadinstitute/hellbender/tools/flag_stat.bam -O foo.bam -- --sparkRunner SPARK --sparkMaster local[*]

    org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1.0 (TID 1, localhost): java.lang.ClassCastException: htsjdk.samtools.SAMFileHeader cannot be cast to htsjdk.samtools.SAMFileHeader
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink.lambda$writeReadsSingle$4e0a7f18$1(ReadsSparkSink.java:186)
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink$$Lambda$86/1825278638.call(Unknown Source)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:153)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:153)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:686)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:686)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
	at org.apache.spark.scheduler.Task.run(Task.scala:70)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by lbergelson** [comment]
@laserson Do you have any idea what's going on with spark submit and local[*] causing these crashes?

**Comment by droazen** [comment]
For alpha-1

**Comment by lbergelson** [comment]
Another user reported a very similar error while running:
```
./gatk/gatk-launch MarkDuplicatesSpark -I ../NA12878.bwa.sam -R ../B37/human_g1k_v37_decoy.fasta -O testMD.bam --sparkRunner SPARK --sparkMaster local[64] > NA12878.MD.spark 2>&1
```
[February 22, 2016 3:53:50 PM CST] org.broadinstitute.hellbender.tools.spark.transforms.markduplicates.MarkDuplicatesSpark done. Elapsed time: 19.84 minutes.
Runtime.totalMemory()=38586548224
java.lang.ClassCastException: htsjdk.samtools.SAMRecord cannot be cast to htsjdk.samtools.SAMRecord
	at org.broadinstitute.hellbender.utils.read.HeaderlessSAMRecordCoordinateComparator.compare(HeaderlessSAMRecordCoordinateComparator.java:13)
	at scala.math.LowPriorityOrderingImplicits$$anon$7.compare(Ordering.scala:153)
	at scala.math.Ordering$$anon$5.compare(Ordering.scala:122)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:351)
	at java.util.TimSort.sort(TimSort.java:230)
	at java.util.Arrays.sort(Arrays.java:1438)
	at scala.collection.SeqLike$class.sorted(SeqLike.scala:615)
	at scala.collection.AbstractSeq.sorted(Seq.scala:40)
	at scala.collection.SeqLike$class.sortBy(SeqLike.scala:594)
	at scala.collection.AbstractSeq.sortBy(Seq.scala:40)
	at org.apache.spark.RangePartitioner$.determineBounds(Partitioner.scala:281)
	at org.apache.spark.RangePartitioner.<init>(Partitioner.scala:154)
	at org.apache.spark.rdd.OrderedRDDFunctions$$anonfun$sortByKey$1.apply(OrderedRDDFunctions.scala:62)
	at org.apache.spark.rdd.OrderedRDDFunctions$$anonfun$sortByKey$1.apply(OrderedRDDFunctions.scala:61)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
	at org.apache.spark.rdd.OrderedRDDFunctions.sortByKey(OrderedRDDFunctions.scala:61)
	at org.apache.spark.api.java.JavaPairRDD.sortByKey(JavaPairRDD.scala:922)
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink.sortReads(ReadsSparkSink.java:203)
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink.writeReadsSingle(ReadsSparkSink.java:189)
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink.writeReads(ReadsSparkSink.java:128)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.writeReads(GATKSparkTool.java:234)
	at org.broadinstitute.hellbender.tools.spark.transforms.markduplicates.MarkDuplicatesSpark.runTool(MarkDuplicatesSpark.java:78)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:310)
	at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:98)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:146)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:165)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:66)
	at org.broadinstitute.hellbender.Main.main(Main.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by lbergelson** [comment]
@droazen I don't understand this problem.  I think I'm going to prevent it by having GATK-launch reject commands with spark-submit and local.  Does that seem sane to you?

**Comment by droazen** [comment]
I think it's sane to prevent this combination for now, but let's keep this ticket open to try to eventually understand what's going on. It almost sounds like we have two versions of the `SAMRecord` class for some reason -- could it possibly be a `serialVersionUID` issue?

**Comment by lbergelson** [comment]
It does seem that way.  I don't think it's `serialVersionUID`, that usually manifests as failures to deserialize rather than class cast problems.  I think it's likely an issue with 2 different class loaders loading that same class (based on discussion in #1386.)  Possibly something analogous to https://issues.apache.org/jira/browse/SPARK-1403, but on yarn.

**Comment by lbergelson** [comment]
Actually, scratch the yarn bit, we're not going through yarn at all.  But it feels like something similar happening.

**Comment by lbergelson** [comment]
So after flailing about for a while, it seems like setting  `spark.executor.userClassPathFirst=false` (instead of the current and longstanding default of `=true`) fixes this issue with the local runner.  From my very limited tests it doesn't seem to have dire consequences. I assume we added that because it was necessary, but it's possible it was just to be symmetric with `spark.driver.userClassPathFire=true` (which is necessary).  

@tomwhite Do you have any opinions about this?

**Comment by lbergelson** [comment]
running with ` -verbose:class` shows 2 separate class loaders being used for each class.  
```
 ./gatk-launch PrintReadsSpark -I src/test/resources/org/broadinstitute/hellbender/tools/flag_stat.bam -O foo.bam -- --sparkRunner SPARK --sparkMaster "local[*]" --driver-java-options   2> /dev/null | grep SAMFileHeader
[Loaded htsjdk.samtools.SAMFileHeader from file:/Users/louisb/Workspace/gatk/build/libs/gatk-all-4.alpha-142-g08c27aa-SNAPSHOT-spark.jar]
[Loaded htsjdk.samtools.SAMFileHeader$SortOrder from file:/Users/louisb/Workspace/gatk/build/libs/gatk-all-4.alpha-142-g08c27aa-SNAPSHOT-spark.jar]
[Loaded htsjdk.samtools.SAMFileHeader$GroupOrder from file:/Users/louisb/Workspace/gatk/build/libs/gatk-all-4.alpha-142-g08c27aa-SNAPSHOT-spark.jar]
[Loaded htsjdk.samtools.SAMFileHeader from file:/private/var/folders/xt/vq7wz8955r1401mv8w0f4zf9qbfwzl/T/louisb/spark-6607a950-e256-47fb-9f8c-7a9b60388c0a/userFiles-bd28d98d-f860-43bd-ae54-a3a94dd7eaa7/gatk-all-4.alpha-142-g08c27aa-SNAPSHOT-spark.jar]
[Loaded htsjdk.samtools.SAMFileHeader$SortOrder from file:/private/var/folders/xt/vq7wz8955r1401mv8w0f4zf9qbfwzl/T/louisb/spark-6607a950-e256-47fb-9f8c-7a9b60388c0a/userFiles-bd28d98d-f860-43bd-ae54-a3a94dd7eaa7/gatk-all-4.alpha-142-g08c27aa-SNAPSHOT-spark.jar]
[Loaded htsjdk.samtools.SAMFileHeader$GroupOrder from file:/private/var/folders/xt/vq7wz8955r1401mv8w0f4zf9qbfwzl/T/louisb/spark-6607a950-e256-47fb-9f8c-7a9b60388c0a/userFiles-bd28d98d-f860-43bd-ae54-a3a94dd7eaa7/gatk-all-4.alpha-142-g08c27aa-SNAPSHOT-spark.jar]
```
