### ISSUE TITLE
Travis fails even when local testing works for class AlleleFranctionInitializerUnitTest

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#1320]
Locally testing does ok but when run in Travis you get an error consistently.

The stack trace reads:

<pre>
org.broadinstitute.hellbender.tools.exome.allelefraction.AlleleFractionInitializerUnitTest.testInitialize FAILED
    java.lang.AssertionError: expected [0.0] but found [-0.023368743794425884]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:496)
        at org.testng.Assert.assertEquals(Assert.java:209)
        at org.testng.Assert.assertEquals(Assert.java:222)
        at org.broadinstitute.hellbender.tools.exome.allelefraction.AlleleFractionInitializerUnitTest.testInitialize(AlleleFractionInitializerUnitTest.java:41)
</pre>

**Comment by vruano** [comment]
@davidbenjamin 
Perhaps some random seed number is hostname architecture sensitive? are native libraries involved? If this is using spark perhaps the test becomes non-deterministic?

**Comment by vruano** [comment]
Oups wrong repo! this belongs to gatk-protected. Sorry.
