### ISSUE TITLE
blowup on direct runner with hdfs

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1324]
` ./gatk-launch  CountReadsSpark --input hdfs:///user/akiezun/data/HCC1143_BL.bam -- --sparkRunner DIRECT`

gives me 
```
java.lang.IllegalArgumentException: Wrong FS: hdfs:/user/akiezun/data/HCC1143_BL.bam, expected: file:///
	at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:647)
	at org.apache.hadoop.fs.FileSystem.makeQualified(FileSystem.java:466)
	at org.apache.hadoop.fs.FilterFileSystem.makeQualified(FilterFileSystem.java:119)
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSource.getHeader(ReadsSparkSource.java:181)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.initializeReads(GATKSparkTool.java:284)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.initializeToolInputs(GATKSparkTool.java:264)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:255)
	at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:36)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:98)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:146)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:165)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:66)
	at org.broadinstitute.hellbender.Main.main(Main.java:81)
```

**Comment by lbergelson** [comment]
This is the issue I was talking about the other day in our collaboration meeting.  The file system is determined by the spark environment.  In the direct runner it ends up being a `LocalFileSystem`.  If you run using the SUBMIT runner on your own computer you'll likely also get a `LocalFileSystem`, if you run with SUBMIT on dataflow01 you'll be able to read hdfs, but unable to access `file://` and all paths will be silently translated to hdfs paths if file:// is specified..

**Comment by droazen** [comment]
There must be a way to disable this auto-translation of the scheme part of the URI...

**Comment by lbergelson** [comment]
related to #1257 by way of filesystem confusion

**Comment by droazen** [comment]
beta, too hard to fix for now probably

**Comment by droazen** [comment]
For alpha-1.

**Comment by droazen** [comment]
Re-assigning this one to @tomwhite, who may have additional insight in this issue.
