### ISSUE TITLE
Can't write bams to /dev/null/ with spark

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1436]
Trying to write bam to dev null using PrintReadsSpark results in:

```
org.broadinstitute.hellbender.exceptions.GATKException: unable to write bam: org.apache.hadoop.fs.ParentNotDirectoryException: Parent path is not a directory: file:/dev/null
	at org.broadinstitute.hellbender.tools.spark.pipelines.PrintReadsSpark.runTool(PrintReadsSpark.java:50)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:257)
	at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:98)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:146)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:165)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:66)
	at org.broadinstitute.hellbender.Main.main(Main.java:81)
```

**Comment by yonraf** [comment]
thank you
