### ISSUE TITLE
Spark Standalone+Markduplicates results in empty BAM or 'Wrong FS' exception

### ISSUE THREAD

**Issue by geetduggal** [broadinstitute/gatk#1444]
I am running into an issue with MarkDuplicatesSpark where it runs successfully in local mode, but if I run it in standalone mode with files on the file system or hdfs I get unexpected results.   It could be that I'm doing something very basic wrong here, so I'm pasting a bunch of contextual information in case it helps.  Thanks in advance!

```
# Output BAM is correct in local mode:
$GATK_DIR/gatk-launch MarkDuplicatesSpark -I NA12878.chrom20.100kb.ILLUMINA.bwa.CEU.exome.20121211.bam -O test.local.bam

# Outputs empty BAM (i.e. header but no alignments) in standalone mode:
$GATK_DIR/gatk-launch MarkDuplicatesSpark -I NA12878.chrom20.100kb.ILLUMINA.bwa.CEU.exome.20121211.bam -O test.standalone.bam -- --sparkRunner SPARK --sparkMaster spark://localhost:7077

# Errors out with a wrong FS type (stacktrace below):
$GATK_DIR/gatk-launch MarkDuplicatesSpark -I hdfs://bam/NA12878.chrom20.100kb.ILLUMINA.bwa.CEU.exome.20121211.bam -O hdfs://bam/test.hdfs.bam -- --sparkRunner SPARK --sparkMaster spark://localhost:7077
```

And the stacktrace for the HDFS case (I'm running HDFS in Pseudo-Distributed mode on the same host as I a running Spark standalone mode on): 

```
org.broadinstitute.hellbender.tools.spark.transforms.markduplicates.MarkDuplicatesSpark done. Elapsed time: 0.07 minutes.
Runtime.totalMemory()=1029177344
java.lang.IllegalArgumentException: Wrong FS: hdfs://bam/NA12878.chrom20.100kb.ILLUMINA.bwa.CEU.exome.20121211.bam, expected: file:///
        at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:645)
        at org.apache.hadoop.fs.FileSystem.makeQualified(FileSystem.java:465)
        at org.apache.hadoop.fs.FilterFileSystem.makeQualified(FilterFileSystem.java:119)
        at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSource.getHeader(ReadsSparkSource.java:181)
        at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.initializeReads(GATKSparkTool.java:284)
        at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.initializeToolInputs(GATKSparkTool.java:264)
        at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:255)
        at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:98)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:146)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:165)
        at org.broadinstitute.hellbender.Main.instanceMain(Main.java:66)
        at org.broadinstitute.hellbender.Main.main(Main.java:81)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
16/01/21 14:55:33 INFO ShutdownHookManager: Shutdown hook called
```

Attached is a small BAM file that I used to reproduce the error (If memory serves, I've seen this issue on other BAM files as well):

[NA12878.chrom20.100kb.ILLUMINA.bwa.CEU.exome.20121211.bam.zip](https://github.com/broadinstitute/gatk/files/101575/NA12878.chrom20.100kb.ILLUMINA.bwa.CEU.exome.20121211.bam.zip)

(This issue may be related to one posted here: https://github.com/broadinstitute/gatk/issues/1417.)

Here is some information on what I installed:

```
    echo "Installing Java"
    sudo add-apt-repository -y ppa:webupd8team/java
    sudo apt-get -qq update
    echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
    echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
    sudo apt-get -qq install -y oracle-java8-installer

    java -version

    echo "Installing Gradle"
    sudo add-apt-repository -y ppa:cwchien/gradle
    sudo apt-get -qq update  > /dev/null
    sudo apt-get -qq install -y gradle

    echo "Downloading binaries for Spark"
    wget http://d3kbcqa49mib13.cloudfront.net/spark-1.5.1-bin-hadoop2.6.tgz
    tar -xzf spark-1.5.1-bin-hadoop2.6.tgz
    export SPARK_HOME=spark-1.5.1-bin-hadoop2.6

    echo "Set up Spark for standalone mode processing"
    $SPARK_HOME/sbin/start-master.sh -h localhost
    $SPARK_HOME/sbin/start-slave.sh spark://localhost:7077


    echo "Downloading source for GATK4"
    wget https://github.com/broadinstitute/gatk/archive/4.alpha.tar.gz
    tar -xvzf 4.alpha.tar.gz
    export GATK_DIR=gatk-4.alpha

    echo "Building GATK4"
    cd $GATK_DIR
    gradle installAll
    cd ..

```

**Comment by lbergelson** [comment]
Hi @geetduggal.  Thanks for the very complete error report!   I'm sorry you're running into these errors.  We're aware of similar problems and fixing them is a very high priority.

It looks like you're running use the tagged alpha version.  I might try using the most version.  Pull request #1433  should hopefully fix the problem your seeing in your third example, which I believe is likely caused by the same issue as in #1324.  (Note that you may have to specify hdfs paths using their full name including the node address.  i.e. `hdfs://bottou01.sjc.cloudera.com/user/tom/bam/CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.bam`.  If you haven't changed it the default name it's probably `fs.defaultFS`)  Would you mind trying with the latest version of master?  ( 98f01b0 or newer).  




The second case of producing an empty bam file is a worrying one, and not one I've seen before.  I can reproduce it locally.

```
./gatk-launch MarkDuplicatesSpark -I src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam -O test.standalone.bam -- --sparkRunner SPARK --sparkMaster spark://wm1b0-8ab:7077
```
results in a bam with only the header.

I filed a new issue #1448 to track this error mode.

**Comment by geetduggal** [comment]
Thanks for your prompt response!  I'll let you know how it works with the most recent version on Github.

**Comment by lbergelson** [comment]
@geetduggal Does the most recent master solve these issues for you?

**Comment by geetduggal** [comment]
Yes.  Thanks!

**Comment by lbergelson** [comment]
Going to mark this as closed then.  Thanks for your input.
