### ISSUE TITLE
MarkDuplicates can't write to file:/// when using yarn

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1451]
Likely an analogous problem to #1417.

```
./gatk-launch MarkDuplicatesSpark -I file:////home/unix/louisb/flag_stat.bam -O file:////home/unix/louisb/testoutput.bam -- --sparkRunner SPARK --sparkMaster yarn-client
```
results in:
```
java.lang.IllegalArgumentException: Wrong FS: file:/home/unix/louisb/testoutput.bam, expected: hdfs://dataflow01.broadinstitute.org:8020
	at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:654)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:193)
	at org.apache.hadoop.hdfs.DistributedFileSystem.access$000(DistributedFileSystem.java:105)
	at org.apache.hadoop.hdfs.DistributedFileSystem$12.doCall(DistributedFileSystem.java:645)
	at org.apache.hadoop.hdfs.DistributedFileSystem$12.doCall(DistributedFileSystem.java:641)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.delete(DistributedFileSystem.java:641)
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink.deleteHadoopFile(ReadsSparkSink.java:200)
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink.writeReadsSingle(ReadsSparkSink.java:191)
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink.writeReads(ReadsSparkSink.java:106)
	at org.broadinstitute.hellbender.tools.spark.transforms.markduplicates.MarkDuplicatesSpark.runTool(MarkDuplicatesSpark.java:94)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:257)
	at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:98)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:146)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:165)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:66)
	at org.broadinstitute.hellbender.Main.main(Main.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by lbergelson** [comment]
different exception on branch https://github.com/broadinstitute/gatk/tree/lb_refactor_to_reduce_ReadSparkSink_duplication

debugging seems to point to the `.` in `testoutput.bam` as the problem, but why that's causing a problem under yarn is mysterious.
```
caused by: java.io.IOException: Mkdirs failed to create file:/home/unix/louisb/writeable/testoutput.bam/_temporary/0/_temporary/attempt_201601291710_0020_r_000000_3 (exists=false, cwd=file:/mnt/disk10/yarn/nm/usercache/louisb/appcache/application_1452219145116_0780/container_1452219145116_0780_01_000002)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:442)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:428)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:917)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:898)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:795)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:784)
	at org.seqdoop.hadoop_bam.BAMRecordWriter.<init>(BAMRecordWriter.java:74)
	at org.seqdoop.hadoop_bam.KeyIgnoringBAMRecordWriter.<init>(KeyIgnoringBAMRecordWriter.java:49)
	at org.seqdoop.hadoop_bam.KeyIgnoringBAMOutputFormat.getRecordWriter(KeyIgnoringBAMOutputFormat.java:91)
	at org.seqdoop.hadoop_bam.KeyIgnoringBAMOutputFormat.getRecordWriter(KeyIgnoringBAMOutputFormat.java:79)
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink$SparkBAMOutputFormat.getRecordWriter(ReadsSparkSink.java:65)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1030)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1014)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tomwhite** [comment]
Not sure about the mkdirs problem (does the directory already exist?), but the `Wrong FS` problem can be fixed by always getting the filesystem from the path, rather than just using the default filesystem. See https://github.com/broadinstitute/gatk/commit/b671a10f4552360580a79074d4d4229fdb425748 for a fix.

**Comment by lbergelson** [comment]
I've fixed the Wrong FS in #1461, but it just ends up changing the error to the second one I posted.

**Comment by droazen** [comment]
@lbergelson Is this one fixed yet?

**Comment by lbergelson** [comment]
Not yet.  This is still mysterious to me.

**Comment by tomwhite** [comment]
@lbergelson what are the steps to reproduce this?

**Comment by lbergelson** [comment]
@tomwhite Sorry! I missed your message.  This reproduces reliably on our cluster if you run the command I posted above on our current master branch.

```
./gatk-launch MarkDuplicatesSpark -I file:///home/unix/louisb/flag_stat.bam -O file:///home/unix/louisb/testoutput.bam -- --sparkRunner SPARK --sparkMaster yarn-client
```

You'll have to adapt it to your own file system or log into ours. Folders under /home/unix/ are visible to every node in our cluster.

**Comment by lbergelson** [comment]
Things to try:

Write to local file instead of nfs
Set spark.hadoop.fs.file.impl

**Comment by akiezun** [comment]
@tomwhite can you take this?

**Comment by tomwhite** [comment]
I'm afraid I can't reproduce this as I don't have NFS on the cluster I'm using.

**Comment by droazen** [comment]
Assigning to @lbergelson to see if this is still an issue
