### ISSUE TITLE
RevertBaseQualityScores blowup

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1473]
running RevertBaseQualityScores from Version:4.alpha-70-g10d9ec1-SNAPSHOT on /seq/picard_aggregation/G77386/NA12878/v1/NA12878.bam

```
java.lang.IllegalArgumentException: end must be >= start. start:13984870 end:13984869
        at org.broadinstitute.hellbender.utils.SimpleInterval.validatePositions(SimpleInterval.java:61)
        at org.broadinstitute.hellbender.utils.SimpleInterval.<init>(SimpleInterval.java:33)
        at org.broadinstitute.hellbender.utils.SimpleInterval.<init>(SimpleInterval.java:45)
        at org.broadinstitute.hellbender.engine.ReadWalker.lambda$traverse$18(ReadWalker.java:79)
        at org.broadinstitute.hellbender.engine.ReadWalker$$Lambda$45/1492875057.accept(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.broadinstitute.hellbender.engine.ReadWalker.traverse(ReadWalker.java:78)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:448)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:98)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:146)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:165)
```

**Comment by akiezun** [comment]
here;s the killer read
```
H22NGALXX141215:1:2116:28232:43888	1171	1	13984870	50	61S90I	=	13984520	-350	GGCCACCCCCCCCCCGGCCCCGCCGCGCCGTCCGGCAGGCGAGGCGCGCCTCTCCCCCCCCGCCCCTACTGGGAAGTGAGGAGCCCCTCCGCCCGGCCAGCCGCCCCATCCAGGAGGGAGGTGGGGGGGTCAGCCCCCCGCCCGGCCAGCC	###########################################################915>=:8/+*)9>6,?1)9.+<05<=:=)7%(=>2(;2*98=7<===<9<====<===<==<===<7;;<<=;<<===<8===8=>>??<=<	MC:Z:151M	OC:Z:61S90M	PG:Z:MarkDuplicates.4	RG:Z:H22NG.1	NM:i:90	MQ:i:60	OQ:Z:###########################################################A<<KFA<7,,,AK<,F7,A,,F(<FFAF,<((KKA(F7(<AKFFKKKFAKKKKKKKKKKKKKKKKF<FFKKFAFFFKKFKKKKKKKKFFFAA	UQ:i:0	AS:i:80
```
