### ISSUE TITLE
Errors in spark tests when connected to Broad VPN

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1534]
@SHuang-Broad reports having problems running spark tests when his machine is connected to the broad vpn

Errors seem to occur with any tests that start a spark context.  They all seem to be caused by `java.net.BindException`

```
23:59:49.200 ERROR NettyTransport:65 - failed to bind to /10.1.2.144:0, shutting down Netty transport
23:59:49.200 WARN  Utils:71 - Service 'sparkDriver' could not bind on port 0. Attempting port 1.
23:59:49.200 ERROR Remoting:65 - Remoting system has been terminated abrubtly. Attempting to shut down transports
23:59:49.206 ERROR NettyTransport:65 - failed to bind to /10.1.2.144:0, shutting down Netty transport
23:59:49.206 ERROR SparkContext:96 - Error initializing SparkContext.
java.net.BindException: Failed to bind to: /10.1.2.144:0: Service 'sparkDriver' failed after 16 retries!
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
	at akka.remote.transport.netty.NettyTransport$$anonfun$listen$1.apply(NettyTransport.scala:393)
	at akka.remote.transport.netty.NettyTransport$$anonfun$listen$1.apply(NettyTransport.scala:389)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by lbergelson** [comment]
I haven't been able to reproduce this on my machine.

**Comment by cwhelan** [comment]
This happens to me, too.

**Comment by lbergelson** [comment]
Strange.  I wonder why it's different for me.

**Comment by droazen** [comment]
@cwhelan @SHuang-Broad are either of you still experiencing this problem?

**Comment by SHuang-Broad** [comment]
I'm no longer experiencing this.

**Comment by cwhelan** [comment]
I'm still getting this error.

**Comment by cwhelan** [comment]
If you set the environment variable `SPARK_LOCAL_IP="127.0.0.1"` , as suggested by this SO post: https://stackoverflow.com/questions/34601554/mac-spark-shell-error-initializing-sparkcontext, the error goes away, so I think it's related to some change in the localhost network configuration our VPN sets up.

**Comment by sooheelee** [comment]
This happens for me also.

**Comment by SHuang-Broad** [comment]
Now, when we are all working from home, this came back....
