### ISSUE TITLE
Errors in VariantFiltration - possibly due to (or exposed by) async tribble reading 

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1638]
this happens on the branch for https://github.com/broadinstitute/gatk/pull/1630 (which uses async IO for tests to mimic non-test usage). This bug is either due to or exposed by asynchronous tribble reading.
 
more logs https://travis-ci.org/broadinstitute/gatk/jobs/118507152

test results
https://storage.googleapis.com/hellbender/test/build_reports/5109.2/tests/classes/org.broadinstitute.hellbender.tools.walkers.filters.VariantFiltrationIntegrationTest.html#testClusteredSnps

```
java.lang.RuntimeException: htsjdk.tribble.TribbleException: Exception encountered in worker thread.
	at org.broadinstitute.hellbender.utils.test.IntegrationTestSpec.executeTest(IntegrationTestSpec.java:153)
	at org.broadinstitute.hellbender.utils.test.IntegrationTestSpec.executeTest(IntegrationTestSpec.java:126)
	at org.broadinstitute.hellbender.utils.test.IntegrationTestSpec.executeTest(IntegrationTestSpec.java:108)
	at org.broadinstitute.hellbender.tools.walkers.filters.VariantFiltrationIntegrationTest.testClusteredSnps(VariantFiltrationIntegrationTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:133)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:83)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: htsjdk.tribble.TribbleException: Exception encountered in worker thread.
	at htsjdk.tribble.readers.AsynchronousLineReader.checkAndThrowIfWorkerException(AsynchronousLineReader.java:61)
	at htsjdk.tribble.readers.AsynchronousLineReader.readLine(AsynchronousLineReader.java:43)
	at htsjdk.tribble.readers.LineIteratorImpl.advance(LineIteratorImpl.java:24)
	at htsjdk.tribble.readers.LineIteratorImpl.advance(LineIteratorImpl.java:11)
	at htsjdk.samtools.util.AbstractIterator.hasNext(AbstractIterator.java:44)
	at htsjdk.tribble.AsciiFeatureCodec.isDone(AsciiFeatureCodec.java:53)
	at htsjdk.tribble.AsciiFeatureCodec.isDone(AsciiFeatureCodec.java:41)
	at htsjdk.tribble.TribbleIndexedFeatureReader$QueryIterator.readNextRecord(TribbleIndexedFeatureReader.java:447)
	at htsjdk.tribble.TribbleIndexedFeatureReader$QueryIterator.<init>(TribbleIndexedFeatureReader.java:390)
	at htsjdk.tribble.TribbleIndexedFeatureReader.query(TribbleIndexedFeatureReader.java:259)
	at org.broadinstitute.hellbender.engine.FeatureDataSource.refillQueryCache(FeatureDataSource.java:522)
	at org.broadinstitute.hellbender.engine.FeatureDataSource.queryAndPrefetch(FeatureDataSource.java:491)
	at org.broadinstitute.hellbender.engine.FeatureManager.getFeatures(FeatureManager.java:253)
	at org.broadinstitute.hellbender.engine.FeatureContext.getValues(FeatureContext.java:162)
	at org.broadinstitute.hellbender.engine.FeatureContext.getValues(FeatureContext.java:138)
	at org.broadinstitute.hellbender.tools.walkers.filters.VariantFiltration.areClusteredSNPs(VariantFiltration.java:369)
	at org.broadinstitute.hellbender.tools.walkers.filters.VariantFiltration.filter(VariantFiltration.java:300)
	at org.broadinstitute.hellbender.tools.walkers.filters.VariantFiltration.apply(VariantFiltration.java:265)
	at org.broadinstitute.hellbender.engine.VariantWalker.lambda$traverse$30(VariantWalker.java:96)
	at org.broadinstitute.hellbender.engine.VariantWalker$$Lambda$415/83249460.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.VariantWalker.traverse(VariantWalker.java:94)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:517)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:102)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:151)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:170)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:67)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:74)
	at org.broadinstitute.hellbender.CommandLineProgramTest.runCommandLine(CommandLineProgramTest.java:65)
	at org.broadinstitute.hellbender.CommandLineProgramTest.runCommandLine(CommandLineProgramTest.java:69)
	at org.broadinstitute.hellbender.utils.test.IntegrationTestSpec.executeTest(IntegrationTestSpec.java:148)
	... 49 more
Caused by: java.nio.channels.ClosedChannelException
	at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:109)
	at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:252)
	at htsjdk.samtools.seekablestream.SeekableFileStream.position(SeekableFileStream.java:64)
	at htsjdk.tribble.TribbleIndexedFeatureReader$BlockStreamWrapper.read(TribbleIndexedFeatureReader.java:534)
	at java.io.InputStream.read(InputStream.java:101)
	at htsjdk.tribble.readers.PositionalBufferedStream.fill(PositionalBufferedStream.java:127)
	at htsjdk.tribble.readers.PositionalBufferedStream.read(PositionalBufferedStream.java:79)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at htsjdk.tribble.readers.LongLineBufferedReader.fill(LongLineBufferedReader.java:140)
	at htsjdk.tribble.readers.LongLineBufferedReader.readLine(LongLineBufferedReader.java:298)
	at htsjdk.tribble.readers.LongLineBufferedReader.readLine(LongLineBufferedReader.java:354)
	at htsjdk.tribble.readers.AsynchronousLineReader$Worker.run(AsynchronousLineReader.java:75)
	... 1 more
```

**Comment by droazen** [comment]
Let's disable async I/O until the htsjdk patch to selectively disable it for tribble propagates to us

**Comment by lbergelson** [comment]
I'm seeing an error that I'm attributing to async until proven otherwise:

```
02:56:04.432 INFO  ProgressMeter -           6:28093199            425.4              67037000         157580.9
02:56:15.165 INFO  ProgressMeter -           6:28465370            425.6              67115000         157697.9
02:56:25.302 INFO  ProgressMeter -           6:28889616            425.8              67154000         157726.9
02:56:35.310 INFO  ProgressMeter -           6:29230512            425.9              67204000         157782.6
02:56:45.327 INFO  ProgressMeter -           6:29580315            426.1              67277000         157892.1
02:56:55.364 INFO  ProgressMeter -           6:30134971            426.3              67386000         158085.8
02:57:05.383 INFO  ProgressMeter -           6:30550933            426.4              67453000         158181.0
02:57:15.412 INFO  ProgressMeter -           6:30698440            426.6              67589000         158437.9
02:57:25.467 INFO  ProgressMeter -           6:31170505            426.8              67702000         158640.4
02:57:27.558 INFO  BaseRecalibrator - Shutting down engine
[March 26, 2016 2:57:27 AM EDT] org.broadinstitute.hellbender.tools.walkers.bqsr.BaseRecalibrator done. Elapsed time: 426.81 minutes.
Runtime.totalMemory()=2072510464
org.broadinstitute.hellbender.exceptions.GATKException: Error querying file /test-data/benchmark/dbsnp_138.b37.excluding_sites_after_129.vcf over interval 6:31324852-31324924
	at org.broadinstitute.hellbender.engine.FeatureDataSource.refillQueryCache(FeatureDataSource.java:526)
	at org.broadinstitute.hellbender.engine.FeatureDataSource.queryAndPrefetch(FeatureDataSource.java:491)
	at org.broadinstitute.hellbender.engine.FeatureManager.getFeatures(FeatureManager.java:253)
	at org.broadinstitute.hellbender.engine.FeatureContext.getValues(FeatureContext.java:162)
	at org.broadinstitute.hellbender.engine.FeatureContext.getValues(FeatureContext.java:114)
	at org.broadinstitute.hellbender.engine.FeatureContext.getValues(FeatureContext.java:253)
	at org.broadinstitute.hellbender.tools.walkers.bqsr.BaseRecalibrator.apply(BaseRecalibrator.java:169)
	at org.broadinstitute.hellbender.engine.ReadWalker.lambda$traverse$0(ReadWalker.java:80)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.ReadWalker.traverse(ReadWalker.java:78)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:517)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:102)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:152)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:171)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:67)
	at org.broadinstitute.hellbender.Main.main(Main.java:82)
Caused by: java.io.IOException: Stream Closed
	at java.io.RandomAccessFile.seek0(Native Method)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:557)
	at htsjdk.samtools.seekablestream.SeekableFileStream.seek(SeekableFileStream.java:60)
	at htsjdk.tribble.TribbleIndexedFeatureReader$BlockStreamWrapper.<init>(TribbleIndexedFeatureReader.java:521)
	at htsjdk.tribble.TribbleIndexedFeatureReader$QueryIterator.advanceBlock(TribbleIndexedFeatureReader.java:420)
	at htsjdk.tribble.TribbleIndexedFeatureReader$QueryIterator.<init>(TribbleIndexedFeatureReader.java:389)
	at htsjdk.tribble.TribbleIndexedFeatureReader.query(TribbleIndexedFeatureReader.java:259)
	at org.broadinstitute.hellbender.engine.FeatureDataSource.refillQueryCache(FeatureDataSource.java:522)
	... 24 more
```

See https://gatk-jenkins.broadinstitute.org/job/GATK-BQSR/2/console.  I see it locally too.  Seems to be non-deterministic.

**Comment by akiezun** [comment]
an attempted fix is in https://github.com/samtools/htsjdk/issues/577

**Comment by droazen** [comment]
@akiezun Why are you using tribble async I/O at all? Didn't we decide never to use that?

**Comment by akiezun** [comment]
We decided to not use it because of bugs. I wanted to fix the bugs. But the whole async tribble may be hopelessly broken beyond repair - see comments in samtools/htsjdk#577.

**Comment by droazen** [comment]
@akiezun We shouldn't waste time trying to fix it -- let's just add a prominent warning in htsjdk that it's not safe to use and move on.

**Comment by akiezun** [comment]
Anyway, closing this. It's not a GATK bug but a htsjdk bug
