### ISSUE TITLE
Implement a test that catches failures to register new annotations in GATKVCFHeaderLines

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1713]

**Comment by droazen** [comment]
If an annotation's header line isn't registered in `GATKVCFHeaderLines`, it can cause a NPE deep in htsjdk when we go to write the header.

**Comment by akiezun** [comment]
do you have a stacktrace?

**Comment by droazen** [comment]
Eg., for `ExcessHet` we needed a line like:

        addInfoLine(new VCFInfoHeaderLine(EXCESS_HET_KEY, 1, VCFHeaderLineType.Float, "Phred-scaled p-value for exact test of excess heterozygosity"));

**Comment by droazen** [comment]
Example stacktrace:

org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerIntegrationTest.testGVCFModeIsConcordantWithGATK3Results FAILED
    java.lang.NullPointerException
        at htsjdk.variant.vcf.VCFHeader.removeVCFVersionLines(VCFHeader.java:268)
        at htsjdk.variant.vcf.VCFHeader.<init>(VCFHeader.java:115)
        at htsjdk.variant.vcf.VCFHeader.<init>(VCFHeader.java:139)
        at htsjdk.variant.vcf.VCFHeader.<init>(VCFHeader.java:135)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.writeHeader(HaplotypeCallerEngine.java:401)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller.onTraversalStart(HaplotypeCaller.java:204)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:515)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:102)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:155)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:174)
        at org.broadinstitute.hellbender.Main.instanceMain(Main.java:67)
        at org.broadinstitute.hellbender.Main.instanceMain(Main.java:74)
        at org.broadinstitute.hellbender.CommandLineProgramTest.runCommandLine(CommandLineProgramTest.java:65)
        at org.broadinstitute.hellbender.CommandLineProgramTest.runCommandLine(CommandLineProgramTest.java:69)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerIntegrationTest.testGVCFModeIsConcordantWithGATK3Results(HaplotypeCallerIntegrationTest.java:109)

**Comment by droazen** [comment]
(Note that I've fixed this for ExcessHet in the HC branch)
