### ISSUE TITLE
FilterVcf blows up with NPE

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1727]
```
./gatk-launch FilterVcf -I src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testGenotypeFilters1.vcf -O a.vcf
```

```
java.lang.NullPointerException
    at org.broadinstitute.hellbender.tools.picard.vcf.filter.AlleleBalanceFilter.filter(AlleleBalanceFilter.java:50)
    at org.broadinstitute.hellbender.tools.picard.vcf.filter.FilterApplyingVariantIterator.next(FilterApplyingVariantIterator.java:52)
    at org.broadinstitute.hellbender.tools.picard.vcf.filter.FilterVcf.doWork(FilterVcf.java:85)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:102)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:155)
    at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgram.instanceMain(PicardCommandLineProgram.java:61)
    at org.broadinstitute.hellbender.Main.instanceMain(Main.java:67)
    at org.broadinstitute.hellbender.Main.main(Main.java:82)
```

the bug is in `AlleleBalanceFilter` - it assumes that all genotypes have 2 AD fields and crashes and burns if they don't.

**Comment by akiezun** [comment]
blocked on #1210

**Comment by droazen** [comment]
Closing as obsolete
