### ISSUE TITLE
is our test suite leaking threads in ProcessController?

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1740]
I find hundreds of those in jstack dump created towards the end of our test run. The wait has no timeout and so these threads never die

```
"OutputCapture-3-stdout-Test worker-12" #1118 daemon prio=5 os_prio=31 tid=0x00007f818d05c000 nid=0xde23 in Object.wait() [0x0000000127aae000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at org.broadinstitute.hellbender.utils.runtime.ProcessController$OutputCapture.run(ProcessController.java:315)
        - locked <0x000000077cf28d98> (a java.util.EnumMap)
```

**Comment by akiezun** [comment]
holy smokes we have a `finalize()` method! It has to go.

**Comment by droazen** [comment]
Are you talking about `Object.finalize()`, or `BaseRecalibrationEngine.finalizeRecalibrationTables()`?

**Comment by akiezun** [comment]
Object.finalize()

**Comment by droazen** [comment]
Closing -- I don't know of any problems resulting from this
