### ISSUE TITLE
async writer thread leak in test suite

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1741]
this guy never dies

```
"SAMFileWriterThread-187" #471 daemon prio=5 os_prio=31 tid=0x00007f818d4b3000 nid=0xd98b waiting on condition [0x0000000126530000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000007507b5178> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:418)
        at htsjdk.samtools.util.AbstractAsyncWriter$WriterRunnable.run(AbstractAsyncWriter.java:116)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by akiezun** [comment]
allocating stack trace
```
   java.lang.Exception
        at htsjdk.samtools.util.AbstractAsyncWriter.<init>(AbstractAsyncWriter.java:42)
        at htsjdk.samtools.AsyncSAMFileWriter.<init>(AsyncSAMFileWriter.java:32)
        at htsjdk.samtools.SAMFileWriterFactory.makeBAMWriter(SAMFileWriterFactory.java:216)
        at htsjdk.samtools.SAMFileWriterFactory.makeBAMWriter(SAMFileWriterFactory.java:188)
        at htsjdk.samtools.SAMFileWriterFactory.makeSAMOrBAMWriter(SAMFileWriterFactory.java:324)
        at htsjdk.samtools.SAMFileWriterFactory.makeWriter(SAMFileWriterFactory.java:343)
        at org.broadinstitute.hellbender.utils.read.ReadUtils.createCommonSAMWriterFromFactory(ReadUtils.java:949)
        at org.broadinstitute.hellbender.utils.read.ReadUtils.createCommonSAMWriter(ReadUtils.java:921)
        at org.broadinstitute.hellbender.engine.GATKTool.createSAMWriter(GATKTool.java:405)
        at org.broadinstitute.hellbender.tools.walkers.bqsr.ApplyBQSR.onTraversalStart(ApplyBQSR.java:54)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:515)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:102)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:155)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:174)
        at org.broadinstitute.hellbender.Main.instanceMain(Main.java:67)
        at org.broadinstitute.hellbender.Main.instanceMain(Main.java:74)
        at org.broadinstitute.hellbender.CommandLineProgramTest.runCommandLine(CommandLineProgramTest.java:65)
        at org.broadinstitute.hellbender.CommandLineProgramTest.runCommandLine(CommandLineProgramTest.java:69)
        at org.broadinstitute.hellbender.utils.test.IntegrationTestSpec.executeTest(IntegrationTestSpec.java:148)
        at org.broadinstitute.hellbender.utils.test.IntegrationTestSpec.executeTest(IntegrationTestSpec.java:126)
        at org.broadinstitute.hellbender.utils.test.IntegrationTestSpec.executeTest(IntegrationTestSpec.java:101)
        at org.broadinstitute.hellbender.tools.walkers.bqsr.ApplyBQSRIntegrationTest.testPRFailWithLowMaxCycle(ApplyBQSRIntegrationTest.java:134)
```

**Comment by akiezun** [comment]
it's because we only close the writer on `onTraversalSuccess`. This will be an issue for all tools

**Comment by droazen** [comment]
How could the writer be closed before the traversal is complete?
