### ISSUE TITLE
BuildBamIndex - scary exception on cram input

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1783]
`./gatk-launch BuildBamIndex -I src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.cram`

blows up with a bogus exception

```
htsjdk.samtools.SAMException: Input file must be bam file, not sam file.
    at org.broadinstitute.hellbender.tools.picard.sam.BuildBamIndex.doWork(BuildBamIndex.java:101)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:102)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:155)
    at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgram.instanceMain(PicardCommandLineProgram.java:61)
    at org.broadinstitute.hellbender.Main.instanceMain(Main.java:67)
    at org.broadinstitute.hellbender.Main.main(Main.java:82)
```

desired outcome: message that using files that are not in BAM format is not supported. No exception!

**Comment by droazen** [comment]
Closing as obsolete
