### ISSUE TITLE
./gatk-launch CountVariantsSpark --variant not reading gz vcf

### ISSUE THREAD

**Issue by tushu1232** [broadinstitute/gatk#1815]
11:05:38.056 INFO  CountVariantsSpark - Shutting down engine
[May 12, 2016 11:05:38 AM AST] org.broadinstitute.hellbender.tools.spark.pipelines.CountVariantsSpark done. Elapsed time: 0.08 minutes.
Runtime.totalMemory()=3114270720
htsjdk.tribble.TribbleException: Input stream does not contain a BCF encoded file; BCF magic header info not found, at record 0 with position 0:
	at htsjdk.variant.bcf2.BCF2Codec.error(BCF2Codec.java:492)
	at htsjdk.variant.bcf2.BCF2Codec.readHeader(BCF2Codec.java:153)
	at org.seqdoop.hadoop_bam.BCFSplitGuesser.<init>(BCFSplitGuesser.java:109)
	at org.seqdoop.hadoop_bam.BCFSplitGuesser.<init>(BCFSplitGuesser.java:89)
	at org.seqdoop.hadoop_bam.VCFInputFormat.addGuessedSplits(VCFInputFormat.java:254)
	at org.seqdoop.hadoop_bam.VCFInputFormat.fixBCFSplits(VCFInputFormat.java:242)
	at org.seqdoop.hadoop_bam.VCFInputFormat.getSplits(VCFInputFormat.java:221)
	at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:95)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1910)
	at org.apache.spark.rdd.RDD.count(RDD.scala:1121)
	at org.apache.spark.api.java.JavaRDDLike$class.count(JavaRDDLike.scala:445)
	at org.apache.spark.api.java.AbstractJavaRDDLike.count(JavaRDDLike.scala:47)
	at org.broadinstitute.hellbender.tools.spark.pipelines.CountVariantsSpark.runTool(CountVariantsSpark.java:39)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:313)
	at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:102)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:155)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:174)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:69)
	at org.broadinstitute.hellbender.Main.main(Main.java:84)

**Comment by akiezun** [comment]
This is a known limitation - blocked by https://github.com/broadinstitute/gatk/issues/1650
Will be resolved soon, when the new version of hadoop-bam is created

**Comment by akiezun** [comment]
@tushu1232 can you retry on the latest master? It should work now

**Comment by tushu1232** [comment]
Thanks Adam the file seems to be reading the zipped vcf file.
Thanks

Tushar B Pathare
High Performance Computing (HPC) Administrator
General Parallel File System
Scientific Computing
Bioinformatics Division
Research

Sidra Medical and Research Centre
Sidra OPC Building
PO Box 26999  |  Doha, Qatar
Near QNCC,5th Floor
Office 4003 3333 ext 37443 | M +974 74793547
tpathare@sidra.org<mailto:tpathare@sidra.org> | www.sidra.org<http://www.sidra.org/>

[cid:B44BCED3-0B3F-40A9-B1D5-31EB5FA1A726]

Follow us on:
[cid:EA30C7A2-88E3-4601-B54A-0AB32237D76F]<https://www.facebook.com/SidraMedicalAndResearchCenter>

[cid:A3C013FB-FC00-44E5-BB4A-F6BBE83393FD]<https://twitter.com/sidra>

[cid:F96B6BE9-8375-4FBC-98A0-F37E2C154AB5]<https://www.linkedin.com/company/sidra-medical-and-research-center>

[cid:C2E7A17B-1BC3-4FE4-AC2E-68CFC411450D]<https://www.instagram.com/sidramedicalandresearchcenter/>

[cid:6C6F39A4-C399-4742-8258-02A135D6E920]<https://www.youtube.com/user/SidraMedical>


[cid:6218F7A6-934F-492F-97F4-9CBACB33003F]

**Comment by akiezun** [comment]
I'm closing then. @tushu1232 says it works now.
