### ISSUE TITLE
ExampleReadWalkerWithVariants blows up 

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1983]
```
./gatk-launch ExampleReadWalkerWithVariants -I src/test/resources/org/broadinstitute/hellbender/engine/reads_data_source_test1.bam  -V ./src/test/resources/org/broadinstitute/hellbender/engine/example_variants.vcf
```

blows up 

```
htsjdk.tribble.TribbleException: Line 12: there aren't enough columns for line 4 (we expected 9 tokens, and saw 1 ), for input source: /Users/akiezun/IdeaProjects/gatk/./src/test/resources/org/broadinstitute/hellbender/engine/example_variants.vcf
    at htsjdk.variant.vcf.AbstractVCFCodec.decodeLine(AbstractVCFCodec.java:276)
    at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:257)
    at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:60)
    at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:74)
    at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:36)
    at htsjdk.tribble.TribbleIndexedFeatureReader$QueryIterator.readNextRecord(TribbleIndexedFeatureReader.java:472)
    at htsjdk.tribble.TribbleIndexedFeatureReader$QueryIterator.next(TribbleIndexedFeatureReader.java:428)
    at htsjdk.tribble.TribbleIndexedFeatureReader$QueryIterator.next(TribbleIndexedFeatureReader.java:396)
    at org.broadinstitute.hellbender.engine.FeatureCache.fill(FeatureCache.java:141)
    at org.broadinstitute.hellbender.engine.FeatureDataSource.refillQueryCache(FeatureDataSource.java:334)
    at org.broadinstitute.hellbender.engine.FeatureDataSource.queryAndPrefetch(FeatureDataSource.java:302)
    at org.broadinstitute.hellbender.engine.FeatureManager.getFeatures(FeatureManager.java:264)
    at org.broadinstitute.hellbender.engine.FeatureContext.getValues(FeatureContext.java:162)
    at org.broadinstitute.hellbender.engine.FeatureContext.getValues(FeatureContext.java:114)
    at org.broadinstitute.hellbender.engine.FeatureContext.getValues(FeatureContext.java:253)
    at org.broadinstitute.hellbender.tools.examples.ExampleReadWalkerWithVariants.apply(ExampleReadWalkerWithVariants.java:71)
    at org.broadinstitute.hellbender.engine.ReadWalker.lambda$traverse$0(ReadWalker.java:80)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at org.broadinstitute.hellbender.engine.ReadWalker.traverse(ReadWalker.java:78)
    at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:508)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:108)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:166)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:185)
    at org.broadinstitute.hellbender.Main.instanceMain(Main.java:76)
    at org.broadinstitute.hellbender.Main.main(Main.java:92)
```

**Comment by droazen** [comment]
Let's see if this is still an issue for beta

**Comment by droazen** [comment]
Closing as invalid -- this was a problem with the `example_variants.vcf` file, which is now removed.
