### ISSUE TITLE
TaggedInputFileArgument needs to be Serializable - or gatk-protected fails

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#2003]
really strange that public tests on spark dont catch this

```
Gradle suite > Gradle test > org.broadinstitute.hellbender.tools.genome.SparkGenomeReadCountsIntegrationTest.testSparkGenomeReadCounts FAILED
    org.apache.spark.SparkException: Task not serializable
        at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:304)
        at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:294)
        at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:122)
        at org.apache.spark.SparkContext.clean(SparkContext.scala:2055)
        at org.apache.spark.rdd.RDD$$anonfun$map$1.apply(RDD.scala:324)
        at org.apache.spark.rdd.RDD$$anonfun$map$1.apply(RDD.scala:323)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
        at org.apache.spark.rdd.RDD.map(RDD.scala:323)
        at org.apache.spark.api.java.JavaRDDLike$class.map(JavaRDDLike.scala:96)
        at org.apache.spark.api.java.AbstractJavaRDDLike.map(JavaRDDLike.scala:46)
        at org.broadinstitute.hellbender.tools.genome.SparkGenomeReadCounts.collectReads(SparkGenomeReadCounts.java:127)
        at org.broadinstitute.hellbender.tools.genome.SparkGenomeReadCounts.runTool(SparkGenomeReadCounts.java:207)
        at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:313)
        at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:108)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:166)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:185)
        at org.broadinstitute.hellbender.Main.instanceMain(Main.java:76)
        at org.broadinstitute.hellbender.Main.instanceMain(Main.java:83)
        at org.broadinstitute.hellbender.CommandLineProgramTest.runCommandLine(CommandLineProgramTest.java:76)
        at org.broadinstitute.hellbender.CommandLineProgramTest.runCommandLine(CommandLineProgramTest.java:80)
        at org.broadinstitute.hellbender.tools.genome.SparkGenomeReadCountsIntegrationTest.testSparkGenomeReadCounts(SparkGenomeReadCountsIntegrationTest.java:28)

        Caused by:
        java.io.NotSerializableException: org.broadinstitute.hellbender.engine.TaggedInputFileArgument
        Serialization stack:
        	- object not serializable (class: org.broadinstitute.hellbender.engine.TaggedInputFileArgument, value: /home/travis/build/broadinstitute/gatk-protected/src/test/resources/org/broadinstitute/hellbender/tools/genome/HCC1143_chr3_1K_11K.tiny.bam)
        	- writeObject data (class: java.util.ArrayList)
        	- object (class java.util.ArrayList, [/home/travis/build/broadinstitute/gatk-protected/src/test/resources/org/broadinstitute/hellbender/tools/genome/HCC1143_chr3_1K_11K.tiny.bam])
        	- field (class: org.broadinstitute.hellbender.cmdline.argumentcollections.OptionalReadInputArgumentCollection, name: readInputs, type: interface java.util.List)
        	- object (class org.broadinstitute.hellbender.cmdline.argumentcollections.OptionalReadInputArgumentCollection, org.broadinstitute.hellbender.cmdline.argumentcollections.OptionalReadInputArgumentCollection@21d212c8)
        	- field (class: org.broadinstitute.hellbender.engine.spark.GATKSparkTool, name: readArguments, type: class org.broadinstitute.hellbender.cmdline.argumentcollections.ReadInputArgumentCollection)
        	- object (class org.broadinstitute.hellbender.tools.genome.SparkGenomeReadCounts, org.broadinstitute.hellbender.tools.genome.SparkGenomeReadCounts@5aef1838)
        	- element of array (index: 0)
        	- array (class [Ljava.lang.Object;, size 2)
        	- field (class: java.lang.invoke.SerializedLambda, name: capturedArgs, type: class [Ljava.lang.Object;)
        	- object (class java.lang.invoke.SerializedLambda, SerializedLambda[capturingClass=class org.broadinstitute.hellbender.tools.genome.SparkGenomeReadCounts, functionalInterfaceMethod=org/apache/spark/api/java/function/Function.call:(Ljava/lang/Object;)Ljava/lang/Object;, implementation=invokeSpecial org/broadinstitute/hellbender/tools/genome/SparkGenomeReadCounts.lambda$collectReads$24c02dc7$2:(Lhtsjdk/samtools/SAMSequenceDictionary;Lorg/broadinstitute/hellbender/utils/read/GATKRead;)Lorg/broadinstitute/hellbender/utils/SimpleInterval;, instantiatedMethodType=(Lorg/broadinstitute/hellbender/utils/read/GATKRead;)Lorg/broadinstitute/hellbender/utils/SimpleInterval;, numCaptured=2])
        	- writeReplace data (class: java.lang.invoke.SerializedLambda)
        	- object (class org.broadinstitute.hellbender.tools.genome.SparkGenomeReadCounts$$Lambda$1140/887035829, org.broadinstitute.hellbender.tools.genome.SparkGenomeReadCounts$$Lambda$1140/887035829@1a912c1e)
        	- field (class: org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction$1, name: fun$1, type: interface org.apache.spark.api.java.function.Function)
        	- object (class org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction$1, <function1>)
            at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
            at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:47)
            at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:101)
            at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:301)
            ... 23 more
```

**Comment by akiezun** [comment]
actually, this was a bug in SparkGenomeReadCounts in gatk-protected - it was using closures not optimally and ended up pulling the whole SparkGenomeReadCounts through serialization. Fixed by making it not serialize the whole class: 
https://github.com/broadinstitute/gatk-protected/pull/610/commits/283a519efc99b117a846e7c8cf02110f5406b3cb
