### ISSUE TITLE
GCS provider ID must be specified even if not using GCS

### ISSUE THREAD

**Issue by tomwhite** [broadinstitute/gatk#2110]
The presence of gcloud-java-nio on the classpath prevents other providers being used if the GCS provider ID has not been specified (e.g. by setting `GOOGLE_APPLICATION_CREDENTIALS`).

Here's an example test case: https://github.com/broadinstitute/gatk/commit/8b217f82352ceb55d21d7a5236e879818910d9c9

and the stacktrace:

```
java.util.ServiceConfigurationError: java.nio.file.spi.FileSystemProvider: Provider com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at java.nio.file.spi.FileSystemProvider.loadInstalledProviders(FileSystemProvider.java:119)
        at java.nio.file.spi.FileSystemProvider.access$000(FileSystemProvider.java:77)
        at java.nio.file.spi.FileSystemProvider$1.run(FileSystemProvider.java:169)
        at java.nio.file.spi.FileSystemProvider$1.run(FileSystemProvider.java:166)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.nio.file.spi.FileSystemProvider.installedProviders(FileSystemProvider.java:166)
        at java.nio.file.Paths.get(Paths.java:141)
        at org.broadinstitute.hellbender.engine.spark.datasources.NioProviderExceptionUnitTest.test(NioProviderExceptionUnitTest.java:12)

        Caused by:
        java.lang.IllegalArgumentException: A project ID is required for this service but could not be determined from the builder or the environment.  Please set a project ID using the builder.
            at shaded.cloud-nio.com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
            at com.google.cloud.ServiceOptions.<init>(ServiceOptions.java:208)
            at com.google.cloud.HttpServiceOptions.<init>(HttpServiceOptions.java:153)
            at com.google.cloud.storage.StorageOptions.<init>(StorageOptions.java:69)
            at com.google.cloud.storage.StorageOptions.<init>(StorageOptions.java:27)
            at com.google.cloud.storage.StorageOptions$Builder.build(StorageOptions.java:64)
            at com.google.cloud.storage.StorageOptions.defaultInstance(StorageOptions.java:91)
            at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.<init>(CloudStorageFileSystemProvider.java:141)
            at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.<init>(CloudStorageFileSystemProvider.java:136)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
            at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
            at java.lang.Class.newInstance(Class.java:438)
            at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
            ... 10 more
```

**Comment by tomwhite** [comment]
@jean-philippe-martin do you think it would be possible to fix this? The workaround is to set `GOOGLE_APPLICATION_CREDENTIALS`, but it would be preferable to have gcloud-java-nio fail when a `gs://` path is specified and the credentials are not set, rather than when the filesystem providers are loaded.

**Comment by jean-philippe-martin** [comment]
Intriguing. Thanks for the good example.

To get around this it looks like we need to update NIO to allow it to be in a special "broken" state where the CloudStorageFileSystemProvider allows itself to be constructed even without credentials, failing later when we ask it to do anything.

I think this is possible, but the change would have to be in gcloud-java-nio itself. The additional state is a bit counter-intuitive (usually allocation-is-initialization) but it seems worthwhile in this case. I'll get the ball rolling over at gcloud-java-nio.

**Comment by tomwhite** [comment]
Thanks @jean-philippe-martin.

**Comment by jean-philippe-martin** [comment]
@tomwhite the fix is in. We only have to use the workaround until the next gcloud-java release (0.2.8, probably).

**Comment by tomwhite** [comment]
Great! Thanks for addressing this so quickly @jean-philippe-martin.

**Comment by jean-philippe-martin** [comment]
You're most welcome @tomwhite ! It looks like 0.2.8 is out now, let me know how it works for you!
