### ISSUE TITLE
reading a headerless sam file fails

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2119]
Trying to read a headerless sam file fails with:

```
java.lang.IllegalArgumentException: unknown SAM format, cannot create RecordReader: file:/Users/louisb/Workspace/gatk/test.sam
    at org.seqdoop.hadoop_bam.AnySAMInputFormat.createRecordReader(AnySAMInputFormat.java:186)
    at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:156)
    at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:129)
    at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:64)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)

      ...
```

It fails because of some problems in `AnySAMInputFormat`.

**Comment by lbergelson** [comment]
I think this is fixed but we need to test it.
