### ISSUE TITLE
GATK4 PrintReadsSpark failing on standalone cluster with 1 worker using spark1.6.2

### ISSUE THREAD

**Issue by tushu1232** [broadinstitute/gatk#2268]
+ blaunch -no-wait -z hpcgenomicn24 /spark-1.6.2-bin-hadoop2.6//bin/spark-class org.apache.spark.deploy.worker.Worker spark://hpcgenomicn24:6311 -c 16
+ echo --conf spark.executor.memory=2g --conf spark.driver.memory=2g --conf spark.local.dir=/gpfs/ngsdata/sparkcache --class org.broadinstitute.hellbender.Main /gpfs/software/spark/gatk4onspark.jar PrintReadsSpark -I /gpfs/home/tpathare/gatk/src/test/resources/NA12878.chr17_69k_70k.dictFix.bam -O /gpfs/home/tpathare/test/
--conf spark.executor.memory=2g --conf spark.driver.memory=2g --conf spark.local.dir=/gpfs/ngsdata/sparkcache --class org.broadinstitute.hellbender.Main /gpfs/software/spark/gatk4onspark.jar PrintReadsSpark -I /gpfs/home/tpathare/gatk/src/test/resources/NA12878.chr17_69k_70k.dictFix.bam -O /gpfs/home/tpathare/test/
+ /spark-1.6.2-bin-hadoop2.6//bin/spark-submit --master spark://hpcgenomicn24:6311 --conf spark.executor.memory=2g --conf spark.driver.memory=2g --conf spark.local.dir=/gpfs/ngsdata/sparkcache --class org.broadinstitute.hellbender.Main /gpfs/software/spark/gatk4onspark.jar PrintReadsSpark -I /gpfs/home/tpathare/gatk/src/test/resources/NA12878.chr17_69k_70k.dictFix.bam -O /gpfs/home/tpathare/test/
23:25:07.475 INFO  IntelGKLUtils - Trying to load Intel GKL library from:
	jar:file:/gpfs/software/spark/gatk4onspark.jar!/com/intel/gkl/native/libIntelGKL.so
23:25:07.552 INFO  IntelGKLUtils - Intel GKL library loaded from classpath.
[November 16, 2016 11:25:07 PM AST] org.broadinstitute.hellbender.tools.spark.pipelines.PrintReadsSpark  --output /gpfs/home/tpathare/test/ --input /gpfs/home/tpathare/gatk/src/test/resources/NA12878.chr17_69k_70k.dictFix.bam  --readValidationStringency SILENT --interval_set_rule UNION --interval_padding 0 --interval_exclusion_padding 0 --bamPartitionSize 0 --disableSequenceDictionaryValidation false --shardedOutput false --numReducers 0 --sparkMaster local[*] --help false --version false --verbosity INFO --QUIET false --use_jdk_deflater false --disableAllReadFilters false
[November 16, 2016 11:25:07 PM AST] Executing as root@hpcgenomicn24 on Linux 2.6.32-358.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_66-b17; Version: Version:4.alpha.2-98-g8fa5092-SNAPSHOT
23:25:07.556 INFO  PrintReadsSpark - Defaults.BUFFER_SIZE : 131072
23:25:07.556 INFO  PrintReadsSpark - Defaults.COMPRESSION_LEVEL : 5
23:25:07.556 INFO  PrintReadsSpark - Defaults.CREATE_INDEX : false
23:25:07.556 INFO  PrintReadsSpark - Defaults.CREATE_MD5 : false
23:25:07.556 INFO  PrintReadsSpark - Defaults.CUSTOM_READER_FACTORY : 
23:25:07.556 INFO  PrintReadsSpark - Defaults.EBI_REFERENCE_SERVICE_URL_MASK : http://www.ebi.ac.uk/ena/cram/md5/%s
23:25:07.557 INFO  PrintReadsSpark - Defaults.NON_ZERO_BUFFER_SIZE : 131072
23:25:07.557 INFO  PrintReadsSpark - Defaults.REFERENCE_FASTA : null
23:25:07.557 INFO  PrintReadsSpark - Defaults.SAM_FLAG_FIELD_FORMAT : DECIMAL
23:25:07.557 INFO  PrintReadsSpark - Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
23:25:07.557 INFO  PrintReadsSpark - Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : false
23:25:07.557 INFO  PrintReadsSpark - Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
23:25:07.557 INFO  PrintReadsSpark - Defaults.USE_CRAM_REF_DOWNLOAD : false
23:25:07.557 INFO  PrintReadsSpark - Deflater IntelDeflater
23:25:07.557 INFO  PrintReadsSpark - Initializing engine
23:25:07.557 INFO  PrintReadsSpark - Done initializing engine
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
16/11/16 23:25:07 INFO SparkContext: Running Spark version 1.6.2
16/11/16 23:25:07 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/11/16 23:25:07 WARN SparkConf: In Spark 1.0 and later spark.local.dir will be overridden by the value set by the cluster manager (via SPARK_LOCAL_DIRS in mesos/standalone and LOCAL_DIRS in YARN).
16/11/16 23:25:07 INFO SecurityManager: Changing view acls to: root
16/11/16 23:25:07 INFO SecurityManager: Changing modify acls to: root
16/11/16 23:25:07 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(root); users with modify permissions: Set(root)
16/11/16 23:25:08 INFO Utils: Successfully started service 'sparkDriver' on port 53746.
16/11/16 23:25:08 INFO Slf4jLogger: Slf4jLogger started
16/11/16 23:25:08 INFO Remoting: Starting remoting
16/11/16 23:25:08 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@172.32.65.22:33197]
16/11/16 23:25:08 INFO Utils: Successfully started service 'sparkDriverActorSystem' on port 33197.
16/11/16 23:25:08 INFO SparkEnv: Registering MapOutputTracker
16/11/16 23:25:08 INFO SparkEnv: Registering BlockManagerMaster
16/11/16 23:25:08 INFO DiskBlockManager: Created local directory at /gpfs/ngsdata/sparkcache/blockmgr-1cb5e4dd-5f50-43a8-b1ca-3d5df9aa6f1c
16/11/16 23:25:08 INFO MemoryStore: MemoryStore started with capacity 1247.3 MB
16/11/16 23:25:08 INFO SparkEnv: Registering OutputCommitCoordinator
16/11/16 23:25:08 INFO Utils: Successfully started service 'SparkUI' on port 4040.
16/11/16 23:25:08 INFO SparkUI: Started SparkUI at http://172.32.65.22:4040
16/11/16 23:25:08 INFO HttpFileServer: HTTP File server directory is /gpfs/ngsdata/sparkcache/spark-29e7cb29-06dd-4145-ad9a-aa75971badb8/httpd-7370bdc2-eb41-46d1-9512-2f387b972cac
16/11/16 23:25:08 INFO HttpServer: Starting HTTP Server
16/11/16 23:25:08 INFO Utils: Successfully started service 'HTTP file server' on port 42517.
16/11/16 23:25:09 INFO SparkContext: Added JAR file:/gpfs/software/spark/gatk4onspark.jar at http://172.32.65.22:42517/jars/gatk4onspark.jar with timestamp 1479327909214
16/11/16 23:25:09 INFO Executor: Starting executor ID driver on host localhost
16/11/16 23:25:09 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40833.
16/11/16 23:25:09 INFO NettyBlockTransferService: Server created on 40833
16/11/16 23:25:09 INFO BlockManagerMaster: Trying to register BlockManager
16/11/16 23:25:09 INFO BlockManagerMasterEndpoint: Registering block manager localhost:40833 with 1247.3 MB RAM, BlockManagerId(driver, localhost, 40833)
16/11/16 23:25:09 INFO BlockManagerMaster: Registered BlockManager
16/11/16 23:25:09 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 209.5 KB, free 209.5 KB)
16/11/16 23:25:10 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 20.1 KB, free 229.6 KB)
16/11/16 23:25:10 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on localhost:40833 (size: 20.1 KB, free: 1247.2 MB)
16/11/16 23:25:10 INFO SparkContext: Created broadcast 0 from newAPIHadoopFile at ReadsSparkSource.java:104
16/11/16 23:25:10 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 10.5 KB, free 240.1 KB)
16/11/16 23:25:10 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 1540.0 B, free 241.7 KB)
16/11/16 23:25:10 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on localhost:40833 (size: 1540.0 B, free: 1247.2 MB)
16/11/16 23:25:10 INFO SparkContext: Created broadcast 1 from broadcast at ReadsSparkSink.java:194
16/11/16 23:25:10 INFO deprecation: mapred.output.dir is deprecated. Instead, use mapreduce.output.fileoutputformat.outputdir
16/11/16 23:25:10 INFO SparkContext: Starting job: saveAsNewAPIHadoopFile at ReadsSparkSink.java:202
16/11/16 23:25:10 INFO FileInputFormat: Total input paths to process : 1
16/11/16 23:25:10 INFO DAGScheduler: Registering RDD 5 (mapToPair at ReadsSparkSink.java:236)
16/11/16 23:25:10 INFO DAGScheduler: Got job 0 (saveAsNewAPIHadoopFile at ReadsSparkSink.java:202) with 1 output partitions
16/11/16 23:25:10 INFO DAGScheduler: Final stage: ResultStage 1 (saveAsNewAPIHadoopFile at ReadsSparkSink.java:202)
16/11/16 23:25:10 INFO DAGScheduler: Parents of final stage: List(ShuffleMapStage 0)
16/11/16 23:25:10 INFO DAGScheduler: Missing parents: List(ShuffleMapStage 0)
16/11/16 23:25:10 INFO DAGScheduler: Submitting ShuffleMapStage 0 (MapPartitionsRDD[5] at mapToPair at ReadsSparkSink.java:236), which has no missing parents
16/11/16 23:25:10 INFO MemoryStore: Block broadcast_2 stored as values in memory (estimated size 13.0 KB, free 254.7 KB)
16/11/16 23:25:10 INFO MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 6.1 KB, free 260.8 KB)
16/11/16 23:25:10 INFO BlockManagerInfo: Added broadcast_2_piece0 in memory on localhost:40833 (size: 6.1 KB, free: 1247.2 MB)
16/11/16 23:25:10 INFO SparkContext: Created broadcast 2 from broadcast at DAGScheduler.scala:1006
16/11/16 23:25:10 INFO DAGScheduler: Submitting 1 missing tasks from ShuffleMapStage 0 (MapPartitionsRDD[5] at mapToPair at ReadsSparkSink.java:236)
16/11/16 23:25:10 INFO TaskSchedulerImpl: Adding task set 0.0 with 1 tasks
16/11/16 23:25:10 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, localhost, partition 0,PROCESS_LOCAL, 2246 bytes)
16/11/16 23:25:10 INFO Executor: Running task 0.0 in stage 0.0 (TID 0)
16/11/16 23:25:10 INFO Executor: Fetching http://172.32.65.22:42517/jars/gatk4onspark.jar with timestamp 1479327909214
16/11/16 23:25:10 INFO Utils: Fetching http://172.32.65.22:42517/jars/gatk4onspark.jar to /gpfs/ngsdata/sparkcache/spark-29e7cb29-06dd-4145-ad9a-aa75971badb8/userFiles-0cb55499-32ca-46c0-990a-357d578c76c6/fetchFileTemp1824632764181339560.tmp
16/11/16 23:25:10 INFO Executor: Adding file:/gpfs/ngsdata/sparkcache/spark-29e7cb29-06dd-4145-ad9a-aa75971badb8/userFiles-0cb55499-32ca-46c0-990a-357d578c76c6/gatk4onspark.jar to class loader
16/11/16 23:25:11 INFO NewHadoopRDD: Input split: file:/gpfs/home/tpathare/gatk/src/test/resources/NA12878.chr17_69k_70k.dictFix.bam:1632-3770875903
16/11/16 23:25:11 INFO Executor: Finished task 0.0 in stage 0.0 (TID 0). 2182 bytes result sent to driver
16/11/16 23:25:11 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 544 ms on localhost (1/1)
16/11/16 23:25:11 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool 
16/11/16 23:25:11 INFO DAGScheduler: ShuffleMapStage 0 (mapToPair at ReadsSparkSink.java:236) finished in 0.562 s
16/11/16 23:25:11 INFO DAGScheduler: looking for newly runnable stages
16/11/16 23:25:11 INFO DAGScheduler: running: Set()
16/11/16 23:25:11 INFO DAGScheduler: waiting: Set(ResultStage 1)
16/11/16 23:25:11 INFO DAGScheduler: failed: Set()
16/11/16 23:25:11 INFO DAGScheduler: Submitting ResultStage 1 (MapPartitionsRDD[9] at mapToPair at ReadsSparkSink.java:273), which has no missing parents
16/11/16 23:25:11 INFO MemoryStore: Block broadcast_3 stored as values in memory (estimated size 71.1 KB, free 331.9 KB)
16/11/16 23:25:11 INFO MemoryStore: Block broadcast_3_piece0 stored as bytes in memory (estimated size 26.0 KB, free 357.9 KB)
16/11/16 23:25:11 INFO BlockManagerInfo: Added broadcast_3_piece0 in memory on localhost:40833 (size: 26.0 KB, free: 1247.2 MB)
16/11/16 23:25:11 INFO SparkContext: Created broadcast 3 from broadcast at DAGScheduler.scala:1006
16/11/16 23:25:11 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 1 (MapPartitionsRDD[9] at mapToPair at ReadsSparkSink.java:273)
16/11/16 23:25:11 INFO TaskSchedulerImpl: Adding task set 1.0 with 1 tasks
16/11/16 23:25:11 INFO TaskSetManager: Starting task 0.0 in stage 1.0 (TID 1, localhost, partition 0,NODE_LOCAL, 1951 bytes)
16/11/16 23:25:11 INFO Executor: Running task 0.0 in stage 1.0 (TID 1)
16/11/16 23:25:11 INFO ShuffleBlockFetcherIterator: Getting 1 non-empty blocks out of 1 blocks
16/11/16 23:25:11 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 3 ms
16/11/16 23:25:11 ERROR Executor: Exception in task 0.0 in stage 1.0 (TID 1)
java.lang.AbstractMethodError: org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink$$Lambda$78/237665701.call(Ljava/lang/Object;)Ljava/lang/Iterable;
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:159)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:159)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
16/11/16 23:25:11 ERROR SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Executor task launch worker-0,5,main]
java.lang.AbstractMethodError: org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink$$Lambda$78/237665701.call(Ljava/lang/Object;)Ljava/lang/Iterable;
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:159)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:159)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
16/11/16 23:25:11 INFO SparkContext: Invoking stop() from shutdown hook
16/11/16 23:25:11 WARN TaskSetManager: Lost task 0.0 in stage 1.0 (TID 1, localhost): java.lang.AbstractMethodError: org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink$$Lambda$78/237665701.call(Ljava/lang/Object;)Ljava/lang/Iterable;
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:159)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:159)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

16/11/16 23:25:11 ERROR TaskSetManager: Task 0 in stage 1.0 failed 1 times; aborting job
16/11/16 23:25:11 INFO TaskSchedulerImpl: Removed TaskSet 1.0, whose tasks have all completed, from pool 
16/11/16 23:25:11 INFO TaskSchedulerImpl: Cancelling stage 1
16/11/16 23:25:11 INFO DAGScheduler: ResultStage 1 (saveAsNewAPIHadoopFile at ReadsSparkSink.java:202) failed in 0.276 s
16/11/16 23:25:11 INFO DAGScheduler: Job 0 failed: saveAsNewAPIHadoopFile at ReadsSparkSink.java:202, took 1.029776 s
16/11/16 23:25:11 INFO SparkContext: SparkContext already stopped.
[November 16, 2016 11:25:11 PM AST] org.broadinstitute.hellbender.tools.spark.pipelines.PrintReadsSpark done. Elapsed time: 0.07 minutes.
Runtime.totalMemory()=2058354688
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1.0 (TID 1, localhost): java.lang.AbstractMethodError: org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink$$Lambda$78/237665701.call(Ljava/lang/Object;)Ljava/lang/Iterable;
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:159)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:159)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1418)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1640)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1599)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1588)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:620)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1832)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1845)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1922)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply$mcV$sp(PairRDDFunctions.scala:1144)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply(PairRDDFunctions.scala:1074)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply(PairRDDFunctions.scala:1074)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopDataset(PairRDDFunctions.scala:1074)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply$mcV$sp(PairRDDFunctions.scala:994)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply(PairRDDFunctions.scala:985)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply(PairRDDFunctions.scala:985)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopFile(PairRDDFunctions.scala:985)
	at org.apache.spark.api.java.JavaPairRDD.saveAsNewAPIHadoopFile(JavaPairRDD.scala:800)
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink.saveAsShardedHadoopFiles(ReadsSparkSink.java:202)
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink.writeReadsSingle(ReadsSparkSink.java:229)
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink.writeReads(ReadsSparkSink.java:152)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.writeReads(GATKSparkTool.java:247)
	at org.broadinstitute.hellbender.tools.spark.pipelines.PrintReadsSpark.runTool(PrintReadsSpark.java:35)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:348)
	at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:109)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:167)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:186)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:95)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:102)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:115)
	at org.broadinstitute.hellbender.Main.main(Main.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.AbstractMethodError: org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink$$Lambda$78/237665701.call(Ljava/lang/Object;)Ljava/lang/Iterable;
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:159)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:159)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
16/11/16 23:25:11 INFO SparkUI: Stopped Spark web UI at http://172.32.65.22:4040
16/11/16 23:25:11 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
16/11/16 23:25:11 INFO MemoryStore: MemoryStore cleared
16/11/16 23:25:11 INFO BlockManager: BlockManager stopped
16/11/16 23:25:11 INFO BlockManagerMaster: BlockManagerMaster stopped
16/11/16 23:25:11 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
16/11/16 23:25:11 INFO SparkContext: Successfully stopped SparkContext
16/11/16 23:25:11 INFO ShutdownHookManager: Shutdown hook called
16/11/16 23:25:11 INFO ShutdownHookManager: Deleting directory /gpfs/ngsdata/sparkcache/spark-29e7cb29-06dd-4145-ad9a-aa75971badb8
16/11/16 23:25:11 INFO ShutdownHookManager: Deleting directory /gpfs/ngsdata/sparkcache/spark-29e7cb29-06dd-4145-ad9a-aa75971badb8/httpd-7370bdc2-eb41-46d1-9512-2f387b972cac
16/11/16 23:25:11 INFO RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.
+ /spark-1.6.2-bin-hadoop2.6//sbin/stop-master.sh

**Comment by lbergelson** [comment]
@tushu1232 GATK4 now requires spark 2.0
