### ISSUE TITLE
I am running sortsam and getting error  Exception in thread "main" java.lang.NoClassDefFoundError: org/xerial/snappy/LoadSnappy

### ISSUE THREAD

**Issue by tushu1232** [broadinstitute/gatk#2299]
[December 7, 2016 11:43:32 AM AST] Executing as root@hpc1 on Linux 2.6.32-358.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_66-b17; Version: Version:4.alpha.2-116-gdd7e19a-SNAPSHOT
11:43:32.131 INFO  SortSam - Defaults.BUFFER_SIZE : 131072
11:43:32.131 INFO  SortSam - Defaults.COMPRESSION_LEVEL : 5
11:43:32.131 INFO  SortSam - Defaults.CREATE_INDEX : false
11:43:32.131 INFO  SortSam - Defaults.CREATE_MD5 : false
11:43:32.131 INFO  SortSam - Defaults.CUSTOM_READER_FACTORY : 
11:43:32.131 INFO  SortSam - Defaults.EBI_REFERENCE_SERVICE_URL_MASK : http://www.ebi.ac.uk/ena/cram/md5/%s
11:43:32.131 INFO  SortSam - Defaults.NON_ZERO_BUFFER_SIZE : 131072
11:43:32.131 INFO  SortSam - Defaults.REFERENCE_FASTA : null
11:43:32.131 INFO  SortSam - Defaults.SAM_FLAG_FIELD_FORMAT : DECIMAL
11:43:32.131 INFO  SortSam - Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
11:43:32.131 INFO  SortSam - Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : false
11:43:32.131 INFO  SortSam - Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
11:43:32.131 INFO  SortSam - Defaults.USE_CRAM_REF_DOWNLOAD : false
11:43:32.131 INFO  SortSam - Deflater IntelDeflater
11:43:32.131 INFO  SortSam - Initializing engine
11:43:32.131 INFO  SortSam - Done initializing engine
11:43:42.134 INFO  SortSam - Shutting down engine
[December 7, 2016 11:43:42 AM AST] org.broadinstitute.hellbender.tools.picard.sam.SortSam done. Elapsed time: 0.17 minutes.
Runtime.totalMemory()=1890058240
Exception in thread "main" java.lang.NoClassDefFoundError: org/xerial/snappy/LoadSnappy
	at htsjdk.samtools.util.SnappyLoader.<init>(SnappyLoader.java:86)
	at htsjdk.samtools.util.SnappyLoader.<init>(SnappyLoader.java:52)
	at htsjdk.samtools.util.TempStreamFactory.getSnappyLoader(TempStreamFactory.java:42)
	at htsjdk.samtools.util.TempStreamFactory.wrapTempOutputStream(TempStreamFactory.java:74)
	at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:223)
	at htsjdk.samtools.util.SortingCollection.add(SortingCollection.java:166)
	at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:192)
	at org.broadinstitute.hellbender.tools.picard.sam.SortSam.doWork(SortSam.java:52)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:112)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:170)
	at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgram.instanceMain(PicardCommandLineProgram.java:62)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:96)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:103)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:116)
	at org.broadinstitute.hellbender.Main.main(Main.java:158)
Caused by: java.lang.ClassNotFoundException: org.xerial.snappy.LoadSnappy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more

**Comment by lbergelson** [comment]
closing this because it's identical to #2300 and I started answering that one first...

**Comment by tushu1232** [comment]
Hello @lbergelson I am running using spark submit and not the gate-launch command.
this is the command I executed 

software/spark/gatk4latest/gatk-launch SortSam --input BAM_BWA/SRR.sorted.bam --output hpcinfra/hadoop/test.bam --SORT_ORDER query name

[December 7, 2016 6:01:51 PM AST] Executing as root@hpc on Linux 2.6.32-358.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_66-b17; Version: Version:4.alpha.2-116-gdd7e19a-SNAPSHOT
18:01:51.712 INFO  SortSam - Defaults.BUFFER_SIZE : 131072
18:01:51.712 INFO  SortSam - Defaults.COMPRESSION_LEVEL : 5
18:01:51.712 INFO  SortSam - Defaults.CREATE_INDEX : false
18:01:51.712 INFO  SortSam - Defaults.CREATE_MD5 : false
18:01:51.712 INFO  SortSam - Defaults.CUSTOM_READER_FACTORY : 
18:01:51.712 INFO  SortSam - Defaults.EBI_REFERENCE_SERVICE_URL_MASK : http://www.ebi.ac.uk/ena/cram/md5/%s
18:01:51.712 INFO  SortSam - Defaults.NON_ZERO_BUFFER_SIZE : 131072
18:01:51.712 INFO  SortSam - Defaults.REFERENCE_FASTA : null
18:01:51.712 INFO  SortSam - Defaults.SAM_FLAG_FIELD_FORMAT : DECIMAL
18:01:51.713 INFO  SortSam - Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
18:01:51.713 INFO  SortSam - Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : false
18:01:51.713 INFO  SortSam - Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
18:01:51.713 INFO  SortSam - Defaults.USE_CRAM_REF_DOWNLOAD : false
18:01:51.713 INFO  SortSam - Deflater IntelDeflater
18:01:51.713 INFO  SortSam - Initializing engine
18:01:51.713 INFO  SortSam - Done initializing engine
18:02:01.512 INFO  SortSam - Shutting down engine
[December 7, 2016 6:02:01 PM AST] org.broadinstitute.hellbender.tools.picard.sam.SortSam done. Elapsed time: 0.16 minutes.
Runtime.totalMemory()=1911029760
Exception in thread "main" java.lang.NoClassDefFoundError: org/xerial/snappy/LoadSnappy
	at htsjdk.samtools.util.SnappyLoader.<init>(SnappyLoader.java:86)
	at htsjdk.samtools.util.SnappyLoader.<init>(SnappyLoader.java:52)
	at htsjdk.samtools.util.TempStreamFactory.getSnappyLoader(TempStreamFactory.java:42)
	at htsjdk.samtools.util.TempStreamFactory.wrapTempOutputStream(TempStreamFactory.java:74)
	at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:223)
	at htsjdk.samtools.util.SortingCollection.add(SortingCollection.java:166)
	at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:192)
	at org.broadinstitute.hellbender.tools.picard.sam.SortSam.doWork(SortSam.java:52)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:112)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:170)
	at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgram.instanceMain(PicardCommandLineProgram.java:62)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:96)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:103)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:116)
	at org.broadinstitute.hellbender.Main.main(Main.java:158)
Caused by: java.lang.ClassNotFoundException: org.xerial.snappy.LoadSnappy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
