### ISSUE TITLE
NPE when doing CollectArtifactSequencingMetrics

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#2351]
From Broad VM:
```
[January 20, 2017 9:07:57 AM EST] org.broadinstitute.hellbender.tools.picard.analysis.artifacts.CollectSequencingArtifactMetrics  --output HSCX1550T --input /dsde/working/lichtens/test_dl_oxoq/code/test_dl_oxoq/cromwell-executions/full_dl_ob_training/2c9b89c2-27ef-448a-b5af-1d090e76ada1/call-dl_ob_training/shard-25/dl_ob_training/00210f87-b7f5-4057-bb02-d3be31029996/call-CollectSequencingArtifactMetrics/inputs/seq/picard_aggregation/C802/HSCX1550T/v3/HSCX1550T.bam --VALIDATION_STRINGENCY SILENT --reference /dsde/working/lichtens/test_dl_oxoq/code/test_dl_oxoq/cromwell-executions/full_dl_ob_training/2c9b89c2-27ef-448a-b5af-1d090e76ada1/call-dl_ob_training/shard-25/dl_ob_training/00210f87-b7f5-4057-bb02-d3be31029996/call-CollectSequencingArtifactMetrics/inputs/seq/references/Homo_sapiens_assembly19/v1/Homo_sapiens_assembly19.fasta  --MINIMUM_QUALITY_SCORE 20 --MINIMUM_MAPPING_QUALITY 30 --MINIMUM_INSERT_SIZE 60 --MAXIMUM_INSERT_SIZE 600 --INCLUDE_UNPAIRED false --TANDEM_READS false --USE_OQ true --CONTEXT_SIZE 1 --ASSUME_SORTED true --STOP_AFTER 0 --COMPRESSION_LEVEL 5 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --help false --version false --verbosity INFO --QUIET false --use_jdk_deflater false
[January 20, 2017 9:07:57 AM EST] Executing as lichtens@node1691.broadinstitute.org on Linux 2.6.32-642.6.2.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_92-b14; Version: Version:null
WARNING 2017-01-20 09:07:57     SamFiles        The index file /seq/fargo_picard_aggregation/C802/HSCX1550T/v3/HSCX1550T.bai was found by resolving the canonical path of a symlink: /dsde/working/lichtens/test_dl_oxoq/code/test_dl_oxoq/cromwell-executions/full_dl_ob_training/2c9b89c2-27ef-448a-b5af-1d090e76ada1/call-dl_ob_training/shard-25/dl_ob_training/00210f87-b7f5-4057-bb02-d3be31029996/call-CollectSequencingArtifactMetrics/inputs/seq/picard_aggregation/C802/HSCX1550T/v3/HSCX1550T.bam -> /seq/fargo_picard_aggregation/C802/HSCX1550T/v3/HSCX1550T.bam
[January 20, 2017 9:23:02 AM EST] org.broadinstitute.hellbender.tools.picard.analysis.artifacts.CollectSequencingArtifactMetrics done. Elapsed time: 15.09 minutes.
Runtime.totalMemory()=4831313920
java.lang.NullPointerException
        at org.broadinstitute.hellbender.tools.picard.analysis.artifacts.ContextAccumulator$AlignmentAccumulator.access$100(ContextAccumulator.java:113)
        at org.broadinstitute.hellbender.tools.picard.analysis.artifacts.ContextAccumulator.countRecord(ContextAccumulator.java:39)
        at org.broadinstitute.hellbender.tools.picard.analysis.artifacts.ArtifactCounter.countRecord(ArtifactCounter.java:82)
        at org.broadinstitute.hellbender.tools.picard.analysis.artifacts.CollectSequencingArtifactMetrics.acceptRead(CollectSequencingArtifactMetrics.java:228)
        at org.broadinstitute.hellbender.tools.picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:114)
        at org.broadinstitute.hellbender.tools.picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:53)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:112)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:170)
        at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgram.instanceMain(PicardCommandLineProgram.java:62)
        at org.broadinstitute.hellbender.Main.instanceMain(Main.java:96)
        at org.broadinstitute.hellbender.Main.instanceMain(Main.java:103)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:116)
        at org.broadinstitute.hellbender.Main.main(Main.java:158)

```

**Comment by sooheelee** [comment]
The error is not with CollectArtifactSequencingMetrics but with GATK's FilterByOrientationBias.

**Comment by davidbenjamin** [comment]
Moot.
