### ISSUE TITLE
Authentication to access private GCS buckets

### ISSUE THREAD

**Issue by mwalker174** [broadinstitute/gatk#2394]
There currently is no way to access files in a GCS bucket that is not public. I will need this feature in the near future to analyze sensitive data. 

Just discussed this with @lbergelson, and it sounds like this is something that is not a ton of work but has just been on the back-burner for a while.

**Comment by lbergelson** [comment]
@mwalker174 Would you mind posting the stack trace you had here as well?

**Comment by mwalker174** [comment]
markw@WMC9F-819:~/IdeaProjects/gatk$ ./gatk-launch PrintReadsSpark -I gs://mw-pathseq-test/hs37d5cs.reads.sorted.bam -O hs37d5cs.reads.txt --apiKey XXXXXXXXXXXXXXXXXXXX --verbosity DEBUG -- --sparkRunner GCS --cluster mw-test --project broad-dsde-methods
Using GATK jar /Users/markw/IdeaProjects/gatk/build/libs/gatk-package-4.alpha.2-157-g7d7c5ec-SNAPSHOT-spark.jar
jar caching is disabled because GATK_GCS_STAGING is not set

please set GATK_GCS_STAGING to a bucket you have write access too in order to enable jar caching
add the following line to you .bashrc or equivalent startup script

    export GATK_GCS_STAGING=gs://<my_bucket>/

Replacing spark-submit style args with dataproc style args

--cluster mw-test --project broad-dsde-methods -> --cluster mw-test --project broad-dsde-methods --properties spark.kryoserializer.buffer.max=512m,spark.driver.maxResultSize=0,spark.driver.userClassPathFirst=true,spark.io.compression.codec=lzf,spark.yarn.executor.memoryOverhead=600,spark.driver.extraJavaOptions=-Dsamjdk.compression_level=1 -DGATK_STACKTRACE_ON_USER_EXCEPTION=true ,spark.executor.extraJavaOptions=-Dsamjdk.compression_level=1 -DGATK_STACKTRACE_ON_USER_EXCEPTION=true

Running:
    gcloud dataproc jobs submit spark --cluster mw-test --project broad-dsde-methods --properties spark.kryoserializer.buffer.max=512m,spark.driver.maxResultSize=0,spark.driver.userClassPathFirst=true,spark.io.compression.codec=lzf,spark.yarn.executor.memoryOverhead=600,spark.driver.extraJavaOptions=-Dsamjdk.compression_level=1 -DGATK_STACKTRACE_ON_USER_EXCEPTION=true ,spark.executor.extraJavaOptions=-Dsamjdk.compression_level=1 -DGATK_STACKTRACE_ON_USER_EXCEPTION=true  --jar /Users/markw/IdeaProjects/gatk/build/libs/gatk-package-4.alpha.2-157-g7d7c5ec-SNAPSHOT-spark.jar -- PrintReadsSpark -I gs://mw-pathseq-test/hs37d5cs.reads.sorted.bam -O hs37d5cs.reads.txt --apiKey XXXXXXXXXXXXXXXXXXXXX --verbosity DEBUG --sparkMaster yarn
Copying file:///Users/markw/IdeaProjects/gatk/build/libs/gatk-package-4.alpha.2-157-g7d7c5ec-SNAPSHOT-spark.jar [Content-Type=application/java-archive]...
- [1 files][ 95.3 MiB/ 95.3 MiB]    9.0 MiB/s
Operation completed over 1 objects/95.3 MiB.
Job [5b3d4225-0547-4aa9-8a83-ab26460aa2d2] submitted.
Waiting for job output...
21:42:45.768 INFO  IntelGKLUtils - Trying to load Intel GKL library from:
	jar:file:/tmp/5b3d4225-0547-4aa9-8a83-ab26460aa2d2/gatk-package-4.alpha.2-157-g7d7c5ec-SNAPSHOT-spark.jar!/com/intel/gkl/native/libgkl_compression.so
21:42:45.791 DEBUG IntelGKLUtils - Extracted Intel GKL to /tmp/root/libgkl_compression6493251482684327282.so

21:42:45.792 INFO  IntelGKLUtils - Intel GKL library loaded from classpath.
[February 6, 2017 9:42:45 PM UTC] org.broadinstitute.hellbender.tools.spark.pipelines.PrintReadsSpark  --output hs37d5cs.reads.txt --input gs://mw-pathseq-test/hs37d5cs.reads.sorted.bam --apiKey XXXXXXXXXXXXXXXX --sparkMaster yarn --verbosity DEBUG  --readValidationStringency SILENT --interval_set_rule UNION --interval_padding 0 --interval_exclusion_padding 0 --bamPartitionSize 0 --disableSequenceDictionaryValidation false --shardedOutput false --numReducers 0 --help false --version false --QUIET false --use_jdk_deflater false --disableAllReadFilters false
[February 6, 2017 9:42:45 PM UTC] Executing as root@mw-test-m on Linux 3.16.0-4-amd64 amd64; OpenJDK 64-Bit Server VM 1.8.0_111-8u111-b14-2~bpo8+1-b14; Version: Version:4.alpha.2-157-g7d7c5ec-SNAPSHOT
21:42:45.795 INFO  PrintReadsSpark - Defaults.BUFFER_SIZE : 131072
21:42:45.795 INFO  PrintReadsSpark - Defaults.COMPRESSION_LEVEL : 1
21:42:45.795 INFO  PrintReadsSpark - Defaults.CREATE_INDEX : false
21:42:45.795 INFO  PrintReadsSpark - Defaults.CREATE_MD5 : false
21:42:45.795 INFO  PrintReadsSpark - Defaults.CUSTOM_READER_FACTORY :
21:42:45.795 INFO  PrintReadsSpark - Defaults.EBI_REFERENCE_SERVICE_URL_MASK : http://www.ebi.ac.uk/ena/cram/md5/%s
21:42:45.796 INFO  PrintReadsSpark - Defaults.NON_ZERO_BUFFER_SIZE : 131072
21:42:45.796 INFO  PrintReadsSpark - Defaults.REFERENCE_FASTA : null
21:42:45.796 INFO  PrintReadsSpark - Defaults.SAM_FLAG_FIELD_FORMAT : DECIMAL
21:42:45.796 INFO  PrintReadsSpark - Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
21:42:45.796 INFO  PrintReadsSpark - Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : false
21:42:45.796 INFO  PrintReadsSpark - Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
21:42:45.796 INFO  PrintReadsSpark - Defaults.USE_CRAM_REF_DOWNLOAD : false
21:42:45.796 INFO  PrintReadsSpark - Deflater IntelDeflater
21:42:45.796 INFO  PrintReadsSpark - Initializing engine
21:42:45.796 INFO  PrintReadsSpark - Done initializing engine
17/02/06 21:42:46 INFO org.spark_project.jetty.util.log: Logging initialized @2790ms
17/02/06 21:42:46 INFO org.spark_project.jetty.server.Server: jetty-9.2.z-SNAPSHOT
17/02/06 21:42:46 INFO org.spark_project.jetty.server.ServerConnector: Started ServerConnector@5148cf20{HTTP/1.1}{0.0.0.0:4040}
17/02/06 21:42:46 INFO org.spark_project.jetty.server.Server: Started @2906ms
17/02/06 21:42:47 INFO com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase: GHFS version: 1.6.0-hadoop2
17/02/06 21:42:48 INFO org.apache.hadoop.yarn.client.RMProxy: Connecting to ResourceManager at mw-test-m/10.128.0.7:8032
17/02/06 21:42:48 INFO org.apache.hadoop.yarn.client.api.impl.YarnClientImpl: Submitted application application_1486412429336_0010
17/02/06 21:42:53 INFO com.google.cloud.genomics.dataflow.utils.GCSOptions: Creating storgae client for PrintReadsSpark
17/02/06 21:42:53 INFO com.google.cloud.genomics.dataflow.readers.bam.SeekableGCSStream: Creating SeekableGCSStream: gs://mw-pathseq-test/hs37d5cs.reads.sorted.bam.bai
17/02/06 21:42:53 INFO com.google.cloud.genomics.dataflow.readers.bam.SeekableGCSStream: uriToStorageObject mw-pathseq-test/hs37d5cs.reads.sorted.bam.bai=mw-pathseq-test:hs37d5cs.reads.sorted.bam.bai
17/02/06 21:42:54 INFO com.google.cloud.genomics.dataflow.readers.bam.BAMIO: No index for gs://mw-pathseq-test/hs37d5cs.reads.sorted.bam.bai
17/02/06 21:42:54 INFO com.google.cloud.genomics.dataflow.readers.bam.SeekableGCSStream: Creating SeekableGCSStream: gs://mw-pathseq-test/hs37d5cs.reads.sorted.bam
17/02/06 21:42:54 INFO com.google.cloud.genomics.dataflow.readers.bam.SeekableGCSStream: uriToStorageObject mw-pathseq-test/hs37d5cs.reads.sorted.bam=mw-pathseq-test:hs37d5cs.reads.sorted.bam
17/02/06 21:42:54 INFO org.spark_project.jetty.server.ServerConnector: Stopped ServerConnector@5148cf20{HTTP/1.1}{0.0.0.0:4040}
21:42:54.861 INFO  PrintReadsSpark - Shutting down engine
[February 6, 2017 9:42:54 PM UTC] org.broadinstitute.hellbender.tools.spark.pipelines.PrintReadsSpark done. Elapsed time: 0.15 minutes.
Runtime.totalMemory()=573571072
***********************************************************************

A USER ERROR has occurred: Failed to read bam header from gs://mw-pathseq-test/hs37d5cs.reads.sorted.bam
 Caused by:Error reading null at position 0

***********************************************************************
org.broadinstitute.hellbender.exceptions.UserException: A USER ERROR has occurred: Failed to read bam header from gs://mw-pathseq-test/hs37d5cs.reads.sorted.bam
 Caused by:Error reading null at position 0
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSource.getHeader(ReadsSparkSource.java:182)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.initializeReads(GATKSparkTool.java:376)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.initializeToolInputs(GATKSparkTool.java:357)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:347)
	at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:112)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:170)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:189)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:96)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:103)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:116)
	at org.broadinstitute.hellbender.Main.main(Main.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:736)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.io.IOException: Error reading null at position 0
	at com.google.cloud.genomics.dataflow.readers.bam.SeekableGCSStream.openStream(SeekableGCSStream.java:126)
	at com.google.cloud.genomics.dataflow.readers.bam.SeekableGCSStream.seek(SeekableGCSStream.java:103)
	at com.google.cloud.genomics.dataflow.readers.bam.SeekableGCSStream.<init>(SeekableGCSStream.java:59)
	at com.google.cloud.genomics.dataflow.readers.bam.BAMIO.openBAMFile(BAMIO.java:67)
	at com.google.cloud.genomics.dataflow.readers.bam.BAMIO.openBAM(BAMIO.java:51)
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSource.getHeader(ReadsSparkSource.java:178)
	... 20 more
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 401 Unauthorized
Anonymous users does not have storage.objects.get access to object mw-pathseq-test/hs37d5cs.reads.sorted.bam.
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1056)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeMedia(AbstractGoogleClientRequest.java:380)
	at com.google.api.services.storage.Storage$Objects$Get.executeMedia(Storage.java:4792)
	at com.google.cloud.genomics.dataflow.readers.bam.SeekableGCSStream.openStream(SeekableGCSStream.java:121)
	... 25 more
ERROR: (gcloud.dataproc.jobs.submit.spark) Job [5b3d4225-0547-4aa9-8a83-ab26460aa2d2] entered state [ERROR] while waiting for [DONE].

**Comment by droazen** [comment]
@jean-philippe-martin Is this the case? I thought this was working..

**Comment by lbergelson** [comment]
Hasn't this been broken for a long time?

**Comment by droazen** [comment]
Not sure, I'll let @jean-philippe-martin answer that.

**Comment by lbergelson** [comment]
I think now that we have the NIO plugin working we can probably replace everything that used AuthHolder with NIO.

**Comment by jean-philippe-martin** [comment]
My recollection is that this is a use case we never put any priority on so there's no test in the GATK suite for access to private files. There should be, of course. The feature is there and (at least locally) it worked when I tried it.

NIO does not use the API_KEY, it uses default credentials. Those are environment variables that are set by the `gcloud` command or pre-set for you in the case of virtual machines on Google.

There are two cases: local execution and Spark. 

I just tested local execution and it worked fine for me:

```
$ ./gatk-launch PrintReads -L Broad.human.exome.b37.small.interval_list -I gs://jpmartin-private/bench/WGS-G94982-NA12878.bam -O t_gcs.bam
```

this command worked even though (unless I'm mistaken) neither the bucket nor the file are public.

One challenge however is that the way to set default credentials has changed recently. Calling `gcloud auth login` used to be enough but now we have to call (IIRC) `gcloud auth application-default login`.

For Spark, the default credentials are set as whoever owns the dataproc environment that's used to run the show. So it should be set so it has access to the buckets necessary. NIO has mechanisms for accessing buckets that belong to someone other than who is running the Spark job, but they are not hooked into GATK yet.

**Comment by lbergelson** [comment]
@jean-philippe-martin The bug is in a piece of code that ISN'T using NIO, but is using some old code from the dataflow days to access the bam.  I think that we can replace that code now that NIO is working and we should no longer need these special cases for GCS files.

**Comment by droazen** [comment]
Assigning to @jean-philippe-martin to migrate from `AuthHolder` to NIO on Spark in order to resolve this issue.
