### ISSUE TITLE
bwaspark fails to write  aligned reads

### ISSUE THREAD

**Issue by tushu1232** [broadinstitute/gatk#2503]
org.broadinstitute.hellbender.exceptions.GATKException: Unable to write aligned reads
	at org.broadinstitute.hellbender.tools.spark.bwa.BwaSpark.runTool(BwaSpark.java:52)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:353)
	at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:111)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:169)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:188)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:120)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:141)
	at org.broadinstitute.hellbender.Main.main(Main.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:728)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:177)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:202)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:116)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.io.IOException: Invalid splitting BAM index: should contain at least 1 offset and the file size
	at org.seqdoop.hadoop_bam.SplittingBAMIndex.readIndex(SplittingBAMIndex.java:69)
	at org.seqdoop.hadoop_bam.SplittingBAMIndex.<init>(SplittingBAMIndex.java:49)
	at org.seqdoop.hadoop_bam.util.SAMFileMerger.mergeSplittingBaiFiles(SAMFileMerger.java:117)
	at org.seqdoop.hadoop_bam.util.SAMFileMerger.mergeParts(SAMFileMerger.java:87)
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink.writeReadsSingle(ReadsSparkSink.java:230)
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink.writeReads(ReadsSparkSink.java:152)
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink.writeReads(ReadsSparkSink.java:119)
	at org.broadinstitute.hellbender.tools.spark.bwa.BwaSpark.runTool(BwaSpark.java:49)
	... 17 more

**Comment by tushu1232** [comment]
Caused by: java.io.IOException: Invalid splitting BAM index: should contain at least 1 offset and the file size

**Comment by droazen** [comment]
@tedsharpe Have you seen errors like this before with `BwaSpark`?

**Comment by lbergelson** [comment]
That sounds like the sort of error we'd get if we tried to index an empty bam.  I wonder if it's the filter problem that Ted's PR is addressing.

**Comment by lbergelson** [comment]
Probably also a bug in the error message, because that's a really unhelpful message.

**Comment by tedsharpe** [comment]
I've never seen it do anything else.

**Comment by droazen** [comment]
@tedsharpe And does your PR https://github.com/broadinstitute/gatk/pull/2494 fix this issue, to your knowledge?

**Comment by tedsharpe** [comment]
It does not.  The code, AFAIK, was pre-broken, unrelated to the BWA work I was doing, and unaddressed by my efforts.

**Comment by droazen** [comment]
I think this is a duplicate of https://github.com/broadinstitute/gatk/issues/2219. I think this error occurs when trying to write an empty file, which is why I was hoping that https://github.com/broadinstitute/gatk/pull/2494 would fix this by adjusting the read filtering.

@tushu1232 Can you test with https://github.com/broadinstitute/gatk/pull/2494 and tell us whether you still see the error?

**Comment by droazen** [comment]
Adding @tomwhite to comment on this.

**Comment by tedsharpe** [comment]
I did get this to run on my local machine.  It may be more fixed than I had believed.

**Comment by lbergelson** [comment]
I'm assuming it's because of the filters, which should be fixed by your branch.

**Comment by droazen** [comment]
Is this still an issue, given that the filter fix has gone in?
