### ISSUE TITLE
ValidateVariants throws IllegalArgumentException if a reference isn't provided

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2509]
ValidateVariants give an `IllegalArgumentException` if a reference isn't provided. 

It should be a `UserException`.  I don't know but I think there may be modes that don't require the reference, so it may need to give a smart error message.

```
gatk-launch ValidateVariants  --variant src/test/resources/org/broadinstitute/hellbender/tools/walkers/ValidateVariants/validationExampleGood.vcf
Using GATK wrapper script /Users/louisb/Workspace/gatk/build/install/gatk/bin/gatk
Running:
    /Users/louisb/Workspace/gatk/build/install/gatk/bin/gatk ValidateVariants --variant src/test/resources/org/broadinstitute/hellbender/tools/walkers/ValidateVariants/validationExampleGood.vcf
17:43:53.119 INFO  NativeLibraryLoader - Loading libgkl_compression.dylib from jar:file:/Users/louisb/Workspace/gatk/build/install/gatk/lib/gkl-0.4.1.jar!/com/intel/gkl/native/libgkl_compression.dylib
[March 21, 2017 5:43:53 PM EDT] org.broadinstitute.hellbender.tools.walkers.variantutils.ValidateVariants  --variant src/test/resources/org/broadinstitute/hellbender/tools/walkers/ValidateVariants/validationExampleGood.vcf  --doNotValidateFilteredRecords false --warnOnErrors false --interval_set_rule UNION --interval_padding 0 --interval_exclusion_padding 0 --readValidationStringency SILENT --secondsBetweenProgressUpdates 10.0 --disableSequenceDictionaryValidation false --createOutputBamIndex true --createOutputBamMD5 false --createOutputVariantIndex true --createOutputVariantMD5 false --lenient false --addOutputSAMProgramRecord true --cloudPrefetchBuffer 40 --cloudIndexPrefetchBuffer -1 --disableBamIndexCaching false --help false --version false --showHidden false --verbosity INFO --QUIET false --use_jdk_deflater false --use_jdk_inflater false --disableToolDefaultReadFilters false
[March 21, 2017 5:43:53 PM EDT] Executing as louisb@WMD2A-31E on Mac OS X 10.11.6 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_112-b16; Version: Version:4.alpha.2-189-g724fbd0-SNAPSHOT
17:43:53.162 INFO  ValidateVariants - Defaults.BUFFER_SIZE : 131072
17:43:53.162 INFO  ValidateVariants - Defaults.COMPRESSION_LEVEL : 1
17:43:53.162 INFO  ValidateVariants - Defaults.CREATE_INDEX : false
17:43:53.163 INFO  ValidateVariants - Defaults.CREATE_MD5 : false
17:43:53.163 INFO  ValidateVariants - Defaults.CUSTOM_READER_FACTORY :
17:43:53.163 INFO  ValidateVariants - Defaults.EBI_REFERENCE_SERVICE_URL_MASK : http://www.ebi.ac.uk/ena/cram/md5/%s
17:43:53.163 INFO  ValidateVariants - Defaults.NON_ZERO_BUFFER_SIZE : 131072
17:43:53.163 INFO  ValidateVariants - Defaults.REFERENCE_FASTA : null
17:43:53.163 INFO  ValidateVariants - Defaults.SAM_FLAG_FIELD_FORMAT : DECIMAL
17:43:53.163 INFO  ValidateVariants - Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
17:43:53.163 INFO  ValidateVariants - Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
17:43:53.163 INFO  ValidateVariants - Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
17:43:53.163 INFO  ValidateVariants - Defaults.USE_CRAM_REF_DOWNLOAD : false
17:43:53.163 INFO  ValidateVariants - Deflater IntelDeflater
17:43:53.163 INFO  ValidateVariants - Inflater IntelInflater
17:43:53.163 INFO  ValidateVariants - Initializing engine
17:43:53.270 INFO  FeatureManager - Using codec VCFCodec to read file file:///Users/louisb/Workspace/gatk/src/test/resources/org/broadinstitute/hellbender/tools/walkers/ValidateVariants/validationExampleGood.vcf
17:43:53.287 INFO  FeatureManager - Using codec VCFCodec to read file file:///Users/louisb/Workspace/gatk/src/test/resources/org/broadinstitute/hellbender/tools/walkers/ValidateVariants/validationExampleGood.vcf
17:43:53.291 WARN  IndexUtils - Feature file "/Users/louisb/Workspace/gatk/src/test/resources/org/broadinstitute/hellbender/tools/walkers/ValidateVariants/validationExampleGood.vcf" appears to contain no sequence dictionary. Attempting to retrieve a sequence dictionary from the associated index file
17:43:53.293 INFO  ValidateVariants - Done initializing engine
17:43:53.294 INFO  ProgressMeter - Starting traversal
17:43:53.294 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Records Processed   Records/Minute
17:43:53.302 INFO  ValidateVariants - Shutting down engine
[March 21, 2017 5:43:53 PM EDT] org.broadinstitute.hellbender.tools.walkers.variantutils.ValidateVariants done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=194510848
java.lang.IllegalArgumentException: Illegal base [] seen in the allele
	at htsjdk.variant.variantcontext.Allele.create(Allele.java:231)
	at htsjdk.variant.variantcontext.Allele.create(Allele.java:374)
	at org.broadinstitute.hellbender.tools.walkers.variantutils.ValidateVariants.apply(ValidateVariants.java:181)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.lambda$traverse$0(VariantWalkerBase.java:104)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.traverse(VariantWalkerBase.java:102)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:664)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:116)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:121)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:142)
	at org.broadinstitute.hellbender.Main.main(Main.java:218)
```

**Comment by davidbenjamin** [comment]
Closed by #2649
