### ISSUE TITLE
Error getting access token for service account

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2514]
Seeing a test failure due to errors with the service account access token.  Possibly related to updating the NIO dependency.  We've seen this multiple times today. 
```
Gradle suite > Gradle test > org.broadinstitute.hellbender.utils.nio.GcsNioIntegrationTest.openPublicFile FAILED
    com.google.cloud.storage.StorageException: Error getting access token for service account: 
        at com.google.cloud.storage.spi.DefaultStorageRpc.translate(DefaultStorageRpc.java:203)
        at com.google.cloud.storage.spi.DefaultStorageRpc.get(DefaultStorageRpc.java:349)
        at com.google.cloud.storage.StorageImpl$5.call(StorageImpl.java:186)
        at com.google.cloud.storage.StorageImpl$5.call(StorageImpl.java:183)
        at com.google.cloud.RetryHelper.doRetry(RetryHelper.java:179)
        at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:244)
        at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:183)
        at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:197)
        at com.google.cloud.storage.contrib.nio.CloudStorageReadChannel.fetchSize(CloudStorageReadChannel.java:194)
        at com.google.cloud.storage.contrib.nio.CloudStorageReadChannel.<init>(CloudStorageReadChannel.java:72)
        at com.google.cloud.storage.contrib.nio.CloudStorageReadChannel.create(CloudStorageReadChannel.java:62)
        at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.newReadChannel(CloudStorageFileSystemProvider.java:268)
        at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.newByteChannel(CloudStorageFileSystemProvider.java:229)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.newInputStream(CloudStorageFileSystemProvider.java:348)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at org.broadinstitute.hellbender.utils.nio.GcsNioIntegrationTest.openPublicFile(GcsNioIntegrationTest.java:33)
        Caused by:
        java.io.IOException: Error getting access token for service account: 
            at shaded.cloud-nio.com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:319)
            at shaded.cloud-nio.com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:149)
            at shaded.cloud-nio.com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:135)
            at shaded.cloud-nio.com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:96)
            at com.google.cloud.HttpTransportOptions$1.initialize(HttpTransportOptions.java:149)
            at shaded.cloud-nio.com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:93)
            at shaded.cloud-nio.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:300)
            at shaded.cloud-nio.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
            at shaded.cloud-nio.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
            at shaded.cloud-nio.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
            at com.google.cloud.storage.spi.DefaultStorageRpc.get(DefaultStorageRpc.java:347)
            ... 17 more
            Caused by:
            java.net.SocketTimeoutException: Read timed out
                at java.net.SocketInputStream.socketRead0(Native Method)
                at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
                at java.net.SocketInputStream.read(SocketInputStream.java:170)
                at java.net.SocketInputStream.read(SocketInputStream.java:141)
                at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
                at sun.security.ssl.InputRecord.read(InputRecord.java:503)
                at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
                at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
                at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
                at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
                at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
                at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
                at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
                at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
                at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
                at shaded.cloud-nio.com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
                at shaded.cloud-nio.com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972)
                at shaded.cloud-nio.com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:317)
                ... 27 more
```

**Comment by lbergelson** [comment]
@jean-philippe-martin Could you take a look at this one too?

**Comment by jean-philippe-martin** [comment]
I set TEST_TYPE to "all" and was able to run this test without failure. The command I used is:
```
./gradlew test --tests org.broadinstitute.hellbender.utils.nio.GcsNioIntegrationTest.openPublicFile
```
I ran it 7 times and got the same result every time:
`BUILD SUCCESSFUL`

It looks like this was a transient problem: either the internet connection was stalled or the authentication server was down temporarily.

As this happens at the very beginning of the execution, it's probably not a very big deal: the user can just retry.

Incidentally, PR #2506 that is under review lengthens the connection timeouts, if I am not mistaken. This will probably make the problem less likely to reoccur.

**Comment by jean-philippe-martin** [comment]
I ran it another 40, bringing the total to 50. They all passed.

**Comment by lbergelson** [comment]
I think something must have been going on with the auth service at the time because it happened twice in quick succession.  If we can't reproduce I'm not sure what we can do about it.

**Comment by jean-philippe-martin** [comment]
You're probably right. For now perhaps it's best to do nothing: the auth service is normally up and if it's temporarily down, perhaps it's best not to hammer it with repeated requests.

**Comment by droazen** [comment]
Closing -- this was likely a temporary issue, as we haven't seen it again.
