### ISSUE TITLE
Passing an inexistent bam file name to a Spark walker results in NPE.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#2541]
First it does not complain that the file does not exists but when you request the getReadsHeader() it results in a deep down NPE exception. The fact that the walker requires reads does not help either.

**Comment by droazen** [comment]
@tomwhite Can you have a look at this one? Likely an issue in Hadoop-BAM.

**Comment by tomwhite** [comment]
@vruano I tried to reproduce this by specifying a non-existent BAM file to `CountReadsSpark`. I get a `UserException` (stacktrace below), not an NPE. Can you post your stacktrace please?

```
org.broadinstitute.hellbender.exceptions.UserException: Failed to read bam header from /Users/tom/workspace/gatk/src/test/resources/org/broadinstitute/hellbender/tools/nonexistent.bam
     Caused by:/Users/tom/workspace/gatk/src/test/resources/org/broadinstitute/hellbender/tools/nonexistent.bam
        at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSource.getHeader(ReadsSparkSource.java:204)
        at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.initializeReads(GATKSparkTool.java:381)
        at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.initializeToolInputs(GATKSparkTool.java:361)
        at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:351)
        at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:116)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:121)
        at org.broadinstitute.hellbender.Main.instanceMain(Main.java:108)
        at org.broadinstitute.hellbender.Main.instanceMain(Main.java:128)
        at org.broadinstitute.hellbender.CommandLineProgramTest.runCommandLine(CommandLineProgramTest.java:28)
        at org.broadinstitute.hellbender.utils.test.CommandLineProgramTester.runCommandLine(CommandLineProgramTester.java:88)
        at org.broadinstitute.hellbender.tools.spark.pipelines.CountReadsSparkIntegrationTest.testNonExistentInputBam(CountReadsSparkIntegrationTest.java:111)

        Caused by:
        java.io.FileNotFoundException: /Users/tom/workspace/gatk/src/test/resources/org/broadinstitute/hellbender/tools/nonexistent.bam
            at org.apache.hadoop.fs.RawLocalFileSystem.open(RawLocalFileSystem.java:200)
            at org.apache.hadoop.fs.ChecksumFileSystem.open(ChecksumFileSystem.java:344)
            at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:767)
            at org.seqdoop.hadoop_bam.util.SAMHeaderReader.readSAMHeaderFrom(SAMHeaderReader.java:51)
            at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSource.getHeader(ReadsSparkSource.java:202)
            ... 13 more
```

**Comment by droazen** [comment]
@vruano Can you provide a command line to reproduce?

**Comment by vruano** [comment]
That was a long time ago, I'm not able to figure out what I did at the time to trigger. 
I suggest that you close this issue. If that is still a problem, it should pop out at some point.

**Comment by droazen** [comment]
Closing
