### ISSUE TITLE
VariantWalkerSpark produces mysterious serialization exception with some VCFs: 

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#2545]
This error does not occur with every VCF but at least with the one enclosed below. It passes vcf-validator with default arguments. 

To reproduce: 

```
term1$ spark-shell # start you spark local cluster in another screen
...
term2$ cd /dsde/working/valentin/bugs/gatk-var-walker-ser
term2$ git checkout 58cb99ec 
term2$ ./gradlew sparkJar
term2$ ./gatk-launch-debug ExampleVariantWalkerSpark -V ./in.vcf.gz  -- --sparkRunner SPARK --sparkMaster local

```

```
The stacktrace starts with:

17/03/29 16:44:56 INFO SparkContext: Successfully stopped SparkContext
16:44:56.000 INFO  ExampleVariantWalkerSpark - Shutting down engine
[March 29, 2017 4:44:56 PM EDT] org.broadinstitute.hellbender.tools.examples.ExampleVariantWalkerSpark done. Elapsed time: 0.08 minutes.
Runtime.totalMemory()=576192512
java.lang.IllegalArgumentException: requirement failed: The partition coalescer passed in must be serializable.
	at scala.Predef$.require(Predef.scala:224)
	at org.apache.spark.rdd.CoalescedRDD.<init>(CoalescedRDD.scala:84)
	at org.apache.spark.rdd.RDD$$anonfun$coalesce$1.apply(RDD.scala:466)
	at org.apache.spark.rdd.RDD$$anonfun$coalesce$1.apply(RDD.scala:445)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.coalesce(RDD.scala:445)
	at org.broadinstitute.hellbender.engine.spark.SparkSharder.coalesce(SparkSharder.java:321)
	at org.broadinstitute.hellbender.engine.spark.SparkSharder.joinOverlapping(SparkSharder.java:189)
	at org.broadinstitute.hellbender.engine.spark.SparkSharder.joinOverlapping(SparkSharder.java:126)
	at org.broadinstitute.hellbender.engine.spark.SparkSharder.shard(SparkSharder.java:99)
	at org.broadinstitute.hellbender.engine.spark.VariantWalkerSpark.getVariants(VariantWalkerSpark.java:129)
	at org.broadinstitute.hellbender.engine.spark.VariantWalkerSpark.runTool(VariantWalkerSpark.java:160)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:353)
	at org.broadinstitute.hellbender.engine.spark.VariantWalkerSpark.runPipeline(VariantWalkerSpark.java:57)
	at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:116)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:121)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:142)
	at org.broadinstitute.hellbender.Main.main(Main.java:218)
```

**Comment by vruano** [comment]
As per @droazen recommendation I tried adding the following line to GATKRegistrator.java:

```
kryo.register(RangePartitionCoalescer.class, new FieldSerializer<>(kryo, RangePartitionCoalescer.class));
```

Same result, no improvement.

**Comment by vruano** [comment]
Since the problem disappear depending on the content of the VCF I suspect that the error message is actually misleading.

**Comment by droazen** [comment]
@vruano What happens if you make your tool extend `GATKSparkTool` directly, rather than `VariantWalkerSpark` then do the following in your `runTool()` method?

```
final VariantsSparkSource variantsSource = new VariantsSparkSource(ctx);
final List<SimpleInterval> intervals = hasIntervals() ? getIntervals() : IntervalUtils.getAllIntervalsForReference(getBestAvailableSequenceDictionary());
final JavaRDD<VariantContext> variants = variantsSource.getParallelVariantContexts(vcf, getIntervals());
```

And then do a `variants.mapPartitions()` call on the resulting `variants` RDD to process each variant?

Also, at-mentioning @tomwhite here to comment on the `VariantWalkerSpark` issue, since he wrote that class.

**Comment by vruano** [comment]
It seems that the error goes away when I installed 2.0.2 ..... I had the 2.1.0 that is the only 2.x.x available thru homebrew on Mac. So it might all be due to a version difference.

**Comment by droazen** [comment]
@vruano Aha, I didn't notice that you were running with a local Spark master (`--sparkRunner SPARK --sparkMaster local`)! If you omit those arguments from your command line, you'll fall back to using the in-memory Spark runner instead, which uses threads rather than processes.  The in-memory runner will always be the correct version for GATK4, since it's linked into our jar.

**Comment by droazen** [comment]
(In other words, it's not necessary to spin up a Spark cluster locally, if all you want to do is run your tool across multiple threads)

**Comment by vruano** [comment]
mmm... that said, I think this must fail using the right error message, don't you think? @droazen.

**Comment by droazen** [comment]
Yes, of course :) It can be a challenge to get good error messages out of Spark, but perhaps we could have some kind of up-front check in GATK4 for a Spark version mismatch.

**Comment by lbergelson** [comment]
Oh, that's interesting...  I wonder if there is a sane way to detect the version mismatch.  It's weird that it breaks with a NEWER version of spark.  I would expect 2.1.0 to be compatible with 2.0.2.  

Incidentally, it would be a good idea to upgrade to the newest spark version.  #2555
