### ISSUE TITLE
Incorrect error message when trying to read corrupt bam file

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2551]
The error `Cannot use index file with textual SAM file` was reported by `AssemblyRegionUnitTest.testCreateFromReadShard`when trying to read what was likely a corrupted large file bam on travis.

This error does not accurately reflect the problem and is likely caused by a chain of fallbacks in htsjdk.  It's possible that the switch from file -> path has changed the sequence of fallbacks causing this error to appear.

**Comment by lbergelson** [comment]
java.lang.RuntimeException: Cannot use index file with textual SAM file
        at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:402)
        at htsjdk.samtools.SamReaderFactory.open(SamReaderFactory.java:105)
        at org.broadinstitute.hellbender.engine.ReadsDataSource.<init>(ReadsDataSource.java:226)
        at org.broadinstitute.hellbender.engine.ReadsDataSource.<init>(ReadsDataSource.java:161)
        at org.broadinstitute.hellbender.engine.ReadsDataSource.<init>(ReadsDataSource.java:117)
        at org.broadinstitute.hellbender.engine.ReadsDataSource.<init>(ReadsDataSource.java:86)
        at org.broadinstitute.hellbender.engine.AssemblyRegionUnitTest.testCreateFromReadShard(AssemblyRegionUnitTest.java:46
