### ISSUE TITLE
Shutdown hook called before final status was reported.

### ISSUE THREAD

**Issue by david-wb** [broadinstitute/gatk#2666]
Hi, 
I am experimenting with submitting a PrintReadsSpark job to a yarn spark cluster in AWS. I run the job with the following command.

```
spark-submit --deploy-mode cluster --class org.broadinstitute.hellbender.Main --deploy-mode cluster --master yarn gatk-package-4.alpha.2-248-gcd449bf-SNAPSHOT-spark.jar PrintReadsSpark -I hdfs://chr1.bam -O hdfs://output.bam
```

I can see from the output files that the job finished successfully, however the cluster tells me that it failed. It shows the following error message:

```
17/05/05 06:03:53 INFO ApplicationMaster: Final app status: FAILED, exitCode: 16, (reason: Shutdown hook called before final status was reported.)
```

I believe this may be due to the `System.exit(0)` statement at line 144 in hellbender.Main, though I am not sure. 

Here is a more complete snippet from the stderr log. 

```
17/05/05 06:03:50 INFO FileOutputCommitter: File Output Committer Algorithm version is 1
17/05/05 06:03:52 WARN DFSClient: Caught exception 
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1249)
	at java.lang.Thread.join(Thread.java:1323)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.closeResponder(DFSOutputStream.java:609)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.endBlock(DFSOutputStream.java:370)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:546)
17/05/05 06:03:52 INFO FileOutputCommitter: Saved output of task 'attempt_20170505060336_0011_r_000001_0' to hdfs://ip-172-30-0-86.ec2.internal:8020/output.bam.parts/_temporary/0/task_20170505060336_0011_r_000001
17/05/05 06:03:52 INFO Executor: Finished task 1.0 in stage 2.0 (TID 3). 1921 bytes result sent to driver
17/05/05 06:03:52 INFO TaskSetManager: Finished task 1.0 in stage 2.0 (TID 3) in 10260 ms on localhost (executor driver) (1/4)
17/05/05 06:03:53 INFO FileOutputCommitter: Saved output of task 'attempt_20170505060336_0011_r_000000_0' to hdfs://ip-172-30-0-86.ec2.internal:8020/output.bam.parts/_temporary/0/task_20170505060336_0011_r_000000
17/05/05 06:03:53 INFO Executor: Finished task 0.0 in stage 2.0 (TID 2). 1921 bytes result sent to driver
17/05/05 06:03:53 INFO FileOutputCommitter: Saved output of task 'attempt_20170505060336_0011_r_000003_0' to hdfs://ip-172-30-0-86.ec2.internal:8020/output.bam.parts/_temporary/0/task_20170505060336_0011_r_000003
17/05/05 06:03:53 INFO TaskSetManager: Finished task 0.0 in stage 2.0 (TID 2) in 10599 ms on localhost (executor driver) (2/4)
17/05/05 06:03:53 INFO Executor: Finished task 3.0 in stage 2.0 (TID 5). 1921 bytes result sent to driver
17/05/05 06:03:53 INFO TaskSetManager: Finished task 3.0 in stage 2.0 (TID 5) in 10599 ms on localhost (executor driver) (3/4)
17/05/05 06:03:53 INFO FileOutputCommitter: Saved output of task 'attempt_20170505060336_0011_r_000002_0' to hdfs://ip-172-30-0-86.ec2.internal:8020/output.bam.parts/_temporary/0/task_20170505060336_0011_r_000002
17/05/05 06:03:53 INFO Executor: Finished task 2.0 in stage 2.0 (TID 4). 1921 bytes result sent to driver
17/05/05 06:03:53 INFO TaskSetManager: Finished task 2.0 in stage 2.0 (TID 4) in 10792 ms on localhost (executor driver) (4/4)
17/05/05 06:03:53 INFO TaskSchedulerImpl: Removed TaskSet 2.0, whose tasks have all completed, from pool 
17/05/05 06:03:53 INFO DAGScheduler: ResultStage 2 (saveAsNewAPIHadoopFile at ReadsSparkSink.java:202) finished in 10.796 s
17/05/05 06:03:53 INFO DAGScheduler: Job 1 finished: saveAsNewAPIHadoopFile at ReadsSparkSink.java:202, took 17.010114 s
17/05/05 06:03:53 INFO SparkUI: Stopped Spark web UI at http://172.30.0.122:35794
17/05/05 06:03:53 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
17/05/05 06:03:53 INFO MemoryStore: MemoryStore cleared
17/05/05 06:03:53 INFO BlockManager: BlockManager stopped
17/05/05 06:03:53 INFO BlockManagerMaster: BlockManagerMaster stopped
17/05/05 06:03:53 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
17/05/05 06:03:53 INFO SparkContext: Successfully stopped SparkContext
[May 5, 2017 6:03:53 AM UTC] org.broadinstitute.hellbender.tools.spark.pipelines.PrintReadsSpark done. Elapsed time: 0.40 minutes.
Runtime.totalMemory()=799080448
17/05/05 06:03:53 INFO ApplicationMaster: Final app status: FAILED, exitCode: 16, (reason: Shutdown hook called before final status was reported.)
17/05/05 06:03:53 INFO ApplicationMaster: Unregistering ApplicationMaster with FAILED (diag message: Shutdown hook called before final status was reported.)
17/05/05 06:03:53 INFO ApplicationMaster: Deleting staging directory hdfs://ip-172-30-0-86.ec2.internal:8020/user/hadoop/.sparkStaging/application_1493961816416_0002
17/05/05 06:03:53 INFO ShutdownHookManager: Shutdown hook called
17/05/05 06:03:53 INFO ShutdownHookManager: Deleting directory /mnt1/yarn/usercache/hadoop/appcache/application_1493961816416_0002/spark-23bc1c26-8133-475d-8418-1def58e976fd
17/05/05 06:03:53 INFO ShutdownHookManager: Deleting directory /mnt/yarn/usercache/hadoop/appcache/application_1493961816416_0002/spark-edb79d30-a7d3-4ed2-ad61-2dc8ea95c5b1
```

Thanks in helping me solve this issue!

**Comment by lbergelson** [comment]
Hi @david-wb 

I reformatted your comment slightly to make the stack trace more legible, I hope you don't mind.

I suspect your intuition about the System.exit(0) is entirely correct.  I suspect we haven't noticed it because we typically run in yarn client mode and you're running in cluster mode.  

Two questions:
1.  How often does it happen?  Can you regularly reproduce it?
2.  Have you examined the output files to make sure they are correct and not truncated?  

It looks like we'll probably have to add a check and wait for the spark context to properly shut down.

**Comment by david-wb** [comment]
1. Yes it it reproducible. It happens every time. 

2. No, I have not examined the output files, but I have run the same app on my local machine with 
`
spark-submit --master local[2] gatk-package-4.alpha.2-252-gf627ed4-SNAPSHOT-spark.jar PrintReadsSpark -I chr1.bam -O output.bam
`
And the output.bam has nearly the same size in bytes as the output from the yarn cluster. The output .bai files have identical sizes.

**Comment by lbergelson** [comment]
@david-wb Thanks for the detailed information.  That's really helpful.   I don't think we're going to be able to get to this for the next few weeks since we're pretty swamped with work for our beta release.        Hopefully it's not blocking you since it seems like the output of the tools is correct.  We'll get back to you when we have a proposed PR for a fix that you can test.

**Comment by david-wb** [comment]
Sounds good. I can also run in client mode for the time being.
