### ISSUE TITLE
htsjdk.samtools.FileTruncatedException in GenomicsDBImport

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2686]
@kcibul encountered the following transient error when running GenomicsDBImport with vcfs in GCS.

```
[May 9, 2017 1:35:47 PM UTC] org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport done. Elapsed time: 2.44 minutes.
Runtime.totalMemory()=2436366336
htsjdk.samtools.FileTruncatedException: Premature end of file: /temp/10C102545.5783b88e-6d16-4da7-be0e-590811cd6d2f.g.vcf.gz
    at htsjdk.samtools.util.BlockCompressedInputStream.processNextBlock(BlockCompressedInputStream.java:513)
    at htsjdk.samtools.util.BlockCompressedInputStream.nextBlock(BlockCompressedInputStream.java:451)
    at htsjdk.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:441)
    at htsjdk.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:194)
    at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:234)
    at htsjdk.tribble.readers.TabixReader.readLine(TabixReader.java:199)
    at htsjdk.tribble.readers.TabixReader$IteratorImpl.next(TabixReader.java:416)
    at htsjdk.tribble.readers.TabixIteratorLineReader.readLine(TabixIteratorLineReader.java:45)
    at htsjdk.tribble.TabixFeatureReader$FeatureIterator.readNextRecord(TabixFeatureReader.java:178)
    at htsjdk.tribble.TabixFeatureReader$FeatureIterator.next(TabixFeatureReader.java:216)
    at htsjdk.tribble.TabixFeatureReader$FeatureIterator.next(TabixFeatureReader.java:156)
    at com.intel.genomicsdb.GenomicsDBImporterStreamWrapper.next(GenomicsDBImporterStreamWrapper.java:100)
    at com.intel.genomicsdb.GenomicsDBImporter.importBatch(GenomicsDBImporter.java:1313)
    at org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport.traverse(GenomicsDBImport.java:361)
    at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:740)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:116)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
    at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:121)
    at org.broadinstitute.hellbender.Main.mainEntry(Main.java:142)
    at org.broadinstitute.hellbender.Main.main(Main.java:220)
```

This was run with prefetching on and buffers of size 2.  It's worry some that we seem to be seeing corrupted data, and not an IOException.

**Comment by lbergelson** [comment]
@jean-philippe-martin Any thoughts on how this one is possible?  I'm assuming it was some sort of network error because it's transient.

**Comment by jean-philippe-martin** [comment]
@lbergelson my guess would be a transient network error due perhaps to storage being temporarily overloaded. This should cause the read to fail, though, no pretend to pass. So I'm surprised that the next step starts (and then reports the error we see since the input isn't complete).

**Comment by kgururaj** [comment]
Was this issue resolved?

**Comment by jean-philippe-martin** [comment]
@kgururaj I don't think so. While we see a lot fewer transient errors with the latest version, recent issue #3481 reports a similar truncation symptom.

**Comment by lbergelson** [comment]
Closing this because we can't reproduce.  This may have been fixed by the fix to the gzip bug.
