### ISSUE TITLE
GATKReadFilterPluginDescriptor does not work with Barclay (for other projects)

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#2739]
Trying to generate the documentation with gatk-protected to explore how a dependent-project could include ReadFilters and other utilities, running in my local computer it throws the following error:

```
javadoc: error - In doclet class org.broadinstitute.hellbender.utils.help.GATKHelpDoclet,  method start has thrown an exception java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: Could not find the field corresponding to java.lang.Throwable.backtrace, presumably because the field is inaccessible
        at org.broadinstitute.barclay.help.DefaultDocWorkUnitHandler.getFieldDoc(DefaultDocWorkUnitHandler.java:604)
        at org.broadinstitute.barclay.help.DefaultDocWorkUnitHandler.getFieldDoc(DefaultDocWorkUnitHandler.java:622)
        at org.broadinstitute.barclay.help.DefaultDocWorkUnitHandler.getFieldDoc(DefaultDocWorkUnitHandler.java:622)
        at org.broadinstitute.barclay.help.DefaultDocWorkUnitHandler.getFieldDoc(DefaultDocWorkUnitHandler.java:622)
        at org.broadinstitute.barclay.help.DefaultDocWorkUnitHandler.getFieldDoc(DefaultDocWorkUnitHandler.java:591)
        at org.broadinstitute.barclay.help.DefaultDocWorkUnitHandler.getFieldDocForCommandLineArgument(DefaultDocWorkUnitHandler.java:403)
        at org.broadinstitute.barclay.help.DefaultDocWorkUnitHandler.processNamedArgument(DefaultDocWorkUnitHandler.java:357)
        at org.broadinstitute.barclay.help.DefaultDocWorkUnitHandler.lambda$addCommandLineArgumentBindings$5(DefaultDocWorkUnitHandler.java:287)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at org.broadinstitute.barclay.help.DefaultDocWorkUnitHandler.addCommandLineArgumentBindings(DefaultDocWorkUnitHandler.java:287)
        at org.broadinstitute.barclay.help.DefaultDocWorkUnitHandler.processWorkUnit(DefaultDocWorkUnitHandler.java:202)
        at org.broadinstitute.barclay.help.DocWorkUnit.processDoc(DocWorkUnit.java:144)
        at org.broadinstitute.barclay.help.HelpDoclet.lambda$processDocs$1(HelpDoclet.java:169)
        at java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:2742)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at org.broadinstitute.barclay.help.HelpDoclet.processDocs(HelpDoclet.java:169)
        at org.broadinstitute.barclay.help.HelpDoclet.startProcessDocs(HelpDoclet.java:113)
        at org.broadinstitute.hellbender.utils.help.GATKHelpDoclet.start(GATKHelpDoclet.java:34)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:310)
        at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:189)
        at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:366)
        at com.sun.tools.javadoc.Start.begin(Start.java:219)
        at com.sun.tools.javadoc.Start.begin(Start.java:205)
        at com.sun.tools.javadoc.Main.execute(Main.java:64)
        at com.sun.tools.javadoc.Main.main(Main.java:54)
1 error
:gatkDoc FAILED
```

I can reproduce this error with a custom project with the gradle.build from gatk-protected and only the following class:

```java
/**
 * @author Daniel Gomez-Sanchez (magicDGS)
 */
@CommandLineProgramProperties(oneLineSummary = "Test plugin doc", summary = "Test plugin doc", programGroup = QCProgramGroup.class)
@DocumentedFeature
public class ExampleToolWithPluginDescriptor extends CommandLineProgram {

    @Override
    public List<? extends CommandLinePluginDescriptor<?>> getPluginDescriptors() {
        return Collections.singletonList(new GATKReadFilterPluginDescriptor(new ArrayList<>()));
    }

    @Override
    protected Object doWork() {
        return null;
    }
}
```

**Comment by magicDGS** [comment]
@cmnbroad, can you help me with this? I asked you because you are maintaining Barclay and you have implemented the gatk-protected doc task.

I would like to use the doc processing in my own toolkit, because it is very nice to automatize the help generation. Thank you in advance!

**Comment by cmnbroad** [comment]
@magicDGS We recently hit this ourselves (https://github.com/broadinstitute/gatk-protected/issues/1048). The fix is easy, but I'd like to find a way to repro it as a standalone test in Barclay, with no dependencies, i.e., no gatk dependencies.

Also, to use docgen for your toolkit, you'll need to provide the source for common classes like read filters, argument collections, etc. You may have noticed that gatk-protected does this. I expect that list will grow as we add @DocumentedFeature to more tools and encounter more dependencies.

**Comment by magicDGS** [comment]
I know that, and I kind of have an idea of how to do it with gradle without having a local copy (if you are interested, see https://stackoverflow.com/questions/28149123/is-there-a-way-to-tell-gradle-to-include-dependencies-javadocs-in-generated-java).

I subscribed to broadinstitute/gatk-protected#1048, and I'm closing this as a duplicate of that one. Thanks for your help.
