### ISSUE TITLE
Google cloud output issue with --shardedOutput false

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#2793]
When running PrintReads on GCS with shardedOutput false, I'm experiencing a file write failure for my output.  I have verified that I can write to the bucket I specify and that when shardedOutput is true this error does not occur.  @tomwhite - any thoughts?

Here's my invocation:

./gatk-launch PrintReadsSpark -I gs://hellbender/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam -O gs://jonn-test-bucket/foo.bam --shardedOutput false  -- --sparkRunner GCS --cluster jonn-test-cluster --num-executors 5 --executor-cores 4 --executor-memory 4g

Here is the stack trace:

org.broadinstitute.hellbender.exceptions.UserException$CouldNotCreateOutputFile: Couldn't write file gs://jonn-test-bucket/foo.bam because writing failed with exception jonn-test-bucket/foo.bam.parts
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.writeReads(GATKSparkTool.java:255)
	at org.broadinstitute.hellbender.tools.spark.pipelines.PrintReadsSpark.runTool(PrintReadsSpark.java:37)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:353)
	at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:116)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:171)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:190)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:121)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:142)
	at org.broadinstitute.hellbender.Main.main(Main.java:220)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:736)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.nio.file.NoSuchFileException: jonn-test-bucket/foo.bam.parts
	at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.readAttributes(CloudStorageFileSystemProvider.java:575)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:72)
	at java.nio.file.Files.walk(Files.java:3574)
	at java.nio.file.Files.walk(Files.java:3625)
	at org.seqdoop.hadoop_bam.util.NIOFileUtil.getFilesMatching(NIOFileUtil.java:91)
	at org.seqdoop.hadoop_bam.util.SAMFileMerger.mergeParts(SAMFileMerger.java:61)
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink.writeReadsSingle(ReadsSparkSink.java:230)
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink.writeReads(ReadsSparkSink.java:152)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.writeReads(GATKSparkTool.java:250)
	... 18 more

**Comment by droazen** [comment]
@jean-philippe-martin Can you comment on this one as well? Is this related to that globbing issue we fixed a while back?

**Comment by droazen** [comment]
@tomwhite @jean-philippe-martin Thoughts on this? I'm concerned that we might not have completely fixed that NIO BAM merging issue on Spark after all...

**Comment by tomwhite** [comment]
Is the output bucket otherwise empty? Does it work if you specify `--shardedOutput true`? (I'm not able to test this at the moment)

**Comment by droazen** [comment]
@tomwhite Yes, it works with `--shardedOutput true` and the exact same bucket.

**Comment by tomwhite** [comment]
It looks like the trailing slash on _foo.bam.parts_ is missing, so GCS interprets it as a file not a directory.

**Comment by droazen** [comment]
Interesting theory -- @jonn-smith is testing it out.

**Comment by jean-philippe-martin** [comment]
Great! I was testing it out as well.

**Comment by jonn-smith** [comment]
Here's some additional info.

After testing with the trailing slash, the process seems to run longer but there is some strangeness.  Looking at the Spark jobs info, it claims to have completed `saveAsNewAPIHadoopFile at ReadsSparkSink.java:202` but is still running.

**Comment by droazen** [comment]
@jean-philippe-martin Are you able to replicate this problem?

**Comment by jean-philippe-martin** [comment]
I saw it run for a surprisingly long time. Then it failed with a `SSLHandshakeException`. I need to run this with the [gcloud fix snapshot](https://github.com/broadinstitute/gatk/tree/jp_gcloud_17_snapshot).

**Comment by jean-philippe-martin** [comment]
Good news: I have a fix. Bad news: it requires changes to gcloud.

**Comment by droazen** [comment]
@jean-philippe-martin Will the fix be easy to implement? Can you provide more details on the underlying issue?

**Comment by jean-philippe-martin** [comment]
The fix is trivial, it's in [PR#2124](https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2124). 

The underlying issue is that Java's Files.walk() ends up in an infinite loop when iterating over files on GCS because the iterator returns the directory itself as the first result, so Files.walk() tries to cd there and we're stuck.

What we need to do on our end is add the "/" suffix and use the newer version of gcloud.

**Comment by droazen** [comment]
Ouch! Well that definitely explains the hanging :)

Now do you think we can possibly convince the maintainers of that project to cut a bug fix release with that patch, once it's merged?

**Comment by jean-philippe-martin** [comment]
We'll have to ask them, I don't know.

**Comment by droazen** [comment]
For now we will update to a snapshot with JP's fix, and add a test proving that the fix works.

**Comment by droazen** [comment]
This is believed to be fixed now that we've moved to a newer `google-cloud-java` snapshot, but we still need tests to prove that it is.
