### ISSUE TITLE
Snappy-java error when running gatk-launch FastqToSam

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2868]
@personalis commented on [Thu Jun 23 2016](https://github.com/broadinstitute/gatk-protected/issues/587)

We got the following error when running gatk-launch FastqToSam:

java.lang.IllegalArgumentException: Self-suppression not permitted
    at java.lang.Throwable.addSuppressed(Throwable.java:1043)
    at org.broadinstitute.hellbender.tools.picard.sam.FastqToSam.doWork(FastqToSam.java:163)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:102)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:155)
    at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgram.instanceMain(PicardCommandLineProgram.java:61)
    at org.broadinstitute.hellbender.Main.instanceMain(Main.java:67)
    at org.broadinstitute.hellbender.Main.main(Main.java:82)
Caused by: java.lang.NoClassDefFoundError: org/xerial/snappy/LoadSnappy
    at htsjdk.samtools.util.SnappyLoader.<init>(SnappyLoader.java:86)
    at htsjdk.samtools.util.SnappyLoader.<init>(SnappyLoader.java:52)
    at htsjdk.samtools.util.TempStreamFactory.getSnappyLoader(TempStreamFactory.java:42)
    at htsjdk.samtools.util.TempStreamFactory.wrapTempOutputStream(TempStreamFactory.java:74)
    at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:223)
    at htsjdk.samtools.util.SortingCollection.add(SortingCollection.java:166)
    at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:192)
    at htsjdk.samtools.AsyncSAMFileWriter.synchronouslyWrite(AsyncSAMFileWriter.java:36)
    at htsjdk.samtools.AsyncSAMFileWriter.synchronouslyWrite(AsyncSAMFileWriter.java:16)
    at htsjdk.samtools.util.AbstractAsyncWriter$WriterRunnable.run(AbstractAsyncWriter.java:117)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.xerial.snappy.LoadSnappy
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 11 more

We can find snappy-java in <INST_DIR>/build/install/gatk/lib/snappy-java-1.1.1.7.jar, but it does not have a LoadSnappy class.   Renaming the snappy-java jar file so gatk cannot find it allows FastqToSam to run through.

---

@akiezun commented on [Thu Jun 30 2016](https://github.com/broadinstitute/gatk-protected/issues/587#issuecomment-229843043)

thanks for the report. Can you provide the whole commandline you used?

---

@huangk3 commented on [Thu Sep 15 2016](https://github.com/broadinstitute/gatk-protected/issues/587#issuecomment-247467619)

Hi @akiezun I experience the same error when running gate-launch FastqToSam. My command line is:
"./gatk_launch FastqToSam -SM "test" -F1 $fq1 -F2 $fq2 -O test.spark.sam -SO coordinate -R $ref --STRIP_UNPAIRED_MATE_NUMBER true --VALIDATION_STRINGENCY LENIENT -PL ILLUMINA --CREATE_INDEX true"

My Spark version is 2.0.0
Thanks!

---

@lbergelson commented on [Mon Sep 19 2016](https://github.com/broadinstitute/gatk-protected/issues/587#issuecomment-248086238)

@huangk3 Unfortunately Adam moved on to a different job so he's longer working on GATK.  

I believe this is the same problem as https://github.com/broadinstitute/gatk/issues/2026 and has been patched in gatk public with https://github.com/broadinstitute/gatk/pull/2028.  You might try using FastqToSam in the public repo, or wait and try a new version of protected that incorporates an updated gatk public (coming soon..)

**Comment by lbergelson** [comment]
Closing this since the error should no longer occur since htsjdk updated it's snappy version which was included in #3588
