### ISSUE TITLE
GenotypeCopyNumberTriStateSegments fails when when the ReadCountsCollection targets differ from input target list

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2898]
@asmirnov239 commented on [Thu Sep 29 2016](https://github.com/broadinstitute/gatk-protected/issues/727)

Here is the stack trace:

```
java.lang.IllegalArgumentException: the 'to' index must be between 'from' and the length of the data/position sequence
        at org.broadinstitute.hellbender.utils.Utils.validateArg(Utils.java:609)
        at org.broadinstitute.hellbender.utils.param.ParamUtils.inRange(ParamUtils.java:80)
        at org.broadinstitute.hellbender.utils.hmm.ForwardBackwardAlgorithm$Result.logProbability(ForwardBackwardAlgorithm.java:141)
        at org.broadinstitute.hellbender.tools.exome.germlinehmm.GenotypeCopyNumberTriStateSegments.lambda$calculateLog10GP$6(GenotypeCopyNumberTriStateSegments.java:197)
        at java.util.stream.ReferencePipeline$6$1.accept(ReferencePipeline.java:244)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.util.stream.DoublePipeline.toArray(DoublePipeline.java:506)
        at org.broadinstitute.hellbender.tools.exome.germlinehmm.GenotypeCopyNumberTriStateSegments.calculateLog10GP(GenotypeCopyNumberTriStateSegments.java:198)
        at org.broadinstitute.hellbender.tools.exome.germlinehmm.GenotypeCopyNumberTriStateSegments.lambda$composeVariantContext$0(GenotypeCopyNumberTriStateSegments.java:125)
        at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.broadinstitute.hellbender.tools.exome.germlinehmm.GenotypeCopyNumberTriStateSegments.composeVariantContext(GenotypeCopyNumberTriStateSegments.java:141)
        at org.broadinstitute.hellbender.tools.exome.germlinehmm.GenotypeCopyNumberTriStateSegments.makeCalls(GenotypeCopyNumberTriStateSegments.java:104)
        at org.broadinstitute.hellbender.tools.exome.germlinehmm.CopyNumberTriStateSegmentCaller.doWork(CopyNumberTriStateSegmentCaller.java:121)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:108)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:166)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:185)

```

You can see all input files here:
/dsde/working/asmirnov/evaluations/Germline_CNV/TCGA/xhmm/debugging

The best fix would probably be to provide a warning to the user about inconsistency between target lists, and then subset input targets to match the those found in read count collection.
You can do that in the makeCalls() method of the GenotypeCopyNumberTriStateSegments tool here:

```
    @Override
    protected void makeCalls(final CopyNumberTriStateHiddenMarkovModel model, final TargetCollection<Target> targets, final ReadCountCollection inputCounts) {
        logger.info("Composing list of segment intervals to genotype ...");
        final List<GenotypingSegment> segments = composeGenotypingSegments(segmentsFile, targets);
        logger.info(String.format("A total of %d segments to genotype found", segments.size()));
        final List<ForwardBackwardAlgorithm.Result<Double, Target, CopyNumberTriState>> fbResults = runFWBWAlgorithm(model, inputCounts);
        for (final GenotypingSegment segment : segments) {
            final VariantContext variant = composeVariantContext(segment, inputCounts.columnNames(), fbResults);
            outputWriter.add(variant);
        }
    }
```

@vruano Could you please look into this?

---

@vruano commented on [Wed Oct 05 2016](https://github.com/broadinstitute/gatk-protected/issues/727#issuecomment-251744663)

Ok, I will take care of this. For now just to mention that the workaround is to provide a tool with a target file that matches the targets in the input count file.

**Comment by davidbenjamin** [comment]
@samuelklee This tool no longer exists, right?

**Comment by samuelklee** [comment]
Yup, thanks!
