### ISSUE TITLE
CorrectGCBias throwing NullPointerException

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2920]
@samuelklee commented on [Sun Nov 27 2016](https://github.com/broadinstitute/gatk-protected/issues/802)

Possibly due to bad input, but we should throw a better exception regardless:

    java.lang.NullPointerException
	at org.broadinstitute.hellbender.tools.exome.gcbias.CorrectGCBias.lambda$gcContentsOfTargets$1(CorrectGCBias.java:91)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
	at org.broadinstitute.hellbender.tools.exome.gcbias.CorrectGCBias.gcContentsOfTargets(CorrectGCBias.java:91)
	at org.broadinstitute.hellbender.tools.exome.gcbias.CorrectGCBias.doWork(CorrectGCBias.java:65)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:108)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:166)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:185)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:76)
	at org.broadinstitute.hellbender.Main.main(Main.java:92)

---

@samuelklee commented on [Mon Nov 28 2016](https://github.com/broadinstitute/gatk-protected/issues/802#issuecomment-263328345)

Looks like the issue was that the coverage files contained additional targets (on the sex chromosomes) that were missing in the list of targets passed.

**Comment by samuelklee** [comment]
Deleted in #3935.
