### ISSUE TITLE
CNV Pipeline outputs NaN and errors at segmentation with heavily downsampled input

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2944]
@meganshand commented on [Thu Feb 16 2017](https://github.com/broadinstitute/gatk-protected/issues/907)

Using a tiny bam file that I typically use for testing while running the CNV wdl on the cloud, I got the following errors (the tiny file is here: `gs://broad-dsde-methods/takuto/test_files/small_NA12878_hg19.bam`):

1. The output tsv from TumorNormalizeSomaticReadCounts contained NaNs
2. TumorPerformSeg threw the following error:

```
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/cromwell_root/tmp
[February 16, 2017 3:23:02 PM UTC] org.broadinstitute.hellbender.tools.exome.PerformSegmentation  --tangentNormalized /cromwell_root/broad-dsde-methods/cromwell-execution-24/TumorOnly/f30dd8c6-eec3-45ba-b7f2-f845d308d59d/call-TumorNormalizeSomaticReadCounts/small_NA12878.tn.tsv --output small_NA12878.seg --log2Input true --alpha 0.01 --nperm 10000 --pmethod hybrid --minWidth 2 --kmax 25 --nmin 200 --eta 0.05 --trim 0.025 --undoSplits none --undoPrune 0.05 --undoSD 3 --help false --version false --verbosity INFO --QUIET false  --use_jdk_deflater false
[February 16, 2017 3:23:02 PM UTC] Executing as root@3addd2d7b373 on Linux 3.16.0-0.bpo.4-amd64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_121-b13; Version: Version:c17c8ed-SNAPSHOT
[February 16, 2017 3:23:04 PM UTC] org.broadinstitute.hellbender.tools.exome.PerformSegmentation done. Elapsed time: 0.04 minutes.
Runtime.totalMemory()=185597952
org.broadinstitute.hellbender.utils.R.RScriptExecutorException: 
Rscript exited with 1
Command Line: Rscript -e tempLibDir = '/cromwell_root/tmp/root/Rlib.5210694187065743072';source('/cromwell_root/tmp/root/CBS.8616708738798684646.R'); --args --sample_name=NA12878 --targets_file=/cromwell_root/broad-dsde-methods/cromwell-execution-24/TumorOnly/f30dd8c6-eec3-45ba-b7f2-f845d308d59d/call-TumorNormalizeSomaticReadCounts/small_NA12878.tn.tsv --output_file=small_NA12878.seg --log2_input=TRUE --min_width=2 --alpha=0.01 --nperm=10000 --pmethod=hybrid --kmax=25 --nmin=200 --eta=0.05 --trim=0.025 --undosplits=none --undoprune=0.05 --undoSD=3
Stdout: $sample_name
[1] "NA12878"

$targets_file
[1] "/cromwell_root/broad-dsde-methods/cromwell-execution-24/TumorOnly/f30dd8c6-eec3-45ba-b7f2-f845d308d59d/call-TumorNormalizeSomaticReadCounts/small_NA12878.tn.tsv"

$output_file
[1] "small_NA12878.seg"

$log2_input
[1] "TRUE"

$min_width
[1] 2

$alpha
[1] 0.01

$nperm
[1] 10000

$pmethod
[1] "hybrid"

$kmax
[1] 25

$nmin
[1] 200

$eta
[1] 0.05

$trim
[1] 0.025

$undosplits
[1] "none"

$undoprune
[1] "0.05"

$undoSD
[1] 3

$help
[1] FALSE


Stderr: Error in sort(abs(diff(genomdat)))[1:n.keep] : 
  only 0's may be mixed with negative subscripts
Calls: source ... segment -> inherits -> smooth.CNA -> trimmed.variance
Execution halted

	at org.broadinstitute.hellbender.utils.R.RScriptExecutor.exec(RScriptExecutor.java:163)
	at org.broadinstitute.hellbender.utils.segmenter.RCBSSegmenter.writeSegmentFile(RCBSSegmenter.java:114)
	at org.broadinstitute.hellbender.tools.exome.PerformSegmentation.applySegmentation(PerformSegmentation.java:185)
	at org.broadinstitute.hellbender.tools.exome.PerformSegmentation.doWork(PerformSegmentation.java:180)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:112)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:170)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:189)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:96)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:103)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:116)
	at org.broadinstitute.hellbender.Main.main(Main.java:158)
```

**Comment by samuelklee** [comment]
R CBS issue, obviated by #2858.

**Comment by jrvanalstine** [comment]
Sorry, I know this is old, but i'm currently dealing with this exact issue using `gatk-4.beta.5`. It sounds like this has been solved, but the solution isn't clear to me.

**Comment by samuelklee** [comment]
@jrvanalstine I'd strongly suggest that you upgrade.  As discussed in the linked issue above, the underlying segmentation algorithm is completely different from that used in the beta workflows.  Major changes were made to file formats and the overall structure of the pipeline as well.

That said, it may still be the case that heavily downsampled input still gives strange results---if you are just downsampling to create test BAMs, I'd suggest that you increase the bin size to maintain a reasonable number of counts in each bin.
