### ISSUE TITLE
IllegalArgumentException in HaplotypeCallerSpark

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3013]
@tomwhite commented on [Tue May 23 2017](https://github.com/broadinstitute/gatk-protected/issues/1091)

When running on a 160GB BAM I get:

```
java.lang.IllegalArgumentException: contig must be non-null and not equal to *, and start must be >= 1
     at org.broadinstitute.hellbender.utils.read.SAMRecordToGATKReadAdapter.setPosition(SAMRecordToGATKReadAdapter.java:89)
     at org.broadinstitute.hellbender.utils.clipping.ClippingOp.applyHARDCLIP_BASES(ClippingOp.java:381)
     at org.broadinstitute.hellbender.utils.clipping.ClippingOp.apply(ClippingOp.java:73)
     at org.broadinstitute.hellbender.utils.clipping.ReadClipper.clipRead(ReadClipper.java:147)
     at org.broadinstitute.hellbender.utils.clipping.ReadClipper.clipRead(ReadClipper.java:128)
     at org.broadinstitute.hellbender.utils.clipping.ReadClipper.hardClipSoftClippedBases(ReadClipper.java:332)
     at org.broadinstitute.hellbender.utils.clipping.ReadClipper.hardClipSoftClippedBases(ReadClipper.java:335)
     at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.finalizeRegion(AssemblyBasedCallerUtils.java:84)
     at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.assembleReads(AssemblyBasedCallerUtils.java:238)
     at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.callRegion(HaplotypeCallerEngine.java:478)
     at org.broadinstitute.hellbender.tools.HaplotypeCallerSpark.lambda$regionToVariants$580(HaplotypeCallerSpark.java:203) 
```

At first glance this looks like a problem with unmapped reads, but these are filtered out by the tool. So it's more likely to be in the clipping logic. It's hard to diagnose since it doesn't say which read caused it, and it's slow to reproduce as it is running on a large input.

Any thoughts @lbergelson, @droazen?

---

@lbergelson commented on [Sat May 27 2017](https://github.com/broadinstitute/gatk-protected/issues/1091#issuecomment-304466112)

@tomwhite Is it possible you could upload the bam file somewhere on google cloud along with the command line you used?  It's not obvious to me where the error is being caused.  It's painful to debug anything on a 160GB file, but I think we can probably do a binary search on the file and find the bad location pretty quickly.  I.e. throw compute at the problem instead of human time...

**Comment by tomwhite** [comment]
@lbergelson I uploaded the sharded BAM to https://console.cloud.google.com/storage/browser/gatk-tom-testdata/out/bqsr-sharded/?project=broad-gatk-collab.

I also did some more debugging and got the following information about the (first) read that is failing:

```
  Caused by: java.lang.IllegalArgumentException: contig must be non-null and not equal to *, and start must be >= 1
.Bad read: HK35MCCXX160204:3:1204:16082:6812161GL000208.110030113S24M14SX617308030TTTACTTTTCCA
ACGAATAACTCACAGAGGTCCAAATATACACCATCAGATACTACAACAGGAGAGCTTCATTCCTGCCCTGTCAAAAGACATCTTCAACCCTATTAGTCGACTGCACACATCTCAATGAAGTTCCTCAGACGACTTCTGC,BB@
?CBBBAA<7;->.5=B.AA-&6'=='50=?C;<+5;@C@(-C=C@CC@;A@@C6&C4(-(-(/7,(-A<<=B?A*9:(-2.<<=:@;C-)76?C8<###################################################MC:Z:45S106MMD:Z:24PG:Z:MarkDuplicates.1FRG:Z:HK35M.3NM:i:0MQ:i:37OQ:Z:,AFAFKKKFKKAAF<A,7AKAFK,,7,AF,77FFF<A,7AKKK,,FFKKKFFFKKKK7,F<,,
,,,77,,,FAFFAFK,A7(,7,A<AAAFF,,77FK7F###################################################UQ:i:0AS:i:24

Clipped Read: HK35MCCXX160204:3:1204:16082:6812161GL000208.110030100S51HX617308030TTTACTTTTCCAACGAATAA
CTCACAGAGGTCCAAATATACACCATCAGATACTACAACAGGAGAGCTTCATTCCTGCCCTGTCAAAAGACATCTTCAAC,BB@?CBBBAA<7;->.5=B.AA-&6'=='50=?C;<+5;@C@(-C=C@CC@;A@@C6&C
4(-(-(/7,(-A<<=B?A*9:(-2.<<=:@;C-)76?C8<MC:Z:45S106MMD:Z:24PG:Z:MarkDuplicates.1FRG:Z:HK35M.3NM:i:0MQ:i:37OQ:Z:,AFAFKKKFKKAAF<
A,7AKAFK,,7,AF,77FFF<A,7AKKK,,FFKKKFFFKKKK7,F<,,,,,77,,,FAFFAFK,A7(,7,A<AAAFF,,77FK7F###################################################UQ:i
:0AS:i:24

at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.finalizeRegion(AssemblyBasedCallerUtils.java:91)
at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.assembleReads(AssemblyBasedCallerUtils.java:246)
at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.callRegion(HaplotypeCallerEngine.java:493)
at org.broadinstitute.hellbender.tools.HaplotypeCallerSpark.lambda$regionToVariants$1326(HaplotypeCallerSpark.java:223)
at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169)
at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:42)
at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:213)
at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:935)
at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:926)
at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:866)
at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:926)
at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:670)
at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:330)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:281)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
at org.apache.spark.scheduler.Task.run(Task.scala:86)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by tomwhite** [comment]
I originally reported this, so not sure why it is assigned to me!

**Comment by droazen** [comment]
Whoops, sorry about that @tomwhite  :)
