### ISSUE TITLE
"Unable to find _SUCCESS file"

### ISSUE THREAD

**Issue by hsnusonic** [broadinstitute/gatk#3066]
I just try to run PrintReadsSpark on cloudera cluster and meet this error.

Command:
```
$ ./gatk-launch PrintReadsSpark -I NA12878.chr17_69k_70k.dictFix.bam -O /user/yaron/output.bam -- --sparkRunner SPARK --sparkMaster yarn  --num-executors 5 --executor-cores 2 --executor-memory 1g
```
Results:
```
Using GATK jar /home/yaron/gatk/build/libs/gatk-spark.jar
Running:
    spark-submit --master yarn --conf spark.kryoserializer.buffer.max=512m --conf spark.driver.maxResultSize=0 --conf spark.driver.userClassPathFirst=true --conf spark.io.compression.codec=lzf --conf spark.yarn.executor.memoryOverhead=600 --conf spark.driver.extraJavaOptions=-DGATK_STACKTRACE_ON_USER_EXCEPTION=true -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=false -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -Dsnappy.disable=true  --conf spark.executor.extraJavaOptions=-DGATK_STACKTRACE_ON_USER_EXCEPTION=true -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=false -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -Dsnappy.disable=true  --num-executors 5 --executor-cores 2 --executor-memory 1g /home/yaron/gatk/build/libs/gatk-spark.jar PrintReadsSpark -I NA12878.chr17_69k_70k.dictFix.bam -O /user/yaron/output.bam --sparkMaster yarn
09:14:13.551 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/yaron/gatk/build/libs/gatk-spark.jar!/com/intel/gkl/native/libgkl_compression.so
[June 8, 2017 9:14:13 AM CST] org.broadinstitute.hellbender.tools.spark.pipelines.PrintReadsSpark  --output /user/yaron/output.bam --input NA12878.chr17_69k_70k.dictFix.bam --sparkMaster yarn  --readValidationStringency SILENT --interval_set_rule UNION --interval_padding 0 --interval_exclusion_padding 0 --bamPartitionSize 0 --disableSequenceDictionaryValidation false --shardedOutput false --numReducers 0 --help false --version false --showHidden false --verbosity INFO --QUIET false --use_jdk_deflater false --use_jdk_inflater false --disableToolDefaultReadFilters false
[June 8, 2017 9:14:13 AM CST] Executing as yaron@dn1 on Linux 4.4.0-31-generic amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_121-b13; Version: 4.alpha.2-281-g752d020-SNAPSHOT
09:14:13.567 INFO  PrintReadsSpark - HTSJDK Defaults.COMPRESSION_LEVEL : 1
09:14:13.567 INFO  PrintReadsSpark - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
09:14:13.567 INFO  PrintReadsSpark - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : false
09:14:13.567 INFO  PrintReadsSpark - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
09:14:13.567 INFO  PrintReadsSpark - Deflater: IntelDeflater
09:14:13.567 INFO  PrintReadsSpark - Inflater: IntelInflater
09:14:13.567 INFO  PrintReadsSpark - Initializing engine
09:14:13.567 INFO  PrintReadsSpark - Done initializing engine
log4j:ERROR A "org.apache.log4j.ConsoleAppender" object is not assignable to a "org.apache.log4j.Appender" variable.
log4j:ERROR The class "org.apache.log4j.Appender" was loaded by
log4j:ERROR [sun.misc.Launcher$AppClassLoader@6d21714c] whereas object of type
log4j:ERROR "org.apache.log4j.ConsoleAppender" was loaded by [org.apache.spark.util.ChildFirstURLClassLoader@6ee12bac].
log4j:ERROR Could not instantiate appender named "console".
log4j:ERROR A "org.apache.log4j.ConsoleAppender" object is not assignable to a "org.apache.log4j.Appender" variable.
log4j:ERROR The class "org.apache.log4j.Appender" was loaded by
log4j:ERROR [sun.misc.Launcher$AppClassLoader@6d21714c] whereas object of type
log4j:ERROR "org.apache.log4j.ConsoleAppender" was loaded by [org.apache.spark.util.ChildFirstURLClassLoader@6ee12bac].
log4j:ERROR Could not instantiate appender named "console".
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
log4j:WARN No appenders could be found for logger (org.apache.spark.SparkContext).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
09:14:26.202 INFO  PrintReadsSpark - Shutting down engine
[June 8, 2017 9:14:26 AM CST] org.broadinstitute.hellbender.tools.spark.pipelines.PrintReadsSpark done. Elapsed time: 0.21 minutes.
Runtime.totalMemory()=494927872
***********************************************************************

A USER ERROR has occurred: Couldn't write file /user/yaron/output.bam because writing failed with exception /user/yaron/output.bam.parts/_SUCCESS: Unable to find _SUCCESS file

***********************************************************************
org.broadinstitute.hellbender.exceptions.UserException$CouldNotCreateOutputFile: Couldn't write file /user/yaron/output.bam because writing failed with exception /user/yaron/output.bam.parts/_SUCCESS: Unable to find _SUCCESS file
        at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.writeReads(GATKSparkTool.java:255)
        at org.broadinstitute.hellbender.tools.spark.pipelines.PrintReadsSpark.runTool(PrintReadsSpark.java:37)
        at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:353)
        at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:116)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:171)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:190)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:121)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:142)
        at org.broadinstitute.hellbender.Main.main(Main.java:220)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:736)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.nio.file.NoSuchFileException: /user/yaron/output.bam.parts/_SUCCESS: Unable to find _SUCCESS file
        at org.seqdoop.hadoop_bam.util.SAMFileMerger.mergeParts(SAMFileMerger.java:53)
        at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink.writeReadsSingle(ReadsSparkSink.java:230)
        at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink.writeReads(ReadsSparkSink.java:152)
        at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.writeReads(GATKSparkTool.java:250)
        ... 18 more
```
However, I can find that _SUCCESS file exists in output.bam.parts. Could someone tell me what may be the cause? Thanks!
```
$ hdfs dfs -ls output.bam.parts
Found 3 items
-rw-r--r--   3 yaron yaron          0 2017-06-08 09:14 output.bam.parts/_SUCCESS
-rw-r--r--   3 yaron yaron      62019 2017-06-08 09:14 output.bam.parts/part-r-00000.bam
-rw-r--r--   3 yaron yaron         16 2017-06-08 09:14 output.bam.parts/part-r-00000.bam.splitting-bai
```

**Comment by yu68** [comment]
This error also happens in AWS EMR. Is there a plan to fix this bug. @vdauwera 
Thanks!

**Comment by chandrans** [comment]
Another user on forum has reported this: https://gatkforums.broadinstitute.org/gatk/discussion/11386/gatk4-0-0-0-hcspark-step-run-on-spark-cluster-unable-to-find-success-file

**Comment by Vzzarr** [comment]
I report even my experience which is similar, I hope it might be useful for debugging:

```
 /spark//bin/spark-submit --master spark://d16a85842e24:7077 --conf spark.driver.userClassPathFirst=false --conf spark.io.compression.codec=lzf --conf spark.driver.maxResultSize=0 --conf spark.executor.extraJavaOptions=-DGATK_STACKTRACE_ON_USER_EXCEPTION=true -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=false -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1  --conf spark.driver.extraJavaOptions=-DGATK_STACKTRACE_ON_USER_EXCEPTION=true -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=false -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1  --conf spark.kryoserializer.buffer.max=512m --conf spark.yarn.executor.memoryOverhead=600 \
--driver-memory 20g --executor-cores 4 --executor-memory 8g \
/gatk/build/libs/gatk-spark.jar HaplotypeCallerSpark --bam-partition-size 4000000 \
--input hdfs://namenode:8020/PREPROCESSING/PFC_0028_SW_CGTACG_R_recal_reads.bam \
--reference hdfs://namenode:8020/hg19-ucsc/ucsc.hg19.2bit \
--output /NGS-SparkGATK/docker/run/output/PREPROCESSING/PFC_0028_SW_CGTACG_R_raw_variants.g.vcf \
--emit-ref-confidence GVCF --spark-master spark://d16a85842e24:7077
```

As you can see in my case I executed HaplotypeCallerSpark and I declared the output file in normal File System, not HDFS (I hope it's not a problem, because of pipeline requirements). And so I faced with this exception:

```
***********************************************************************

A USER ERROR has occurred: Couldn't write file /NGS-SparkGATK/docker/run/output/PREPROCESSING/PFC_0028_SW_CGTACG_R_raw_variants.g.vcf because writing failed with exception /NGS-SparkGATK/docker/run/output/PREPROCESSING/PFC_0028_SW_CGTACG_R_raw_variants.g.vcf.parts/_SUCCESS: Unable to find _SUCCESS file

***********************************************************************
```

Moreover while executing this tool in local mode with the same input sample took about 200 minutes, this time took 3606 minutes in cluster mode. Is it because I used  --bam-partition-size 4000000? Or because HaplotypeCallerSpark doesn't get a good speed-up in cluster mode?

**Comment by liliu1986** [comment]
Hi folks, is there any update on resolving this issue? I still have encountered this in gatk-4.0.6.0

**Comment by tomwhite** [comment]
Does the problem go away if you use an output path with the 'hdfs://' scheme? E.g. _hdfs://namenode:8020/user/yaron/output.bam_ (where _namenode_ is the hostname of the namenode).

There are two libraries being used internally for accessing the filesystem - the Hadoop filesystem API, and the NIO API - and they have slightly different behaviour if no scheme is provided. So to avoid problems it's best to give full paths with URI schemes for all input and output paths.

**Comment by davidbenjamin** [comment]
Haven't heard from the users about this proposed solution in 1 1/2 years.
