### ISSUE TITLE
Possible Intel deflater bug triggered by GatherVcfsIntegrationTest

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3117]
In the branch `dr_intel_deflater_bug_repro`, running `./gradlew clean test -Dtest.single=GatherVcfsIntegrationTest` will trigger the following test failure:

```
Gradle suite > Gradle test > org.broadinstitute.hellbender.tools.GatherVcfsIntegrationTest.testBlockGather[14](/Users/droazen/src/hellbender/src/test/resources/large/gvcfs/combined.gatk3.7_30_ga4f720357.expected.vcf, 8536) FAILED
    java.lang.AssertionError: different sizes 16940 vs 17070
        at org.broadinstitute.hellbender.utils.test.VariantContextTestUtils.assertEqualVariants(VariantContextTestUtils.java:173)
        at org.broadinstitute.hellbender.tools.GatherVcfsIntegrationTest.testBlockGather(GatherVcfsIntegrationTest.java:103)
Results: FAILURE (15 tests, 14 successes, 1 failures, 0 skipped)
```

The tool writes a vcf that, when read back in by GATK, appears to have fewer records than it should.

The same test does NOT fail if you do ANY of the following:

* Edit `GatherVcfsIntegrationTest.testBlockGather()` to turn on the JDK deflater by changing `.addBooleanArgument("use_jdk_deflater", false);` to `.addBooleanArgument("use_jdk_deflater", true);`

* Keep the Intel deflater on, but edit `build.gradle` to change `samjdk.compression_level` to 1 or 2. (You'll also need to change the `Assert.assertEquals(System.getProperty("samjdk.compression_level"), "5");` line in `GatherVcfsIntegrationTest.testBlockGather()` accordingly)

* Edit the `getVcfsToShard` `DataProvider` in `GatherVcfsIntegrationTest` to change the failing `{LARGE_VCF, 8536}` test case to `{LARGE_VCF, 8535}`. This cuts the number of files that the vcf gets split into in half, and the test passes.

* Comment out all but the last test case in the `getVcfsToShard` `DataProvider` in `GatherVcfsIntegrationTest`. This indicates that there is something stateful going on, since the test case does not fail if run in isolation.

One additional bit of information: the test fails with the Intel deflater and compression levels 5 and 9, but with compression level 9 GATK is able to read many fewer records from the final output file than it does at compression level 5. As mentioned above, at compression levels 1 or 2 it's able to read all the records correctly. If you manually decompress the output file it appears to have all the correct records in all cases, so it's something wrong with the compression itself.

**Comment by droazen** [comment]
For @gspowley and @erniebrau

**Comment by droazen** [comment]
After further testing, we've found that this problem also occurs with the JDK deflater/inflater at compression level 9. This makes it much more likely to be a bug in the tool or the test itself, rather than the Intel deflater/inflater.

**Comment by droazen** [comment]
Closing -- not a bug in the Intel inflater/deflater.
