### ISSUE TITLE
GenotypeGVCFs fails with NullPointerException

### ISSUE THREAD

**Issue by eitanbanks** [broadinstitute/gatk#3210]
In a joint calling run with 11,000 samples, and broken up into over 10,000 scatters, a single one failed with a NPE.  I was able to get around it for now by just ignoring that scatter for the output, but that's really not an ideal thing to do for joint calling (and we cannot do that for the CCDG callset).  I can't give you the inputs because it was running on so many samples (and via GenomicsDB), but hopefully the stacktrace will help here:

java.lang.NullPointerException
        at org.broadinstitute.hellbender.tools.walkers.genotyper.AlleleSubsettingUtils.calculateLikelihoodSums(AlleleSubsettingUtils.java:234)
        at org.broadinstitute.hellbender.tools.walkers.genotyper.AlleleSubsettingUtils.calculateMostLikelyAlleles(AlleleSubsettingUtils.java:199)
        at org.broadinstitute.hellbender.tools.walkers.genotyper.GenotypingEngine.calculateGenotypes(GenotypingEngine.java:241)
        at org.broadinstitute.hellbender.tools.walkers.genotyper.GenotypingEngine.calculateGenotypes(GenotypingEngine.java:205)
        at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.calculateGenotypes(GenotypeGVCFs.java:276)
        at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.regenotypeVC(GenotypeGVCFs.java:234)
        at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.apply(GenotypeGVCFs.java:213)

I'm not sure who now owns this code, so will ping @davidbenjamin, @ldgauthier, @droazen.

**Comment by sooheelee** [comment]
Was the NPE for a sample or shard?

**Comment by eitanbanks** [comment]
This tool works on a shard of many samples.  You can tell from the stacktrace where in the code it choked.

**Comment by ronlevine** [comment]
I have a fix, pushing to the origin as soon a I fix my 2fa.
