### ISSUE TITLE
google-cloud-java: CloudStorageReadChannel.create() does a GCS access outside of the retry mechanism in CloudStorageReadChannel.read()

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3253]
`CloudStorageReadChannel.create()` appears to do a GCS access outside of the retry mechanism in `CloudStorageReadChannel.read()`. It calls the constructor, which calls `CloudStorageReadChannel.fetchSize()`, which does a `gcsStorage.get(file)` followed by a `getSize()`. 

We are seeing 503 failures specifically from the GCS access in `CloudStorageReadChannel.fetchSize()`:

```
com.google.cloud.storage.StorageException: 503 Service Unavailable
        at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:189)
        at com.google.cloud.storage.spi.v1.HttpStorageRpc.get(HttpStorageRpc.java:335)
        at com.google.cloud.storage.StorageImpl$5.call(StorageImpl.java:191)
        at com.google.cloud.storage.StorageImpl$5.call(StorageImpl.java:188)
        at shaded.cloud_nio.com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:94)
        at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:54)
        at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:188)
        at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:202)
        at com.google.cloud.storage.contrib.nio.CloudStorageReadChannel.fetchSize(CloudStorageReadChannel.java:234)
        at com.google.cloud.storage.contrib.nio.CloudStorageReadChannel.<init>(CloudStorageReadChannel.java:78)
        at com.google.cloud.storage.contrib.nio.CloudStorageReadChannel.create(CloudStorageReadChannel.java:68)
        at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.newReadChannel(CloudStorageFileSystemProvider.java:304)
        at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.newByteChannel(CloudStorageFileSystemProvider.java:265)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at htsjdk.samtools.seekablestream.SeekablePathStream.<init>(SeekablePathStream.java:41)
        at htsjdk.samtools.seekablestream.SeekableStreamFactory$DefaultSeekableStreamFactory.getStreamFor(SeekableStreamFactory.java:101)
        at htsjdk.tribble.readers.TabixReader.readIndex(TabixReader.java:270)


[2:58] 
From stdout:


[2:58] 
15:55:58.059 INFO  GenomicsDBImport - Done importing batch 19/444
15:56:21.780 INFO  GenomicsDBImport - Shutting down engine
code:      503
message:   503 Service Unavailable
reason:    null
location:  null
retryable: false
```

**Comment by droazen** [comment]
For @jean-philippe-martin. I'll try to throw together a patched version of `google-cloud-java` locally for us to test, to see if this is the last of the 503-related problems.

**Comment by droazen** [comment]
@jean-philippe-martin When you patch this one, could you also audit the rest of `CloudStorageReadChannel` for any other methods that could trigger a GCS access and require retries?

**Comment by droazen** [comment]
@jean-philippe-martin I've implemented an initial patch for this issue here: https://github.com/droazen/google-cloud-java/tree/dr_retry_CloudStorageReadChannel_fetchSize

Since we still don't have our Google CLA issues worked out, I'm unable to PR it directly against `google-cloud-java`, so you'll have to do that part. We'll test it out on our end and see if the 503s are finally conquered once and for all!

**Comment by droazen** [comment]
The patch clears up the 503 failures due to `fetchSize()`, but we are STILL seeing 503's with other metadata operations such as `Files.exists()`:

```
com.google.cloud.storage.StorageException: 503 Service Unavailable
        at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:189)
        at com.google.cloud.storage.spi.v1.HttpStorageRpc.get(HttpStorageRpc.java:335)
        at com.google.cloud.storage.StorageImpl$5.call(StorageImpl.java:191)
        at com.google.cloud.storage.StorageImpl$5.call(StorageImpl.java:188)
        at shaded.cloud_nio.com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:94)
        at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:54)
        at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:188)
        at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.checkAccess(CloudStorageFileSystemProvider.java:586)
        at java.nio.file.Files.exists(Files.java:2385)
        at htsjdk.tribble.util.ParsingUtils.resourceExists(ParsingUtils.java:428)
        at htsjdk.tribble.AbstractFeatureReader.isTabix(AbstractFeatureReader.java:217)
        at htsjdk.tribble.AbstractFeatureReader$ComponentMethods.isTabix(AbstractFeatureReader.java:223)
```

I'm going to continue modifying the patch until we see all 503s go away, then post here once it's ready.

**Comment by jean-philippe-martin** [comment]
OK @droazen then I'll wait for your signal before copying the PR.

**Comment by jean-philippe-martin** [comment]
@droazen it may be prudent to also include `innerOpen` in the retry logic.

**Comment by jean-philippe-martin** [comment]
I looked at the code and opening the channel does not seem to send any RPC, not even to check that the file exists (I double-checked by calling it on a nonexistent file). So we'll be OK leaving `innerOpen` out of the retry logic.

**Comment by droazen** [comment]
@jean-philippe-martin I can wrap the `CloudStorageFileSystemProvider.checkAccess()` method in a retry, but can you think of any other methods *outside* of `CloudStorageReadChannel` that might also require a retry?

**Comment by jean-philippe-martin** [comment]
yes, in `CloudStorageFileSystemProvider`: `readAttributes`, `newDirectoryStream`, `deleteIfExists`, `copy`

**Comment by droazen** [comment]
Ok @jean-philippe-martin, I have an updated patch that seems to resolve the 503 errors! It's here: https://github.com/droazen/google-cloud-java/tree/dr_retry_CloudStorageReadChannel_fetchSize

Will you have time before you leave on vacation to open a PR against google-cloud-java? If not, let me know and we'll try to sort out our CLA issues and PR it ourselves. I didn't have time to write unit tests, unfortunately, though we're running it now with 1000 concurrent jobs each accessing 11,000 files and not seeing any errors.

**Comment by jean-philippe-martin** [comment]
No problem @droazen.

**Comment by jean-philippe-martin** [comment]
This is odd, it looks like you retry unconditionally on delete (CloudStorageFileSystemProvider, line 419). It would make more sense to use the same logic as before to only retry if it's retriable, and reopen if it's reopenable.

Do you mind if I do this change? We'll probably have to do it anyways for the PR to get through.

**Comment by droazen** [comment]
@jean-philippe-martin Yeah, I was being a bit over-aggressive with the retries to maximize my chances of fixing the failures. We could make the retries conditional, and I did extract `CloudStorageRetryHandler.isRetryable()` and `CloudStorageRetryHandler.isReopenable()` methods, but are we 100% sure that in `CloudStorageFileSystemProvider` we wouldn't want to retry any of the errors that in `CloudStorageReadChannel` result in a reopen? That wasn't clear to me.

**Comment by jean-philippe-martin** [comment]
@droazen I'll put together my version and you can have a look. I'm making it always attempt a retry on retriable exceptions, so we don't have to worry about errors that would result in a reopen in `CloudStorageReadChannel`.

**Comment by droazen** [comment]
But could any of the errors that result in a re-open in `CloudStorageReadChannel` succeed in `CloudStorageFileSystemProvider` if we retry when we encounter them?

**Comment by jean-philippe-martin** [comment]
I doubt it but I can change the code to retry in those circumstances so we're super aggressive. That means that there we'd be retrying 40 times instead of 20, for an error that is not marked as retriable (so that normally wouldn't be retried at all).

**Comment by jean-philippe-martin** [comment]
OK it's up at #2239, please have a look. I've updated the code to retry when reopens are indicated (since the two don't overlap I take back that line about it retrying 40 times). This means that it'll be close to the level of aggressive that you tested with.
