### ISSUE TITLE
FilterByOrientationBias gives random failures

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#3291]
Out of 11 runs on exactly the same data, FilterByOrientationBias fails 6 times and succeeds 5 times. Assigning @LeeTL1220, given prior interaction with user.

- User reports this error in: https://gatkforums.broadinstitute.org/gatk/discussion/comment/40412#Comment_40412
- My recapitulation is in: https://github.com/broadinstitute/dsde-docs/issues/2294

Data is at `/humgen/gsa-scr1/pub/incoming/byoo_FilterByOrientationBias.zip`.

Command is:
```
gatk-launch FilterByOrientationBias \
    -A 'G/T' -A 'C/T' \
    -V test2.vcf \
    -P test2.pre_adapter_detail_metrics \
    --output ob_filtered2.vcf
```

Error message changes between:
```
java.lang.IllegalStateException: Allele in genotype C* not in the variant context [G*, T]
	at htsjdk.variant.variantcontext.VariantContext.validateGenotypes(VariantContext.java:1360)
	at htsjdk.variant.variantcontext.VariantContext.validate(VariantContext.java:1298)
	at htsjdk.variant.variantcontext.VariantContext.<init>(VariantContext.java:401)
	at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:494)
	at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:488)
	at org.broadinstitute.hellbender.tools.exome.orientationbiasvariantfilter.OrientationBiasFilterer.annotateVariantContextsWithFilterResults(OrientationBiasFilterer.java:216)
	at org.broadinstitute.hellbender.tools.exome.FilterByOrientationBias.onTraversalSuccess(FilterByOrientationBias.java:168)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:781)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:115)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:170)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:189)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:122)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:143)
	at org.broadinstitute.hellbender.Main.main(Main.java:221)
```
and
```
java.lang.IllegalStateException: Allele in genotype G* not in the variant context [C*, T]
	at htsjdk.variant.variantcontext.VariantContext.validateGenotypes(VariantContext.java:1360)
	at htsjdk.variant.variantcontext.VariantContext.validate(VariantContext.java:1298)
	at htsjdk.variant.variantcontext.VariantContext.<init>(VariantContext.java:401)
	at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:494)
	at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:488)
	at org.broadinstitute.hellbender.tools.exome.orientationbiasvariantfilter.OrientationBiasFilterer.annotateVariantContextsWithFilterResults(OrientationBiasFilterer.java:216)
	at org.broadinstitute.hellbender.tools.exome.FilterByOrientationBias.onTraversalSuccess(FilterByOrientationBias.java:211)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:840)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:115)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:170)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:189)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:131)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:152)
	at org.broadinstitute.hellbender.Main.main(Main.java:230)
```

I tested using `gatk-package-4.beta.1-local.jar` and pre-release alpha version `gatk-4.alpha.2-1134-ga9d9d91-SNAPSHOT/gatk-package-4.alpha.2-1134-ga9d9d91-SNAPSHOT-local.jar`.

**Comment by sooheelee** [comment]
As an aside, the stdout is toooooooo loooooooooong.

**Comment by sooheelee** [comment]
The fix has been merged. Have notified the user.
