### ISSUE TITLE
teach hadoop bam the horrors of hg38 contig names

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#3360]
spark things are falling over when they encounter the new hg38 contig names that include `:` and `-`   

We need to update hadoop bam to understand these since they are an unfortunate fact of life.

```
[ameyner2@node2c15 read_counts]$ /exports/igmm/eddie/bioinfsvice/ameynert/software/gatk-4.beta.2/gatk-launch SparkGenomeReadCounts -I ../../bcbio/final/WW00247b/WW00247b-ready.bam -o WW00247b.prop_cov --reference /exports/igmm/eddie/bioinfsvice/ameynert/bcbio/data/genomes/Hsapiens/hg38/seq/hg38.fa
Using GATK jar /gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/gatk-4.beta.2/gatk-package-4.beta.2-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -Dsnappy.disable=true -jar /gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/gatk-4.beta.2/gatk-package-4.beta.2-local.jar SparkGenomeReadCounts -I ../../bcbio/final/WW00247b/WW00247b-ready.bam -o WW00247b.prop_cov --reference /exports/igmm/eddie/bioinfsvice/ameynert/bcbio/data/genomes/Hsapiens/hg38/seq/hg38.fa
16:51:57.743 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/gatk-4.beta.2/gatk-package-4.beta.2-local.jar!/com/intel/gkl/native/libgkl_compression.so
[21 July 2017 16:51:57 BST] SparkGenomeReadCounts  --outputFile WW00247b.prop_cov --reference /exports/igmm/eddie/bioinfsvice/ameynert/bcbio/data/genomes/Hsapiens/hg38/seq/hg38.fa --input ../../bcbio/final/WW00247b/WW00247b-ready.bam  --keepXYMT false --binsize 10000 --readValidationStringency SILENT --interval_set_rule UNION --interval_padding 0 --interval_exclusion_padding 0 --bamPartitionSize 0 --disableSequenceDictionaryValidation false --shardedOutput false --numReducers 0 --sparkMaster local[*] --help false --version false --showHidden false --verbosity INFO --QUIET false --use_jdk_deflater false --use_jdk_inflater false --disableToolDefaultReadFilters false
[21 July 2017 16:51:57 BST] Executing as ameyner2@node2c15.ecdf.ed.ac.uk on Linux 3.10.0-327.36.3.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_121-b13; Version: 4.beta.2
16:51:57.770 INFO  SparkGenomeReadCounts - HTSJDK Defaults.COMPRESSION_LEVEL : 1
16:51:57.770 INFO  SparkGenomeReadCounts - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
16:51:57.770 INFO  SparkGenomeReadCounts - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
16:51:57.770 INFO  SparkGenomeReadCounts - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
16:51:57.770 INFO  SparkGenomeReadCounts - Deflater: IntelDeflater
16:51:57.770 INFO  SparkGenomeReadCounts - Inflater: IntelInflater
16:51:57.770 INFO  SparkGenomeReadCounts - Initializing engine
16:51:57.770 INFO  SparkGenomeReadCounts - Done initializing engine
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
17/07/21 16:51:58 INFO SparkContext: Running Spark version 2.0.2
17/07/21 16:51:58 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/07/21 16:51:58 INFO SecurityManager: Changing view acls to: ameyner2
17/07/21 16:51:58 INFO SecurityManager: Changing modify acls to: ameyner2
17/07/21 16:51:58 INFO SecurityManager: Changing view acls groups to: 
17/07/21 16:51:58 INFO SecurityManager: Changing modify acls groups to: 
17/07/21 16:51:58 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(ameyner2); groups with view permissions: Set(); users  with modify permissions: Set(ameyner2); groups with modify permissions: Set()
17/07/21 16:51:58 INFO Utils: Successfully started service 'sparkDriver' on port 43815.
17/07/21 16:51:58 INFO SparkEnv: Registering MapOutputTracker
17/07/21 16:51:58 INFO SparkEnv: Registering BlockManagerMaster
17/07/21 16:51:58 INFO DiskBlockManager: Created local directory at /tmp/ameyner2/blockmgr-d8bbd2bc-8366-4b98-a238-2d51da1689d1
17/07/21 16:51:58 INFO MemoryStore: MemoryStore started with capacity 15.8 GB
17/07/21 16:51:58 INFO SparkEnv: Registering OutputCommitCoordinator
17/07/21 16:51:58 INFO Utils: Successfully started service 'SparkUI' on port 4040.
17/07/21 16:51:58 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://192.41.105.80:4040
17/07/21 16:51:58 INFO Executor: Starting executor ID driver on host localhost
17/07/21 16:51:58 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 34818.
17/07/21 16:51:58 INFO NettyBlockTransferService: Server created on 192.41.105.80:34818
17/07/21 16:51:58 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 192.41.105.80, 34818)
17/07/21 16:51:58 INFO BlockManagerMasterEndpoint: Registering block manager 192.41.105.80:34818 with 15.8 GB RAM, BlockManagerId(driver, 192.41.105.80, 34818)
17/07/21 16:51:58 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 192.41.105.80, 34818)
16:51:59.636 INFO  SparkGenomeReadCounts - Dropping non-autosomes, as requested...
16:51:59.672 INFO  SparkGenomeReadCounts - Starting Spark coverage collection...
17/07/21 16:52:00 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 463.4 KB, free 15.8 GB)
17/07/21 16:52:00 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 52.9 KB, free 15.8 GB)
17/07/21 16:52:00 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 192.41.105.80:34818 (size: 52.9 KB, free: 15.8 GB)
17/07/21 16:52:00 INFO SparkContext: Created broadcast 0 from newAPIHadoopFile at ReadsSparkSource.java:109
17/07/21 16:52:00 INFO FileInputFormat: Total input paths to process : 1
17/07/21 16:52:08 INFO SparkUI: Stopped Spark web UI at http://192.41.105.80:4040
17/07/21 16:52:08 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
17/07/21 16:52:08 INFO MemoryStore: MemoryStore cleared
17/07/21 16:52:08 INFO BlockManager: BlockManager stopped
17/07/21 16:52:08 INFO BlockManagerMaster: BlockManagerMaster stopped
17/07/21 16:52:08 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
17/07/21 16:52:08 INFO SparkContext: Successfully stopped SparkContext
16:52:08.357 INFO  SparkGenomeReadCounts - Shutting down engine
[21 July 2017 16:52:08 BST] org.broadinstitute.hellbender.tools.genome.SparkGenomeReadCounts done. Elapsed time: 0.18 minutes.
Runtime.totalMemory()=4171235328
java.lang.NumberFormatException: For input string: "A*01"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at org.seqdoop.hadoop_bam.BAMInputFormat.getIntervals(BAMInputFormat.java:104)
    at org.seqdoop.hadoop_bam.BAMInputFormat.filterByInterval(BAMInputFormat.java:284)
    at org.seqdoop.hadoop_bam.BAMInputFormat.getSplits(BAMInputFormat.java:158)
    at org.seqdoop.hadoop_bam.AnySAMInputFormat.getSplits(AnySAMInputFormat.java:252)
    at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:121)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246)
    at scala.Option.getOrElse(Option.scala:121)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:246)
    at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246)
    at scala.Option.getOrElse(Option.scala:121)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:246)
    at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246)
    at scala.Option.getOrElse(Option.scala:121)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:246)
    at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246)
    at scala.Option.getOrElse(Option.scala:121)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:246)
    at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246)
    at scala.Option.getOrElse(Option.scala:121)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:246)
    at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246)
    at scala.Option.getOrElse(Option.scala:121)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:246)
    at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246)
    at scala.Option.getOrElse(Option.scala:121)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:246)
    at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246)
    at scala.Option.getOrElse(Option.scala:121)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:246)
    at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246)
    at scala.Option.getOrElse(Option.scala:121)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:246)
    at org.apache.spark.Partitioner$.defaultPartitioner(Partitioner.scala:65)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$reduceByKey$3.apply(PairRDDFunctions.scala:328)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$reduceByKey$3.apply(PairRDDFunctions.scala:328)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
    at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
    at org.apache.spark.rdd.PairRDDFunctions.reduceByKey(PairRDDFunctions.scala:327)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$countByKey$1.apply(PairRDDFunctions.scala:372)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$countByKey$1.apply(PairRDDFunctions.scala:372)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
    at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
    at org.apache.spark.rdd.PairRDDFunctions.countByKey(PairRDDFunctions.scala:371)
    at org.apache.spark.rdd.RDD$$anonfun$countByValue$1.apply(RDD.scala:1175)
    at org.apache.spark.rdd.RDD$$anonfun$countByValue$1.apply(RDD.scala:1175)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
    at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
    at org.apache.spark.rdd.RDD.countByValue(RDD.scala:1174)
    at org.apache.spark.api.java.JavaRDDLike$class.countByValue(JavaRDDLike.scala:487)
    at org.apache.spark.api.java.AbstractJavaRDDLike.countByValue(JavaRDDLike.scala:45)
    at org.broadinstitute.hellbender.tools.genome.SparkGenomeReadCounts.collectReads(SparkGenomeReadCounts.java:162)
    at org.broadinstitute.hellbender.tools.genome.SparkGenomeReadCounts.runTool(SparkGenomeReadCounts.java:241)
    at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:353)
    at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:115)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:170)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:189)
    at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:131)
    at org.broadinstitute.hellbender.Main.mainEntry(Main.java:152)
    at org.broadinstitute.hellbender.Main.main(Main.java:230)
17/07/21 16:52:08 INFO ShutdownHookManager: Shutdown hook called
```

**Comment by lbergelson** [comment]
@tomwhite Could you take this one on?

**Comment by tomwhite** [comment]
@lbergelson is there a spec for the names somewhere? I'm wondering if there is some kind of escape sequence that is used. Can you also upload a file that causes the error?

**Comment by lbergelson** [comment]
@tomwhite Sorry!  I wasn't thinking, we keep hitting this issue in different places and I was assuming you had seen it before. The issue is that there was no spec for contig names, and when they made hg38 they allowed contig names like `HLA:1-3:52-*:6+` which are terrible because they are ambiguous with the format for specifying intervals.  Everyone in the world who wrote software that parses contig names and intervals was using the implicit assumption that `:` and `-` didn't appear in the contig names and write intervals as `contig:start-stop`.  So we had to modify all the code that parses intervals to first try to understand it as a complete contig name and if that matches a contig in the sequence dictionary stop parsing it.  

I will track down a file that triggers the issue.

**Comment by tomwhite** [comment]
@lbergelson no, I hadn't seen it, but your explanation makes sense. Do you know if htsjdk has addressed this issue? It would be good to share code if possible.

**Comment by lbergelson** [comment]
We've definitely addressed it somewhere... but I'm not sure off the top of my head if it's in  in htsjdk or in gatk.  I will try to find the code while I'm trying to find an hg38 bam...

**Comment by SHuang-Broad** [comment]
I've been using the following regular expression for hg 38 contig names

```
(chr([0-9]+|X|Y|M|Un)(_[A-Z]+[0-9]+v[0-9](_random|_alt|_decoy)?)?|HLA-[A-Z]+([0-9]+)?\*[0-9]+:[0-9]+(N|(:[0-9]+){0,}))
```

**Comment by tomwhite** [comment]
@SHuang-Broad thanks for the regex. Where have you been using the regex? I couldn't find it in htsjdk or GATK, and in fact neither of these seem to have tests for hg38-style contig/chromosome names. Ideally htsjdk would have code for this so that both Hadoop-BAM and GATK could call it directly.

**Comment by SHuang-Broad** [comment]
@tomwhite I haven't tested them because I am using them for looking at some structural variant VCF files generated from BAM files aligned to GRCh38. The regex is from eyeballing those 3000 lines of headers :tired_face:

If you would like such tests, I can provide one quickly, just tell me the preferred format, and preferably where to in htsjdk.

**Comment by SHuang-Broad** [comment]
@tomwhite , since this is becoming used by others, I went back and checked the regex, turns out that it is no catching all the contigs in the headers, so here is the updated one:
```
(chr([0-9]{1,2}|X|Y|M|Un|EBV)(_[A-Z]+[0-9]{6,8}v[0-9](_random|_alt|_decoy)?)?|HLA-[A-Z]{1,3}([0-9])?\*[0-9]{2,2}:[0-9]{2,3}(N|Q|(:[0-9]{2,2}){0,}(N|L|S|Q)?))
```
There are 3366 different contigs in the bam/vcf files I "tested" this with, and this catches all of them.

**Comment by magicDGS** [comment]
My two cents: because the symbols used for interval definition (`:` and `-`) are allowed in the specifications, I guess that the regexp should account for whatever kind of contig names and not only for the case of hg38. I use to work with non-model organisms and this is an issue frequently found too...

**Comment by heuermh** [comment]
If anyone wants to learn more about the horrors of HLA (and MHC more generally) naming, ping me elsewhere, probably best at https://github.com/nmdp-bioinformatics/genotype-list.

**Comment by vruano** [comment]
Is there a work-around?

**Comment by vruano** [comment]
I guess that ':' that should be considered the one that separates the contig from the position is the last one, the start and stop can be worked out from there.

**Comment by magicDGS** [comment]
If a whole contig with a name containing `:` is specified, then the last one does not separate the contig from the positions.

My suggestion is crosscheck both the whole `String` provided and the sub-string before the `:` - I am not sure how to deal with cases where both are present (and if this even possible), but otherwise is kind of easy: if all the `String` is present, the "interval" is the whole contig; if the sub-string is present, the rest should be the coordinate within the contig.
