### ISSUE TITLE
CollectSequencingArtifactMetrics: NullPointer exception without reference

### ISSUE THREAD

**Issue by lima1** [broadinstitute/gatk#3362]
I think CollectSequencingArtifactMetrics requires a reference, but the documentation lists it as optional.  Without reference, I get an instant crash. I also get NullPointer exceptions when proving --DB_SNP. 

```
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -Dsnappy.disable=true -jar /home/riestma1/gatk-4.beta.3/gatk-package-4.beta.3-local.jar CollectSequencingArtifactMetrics --input sample1.bam --output sample1_pre_adapter_detail_metrics
 ...
18:06:26.220 INFO  CollectSequencingArtifactMetrics - Shutting down engine
[July 26, 2017 6:06:26 PM EDT] org.broadinstitute.hellbender.tools.picard.analysis.artifacts.CollectSequencingArtifactMetrics done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=1517289472
java.lang.NullPointerException
	at org.broadinstitute.hellbender.tools.picard.analysis.artifacts.CollectSequencingArtifactMetrics.acceptRead(CollectSequencingArtifactMetrics.java:214)
	at org.broadinstitute.hellbender.tools.picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:114)
	at org.broadinstitute.hellbender.tools.picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:53)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:116)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:173)
	at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgram.instanceMain(PicardCommandLineProgram.java:62)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:131)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:152)
	at org.broadinstitute.hellbender.Main.main(Main.java:233)
```

**Comment by lbergelson** [comment]
@lima1 Does this same problem occur in the picard version of collect sequencing metrics?  We're going to be replacing our version of this tool with the original picard version soon, so hopefully that will resolve these problems.
