### ISSUE TITLE
ArrayIndexOutOfBounds using GenotypeGVCFs when reading from a GenomicsDB

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#3412]
We've seen 2 instances of this error now:
```
java.lang.ArrayIndexOutOfBoundsException: 15
	at htsjdk.variant.bcf2.BCF2Utils.decodeType(BCF2Utils.java:122)
	at htsjdk.variant.bcf2.BCF2Decoder.decodeInt(BCF2Decoder.java:220)
	at htsjdk.variant.bcf2.BCF2Decoder.decodeNumberOfElements(BCF2Decoder.java:205)
	at htsjdk.variant.bcf2.BCF2Decoder.decodeTypedValue(BCF2Decoder.java:129)
	at htsjdk.variant.bcf2.BCF2Decoder.decodeTypedValue(BCF2Decoder.java:125)
	at htsjdk.variant.bcf2.BCF2LazyGenotypesDecoder.parse(BCF2LazyGenotypesDecoder.java:75)
	at htsjdk.variant.variantcontext.LazyGenotypesContext.decode(LazyGenotypesContext.java:158)
	at htsjdk.variant.variantcontext.LazyGenotypesContext.getGenotypes(LazyGenotypesContext.java:148)
	at htsjdk.variant.variantcontext.GenotypesContext.getMaxPloidy(GenotypesContext.java:431)
	at htsjdk.variant.variantcontext.VariantContext.getMaxPloidy(VariantContext.java:785)
	at org.broadinstitute.hellbender.tools.walkers.ReferenceConfidenceVariantContextMerger.mergeRefConfidenceGenotypes(ReferenceConfidenceVariantContextMerger.java:405)
	at org.broadinstitute.hellbender.tools.walkers.ReferenceConfidenceVariantContextMerger.merge(ReferenceConfidenceVariantContextMerger.java:92)
	at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.apply(GenotypeGVCFs.java:212)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.lambda$traverse$0(VariantWalkerBase.java:110)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.traverse(VariantWalkerBase.java:108)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:838)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:116)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:173)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:131)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:152)
	at org.broadinstitute.hellbender.Main.main(Main.java:233)
```

It seems to happen in rare cases when reading from a genomicsDB instance with GenotypeGVCFs.  The array that is going out of bounds is one that maps ID values to BCF2Types.  The valid values for BCF2Types are 0,1,2,3,5,7 as defined in the [bcf spec section 6.3.3](https://samtools.github.io/hts-specs/VCFv4.3.pdf)  It seems likely that this is either a bug in htsjdk, in htsjlib, or in GenomicsDB.

**Comment by droazen** [comment]
@kgururaj @kdatta Any insight into this one?

**Comment by lbergelson** [comment]
It's possible this is some issue in the htsjdk or htslib bcf codec as well, so we should look in that end of it as well.

**Comment by kgururaj** [comment]
Would it be possible to obtain input files which triggered this bug? Or a core dump file as described here https://github.com/Intel-HLS/GenomicsDB/wiki/Bug-report?

**Comment by lbergelson** [comment]
I think these went away when we re-ran with more memory.

**Comment by kgururaj** [comment]
Should this issue be closed?

**Comment by lbergelson** [comment]
@kgururaj I think so.  We've been unable to reproduce it and haven't seen it again since we fixed the memory requirements in our pipeline.  If it reoccurs we'll reopen.

**Comment by ldgauthier** [comment]
I hit this same error attempting a 156K callset.  I'm rerunning with more memory and also downloading the GDB for debugging, which is 46GB.  :-/
