### ISSUE TITLE
TargetCoverageSexGenotyper fails for bad samples

### ISSUE THREAD

**Issue by dpmccabe** [broadinstitute/gatk#3442]
The TargetCoverageSexGenotyper can sometimes fail to calculate genotype LLs for low-quality (low-coverage) samples. The exception below can be reproduced trivially: just pass it a raw coverage matrix containing a single sample that has all only zeroes in its counts column. In practice, I've recently encountered several samples that somehow passed upstream QC but failed to genotype due to extensive dropout. This causes program termination and no genotypes are written for any samples in the input. Could we instead warn and print an `NA` genotype for such samples?

```[August 14, 2017 5:06:20 PM EDT] org.broadinstitute.hellbender.tools.exome.sexgenotyper.TargetCoverageSexGenotyper done. Elapsed time: 0.04 minutes.
Runtime.totalMemory()=869269504
org.apache.commons.math3.exception.NotStrictlyPositiveException: mean (0)
	at org.apache.commons.math3.distribution.PoissonDistribution.<init>(PoissonDistribution.java:126)
	at org.apache.commons.math3.distribution.PoissonDistribution.<init>(PoissonDistribution.java:103)
	at org.apache.commons.math3.distribution.PoissonDistribution.<init>(PoissonDistribution.java:80)
	at org.broadinstitute.hellbender.tools.exome.sexgenotyper.TargetCoverageSexGenotypeCalculator.lambda$calculateSexGenotypeData$20(TargetCoverageSexGenotypeCalculator.java:414)```

**Comment by lbergelson** [comment]
@mbabadi This looks like one for you.

**Comment by mbabadi** [comment]
Deprecated by the new tool `DetermineGermlineContigPloidy`. Closing.
