### ISSUE TITLE
IllegalArgumentException during clipping: contig must be non-null and not equal to *, and start must be >= 1

### ISSUE THREAD

**Issue by chapmanb** [broadinstitute/gatk#3466]
We're running into an error with GATK 4.0beta3 on some read pairs that appears related to processing clipping on a read. The BAM file itself gets processed fine on GATK 3.8 and the problematic read appears okay on a manual inspection. This is a self-contained reproducible test case that demonstrates the issue:

https://s3.amazonaws.com/chapmanb/testcases/gatk_cigar_error.tar.gz

The error is:
```
java.lang.IllegalArgumentException: contig must be non-null and not equal to *, and start must be >= 1
        at org.broadinstitute.hellbender.utils.read.SAMRecordToGATKReadAdapter.setPosition(SAMRecordToGATKReadAdapter.java:92)
        at org.broadinstitute.hellbender.utils.clipping.ClippingOp.applyHARDCLIP_BASES(ClippingOp.java:381)
        at org.broadinstitute.hellbender.utils.clipping.ClippingOp.apply(ClippingOp.java:73)
        at org.broadinstitute.hellbender.utils.clipping.ReadClipper.clipRead(ReadClipper.java:147)
        at org.broadinstitute.hellbender.utils.clipping.ReadClipper.clipRead(ReadClipper.java:128)
        at org.broadinstitute.hellbender.utils.clipping.ReadClipper.hardClipSoftClippedBases(ReadClipper.java:332)
        at org.broadinstitute.hellbender.utils.clipping.ReadClipper.hardClipSoftClippedBases(ReadClipper.java:335)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.finalizeRegion(AssemblyBasedCallerUtils.java:84)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.assembleReads(AssemblyBasedCallerUtils.java:238)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.callRegion(HaplotypeCallerEngine.java:480)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller.apply(HaplotypeCaller.java:221)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:244)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:217)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:838)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:116)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:173)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:131)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:152)
        at org.broadinstitute.hellbender.Main.main(Main.java:233)
```
and I believe this is the problematic read:
```
SRR826467.159276265     113     MT      18      52      108S62M80S      *       6996084 0       AAAATTGAGCTTTATCCGAAAGCTGCCTCCTGTTTCAGGGTCACAAGGCCTAAGTAGCCCACGCGTTCCCCTTAAATATGCCATCACGATTGACCACAGTTCTCTCGACCTATTAACCTCTCACGGGGGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGGTATGCACGTCATTTTTTTTTTTTTTCAAGCAGAAGACGGCATACGAGATCGTGATGTGACTGGAGTTCAGACGTGTGCTCTTCCGATC ##################################################################################################################################################################################DDDDFFEC>GGGIEJIGGF8GHCDFD?HFD;FGHGGHGFDDIGJJJIIJJJIIGGGIIIHHHFHFFFFFCCC        RG:Z:DRAGEN_RGID        AS:i:52 XS:i:30 NM:i:2
```
Thanks much for looking at this and please let me know I can provide any other information.

**Comment by chapmanb** [comment]
@droazen @vdauwera -- sorry to bump this but I'm hitting this problem with additional unrelated samples and could provide additional test cases if this isn't enough to debug. Thanks much.

**Comment by lbergelson** [comment]
I think this issue is likely the same as https://github.com/broadinstitute/gatk/issues/3813

**Comment by KrzysztofMKozak** [comment]
Are there any news on this, please? Unfortunately seems to crop up with a lot of my data...

**Comment by lbergelson** [comment]
We hope to have this fixed by the 4.0 release on tuesday.

**Comment by droazen** [comment]
Yes, it's on my TODO list. Should have a PR by Monday.

**Comment by droazen** [comment]
Fix for this issue is here: https://github.com/broadinstitute/gatk/pull/4080
