### ISSUE TITLE
Failure with missing host and port in --knownSites for HDFS on GCP

### ISSUE THREAD

**Issue by tomwhite** [broadinstitute/gatk#3468]
Stacktrace is below. It looks like the default port (8020) is not being picked up.
```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 8 in stage 5.0 failed 4 times, most recent failure: Lost task 8.3 in stage 5.0 (TID 82, tw-cluster-2-w-4.c.broad-gatk-collab.internal): java.lang.IllegalArgumentEx
ception: Wrong FS: hdfs://tw-cluster-2-m:-1/user/tom/small_spark_eval/dbsnp_138.b37.20.21.vcf, expected: hdfs://tw-cluster-2-m
     at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:648)
     at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:194)
     at org.apache.hadoop.hdfs.DistributedFileSystem.access$000(DistributedFileSystem.java:106)
     at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1305)
     at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1301)
     at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
     at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1301)
     at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1426)
     at hdfs.jsr203.HadoopFileSystem.checkAccess(HadoopFileSystem.java:937)
     at hdfs.jsr203.HadoopFileSystemProvider.checkAccess(HadoopFileSystemProvider.java:75)
     at java.nio.file.Files.exists(Files.java:2385)
     at org.broadinstitute.hellbender.utils.io.IOUtils.assertFileIsReadable(IOUtils.java:551)
     at org.broadinstitute.hellbender.engine.FeatureDataSource.getFeatureReader(FeatureDataSource.java:292)
     at org.broadinstitute.hellbender.engine.FeatureDataSource.<init>(FeatureDataSource.java:244)
     at org.broadinstitute.hellbender.engine.FeatureDataSource.<init>(FeatureDataSource.java:218)
     at org.broadinstitute.hellbender.engine.FeatureDataSource.<init>(FeatureDataSource.java:202)
     at org.broadinstitute.hellbender.engine.spark.KnownSitesCache.loadFromFeatureDataSource(KnownSitesCache.java:43)
```

**Comment by tomwhite** [comment]
I've created (and tested) a fix in jsr203-hadoop: https://github.com/damiencarol/jsr203-hadoop/pull/32
