### ISSUE TITLE
CreateSomaticPanelOfNormals (i) counts same sample twice, (ii) misses a site and (iii) does not take a list of vcfs

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#3510]
I bring the first point up given the safeguards our previous workflow had in place. In GATK3, CombineVariants checks that all the sample names are unique. You have to add `--genotypemergeoption UNIQUIFY` to allow use of the same normal sample.

In GATK4, CreateSomaticPanelOfNormals allows input of the same sample twice and thereby counts the same evidence in the PoN it generates. Granted, I am doing something intentionally stupid here but I can imagine that this could happen accidentally for situations where we are dealing with hundreds of normal samples. 

Interestingly, given the same sample twice, for my test case, it generates a PoN that has one less call than the inputs.

Here is the command that runs successfully. Note that 2 is a direct copy of 1 made using unix `cp`.
```
	gatk-launch CreateSomaticPanelOfNormals \
		-vcfs 1_normalforpon.vcf.gz \
		-vcfs 2_normalforpon.vcf.gz \
		-O 3_discard_practice_pon.vcf.gz
```

Then I check the number of sites and I see a discrepency.
```
WMCF9-CB5:working shlee$ gzcat 3_discard_practice_pon.vcf.gz | grep -v '#' | wc -l
     138
WMCF9-CB5:working shlee$ gzcat 1_normalforpon.vcf.gz | grep -v '#' | wc -l
     139
WMCF9-CB5:working shlee$ gzcat 2_normalforpon.vcf.gz | grep -v '#' | wc -l
     139
```

Probing further we see:
```
WMCF9-CB5:working shlee$ diff <(gzcat 1_normalforpon.vcf.gz | grep -v '#' | cut -f1,2) <(gzcat 3_discard_practice_pon.vcf.gz | grep -v '#' | cut -f1,2)
139d138
< chrX	153909841
WMCF9-CB5:working shlee$ gzcat 1_normalforpon.vcf.gz | grep 'chrX\t153909841'
chrX	153909841	.	C	A	.	.	DP=11;ECNT=1;POP_AF=1.000e-03;P_GERMLINE=-2.169e-04;TLOD=14.94	GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:MBQ:MCL:MFRL:MMQ:MPOS:REF_F1R2:REF_F2R1:SA_MAP_AF:SA_POST_PROB	0/1:6,5:0.455:3:2:0.400:30,33:0,0:191,278:60,60:11,20:1:5:0.404,0.444,0.455:0.025,0.025,0.950
WMCF9-CB5:working shlee$ gzcat 2_normalforpon.vcf.gz | grep 'chrX\t153909841'
chrX	153909841	.	C	A	.	.	DP=11;ECNT=1;POP_AF=1.000e-03;P_GERMLINE=-2.169e-04;TLOD=14.94	GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:MBQ:MCL:MFRL:MMQ:MPOS:REF_F1R2:REF_F2R1:SA_MAP_AF:SA_POST_PROB	0/1:6,5:0.455:3:2:0.400:30,33:0,0:191,278:60,60:11,20:1:5:0.404,0.444,0.455:0.025,0.025,0.950
WMCF9-CB5:working shlee$ gzcat 3_discard_practice_pon.vcf.gz | grep 'chrX'
##contig=<ID=chrX,length=156040895>
##contig=<ID=chrX_KI270880v1_alt,length=284869>
##contig=<ID=chrX_KI270881v1_alt,length=144206>
##contig=<ID=chrX_KI270913v1_alt,length=274009>
chrX	132097402	.	TACAC	T,TAC	.	.	.
```
This site should have been called in the PoN. Finally, for the `-vcfs` parameter, if I provide a list of files, one per line, the tool errors with
```
htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: Your input file has a malformed header: We never saw the required CHROM header line (starting with one #) for the input VCF file, for input source: /Users/shlee/Desktop/August2017_tutorial_dev/working/list_of_normals_for_pon.txt
	at htsjdk.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:253)
	at htsjdk.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:101)
	at htsjdk.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:126)
	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:110)
	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:74)
	at htsjdk.variant.vcf.VCFFileReader.<init>(VCFFileReader.java:58)
	at org.broadinstitute.hellbender.tools.walkers.mutect.CreateSomaticPanelOfNormals.doWork(CreateSomaticPanelOfNormals.java:122)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:116)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:173)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:131)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:152)
	at org.broadinstitute.hellbender.Main.main(Main.java:233)
Caused by: htsjdk.tribble.TribbleException$InvalidHeader: Your input file has a malformed header: We never saw the required CHROM header line (starting with one #) for the input VCF file
	at htsjdk.variant.vcf.VCFCodec.readActualHeader(VCFCodec.java:115)
	at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:83)
	at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:36)
	at htsjdk.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:251)
	... 12 more
```

Either we should update the documentation to point users to use the `--arguments_file` instead (let me know) or we should update the functionality to accept a list of files. Currently, the option is described as:

> --vcfsListFile,-vcfs:File     VCFs for samples to include. May be specified either one at a time, or as one or more .list file containing multiple VCFs, one per line.  This argument must be specified at least once. Required. 

Here is the test data:
[createsomaticpanelofnormals_testcase_shlee.zip](https://github.com/broadinstitute/gatk/files/1251993/createsomaticpanelofnormals_testcase_shlee.zip)

**Comment by sooheelee** [comment]
Forgot to mention I am using GATK4.beta.3.

**Comment by davidbenjamin** [comment]
@sooheelee I fixed the javadoc and added a logger warning letting users know that they must input a .args file for their vcfs list.  When I copy your .list file to a .args file everything works.  I'm going to address the other stuff for the release as well.

**Comment by davidbenjamin** [comment]
@sooheelee I just fixed the missing variant with a one-line change in my branch.  The tool was forgetting to check the last locus after all the variants had been read in.

**Comment by davidbenjamin** [comment]
@sooheelee I added a command line argument for duplicate options: `THROW_ERROR`, `CHOOSE_FIRST`, and `ALLOW_ALL`.  I will now issue the PR but won't assign a reviewer from the M2 team until after the break.  If you want to review go ahead but there's some Java code.

**Comment by sooheelee** [comment]
Thanks, @davidbenjamin. I started learning Java over the break as planned. I'm a quarter in to my intro to Java class. So at this point, I think it best to leave the review to those who are more versed in the language.
