### ISSUE TITLE
HaplotypeCallerSpark, SparkgenomeReadCounts fail reference name lookup

### ISSUE THREAD

**Issue by chapmanb** [broadinstitute/gatk#3659]
I'm running HaplotypeCallerSpark with GATK4 beta 5 and running into an issue where it complains about a reference name lookup, reporting that a strange reference name is not found:
```
java.lang.IllegalArgumentException: Reference name for '1145119298' not found in sequence dictionary.
```
This happens with HaplotypeCallerSpark independent of the number of cores or memory requested but works fine with HaplotypeCaller using the same BED and BAM inputs. The BED file has a number of regions on chr15, chr16 and chr17 and I'm happy to share anything that would be useful. I'm still working on generating a minimal example that demonstrates the issue.

The command we're running is:
```
gatk-launch --javaOptions '-Xms1000m -Xmx46965m -Djava.io.tmpdir=/mnt/work/cwl/bcbio_validation_workflows/giab-joint/bunny_work/main-giab-joint-2017-10-03-104521.457/root/variantcall/8/variantcall_batch_region/16/bcbiotx/tmp7exzBH' HaplotypeCallerSpark --reference /mnt/work/cwl/bcbio_validation_workflows/giab-joint/biodata/collections/hg38/ucsc/hg38.2bit --annotation FisherStrand --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation QualByDepth --annotation ReadPosRankSumTest --annotation RMSMappingQuality --annotation BaseQualityRankSumTest --annotation MappingQuality --annotation DepthPerAlleleBySample --annotation Coverage -I /mnt/work/cwl/bcbio_validation_workflows/giab-joint/bunny_work/main-giab-joint-2017-10-02-100534.907/root/postprocess_alignment/2/align/NA24631/NA24631-sort-recal.bam -L /mnt/work/cwl/bcbio_validation_workflows/giab-joint/bunny_work/main-giab-joint-2017-10-03-104521.457/root/variantcall/8/variantcall_batch_region/16/gatk-haplotype/chr15/NA24631-chr15_68578892_84670250-block-regions.bed --interval_set_rule INTERSECTION --sparkMaster local[16] --conf spark.local.dir=/mnt/work/cwl/bcbio_validation_workflows/giab-joint/bunny_work/main-giab-joint-2017-10-03-104521.457/root/variantcall/8/variantcall_batch_region/16/bcbiotx/tmp7exzBH --annotation ClippingRankSumTest --annotation DepthPerSampleHC --output /mnt/work/cwl/bcbio_validation_workflows/giab-joint/bunny_work/main-giab-joint-2017-10-03-104521.457/root/variantcall/8/variantcall_batch_region/16/bcbiotx/tmp7exzBH/NA24631-chr15_68578892_84670250-block.vcf.gz --emitRefConfidence GVCF -GQB 10 -GQB 20 -GQB 30 -GQB 40 -GQB 60 -GQB 80
```
and the full traceback is:
```
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1454)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1442)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1441)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1441)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1667)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1622)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1611)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:632)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1873)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1886)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1899)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1913)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:912)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:911)
	at org.apache.spark.RangePartitioner$.sketch(Partitioner.scala:264)
	at org.apache.spark.RangePartitioner.<init>(Partitioner.scala:126)
	at org.apache.spark.rdd.OrderedRDDFunctions$$anonfun$sortByKey$1.apply(OrderedRDDFunctions.scala:62)
	at org.apache.spark.rdd.OrderedRDDFunctions$$anonfun$sortByKey$1.apply(OrderedRDDFunctions.scala:61)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
	at org.apache.spark.rdd.OrderedRDDFunctions.sortByKey(OrderedRDDFunctions.scala:61)
	at org.apache.spark.api.java.JavaPairRDD.sortByKey(JavaPairRDD.scala:913)
	at org.apache.spark.api.java.JavaPairRDD.sortByKey(JavaPairRDD.scala:903)
	at org.broadinstitute.hellbender.utils.spark.SparkUtils.coordinateSortReads(SparkUtils.java:130)
	at org.broadinstitute.hellbender.tools.HaplotypeCallerSpark.callVariantsWithHaplotypeCallerAndWriteOutput(HaplotypeCallerSpark.java:163)
	at org.broadinstitute.hellbender.tools.HaplotypeCallerSpark.runTool(HaplotypeCallerSpark.java:125)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:353)
	at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:119)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:176)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:195)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:131)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:152)
	at org.broadinstitute.hellbender.Main.main(Main.java:233)
Caused by: java.lang.IllegalArgumentException: Reference name for '1145119298' not found in sequence dictionary.
	at htsjdk.samtools.SAMRecord.resolveNameFromIndex(SAMRecord.java:569)
	at htsjdk.samtools.SAMRecord.setReferenceIndex(SAMRecord.java:422)
	at htsjdk.samtools.BAMRecord.<init>(BAMRecord.java:87)
	at htsjdk.samtools.DefaultSAMRecordFactory.createBAMRecord(DefaultSAMRecordFactory.java:42)
	at htsjdk.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:210)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.getNextRecord(BAMFileReader.java:829)
	at htsjdk.samtools.BAMFileReader$BAMFileIndexIterator.getNextRecord(BAMFileReader.java:981)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:803)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:797)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:765)
	at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.advance(BAMFileReader.java:1034)
	at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.<init>(BAMFileReader.java:1003)
	at htsjdk.samtools.BAMFileReader.createIndexIterator(BAMFileReader.java:944)
	at org.seqdoop.hadoop_bam.BAMRecordReader.initialize(BAMRecordReader.java:169)
	at org.seqdoop.hadoop_bam.BAMInputFormat.createRecordReader(BAMInputFormat.java:121)
	at org.seqdoop.hadoop_bam.AnySAMInputFormat.createRecordReader(AnySAMInputFormat.java:190)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:170)
	at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:130)
	at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:67)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
Thanks for any suggestions or pointers to debug further.

**Comment by cmnbroad** [comment]
Also happened in SparkGenomeReadCounts (see #3679).

**Comment by droazen** [comment]
@tomwhite Could you please have a look at this one? Thanks!

**Comment by chapmanb** [comment]
Chris and Tom;
Thanks much for looking at this, and confirming that it's not something I'm doing wrong. I have a reproducible test case I could share but I can't seem to reduce the BAM file to a smaller size and still show the problem. Do you have enough to work off of, or is it useful to share this? It's a 19Gb BAM and small BED file and associated scripts and I could put on S3 if it's helpful.

**Comment by tomwhite** [comment]
I wonder if this is happening because it's using the sequence dictionary from the reads, rather than from the reference. Is there some way you could compare the two?

I think we would need the BAM to get any further with this one, so yes it would be useful to share.

**Comment by chapmanb** [comment]
Tom;
I believe the BAM and reference sequence dictionaries are the same. The 2bit is generated from the hg38 fasta reference used for alignment. Definitely happy to dig more if you think of other potential issues.

Here is a reproducible example with a regions file, small bash script and the large 18Gb input BAM that causes the problem:
```
wget https://s3.amazonaws.com/chapmanb/testcases/gatk/gatkspark_refname.tar.gz
tar -xzvpf gatkspark_refname.tar.gz
cd gatkspark_refname
wget https://s3.amazonaws.com/chapmanb/testcases/gatk/gatkspark_refname.bam
wget https://s3.amazonaws.com/chapmanb/testcases/gatk/gatkspark_refname.bam.bai
```
Then edit `run.sh` to point at your local hg38 2bit reference.

Let me know if I can provide anything else to help.

**Comment by samuelklee** [comment]
What is the status of this bug?  The rate of failure in SparkGenomeReadCounts is non-negligible, so this is  becoming an issue for testing the new CNV WGS pipeline.

**Comment by tomwhite** [comment]
@chapmanb thanks for providing a test case to reproduce this. I've been travelling and haven't had a chance to look at it yet, but I will soon.

**Comment by tomwhite** [comment]
I've managed to reproduce and diagnose the issue: it's a bug in Hadoop-BAM where the chunks aren't always being aligned to read boundaries when intervals are specified. This causes the reference name index to be values that are too big, since the record fields are nonsense, due to the misalignment. I've got a fix that I'll post soon.

**Comment by chapmanb** [comment]
Tom -- brilliant, thanks so much for digging and identifying the underlying problem. Excited to keep pushing forward with spark genotyping testing once it's fixed.

**Comment by tomwhite** [comment]
@chapmanb I've looked at this more, and the underlying issue is that the Hadoop-BAM code for finding input splits at BAM record boundaries is not working correctly for some BAM files. I think we can fix this by having stronger checks, and that's what I am working on now.

In the meantime, as a workaround you could try running `CreateHadoopBamSplittingIndex` to create a BAM splitting index. This might allow you to make progress.

Thanks for your help!

**Comment by tomwhite** [comment]
BTW here is the Hadoop-BAM fix: https://github.com/HadoopGenomics/Hadoop-BAM/pull/164.

**Comment by tomwhite** [comment]
@chapmanb I forgot to say that with the fix I can run your test command successfully. Without the fix I was getting the same error that you got.

If you want to try out the fix you will have to build Hadoop-BAM, see https://github.com/broadinstitute/gatk/wiki/Build-GATK-with-a-locally-built-htsjdk-or-Hadoop-BAM. When building GATK, do something like:

```bash
./gradlew clean installDist sparkJar -DhadoopBam.version=...
```

For the record, here is the command I ran:
```bash
./gatk-launch HaplotypeCallerSpark -I hdfs:///user/$USER/debug-ref-name/gatkspark_refname.bam -R hdfs:///user/$USER/debug-ref-name/Homo_sapiens_assembly38.2bit -O hdfs:///user/$USER/debug-ref-name/out/NA24631-chr15_68578892_84670250-block.vcf.gz -pairHMM AVX_LOGLESS_CACHING -L regions.bed \
  -- \
  --sparkRunner SPARK --sparkMaster yarn-client --sparkSubmitCommand spark2-submit \
  --driver-memory 4G \
  --num-executors 30 \
  --executor-cores 1 \
  --executor-memory 4G \
  --conf spark.dynamicAllocation.enabled=false
```
