### ISSUE TITLE
CollectAllelicCounts out of memory on WGS.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#3678]
Attempted to collect pileups at ~5M sites using -Xmx48G, which seems like it should be enough.  Looks like an ArrayList doubling in htsjdk is ultimately to blame, but I haven't looked into whether this might originate with an issue with the LocusWalker implementation or elsewhere in the engine:

    Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3181)
        at java.util.ArrayList.grow(ArrayList.java:261)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
        at java.util.ArrayList.addAll(ArrayList.java:579)
        at htsjdk.samtools.BAMFileSpan.merge(BAMFileSpan.java:307)
        at htsjdk.samtools.BAMFileReader.getFileSpan(BAMFileReader.java:903)
        at htsjdk.samtools.BAMFileReader.createIndexIterator(BAMFileReader.java:915)
        at htsjdk.samtools.BAMFileReader.query(BAMFileReader.java:575)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:528)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:400)
        at org.broadinstitute.hellbender.utils.iterators.SamReaderQueryingIterator.loadNextIterator(SamReaderQueryingIterator.java:125)
        at org.broadinstitute.hellbender.utils.iterators.SamReaderQueryingIterator.<init>(SamReaderQueryingIterator.java:66)
        at org.broadinstitute.hellbender.engine.ReadsDataSource.prepareIteratorsForTraversal(ReadsDataSource.java:404)
        at org.broadinstitute.hellbender.engine.ReadsDataSource.iterator(ReadsDataSource.java:330)
        at java.lang.Iterable.spliterator(Iterable.java:101)
        at org.broadinstitute.hellbender.utils.Utils.stream(Utils.java:1055)
        at org.broadinstitute.hellbender.engine.GATKTool.getTransformedReadStream(GATKTool.java:254)
        at org.broadinstitute.hellbender.engine.LocusWalker.traverse(LocusWalker.java:157)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:838)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:119)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:176)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:195)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:131)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:152)
        at org.broadinstitute.hellbender.Main.main(Main.java:233)

**Comment by samuelklee** [comment]
Actually, this might have been a cromwell issue, looks like I unintentionally passed -Xmx4g...
