### ISSUE TITLE
Transient GCS Permission Errors when using 4.beta.6

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/gatk#3735]
We've been using 4.beta.6 to generate new callsets because it has the GenomicsDBImport batching fix and it seems to have introduced transient Auth errors that production was not seeing before.  This happens a maybe one shard at every task level and when rerun usually succeeds but as you can imagine is pretty annoying.  This happens across multiple tools (GenomicsDBImport, GatherVcfs)

Sometimes we get this as the only response from GATK when this happens

```
***********************************************************************

A USER ERROR has occurred: Couldn't read file. Error was: Failure while waiting for FeatureReader to initialize  with exception: com.google.cloud.storage.StorageException: 403 Forbidden
443301511749-compute@developer.gserviceaccount.com does not have storage.objects.get access to broad-gotc-prod-storage/pipeline/G101956/gvcfs/DDP_ATCP_42_1.4afb46bb-4009-47c4-9aa0-407e92de0db8.g.vcf.gz.

***********************************************************************
```

and other times we get a nice stacktrace for this issue

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.cloud.storage.StorageException: 403 Forbidden
443301511749-compute@developer.gserviceaccount.com does not have storage.objects.get access to broad-jg-dev-11k-call-set/JointGenotyping/0cb36821-b8bf-4e6d-a352-07b101f6b7d1/call-ApplyRecalibration/shard-1734/GMKF_Seidman_CHD_WGS_904.filtered.1734.vcf.gz.
	at org.broadinstitute.hellbender.utils.nio.SeekableByteChannelPrefetcher.read(SeekableByteChannelPrefetcher.java:309)
	at htsjdk.samtools.seekablestream.SeekablePathStream.read(SeekablePathStream.java:86)
	at htsjdk.samtools.util.IOUtil.transferByStream(IOUtil.java:141)
	at org.broadinstitute.hellbender.tools.GatherVcfsCloud.gatherWithBlockCopying(GatherVcfsCloud.java:394)
	at org.broadinstitute.hellbender.tools.GatherVcfsCloud.doWork(GatherVcfsCloud.java:143)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:119)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:176)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:195)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:137)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:158)
	at org.broadinstitute.hellbender.Main.main(Main.java:239)
Caused by: java.util.concurrent.ExecutionException: com.google.cloud.storage.StorageException: 403 Forbidden
443301511749-compute@developer.gserviceaccount.com does not have storage.objects.get access to broad-jg-dev-11k-call-set/JointGenotyping/0cb36821-b8bf-4e6d-a352-07b101f6b7d1/call-ApplyRecalibration/shard-1734/GMKF_Seidman_CHD_WGS_904.filtered.1734.vcf.gz.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.broadinstitute.hellbender.utils.nio.SeekableByteChannelPrefetcher$WorkUnit.getBuf(SeekableByteChannelPrefetcher.java:136)
	at org.broadinstitute.hellbender.utils.nio.SeekableByteChannelPrefetcher.fetch(SeekableByteChannelPrefetcher.java:255)
	at org.broadinstitute.hellbender.utils.nio.SeekableByteChannelPrefetcher.read(SeekableByteChannelPrefetcher.java:300)
	... 10 more
Caused by: com.google.cloud.storage.StorageException: 403 Forbidden
443301511749-compute@developer.gserviceaccount.com does not have storage.objects.get access to broad-jg-dev-11k-call-set/JointGenotyping/0cb36821-b8bf-4e6d-a352-07b101f6b7d1/call-ApplyRecalibration/shard-1734/GMKF_Seidman_CHD_WGS_904.filtered.1734.vcf.gz.
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:189)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.read(HttpStorageRpc.java:526)
	at com.google.cloud.storage.BlobReadChannel$1.call(BlobReadChannel.java:127)
	at com.google.cloud.storage.BlobReadChannel$1.call(BlobReadChannel.java:124)
	at shaded.cloud_nio.com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:94)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:54)
	at com.google.cloud.storage.BlobReadChannel.read(BlobReadChannel.java:124)
	at com.google.cloud.storage.contrib.nio.CloudStorageReadChannel.read(CloudStorageReadChannel.java:114)
	at org.broadinstitute.hellbender.utils.nio.SeekableByteChannelPrefetcher$WorkUnit.call(SeekableByteChannelPrefetcher.java:131)
	at org.broadinstitute.hellbender.utils.nio.SeekableByteChannelPrefetcher$WorkUnit.call(SeekableByteChannelPrefetcher.java:104)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: shaded.cloud_nio.com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
443301511749-compute@developer.gserviceaccount.com does not have storage.objects.get access to broad-jg-dev-11k-call-set/JointGenotyping/0cb36821-b8bf-4e6d-a352-07b101f6b7d1/call-ApplyRecalibration/shard-1734/GMKF_Seidman_CHD_WGS_904.filtered.1734.vcf.gz.
	at shaded.cloud_nio.com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
	at shaded.cloud_nio.com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at shaded.cloud_nio.com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at shaded.cloud_nio.com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at shaded.cloud_nio.com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1056)
	at shaded.cloud_nio.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at shaded.cloud_nio.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at shaded.cloud_nio.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeMedia(AbstractGoogleClientRequest.java:380)
	at shaded.cloud_nio.com.google.api.services.storage.Storage$Objects$Get.executeMedia(Storage.java:6133)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.read(HttpStorageRpc.java:505)
	... 12 more
```

This service account does have access to these files because every shard accesses the same files  and most of them succeed and when the same task is rerun it does succeed.  @snovod should have any other information you may need.

**Comment by snovod** [comment]
I have seen this 4 times in the last week or so.

e2cd74d3-33b9-47de-98ce-0bdd22729fa0
gs://broad-jg-dev-11k-call-set/JointGenotyping/e2cd74d3-33b9-47de-98ce-0bdd22729fa0/call-ImportGVCFs/shard-179/ImportGVCFs-179-stderr.log

94b9b228-852b-40ab-8791-16edd4a229c1
gs://broad-jg-dev-11k-call-set/JointGenotyping/94b9b228-852b-40ab-8791-16edd4a229c1/call-ImportGVCFs/shard-684/ImportGVCFs-684-stderr.log

0cb36821-b8bf-4e6d-a352-07b101f6b7d1
gs://broad-jg-dev-11k-call-set/JointGenotyping/0cb36821-b8bf-4e6d-a352-07b101f6b7d1/call-FinalGatherVcf/FinalGatherVcf-stderr.log

6ab86d5a-fc66-41ac-bd14-2df027c94629
gs://broad-jg-dev-11k-call-set/JointGenotyping/6ab86d5a-fc66-41ac-bd14-2df027c94629/call-ImportGVCFs/shard-143/attempt-2/ImportGVCFs-143-stderr.log

**Comment by droazen** [comment]
@jean-philippe-martin Could you please have a look at this one? I'd say this is higher priority than https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2453

**Comment by jean-philippe-martin** [comment]
This looks like the auth service saw some transient error and instead of replying with a 503 (service temporarily unavailable), it replied with a 403 (forbidden). A walkaround would be to retry on those. The side effect will be that if we genuinely do not have access, it'll take a bit longer to report it.

**Comment by snovod** [comment]
Of the three Joint Callings workflow I resubmitted yesterday 2 failed with this error.

**Comment by lbergelson** [comment]
@jean-philippe-martin Do you know what google service is responsible for this?  It sounds like a bug that should be fixed on google's end if it's misreporting errors.  It's also strange that it just started happening, possibly just recently introduced.

**Comment by cwhelan** [comment]
I don't know if it's the same issue but we have recently started seeing random 403 errors running dataproc jobs that appear to be internal to GCS dataproc services:

```
ERROR: (gcloud.dataproc.jobs.submit.spark) HTTPError 403: cwhelan@broadinstitute.org does not have storage.objects.get access to dataproc-ed605f51-8ceb-44f7-b48c-a87bc588c1a6-us/google-cloud-dataproc-metainfo/dbfb2df5-060a-425e-ac31-77484354f264/jobs/0a5c53e9-f935-48f8-a39e-8a46d20b5ec9/driveroutput.000000010.
```

For us the job keeps running on the dataproc cluster but the error crashes the client program that submitted the job.

**Comment by jean-philippe-martin** [comment]
@cwhelan yes that would be consistent with a bug in the auth service.

@snovod if you're feeling ambitious you can try running a version that includes PR#3739 and let me know whether this fixes it or, if not, share a stack trace?

**Comment by jean-philippe-martin** [comment]
For what it's worth, [this completely different thread about Drive](https://github.com/ncw/rclone/issues/20) also shows an issue where a transient issue (rate limit exceeded) results in a 403 error. This strengthens our argument that we need to retry on 403s.

**Comment by jean-philippe-martin** [comment]
@jsotobroad if my theory that this is a misreported 503 is correct, then the kind of bucket is going to play a role. If you need to send many requests a second, consider using a **multi-regional** storage bucket if you don't already. This may reduce the frequency of this problem.

**Comment by jsotobroad** [comment]
Interesting, will bring the **multi-regional** bucket to the team, thanks for looking at this

**Comment by droazen** [comment]
@jsotobroad Prospective fix is up at https://github.com/broadinstitute/gatk/pull/3766. @jsotobroad Could you try this branch out and see if it resolves the 403 issue?
