### ISSUE TITLE
HDF5Library uses incorrect logger.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#3763]
Results in a warning message.

**Comment by lbergelson** [comment]
@samuelklee Is it something in our code or in the hdf5 java or native code that we wrap?  What's the error?

**Comment by samuelklee** [comment]
I think it's simply that HDF5Library uses `org.apache.log4j.LogManager` rather than `org.apache.logging.log4j.LogManager`.

**Comment by samuelklee** [comment]
Here's the warning that pops up:

    log4j:WARN No appenders could be found for logger (org.broadinstitute.hdf5.HDF5Library).
    log4j:WARN Please initialize the log4j system properly.
    log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by lbergelson** [comment]
Ah, thanks, that sounds like an easy fix then.

**Comment by samuelklee** [comment]
@lbergelson I forgot about this low hanging fruit.  Any chance that you can take care of it?

**Comment by samuelklee** [comment]
@lbergelson can you take care of this?

**Comment by Emmalynchen** [comment]
Running into a similar issue when launching [cnv_somatic_pair_workflow 1.3](https://dockstore.org/workflows/github.com/gatk-workflows/gatk4-somatic-cnvs/cnv_somatic_pair_workflow:1.3.0?tab=info) with [gatk docker 4.1](us.gcr.io/broad-gatk/gatk:4.1.0.0) on Terra. Any suggestions?

```
log4j:WARN No appenders could be found for logger (org.broadinstitute.hdf5.HDF5Library).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
22:50:56.367 INFO  DenoiseReadCounts - Reading read-counts file (/cromwell_root/fc-88ae2d4c-8e67-478a-893c-65db97d40c80/9a75a2c6-0c0b-4903-80e6-0082435645c1/CNVSomaticPairWorkflow/ca25a6aa-92b6-4a41-b41a-740cf40b2143/call-CollectCountsTumor/S027-1A-deduped.counts.hdf5)...
```

Full error message below:
```
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/cromwell_root/tmp.21bb067d
22:50:55.910 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gatk/gatk-package-4.1.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
22:50:56.299 INFO  DenoiseReadCounts - ------------------------------------------------------------
22:50:56.300 INFO  DenoiseReadCounts - The Genome Analysis Toolkit (GATK) v4.1.0.0
22:50:56.300 INFO  DenoiseReadCounts - For support and documentation go to https://software.broadinstitute.org/gatk/
22:50:56.301 INFO  DenoiseReadCounts - Executing as root@fccf9fc16dab on Linux v4.9.0-0.bpo.6-amd64 amd64
22:50:56.301 INFO  DenoiseReadCounts - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_191-8u191-b12-0ubuntu0.16.04.1-b12
22:50:56.301 INFO  DenoiseReadCounts - Start Date/Time: May 7, 2019 10:50:55 PM UTC
22:50:56.301 INFO  DenoiseReadCounts - ------------------------------------------------------------
22:50:56.301 INFO  DenoiseReadCounts - ------------------------------------------------------------
22:50:56.302 INFO  DenoiseReadCounts - HTSJDK Version: 2.18.2
22:50:56.302 INFO  DenoiseReadCounts - Picard Version: 2.18.25
22:50:56.302 INFO  DenoiseReadCounts - HTSJDK Defaults.COMPRESSION_LEVEL : 2
22:50:56.302 INFO  DenoiseReadCounts - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
22:50:56.302 INFO  DenoiseReadCounts - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
22:50:56.302 INFO  DenoiseReadCounts - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
22:50:56.302 INFO  DenoiseReadCounts - Deflater: IntelDeflater
22:50:56.302 INFO  DenoiseReadCounts - Inflater: IntelInflater
22:50:56.302 INFO  DenoiseReadCounts - GCS max retries/reopens: 20
22:50:56.302 INFO  DenoiseReadCounts - Requester pays: disabled
22:50:56.302 INFO  DenoiseReadCounts - Initializing engine
22:50:56.302 INFO  DenoiseReadCounts - Done initializing engine
log4j:WARN No appenders could be found for logger (org.broadinstitute.hdf5.HDF5Library).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
22:50:56.367 INFO  DenoiseReadCounts - Reading read-counts file (/cromwell_root/fc-88ae2d4c-8e67-478a-893c-65db97d40c80/9a75a2c6-0c0b-4903-80e6-0082435645c1/CNVSomaticPairWorkflow/ca25a6aa-92b6-4a41-b41a-740cf40b2143/call-CollectCountsTumor/S027-1A-deduped.counts.hdf5)...
22:50:58.635 INFO  SVDDenoisingUtils - Validating sample intervals against original intervals used to build panel of normals...
22:50:59.487 INFO  DenoiseReadCounts - Shutting down engine
[May 7, 2019 10:50:59 PM UTC] org.broadinstitute.hellbender.tools.copynumber.DenoiseReadCounts done. Elapsed time: 0.06 minutes.
Runtime.totalMemory()=894959616
java.lang.IllegalArgumentException: Sample intervals must be identical to the original intervals used to build the panel of normals.
	at org.broadinstitute.hellbender.utils.Utils.validateArg(Utils.java:724)
	at org.broadinstitute.hellbender.tools.copynumber.denoising.SVDDenoisingUtils.denoise(SVDDenoisingUtils.java:120)
	at org.broadinstitute.hellbender.tools.copynumber.denoising.SVDReadCountPanelOfNormals.denoise(SVDReadCountPanelOfNormals.java:88)
	at org.broadinstitute.hellbender.tools.copynumber.DenoiseReadCounts.doWork(DenoiseReadCounts.java:202)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:138)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)
Using GATK jar /root/gatk.jar defined in environment variable GATK_LOCAL_JAR
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx12000m -jar /root/gatk.jar DenoiseReadCounts --input /cromwell_root/fc-88ae2d4c-8e67-478a-893c-65db97d40c80/9a75a2c6-0c0b-4903-80e6-0082435645c1/CNVSomaticPairWorkflow/ca25a6aa-92b6-4a41-b41a-740cf40b2143/call-CollectCountsTumor/S027-1A-deduped.counts.hdf5 --count-panel-of-normals /cromwell_root/fc-88ae2d4c-8e67-478a-893c-65db97d40c80/9838fed6-ec4d-45f2-bb27-8bfd78f0cc72/CNVSomaticPanelWorkflow/6c91bc28-a13c-4fc9-bbe4-3c74f153a8c2/call-CreateReadCountPanelOfNormals/wgs-do-gc.pon.hdf5 --standardized-copy-ratios S027-1A-deduped.standardizedCR.tsv --denoised-copy-ratios S027-1A-deduped.denoisedCR.tsv
```

**Comment by samuelklee** [comment]
@Emmalynchen I wouldn't worry about the `log4j:WARN` messages discussed in this thread---they're just harmless annoyances that pop up because we haven't gotten around to making sure the HDF5Library dependency uses the same logger as the rest of the GATK.

Looking at your initial post (before you edited it), it looks like DenoiseReadCounts is failing because the panel of normals contains different intervals than those in the read-count collection you are trying to denoise:

```
22:50:58.635 INFO  SVDDenoisingUtils - Validating sample intervals against original intervals used to build panel of normals...
22:50:59.487 INFO  DenoiseReadCounts - Shutting down engine
[May 7, 2019 10:50:59 PM UTC] org.broadinstitute.hellbender.tools.copynumber.DenoiseReadCounts done. Elapsed time: 0.06 minutes.
Runtime.totalMemory()=894959616
java.lang.IllegalArgumentException: Sample intervals must be identical to the original intervals used to build the panel of normals.
```

You might try asking for more pointers over in the GATK Forums (https://gatkforums.broadinstitute.org/gatk), if you need them.  Good luck!

**Comment by Emmalynchen** [comment]
@samuelklee Thank you for the pointers and catching that even after the edit! I saw the error but thought I was using the right intervals. Will do some digging.

**Comment by samuelklee** [comment]
@lbergelson did we ever close the loop on this?

**Comment by samuelklee** [comment]
@droazen can we take care of this?  See https://gatkforums.broadinstitute.org/gatk/discussion/24348/log4j-warn-please-initialize-the-log4j-system-properly#latest.

**Comment by samuelklee** [comment]
@droazen @lbergelson any chance we can close this out?

**Comment by droazen** [comment]
@samuelklee Sure, would you care to review https://github.com/broadinstitute/hdf5-java-bindings/pull/14 to see whether it fixes this issue?
