### ISSUE TITLE
Cant output to /dev/null, fails closing index

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/gatk#3829]
GATK version - Version: 4.beta.6-SNAPSHOT (using us.gcr.io/broad-gatk/gatk:4.beta.6 docker images) 

command:
```
/gatk/gatk-launch --javaOptions "-Xmx6g -Xms6g" \
SelectVariants \
--variant one_sample_test.sites_only.vcf.gz \
--output "/dev/null"
```
exception:
```
htsjdk.samtools.util.RuntimeIOException: Unable to close index for /dev/null
	at htsjdk.variant.variantcontext.writer.IndexingVariantContextWriter.close(IndexingVariantContextWriter.java:152)
	at htsjdk.variant.variantcontext.writer.VCFWriter.close(VCFWriter.java:212)
	at org.broadinstitute.hellbender.tools.walkers.variantutils.SelectVariants.closeTool(SelectVariants.java:634)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:842)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:119)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:176)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:195)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:137)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:158)
	at org.broadinstitute.hellbender.Main.main(Main.java:239)
Caused by: java.io.IOException: Cannot write based on a non-regular file: file:///dev/null
	at htsjdk.tribble.index.AbstractIndex.writeBasedOnFeaturePath(AbstractIndex.java:389)
	at htsjdk.tribble.index.Index.writeBasedOnFeatureFile(Index.java:102)
	at htsjdk.variant.variantcontext.writer.IndexingVariantContextWriter.close(IndexingVariantContextWriter.java:147)
	... 9 more
```

I *think* this is expected to work, if not then feel free to close.

**Comment by vruano** [comment]
If IndexingVariantContextWriter is mean to create a index alongside /dev/null (... /dev/null.idx?) it isn't surprising that it does not work although the error message could be more informative. Is there a way to ask SelectVariants not to create an index and in that case you still have an exception?

**Comment by vruano** [comment]
Indeed adding ```--createOutputVariantIndex false``` there is exception any longer.
Probrably the actual base cause is that the user does not have permission to create a file under /dev

Ideally instead of ``` Unable to close index for /dev/null``` the error message should be something like ``` Unable to create index file /dev/null.idx for the output; not enough permissions```.
