### ISSUE TITLE
Exception: Invalid interval when processing chr5 of platinum genome NA12878

### ISSUE THREAD

**Issue by fac2003** [broadinstitute/gatk#4120]
Note that I want to disable filters intentionally to keep poor alignments.

```
java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -Xmx10g -jar gatk-4.0.0.0/gatk-package-4.0.0.0-local.jar HaplotypeCaller -L chr5 --reference genomes/ucsc_hg19.fasta --input NA12878_S1_md.bam --output hc_variants_7.vcf --bam-output realigned_slice_7.bam --max-reads-per-alignment-start 1000 --min-base-quality-score 0 --minimum-mapping-quality 0 --disable-read-filter MappingQualityReadFilter --disable-read-filter MappingQualityAvailableReadFilter --disable-read-filter NotSecondaryAlignmentReadFilter --disable-read-filter NotDuplicateReadFilter --disable-read-filter PassesVendorQualityCheckReadFilter --disable-read-filter NonZeroReferenceLengthAlignmentReadFilter --disable-read-filter GoodCigarReadFilter --disable-read-filter WellformedReadFilter`
[January 10, 2018 2:39:19 PM EST] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 91.81 minutes.
Runtime.totalMemory()=7215251456
java.lang.IllegalArgumentException: Invalid interval. Contig:chr5 start:71357769 end:71357768
        at org.broadinstitute.hellbender.utils.Utils.validateArg(Utils.java:687)
        at org.broadinstitute.hellbender.utils.SimpleInterval.validatePositions(SimpleInterval.java:61)
        at org.broadinstitute.hellbender.utils.SimpleInterval.<init>(SimpleInterval.java:37)
        at org.broadinstitute.hellbender.utils.SimpleInterval.<init>(SimpleInterval.java:49)
        at org.broadinstitute.hellbender.engine.AssemblyRegion.add(AssemblyRegion.java:335)
        at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.fillNextAssemblyRegionWithReads(AssemblyRegionIterator.java:230)
        at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.loadNextAssemblyRegion(AssemblyRegionIterator.java:194)
        at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.next(AssemblyRegionIterator.java:135)
        at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.next(AssemblyRegionIterator.java:34)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:290)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:271)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:893)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:136)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:152)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:195)
        at org.broadinstitute.hellbender.Main.main(Main.java:275)
```

**Comment by fac2003** [comment]
I see the exception on most chromosomes, here's the one for chr1:

java.lang.IllegalArgumentException: Invalid interval. Contig:chr1 start:79293873 end:79293872
        at org.broadinstitute.hellbender.utils.Utils.validateArg(Utils.java:687)
        at org.broadinstitute.hellbender.utils.SimpleInterval.validatePositions(SimpleInterval.java:61)
        at org.broadinstitute.hellbender.utils.SimpleInterval.<init>(SimpleInterval.java:37)
        at org.broadinstitute.hellbender.utils.SimpleInterval.<init>(SimpleInterval.java:49)
        at org.broadinstitute.hellbender.engine.AssemblyRegion.add(AssemblyRegion.java:335)
        at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.fillNextAssemblyRegionWithReads(AssemblyRegionIterator.java:230)
        at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.loadNextAssemblyRegion(AssemblyRegionIterator.java:194)
        at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.next(AssemblyRegionIterator.java:135)
        at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.next(AssemblyRegionIterator.java:34)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:290)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:271)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:893)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:136)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:152)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:195)
        at org.broadinstitute.hellbender.Main.main(Main.java:275)

**Comment by lbergelson** [comment]
@fac2003 I believe that you have intervals that are of 0 length in your interval file.  GATK doesn't like those.  Did you intend to have 0 length intervals or is that unintentional?

**Comment by lbergelson** [comment]
Actually, I'm sorry, I think I jumped to conclusions too quickly without reading through everything...  It looks like some of the reads are of 0 length, which is probably what's causing the problems.  Those would normally be filtered out, but they're getting through since you disabled filters.

Could you try running without `--disable-read-filter NonZeroReferenceLengthAlignmentReadFilter`?

**Comment by fac2003** [comment]
I removed this filter and it fixed the issue. Thanks.

**Comment by lbergelson** [comment]
👍 In general the tools will likely run into trouble if you remove their default filters.
