### ISSUE TITLE
Could not load genomicsdb native library

### ISSUE THREAD

**Issue by owensgl** [broadinstitute/gatk#4124]
With GATKv4.0.0.0, when I try to run GenomicsDBimport, it crashes and gives this error message:

> 19:29:01.249 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/gatk/4.0.0.0/gatk-package-4.0.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
19:29:01.391 INFO  GenomicsDBImport - ------------------------------------------------------------
19:29:01.391 INFO  GenomicsDBImport - The Genome Analysis Toolkit (GATK) v4.0.0.0
19:29:01.391 INFO  GenomicsDBImport - For support and documentation go to https://software.broadinstitute.org/gatk/
19:29:01.391 INFO  GenomicsDBImport - Executing as gowens@cdr619.int.cedar.computecanada.ca on Linux v3.10.0-693.5.2.el7.x86_64 amd64
19:29:01.391 INFO  GenomicsDBImport - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_121-b13
19:29:01.392 INFO  GenomicsDBImport - Start Date/Time: January 10, 2018 7:29:01 PST PM
19:29:01.392 INFO  GenomicsDBImport - ------------------------------------------------------------
19:29:01.392 INFO  GenomicsDBImport - ------------------------------------------------------------
19:29:01.392 INFO  GenomicsDBImport - HTSJDK Version: 2.13.2
19:29:01.392 INFO  GenomicsDBImport - Picard Version: 2.17.2
19:29:01.392 INFO  GenomicsDBImport - HTSJDK Defaults.COMPRESSION_LEVEL : 1
19:29:01.392 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
19:29:01.392 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
19:29:01.392 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
19:29:01.393 INFO  GenomicsDBImport - Deflater: IntelDeflater
19:29:01.393 INFO  GenomicsDBImport - Inflater: IntelInflater
19:29:01.393 INFO  GenomicsDBImport - GCS max retries/reopens: 20
19:29:01.393 INFO  GenomicsDBImport - Using google-cloud-java patch 6d11bef1c81f885c26b2b56c8616b7a705171e4f from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes
19:29:01.393 INFO  GenomicsDBImport - Initializing engine
19:29:23.214 INFO  IntervalArgumentCollection - Processing 1000000 bp from intervals
19:29:23.216 INFO  GenomicsDBImport - Done initializing engine
19:29:23.332 INFO  GenomicsDBImport - Shutting down engine
[January 10, 2018 7:29:23 PST PM] org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport done. Elapsed time: 0.37 minutes.
Runtime.totalMemory()=2804940800
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport.overwriteOrCreateWorkspace(GenomicsDBImport.java:706)
        at org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport.onTraversalStart(GenomicsDBImport.java:448)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:891)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:136)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:152)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:195)
        at org.broadinstitute.hellbender.Main.main(Main.java:275)
Caused by: com.intel.genomicsdb.GenomicsDBException: Could not load genomicsdb native library
        at com.intel.genomicsdb.GenomicsDBImporter.<clinit>(GenomicsDBImporter.java:72)
        ... 9 more

This seems similar to the issue raised [here](https://github.com/broadinstitute/gatk/issues/4062), but I thought that issue was resolved, so it may be different.

**Comment by jamesemery** [comment]
Hello @owensgl. Could you provide me with an example command line argument that causes this error? I would like to know more about where you are putting your genomcisDB.

**Comment by droazen** [comment]
@kgururaj Could you also have a look at this one, please?

**Comment by kgururaj** [comment]
Same question as Louis, which OS (or Docker image) are you running on?

Just FYI,  we now have a repo and Travis setup to test out the jars for issues. The tests for this jar passed the last time - I have restarted the build (Ubuntu and MacOSX)

https://travis-ci.org/kgururaj/TestGenomicsDBJar/builds/325659272

**Comment by lbergelson** [comment]
I suspect it's a different issue than #4062, but probably some similar library incompatibility issue.  Unfortunately the stack trace doesn't have enough information in it.  We should consider rewriting the error message for this so that we are sure to have the first cause reported, not just the `Could not load genomicsdb native library` message.

**Comment by kgururaj** [comment]
A check:
Can you clone https://github.com/kgururaj/TestGenomicsDBJar ?
```
GENOMICSDB_VERSION=0.8.1-proto-3.0.0-beta-1+uuid-static
curl -O http://repo1.maven.org/maven2/com/intel/genomicsdb/${GENOMICSDB_VERSION}/genomicsdb-${GENOMICSDB_VERSION}-jar-with-dependencies.jar
bash -x TestGenomicsDBJar/run_checks.sh
```

**Comment by owensgl** [comment]
Hi, 
This is the command I used ($tmp is a string of 150 gvcfs):
`gatk GenomicsDBImport \
        $tmp \
        --genomicsdb-workspace-path /scratch/gowens/wild_gwas/$genomicsdb/${chr}_$pos \
        --intervals $contig \
        --batch-size 100`

The OS version is:

> LSB
 Version:    n/a
Distributor ID: CentOS
Description:    CentOS Linux release 7.4.1708 (Core)
Release:        7.4.1708
Codename:       Core

I'll try to do the tests kgururaj suggests.

**Comment by owensgl** [comment]
@kgururaj I ran the commands you suggested. 

> [user@cedar5 bin]$ bash -x TestGenomicsDBJar/run_checks.sh
> + [[ hB != hxB ]]
> + XTRACE_STATE=-x
> + [[ hxB != hxB ]]
> + VERBOSE_STATE=+v
> + set +xv
> + unset XTRACE_STATE VERBOSE_STATE
> ++ uname -s
> + osname=Linux
> + jar xf genomicsdb--jar-with-dependencies.jar libtiledbgenomicsdb.so
> java.io.FileNotFoundException: genomicsdb--jar-with-dependencies.jar (No such file or directory)
>         at java.util.zip.ZipFile.open(Native Method)
>         at java.util.zip.ZipFile.<init>(ZipFile.java:219)
>         at java.util.zip.ZipFile.<init>(ZipFile.java:149)
>         at java.util.zip.ZipFile.<init>(ZipFile.java:120)
>         at sun.tools.jar.Main.extract(Main.java:1004)
>         at sun.tools.jar.Main.run(Main.java:305)
>         at sun.tools.jar.Main.main(Main.java:1288)
> + jar xf genomicsdb--jar-with-dependencies.jar libtiledbgenomicsdb.dylib
> java.io.FileNotFoundException: genomicsdb--jar-with-dependencies.jar (No such file or directory)
>         at java.util.zip.ZipFile.open(Native Method)
>         at java.util.zip.ZipFile.<init>(ZipFile.java:219)
>         at java.util.zip.ZipFile.<init>(ZipFile.java:149)
>         at java.util.zip.ZipFile.<init>(ZipFile.java:120)
>         at sun.tools.jar.Main.extract(Main.java:1004)
>         at sun.tools.jar.Main.run(Main.java:305)
>         at sun.tools.jar.Main.main(Main.java:1288)
> + '[' Linux == Darwin ']'
> + LIBRARY_SUFFIX=so
> + ldd libtiledbgenomicsdb.so
> ldd: ./libtiledbgenomicsdb.so: No such file or directory
> + md5sum libtiledbgenomicsdb.so
> md5sum: libtiledbgenomicsdb.so: No such file or directory

I'm using a compute canada server, so I don't have root access. The version of gatk4 I'm using was installed by their support team, and I load it using 'module load gatk'. I had that module loaded when I ran this test.

**Comment by kgururaj** [comment]
Minor change in my comment - could you re-run with the modified commands?

**Comment by owensgl** [comment]
With updated command:

> [user@cedar5 bin]$ bash -x TestGenomicsDBJar/run_checks.sh
> + [[ hB != hxB ]]
> + XTRACE_STATE=-x
> + [[ hxB != hxB ]]
> + VERBOSE_STATE=+v
> + set +xv
> + unset XTRACE_STATE VERBOSE_STATE
> ++ uname -s
> + osname=Linux
> + jar xf genomicsdb-0.8.1-proto-3.0.0-beta-1+uuid-static-jar-with-dependencies.jar libtiledbgenomicsdb.so
> + jar xf genomicsdb-0.8.1-proto-3.0.0-beta-1+uuid-static-jar-with-dependencies.jar libtiledbgenomicsdb.dylib
> + '[' Linux == Darwin ']'
> + LIBRARY_SUFFIX=so
> + ldd libtiledbgenomicsdb.so
> ldd: warning: you do not have execution permission for `./libtiledbgenomicsdb.so'
>         linux-vdso.so.1 (0x00007ffca79df000)
>         libpthread.so.0 => /cvmfs/soft.computecanada.ca/nix/store/77k5s2iy82zny2xazfsrrysbyifyy79b-glibc-2.24/lib/libpthread.so.0 (0x00007f146cb0c000)
>         libz.so.1 => not found
>         libuuid.so.1 => not found
>         librt.so.1 => /cvmfs/soft.computecanada.ca/nix/store/77k5s2iy82zny2xazfsrrysbyifyy79b-glibc-2.24/lib/librt.so.1 (0x00007f146c902000)
>         libm.so.6 => /cvmfs/soft.computecanada.ca/nix/store/77k5s2iy82zny2xazfsrrysbyifyy79b-glibc-2.24/lib/libm.so.6 (0x00007f146c5fd000)
>         libc.so.6 => /cvmfs/soft.computecanada.ca/nix/store/77k5s2iy82zny2xazfsrrysbyifyy79b-glibc-2.24/lib/libc.so.6 (0x00007f146c25f000)
>         /cvmfs/soft.computecanada.ca/nix/store/77k5s2iy82zny2xazfsrrysbyifyy79b-glibc-2.24/lib64/ld-linux-x86-64.so.2 (0x000055ddfd95d000)
> + md5sum libtiledbgenomicsdb.so
> 83007be5ce8b0c832b539b21b6c0d68d  libtiledbgenomicsdb.so

**Comment by kgururaj** [comment]
Interesting, this is the first time that I have seen a CentOS-7 install without zlib and uuid - even the minimal installations include it.

Your options are:
- Install zlib  and uuid (yum -y install zlib libuuid)
- Ask your admins whether these packages are installed in some other location. For example, if the zlib library is at /opt/my_install/lib64/libz.so, then you can set your environment variable LD_LIBRARY_PATH
```
export LD_LIBRARY_PATH=/opt/my_install/lib64:/opt/my_install/lib:$LD_LIBRARY_PATH
```
- Wait for the next GenomicsDB binary jar to show up

**Comment by dklimes** [comment]
This is obviously very late but I ran into the exact same problem just today (where native libraries weren't loading properly). I was able to solve it by adding the --tmp-dir option and a temporary directory (as advised here: https://gatk.broadinstitute.org/hc/en-us/articles/18965297287067-How-to-setup-and-use-temporary-folder-for-GATK-local-execution).

The problem was that java used /tmp as the default temporary directory. When I updated **my command** to:
```{bash}
gatk GenomicsDBImport \
  -V id1_raw.g.vcf \
  -V id2_raw.g.vcf \
  --genomicsdb-workspace-path my_database \
  --tmp-dir tmp \
  -L chr1
```
it worked without the error. Running this without --tmp-dir set created a native library loading error for me. Hopefully this can help someone in the future.
