### ISSUE TITLE
BwaAndMarkDuplicatesPipelineSpark crash

### ISSUE THREAD

**Issue by lelqz** [broadinstitute/gatk#4179]
my pipeline(from fastq ) is 👍 
       

1.  FastqToSam 

2. ConvertHeaderlessHadoopBamShardToBam

3. BwaAndMarkDuplicatesPipelineSpark
  
......

but in the step 3 （BwaAndMarkDuplicatesPipelineSpark），the pipeline crash
```
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3, com1, executor 1): # **java.lang.IllegalArgumentException: Reference name for '1853452901' not found in sequence dictionary.
        at htsjdk.samtools.SAMRecord.resolveNameFromIndex(SAMRecord.java:569)
        at htsjdk.samtools.SAMRecord.setMateReferenceIndex(SAMRecord.java:506)
        at htsjdk.samtools.BAMRecord.<init>(BAMRecord.java:94)
        at htsjdk.samtools.DefaultSAMRecordFactory.createBAMRecord(DefaultSAMRecordFactory.java:42)
        at htsjdk.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:210)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.getNextRecord(BAMFileReader.java:829)
        at htsjdk.samtools.BAMFileReader$BAMFileIndexIterator.getNextRecord(BAMFileReader.java:981)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:803)
        at htsjdk.samtools.BAMFileReader$BAMFileIndexIterator.<init>(BAMFileReader.java:963)
        at htsjdk.samtools.BAMFileReader.getIterator(BAMFileReader.java:491)**
        at org.seqdoop.hadoop_bam.BAMRecordReader.initialize(BAMRecordReader.java:182)
        at org.seqdoop.hadoop_bam.BAMInputFormat.createRecordReader(BAMInputFormat.java:211)
        at org.seqdoop.hadoop_bam.AnySAMInputFormat.createRecordReader(AnySAMInputFormat.java:190)
        at org.apache.spark.rdd.NewHadoopRDD$$anon$1.liftedTree1$1(NewHadoopRDD.scala:180)
        at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:179)
        at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:134)
        at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:69)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
        at org.apache.spark.scheduler.Task.run(Task.scala:108)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by droazen** [comment]
@lelqz Why are you running `ConvertHeaderlessHadoopBamShardToBam`? This is a diagnostic tool meant for debugging Spark pipelines, and should not be part of your pipeline proper! It is likely corrupting your BAM file.

**Comment by droazen** [comment]
Running `ConvertHeaderlessHadoopBamShardToBam` on anything other than an intermediate Hadoop-BAM shard will absolutely corrupt the file.

**Comment by lelqz** [comment]
I use gatk 4.0.0.0.
I don't think the crashing caused by running ConvertHeaderlessHadoopBamShardToBam .Beause I try the test with unalign Header-Bam file by picard tools , the BwaAndMarkDuplicatesPipelineSpark crashing  is still

**Comment by lelqz** [comment]
by deguging, the command ConvertHeaderlessHadoopBamShardToBam currupts the bam。I use ReplaceSamHeader  to convert Headerless shard bam to bam. It does work.

**Comment by jamesemery** [comment]
This ticket is substantially out of date. In 4.1 we have overhauled both MarkDuplicatesSpark and have replaced the old Hadoop-Bam machinery with Disq. Closing
