### ISSUE TITLE
Issue with gzipped VCF files after HC scatter/gather

### ISSUE THREAD

**Issue by marchoeppner** [broadinstitute/gatk#4255]
Hi,
I am not sure if this is a gatk bug or some other issue on our system. 
Setup: Centos 6.9, Zlib 1.2.3, gatk 4.0.0

The issue:
I am running scatter/gather haplotyping for 30X WGS data, per sample using the BROAD interval list to launch parallel processing branches (1 per sample per interval). Each individual "branch" outputs a gzip compressed file for a given target interval. I am then trying to merge these files into a per-sample gvcf for subsequent genotyping across samples. 

However, the combination using GatherVcfs fails with the following message: 

`htsjdk.tribble.TribbleException: Line 14922244: there aren't enough columns for line 1  59930777        .       A       <NON_REF>       .       .       END=5993077 (we expected 9 tokens, and saw 8 ), for input source: file:///ifs/data/nfs_share/sukmb352/projects/dzhk/genomes/test/work/2e/63b1bc25956a67ba90c2f2fadc21aa/Individual_AS-167622_Sample_AS-167622.merged.vcf.gz
        at htsjdk.variant.vcf.AbstractVCFCodec.decodeLine(AbstractVCFCodec.java:281)
        at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:262)
        at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:64)
        at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:70)
        at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:37)
        at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.readNextRecord(TribbleIndexedFeatureReader.java:365)
        at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.next(TribbleIndexedFeatureReader.java:346)
        at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.next(TribbleIndexedFeatureReader.java:307)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.broadinstitute.hellbender.engine.VariantWalkerBase.traverse(VariantWalkerBase.java:108)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:893)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:136)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:152)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:195)
        at org.broadinstitute.hellbender.Main.main(Main.java:275)`

Interestingly, this does not happen when I first decompress the vcf file. So it seems to be an issue with the gzip compression (?). Is this a known problem; anything I should check or change to address this problem?

Kind regards,
Marc

**Comment by magicDGS** [comment]
This looks like https://github.com/broadinstitute/gatk/issues/4224, which might be fixed by using an index (there is a PR to indicate that it is required in this case, see ).

It is coming from a combination of the java's `GZIPInputStream` bug and a HTSJDK's `SeekableStream` problem (https://github.com/samtools/htsjdk/issues/898). I just did a PR fixing the `SeekableStream` (https://github.com/samtools/htsjdk/pull/1077). I hope that this help to go around this...

**Comment by davidbenjamin** [comment]
@magicDGS is correct; the inputs need to be indexed.
