### ISSUE TITLE
Suggestion of command prints stacktrace

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#4256]
In the latest master, running for example `java -jar build/libs/gatk.jar FixVcfHead` returns:

```
USAGE:  <program name> [-h]

Available Programs:
--------------------------------------------------------------------------------------
Base Calling:                                    Tools that process sequencing machine data, e.g. Illumina base calls, and detect sequencing level attributes, e.g. adapters
    CheckIlluminaDirectory (Picard)              Asserts the validity for specified Illumina basecalling data.
    CollectIlluminaBasecallingMetrics (Picard)   Collects Illumina Basecalling metrics for a sequencing run.

...skipped for brevity...

    VcfFormatConverter (Picard)                  Converts VCF to BCF or BCF to VCF.
    VcfToIntervalList (Picard)                   Converts a VCF or BCF file to a Picard Interval List

--------------------------------------------------------------------------------------

Exception in thread "main" org.broadinstitute.hellbender.exceptions.UserException: 'FixVcfHead' is not a valid command.
Did you mean this?
        FixVcfHeader
	at org.broadinstitute.hellbender.Main.extractCommandLineProgram(Main.java:341)
	at org.broadinstitute.hellbender.Main.setupConfigAndExtractProgram(Main.java:172)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:192)
	at org.broadinstitute.hellbender.Main.main(Main.java:275)
```

I expect something without the stack trace and the scary "Exception" message. For example:

```
USAGE:  <program name> [-h]

Available Programs:
--------------------------------------------------------------------------------------
Base Calling:                                    Tools that process sequencing machine data, e.g. Illumina base calls, and detect sequencing level attributes, e.g. adapters
    CheckIlluminaDirectory (Picard)              Asserts the validity for specified Illumina basecalling data.
    CollectIlluminaBasecallingMetrics (Picard)   Collects Illumina Basecalling metrics for a sequencing run.

...skipped for brevity...

    VcfFormatConverter (Picard)                  Converts VCF to BCF or BCF to VCF.
    VcfToIntervalList (Picard)                   Converts a VCF or BCF file to a Picard Interval List

--------------------------------------------------------------------------------------

Did you mean this?
        FixVcfHeader
```

The same happens with unknown commands. The code that should be changed for that is the following, where the `setupConfigAndExtractProgram` call should be also inside the try block:

https://github.com/broadinstitute/gatk/blob/8ac2f102b303f343c4787ad4e3359335641c5121/src/main/java/org/broadinstitute/hellbender/Main.java#L190-L212

**Comment by lbergelson** [comment]
@magicDGS Good catch.  We should fix this.

**Comment by magicDGS** [comment]
Pull request here: #4283
