### ISSUE TITLE
Crash with IndexFeatureFile on VCF with header but no variants

### ISSUE THREAD

**Issue by acesnik** [broadinstitute/gatk#4269]
I ran IndexFeatureFile on a VCF with a valid header but no variant features. IndexFeatureFile crashes due to something regarding the progress meter. This might be a good place to output one of your helpful `USER ERROR` messages. 

Thanks!

```
acesnik@DESKTOP$ gatk/gatk IndexFeatureFile --feature-file bad.vcf
Using GATK jar gatk/gatk-package-4.0.0.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -jar gatk/gatk-package-4.0.0.0-local.jar IndexFeatureFile --feature-file bad.vcf
00:17:06.701 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:gatk/gatk-package-4.0.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
00:17:06.843 INFO  IndexFeatureFile - ------------------------------------------------------------
00:17:06.843 INFO  IndexFeatureFile - The Genome Analysis Toolkit (GATK) v4.0.0.0
00:17:06.844 INFO  IndexFeatureFile - For support and documentation go to https://software.broadinstitute.org/gatk/
00:17:06.845 INFO  IndexFeatureFile - Executing as acesnik@DESKTOP-NTA5PMC on Linux v4.4.0-43-Microsoft amd64
00:17:06.845 INFO  IndexFeatureFile - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_161-b12
00:17:06.846 INFO  IndexFeatureFile - Start Date/Time: January 26, 2018 12:17:06 AM GMT
00:17:06.846 INFO  IndexFeatureFile - ------------------------------------------------------------
00:17:06.846 INFO  IndexFeatureFile - ------------------------------------------------------------
00:17:06.847 INFO  IndexFeatureFile - HTSJDK Version: 2.13.2
00:17:06.847 INFO  IndexFeatureFile - Picard Version: 2.17.2
00:17:06.848 INFO  IndexFeatureFile - HTSJDK Defaults.COMPRESSION_LEVEL : 1
00:17:06.849 INFO  IndexFeatureFile - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
00:17:06.849 INFO  IndexFeatureFile - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
00:17:06.850 INFO  IndexFeatureFile - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
00:17:06.850 INFO  IndexFeatureFile - Deflater: IntelDeflater
00:17:06.855 INFO  IndexFeatureFile - Inflater: IntelInflater
00:17:06.856 INFO  IndexFeatureFile - GCS max retries/reopens: 20
00:17:06.858 INFO  IndexFeatureFile - Using google-cloud-java patch 6d11bef1c81f885c26b2b56c8616b7a705171e4f from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes
00:17:06.859 INFO  IndexFeatureFile - Initializing engine
00:17:06.860 INFO  IndexFeatureFile - Done initializing engine
00:17:07.292 INFO  FeatureManager - Using codec VCFCodec to read file file://bad.vcf
00:17:07.310 INFO  IndexFeatureFile - Shutting down engine
[January 26, 2018 12:17:07 AM GMT] org.broadinstitute.hellbender.tools.IndexFeatureFile done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=512229376
java.lang.IllegalStateException: the progress meter has not been started yet
        at org.broadinstitute.hellbender.utils.Utils.validate(Utils.java:697)
        at org.broadinstitute.hellbender.engine.ProgressMeter.stop(ProgressMeter.java:230)
        at org.broadinstitute.hellbender.utils.codecs.ProgressReportingDelegatingCodec.isDone(ProgressReportingDelegatingCodec.java:104)
        at htsjdk.tribble.index.IndexFactory$FeatureIterator.readNextFeature(IndexFactory.java:522)
        at htsjdk.tribble.index.IndexFactory$FeatureIterator.<init>(IndexFactory.java:440)
        at htsjdk.tribble.index.IndexFactory.createDynamicIndex(IndexFactory.java:326)
        at org.broadinstitute.hellbender.tools.IndexFeatureFile.createAppropriateIndexInMemory(IndexFeatureFile.java:122)
        at org.broadinstitute.hellbender.tools.IndexFeatureFile.doWork(IndexFeatureFile.java:71)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:136)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:152)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:195)
        at org.broadinstitute.hellbender.Main.main(Main.java:275)
```

**Comment by jhl667** [comment]
I experienced this in 4.0.11.0.  I have some variant callers in my workflow that serve a very niche purpose, and therefore may pass 0 variant VCFs from time to time.
