### ISSUE TITLE
HaplotypeCaller failing when -contamination argument is supplied

### ISSUE THREAD

**Issue by eitanbanks** [broadinstitute/gatk#4312]
I believe that the problem is that HaplotypeCallerGenotypingEngine doesn't use the version of StandardCallerArgumentCollection.getSampleContamination() with the sampleID, so the sampleContamination variable is never initialized and we get a NPE.  The -contamination argument is standard in our production GATK pipeline... and we're about to start telling everyone to use it!  This is an important one to fix.

Here's a stacktrace:

java.lang.NullPointerException
	at java.util.Collections$UnmodifiableMap.<init>(Collections.java:1446)
	at java.util.Collections.unmodifiableMap(Collections.java:1433)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.StandardCallerArgumentCollection.getSampleContamination(StandardCallerArgumentCollection.java:89)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerGenotypingEngine.assignGenotypeLikelihoods(HaplotypeCallerGenotypingEngine.java:141)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.callRegion(HaplotypeCallerEngine.java:566)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller.apply(HaplotypeCaller.java:218)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:295)

**Comment by droazen** [comment]
Thanks @eitanbanks, we'll try to get a patch out this week for this one.

**Comment by eitanbanks** [comment]
Awesome - thanks!

**Comment by thw17** [comment]
Hi,

Any updates on this? I'm running into the same error with v4.0.1.2

Thanks!

**Comment by droazen** [comment]
@thw17 I have a patch for this issue -- I am still testing it internally, but it should make it into the next GATK release.

**Comment by thw17** [comment]
Thanks, @droazen!
