### ISSUE TITLE
BQSR runs out of memory when given a large interval file (> 10 million intervals) 

### ISSUE THREAD

**Issue by takutosato** [broadinstitute/gatk#4334]
Discussed this with @lbergelson. This probably applies to any read walker. The interval file in question contains about 43 million single base intervals - they are the bases around homopolymers of length 5 or greater.

The interval file:

`/humgen/gsa-hpprojects/dev/tsato/palantir/Analysis/642_BQSRImprovementPrelim/hg19-homopolymers-save.interval_list`

Stacktrace:
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.BitSet.initWords(BitSet.java:166)
	at java.util.BitSet.<init>(BitSet.java:161)
	at htsjdk.samtools.GenomicIndexUtil.regionToBins(GenomicIndexUtil.java:90)
	at htsjdk.samtools.BinningIndexContent.getChunksOverlapping(BinningIndexContent.java:121)
	at htsjdk.samtools.CachingBAMFileIndex.getSpanOverlapping(CachingBAMFileIndex.java:71)
	at htsjdk.samtools.BAMFileReader.getFileSpan(BAMFileReader.java:898)
	at htsjdk.samtools.BAMFileReader.createIndexIterator(BAMFileReader.java:915)
	at htsjdk.samtools.BAMFileReader.query(BAMFileReader.java:575)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:528)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:400)
	at org.broadinstitute.hellbender.utils.iterators.SamReaderQueryingIterator.loadNextIterator(SamReaderQueryingIterator.java:125)
	at org.broadinstitute.hellbender.utils.iterators.SamReaderQueryingIterator.<init>(SamReaderQueryingIterator.java:66)
	at org.broadinstitute.hellbender.engine.ReadsDataSource.prepareIteratorsForTraversal(ReadsDataSource.java:404)
	at org.broadinstitute.hellbender.engine.ReadsDataSource.iterator(ReadsDataSource.java:330)
	at java.lang.Iterable.spliterator(Iterable.java:101)
	at org.broadinstitute.hellbender.utils.Utils.stream(Utils.java:1055)
	at org.broadinstitute.hellbender.engine.GATKTool.getTransformedReadStream(GATKTool.java:252)
	at org.broadinstitute.hellbender.engine.ReadWalker.traverse(ReadWalker.java:93)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:893)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:136)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:152)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:195)
	at org.broadinstitute.hellbender.Main.main(Main.java:275)

**Comment by droazen** [comment]
@takutosato Well, how much memory did you give the tool itself? (ie., what was your `-Xmx` value)

**Comment by takutosato** [comment]
@droazen I didn't specify `-Xmx`, just gave it more memory to the server (up to 32GB). The most memory BQSR consumed before it failed was about 28GB: ``Runtime.totalMemory()=28631367680``

I'm testing to see if scattering BaseRecalibrator and then calling GatherBQSRReports would help

**Comment by droazen** [comment]
@takutosato Can you try specifying `-Xmx` explicitly (`./gatk --java-options "-Xmx Xg"`), set it to a value substantially lower than the amount of physical memory, and see if that helps?

**Comment by takutosato** [comment]
I tried `java -Xmx8g`, and got `Runtime.totalMemory()=5783945216.` The physical memory was 32GB.

**Comment by droazen** [comment]
@takutosato To clarify, it ran out of memory with `-Xmx8g` as well?

**Comment by takutosato** [comment]
Yup
