### ISSUE TITLE
funcotator and file locking

### ISSUE THREAD

**Issue by jhl667** [broadinstitute/gatk#4413]
Hi all,

Below error occurs trying to access Funcotator data source directory installed on lustre file system.  We have a non-lustre mounted fs for cases like this, but I thought it was worth bringing up.

```
org.broadinstitute.hellbender.exceptions.GATKException: Unable to query the database for geneName: null
	at org.broadinstitute.hellbender.tools.funcotator.dataSources.cosmic.CosmicFuncotationFactory.createFuncotations(CosmicFuncotationFactory.java:244)
	at org.broadinstitute.hellbender.tools.funcotator.Funcotator.enqueueAndHandleVariant(Funcotator.java:404)
	at org.broadinstitute.hellbender.tools.funcotator.Funcotator.apply(Funcotator.java:316)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.lambda$traverse$0(VariantWalkerBase.java:110)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.traverse(VariantWalkerBase.java:108)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:893)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:136)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:152)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:195)
	at org.broadinstitute.hellbender.Main.main(Main.java:275)
Caused by: org.sqlite.SQLiteException: [SQLITE_IOERR_LOCK]  I/O error in the advisory file locking logic (disk I/O error)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.throwex(DB.java:886)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:127)
	at org.sqlite.core.DB.prepare(DB.java:227)
	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:81)
	at org.broadinstitute.hellbender.tools.funcotator.dataSources.cosmic.CosmicFuncotationFactory.createFuncotations(CosmicFuncotationFactory.java:215)
	... 21 more

```

**Comment by jonn-smith** [comment]
@jhl667 I'm looking into this.

It looks like I neglected to set the sqlite connection to read only mode when connecting to the db file.  I'm going to update it to do so.

I'm not sure this applies when a read-only connection is created, but it looks like sqlite has some issues with NFS / distributed file systems:
- https://stackoverflow.com/questions/9907429/locking-sqlite-file-on-nfs-filesystem-possible 
- https://github.com/CGATOxford/CGATPipelines/issues/

One post in the github thread above mentions using `-o flock` when mounting Lustre partitions so that they all have concurrent locks.  This _may_ be a workaround in the meantime.  

I'll try to look at it on our NFS mounts - I don't have access to a Lustre fs.

**Comment by jonn-smith** [comment]
Need to test the fix for this on a distributed file system.

**Comment by LeeTL1220** [comment]
Tried w/ 11 simultaneous funcotator runs all exactly the same except for output file name and had no issue.

**Comment by LeeTL1220** [comment]
Local Broad internal NFS

**Comment by LeeTL1220** [comment]
If I get a chance I will up it to 50 or so

**Comment by LeeTL1220** [comment]
I am having trouble getting compute for more than 15 simultaneous runs, but 15 seems to work fine on NFS.

**Comment by LeeTL1220** [comment]
@jonn-smith Any objection if I close this?

**Comment by jonn-smith** [comment]
@droazen No objection here.  It may be that my changing the db access to read only fixed the issue.
