### ISSUE TITLE
GarbageCollector error in GenotypeGVCFs after GenomicsDBImport after HaplotypeCaller 

### ISSUE THREAD

**Issue by sachalau** [broadinstitute/gatk#4467]
Hello,

I am using the latest gatk4 from bioconda (4.0.2.0-0).

I have genotyped 40 bacterial samples with HaplotypeCaller and -ERC BP_RESOLUTION. I have then merged the gvcfs files in a genomic db using GenomicsDBImport.

However, when I try genotyping this genomics db, the genotyper starts but hangs rather rapidly like so : 

```
07:18:31.127 INFO  ProgressMeter -    NC_016854.1:20000              0.2                 20000          86132.6
07:18:42.173 INFO  ProgressMeter -    NC_016854.1:58000              0.4                 58000         139322.6
07:21:16.150 INFO  ProgressMeter -    NC_016854.1:82000              3.0                 82000          27493.1
07:21:27.087 INFO  ProgressMeter -    NC_016854.1:99000              3.2                 99000          31280.9
07:24:06.157 INFO  ProgressMeter -   NC_016854.1:102000              5.8                102000          17537.7
07:24:16.220 INFO  ProgressMeter -   NC_016854.1:138000              6.0                138000          23062.5
07:24:29.116 INFO  ProgressMeter -   NC_016854.1:175000              6.2                175000          28231.8
07:43:58.742 INFO  GenotypeGVCFs - Shutting down engine
GENOMICSDB_TIMER,GenomicsDB iterator next() timer,Wall-clock time(s),29.644886145999088,Cpu time(s),29.480321756000397
Using GATK jar /opt/conda/envs/789546e2/share/gatk4-4.0.1.1-0/gatk-package-4.0.1.1-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -jar /opt/conda/envs/789546e2/share/gatk4-4.0.1.1-0/gatk-package-4.0.1.1-local.jar GenotypeGVCFs -ploidy 1 -R references/359488/genome_fasta.fasta --annotate-with-num-discovered-alleles true --annotations-to-exclude InbreedingCoeff -V gendb://typing/gatk_gvcfs/full_genome/359488/bwa/genomics_db -O typing/gatk_gvcfs/full_genome/359488/bwa/all_samples.vcf
```
In between the last ProgressMeter and the Shutting down of the engine, I see the java process still running with top.

Do you know what could be causing the problem ? Could it be related to -ERC BP_RESOLUTION ? I used to use -ERC GVCF before but I would rather keep the information of the coverage for post filtering, and I am not sure how to use --GVCFGQBands to match my criteria for coverage filtering.

Thanks a lot for your help !

Edit: sorry with the latest version of gatk I get a new message error :
```
08:22:54.446 INFO  ProgressMeter -    NC_016854.1:20000              0.2                 20000          87450.8
08:23:04.942 INFO  ProgressMeter -    NC_016854.1:58000              0.4                 58000         143694.8
08:25:25.155 INFO  ProgressMeter -    NC_016854.1:82000              2.7                 82000          29921.4
08:25:35.161 INFO  ProgressMeter -   NC_016854.1:100000              2.9                100000          34396.6
08:28:02.395 INFO  ProgressMeter -   NC_016854.1:102000              5.4                102000          19025.7
08:28:13.248 INFO  ProgressMeter -   NC_016854.1:140000              5.5                140000          25261.3
08:28:24.027 INFO  ProgressMeter -   NC_016854.1:175000              5.7                175000          30585.2
08:46:13.574 INFO  GenotypeGVCFs - Shutting down engine
GENOMICSDB_TIMER,GenomicsDB iterator next() timer,Wall-clock time(s),29.232685148998623,Cpu time(s),29.09919726900138
[February 28, 2018 8:46:13 AM UTC] org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 23.59 minutes.
Runtime.totalMemory()=5588910080
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.GeneralPloidyExactAFCalculator$CombinedPoolLikelihoods.getLikelihoodOfConformation(GeneralPloidyExactAFCalculator.java:61)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.GeneralPloidyExactAFCalculator.computeLofK(GeneralPloidyExactAFCalculator.java:283)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.GeneralPloidyExactAFCalculator.calculateACConformationAndUpdateQueue(GeneralPloidyExactAFCalculator.java:187)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.GeneralPloidyExactAFCalculator.fastCombineMultiallelicPool(GeneralPloidyExactAFCalculator.java:148)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.GeneralPloidyExactAFCalculator.combineSinglePools(GeneralPloidyExactAFCalculator.java:112)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.GeneralPloidyExactAFCalculator.computeLog10PNonRef(GeneralPloidyExactAFCalculator.java:25)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.AFCalculator.getLog10PNonRef(AFCalculator.java:33)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.GenotypingEngine.calculateGenotypes(GenotypingEngine.java:255)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.GenotypingEngine.calculateGenotypes(GenotypingEngine.java:210)
	at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.calculateGenotypes(GenotypeGVCFs.java:266)
	at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.regenotypeVC(GenotypeGVCFs.java:222)
	at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.apply(GenotypeGVCFs.java:201)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.lambda$traverse$0(VariantWalkerBase.java:110)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase$$Lambda$82/1457352442.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.traverse(VariantWalkerBase.java:108)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:893)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:135)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:180)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:199)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:159)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:201)
	at org.broadinstitute.hellbender.Main.main(Main.java:287)
Using GATK jar /opt/conda/envs/4931d9c1/share/gatk4-4.0.2.0-0/gatk-package-4.0.2.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -jar /opt/conda/envs/4931d9c1/share/gatk4-4.0.2.0-0/gatk-package-4.0.2.0-local.jar GenotypeGVCFs -ploidy 1 -R references/359488/genome_fasta.fasta --annotate-with-num-discovered-alleles true --annotations-to-exclude InbreedingCoeff -V gendb://typing/gatk_gvcfs/full_genome/359488/bwa/genomics_db -O typing/gatk_gvcfs/full_genome/359488/bwa/all_samples.vcf
```

Problem with  the GarbageCollector ?

**Comment by lbergelson** [comment]
@Cashalow The GC error indicates that you are running out of memory.  How much physical memory does your machine have, and how much are you allocating with `-Xmx`?

**Comment by Cashalow** [comment]
okay thanks a lot, I have tried with more resources than the standard which was 8Go I think. However I was wondering whether you knew what were the main parameters that influence the amount of Ram need by GenotypeGVCFs. For this particular example I only used 50 of them for instance. Do you know whether  the -ERC BP_RESOLUTION instead of -ERC GVCF of haplotype caller will cause GenotypeGVCF to consume more RAM for instance ?

**Comment by Cashalow** [comment]
Hello again ! 

I have tried with many different setups, allowing for more RAM (23Go) and with -ERC GVCF instead of -ERC BP_RESOLUTION but I can never GenotypeGVCF my dataset of 50 microbial genomes. 

I was looking for a bit of documentation and I found this related problem but old problem that should be fixed : https://gatkforums.broadinstitute.org/gatk/discussion/5585/genotypegvcfs-running-out-of-memory-with-50-samples

I probably have a lot of multi allelic sites in my data set too. Apparently this problem was fixed for CombineGVCFs however I am using GenomicsDBImport for merging all my GVCF. Do you think this might be causing the problem ? I am trying now to use CombineGVCFs to see if this resolves the problem.

**Comment by ldgauthier** [comment]
@Cashalow Can you include the full command line? 50 human genomes (ploidy 2) would need less than 7GB memory in my experience, even for highly multi-allelic indel sites.  I would expect ploidy 1 calls (as most users run microbial genomes) would require even less, but we have some diploid-specific optimizations.  Are you using the `new-qual` argument?  That QUAL calculation algorithm is less computationally intensive and I believe it is applicable to all ploidies.

**Comment by Cashalow** [comment]
Thanks for your help ! I was not using the `new-qual` argument. Here are the different command I used: 

```    
gatk-launch GenotypeGVCFs --java-options -Xmx23g -ploidy 1 -R $ref --annotations-to-exclude InbreedingCoeff -V gendb://gendb -O all_samples.vcf &> log
```

You don't think using CombineGVCFs or GenomicDBImport will make any change then ? I will try now using `new-qual`

**Comment by ldgauthier** [comment]
It's possible that GenomicsDB was also optimized for diploids and thusly slower for other ploidies because a lot of the code was ported from GATK.  I think `new-qual` is more likely to help, but you can certainly try CombineGVCFs.

I don't have a lot of good benchmarks, honestly, but maybe @lbergelson does.  GATK3 GenotypeGVCFs for 20,000 human samples took 113.54 hours for about 1.9Mbp, but that was on a CombinedGVCF already extracted from GenomicsDB.  With that many samples there are a lot of multi-allelics so that part should be similar to your data.  The java options were `java -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Xmx11500m`, so still less memory than your task seems to need.  And without `new-qual`. It also seems to be much faster than your run, but it's hard to say how runtime should scale with the number of samples.

**Comment by davidbenjamin** [comment]
New qual fixes this.  Closing since new qual has since become the only qual.
