### ISSUE TITLE
Funcotator hg38 data source not working; configuration files contains reference to files not present

### ISSUE THREAD

**Issue by jason-weirather** [broadinstitute/gatk#4521]
From ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/funcotator/ the file `gencode/hg38/gencode.config` makes reference to `gencode.v27.pc_transcripts.fasta` 

```
# Required field for GENCODE files.
# Path to the FASTA file from which to load the sequences for GENCODE transcripts:
gencode_fasta_path = gencode.v27.pc_transcripts.fasta
```

which is not present in the directory. 

```
$ ls
gencode.config
gencode.v27.chr_patch_hapl_scaff.annotation.REORDERED.gtf
gencode.v27.chr_patch_hapl_scaff.annotation.REORDERED.gtf.idx
gencode.v27.transcripts.dict
gencode.v27.transcripts.fasta
gencode.v27.transcripts.fasta.fai
```

Downloading the pc_transcript.fasta from gencode does not fix the errors thrown when trying to use the reference.  The error message is a fairly uninformative null pointer exception.  

```
00:27:35.745 INFO  Funcotator - Done initializing engine
00:27:35.758 INFO  Funcotator - Shutting down engine
[March 12, 2018 12:27:35 AM UTC] org.broadinstitute.hellbender.tools.funcotator.Funcotator done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=2258108416
java.lang.NullPointerException
	at org.broadinstitute.hellbender.tools.funcotator.Funcotator.closeTool(Funcotator.java:330)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:897)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:135)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:180)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:199)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:159)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:202)
	at org.broadinstitute.hellbender.Main.main(Main.java:288)
```

**Comment by jonn-smith** [comment]
@jason-weirather I see the error in the config file - this is definitely a bug in the data source release.  There will need to be another data sources release to fix this and another data sources bug.  I expect that this will be released by end of week.

I will run through some additional tests on hg38 data to see if I can duplicate the null pointer exception.

**Comment by jonn-smith** [comment]
@jason-weirather There is a new set of data sources available in the data sources area (v1.1).  I still haven't tested very thoroughly, but it should have all required files for hg38.

I'm planning to test this further later this week / early next week.

**Comment by jason-weirather** [comment]
Thanks @jonn-smith, I really appreciate your work in supporting hg38. In case its helpful, I gave your files a go was met with a pretty abrupt error and exit.  ... testing on 4.0.2.1

```
02:48:07.582 INFO  Funcotator - Initializing engine
02:48:07.988 INFO  FeatureManager - Using codec VCFCodec to read file file:///cluster/jasonw/Work/pd.vcf
02:48:08.012 INFO  Funcotator - Done initializing engine
02:48:08.047 INFO  Funcotator - Shutting down engine
[March 22, 2018 2:48:08 AM UTC] org.broadinstitute.hellbender.tools.funcotator.Funcotator done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=1948254208
java.lang.NullPointerException
	at org.broadinstitute.hellbender.tools.funcotator.Funcotator.closeTool(Funcotator.java:330)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:897)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:135)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:180)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:199)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:159)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:202)
	at org.broadinstitute.hellbender.Main.main(Main.java:288)
```

**Comment by jonn-smith** [comment]
OK - I'll start digging into this now.

**Comment by jonn-smith** [comment]
Alright, I've at least found (and fixed) a bug that was causing the error message to be so vague.  

I may have found the error you're running into as well, if so it should be fixed pretty quickly.

**Comment by jonn-smith** [comment]
@jason-weirather OK, I found the problem.  It was _another_ issue with the data sources.

I've fixed it in my local copy - we'll have to release another version tomorrow.

I have also made a few logging upgrades so you'll get more information about errors.

I'm opening the PR for this now.

**Comment by jason-weirather** [comment]
Hi @jonn-smith I had some success getting outputs with this.  However ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/funcotator/ is no longer accessible.  The most recent version of I accessed on 3/19/2018 still contained at least one error.  I'm trying to correct them myself as I go using a more recent build of GATK but it would be helpful if the data files required by this program were available.   The one I found is in `gencode_xrefseq.config` where it references a source that doesn't exist and I fixed that.  After that I was able to get outputs with hg38.  Thanks for your work on this!

**Comment by jonn-smith** [comment]
@jason-weirather Interesting.  I have no trouble accessing the FTP site from outside the Broad.  What kind of error message are you getting?

There is a new version from 3/29 that has several fixes in it, in addition you'll need to make sure you have the latest GATK code (you may need to pull the source code rather than a release - I'm not sure when the last release was and some fixes required both data source changes and code changes).  If you can wait a few days we're planning on doing another minor / bugfix release this week.

In general it's probably not worth trying to fix errors in the data sources - you may find yourself going down a rabbit hole.  That said, one of the things that was fixed was that data source line in the gencode file.

There shouldn't be very many __UNKNOWN__ fields (if any at all) - at least there aren't when running with the latest version of everything.

**Comment by jason-weirather** [comment]
Thanks @jonn-smith for the quick reply.  I think it was a browser or network issue on my end blocking me from the ftp before.  I tried again and got the new file.

ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/funcotator/funcotator_dataSources.v1.2.20180329.tar.gz

This is working for me strait out of the box.  I am using the newest gatk by building the docker image.

Its not as many `__UNKNOWN__` as I was seeing before with the old annotation.

Heres the first couple of non-comment lines from the MAF. I'm working with outputs from mutect2. 

```
Hugo_Symbol	Entrez_Gene_Id	Center	NCBI_Build	Chromosome	Start_Position	End_Position	Strand	Variant_Classification	Variant_Type	Reference_Allele	Tumor_Seq_Allele1	Tumor_Seq_Allele2	dbSNP_RS	dbSNP_Val_Status	Tumor_Sample_Barcode	Matched_Norm_Sample_Barcode	Match_Norm_Seq_Allele1	Match_Norm_Seq_Allele2	Tumor_Validation_Allele1	Tumor_Validation_Allele2	Match_Norm_Validation_Allele1	Match_Norm_Validation_Allele2	Verification_Status	Validation_Status	Mutation_Status	Sequencing_Phase	Sequence_Source	Validation_Method	Score	BAM_File	Sequencer	Tumor_Sample_UUID	Matched_Norm_Sample_UUID	Genome_Change	Annotation_Transcript	Transcript_Strand	Transcript_Exon	Transcript_Position	cDNA_Change	Codon_Change	Protein_Change	Other_Transcripts	Refseq_mRNA_Id	Refseq_prot_Id	SwissProt_acc_Id	SwissProt_entry_Id	Description	UniProt_AApos	UniProt_Region	UniProt_Site	UniProt_Natural_Variations	UniProt_Experimental_Info	GO_Biological_Process	GO_Cellular_Component	GO_Molecular_Function	COSMIC_overlapping_mutations	COSMIC_fusion_genes	COSMIC_tissue_types_affected	COSMIC_total_alterations_in_gene	Tumorscape_Amplification_Peaks	Tumorscape_Deletion_Peaks	TCGAscape_Amplification_Peaks	TCGAscape_Deletion_Peaks	DrugBank	ref_context	gc_content	CCLE_ONCOMAP_overlapping_mutations	CCLE_ONCOMAP_total_mutations_in_gene	CGC_Mutation_Type	CGC_Translocation_Partner	CGC_Tumor_Types_Somatic	CGC_Tumor_Types_Germline	CGC_Other_Diseases	DNARepairGenes_Activity_linked_to_OMIM	FamilialCancerDatabase_SyndromeMUTSIG_Published_Results	OREGANNO_ID	OREGANNO_Values	tumor_f	Achilles_Top_Genes	CGC_Name	CGC_GeneID	CGC_Chr	CGC_Chr_Band	CGC_Cancer_Somatic_Mut	CGC_Cancer_Germline_Mut	CGC_Cancer_Syndrome	CGC_Tissue_Type	CGC_Cancer_Molecular_Genetics	CGC_Other_Germline_Mut	CosmicFusion_fusion_id	DNARepairGenes_Chromosome_location_linked_to_NCBI_MapView	DNARepairGenes_Accession_number_linked_to_NCBI_Entrez	Familial_Cancer_Genes_Synonym	Familial_Cancer_Genes_Reference	Gencode_27_secondaryVariantClassification	Gencode_XHGNC_hgnc_id	HGNC_HGNC_ID	HGNC_Status	HGNC_Locus_Type	HGNC_Locus_Group	HGNC_Previous_Symbols	HGNC_Previous_Name	HGNC_Synonyms	HGNC_Name_Synonyms	HGNC_Chromosome	HGNC_Date_Modified	HGNC_Date_Symbol_Changed	HGNC_Date_Name_Changed	HGNC_Accession_Numbers	HGNC_Enzyme_IDs	HGNC_Ensembl_Gene_ID	HGNC_Pubmed_IDs	HGNC_RefSeq_IDs	HGNC_Gene_Family_ID	HGNC_Gene_Family_Name	HGNC_CCDS_IDs	HGNC_Vega_ID	HGNC_OMIM_ID(supplied_by_OMIM)	HGNC_RefSeq(supplied_by_NCBI)	HGNC_UniProt_ID(supplied_by_UniProt)	HGNC_Ensembl_ID(supplied_by_Ensembl)	HGNC_UCSC_ID(supplied_by_UCSC)	Oreganno_Build	Simple_Uniprot_alt_uniprot_accessions	dbSNP_ASP	dbSNP_ASS	dbSNP_CAF	dbSNP_CDA	dbSNP_CFL	dbSNP_COMMON	dbSNP_DSS	dbSNP_G5	dbSNP_G5A	dbSNP_GENEINFO	dbSNP_GNO	dbSNP_HD	dbSNP_INT	dbSNP_KGPhase1	dbSNP_KGPhase3	dbSNP_LSD	dbSNP_MTP	dbSNP_MUT	dbSNP_NOC	dbSNP_NOV	dbSNP_NSF	dbSNP_NSM	dbSNP_NSN	dbSNP_OM	dbSNP_OTH	dbSNP_PM	dbSNP_PMC	dbSNP_R3	dbSNP_RdbSNP_REF	dbSNP_RV	dbSNP_S3D	dbSNP_SAO	dbSNP_SLO	dbSNP_SSR	dbSNP_SYN	dbSNP_TOPMED	dbSNP_TPA	dbSNP_U3	dbSNP_U5	dbSNP_VC	dbSNP_VP	dbSNP_WGT	dbSNP_WTD	dbSNP_dbSNPBuildID	HGNC_Entrez_Gene_ID(supplied_by_NCBI)	dbSNP_RSPOS	
SAMD11	148398	__UNKNOWN__	hg38	1	938958	938958	+	Intron	SNP	C	C	A		false	__UNKNOWN__	__UNKNOWN__	__UNKNOWN__	__UNKNOWN__	__UNKNOWN__	__UNKNOWN__	__UNKNOWN__	__UNKNOWN__	__UNKNOWN__	__UNKNOWN__	__UNKNOWN__	__UNKNOWN__	__UNKNOWN__	__UNKNOWN__	NA	NA	__UNKNOWN__	__UNKNOWN__	__UNKNOWN__	g.chr1:938958C>A	ENST00000622503.4	+		SAMD11_ENST00000342066.7_Intron|SAMD11_ENST00000616016.4_Intron|SAMD11_ENST00000618779.4_Intron|SAMD11_ENST00000617307.4_Intron|SAMD11_ENST00000616125.4_Intron|SAMD11_ENST00000618181.4_Intron|SAMD11_ENST00000618323.4_Intron|SAMD11_ENST00000620200.4_Intron			Q96NU1	SAM11_HUMAN	sterile alpha motif domain containing 11	__UNKNOWN__	__UNKNOWN__	__UNKNOWN__	__UNKNOWN__	__UNKNOWN__	negative regulation of transcription from RNA polymerase II promoter (GO:0000122)	nucleus (GO:0005634)		0		biliary_tract(2)|breast(11)|central_nervous_system(44)|large_intestine(11)|lung(1)|pancreas(22)|upper_aerodigestive_tract(1)	92	__UNKNOWN__	__UNKNOWN__	__UNKNOWN__	__UNKNOWN__		ATGGTGGGTGCGGTCCAGGCT	0.6483790523690773	__UNKNOWN__	__UNKNOWN__					__UNKNOWN__			__UNKNOWN__					AL645608	HGNC:28706	Approved	gene with protein product	protein-coding gene			MGC45873		1p36.33	2014-11-19	BC024295		ENSG00000187634	12477932	NM_152486	760	Sterile alpha motif domain containing	CCDS2	OTTHUMG00000040719	616765	NM_152486	Q96NU1	ENSG00000187634	uc001abw.2		A2AA76|I7FV78|I7FV81|I7G0Z6|Q5SV96|Q5SV99|Q5SVA0|Q8N195|Q8TB59	false	false		false	false	false	false	false		false	false	false	false	false	false	false	false	false	false	false	false	false	false	false	false	false	false	false	false	false	false		false		false	false	false	false				false		148398		
```
Thanks!

**Comment by jonn-smith** [comment]
@jason-weirather No prob.

I'm glad it's working a little better.  Some of those `__UNKNOWN__`s are expected because there's no annotation source / value for them (like for `Center` and some of the other early annotations).  I'm not sure about some of the others, though.

FYI - I'll take a closer look tomorrow, but I put your data into Excel to line up the columns and it became misaligned which makes me a little concerned.
