### ISSUE TITLE
CombineGVCFs incorrectly parses last GVCF block consisting of HLA contig

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#4572]
Data is sensitive and bug is recapitulated in https://github.com/broadinstitute/dsde-docs/issues/3026.

CombineGVCFs gives the following error message:
```
java.lang.IllegalArgumentException: Invalid interval. Contig:HLA-DRB1*15:03:01:02 start:11569 end:11005
	at org.broadinstitute.hellbender.utils.Utils.validateArg(Utils.java:687)
	at org.broadinstitute.hellbender.utils.SimpleInterval.validatePositions(SimpleInterval.java:61)
	at org.broadinstitute.hellbender.utils.SimpleInterval.<init>(SimpleInterval.java:37)
	at org.broadinstitute.hellbender.tools.walkers.CombineGVCFs.onTraversalSuccess(CombineGVCFs.java:415)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:895)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:135)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:180)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:199)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:159)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:202)
	at org.broadinstitute.hellbender.Main.main(Main.java:288)
```
Here are the dictionary lines for two consecutive HLA-DRB1 contigs:
```
@SQ     SN:HLA-DRB1*15:03:01:02 LN:11569        M5:4e0d459b9bd15bff8645de84334e3d25     AS:38   UR:/seq/references/Homo_sapiens_assembly38/v0/Homo_sapiens_assembly38.fasta     SP:Homo sapiens
@SQ     SN:HLA-DRB1*16:02:01    LN:11005        M5:4a972df76bd3ee2857b87bd5be5ea00a     AS:38   UR:/seq/references/Homo_sapiens_assembly38/v0/Homo_sapiens_assembly38.fasta     SP:Homo sapiens
```
Notice the `LN` lengths match up. It appears that our tool is mistaking contig information.

**Comment by sooheelee** [comment]
I will assign to @droazen to delegate.

**Comment by droazen** [comment]
@cmnbroad Could you have a look at this one when you get a chance?

**Comment by sooheelee** [comment]
Original post on forum: https://gatkforums.broadinstitute.org/gatk/discussion/comment/47226#Comment_47226

**Comment by cmnbroad** [comment]
@sooheelee I can see the original forum post, but I get a 404 when I click on the link at the top of this ticket (https://github.com/broadinstitute/dsde-docs/issues/3026).

**Comment by sooheelee** [comment]
We need to ask @vdauwera to give you permission to view the dsde-docs repo.

**Comment by sooheelee** [comment]
In the meanwhile, I've SLACKed you the location of the data @cmnbroad.

**Comment by cmnbroad** [comment]
Thanks @sooheelee. The code is definitely not correctly reconciling the accumulated variants/blocks that are remaining when traversal ends. I have a fix that resolves it, at least for this case, but this needs some more analysis and I'm going to have to write some additional tests to be sure that its correct.

**Comment by sooheelee** [comment]
Great to hear there is a fix so soon @cmnbroad. Let me know if I can help out with creating test data.

**Comment by sooheelee** [comment]
Fyi @cmnbroad, the researcher has clarified that this error occurs for other primary assembly contigs, e.g. chr1. See their clarification [here](https://gatkforums.broadinstitute.org/gatk/discussion/comment/47226#Comment_47226).

**Comment by cmnbroad** [comment]
The fix for this issue is merged, but there are a couple of PRs for related issues (https://github.com/broadinstitute/gatk/pull/4680 and https://github.com/broadinstitute/gatk/pull/4681) that should be merged before we do a release.
