### ISSUE TITLE
IndexOutOfBoundsException of Mutect2/GATK 4.0.2.1

### ISSUE THREAD

**Issue by wangyugui** [broadinstitute/gatk#4578]
Hi.

IndexOutOfBoundsException of Mutect2/GATK 4.0.2.1.

```
# java -jar /usr/hpc-bio/gatk/gatk-package-4.0.2.1-local.jar Mutect2 --verbosity WARNING -R /usr/bio-ref/GRCh38.p0.dnaref/dnaf.fa --germline-resource /usr/bio-ref/GRCh38.p0.dnaref/common.vcf --max-reads-per-alignment-start 100 -L X -I /biowrk/BaseSpace/bam.bwa/HiSe
qX-PCR-free-v2.5-NA12878/md.bam -tumor HiSeqX-PCR-free-v2.5-NA12878 -O mutect2.tumor-only.vcf
23:17:38.084 WARN  IntelPairHmm - Flush-to-zero (FTZ) is enabled when running PairHMM
[March 26, 2018 11:17:38 PM CST] org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2 done. Elapsed time: 0.08 minutes.
Runtime.totalMemory()=2384986112
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2Engine.isActive(Mutect2Engine.java:316)
        at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.loadNextAssemblyRegion(AssemblyRegionIterator.java:159)
        at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.next(AssemblyRegionIterator.java:135)
        at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.next(AssemblyRegionIterator.java:34)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:290)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:271)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:893)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:135)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:180)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:199)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:159)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:202)
        at org.broadinstitute.hellbender.Main.main(Main.java:288)
```

but it works well on some other chr/region too.

**Comment by wangyugui** [comment]
Hi.

Same Error on 4.0.3.0
```
java -jar /usr/hpc-bio/gatk/gatk-package-4.0.3.0-local.jar Mutect2 --verbosity WARNING -R /usr/bio-ref/GRCh38.p0.dnaref/dnaref.fa --germline-resource /usr/bio-ref/GRCh38.p0.dnaref/common.vcf --max-reads-per-alignment-start 100 -L X -I /biowrk/BaseSpace/bam.bwa/HiSeqX-PCR-free-v2.5-NA12878/md.bam -tumor HiSeqX-PCR-free-v2.5-NA12878 -O mutect2.tumor-only.vcf
23:50:01.301 WARN  IntelPairHmm - Flush-to-zero (FTZ) is enabled when running PairHMM
[March 28, 2018 11:50:04 PM CST] org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2 done. Elapsed time: 0.17 minutes.
Runtime.totalMemory()=2354577408
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2Engine.isActive(Mutect2Engine.java:316)
        at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.loadNextAssemblyRegion(AssemblyRegionIterator.java:159)
        at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.next(AssemblyRegionIterator.java:135)
        at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.next(AssemblyRegionIterator.java:34)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:290)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:271)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:893)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:134)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

**Comment by droazen** [comment]
@davidbenjamin Could you have a look at this one when you get a chance? Looks like it might be a bug in `Mutect2Engine.isActive()`

**Comment by davidbenjamin** [comment]
@wangyugui This could happen if your germline resource doesn't have an allele frequency (AF) INFO field on the X chromosome, at least for some variants.    Without AF the germline resource doesn't do anything, and you might as well just run M2 without the germline resource when this is the case.  By the way, what resource are you using?  It doesn't look like gnomAD, which is the best option.  I thought that somewhere there were hg38 versions.

That said, this is still a bug and I will fix it.

**Comment by wangyugui** [comment]
yes. there is no INFO/AF. but there is a INFO/CAF info
This is a dbsnp(common) vcf file.

**Comment by wangyugui** [comment]
The same command works well on MT, but failed on X; 
Is there any other reason too?

**Comment by davidbenjamin** [comment]
@wangyugui I think that I'm against supporting INFO/CAF, first because trying to support non-standard annotations could get messy, and secondly because we want people to use gnomAD.  If you really want to use dbSNP you could always do something like:
```bash
gunzip dbsnp.vcf.gz
sed 's/CAF/AF/g' dbsnp.vcf > dbsnp_for_m2.vcf
java -jar $gatk IndexFeatureFile -F dbsnp_for_m2.vcf
```
But again, we do not recommend this!  In fact, we would probably name the `--germline-resource` argument `--gnomad` if it weren't for people using Mutect2 for dogs, mitochondria etc.

**Comment by wangyugui** [comment]
sed 's/CAF/AF/g' dbsnp.vcf > dbsnp_for_m2.vcf does NOT work.
because CAF is diff from AF in format, not just name.

**Comment by davidbenjamin** [comment]
Ah, I see -- it seems like the difference is that the CAF includes the reference allele while AF doesn't.  Is that right?  So you would have `AF=0.1` and `CAF=0.9,0.1`.  I have to imagine there is some sort of bash trickery you could do.  For example, if every site has at least one alt allele, and therefore CAF always has a comma, you could delete everything from the `=` (exclusive) until the `,` (inclusive) like this (
```bash
sed sed 's/CAF\=[^,]*\,/AF\=/g' dbsnp.vcf > dbsnp_for_m2.vcf
```
which replaces `CAF=[anything except a comma, which here is the ref AF],` with `AF=`.

**Comment by wangyugui** [comment]
with these fix, it works now

```
sed 's/CAF\=[^,]*\,/AF\=/g' 
sed 's/##INFO=<ID=CAF,Number=R/##INFO=<ID=AF,Number=A/g'
sed 's#AF=\.;#AF=0;#g' 
```

please fix these case if possible.
1)no INFO/AF in vcf record
2)AF=. in VCF record

**Comment by davidbenjamin** [comment]
PR #4607, which ought to fix this, has been merged.

**Comment by flinz** [comment]
Can confirm that this fixed the same issue for me.

**Comment by davidbenjamin** [comment]
@flinz Thanks for confirming!

**Comment by lamz138138** [comment]
Hi @davidbenjamin 

I meet a similar problem when running GATK-4.1.2.0, the weird thing is it finished successfully for some samples. 

My command is:

`toolPath/gatk --java-options "-Xmx30G -Djava.io.tmpdir=./tmp" Mutect2 -I C150589TF.bam -I C150589NF.bam -normal C150589NF -R /path/to/reference/gatk/GRCh38.d1.vd1.fa --panel-of-normals /path/to/mutect2/pon/chr16.vcf.gz --germline-resource /path/to/gnomAD/gnomad.genomes.r3.0.sites.chr16.vcf.bgz -L chr16 -O unfiltered-chr16.vcf >mutect2-chr16.log 2>mutect2-chr16.err`

The last lines of mutect2-chr16.err:
```
08:40:14.455 INFO  ProgressMeter -       chr16:34593354             22.7                132470           5832.0
08:41:07.915 INFO  ProgressMeter -       chr16:34595109             23.6                132480           5612.3
08:42:02.710 INFO  VectorLoglessPairHMM - Time spent in setup for JNI call : 0.735608267
08:42:02.710 INFO  PairHMM - Total compute time in PairHMM computeLogLikelihoods() : 609.8425236940001
08:42:02.710 INFO  SmithWatermanAligner - Total compute time in java Smith-Waterman : 142.16 sec
08:42:02.711 INFO  Mutect2 - Shutting down engine
[December 4, 2019 8:42:02 AM CST] org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2 done. Elapsed time: 24.59 minutes.
Runtime.totalMemory()=2076049408
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.lambda$getGermlineAltAlleleFrequencies$31(SomaticGenotypingEngine.java:350)
        at java.util.stream.ReferencePipeline$6$1.accept(ReferencePipeline.java:244)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.util.stream.DoublePipeline.toArray(DoublePipeline.java:506)
        at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.getGermlineAltAlleleFrequencies(SomaticGenotypingEngine.java:352)
        at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.getNegativeLogPopulationAFAnnotation(SomaticGenotypingEngine.java:335)
        at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.callMutations(SomaticGenotypingEngine.java:141)
        at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2Engine.callRegion(Mutect2Engine.java:250)
        at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2.apply(Mutect2.java:324)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:308)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:281)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1039)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
        at org.broadinstitute.hellbender.Main.main(Main.java:291)
```

Then, I try to run 3 jobs for testing: 1) without --panel-of-normals and --germline-resource; 2)  without --panel-of-normals; 3) without --germline-resource. All three jobs finished success. Can you help me solve the problem? 

Thanks in davance!

**Comment by davidbenjamin** [comment]
@lamz138138 Was your panel of normals created by `CreateSomaticPanelOfNormals`?  Any reason not to use our best practices germline resource gs://gatk-best-practices/somatic-hg38/af-only-gnomad.hg38.vcf.gz?

If you wish to dig into this, you could find the last line of the output Mutect2 vcf (it ought to produce output before it crashes, and the last line will be the last successfully emitted site).  Then you could post here the contents of your panel of normals and germine resource within 1000 bases of that site.

**Comment by D0g4** [comment]
I am having the same problem.
The last lines read as follow:
```
12:15:53.217 INFO  ProgressMeter -        chr3:73018046            285.5               2140110           7497.0
12:16:03.395 INFO  ProgressMeter -        chr3:73445027            285.6               2141720           7498.2
12:16:13.407 INFO  ProgressMeter -        chr3:75481384            285.8               2149100           7519.7
12:16:16.285 INFO  VectorLoglessPairHMM - Time spent in setup for JNI call : 4.453178435
12:16:16.286 INFO  PairHMM - Total compute time in PairHMM computeLogLikelihoods() : 2290.3264339380003
12:16:16.286 INFO  SmithWatermanAligner - Total compute time in java Smith-Waterman : 4541.79 sec
12:16:16.289 INFO  Mutect2 - Shutting down engine
[April 20, 2020 12:16:16 PM UTC] org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2 done. Elapsed time: 285.86 minutes.
Runtime.totalMemory()=8561098752
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.lambda$getGermlineAltAlleleFrequencies$26(SomaticGenotypingEngine.java:339)
	at java.util.stream.ReferencePipeline$6$1.accept(ReferencePipeline.java:244)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.DoublePipeline.toArray(DoublePipeline.java:508)
	at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.getGermlineAltAlleleFrequencies(SomaticGenotypingEngine.java:341)
	at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.getNegativeLogPopulationAFAnnotation(SomaticGenotypingEngine.java:324)
	at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.callMutations(SomaticGenotypingEngine.java:146)
	at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2Engine.callRegion(Mutect2Engine.java:251)
	at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2.apply(Mutect2.java:320)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:308)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:281)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
	at org.broadinstitute.hellbender.Main.main(Main.java:292)
```
I downloaded the file from gnomAD repository ("All chromosomes VCF"), but had to do some changes, as follow:
1. Lifted over to hg19, by using [b37tohg19.chain](https://github.com/broadgsa/gatk/blob/master/public/chainFiles/b37tohg19.chain) by using:
```
sudo java -jar /picard-2.21.3/picard.jar LiftoverVcf I=ExAC.r1.sites.vep.vcf.gz O=ExAC_hg19.r1.sites.vep.vcf.gz CHAIN=b37tohg19.chain REJECT=rejected_variants.vcf R=/reference/hg19/hg19.fa ALLOW_MISSING_FIELDS_IN_HEADER=true MAX_RECORDS_IN_RAM=100000
```
2. Got rid of the [chrN_random tables](http://genome.ucsc.edu/FAQ/FAQdownloads#download10) by manually deleting them from the header of ```ExAC_hg19.r1.sites.vep.vcf.gz``` and creating a new file with just the new header, ```header_hg19_Ion.vcf```; and

3. Fixed the header by using:
```
java -jar picard.jar FixVcfHeader I=/gatk_data/reference/gnomAD/gnomad.exomes_hg19.r2.1.1.sites.vcf.bgz O=/gatk_data/reference/gnomAD/gnomad.exomes_hg19_Ion.r2.1.1.sites.vcf.bgz HEADER=/gatk_data/reference/gnomAD/header_hg19_Ion.vcf MAX_RECORDS_IN_RAM=70000
```

I am bit lost on where the error might be, Any help is greatly appreciated.
Thanks!

**Comment by xiucz** [comment]
I am having the same problem...

```
[August 27, 2020 2:10:07 PM CST] org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2 done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=1859649536
java.nio.BufferUnderflowException
        at java.nio.ByteBuffer.get(ByteBuffer.java:688)
        at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:285)
        at java.nio.ByteBuffer.get(ByteBuffer.java:715)
        at htsjdk.samtools.MemoryMappedFileBuffer.readBytes(MemoryMappedFileBuffer.java:34)
        at htsjdk.samtools.AbstractBAMFileIndex.readBytes(AbstractBAMFileIndex.java:439)
        at htsjdk.samtools.AbstractBAMFileIndex.verifyIndexMagicNumber(AbstractBAMFileIndex.java:376)
        at htsjdk.samtools.AbstractBAMFileIndex.<init>(AbstractBAMFileIndex.java:70)
        at htsjdk.samtools.AbstractBAMFileIndex.<init>(AbstractBAMFileIndex.java:64)
        at htsjdk.samtools.CachingBAMFileIndex.<init>(CachingBAMFileIndex.java:56)
        at htsjdk.samtools.BAMFileReader.getIndex(BAMFileReader.java:418)
        at htsjdk.samtools.BAMFileReader.createIndexIterator(BAMFileReader.java:952)
        at htsjdk.samtools.BAMFileReader.query(BAMFileReader.java:612)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:533)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:405)
        at org.broadinstitute.hellbender.utils.iterators.SamReaderQueryingIterator.loadNextIterator(SamReaderQueryingIterator.java:125)
        at org.broadinstitute.hellbender.utils.iterators.SamReaderQueryingIterator.<init>(SamReaderQueryingIterator.java:66)
        at org.broadinstitute.hellbender.engine.ReadsDataSource.prepareIteratorsForTraversal(ReadsDataSource.java:416)
        at org.broadinstitute.hellbender.engine.ReadsDataSource.iterator(ReadsDataSource.java:342)
        at org.broadinstitute.hellbender.engine.MultiIntervalLocalReadShard.iterator(MultiIntervalLocalReadShard.java:134)
        at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.<init>(AssemblyRegionIterator.java:86)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:188)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:173)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
        at org.broadinstitute.hellbender.Main.main(Main.java:292)
```

and my command:
```
gatk-4.1.7.0/gatk Mutect2 -force-active -R ~/hg19/gatk_bundle/ucsc.hg19.fasta \
-I bam/T.BQSR.reheader.bam --alleles xx.vcf -O gga.vcf -L total.site.bed -ip 200
```
