### ISSUE TITLE
CombineGVCFs: java.lang.ClassCastException

### ISSUE THREAD

**Issue by huangzhibo** [broadinstitute/gatk#4633]
When the gvcf was merged by "bcftools concat", the following error will be happen.

more info: 
https://gatkforums.broadinstitute.org/gatk/discussion/10817/gatk-runtime-error-on-genotypegvcfs-java-lang-double-cannot-be-cast-to-java-lang-integer

**java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer**
	at java.lang.Integer.compareTo(Integer.java:52)
	at java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:52)
	at java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:47)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:351)
	at java.util.TimSort.sort(TimSort.java:216)
	at java.util.Arrays.sort(Arrays.java:1507)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:302)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.broadinstitute.hellbender.utils.Utils.getMedianValue(Utils.java:1137)
	at org.broadinstitute.hellbender.tools.walkers.ReferenceConfidenceVariantContextMerger.mergeAttributes(ReferenceConfidenceVariantContextMerger.java:277)
	at org.broadinstitute.hellbender.tools.walkers.ReferenceConfidenceVariantContextMerger.merge(ReferenceConfidenceVariantContextMerger.java:101)
	at org.broadinstitute.hellbender.tools.walkers.CombineGVCFs.endPreviousStates(CombineGVCFs.java:340)
	at org.broadinstitute.hellbender.tools.walkers.CombineGVCFs.createIntermediateVariants(CombineGVCFs.java:189)
	at org.broadinstitute.hellbender.tools.walkers.CombineGVCFs.apply(CombineGVCFs.java:134)
	at org.broadinstitute.hellbender.engine.MultiVariantWalkerGroupedOnStart.apply(MultiVariantWalkerGroupedOnStart.java:73)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.lambda$traverse$0(VariantWalkerBase.java:110)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase$$Lambda$87/908435478.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
        .......

**Comment by cmnbroad** [comment]
This happens when merging variant contexts that have a floating point attribute, i.e. MQRankSum, and some sites have the integer value "0". The same issue occurs in GATK 3.

**Comment by lbergelson** [comment]
@cmnbroad It would be good if we could fix this....

**Comment by cmnbroad** [comment]
Fixed via https://github.com/broadinstitute/gatk/pull/4680.
