### ISSUE TITLE
Bug report:HaplotypeCaller haploid GVCF format error?

### ISSUE THREAD

**Issue by yoshim7910** [broadinstitute/gatk#4657]
I prepared a clean Bam file following GATK Best Practice and used GATK4 HaplotypeCaller to create a gvcf with ploidy1 option:

'''
gatk-4.0.2.1/gatk HaplotypeCaller --native-pair-hmm-threads 24 -I KU_filtered_sorted_mdup.bam -O HC.KU.raw.snps.indels.g.vcf -R ref.fasta -ploidy 1 --emit-ref-confidence GVCF
'''

When I validated the gvcf, ValidateVariants threw errors at the end:

'''
<br />11:27:55.681 INFO  ProgressMeter - Traversal complete. Processed 124689522 total variants in 3.8 minutes.
11:27:55.681 INFO  ValidateVariants - Shutting down engine
[April 10, 2018 11:27:55 AM JST] org.broadinstitute.hellbender.tools.walkers.variantutils.ValidateVariants done. Elapsed time: 3.82 minutes.
Runtime.totalMemory()=4682940416
java.lang.IllegalArgumentException: Illegal character in path at index 15:HC.KU.raw.snps.indels.g.vcf
    at java.net.URI.create(URI.java:852)
    at org.broadinstitute.hellbender.engine.FeatureInput.makeIntoAbsolutePath(FeatureInput.java:242)
    at org.broadinstitute.hellbender.engine.FeatureInput.toString(FeatureInput.java:314)
    at java.util.Formatter$FormatSpecifier.printString(Formatter.java:2886)
    at java.util.Formatter$FormatSpecifier.print(Formatter.java:2763)
    at java.util.Formatter.format(Formatter.java:2520)
    at java.util.Formatter.format(Formatter.java:2455)
    at java.lang.String.format(String.java:2940)
    at org.broadinstitute.hellbender.engine.FeatureDataSource.close(FeatureDataSource.java:589)
    at org.broadinstitute.hellbender.engine.FeatureManager.lambda$close$9(FeatureManager.java:505)
    at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
    at org.broadinstitute.hellbender.engine.FeatureManager.close(FeatureManager.java:505)
    at org.broadinstitute.hellbender.engine.GATKTool.onShutdown(GATKTool.java:857)
    at org.broadinstitute.hellbender.engine.VariantWalker.onShutdown(VariantWalker.java:95)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:138)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:180)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:199)
    at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:159)
    at org.broadinstitute.hellbender.Main.mainEntry(Main.java:202)
    at org.broadinstitute.hellbender.Main.main(Main.java:288)
Caused by: java.net.URISyntaxException: Illegal character in path at index 15: /media/yoshi/My Book/Aet_v4.0_ChrSeqSplit/HC.KU-2103.raw.snps.indels.g.vcf
    at java.net.URI$Parser.fail(URI.java:2848)
    at java.net.URI$Parser.checkChars(URI.java:3021)
    at java.net.URI$Parser.parseHierarchical(URI.java:3105)
    at java.net.URI$Parser.parse(URI.java:3063)
    at java.net.URI.<init>(URI.java:588)
    at java.net.URI.create(URI.java:850)
    ... 19 more
'''

When I ran GenotypeGVCFs using the gvcf, it ran to completion, but threw the same "java.lang.IllegalArgumentException" errors at the end.

I have submitted a bug report to FTP server.
The name of the uploaded archive file is YoshiM_BugReport.tar.gz.

**Comment by cmnbroad** [comment]
Hi @yoshim7910- can you post the full path name of the location where the input variant file was ? It looks like it probably contains a character that isn't legal in a URI.

**Comment by yoshim7910** [comment]
Hi @cmnbroad - Here is the location and full command used:

'/home/yoshi/GATK/gatk-4.0.2.1/gatk' ValidateVariants -R '/media/yoshi/My Book/Aet_v4.0_ChrSeqSplit/Aet_v4.0_ChrSeqSplit.fasta' -V '/media/yoshi/My Book/Aet_v4.0_ChrSeqSplit/HC.KU-2103.raw.snps.indels.g.vcf' -gvcf

Many thanks

**Comment by yoshim7910** [comment]
Hi @cmnbroad - I removed a space in the path and re-ran ValidateVariants. It went through throwing no errors. Many thanks.
