### ISSUE TITLE
Error in gcnv kernel of DetermineGermlineContigPloidy

### ISSUE THREAD

**Issue by stefandiederich** [broadinstitute/gatk#4679]
Dear Sir or Madame, 

I am testing the germline CNV tools (GATK version 4.0.3.0). I know it is still in beta but maybe you can tell me what this error is about. 

```
13:16:06.332 INFO gcnvkernel.tasks.inference_task_base - (sampling epoch 1):   0%|          | 0/100 [00:00<?, ?it/s]
13:16:08.494 INFO gcnvkernel.tasks.inference_task_base - (sampling epoch 1) relative error: 1.0000 +/- 0.0000:   1%|1         | 1/100 [00:02<03:33,  2.16s/it]
13:16:10.652 INFO gcnvkernel.tasks.inference_task_base -
Stderr: Traceback (most recent call last):
  File "/tmp/die9s/cohort_determine_ploidy_and_depth.861556744637254264.py", line 106, in <module>
    gcnvkernel.io_ploidy.PloidyModelWriter(ploidy_config, ploidy_workspace,
AttributeError: module 'gcnvkernel.io.io_ploidy' has no attribute 'PloidyModelWriter'


at org.broadinstitute.hellbender.utils.python.PythonExecutorBase.getScriptException(PythonExecutorBase.java:75)
at org.broadinstitute.hellbender.utils.runtime.ScriptExecutor.executeCuratedArgs(ScriptExecutor.java:126)
at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeArgs(PythonScriptExecutor.java:170)
at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeScript(PythonScriptExecutor.java:151)
at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeScript(PythonScriptExecutor.java:121)
at org.broadinstitute.hellbender.tools.copynumber.DetermineGermlineContigPloidy.executeDeterminePloidyAndDepthPythonScript(DetermineGermlineContigPloidy.java:365)
at org.broadinstitute.hellbender.tools.copynumber.DetermineGermlineContigPloidy.doWork(DetermineGermlineContigPloidy.java:263)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:134)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

I also know that I should post errors in the GATK forum, but when I do this I get the following error message :
``` { "Code": 403, "Exception": "You need the Garden.Community.Manage permission to do that.", "Class": "Gdn_UserException" }```

Thanks in advance
Stefan

**Comment by samuelklee** [comment]
Hi @stefandiederich,

My guess is that you may have created your GATK conda environment with an older version of the GATK that did not include the changes to the `PloidyModelWriter`.  Can you try creating a new conda environment with 4.0.3.0 and re-running?

@vdauwera @sooheelee @chandrans Any idea what the forum error message is about?

**Comment by stefandiederich** [comment]
Hi @samuelklee 
yes you are right, I did not recreate the conda environment when updating to 4.0.3.0. I'll try that and give you a feedback. Do you know the state of developement of the germline CNV best practise or a short manual?

**Comment by stefandiederich** [comment]
Hi @samuelklee 
I updated my conda environment and it worked now. 
Sorry again for posting the error in github and not in the gatk forum, hopefully next time it will work.

Thanks again
Stefan

**Comment by sooheelee** [comment]
As our forum gets updates from Vanilla, sometimes we get new and unexpected glitches. These are typically ironed out fairly quickly. @tmm211 is handling Vanilla forum issues these days. Sorry for your error @stefandiederich.

**Comment by samuelklee** [comment]
@stefandiederich We are finalizing some hyperparameter optimizations and will have some results and recommendations to share within ~1 month.  You may find some preliminary recommendations for WES in this forum thread: https://gatkforums.broadinstitute.org/gatk/discussion/11711/germlinecnvcaller-interval-merging-rule-error

Once our optimizations are finalized, @vdauwera and her team will put together a tutorial and other workshop materials---stay tuned!

**Comment by tmm211** [comment]
@stefandiederich a patch went out to fix this at 10 AM this morning. Can you confirm you are no longer having trouble posting?

**Comment by stefandiederich** [comment]
Good morning :-)
@samuelklee 
Thanks for the link to the preliminary parameter. I will try them!

@tmm211 
Just tested the posting function on gatk main page. The error seems to be solved. Thank you!
