### ISSUE TITLE
[CNNScoreVariants] A timeout ocurred waiting for output from the remote Python command

### ISSUE THREAD

**Issue by heliac2000** [broadinstitute/gatk#4696]
In GATK 4.0.3, add `tensorflow-gpu==1.4.0` to `gatkcondaenv.yml `and create a conda environment.

    $ conda env create -n gatk_gpu -f gatkcondaenv.yml

Activate this environment and execute GATK CNNScoreVariants(1D model).

    $ gatk-4.0.3.0/gatk --java-options '-Xmx8G -DGATK_STACKTRACE_ON_USER_EXCEPTION=true' CNNScoreVariants -V INPUT_VCF -R REF -O OUTPUT_VCF

Then, GATK outputs the following:

```
18:30:57.468 INFO  CNNScoreVariants - Initializing engine
18:30:57.985 INFO  FeatureManager - Using codec VCFCodec to read file ...
18:30:58.183 INFO  IntervalArgumentCollection - Processing 48129895 bp from intervals
18:30:58.188 INFO  CNNScoreVariants - Done initializing engine
18:31:00.188 INFO  CNNScoreVariants - Using key:CNN_1D for CNN architecture:.../1d_cnn_mix_train_full_bn.2560984151625233621.json and weights:.../1d_cnn_mix_train_full_bn.2397909300265264152.hd5
18:31:19.873 INFO  ProgressMeter - Starting traversal
18:31:19.874 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
18:31:50.095 INFO  CNNScoreVariants - Shutting down engine
[2018/04/24 18:31:50 JST] org.broadinstitute.hellbender.tools.walkers.vqsr.CNNScoreVariants done. Elapsed time: 0.88 minutes.
Runtime.totalMemory()=2141716480
***********************************************************************
A USER ERROR has occurred: A timeout ocurred waiting for output from the remote Python command.
***********************************************************************
org.broadinstitute.hellbender.exceptions.UserException: A timeout ocurred waiting for output from the remote Python command.
        at org.broadinstitute.hellbender.utils.python.StreamingPythonScriptExecutor.getAccumulatedOutput(StreamingPythonScriptExecutor.java:219)
        at org.broadinstitute.hellbender.utils.python.StreamingPythonScriptExecutor.sendSynchronousCommand(StreamingPythonScriptExecutor.java:153)
        at org.broadinstitute.hellbender.tools.walkers.vqsr.CNNScoreVariants.onTraversalStart(CNNScoreVariants.java:260)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:891)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:134)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
Caused by: java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at org.broadinstitute.hellbender.utils.runtime.StreamingProcessController.getProcessOutput(StreamingProcessController.java:278)
        at org.broadinstitute.hellbender.utils.runtime.StreamingProcessController.getOutputSynchronizedBy(StreamingProcessController.java:192)
        at org.broadinstitute.hellbender.utils.runtime.StreamingProcessController.getProcessOutputByPrompt(StreamingProcessController.java:163)
        at org.broadinstitute.hellbender.utils.python.StreamingPythonScriptExecutor.getAccumulatedOutput(StreamingPythonScriptExecutor.java:209)
        ... 9 more
```

While this execution, continue watching the processes on GPU.

    $ watch -n 0.5 sh -c 'nvidia-smi | tail'
```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     63485      C   python                                     15422MiB |
|    1     63485      C   python                                     15358MiB |
|    2     63485      C   python                                     15358MiB |
|    3     63485      C   python                                     15358MiB |
|    4     63485      C   python                                     15358MiB |
|    5     63485      C   python                                     15358MiB |
|    6     63485      C   python                                     15358MiB |
|    7     63485      C   python                                     15358MiB |
+-----------------------------------------------------------------------------+
```

After GATK exits abnormally, these python processes remains for a while.

Environment:

- NVIDIA DGX-1(GPU: Tesla V100)
- Ubuntu 16.04
- NVIDIA driver 384.111
- CUDA 8.0
- cuDNN v6.0 for CUDA 8.0

**Comment by heliac2000** [comment]
Thanks for your reply. I try `--enable-journal` option and the following message is repeated many times.

    Received from stderr: [>>> ]

    Sending: [vqsr_cnn.score_and_write_batch(args, model, tempFile, fifoFile, 2, 2, '')
    ]

I trace the python process that is piped-forked by CNNScoreVariants.

    write(2, ">>> ", 4)                     = -1 EPIPE (Broken pipe)
    --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=58415, si_uid=xxxx} ---
    read(0, "", 1)                          = 0
    write(2, "\n", 1)                       = -1 EPIPE (Broken pipe)
    --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=58415, si_uid=xxxx} ---
    rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7f054d1fe5e0}, {0x5006d0, [], SA_RESTORER, 0x7f054d1fe5e0}, 8) = 0
    close(3)                                = 0
    write(4, "952\n1\t121482273\tA\t[G]\t-14.449\n1\t"..., 2018) = 2018
    close(4)                                = 0
                      :
    close(21)                               = 0
    exit_group(0)                           = ?
    +++ exited with 0 +++
    
EPIPE is occured after CNNScoreVariants stops.

**Comment by cmnbroad** [comment]
@heliac2000 Thanks for the trace. I suspect that once the timeout initially occurs, the GATK process terminates, but the Python process is still trying to write back to it and gets the "broken pipe" return code. We already have plan to make the IPC/timeout more robust. In the meantime it would be interesting to see the last 50-100 lines of the journal file if it contains contains anything other than the repeated `Sending: [vqsr_cnn.score_and_write_batch(args, model, tempFile, fifoFile, 2, 2, '')` lines (which are expected).
