### ISSUE TITLE
barclay fails to set collection arguments initialized with an immutable collection

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#4702]
If you have a barclay `@Argument` field of type `List`, barclay will fail to set the field value properly when the argument is specified if the `List` is initialized using an immutable Collection, such as that returned by `Collections.emptyList()`. Example error:

```
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at org.broadinstitute.barclay.argparser.CommandLineArgumentParser.setArgument(CommandLineArgumentParser.java:706)
	at org.broadinstitute.barclay.argparser.CommandLineArgumentParser.parseArguments(CommandLineArgumentParser.java:427)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.parseArgs(CommandLineProgram.java:220)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:194)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

**Comment by droazen** [comment]
For @cmnbroad

**Comment by magicDGS** [comment]
There's a solution here: https://github.com/broadinstitute/barclay/pull/102

**Comment by magicDGS** [comment]
Also, some discussion about what to do with immutable collections in barclay is here: https://github.com/broadinstitute/barclay/issues/100
