### ISSUE TITLE
Mutect2 not working in 4.0.5.0 ?

### ISSUE THREAD

**Issue by af8** [broadinstitute/gatk#4875]
```
/opt/jdk1.8.0_172/bin/java -jar /data-ddn/software/GATK4/4.0.3.0/gatk-package-4.0.3.0-local.jar Mutect2 -h | head

USAGE: Mutect2 [arguments]

Call somatic SNVs and indels via local assembly of haplotypes
Version:4.0.3.0


Required Arguments:

--input,-I:String             BAM/SAM/CRAM file containing reads  This argument must be specified at least once.
                              Required.

--output,-O:File              File to which variants should be written  Required.

--reference,-R:String         Reference sequence file  Required.

--tumor-sample,-tumor:String  BAM sample name of tumor.  May be URL-encoded as output by GetSampleName with -encode
                              argument.  Required.


...
```

while version 4.0.5.0 raises an error :

```
/opt/jdk1.8.0_172/bin/java -jar /data-ddn/software/GATK4/4.0.5.0/gatk-package-4.0.5.0-local.jar Mutect2 -h
java.lang.IllegalArgumentException: Allowed values request for unrecognized string argument: input
	at org.broadinstitute.hellbender.cmdline.GATKPlugin.GATKAnnotationPluginDescriptor.getAllowedValuesForDescriptorHelp(GATKAnnotationPluginDescriptor.java:246)
	at org.broadinstitute.barclay.argparser.CommandLineArgumentParser.usageForPluginDescriptorArgumentIfApplicable(CommandLineArgumentParser.java:870)
	at org.broadinstitute.barclay.argparser.CommandLineArgumentParser.makeArgumentDescription(CommandLineArgumentParser.java:847)
	at org.broadinstitute.barclay.argparser.CommandLineArgumentParser.printArgumentUsage(CommandLineArgumentParser.java:791)
	at org.broadinstitute.barclay.argparser.CommandLineArgumentParser.lambda$printArgumentUsageBlock$2(CommandLineArgumentParser.java:276)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.barclay.argparser.CommandLineArgumentParser.printArgumentUsageBlock(CommandLineArgumentParser.java:276)
	at org.broadinstitute.barclay.argparser.CommandLineArgumentParser.usage(CommandLineArgumentParser.java:308)
	at org.broadinstitute.barclay.argparser.CommandLineArgumentParser.parseArguments(CommandLineArgumentParser.java:417)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.parseArgs(CommandLineProgram.java:221)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:195)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)

```

Thank you,
Anthony

**Comment by cmnbroad** [comment]
@af8 thanks for the report. It does look like we introduced a change that causes this bug. It should only affect command line help requests ("-h"); the tool itself should work ok.

**Comment by tfenne** [comment]
FWIW I'm having the exact same issue with HaplotypeCaller.  It's not quite limited to just requests for help (`-h`).  Any completely valid command line works.  Any incorrect command line that also triggers display of the help text also fails with the same error message.

**Comment by cmnbroad** [comment]
@tfenne Yeah, the invalid command issue makes makes sense. HC, GenotypeGVCFs, CombineGVCFs and VariantAnnotator will all have this same behavior.

**Comment by droazen** [comment]
We are going to cut a release now to push out the fix for this issue.

**Comment by tfenne** [comment]
Thanks @droazen!
