### ISSUE TITLE
New qual parameter errors GenotypeGVCFs in v4.0.5.0.

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#4975]
Researcher reports error in GenotypeGVCFs that uses a GenomicsDB database using v4.0.5.0. Removing `new qual` param OR using v4.0.4.0 allows the command to run without error.

I saw a similar error with v4.0.5.1 when I tried to add `new qual` to a workshop hands-on tutorial GenotypeGVCFs step using a GenomicsDB database.

---
Hi,

I am trying to process locally 260 WES gvcf through joint discovery wdl pipeline. I encountered an error at GenotypeGVCFs below which I am not sure how to proceed.

I have used all the default reference libraries and only modified the merge_count in the script to be 8144 so that my server resources won't be maxout fully in the ImportGVCFs step. 

[https://github.com/gatk-workflows/gatk4-germline-snps-indels/blob/master/joint-discovery-gatk4-local.wdl](https://github.com/gatk-workflows/gatk4-germline-snps-indels/blob/master/joint-discovery-gatk4-local.wdl "https://github.com/gatk-workflows/gatk4-germline-snps-indels/blob/master/joint-discovery-gatk4-local.wdl")

```
23:17:43.992 WARN  InbreedingCoeff - Annotation will not be calculated, must provide at least 10 samples
23:17:44.064 WARN  InbreedingCoeff - Annotation will not be calculated, must provide at least 10 samples
23:17:46.334 INFO  GenotypeGVCFs - Shutting down engine
GENOMICSDB_TIMER,GenomicsDB iterator next() timer,Wall-clock time(s),30.197597194999727,Cpu time(s),28.791204838999864
[June 25, 2018 11:17:46 PM UTC] org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 4.01 minutes.
Runtime.totalMemory()=5354029056
java.lang.IllegalArgumentException: log10LikelihoodsOfAC are bad 2.559797571100845E-21,NaN
	at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.AFCalculationResult.<init>(AFCalculationResult.java:72)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.AlleleFrequencyCalculator.getLog10PNonRef(AlleleFrequencyCalculator.java:143)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.GenotypingEngine.calculateGenotypes(GenotypingEngine.java:255)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.GenotypingEngine.calculateGenotypes(GenotypingEngine.java:210)
	at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.calculateGenotypes(GenotypeGVCFs.java:266)
	at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.regenotypeVC(GenotypeGVCFs.java:222)
	at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.apply(GenotypeGVCFs.java:201)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.lambda$traverse$0(VariantWalkerBase.java:109)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.traverse(VariantWalkerBase.java:107)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:980)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:135)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:180)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:199)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
Using GATK jar /gatk/build/libs/gatk-package-4.0.5.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx5g -Xms5g -jar /gatk/build/libs/gatk-package-4.0.5.0-local.jar GenotypeGVCFs -R /cromwell-executions/JointGenotyping/3a733624-60a0-4e57-b7f5-7b7e99795738/call-GenotypeGVCFs/shard-25/inputs/data1/bill/pipeline/cromwell/hg38/Homo_sapiens_assembly38.fasta -O output.vcf.gz -D /cromwell-executions/JointGenotyping/3a733624-60a0-4e57-b7f5-7b7e99795738/call-GenotypeGVCFs/shard-25/inputs/data1/bill/pipeline/cromwell/hg38/Homo_sapiens_assembly38.dbsnp138.vcf -G StandardAnnotation --only-output-calls-starting-in-intervals --use-new-qual-calculator -V gendb://genomicsdb -L chrY:10821870-11717714
```
This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/12283/running-260-wes-samples-through-joint-discovery-and-vqsr/p1

**Comment by sooheelee** [comment]
Assigning to @droazen to delegate.

**Comment by sooheelee** [comment]
Tagging @davidbenjamin, because I think he will be interested.

**Comment by droazen** [comment]
@davidbenjamin Can you think of any changes that went in between `4.0.4.0` and `4.0.5.0` that could have caused this? The major changes to newQual between those two releases were in https://github.com/broadinstitute/gatk/pull/4801, I believe.

**Comment by V-Z** [comment]
I see same problem in `4.0.5.2`:

    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /home/vojta/bin/gatk/gatk-package-4.0.5.2-local.jar GenotypeGVCFs -O rad34test.comb2.raw.g.vcf.gz -R ../../../jic_reference/alygenomes.fasta -V rad34test.comb2.raw.vcf.gz --new-qual
    22:45:47.050 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/vojta/bin/gatk/gatk-package-4.0.5.2-local.jar!/com/intel/gkl/native/libgkl_compression.so
    22:45:47.648 INFO  GenotypeGVCFs - ------------------------------------------------------------
    22:45:47.649 INFO  GenotypeGVCFs - The Genome Analysis Toolkit (GATK) v4.0.5.2
    22:45:47.649 INFO  GenotypeGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
    22:45:47.800 INFO  GenotypeGVCFs - Initializing engine
    22:45:48.331 INFO  FeatureManager - Using codec VCFCodec to read file file:///home/vojta/dokumenty/fakulta/botanika/arabidopsis/samples/lib_2018_06/4_joined/rad34test.comb2.raw.vcf.gz
    22:45:48.467 INFO  GenotypeGVCFs - Done initializing engine
    22:45:48.555 INFO  ProgressMeter - Starting traversal
    22:45:48.556 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
    22:45:51.038 WARN  InbreedingCoeff - Annotation will not be calculated, must provide at least 10 samples
    22:45:51.045 INFO  GenotypeGVCFs - Shutting down engine
    [2. července 2018 22:45:51 CEST] org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 0.07 minutes.
    Runtime.totalMemory()=528482304
    java.lang.IllegalArgumentException: log10LikelihoodsOfAC are bad 6.911788849595091E-17,NaN
    at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.AFCalculationResult.<init>(AFCalculationResult.java:72)
    at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.AlleleFrequencyCalculator.getLog10PNonRef(AlleleFrequencyCalculator.java:143)
    at org.broadinstitute.hellbender.tools.walkers.genotyper.GenotypingEngine.calculateGenotypes(GenotypingEngine.java:255)
    at org.broadinstitute.hellbender.tools.walkers.genotyper.GenotypingEngine.calculateGenotypes(GenotypingEngine.java:210)
    at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.calculateGenotypes(GenotypeGVCFs.java:266)
    at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.regenotypeVC(GenotypeGVCFs.java:222)
    at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.apply(GenotypeGVCFs.java:201)
    at org.broadinstitute.hellbender.engine.VariantWalkerBase.lambda$traverse$0(VariantWalkerBase.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at org.broadinstitute.hellbender.engine.VariantWalkerBase.traverse(VariantWalkerBase.java:149)
    at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:984)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:135)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:180)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:199)
    at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
    at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
    at org.broadinstitute.hellbender.Main.main(Main.java:289)

**Comment by davidbenjamin** [comment]
@droazen I think I see how #4801 could introduce a rounding error that creates an extremely small positive log10 probability, which triggers the error.  The old code was 
```
log10PNoVariant += log10GenotypePosteriors[HOM_REF_GENOTYPE_INDEX]
```

and the new code to handle spanning deletion is
```
log10PNoVariant += MathUtils.log10SumLog10(nonVariantLog10Posteriors)
```
where `nonVariantLog10Posteriors` includes but the hom ref posterior *and* the posteriors of ref / span del het genotypes.  So instead of A, where A is the log 10 hom ref posterior, we have log10(10^A + 10^B), where B is the ref/span del het log10 posterior.  This latter quantity should never be positive, but the `log10SumLog10` method it relies on doesn't know that and has finite precision.   Given that the problematic number is truly miniscule, `2.559797571100845E-21`, my money is on that explanation.  I think a reasonable solution is just to replace it by zero, because we know that's where it comes from.  That is, the code should become
```
log10PNoVariant += Math.min(MathUtils.log10SumLog10(nonVariantLog10Posteriors), 0);
```

If there is a way for me to debug without having to learn to use GenomicsDB I would like to confirm this myself.  Otherwise, @sooheelee can I give you a jar to try out on the tutorial data where you spotted the problem earlier?

**Comment by droazen** [comment]
@davidbenjamin The error is not specific to GenomicsDB. @V-Z got the same error with a VCF as input (see https://github.com/broadinstitute/gatk/issues/4544#issuecomment-401904928), so that should make it slightly easier to replicate.

**Comment by droazen** [comment]
Fixed in https://github.com/broadinstitute/gatk/pull/4980
