### ISSUE TITLE
GenotypeGVCFs error log10LikelihoodsOfAC are bad

### ISSUE THREAD

**Issue by cvalenci** [broadinstitute/gatk#5009]
Hi, I am working with WES data with 130 samples. I've been following GATK4 best practices and also using the GRCh38 reference from the GATK bundle. I've been able to pre-process all the samples and to use Haplotypecaller for the 130 samples, then I proceed to merge all into a single gVCF file to then perform a join-call of SNPs and INdels. However, I got the following error message when using "GenotypeGVCF" 
Thank you
Cristian

### Affected tool(s) or class(es)
GenotypeGVCFs

### Affected version(s)
GATK v4.0.5.2
### Description 
12:37:00.202 WARN  GATKAnnotationPluginDescriptor - Redundant enabled annotation group (StandardAnnotation) is enabled for this tool by default
12:37:00.306 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home-1/cvalenc1@jhu.edu/apps/GATK4/gatk-4.0.5.2/gatk-package-4.0.5.2-local.jar!/com/intel/gkl/native/libg
kl_compression.so
12:37:00.524 INFO  GenotypeGVCFs - ------------------------------------------------------------
12:37:00.524 INFO  GenotypeGVCFs - The Genome Analysis Toolkit (GATK) v4.0.5.2
12:37:00.524 INFO  GenotypeGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
12:37:00.529 INFO  GenotypeGVCFs - Executing as cvalenc1@jhu.edu@compute0207 on Linux v2.6.32-696.28.1.el6.x86_64 amd64
12:37:00.530 INFO  GenotypeGVCFs - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_45-b14
12:37:00.530 INFO  GenotypeGVCFs - Start Date/Time: July 12, 2018 12:37:00 PM EDT
12:37:00.530 INFO  GenotypeGVCFs - ------------------------------------------------------------
12:37:00.530 INFO  GenotypeGVCFs - ------------------------------------------------------------
12:37:00.530 INFO  GenotypeGVCFs - HTSJDK Version: 2.16.0
12:37:00.530 INFO  GenotypeGVCFs - Picard Version: 2.18.7
12:37:00.530 INFO  GenotypeGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2
12:37:00.531 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
12:37:00.531 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
12:37:00.531 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
12:37:00.531 INFO  GenotypeGVCFs - Deflater: IntelDeflater
12:37:00.531 INFO  GenotypeGVCFs - Inflater: IntelInflater
12:37:00.531 INFO  GenotypeGVCFs - GCS max retries/reopens: 20
12:37:00.531 INFO  GenotypeGVCFs - Using google-cloud-java patch 6d11bef1c81f885c26b2b56c8616b7a705171e4f from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes
12:37:00.531 INFO  GenotypeGVCFs - Initializing engine
12:37:02.095 INFO  FeatureManager - Using codec VCFCodec to read file file:///home-1/cvalenc1@jhu.edu/work/cvalenc1/Paralysis/NEW_ALIGNEMENT/Sample_VCF/Multi.g.vcf
12:37:03.426 INFO  GenotypeGVCFs - Done initializing engine
12:37:03.683 INFO  ProgressMeter - Starting traversal
12:37:03.683 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
12:37:13.942 INFO  ProgressMeter -         chr1:1034498              0.2                 14000          81887.3
12:37:24.351 INFO  ProgressMeter -         chr1:1322991              0.3                 41000         119030.3
12:37:34.716 INFO  ProgressMeter -         chr1:1926324              0.5                 83000         160474.3
12:37:44.726 INFO  ProgressMeter -         chr1:3786982              0.7                124000         181273.3
12:37:45.921 INFO  GenotypeGVCFs - Shutting down engine
[July 12, 2018 12:37:45 PM EDT] org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 0.76 minutes.
Runtime.totalMemory()=5942280192
java.lang.IllegalArgumentException: log10LikelihoodsOfAC are bad 8.038983630564185E-17,NaN
        at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.AFCalculationResult.<init>(AFCalculationResult.java:72)
        at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.AlleleFrequencyCalculator.getLog10PNonRef(AlleleFrequencyCalculator.java:143)
        at org.broadinstitute.hellbender.tools.walkers.genotyper.GenotypingEngine.calculateGenotypes(GenotypingEngine.java:255)
        at org.broadinstitute.hellbender.tools.walkers.genotyper.GenotypingEngine.calculateGenotypes(GenotypingEngine.java:210)
        at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.calculateGenotypes(GenotypeGVCFs.java:266)
        at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.regenotypeVC(GenotypeGVCFs.java:222)
        at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.apply(GenotypeGVCFs.java:201)
        at org.broadinstitute.hellbender.engine.VariantWalkerBase.lambda$traverse$0(VariantWalkerBase.java:151)
        at org.broadinstitute.hellbender.engine.VariantWalkerBase$$Lambda$96/1188871851.accept(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.broadinstitute.hellbender.engine.VariantWalkerBase.traverse(VariantWalkerBase.java:149)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:984)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:135)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:180)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:199)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
Using GATK jar /home-1/cvalenc1@jhu.edu/apps/GATK4/gatk-4.0.5.2/gatk-package-4.0.5.2-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -DGATK_STACKTRACE_ON_USER_E
XCEPTION=true -jar /home-1/cvalenc1@jhu.edu/apps/GATK4/gatk-4.0.5.2/gatk-package-4.0.5.2-local.jar GenotypeGVCFs -R /home-1/cvalenc1@jhu.edu/work/cvalenc1/hg38_broad/Homo_sapiens_assembly38.f
asta -V /home-1/cvalenc1@jhu.edu/work/cvalenc1/Paralysis/NEW_ALIGNEMENT/Sample_VCF/Multi.g.vcf -G StandardAnnotation -new-qual -O /home-1/cvalenc1@jhu.edu/work/cvalenc1/Paralysis/NEW_ALIGNEME
NT/VCF/Cohort_call.vcf

#### Steps to reproduce
My script:
# load modules for GATK4
module load java/JDK_1.8.0_45
module load python/3.6.5
PICARD=/home-1/cvalenc1@jhu.edu/apps/picard/2/build/libs/picard.jar
# setting reference
REF=~/work/cvalenc1/hg38_broad/Homo_sapiens_assembly38.fasta
VCF=~/work/cvalenc1/Paralysis/NEW_ALIGNEMENT/Sample_VCF/Multi.g.vcf
NEWVCF=~/work/cvalenc1/Paralysis/NEW_ALIGNEMENT/VCF/Cohort_call.vcf

# run GATK 
~/apps/GATK4/gatk-4.0.5.2/gatk --java-options '-DGATK_STACKTRACE_ON_USER_EXCEPTION=true' GenotypeGVCFs -R $REF -V $VCF -G StandardAnnotation -new-qual -O $NEWVCF

# done

#### Expected behavior
_Tell us what should happen_

#### Actual behavior
_Tell us what happens instead_

----

### Tool(s) or class(es) involved
_Tool/class name(s), special parameters?_

### Description
_Specify whether you want a modification of an existing behavior or addition of a new capability._
_Provide **examples**, **screenshots**, where appropriate._

----

### Tool(s) or class(es) involved
_Tool/class name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

**Comment by ldgauthier** [comment]
Sorry for the bug @cvalenci.  That looks like something we've seen before and recently fixed (#4980). Can you try 4.0.6.0: https://github.com/broadinstitute/gatk/releases/tag/4.0.6.0 ?

**Comment by cvalenci** [comment]
HI, thank you for the quick response. Sure, I will try the new version. Does it mean that I need to re-run everything from Haplotypecaller again in all the samples or can I take my "Multi.g.VCF" generated with  GATK 4.0.5.2 and do the Joint-Call with GATK 4.0.6.0?

**Comment by ldgauthier** [comment]
Nothing in the GVCF output should change with this bug fix, so just running GenotypeGVCFs with 4.0.6.0 will be fine.  (David has more details in #5000)

**Comment by ldgauthier** [comment]
I'm confident this should solve your issue, but please reopen if that's not the case.
