### ISSUE TITLE
Tabix fails in UpdateVCFSequenceDictionary when outputting .vcf.gz file

### ISSUE THREAD

**Issue by kachulis** [broadinstitute/gatk#5087]
### Affected tool(s) or class(es)
UpdateVCFSequenceDictionary

### Affected version(s)
- \[x] Latest master branch as of 8/3/18

### Description 
I am running UpdateVCFSequenceDictionary on a vcf which should have a hg38 header but which (for unrelated unpleasant reasons) instead has a hg19 header. Using an hg38 dictionary as source dict to try to fix the header.   If I ask to output a .vcf file, everything works fine.  If I ask to output a .vcf.gz file, gatk crashes with
```
java.lang.ArrayIndexOutOfBoundsException: 12922
	at htsjdk.samtools.BinningIndexBuilder.processFeature(BinningIndexBuilder.java:89)
	at htsjdk.tribble.index.tabix.TabixIndexCreator.finalizeFeature(TabixIndexCreator.java:106)
	at htsjdk.tribble.index.tabix.TabixIndexCreator.finalizeIndex(TabixIndexCreator.java:129)
	at htsjdk.variant.variantcontext.writer.IndexingVariantContextWriter.close(IndexingVariantContextWriter.java:146)
	at htsjdk.variant.variantcontext.writer.VCFWriter.close(VCFWriter.java:212)
	at org.broadinstitute.hellbender.tools.walkers.variantutils.UpdateVCFSequenceDictionary.closeTool(UpdateVCFSequenceDictionary.java:174)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:983)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:137)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:182)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:201)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
```  

#### Steps to reproduce
Works: ``gatk UpdateVCFSequenceDictionary -V /dsde/working/ckachulis/UpdateVCFSequenceDictionary_Bug/na12878_hg38_giab_pg_hybrid_happy.vcf.gz -O corrected.dictionary.vcf --source-dictionary /seq/references/Homo_sapiens_assembly38/v0/Homo_sapiens_assembly38.dict --replace ``

Crashes: ``gatk UpdateVCFSequenceDictionary -V /dsde/working/ckachulis/UpdateVCFSequenceDictionary_Bug/na12878_hg38_giab_pg_hybrid_happy.vcf.gz -O corrected.dictionary.vcf.gz --source-dictionary /seq/references/Homo_sapiens_assembly38/v0/Homo_sapiens_assembly38.dict --replace `` 

This is caused by the Tabix tools in htsjdk being given the dictionary from the input vcf to use for indexing instead of the source-dictionary.  Can be fixed by overriding ``getBestAvailableSequenceDictionary()`` in UpdateVCFSequenceDictionary to return ``sourceDictionary``.  However, this requires making ``VariantWalkerBase::getBestAvailableSequenceDictionary()`` non-final, so perhaps there is a better option.

**Comment by cmnbroad** [comment]
@kachulis Thanks for the report. The fix will be slightly complicated by the fact that there is also a (GATK-tool) level arg called `masterSequenceDictionary`. So in the override, we'll want to validate/resolve that argument against the others as well.

If you need a short term workaround, you can try disabling on-they-fly indexing (`--create-output-variant-index false`, and then index the output separately using `IndexFeatureFile`.

**Comment by kachulis** [comment]
Thanks @cmnbroad for the workaround
