### ISSUE TITLE
String index out of range in ReferenceBases.annotate when calling variants at ends of chromosomes using MuTect2

### ISSUE THREAD

**Issue by chapmanb** [broadinstitute/gatk#5130]
### Affected tool(s) or class(es)

MuTect2 for the test case, but any caller using the Reference Bases annotation and calling bases near the end of chromosomes.

### Affected version(s)

This occurs with the latest release (4.0.8.1) and not with the previous (4.0.7.0). It appears to be related to the addition of the Orientation Bias filter (#4895) and assessing sequence context:

https://github.com/broadinstitute/gatk/pull/4895/files#diff-07e3c8c33f865c5b32b362afe50cfd86R48

### Description 

When identifying variants near the end of chromosome boundaries, MuTect2 fails with:
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 369
        at java.lang.String.substring(String.java:1963)
        at org.broadinstitute.hellbender.tools.walkers.annotator.ReferenceBases.annotate(ReferenceBases.java:48)
        at org.broadinstitute.hellbender.tools.walkers.annotator.VariantAnnotatorEngine.annotateContext(VariantAnnotatorEngine.java:270)
        at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.callMutations(SomaticGenotypingEngine.java:176)
        at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2Engine.callRegion(Mutect2Engine.java:211)
        at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2.apply(Mutect2.java:212)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:291)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:267)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:979)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:137)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:182)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:201)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

#### Steps to reproduce

This is a self contained test case with a shell script that demonstrates the issue:

https://s3.amazonaws.com/chapmanb/testcases/gatk/gatk4_mutect2_indexerror.tar.gz

You can adjust the BED file (`TumorOnly-chr22_14000_20001-regions.bed`) to make it not fail. The current failing version is:
```
chr22   14000   19995
```
and reducing one base at the end will pass cleanly:
```
chr22   14000   19994
```

Thanks for looking at this and please let me know if I can provide any other information.

**Comment by droazen** [comment]
@davidbenjamin A Mutect bug/possible regression for you to look at when you return

**Comment by sbamin** [comment]
I am getting the similar error (gatk 4.0.8.1), and in my case, it does not help even if I trim end by 1-base. Does trimming one base also apply to length of an entire chromosome if I am supplying `-L 1:1-100000`?

```
[August 28, 2018 6:10:37 PM EDT] org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2 done. Elapsed time: 0.45 minutes.
Runtime.totalMemory()=2649751552
java.lang.StringIndexOutOfBoundsException: String index out of range: 177
        at java.lang.String.substring(String.java:1963)
        at org.broadinstitute.hellbender.tools.walkers.annotator.ReferenceBases.annotate(ReferenceBases.java:48)
        at org.broadinstitute.hellbender.tools.walkers.annotator.VariantAnnotatorEngine.annotateContext(VariantAnnotatorEngine.java:270)
        at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.callMutations(SomaticGenotypingEngine.java:176)
        at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2Engine.callRegion(Mutect2Engine.java:211)
        at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2.apply(Mutect2.java:212)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:291)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:267)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:979)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:137)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:182)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:201)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

**Comment by chapmanb** [comment]
Samir;
I'm not entirely sure about the fix, but based on where I think it's coming from you'll want to work around the problem by avoiding at least 10bp towards the start/end of a chromosome. That's the amount of sequence context it's filling around the variant. Hope this helps for your problem case.

**Comment by droazen** [comment]
@takutosato Could you please have a look at this one when you get a chance? It might be related to your recently-merged PR https://github.com/broadinstitute/gatk/pull/4895

**Comment by takutosato** [comment]
I'm on it

**Comment by sbamin** [comment]
Hi Brad,

 Thanks for a temporary fix. It works with GATK v 4.0.8.1, though I skipped trimming start coordinates, and only trimmed end by 10bp.

**Comment by takutosato** [comment]
@chapmanb, @sbamin, thank you for reporting the error.

I fixed the bug by padding the reference bases with N's when we reach the end of the chromosome, with the variant base in the middle 

But in retrospect, I'm pretty sure @davidbenjamin would rather slide the center and get real bases (i.e. variant need not be in the center). So I'll write that version tomorrow.

PR is #5151

**Comment by chapmanb** [comment]
Takuto -- thanks so much for working on this, I appreciate the quick fix.

**Comment by sbamin** [comment]
Thanks @takutosato for quick fix and love the openness of the code. Now, I understand what's happening inside gatk commands. Much appreciated.

**Comment by droazen** [comment]
Fixed in https://github.com/broadinstitute/gatk/pull/5151
