### ISSUE TITLE
Better error message when GCS credentials are required

### ISSUE THREAD

**Issue by jmthibault79** [broadinstitute/gatk#5468]
### Tool(s) or class(es) involved
Reading files from non-public GCS paths

### Description
I did not have Application Default Credentials set up when I tried to read from a private bucket.  This failed, as expected.  Could we add a comment explaining that running `gcloud auth application-default login` is the necessary step to making this work?  I didn't see anything on the forum about how to solve this.  The solution was in the comments to #2394.

### Observed
GATK errored out with a stack trace:
```
code:      401
message:   Anonymous caller does not have storage.objects.get access to joel-cram/SAM24339124.cram.
reason:    required
location:  Authorization
retryable: false
com.google.cloud.storage.StorageException: Anonymous caller does not have storage.objects.get access to joel-cram/SAM24339124.cram.
        at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:220)
        at com.google.cloud.storage.spi.v1.HttpStorageRpc.get(HttpStorageRpc.java:415)
        at com.google.cloud.storage.StorageImpl$5.call(StorageImpl.java:198)
        at com.google.cloud.storage.StorageImpl$5.call(StorageImpl.java:195)
        at shaded.cloud_nio.com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89)
        at com.google.cloud.RetryHelper.run(RetryHelper.java:74)
        at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
        at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:195)
        at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.checkAccess(CloudStorageFileSystemProvider.java:673)
        at java.nio.file.Files.exists(Files.java:2385)
        at htsjdk.samtools.util.IOUtil.assertFileIsReadable(IOUtil.java:429)
        at org.broadinstitute.hellbender.engine.ReadsDataSource.<init>(ReadsDataSource.java:206)
```

```
Caused by: shaded.cloud_nio.com.google.api.client.googleapis.json.GoogleJsonResponseException: 401 Unauthorized
{
  "code" : 401,
  "errors" : [ {
    "domain" : "global",
    "location" : "Authorization",
    "locationType" : "header",
    "message" : "Anonymous caller does not have storage.objects.get access to joel-cram/SAM24339124.cram.",
    "reason" : "required"
  } ],
  "message" : "Anonymous caller does not have storage.objects.get access to joel-cram/SAM24339124.cram."
}
```

### Desired
Something like "Unable to read gs://joel-cram/SAM24339124.cram due to permissions.  Have you enabled Google Cloud Application Default Credentials by running 'gcloud auth application-default login'?  See [this forum post] for details."

**Comment by jean-philippe-martin** [comment]
I agree this would make GATK easier to use. In fairness, these steps *are* described [in the documentation](https://github.com/broadinstitute/gatk/blob/master/README.md#gcs).

**Comment by jmthibault79** [comment]
Good point, thanks.  Not sure why I didn't look there.
