### ISSUE TITLE
Investigate NIO retry failures observed in CNV walkers.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#5631]
The problem may not be specific to these CNV walkers.  A ModelSegments FC evaluation of a branch of 4.0.12.0 yielded several instances of the following exception in the CollectReadCounts and CollectAllelicCounts tools (multiple samples failing on one or more out of 3 total runs of these tools) when using NIO:

> java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.cloud.storage.StorageException: All 20 reopens failed. Waited a total of 1918000 ms between attempts
    at org.broadinstitute.hellbender.utils.nio.SeekableByteChannelPrefetcher.read(SeekableByteChannelPrefetcher.java:318)
    at htsjdk.samtools.seekablestream.SeekablePathStream.read(SeekablePathStream.java:86)
    at htsjdk.samtools.util.BlockCompressedInputStream.readBytes(BlockCompressedInputStream.java:571)
    at htsjdk.samtools.util.BlockCompressedInputStream.readBytes(BlockCompressedInputStream.java:560)
    at htsjdk.samtools.util.BlockCompressedInputStream.processNextBlock(BlockCompressedInputStream.java:525)
    at htsjdk.samtools.util.BlockCompressedInputStream.nextBlock(BlockCompressedInputStream.java:468)
    at htsjdk.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:458)
    at htsjdk.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:196)
    at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:331)
    at java.io.DataInputStream.read(DataInputStream.java:149)
    at htsjdk.samtools.util.BinaryCodec.readBytesOrFewer(BinaryCodec.java:421)
    at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:394)
    at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:380)
    at htsjdk.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:268)
    at htsjdk.samtools.BAMFileReader$BAMFileIterator.getNextRecord(BAMFileReader.java:829)
    at htsjdk.samtools.BAMFileReader$BAMFileIndexIterator.getNextRecord(BAMFileReader.java:981)
    at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:803)
    at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:797)
    at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:765)
    at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.advance(BAMFileReader.java:1034)
    at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.next(BAMFileReader.java:1024)
    at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.next(BAMFileReader.java:988)
    at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:569)
    at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:548)
    at org.broadinstitute.hellbender.utils.iterators.SamReaderQueryingIterator.loadNextRecord(SamReaderQueryingIterator.java:114)
    at org.broadinstitute.hellbender.utils.iterators.SamReaderQueryingIterator.next(SamReaderQueryingIterator.java:151)
    at org.broadinstitute.hellbender.utils.iterators.SamReaderQueryingIterator.next(SamReaderQueryingIterator.java:29)
    at org.broadinstitute.hellbender.utils.iterators.SAMRecordToReadIterator.next(SAMRecordToReadIterator.java:27)
    at org.broadinstitute.hellbender.utils.iterators.SAMRecordToReadIterator.next(SAMRecordToReadIterator.java:13)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at org.broadinstitute.hellbender.engine.ReadWalker.traverse(ReadWalker.java:89)
    at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:966)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:138)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
    at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
    at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
    at org.broadinstitute.hellbender.Main.main(Main.java:291)
Caused by: java.util.concurrent.ExecutionException: com.google.cloud.storage.StorageException: All 20 reopens failed. Waited a total of 1918000 ms between attempts
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at org.broadinstitute.hellbender.utils.nio.SeekableByteChannelPrefetcher$WorkUnit.getBuf(SeekableByteChannelPrefetcher.java:140)
    at org.broadinstitute.hellbender.utils.nio.SeekableByteChannelPrefetcher.fetch(SeekableByteChannelPrefetcher.java:264)
    at org.broadinstitute.hellbender.utils.nio.SeekableByteChannelPrefetcher.read(SeekableByteChannelPrefetcher.java:309)
    ... 44 more
Caused by: com.google.cloud.storage.StorageException: All 20 reopens failed. Waited a total of 1918000 ms between attempts
    at com.google.cloud.storage.contrib.nio.CloudStorageRetryHandler.handleReopenForStorageException(CloudStorageRetryHandler.java:123)
    at com.google.cloud.storage.contrib.nio.CloudStorageRetryHandler.handleStorageException(CloudStorageRetryHandler.java:93)
    at com.google.cloud.storage.contrib.nio.CloudStorageReadChannel.handleStorageException(CloudStorageReadChannel.java:242)
    at com.google.cloud.storage.contrib.nio.CloudStorageReadChannel.read(CloudStorageReadChannel.java:145)
    at org.broadinstitute.hellbender.utils.nio.SeekableByteChannelPrefetcher$WorkUnit.call(SeekableByteChannelPrefetcher.java:135)
    at org.broadinstitute.hellbender.utils.nio.SeekableByteChannelPrefetcher$WorkUnit.call(SeekableByteChannelPrefetcher.java:108)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.cloud.storage.StorageException: Connection closed prematurely: bytesRead = 16777216, Content-Length = 41943040
    at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:220)
    at com.google.cloud.storage.spi.v1.HttpStorageRpc.read(HttpStorageRpc.java:644)
    at com.google.cloud.storage.BlobReadChannel$1.call(BlobReadChannel.java:127)
    at com.google.cloud.storage.BlobReadChannel$1.call(BlobReadChannel.java:124)
    at shaded.cloud_nio.com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89)
    at com.google.cloud.RetryHelper.run(RetryHelper.java:74)
    at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
    at com.google.cloud.storage.BlobReadChannel.read(BlobReadChannel.java:124)
    at com.google.cloud.storage.contrib.nio.CloudStorageReadChannel.read(CloudStorageReadChannel.java:141)
    ... 6 more
Caused by: java.io.IOException: Connection closed prematurely: bytesRead = 16777216, Content-Length = 41943040
    at shaded.cloud_nio.com.google.api.client.http.javanet.NetHttpResponse$SizeValidatingInputStream.throwIfFalseEOF(NetHttpResponse.java:202)
    at shaded.cloud_nio.com.google.api.client.http.javanet.NetHttpResponse$SizeValidatingInputStream.read(NetHttpResponse.java:171)
    at java.io.FilterInputStream.read(FilterInputStream.java:107)
    at shaded.cloud_nio.com.google.api.client.util.ByteStreams.copy(ByteStreams.java:51)
    at shaded.cloud_nio.com.google.api.client.util.IOUtils.copy(IOUtils.java:94)
    at shaded.cloud_nio.com.google.api.client.util.IOUtils.copy(IOUtils.java:63)
    at shaded.cloud_nio.com.google.api.client.http.HttpResponse.download(HttpResponse.java:421)
    at com.google.cloud.storage.spi.v1.HttpStorageRpc.read(HttpStorageRpc.java:638)
    ... 13 more

Subsequent reruns on 4.0.4.0 yielded only 1 failure out of 3 walkers x 59 samples; no failures were observed on 4.0.9.0 or 4.0.11.0.  So the problem is not unique to 4.0.12.0, but the rate of failure is much higher.

Additional reruns on 4.0.12.0 suggest that the original failures were not intermittent; one run showed 6/59 samples failing, with many of those having more than one of the 3 walkers fail.

Additional reruns with a branch of 4.0.12.0 that reverted to the htsjdk version used in 4.0.11.0 still showed a high rate of failure.  There were at least a couple of instances where the same BAM appeared to fail in roughly the same spot as in the 4.0.12.0 runs, and other instances where the same BAM failed in roughly the same spot, only in two different walkers.  However, the set of BAMs that failed was not consistent across all runs.

Leaving to @droazen to delegate.  The FC CNV featured WDL doesn't use NIO yet, but I'm surprised this hasn't cropped up in other WDLs.

**Comment by droazen** [comment]
@samuelklee Thanks for filing this. Now that 4.1 is out, we should be able to continue looking into this.

It's a long shot, but have you tried a run with 4.1.0.0 instead of 4.0.12.0?

**Comment by droazen** [comment]
@jean-philippe-martin, when you have a chance could you please take a look at the stack trace above and give your thoughts? Our NIO library dependency was not upgraded between 4.0.11.0 and 4.0.12.0 (it was last upgraded in 4.0.9.0), so it's not clear what it is about 4.0.12.0 that is leading to this higher failure rate. 

We've already tried a custom build of 4.0.12.0 that included the version of htsjdk from 4.0.11.0, but that didn't help.

**Comment by samuelklee** [comment]
Sure, kicked off a run with 4.1.0.0.  Thanks for looking into this!

**Comment by jean-philippe-martin** [comment]
If only some of the accesses failed, then it's likely what we're seeing here is GCS refusing to serve requests because it feels it's getting too many. How many machines are trying to access the file? How many threads per machine? What storage class is the bucket?

The lower storage classes support fewer parallel accesses, and NIO's prefetching (if enabled) results in two threads per reader.

**Comment by samuelklee** [comment]
The possibility that this problem could be specific to the TCGA FC BAMs did arise in our previous discussions---not sure what storage class those are on?

However, in this workflow, at most one ReadWalker (CollectReadCounts) and one LocusWalker (CollectAllelicCounts) would try to access the same (tumor) BAM.  There were several instances of (normal) BAMs which only had one LocusWalker (CollectAllelicCounts) accessing them that failed.

**Comment by samuelklee** [comment]
Rate of failure still seems high in 4.1.

**Comment by droazen** [comment]
@samuelklee Is this still happening?

**Comment by samuelklee** [comment]
Last I checked (perhaps a week or so after my last comment) it was still happening.  I've been running a lot of NIO with 4.0.4.0 in the past few days with no issue, though.

**Comment by droazen** [comment]
@samuelklee When you get a chance, could you repeat your test with latest gatk/master? We recently (ie., within the past 2 weeks) upgraded to a newer gcloud release, and I'm curious to test whether that had an effect.

**Comment by samuelklee** [comment]
I collected coverage over 200 WGS BAMs on FC and didn't get a single failure, so hopefully this has indeed been fixed!  Thanks @droazen, will close for now.

**Comment by droazen** [comment]
@samuelklee That's really good news! Do you think it was the gcloud upgrade that did the trick, then?

**Comment by samuelklee** [comment]
Not sure if I can say that for certain, but sounds reasonable.  In any case, I'll keep an eye out to make sure it doesn't crop back up!

**Comment by abhisheknrl** [comment]
I come across this issue with v4.1.2.0. Until Aug 25, 2019, I had no problem analyzing TCGA WGS bams. I suddenly had a problem after 2 days. My jobs are failing even after allocating 400 GB extra disc space (on top of what I used before).
Is this problem completely fixed? Has anyone seen this recently?

Thanks!
Abhishek

**Comment by jean-philippe-martin** [comment]
Multiple causes can cause closed connections when reading from GCS, almost all of which are outside of our control. This will never be "completely fixed" in the sense that even if the code is perfect it's completely possible to send too many requests to GCS, and it'll respond by closing connections.

The main factors that I know of are:

- number of concurrent accesses to the GCS bucket in question
- number of concurrent accesses to the GCP project in question
- storage class of the GCS bucket in question (the more expensive ones have more replicas, thus can handle a higher load)

If you're running into those difficulties I would suggest trying to reduce the load (reduce the number of concurrent workers or threads) and making sure it's not a single-region storage bucket. If that fails, perhaps try using a different bucket that no one else is also using (to reduce other sources of load).

If I understand correctly that you didn't change the version you're using but are suddenly seeing more issues than before, then perhaps the cause is a server-side change from GCS (outside of our control), a change in configuration (are you reading from a bucket of a different class from before), or perhaps just an increase of other activity on the same bucket/project.

The current code is very persistent in its retries: as you can see from the messages it spent a whole half hour waiting. If it's an overload situation then you may get better performance by reducing the worker count (as they will have to retry less).

**Comment by abhisheknrl** [comment]
Thanks, JP!
Yes, you understood right. I did not change anything. It was only different days. The probability that the same bucket could have been accessed by multiple jobs/projects totally makes sense. I will try lowering the number of scattered tasks and see if it works.
