### ISSUE TITLE
Funcotator reproducibly crashes on specific WES VCF record produced by GATK4.1.0 (java 1.8.0_45)

### ISSUE THREAD

**Issue by bhanugandham** [broadinstitute/gatk#5783]
Please find below the user report of this issue:

Here is the error I got:
    [February 25, 2019 8:18:10 PM PST] org.broadinstitute.hellbender.tools.funcotator.Funcotator done. Elapsed time: 11.08 minutes.
    Runtime.totalMemory()=5379719168
    java.lang.StringIndexOutOfBoundsException: String index out of range: 545
       at java.lang.String.substring(String.java:1951)
       at org.broadinstitute.hellbender.tools.funcotator.ProteinChangeInfo.initializeForDeletion(ProteinChangeInfo.java:192)
       at org.broadinstitute.hellbender.tools.funcotator.ProteinChangeInfo.<init>(ProteinChangeInfo.java:96)
       at org.broadinstitute.hellbender.tools.funcotator.ProteinChangeInfo.create(ProteinChangeInfo.java:371)
[...]

and here is offending record:
`chr12 70747693 .  TAAAAAAA T,TAAAA,TAAAAA,TAAAAAA,TAAAAAAAA .  artifact_in_normal;germline_risk;multiallelic   CONTQ=93;DP=537;ECNT=1;GERMQ=253,113,0,0,18;MBQ=36,24,36,28,36,33;MFRL=293,529,291,288,325,299;MMQ=60,29,60,60,60,60;MPOS=43,43,41,44,26;NALOD=0.912,0.217,-2.040e+00,-1.342e+01,-4.057e+00;NLOD=20.49,13.33,2.58,-1.476e+01,2.13;POPAF=2.27,1.08,2.19,2.53,5.40;REF_BASES=GCAAGCCTTCTAAAAAAAAAA;RPA=25,18,22,23,24,26;RU=A;SAAF=0.394,0.404,0.420;SAPP=0.019,0.015,0.965;STR;TLOD=3.88,7.29,6.62,36.73,3.85   GT:AD:AF:DP:F1R2:F2R1   0/0:21,0,1,7,14,6:0.011,0.025,0.099,0.262,0.124:49:14,0,1,6,7,4:7,0,0,1,7,2   0/1/2/3/4/5:65,3,11,20,47,18:0.016,0.057,0.076,0.245,0.092:164:32,3,6,14,30,8:33,0,5,6,17,10`

As a result the Funcotator output is truncated. Bug?

Thanks!
Ivan

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/23631/funcotator-reproducibly-crushes-on-specific-wes-vcf-record-produced-by-gatk4-1-0-java-1-8-0-45/p1

**Comment by droazen** [comment]
Re-assigning to @haileypfox
