### ISSUE TITLE
Java related error encountered while running gatk PathSeqPipelineSpark

### ISSUE THREAD

**Issue by bhanugandham** [broadinstitute/gatk#5802]
Hi,

I am trying to test the pathseq tutorial following the tutorial on [this]( https://gatkforums.broadinstitute.org/gatk/discussion/10913/how-to-run-the-pathseq-pipeline "this") link

I ran the following commands

    bioinfo@bioinfo$ conda activate gatk
    (gatk) bioinfo@bioinfo$ gatk PathSeqPipelineSpark \
    >     --input test_sample.bam \
    >     --filter-bwa-image hg19mini.fasta.img \
    >     --kmer-file hg19mini.hss \
    >     --min-clipped-read-length 70 \
    >     --microbe-fasta e_coli_k12.fasta \
    >     --microbe-bwa-image e_coli_k12.fasta.img \
    >     --taxonomy-file e_coli_k12.db \
    >     --output output.pathseq.bam \
    >     --scores-output output.pathseq.txt

And encountered below error:

    Using GATK jar /home/bioinfo/Installers/gatk4/gatk-4.1.0.0/gatk-package-4.1.0.0-local.jar
    Running:
        java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /home/bioinfo/Installers/gatk4/gatk-4.1.0.0/gatk-package-4.1.0.0-local.jar PathSeqPipelineSpark --input test_sample.bam --filter-bwa-image hg19mini.fasta.img --kmer-file hg19mini.hss --min-clipped-read-length 70 --microbe-fasta e_coli_k12.fasta --microbe-bwa-image e_coli_k12.fasta.img --taxonomy-file e_coli_k12.db --output output.pathseq.bam --scores-output output.pathseq.txt
    18:57:39.629 WARN  SparkContextFactory - Environment variables HELLBENDER_TEST_PROJECT and HELLBENDER_JSON_SERVICE_ACCOUNT_KEY must be set or the GCS hadoop connector will not be configured properly
    18:57:39.729 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/bioinfo/Installers/gatk4/gatk-4.1.0.0/gatk-package-4.1.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
    18:57:41.594 INFO  PathSeqPipelineSpark - ------------------------------------------------------------
    18:57:41.594 INFO  PathSeqPipelineSpark - The Genome Analysis Toolkit (GATK) v4.1.0.0
    18:57:41.594 INFO  PathSeqPipelineSpark - For support and documentation go to https://software.broadinstitute.org/gatk/
    18:57:41.739 INFO  PathSeqPipelineSpark - Initializing engine
    18:57:41.739 INFO  PathSeqPipelineSpark - Done initializing engine
    Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
    19/03/05 18:57:41 INFO SparkContext: Running Spark version 2.2.0
    18:57:41.968 WARN  NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
    18:57:42.155 INFO  PathSeqPipelineSpark - Shutting down engine
    [5 March, 2019 6:57:42 PM IST] org.broadinstitute.hellbender.tools.spark.pathseq.PathSeqPipelineSpark done. Elapsed time: 0.04 minutes.
    Runtime.totalMemory()=645922816
    Exception in thread "main" java.lang.ExceptionInInitializerError
    	at org.apache.spark.SparkConf.validateSettings(SparkConf.scala:546)
    	at org.apache.spark.SparkContext.<init>(SparkContext.scala:373)
    	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
    	at org.broadinstitute.hellbender.engine.spark.SparkContextFactory.createSparkContext(SparkContextFactory.java:178)
    	at org.broadinstitute.hellbender.engine.spark.SparkContextFactory.getSparkContext(SparkContextFactory.java:110)
    	at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:28)
    	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:138)
    	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
    	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
    	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
    	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
    	at org.broadinstitute.hellbender.Main.main(Main.java:291)
    Caused by: java.net.UnknownHostException: bioinfo: bioinfo: unknown error
    	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
    	at org.apache.spark.util.Utils$.findLocalInetAddress(Utils.scala:891)
    	at org.apache.spark.util.Utils$.org$apache$spark$util$Utils$$localIpAddress$lzycompute(Utils.scala:884)
    	at org.apache.spark.util.Utils$.org$apache$spark$util$Utils$$localIpAddress(Utils.scala:884)
    	at org.apache.spark.util.Utils$$anonfun$localHostName$1.apply(Utils.scala:941)
    	at org.apache.spark.util.Utils$$anonfun$localHostName$1.apply(Utils.scala:941)
    	at scala.Option.getOrElse(Option.scala:121)
    	at org.apache.spark.util.Utils$.localHostName(Utils.scala:941)
    	at org.apache.spark.internal.config.package$.<init>(package.scala:204)
    	at org.apache.spark.internal.config.package$.<clinit>(package.scala)
    	... 12 more
    Caused by: java.net.UnknownHostException: bioinfo: unknown error
    	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
    	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
    	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
    	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
    	... 21 more
    

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/23594/java-related-error-encountered-while-running-gatk-pathseqpipelinespark/p1

**Comment by bhanugandham** [comment]
Hi @jamesemery 

I checked with chris about this issue and he mentioned I should ask you, as you are the sparks expert. Chris mentioned "there is an issue with Spark resolving the spark master back to the local host". Is this a possible bug or whats the solution for this?

**Comment by droazen** [comment]
I'd actually tag @mwalker174 on this one @bhanugandham

**Comment by mwalker174** [comment]
Hi @bhanugandham 

I wasn't able to reproduce your problem on my laptop. Based on the error message, it looks like a network config Spark issue. What environment are you running this in? If it's MacOS, can you post the contents of `/etc/hosts`? Also the error message looks like it's truncated. You might be able to get the full stack trace by adding `--verbosity DEBUG`, which would be helpful as well.

**Comment by bhanugandham** [comment]
Hi @mwalker174 

Thank you for looking into this so quickly. This is a question from the GATK forum. I have asked the user for the information you requested. I will get back to you with more details.
