### ISSUE TITLE
GATK does not work on Windows any longer

### ISSUE THREAD

**Issue by teepean** [broadinstitute/gatk#5805]
GATK doesn't seem to be working on Windows any longer, at least HaploTypeCaller crashes with the following. Tested with GATK 4.0.9.0, 4.0.11.0 and 4.1.0.0.

```
java.exe -jar gatk-package-4.1.0.0-local.jar HaplotypeCaller -R refa.fa -I refa.bam -O bam_chramma.vcf
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/Teemu/AppData/Local/Temp/
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.nio.file.Paths.get(Unknown Source)
        at org.broadinstitute.hellbender.utils.io.IOUtils.getPath(IOUtils.java:759)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:161)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)

```

The last version I have tested where this still works  is 4.0.8.1. It is caused most likely because of the forward slash before C:.

There are several examples of the error that can be googled. Here's one:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=518079

**Comment by teepean** [comment]
According to git bisect this is the commit that is the culprit.

```
9125ff664902b5ac22d0c195b6350d2a0e11baec is the first bad commit
commit 9125ff664902b5ac22d0c195b6350d2a0e11baec
Author: Daniel Gómez-Sánchez <magicDGS@users.noreply.github.com>
Date:   Fri Aug 24 21:22:41 2018 +0200

    NIO support for TMP_DIR (#4469)

    * NIO support for TMP_DIR

:040000 040000 1e2e5ba73c9ed278665dfdee2c21a08a768b7fcd 5c74c0f3b11bc6e7a5cba909648659b18f9fd957 M      src
```

**Comment by cmnbroad** [comment]
@teepean We generally don't test on Windows, though we do try to keep things working there if possible. Is there any chance you could try running [this branch] in the same environment that previously failed, and see if it solves the problem ? Thx ?

**Comment by teepean** [comment]
> 
> 
> @teepean We generally don't test on Windows, though we do try to keep things working there if possible. Is there any chance you could try running [this branch](https://github.com/broadinstitute/gatk/tree/cn_temp_dr_windows) in the same environment that previously failed, and see if it solves the problem ? Thx ?

This fixed the problem and everything else seems to be working correctly. Thank you!

**Comment by cmnbroad** [comment]
@teepean Ok, great - thx for testing that out.

**Comment by cmnbroad** [comment]
@teepean Thanks for following up, but lets leave this issue open until the fix gets merged into master.
