### ISSUE TITLE
Local WDL tests don't work with NIO (tasks with files declared as String)

### ISSUE THREAD

**Issue by meganshand** [broadinstitute/gatk#5855]
### Tool(s) or class(es) involved
All WDL tests (Mutect2, CNV, Mitochondria pipeline, etc)

### Description
I'd like to be able to include tasks in GATK WDLs that use NIO (tasks with `String input_file` rather than `File input_file`). When I tried this with local git lfs files I got an error saying that the file could not be found (even though the file was being downloaded correctly). I then tried putting the file in `gs://hellbender/test/resources/large`, but when the tool tried to run on travis I got a permission error (see below). It would be great if the WDL tests all ran in the cloud since that's the main way we expect to run these WDLs. It would also be great it the local tests could account for NIO tasks (especially as we want to make more tasks use NIO in the future).

```
com.google.cloud.storage.StorageException: Error code 404 trying to get security access token from Compute Engine metadata for the default service account. This may be because the virtual machine instance does not have permission scopes specified. It is possible to skip checking for Compute Engine metadata by specifying the environment  variable NO_GCE_CHECK=true.
    at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:227)
    at com.google.cloud.storage.spi.v1.HttpStorageRpc.get(HttpStorageRpc.java:438)
    at com.google.cloud.storage.StorageImpl$5.call(StorageImpl.java:239)
    at com.google.cloud.storage.StorageImpl$5.call(StorageImpl.java:236)
    at shaded.cloud_nio.com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
    at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
    at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
    at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:235)
    at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.checkAccess(CloudStorageFileSystemProvider.java:687)
    at java.nio.file.Files.exists(Files.java:2385)
    at htsjdk.samtools.util.IOUtil.assertFileIsReadable(IOUtil.java:404)
    at org.broadinstitute.hellbender.engine.ReadsDataSource.<init>(ReadsDataSource.java:206)
    at org.broadinstitute.hellbender.engine.ReadsDataSource.<init>(ReadsDataSource.java:162)
    at org.broadinstitute.hellbender.engine.GATKTool.initializeReads(GATKTool.java:391)
    at org.broadinstitute.hellbender.engine.GATKTool.onStartup(GATKTool.java:640)
    at org.broadinstitute.hellbender.engine.ReadWalker.onStartup(ReadWalker.java:50)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:136)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
    at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
    at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
    at org.broadinstitute.hellbender.Main.main(Main.java:291)
```

**Comment by meganshand** [comment]
This is fixed by using the "localization_optional" option in WDL.
