### ISSUE TITLE
Audit tools with tests with suspicious FeatureCache misses

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#5895]
Results from a Travis run using a branch that throws whenever a FeatureCache miss occurs, and the query interval is on the same contig as was current cached interval, but with a start before the current cached interval start. This indicates that features that have already been ejected from the cache are being re-queried, and the corresponding tool might benefit from a smarter ejection strategy. Some of these could be artifacts of the tests. Failures (see https://travis-ci.com/broadinstitute/gatk/builds/108966841):

FuncotatorIntegrationTest.exhaustiveArgumentTest
FuncotatorIntegrationTest.testFuncotatorWithoutValidatingResults
FuncotatorIntegrationTest.testVcfDatasourceAccountsForAltAlleles
FuncotatorIntegrationTest.testVcfMafConcordance
XGBoostEvidenceFilterUnitTest.testFilter
HaplotypeCallerIntegrationTest.testGenotypeGivenAllelesMode
Mutect2IntegrationTest.testContaminationFilter
Mutect2IntegrationTest.testDreamTumorNormal
Mutect2IntegrationTest.testGivenAllelesMode
Mutect2IntegrationTest.testGivenAllelesZeroCoverage
Mutect2IntegrationTest.testMissingAF
Mutect2IntegrationTest.testPon
Mutect2IntegrationTest.testTumorOnly

Also, these probably don't count, but:
FeatureDataSourceUnitTest.testCacheHitDetection
FeatureDataSourceUnitTest.testSingleDataSourceMultipleQueries

The HC stack was:

`org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerIntegrationTest.testGenotypeGivenAllelesMode [31mFAILED[39m
    org.broadinstitute.hellbender.exceptions.GATKException: Locatable cache miss while attempting to retrieve a previous interval from the locatable cache. New interval: 20:9999980-10000254 Previous: 20:10000555-10001000
        at org.broadinstitute.hellbender.engine.FeatureCache.cacheHit(FeatureCache.java:164)
        at org.broadinstitute.hellbender.engine.FeatureDataSource.queryAndPrefetch(FeatureDataSource.java:497)
        at org.broadinstitute.hellbender.engine.FeatureManager.getFeatures(FeatureManager.java:340)
        at org.broadinstitute.hellbender.engine.FeatureContext.getValues(FeatureContext.java:172)
        at org.broadinstitute.hellbender.engine.FeatureContext.getValues(FeatureContext.java:124)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.callRegion(HaplotypeCallerEngine.java:530)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller.apply(HaplotypeCaller.java:240)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:308)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:281)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1039)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
        at org.broadinstitute.hellbender.Main.instanceMain(Main.java:148)
        at org.broadinstitute.hellbender.Main.instanceMain(Main.java:189)
        at org.broadinstitute.hellbender.CommandLineProgramTest.runCommandLine(CommandLineProgramTest.java:27)
        at org.broadinstitute.hellbender.testutils.CommandLineProgramTester.runCommandLine(CommandLineProgramTester.java:97)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerIntegrationTest.testGenotypeGivenAllelesMode(HaplotypeCallerIntegrationTest.java:394)
`

**Comment by cmnbroad** [comment]
I recently rebased and re-ran this test. The results look similar to last time. The travis results can be found [here](https://app.travis-ci.com/github/broadinstitute/gatk/builds/246119278), while they last. The branch with the code is https://github.com/broadinstitute/gatk/tree/cn_cache_thrash_master.
