### ISSUE TITLE
Java heap space error (java.lang.OutOfMemoryError) in mutect2

### ISSUE THREAD

**Issue by bhanugandham** [broadinstitute/gatk#5900]
I used newly GATK4.1 version, and my scripts are:

java -Xmx300g -jar $GATK Mutect2 \
 --dont-use-soft-clipped-bases true \
 --tmp-dir $cw/$i/tmp \
 --input $DNAbam/ADAR16-DNA-2_NKD180600323/ADAR16-DNA-2_NKD180600323.best.uniq.pair.sort.markdup.bam \
 --input $RNAbam/$i/$i.merge.markdup.reheader.bam \
 --reference $genome\
 --output $cw/$i/$i.dna.rna.vcf \
 --normal-sample ADAR16-DNA-2_NKD180600323 \
 --tumor-sample $i \
 -bamout $cw/$i/$i.support.bam

and tail of error log are:

12:05:06.287 INFO  ProgressMeter - scaffold23905:111448            948.1                636040            670.9
12:05:30.519 INFO  ProgressMeter - scaffold23905:133852            948.5                636120            670.7
12:05:57.277 INFO  ProgressMeter - scaffold23905:147186            949.0                636170            670.4
12:24:34.669 INFO  PairHMM - Total compute time in PairHMM computeLogLikelihoods() : 31261.455155273
12:24:34.670 INFO  SmithWatermanAligner - Total compute time in java Smith-Waterman : 14618.28 sec
INFO	2019-04-13 12:45:11	SortingCollection	Creating merging iterator from 2 files
13:30:49.708 INFO  Mutect2 - Shutting down engine
[April 13, 2019 1:30:49 PM CST] org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2 done. Elapsed time: 1,035.35 minutes.
Runtime.totalMemory()=238653800448
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at htsjdk.samtools.SAMTextHeaderCodec.advanceLine(SAMTextHeaderCodec.java:142)
	at htsjdk.samtools.SAMTextHeaderCodec.decode(SAMTextHeaderCodec.java:97)
	at htsjdk.samtools.reference.ReferenceSequenceFileFactory.loadDictionary(ReferenceSequenceFileFactory.java:235)
	at htsjdk.samtools.reference.AbstractFastaSequenceFile.(AbstractFastaSequenceFile.java:68)
	at htsjdk.samtools.reference.AbstractIndexedFastaSequenceFile.(AbstractIndexedFastaSequenceFile.java:60)
	at htsjdk.samtools.reference.IndexedFastaSequenceFile.(IndexedFastaSequenceFile.java:80)
	at htsjdk.samtools.reference.IndexedFastaSequenceFile.(IndexedFastaSequenceFile.java:98)
	at htsjdk.samtools.reference.ReferenceSequenceFileFactory.getReferenceSequenceFile(ReferenceSequenceFileFactory.java:138)
	at org.broadinstitute.hellbender.utils.fasta.CachingIndexedFastaSequenceFile.(CachingIndexedFastaSequenceFile.java:134)
	at org.broadinstitute.hellbender.utils.fasta.CachingIndexedFastaSequenceFile.(CachingIndexedFastaSequenceFile.java:111)
	at org.broadinstitute.hellbender.utils.fasta.CachingIndexedFastaSequenceFile.(CachingIndexedFastaSequenceFile.java:96)
	at org.broadinstitute.hellbender.engine.ReferenceFileSource.(ReferenceFileSource.java:35)
	at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2Engine.makeStandardMutect2PostFilterReadTransformer(Mutect2Engine.java:171)
	at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2.makePostReadFilterTransformer(Mutect2.java:267)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:270)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:984)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:138)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/58055#Comment_58055

**Comment by bhanugandham** [comment]
@cmnbroad as discussed during gatk office hrs I created a github issue ticket for this error. Let me know if there is any other information you need from the user.

**Comment by droazen** [comment]
@bhanugandham As a side note, you shouldn't be running GATK4 using `java -jar` directly. You should use the included `gatk` launcher script, which sets a lot of important configuration settings, some of which have a major effect on tool performance.

**Comment by bhanugandham** [comment]
@droazen Thank you, I will let the user know too.

**Comment by thmourikis** [comment]
Hi, is this solved? I seem to have the same issue running GATK4 in conda.

**Comment by hliu2016** [comment]
I also run into this error. I am using the `gatk `launcher script. My command is `gatk Mutect2 -R /bio/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa -I chenmeifang-ready.bam -max-mnp-distance 0 -O normal_1.vcf.gz`. Is there any method to work through this error?

**Comment by bhanugandham** [comment]
@hliu2016 

Please post you question on the gatk forum here: https://gatkforums.broadinstitute.org/gatk/categories/ask-the-team. Our support team will help you out on the forum and it will help us keep track of issues users are facing. Thank you!

**Comment by hliu2016** [comment]
@bhanugandham 
I am just following gatk forum to here. I expect to find solution to go through this problem here, but  this thread has been not updated for six months. So I post to ask for help.

**Comment by DeadlyDoll** [comment]
i have the same problem, any progress? thanks

**Comment by fleharty** [comment]
@DeadlyDoll @bhanugandham 
I've not been able to generate this problem in any of my data.  Is there something unique about your data?

**Comment by bhanugandham** [comment]
@hliu2016 and @DeadlyDoll 

Can you please share a problematic subset of the bam so we can recreate this error on our end. Also please post the version of GATK you are using.

**Comment by kchaconv2** [comment]
Hi y'all

I've been trying to run GATK GenotypeGVCFs but I keep encounter this error. I've increase memory but it does not seems to be enough. 
My script is 
java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /gatk/gatk-package-4.0.6.0-local.jar GenotypeGVCFs -ploidy 1 -R /project/uma_john_gibbons/john_gibbons/AORY_AFLA/REF/Aspergillus_oryzae.ASM18445v3.dna.toplevel.fa -O /project/uma_john_gibbons/chacon_vargas/AOR-AFLA/GATK/4-Consolidate_GVCF/combined_Chr1.vcf -V gendb://Chr1/

Any thoughts?

15:06:40.794 WARN  InbreedingCoeff - Annotation will not be calculated, must provide at least 10 samples
05:40:05.630 INFO  GenotypeGVCFs - Shutting down engine
GENOMICSDB_TIMER,GenomicsDB iterator next() timer,Wall-clock time(s),2.0928187529999955,Cpu time(s),0.9772208090000016
[April 10, 2020 5:40:05 AM UTC] org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 932.26 minutes.
Runtime.totalMemory()=31136546816
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.broadinstitute.hellbender.tools.walkers.genotyper.GenotypeLikelihoodCalculator.<init>(GenotypeLikelihoodCalculator.java:153)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.GenotypeLikelihoodCalculators.getInstance(GenotypeLikelihoodCalculators.java:269)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.GeneralPloidyExactAFCalculator.computeLofK(GeneralPloidyExactAFCalculator.java:272)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.GeneralPloidyExactAFCalculator.calculateACConformationAndUpdateQueue(GeneralPloidyExactAFCalculator.java:187)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.GeneralPloidyExactAFCalculator.fastCombineMultiallelicPool(GeneralPloidyExactAFCalculator.java:148)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.GeneralPloidyExactAFCalculator.combineSinglePools(GeneralPloidyExactAFCalculator.java:112)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.GeneralPloidyExactAFCalculator.computeLog10PNonRef(GeneralPloidyExactAFCalculator.java:25)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.AFCalculator.getLog10PNonRef(AFCalculator.java:33)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.GenotypingEngine.calculateGenotypes(GenotypingEngine.java:255)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.GenotypingEngine.calculateGenotypes(GenotypingEngine.java:210)
	at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.calculateGenotypes(GenotypeGVCFs.java:266)
	at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.regenotypeVC(GenotypeGVCFs.java:222)
	at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.apply(GenotypeGVCFs.java:201)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.lambda$traverse$0(VariantWalkerBase.java:151)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase$$Lambda$91/1033850902.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.traverse(VariantWalkerBase.java:149)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:984)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:135)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:180)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:199)
Using GATK jar /gatk/gatk-package-4.0.6.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /gatk/gatk-package-4.0.6.0-local.jar GenotypeGVCFs -ploidy 1 -R /project/uma_john_gibbons/john_gibbons/AORY_AFLA/REF/Aspergillus_oryzae.ASM18445v3.dna.toplevel.fa -O /project/uma_john_gibbons/chacon_vargas/AOR-AFLA/GATK/4-Consolidate_GVCF/combined_Chr1.vcf -V gendb://Chr1/
