### ISSUE TITLE
GATK4.1.0 IndexFeatureFile only indexed the last chromosome

### ISSUE THREAD

**Issue by yifangt** [broadinstitute/gatk#5917]
Hello, 
I was trying to create a candidates SNP list for  **GATK4 BaseRecalibrator** to recalibrate the alignment for SNP calling. And I met a problem with the indexing of the my vcf file of candidates SNPs. 
The indexing step and recalibrating step ran without any error, but only very small amount of SNPs (~2900) were detected from a genome **~15Gbp** size, which is definitely not correct as compared with other methods when **~million SNPs** were detected. 
I tracked down the problem is at the indexing step for the candidates vcf file (**925751 SNPs, through HaplotypeCaller**). The problem looks like only the **last chromosome** was indexed.
This is my log file in which the Google engine related part was omitted as I did not use it: 
```
$ cat ${LOGDIR}/index_candidates.log

(09:28:38.902 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/storage/ppl/yifang/download-software/anaconda3/envs/exome/share/gatk4-4.1.0.0-0/gatk-package-4.1.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
May 06, 2019 9:28:39 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
WARNING: Failed to detect whether we are running on Google Compute Engine.
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)

......

May 06, 2019 9:28:39 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
WARNING: Failed to detect whether we are running on Google Compute Engine.
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	
May 06, 2019 9:28:39 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
WARNING: Failed to detect whether we are running on Google Compute Engine.
java.net.ConnectException: Connection refused

......

	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)

09:28:39.193 INFO  IndexFeatureFile - ------------------------------------------------------------
09:28:39.193 INFO  IndexFeatureFile - The Genome Analysis Toolkit (GATK) v4.1.0.0
09:28:39.193 INFO  IndexFeatureFile - For support and documentation go to https://software.broadinstitute.org/gatk/
09:28:39.194 INFO  IndexFeatureFile - Executing as yifang@valiant5 on Linux v4.15.0-45-generic amd64
09:28:39.194 INFO  IndexFeatureFile - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_45-b14
09:28:39.194 INFO  IndexFeatureFile - Start Date/Time: May 6, 2019 9:28:38 CST AM
09:28:39.194 INFO  IndexFeatureFile - ------------------------------------------------------------
09:28:39.194 INFO  IndexFeatureFile - ------------------------------------------------------------
09:28:39.195 INFO  IndexFeatureFile - HTSJDK Version: 2.18.2
09:28:39.195 INFO  IndexFeatureFile - Picard Version: 2.18.25
09:28:39.195 INFO  IndexFeatureFile - HTSJDK Defaults.COMPRESSION_LEVEL : 2
09:28:39.195 INFO  IndexFeatureFile - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
09:28:39.195 INFO  IndexFeatureFile - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
09:28:39.195 INFO  IndexFeatureFile - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
09:28:39.196 INFO  IndexFeatureFile - Deflater: IntelDeflater
09:28:39.196 INFO  IndexFeatureFile - Inflater: IntelInflater
09:28:39.196 INFO  IndexFeatureFile - GCS max retries/reopens: 20
09:28:39.196 INFO  IndexFeatureFile - Requester pays: disabled
09:28:39.196 INFO  IndexFeatureFile - Initializing engine
09:28:39.196 INFO  IndexFeatureFile - Done initializing engine
09:28:39.696 INFO  FeatureManager - Using codec VCFCodec to read file file:///storage/ppl/yifang/20190327_David_rampseq_Ehsan/data/samtools_sorted_out/SNPs_candidates.g.vcf
09:28:39.708 INFO  ProgressMeter - Starting traversal
09:28:39.708 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Records Processed   Records/Minute
=========This is the indexed chromosome  ===================
09:28:41.968 INFO  ProgressMeter - **chr7B_part2:295520629**              0.0                925631       24596040.7

09:28:41.968 INFO  ProgressMeter - Traversal complete. Processed 925631 total records in 0.0 minutes.
09:28:42.006 INFO  IndexFeatureFile - Successfully wrote index to /storage/ppl/yifang/20190327/data/samtools_sorted_out/SNPs_candidates.g.vcf.idx
09:28:42.006 INFO  IndexFeatureFile - Shutting down engine
[May 6, 2019 9:28:42 CST AM] org.broadinstitute.hellbender.tools.IndexFeatureFile done. Elapsed time: 0.05 minutes.
Runtime.totalMemory()=2434269184)

```
This is my command line:
`java -DGATK_STACKTRACE_ON_USER_EXCEPTION=true -jar ${gatk4_jar} IndexFeatureFile --feature-file ${gvcf} --output ${gvcf}.idx  2>${LOGDIR}/index_candidates.log`

I tried this exact command line with another genome, which worked just fine with output progress report as following for a comparison of the multiple chromosomes processed:
```
12:50:38.871 INFO  ProgressMeter - Starting traversal
12:50:38.873 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Records Processed   Records/Minute
12:50:48.876 INFO  ProgressMeter -          N1:21408210              0.2               5669000       34010598.9
12:50:58.876 INFO  ProgressMeter -          N2:13383863              0.3              11960000       35874618.8

......

12:55:58.884 INFO  ProgressMeter -         N19:50063133              5.3             208660000       39122405.2
12:56:02.409 INFO  ProgressMeter -         N19:55994806              5.4             210940859       39119265.4
12:56:02.409 INFO  ProgressMeter - Traversal complete. Processed 210940859 total records in 5.4 minutes.
12:56:02.429 INFO  IndexFeatureFile - Successfully wrote index to /storage/ppl/yifang/20190225/data3/samtools_sorted_out/SNPs_candidates.g.vcf.idx
12:56:02.429 INFO  IndexFeatureFile - Shutting down engine
[April 25, 2019 12:56:02 PM CST] org.broadinstitute.hellbender.tools.IndexFeatureFile done. Elapsed time: 5.42 minutes.
Runtime.totalMemory()=5618270208
```
Althought no warning/error messages was issued for the indexing of this big genome, I have tried to debug on 3 things I could think of:

1. The chromosome and the coordinate are sorted ascendandly, although the chromosome names are not simply numeric continuous because of the A/B subgroup for each chromosome.
2. The genome size difference, for which no clue was aboserved about the chromosome length limits. 
3. The chromosome names for this big genome is quite long, but I tried the shorter names as A11 for chr1A_part1, A12 for chr1A_part2, ... B72 for chr7B_part2 (42 chromosomes in total), and the problem stayed exactly the same.

Not sure what I may have missed. I appreciate any insight of this problem.
Yifang

**Comment by cmnbroad** [comment]
@yifangt I don't think the progress meter output is a reliable basis for concluding that only one chromosome was indexed, as its time-based not content based. I would suggest manually running a query against candidate snp file after its been indexed (maybe using SelectVariants, on a specific locus on some contig other than the one that IndexFeatureFile reported as being indexed) and see if the results appear to be correct. That will help determine if the index is really the issue.

**Comment by yifangt** [comment]
Thanks Chris!
Yes, you are right!
I tested the index with **SelectVariants** on different intervals, and they are all retrievable with ease and no errors! 
Now the indexing step can be confirmed right and the problem must be something else.
Thank you so much for this advice.
