### ISSUE TITLE
GATK4 SelectVariants: java.lang.NumberFormatException: For input string: "1,0"

### ISSUE THREAD

**Issue by xunxun66** [broadinstitute/gatk#5929]
Hi,

First I filter snp.raw.vcf with `VariantFiltration` command below: 
`gatk-4.1.2.0/gatk --java-options "-Djava.io.tmpdir=/tmp/" VariantFiltration -R genome.fa -V snp_rmnan.raw.vcf --filter-expression "QUAL < 30.0 || QD < 2.0 || FS > 60.0 || MQ < 40.0 || SOR > 4.0 || ReadPosRankSum < -8.0" --filter-name "my_snp_filter" --missing-values-evaluate-as-failing true -O snp_rmnan.raw.vcf.tmp.vcf `

This command runs successfully.

But when I'm using `SelectVariants` command to extact the filtered site:
`gatk-4.1.2.0/gatk --java-options "-Djava.io.tmpdir=/tmp/" SelectVariants -R genome.fa -V snp_rmnan.raw.vcf.tmp.vcf --exclude-filtered -O snp_rmnan.raw.vcf.filter.vcf `

I get this java ERROR below, even without the wrong line number and do not know how to deal with it......... o(╥﹏╥)o，Thank you very much!

~~~
11:15:52.195 INFO  ProgressMeter -       Chr01:15144308             19.9                541000          27161.2
11:16:04.187 INFO  ProgressMeter -       Chr01:15388212             20.1                547000          27189.6
11:16:12.515 INFO  SelectVariants - Shutting down engine
[May 9, 2019 11:16:12 AM CST] org.broadinstitute.hellbender.tools.walkers.variantutils.SelectVariants done. Elapsed time: 20.37 minutes.
Runtime.totalMemory()=2814377984
java.lang.NumberFormatException: For input string: "1,0"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at htsjdk.variant.vcf.AbstractVCFCodec.createGenotypeMap(AbstractVCFCodec.java:734)
        at htsjdk.variant.vcf.AbstractVCFCodec$LazyVCFGenotypesParser.parse(AbstractVCFCodec.java:132)
        at htsjdk.variant.variantcontext.LazyGenotypesContext.decode(LazyGenotypesContext.java:158)
        at htsjdk.variant.variantcontext.LazyGenotypesContext.getGenotypes(LazyGenotypesContext.java:148)
        at htsjdk.variant.variantcontext.GenotypesContext.iterator(GenotypesContext.java:465)
        at org.broadinstitute.hellbender.tools.walkers.variantutils.SelectVariants.initalizeAlleleAnyploidIndicesCache(SelectVariants.java:674)
        at org.broadinstitute.hellbender.tools.walkers.variantutils.SelectVariants.apply(SelectVariants.java:580)
        at org.broadinstitute.hellbender.engine.VariantWalker.lambda$traverse$0(VariantWalker.java:106)
        at org.broadinstitute.hellbender.engine.VariantWalker$$Lambda$73/388489274.accept(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.broadinstitute.hellbender.engine.VariantWalker.traverse(VariantWalker.java:104)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1039)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
        at org.broadinstitute.hellbender.Main.main(Main.java:291)~~~

**Comment by SHuang-Broad** [comment]
@xunxun66
The [forum](https://gatkforums.broadinstitute.org/gatk/categories/ask-the-team) is a better place for this type of questions.

**Comment by xunxun66** [comment]
> @xunxun66
> The [forum](https://gatkforums.broadinstitute.org/gatk/categories/ask-the-team) is a better place for this type of questions.

Thank you so much !
