### ISSUE TITLE
CNNScoreVariants --info-annotation-keys strange behavior

### ISSUE THREAD

**Issue by nikolapeja6** [broadinstitute/gatk#5939]
I read the [CNNScoreVariants documentation](https://software.broadinstitute.org/gatk/documentation/tooldocs/current/org_broadinstitute_hellbender_tools_walkers_vqsr_CNNScoreVariants.php#--info-annotation-keys) and ran the ```--help``` option, and both state the following

```
--info-annotation-keys,-info-annotation-keys:String
		The VCF info fields to send to python.  This argument may be specified 0 or more times.
		Default value: [MQ, DP, SOR, FS, QD, MQRankSum, ReadPosRankSum]. 
``` 

I successfully executed the CNNScoreVariants command with the default value of the ```--info-annotation-keys``` argument in the following way.

```
--info-annotation-keys '[MQ, DP, SOR, FS, QD, MQRankSum, ReadPosRankSum]' 
```

However, when I try to change the number of fields, for example like

```
--info-annotation-keys '[MQ, DP, SOR, FS, QD, MQRankSum]' 
```

or anything more or less than seven fields I get an error like the following one

```
Traceback (most recent call last):
		File "<stdin>", line 1, in <module>
		File "/opt/miniconda/envs/gatk/lib/python3.6/site-packages/vqsr_cnn/vqsr_cnn/inference.py", line 127, in score_and_write_batch
		batch_size=python_batch_size)
		File "/opt/miniconda/envs/gatk/lib/python3.6/site-packages/keras/engine/training.py", line 1152, in predict
		x, _, _ = self._standardize_user_data(x)
		File "/opt/miniconda/envs/gatk/lib/python3.6/site-packages/keras/engine/training.py", line 754, in _standardize_user_data
		exception_prefix='input')
		File "/opt/miniconda/envs/gatk/lib/python3.6/site-packages/keras/engine/training_utils.py", line 136, in standardize_input_data
		str(data_shape))
	ValueError: Error when checking input: expected annotations to have shape (7,) but got array with shape (6,)
```

According to the documentation, I should be able to use the argument with an arbitrary number of fields.

Is this a bug, or am I using the ```--info-annotation-keys``` argument incorrectly?

**Comment by lucidtronix** [comment]
Hi @nikolapeja6,
Sorry for the confusion.  The pre-trained model that we distribute with the GATK was trained with those 7 default annotation keys so if you only change the `--info-annotation-keys` argument and don't pass a model expecting the different arguments you will get the error that you are seeing.  In order to use a different set of arguments you would need to re-train a model that expects that set of annotations.  This forum questions discusses what you would need to do to train a model on a set of custom annotations: https://gatkforums.broadinstitute.org/gatk/discussion/23821/possible-to-using-cnnscorevariants-with-pacbio-reads#latest

**Comment by cmnbroad** [comment]
We should update the class doc and arg doc strings to reflect this.
