### ISSUE TITLE
FilterMutectCalls doesn't accept this parameter `--normal-p-value-threshold`

### ISSUE THREAD

**Issue by bhanugandham** [broadinstitute/gatk#5978]
This error was reported by a user: 

Dear GATK Team, 

I am writing you to discuss a an error while using FilterMutectCalls program and it seems a potential bug. 
I wanted to change the default value of **--normal-p-value-threshold **. It looks like the tool doesn't accept this parameter at all. I tried using it with the default value of 0.001 as well. 

The program works fine when this parameter is removed. Moreover, the error message also states that **BUG: couldn't set field value** .

please see the attached command and the error message. 

** gatk FilterMutectCalls -V TAR-158_unfiltered.vcf.gz --normal-p-value-threshold 0.0001 -R ../data/hg_ref/genome.fa --contamination-table TAR-158_tumor_calculatecontamination.table -O TAR-158_artifact_0.01.vcf.gz**

Using GATK jar /mnt/gpfs1/lmod/apps/gatk/4.1.1.0/gatk-package-4.1.1.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /mnt/gpfs1/lmod/apps/gatk/4.1.1.0/gatk-package-4.1.1.0-local.jar FilterMutectCalls -V TAR-158_unfiltered.vcf.gz --normal-p-value-threshold 0.0001 -R ../data/hg_ref/genome.fa --contamination-table TAR-158_tumor_calculatecontamination.table -O TAR-158_artifact_0.01.vcf.gz
org.broadinstitute.barclay.argparser.CommandLineException$ShouldNeverReachHereException: **BUG: couldn't set field value. For normalPileupPValueThreshold in org.broadinstitute.hellbender.tools.walkers.mutect.filtering.M2FiltersArgumentCollection@69d45cca with value 1.0E-4 This shouldn't happen since we setAccessible(true)**
	at org.broadinstitute.barclay.argparser.CommandLineArgumentParser$ArgumentDefinition.setFieldValue(CommandLineArgumentParser.java:1248)
	at org.broadinstitute.barclay.argparser.CommandLineArgumentParser.setArgument(CommandLineArgumentParser.java:710)
	at org.broadinstitute.barclay.argparser.CommandLineArgumentParser.parseArguments(CommandLineArgumentParser.java:427)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.parseArgs(CommandLineProgram.java:232)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:206)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)
Caused by: java.lang.IllegalAccessException: Can not set static final double field org.broadinstitute.hellbender.tools.walkers.mutect.filtering.M2FiltersArgumentCollection.normalPileupPValueThreshold to java.lang.Double
	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
	at sun.reflect.UnsafeQualifiedStaticDoubleFieldAccessorImpl.set(UnsafeQualifiedStaticDoubleFieldAccessorImpl.java:77)
	at java.lang.reflect.Field.set(Field.java:764)
	at org.broadinstitute.barclay.argparser.CommandLineArgumentParser$ArgumentDefinition.setFieldValue(CommandLineArgumentParser.java:1245)
	... 7 more

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/24071/filtermutectcalls-bug/p1

**Comment by bhanugandham** [comment]
@cmnbroad and @davidbenjamin 

 A user found this error when trying to set the `--normal-p-value-threshold' argument in FilterMutectCalls tool. In the tool documentation, looks like this argument is declared as static and final which is why we see this error. Would you please look into this.

**Comment by cmnbroad** [comment]
@davidbenjamin Looks like the variable for this arg is `final` and `static`. It probably should be neither, but making it non-static looks it it would require retaining a reference to `M2FiltersArgumentCollection` in `Mutect2FilteringEngine`. I'll leave it to you to figure out the right fix.
