### ISSUE TITLE
java.lang.OutOfMemoryError when 'java -jar gatk-package-4.1.2.0-local.jar' sometimes, but there is a lot of memory yet

### ISSUE THREAD

**Issue by wangyugui** [broadinstitute/gatk#6050]
## Bug Report

java.lang.OutOfMemoryError when 'java -jar /usr/hpc-bio/gatk/gatk-package-4.1.2.0-local.jar' sometimes, but there is a lot of memeory yet.

And then all features can not be used.

This is the call stack.
```
java  -jar gatk/gatk-package-4.1.2.0-local.jar
Exception in thread "main" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
        at java.util.Properties$LineReader.readLine(Properties.java:485)
        at java.util.Properties.load0(Properties.java:353)
        at java.util.Properties.load(Properties.java:317)
        at org.aeonbits.owner.loaders.PropertiesLoader.load(PropertiesLoader.java:50)
        at org.aeonbits.owner.loaders.PropertiesLoader.load(PropertiesLoader.java:43)
        at org.aeonbits.owner.LoadersManager.load(LoadersManager.java:46)
        at org.aeonbits.owner.Config$LoadType$2.load(Config.java:129)
        at org.aeonbits.owner.PropertiesManager.doLoad(PropertiesManager.java:290)
        at org.aeonbits.owner.PropertiesManager.load(PropertiesManager.java:163)
        at org.aeonbits.owner.PropertiesManager.load(PropertiesManager.java:153)
        at org.aeonbits.owner.PropertiesInvocationHandler.<init>(PropertiesInvocationHandler.java:54)
        at org.aeonbits.owner.DefaultFactory.create(DefaultFactory.java:46)
        at org.aeonbits.owner.ConfigCache.getOrCreate(ConfigCache.java:87)
        at org.aeonbits.owner.ConfigCache.getOrCreate(ConfigCache.java:40)
        at org.broadinstitute.hellbender.utils.config.ConfigFactory.getOrCreate(ConfigFactory.java:268)
        at org.broadinstitute.hellbender.utils.config.ConfigFactory.getOrCreateConfigFromFile(ConfigFactory.java:454)
        at org.broadinstitute.hellbender.utils.config.ConfigFactory.initializeConfigurationsFromCommandLineArgs(ConfigFactory.java:439)
        at org.broadinstitute.hellbender.utils.config.ConfigFactory.initializeConfigurationsFromCommandLineArgs(ConfigFactory.java:414)
        at org.broadinstitute.hellbender.Main.parseArgsForConfigSetup(Main.java:121)
        at org.broadinstitute.hellbender.Main.setupConfigAndExtractProgram(Main.java:179)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:204)
        at org.broadinstitute.hellbender.Main.main(Main.java:291)
```

### Affected version(s)
- [x] Latest public release version [version?]
   Yes. 4.1.2.0

- [ ] Latest master branch as of [date of test?]
   Not tested.

#### Steps to reproduce
Yet not clear.
maybe the call stack above will help.

----

**Comment by wangyugui** [comment]
Maybe some relationship to multiple GATK4 process and the same time.

**Comment by davidbenjamin** [comment]
@wangyugui What tool are you running?  What is the maximum depth of your sample?  How much RAM does your machine have?  How much RAM did you request in your Java command?

**Comment by wangyugui** [comment]
The command was 'java  -jar gatk/gatk-package-4.1.2.0-local.jar'.  It should output the help message.
The server has 256G memory.

there should be a bug of linux kernel or java jvm or gatk of some version.

Let's close it before I can reproduce it.
