### ISSUE TITLE
Support JDK11

### ISSUE THREAD

**Issue by adamjorr** [broadinstitute/gatk#6053]
## Bug Report
JDK8 is no longer available for the current stable Debian release (buster). Trying to run gatk with an OpenJDK11 install fails.

I anticipate a WONTFIX since this is dependency related, but I figured it would be good to let people know

### Affected tool(s) or class(es)
GATKRead, probably others too

### Affected version(s)
- [x] Latest public release version [4.1.2.0]
- [ ] Latest master branch as of [didn't test]

### Description 
```
Exception in thread "main" java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class org/broadinstitute/hellbender/transformers/ReadTransformer. Method 'org.broadinstitute.hellbender.utils.read.GATKRead lambda$identity$d67512bf$1(org.broadinstitute.hellbender.utils.read.GATKRead)' at index 65 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
	at org.broadinstitute.hellbender.transformers.ReadTransformer.identity(ReadTransformer.java:30)
	at org.broadinstitute.hellbender.engine.GATKTool.makePreReadFilterTransformer(GATKTool.java:345)
	at org.broadinstitute.hellbender.engine.GATKTool.getTransformedReadStream(GATKTool.java:374)
	at org.broadinstitute.hellbender.engine.ReadWalker.traverse(ReadWalker.java:93)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1039)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)
```

This error seems related to the JRE version. You can still install JDK8 manually but that's not ideal for many users.

#### Steps to reproduce
Run GATK on OpenJDK11

#### Expected behavior
Program runs :)

#### Actual behavior
Error

**Comment by droazen** [comment]
@adamjorr We'd like to support newer versions of Java, but have historically been held back by our Apache Spark dependency. We'll take another look at our dependency situation, however, and see if an upgrade is possible at this point.

**Comment by kelepiradam** [comment]
AdoptOpenJDK offers a debian/ubuntu repository for those to install java 1.8. That may be used. Other than that AdoptOpenJDK 11.0.4 works flawlessly for me under Debian Buster unless it is a spark tool.

**Comment by droazen** [comment]
Closing -- superseded by https://github.com/broadinstitute/gatk/issues/6671
