### ISSUE TITLE
FilterMutectCalls : errorRate must be good probability but got NaN

### ISSUE THREAD

**Issue by chadisaad** [broadinstitute/gatk#6058]
I'm trying to run Mutect2 in tumor-only mode, for a small panel, and I get this errors at the FilterMutectCalls step

```bash
  [July 26, 2019 9:34:50 AM UTC] org.broadinstitute.hellbender.tools.walkers.mutect.filtering.FilterMutectCalls done. Elapsed time: 0.06 minutes.
  Runtime.totalMemory()=2129657856
  java.lang.IllegalArgumentException: errorRate must be good probability but got NaN
        at org.broadinstitute.hellbender.utils.Utils.validateArg(Utils.java:730)
        at org.broadinstitute.hellbender.utils.QualityUtils.errorProbToQual(QualityUtils.java:225)
        at org.broadinstitute.hellbender.utils.QualityUtils.errorProbToQual(QualityUtils.java:209)
        at org.broadinstitute.hellbender.tools.walkers.mutect.filtering.Mutect2FilteringEngine.lambda$applyFiltersAndAccumulateOutputStats$13(Mutect2FilteringEngine.java:176)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.broadinstitute.hellbender.tools.walkers.mutect.filtering.Mutect2FilteringEngine.applyFiltersAndAccumulateOutputStats(Mutect2FilteringEngine.java:174)
        at org.broadinstitute.hellbender.tools.walkers.mutect.filtering.FilterMutectCalls.nthPassApply(FilterMutectCalls.java:142)
        at org.broadinstitute.hellbender.engine.MultiplePassVariantWalker.lambda$traverse$0(MultiplePassVariantWalker.java:40)
        at org.broadinstitute.hellbender.engine.MultiplePassVariantWalker.lambda$traverseVariants$1(MultiplePassVariantWalker.java:77)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.broadinstitute.hellbender.engine.MultiplePassVariantWalker.traverseVariants(MultiplePassVariantWalker.java:75)
        at org.broadinstitute.hellbender.engine.MultiplePassVariantWalker.traverse(MultiplePassVariantWalker.java:40)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1039)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
        at org.broadinstitute.hellbender.Main.main(Main.java:291)
  Using GATK jar /gatk/gatk-package-4.1.2.0-local.jar

```

Here is my commands:

```bash

        gatk \
            Mutect2 \
            -R hg19.fa \
            -I test.bam \
            -L myDesign.bed \
            --f1r2-tar-gz  test.f1r2.tar.gz \
            $filterGermline \
            -O  test-unfiltered.vcf


        gatk \
            LearnReadOrientationModel \
            -I    test.f1r2.tar.gz \
            -O  test.read-orientation-model.tar.gz


      gatk \
            FilterMutectCalls \
            -R hg19.fa \
            -V test-unfiltered.vcf  \
            --ob-priors  test.read-orientation-model.tar.gz \
            -O test.vcf
```

**Comment by fleharty** [comment]
@chadisaad Could you make your file test-unfiltered.vcf available?

**Comment by chadisaad** [comment]
Here is the test-unfiltered.vcf file

[test-unfiltered.zip](https://github.com/broadinstitute/gatk/files/3569917/test-unfiltered.zip)

**Comment by davidbenjamin** [comment]
@chadisaad What GATK version did you use?  I was not able to reproduce your error with GATK releases from August 2019 and December 2019.

**Comment by chadisaad** [comment]
with last release, its fine. Bug resolved.

but still have this error : https://github.com/bcbio/bcbio-nextgen/issues/2829

I finished by doing like that : https://github.com/bcbio/bcbio-nextgen/commit/3ed523f04cbbbbf3ef19974d5a7585ed43af2c20

it happens with contrôle empty samples (zero variants)

**Comment by davidbenjamin** [comment]
@chadisaad The remaining error involves samples with no callable sites, which means not only that they are control samples but that M2 saw no sites with coverage of 10 or more reads.  Also, if it is a control sample with no variants, why run FilterMutectCalls on it?

If this error shows up for a case sample, feel free to open an issue in this repo.
