### ISSUE TITLE
GenomicsDBImport java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by bhanugandham** [broadinstitute/gatk#6122]
GATK version: GATK 4.1.3.0
docker container used: quay.io/biocontainers/gatk4:4.1.3.0--0

Please find below the error report from a GATK user:

20:06:25.036 INFO  GenomicsDBImport - GCS max retries/reopens: 20
20:06:25.036 INFO  GenomicsDBImport - Requester pays: disabled
20:06:25.037 INFO  GenomicsDBImport - Initializing engine
20:07:32.463 INFO  FeatureManager - Using codec IntervalListCodec to read file file:///gscmnt/gc2560/core/model_data/2887491634/build21f22873ebe0486c8e6f69c15435aa96/GRCh38_autosomal.interval_list
20:07:32.555 INFO  IntervalArgumentCollection - Processing 2875001522 bp from intervals
20:07:32.792 INFO  GenomicsDBImport - Done initializing engine
20:07:33.106 INFO  GenomicsDBImport - Shutting down engine
[August 22, 2019 8:07:33 PM GMT] org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport done. Elapsed time: 1.17 minutes.
Runtime.totalMemory()=253493248
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.genomicsdb.GenomicsDBUtils.createTileDBWorkspace(GenomicsDBUtils.java:37)
	at org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport.overwriteCreateOrCheckWorkspace(GenomicsDBImport.java:883)
	at org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport.onTraversalStart(GenomicsDBImport.java:605)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1046)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)
Caused by: org.genomicsdb.exception.GenomicsDBException: Could not load genomicsdb native library
	at org.genomicsdb.GenomicsDBUtilsJni.<clinit>(GenomicsDBUtilsJni.java:33)
	... 10 more
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libtiledbgenomicsdb8918780584607909502.so: libcurl.so.4: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.genomicsdb.GenomicsDBLibLoader.loadLibraryFromJar(GenomicsDBLibLoader.java:147)
	at org.genomicsdb.GenomicsDBLibLoader.loadLibrary(GenomicsDBLibLoader.java:47)
	at org.genomicsdb.GenomicsDBUtilsJni.<clinit>(GenomicsDBUtilsJni.java:30)
	... 10 more

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/24378/error-while-running-genomicsdbimport/p1

**Comment by lbergelson** [comment]
@droazen This is fixed now?

**Comment by droazen** [comment]
I believe this was fixed in GenomicsDB version 1.1.2

**Comment by droazen** [comment]
(according to https://github.com/broadinstitute/gatk/pull/6188)
