### ISSUE TITLE
VCFHeaderLine: ID cannot contain an equals sign

### ISSUE THREAD

**Issue by Umutunaldi** [broadinstitute/gatk#6127]
Hi,

I made an alignment with my pair-end reads with this command line i have found on the internet:

```
#!/bin/bash

header=$(zcat $1 | head -n 1)
id=$(echo $header | head -n 1 | cut -f 1-4 -d":" | sed 's/@//' | sed 's/:/_/g')
sm=$(echo $header | head -n 1 | grep -Eo "[ATGCN]+$")
echo "Read Group @RG\tID:$id\tSM:$id"_"$sm\tLB:$id"_"$sm\tPL:ILLUMINA"

bwa mem \
-M \
-t 8 \
-v 3 \
-R $(echo "@RG\tID:$id\tSM:$id"_"$sm\tLB:$id"_"$sm\tPL:ILLUMINA") \
"$path_genome_dir" \
$1 $2 | samblaster -M | samtools fixmate - - | samtools sort -O bam -o "mapped-bwa.bam"
```
Then, I created ".fai" and ".dict" extension of my genome by using,

`java -jar picard.jar CreateSequenceDictionary R= genome.fa O= genome.fa.dict`

`samtools faidx genome.fa`

Then I used this command to use HaplotypeCaller feature of gatk (4.1.3.0): `"./gatk --java-options "-Xmx8G" HaplotypeCaller -R genome.fa -I mapped-bwa.bam -O mapped-bwa.vcf"`

Then, this gave me an error: `java.lang.IllegalArgumentException: VCFHeaderLine: ID cannot contain an equals sign
	at htsjdk.variant.vcf.VCFSimpleHeaderLine.initialize(VCFSimpleHeaderLine.java:108)
	at htsjdk.variant.vcf.VCFSimpleHeaderLine.<init>(VCFSimpleHeaderLine.java:91)
	at htsjdk.variant.vcf.VCFContigHeaderLine.<init>(VCFContigHeaderLine.java:66)
	at htsjdk.variant.vcf.VCFHeader.setSequenceDictionary(VCFHeader.java:294)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.makeVCFHeader(HaplotypeCallerEngine.java:423)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.writeHeader(HaplotypeCallerEngine.java:435)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller.onTraversalStart(HaplotypeCaller.java:229)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1046)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)
`

Do you have any idea to solve this problem? I have tried several methods but couldn't fix it. Thank you so much already!

**Comment by Umutunaldi** [comment]
@cmnbroad Thank you so much for the reply! 

`@HD	VN:1.5	SO:coordinate
@SQ	SN:chr1	LN:33620256
@SQ	SN:chr2	LN:22538771
@SQ	SN:chr3	LN:32707041
@SQ	SN:chr4	LN:28671919
@SQ	SN:chr5	LN:31535018
@SQ	SN:chr6	LN:34462338
@SQ	SN:chr7	LN:29853271
@SQ	SN:chr8	LN:25401129
@SQ	SN:chr9	LN:30402900
@SQ	SN:chr10	LN:28782984
@SQ	SN:chr11	LN:25368500
@SQ	SN:chr12	LN:32976111
@SQ	SN:chr13	LN:32525912
@SQ	SN:chr14	LN:20020210
@SQ	SN:chr15	LN:24972737
@SQ	SN:ScfZf2F_2;HRSCAF=3-1	LN:513416
@SQ	SN:ScfZf2F_4;HRSCAF=5-1	LN:23768
@SQ	SN:ScfZf2F_5;HRSCAF=9-1	LN:63563
@SQ	SN:ScfZf2F_6;HRSCAF=11-1	LN:202551
@SQ	SN:ScfZf2F_7;HRSCAF=12-2	LN:46654
@SQ	SN:ScfZf2F_7;HRSCAF=12-1	LN:201473
`

This is the first lines of my BAM file. Thank you again.

**Comment by Umutunaldi** [comment]
@cmnbroad Thank you now I understand the problem. Also, do you have any idea why is this happening? I have tried it with different reads and still got the same equal signs on my .BAM file. It is probably related to the genome file, right? Thanks again!

**Comment by cmnbroad** [comment]
They're either coming directly from the reference file (which I think is most likely - its easy to check and see if they appear there), or being transformed somehow along the way.
