### ISSUE TITLE
NullPointerException error while running Mutect2

### ISSUE THREAD

**Issue by tmm211** [broadinstitute/gatk#6142]
User is running Mutect2 on GATK 4.1.3.0 and gets a NullPointerException error. Their bam did run using different variant callers. However, they got these [results twice](https://gatkforums.broadinstitute.org/gatk/discussion/comment/60577#Comment_60577) on two different bams. Here is the latest error below. 

If possible, can the error message improve? The user was able to continue after creating  a new index and dictionary for their reference:

./gatk --java-options "-Dsamjdk.sra_libraries_download=true" Mutect2 -R hg19.fa -I test3.bam -O unfiltered.vcf
Using GATK jar /c/linux/gatk/gatk-package-4.1.3.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Dsamjdk.sra_libraries_download=true -jar /c/linux/gatk/gatk-package-4.1.3.0-local.jar Mutect2 -R hg19.fa -I test3.bam -O unfiltered.vcf
10:33:35.145 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/c/linux/gatk/gatk-package-4.1.3.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Aug 28, 2019 10:33:37 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
10:33:37.506 INFO  Mutect2 - ------------------------------------------------------------
10:33:37.507 INFO  Mutect2 - The Genome Analysis Toolkit (GATK) v4.1.3.0
10:33:37.507 INFO  Mutect2 - For support and documentation go to https://software.broadinstitute.org/gatk/
10:33:37.508 INFO  Mutect2 - Executing as ascott3@LAPTOP-L1C565MP on Linux v4.4.0-17763-Microsoft amd64
10:33:37.508 INFO  Mutect2 - Java runtime: OpenJDK 64-Bit Server VM v11.0.4+11-post-Ubuntu-1ubuntu218.04.3
10:33:37.508 INFO  Mutect2 - Start Date/Time: August 28, 2019 at 10:33:35 AM GMT
10:33:37.509 INFO  Mutect2 - ------------------------------------------------------------
10:33:37.509 INFO  Mutect2 - ------------------------------------------------------------
10:33:37.510 INFO  Mutect2 - HTSJDK Version: 2.20.1
10:33:37.510 INFO  Mutect2 - Picard Version: 2.20.5
10:33:37.510 INFO  Mutect2 - HTSJDK Defaults.COMPRESSION_LEVEL : 2
10:33:37.511 INFO  Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
10:33:37.511 INFO  Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
10:33:37.511 INFO  Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
10:33:37.513 INFO  Mutect2 - Deflater: IntelDeflater
10:33:37.513 INFO  Mutect2 - Inflater: IntelInflater
10:33:37.514 INFO  Mutect2 - GCS max retries/reopens: 20
10:33:37.514 INFO  Mutect2 - Requester pays: disabled
10:33:37.514 INFO  Mutect2 - Initializing engine
10:33:37.874 INFO  Mutect2 - Shutting down engine
[August 28, 2019 at 10:33:37 AM GMT] org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2 done. Elapsed time: 0.05 minutes.
Runtime.totalMemory()=161480704
java.lang.NullPointerException
        at org.broadinstitute.hellbender.utils.SequenceDictionaryUtils.getContigNames(SequenceDictionaryUtils.java:463)
        at org.broadinstitute.hellbender.utils.SequenceDictionaryUtils.getCommonContigsByName(SequenceDictionaryUtils.java:457)
        at org.broadinstitute.hellbender.utils.SequenceDictionaryUtils.compareDictionaries(SequenceDictionaryUtils.java:234)
        at org.broadinstitute.hellbender.utils.SequenceDictionaryUtils.validateDictionaries(SequenceDictionaryUtils.java:150)
        at org.broadinstitute.hellbender.utils.SequenceDictionaryUtils.validateDictionaries(SequenceDictionaryUtils.java:98)
        at org.broadinstitute.hellbender.engine.GATKTool.validateSequenceDictionaries(GATKTool.java:769)
        at org.broadinstitute.hellbender.engine.GATKTool.onStartup(GATKTool.java:711)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.onStartup(AssemblyRegionWalker.java:161)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:137)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
        at org.broadinstitute.hellbender.Main.main(Main.java:291)

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/60577#Comment_60577

**Comment by jamesemery** [comment]
An update: apparently asking the user to regenerate their index and dictionary files for their references has resolved the issue. We should soften the blow of null pointers in the future. Apparently the dictionary was present (as it wouldn't work otherwise) but was corrupt somehow, a proposal from @droazen would be to add to the sequnce dictionary check we already perform a check that the file is readable.
