### ISSUE TITLE
CollectWgsMetrics - java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by jemunro** [broadinstitute/gatk#6163]
### Affected tool(s) or class(es)
CollectWgsMetrics

### Affected version(s)
- 4.1.3.0

### Description 
CollectWgsMetrics crashes on input that has worked for previous versions (including 4.1.2.0).

#### Steps to reproduce
```bash
gatk CollectWgsMetrics \
    --java-options "-Xms6G -Xmx10G -Djava.io.tmpdir=." \
    --INPUT=example.bam \
    --OUTPUT=example.seq_metrics.txt \
    --REFERENCE_SEQUENCE=ucsc.hg19.fasta \
    --USE_FAST_ALGORITHM=true \
    --LOCUS_ACCUMULATION_CAP 25000 \
    --COVERAGE_CAP=100
```
#### Expected behavior
CollectWgsMetrics should not crash

#### Actual behavior
```terminal
02:33:12.885 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/opt/conda/envs/base-v1.4.1/share/gatk4-4.1.3.0-0/gatk-package-4.1.3.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
[Mon Sep 16 02:33:13 UTC 2019] CollectWgsMetrics  --INPUT example.bam --OUTPUT example.seq_metrics.txt --COVERAGE_CAP 100 --LOCUS_ACCUMULATION_CAP 25000 --USE_FAST_ALGORITHM true --REFERENCE_SEQUENCE ucsc.hg19.fasta  --MINIMUM_MAPPING_QUALITY 20 --MINIMUM_BASE_QUALITY 20 --STOP_AFTER -1 --INCLUDE_BQ_HISTOGRAM false --COUNT_UNPAIRED false --SAMPLE_SIZE 10000 --ALLELE_FRACTION 0.001 --ALLELE_FRACTION 0.005 --ALLELE_FRACTION 0.01 --ALLELE_FRACTION 0.02 --ALLELE_FRACTION 0.05 --ALLELE_FRACTION 0.1 --ALLELE_FRACTION 0.2 --ALLELE_FRACTION 0.3 --ALLELE_FRACTION 0.5 --READ_LENGTH 150 --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 8 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
Sep 16, 2019 2:33:15 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
[Mon Sep 16 02:33:15 UTC 2019] Executing as user@server on Linux 3.10.0-693.21.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_192-b01; Deflater: Intel; Inflater: Intel; Provider GCS is available; Picard version: Version:4.1.3.0
[Mon Sep 16 02:33:22 UTC 2019] picard.analysis.CollectWgsMetrics done. Elapsed time: 0.16 minutes.
Runtime.totalMemory()=6996099072
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
java.lang.IllegalArgumentException: The requested position is not covered by this StartEdgingRecordAndOffset object.
        at htsjdk.samtools.util.AbstractRecordAndOffset.validateOffset(AbstractRecordAndOffset.java:109)
        at htsjdk.samtools.util.EdgingRecordAndOffset$StartEdgingRecordAndOffset.getBaseQuality(EdgingRecordAndOffset.java:112)
        at picard.analysis.FastWgsMetricsCollector.excludeByQuality(FastWgsMetricsCollector.java:189)
        at picard.analysis.FastWgsMetricsCollector.processRecord(FastWgsMetricsCollector.java:144)
        at picard.analysis.FastWgsMetricsCollector.addInfo(FastWgsMetricsCollector.java:105)
        at picard.analysis.WgsMetricsProcessorImpl.processFile(WgsMetricsProcessorImpl.java:93)
        at picard.analysis.CollectWgsMetrics.doWork(CollectWgsMetrics.java:231)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:25)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
        at org.broadinstitute.hellbender.Main.main(Main.java:291)
Using GATK jar /opt/conda/envs/base-v1.4.1/share/gatk4-4.1.3.0-0/gatk-package-4.1.3.0-local.jar defined in environment variable GATK_LOCAL_JAR
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=8 -Xms6G -Xmx10G -Djava.io.tmpdir=. -jar /opt/conda/envs/base-v1.4.1/share/gatk4-4.1.3.0-0/gatk-package-4.1.3.0-local.jar CollectWgsMetrics --INPUT=example.bam --OUTPUT=example.seq_metrics.txt --REFERENCE_SEQUENCE=ucsc.hg19.fasta --USE_FAST_ALGORITHM=true --LOCUS_ACCUMULATION_CAP 25000 --COVERAGE_CAP=100
```

**Comment by flexray** [comment]
I can confirm that, GATK 4.1.3.0 with CollectRawWgsMetrics

```
picard -Xms4000m \
  CollectRawWgsMetrics \
  INPUT=example.bam
  VALIDATION_STRINGENCY=SILENT \
  REFERENCE_SEQUENCE=Homo_sapiens_assembly38.fasta \
  INCLUDE_BQ_HISTOGRAM=true \
  INTERVALS=wgs_coverage_regions.hg38.interval_list \
  OUTPUT=example.raw_wgs_metrics \
  USE_FAST_ALGORITHM=true \
  READ_LENGTH=250
```

**Output:**
```
18:48:46.330 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/local/share/picard-2.20.7-0/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Fri Sep 20 18:48:46 GMT 2019] CollectRawWgsMetrics INPUT=example.bam
[Fri Sep 20 18:48:46 GMT 2019] Executing as root@98e13b9f4ef1 on Linux 4.19.44+ amd64; OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.20.7-SNAPSHOT
[Fri Sep 20 18:49:00 GMT 2019] picard.analysis.CollectRawWgsMetrics done. Elapsed time: 0.24 minutes.
Runtime.totalMemory()=4054515712
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalArgumentException: The requested position is not covered by this StartEdgingRecordAndOffset object.
        at htsjdk.samtools.util.AbstractRecordAndOffset.validateOffset(AbstractRecordAndOffset.java:146)
        at htsjdk.samtools.util.EdgingRecordAndOffset$StartEdgingRecordAndOffset.getBaseQuality(EdgingRecordAndOffset.java:112)
        at picard.analysis.FastWgsMetricsCollector.excludeByQuality(FastWgsMetricsCollector.java:189)
        at picard.analysis.FastWgsMetricsCollector.processRecord(FastWgsMetricsCollector.java:144)
        at picard.analysis.FastWgsMetricsCollector.addInfo(FastWgsMetricsCollector.java:105)
        at picard.analysis.WgsMetricsProcessorImpl.processFile(WgsMetricsProcessorImpl.java:93)
        at picard.analysis.CollectWgsMetrics.doWork(CollectWgsMetrics.java:231)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```

**Comment by flexray** [comment]
Seems like last working Picard version is
'''
Picard version: 2.20.4-SNAPSHOT
'''
