### ISSUE TITLE
Funcotator shuts down

### ISSUE THREAD

**Issue by rdbremel** [broadinstitute/gatk#6182]
### Affected tool(s) or class(es)
docker version GATK:4.1.1.0

### Affected version(s)
 
latest release

### Description 
Funcotator shuts down part way through job.  A configuration problem @ google?
[funcotator_crash.txt](https://github.com/broadinstitute/gatk/files/3652568/funcotator_crash.txt)

 RuntimeException: java.util.concurrent.ExecutionException: com.google.cloud.storage.StorageException: www.googleapis.com
  
### Description 

04:13:19.667 INFO  ProgressMeter -          15:85753672           1834.2                199000            108.5
04:17:42.593 INFO  VcfFuncotationFactory - dbSNP 9606_b150 cache hits/total: 0/0
04:17:42.593 INFO  VcfFuncotationFactory - gnomAD_exome 2.1 cache hits/total: 0/1402
04:17:42.593 INFO  VcfFuncotationFactory - gnomAD_genome 2.1 cache hits/total: 0/162233
04:17:42.665 INFO  Funcotator - Shutting down engine
[September 25, 2019 4:17:42 AM UTC] org.broadinstitute.hellbender.tools.funcotator.Funcotator done. Elapsed time: 1,845.78 minutes.
Runtime.totalMemory()=4523032576
java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.cloud.storage.StorageException: www.googleapis.com
        at org.broadinstitute.hellbender.utils.nio.SeekableByteChannelPrefetcher.read(SeekableByteChannelPrefetcher.java:318)
        at htsjdk.samtools.seekablestream.SeekablePathStream.read(SeekablePathStream.java:86)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)

**Comment by rdbremel** [comment]
I got it to work by using the runtime switch  --disable-sequence-dictionary-validation 

 

If that is not used it crashes.  

 

Docker commandline

 

/gatk Funcotator  --disable-sequence-dictionary-validation  \

-R mydata/refs/Homo_sapiens_assembly19.fasta \

-V mydata/P50513_mutect2_filtered.vcf   \

-O mydata/P50513_mutect2_funcotator.maf \

--output-file-format MAF  \

--data-sources-path mydata/dataSourcesFolder/funcotator_dataSources.v1.6.20190124s/ --ref-version hg19

**Comment by lbergelson** [comment]
Very strange.  We should look into that.

**Comment by rdbremel** [comment]
As I recall I put that switch in because the error log seemed to suggest that is the point at which it ran out of allocated memory.

**Comment by lbergelson** [comment]
Can you point out where in the log you see that?  I'm looking at it but I don't see anything about memory in the log you provided.  (Except the Runtime.totalMemory()=4523032576 which is just standard output spam from gatk when it shutsdown)   Sequence dictionary validation usually happens first, it's strange that a failure in the middle of a run would be effected by it.  I'm no very curious what weird thing is happening that's causing this...

**Comment by rdbremel** [comment]
I’m sorry I wasn’t really keeping a good trail of the errors and it was a few weeks ago and I have been doing other stuff.  

 

I have a notation in my log about the run time switch and I seem to have gotten the notion about using it from reading stuff in one of the tutorials or on the forum.  I gotta admit I am clueless about what the dictionary validation is actually doing so it wouldn’t have been anything that I conjured up on my own.

**Comment by lbergelson** [comment]
Very reasonable to not have old records of weird failures.  If you run into that out of memory from the index, open a new ticket so we can look into that as well?    

@droazen This looks like something that should be being retried, but isn't.   Any thoughts on potentially missing retry logic?

**Comment by droazen** [comment]
@lbergelson The underlying cause appears to be a `java.net.UnknownHostException: www.googleapis.com`. Haven't we encountered that error in the past on GCS? @jean-philippe-martin ?

**Comment by lbergelson** [comment]
I thought we'd added that to the retry list.

**Comment by jean-philippe-martin** [comment]
Yes, the same error message was reported in https://github.com/broadinstitute/gatk/issues/5094. It was supposedly fixed by a patch to the Pipelines API.

GCS-NIO has support for a list of retriable codes in the `CloudStorageConfiguration`, see there:

https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageConfiguration.java

I think GATK calls this somewhere. It certainly should.

**Comment by rdbremel** [comment]
Not sure they are related but I noted a couple of other mysteries.  

 

I am running the Docker version of GATK on a high end windows workstation and have allocated about 30GB to Docker.

 

Mystery 1:  I get a warning on some commands that it is unable to determine whether it is running on google.  Related to the Funcotator issue perhaps if it can’t determine where it is running it crashes out?

 

Mystery 2:  CollectAllelicCounts crashes with a java memory error.  The -Xmx5g is several multiples of the recommendation.

 

gatk --java-options "-Xmx5g" CollectAllelicCounts  -L mydata/refs/hg19_intervals.interval_list  -I mydata/P50513/Tumor_P50513_2.bam -R mydata/refs/Homo_sapiens_assembly19.fasta -O mydata/P50513/P50513_Tumor.allelicCounts.tsv  

                

20:31:39.543 INFO  ProgressMeter -          1:169308662             59.1              85227000        1443218.8

20:32:01.576 INFO  ProgressMeter -          1:169321662             59.4              85240000        1434518.9

20:32:22.203 INFO  ProgressMeter -          1:169334662             59.8              85253000        1426484.3

20:32:43.007 INFO  ProgressMeter -          1:169341665             60.1              85260000        1418372.5

20:33:04.435 INFO  ProgressMeter -          1:169350665             60.5              85269000        1410144.2

20:33:29.473 INFO  CollectAllelicCounts - Shutting down engine

[October 5, 2019 8:33:29 PM UTC] org.broadinstitute.hellbender.tools.copynumber.CollectAllelicCounts done. Elapsed time: 60.94 minutes.

Runtime.totalMemory()=5,285,347,328

 

 

Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded

 

 

        at java.util.Collections.unmodifiableList(Collections.java:1287)

        at htsjdk.samtools.Cigar.getCigarElements(Cigar.java:54)

        at org.broadinstitute.hellbender.utils.read.SAMRecordToGATKReadAdapter.getCigarElements(SAMRecordToGATKReadAdapter.java:336)

        at org.broadinstitute.hellbender.engine.filters.ReadFilterLibrary$ReadLengthEqualsCigarLengthReadFilter.test(ReadFilterLibrary.java:217)

        at org.broadinstitute.hellbender.engine.filters.ReadFilter$ReadFilterAnd.test(ReadFilter.java:70)

        at org.broadinstitute.hellbender.engine.filters.ReadFilter$ReadFilterAnd.test(ReadFilter.java:70)

        at org.broadinstitute.hellbender.engine.filters.ReadFilter$ReadFilterAnd.test(ReadFilter.java:70)

        at org.broadinstitute.hellbender.engine.filters.WellformedReadFilter.test(WellformedReadFilter.java:77)

        at org.broadinstitute.hellbender.engine.filters.CountingReadFilter.test(CountingReadFilter.java:126)

**Comment by jean-philippe-martin** [comment]
@rdbremel for "mystery 1" see issue #5447. This should be an innocuous warning that it can't initialize the Google Cloud Storage code and shouldn't cause a failure unless you try to access paths that start with "gs://". Going through the Cloud initialization steps described in the README should remove the warning (though again, this isn't required if you don't need to read files from the cloud).

Mystery 2: For what it's worth, "GC overhead limit exceeded" indicates that the VM was spending too much time in GC. Running low on memory is a possible cause but generating too many small objects or being stuck in an infinite loop of allocation/deallocation are others. In the past these have been caused by inputs that were malformed in some way. This isn't the place for this discussion though, please file a separate issue since it's a separate bug.

**Comment by rdbremel** [comment]
Thanx for feedback

I obviously don’t know much if anything  about the underlying logic but
have had enough experience to look in unusual places

Have a good weekend.

RDB
