### ISSUE TITLE
Error while using somatic CNV in wdl

### ISSUE THREAD

**Issue by SaraAlthubaiti** [broadinstitute/gatk#6189]
Hi gatk team,

I'm working with generating CNV for somatic with wdl, using this command:

`java -Xmx75G -Dconfig.file=gatk.conf -jar cromwell-46.1.jar run cnv_somatic_panel_workflow.wdl -i parameters.json `

But I got this error in which I don't know the exact reason for it:

```
[2019-10-01 02:52:52,49] [info] Running with database db.url = jdbc:hsqldb:mem:e98d186c-96db-46ae-92e5-c326e7aa05d9;shutdown=false;hsqldb.tx=mvcc
[2019-10-01 02:53:01,19] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2019-10-01 02:53:01,20] [info] [RenameWorkflowOptionsInMetadata] 100%
[2019-10-01 02:53:01,31] [info] Running with database db.url = jdbc:hsqldb:mem:c4b3296a-4b73-4053-b6bf-d4eeb71c8956;shutdown=false;hsqldb.tx=mvcc
[2019-10-01 02:53:01,85] [info] Slf4jLogger started
[2019-10-01 02:53:02,22] [info] Workflow heartbeat configuration:
{
  "cromwellId" : "cromid-876ccf5",
  "heartbeatInterval" : "2 minutes",
  "ttl" : "10 minutes",
  "failureShutdownDuration" : "5 minutes",
  "writeBatchSize" : 10000,
  "writeThreshold" : 10000
}
[2019-10-01 02:53:02,28] [info] Metadata summary refreshing every 1 second.
[2019-10-01 02:53:02,31] [info] KvWriteActor configured to flush with batch size 200 and process rate 5 seconds.
[2019-10-01 02:53:02,31] [info] WriteMetadataActor configured to flush with batch size 200 and process rate 5 seconds.
[2019-10-01 02:53:02,32] [info] CallCacheWriteActor configured to flush with batch size 100 and process rate 3 seconds.
[2019-10-01 02:53:02,32] [warn] 'docker.hash-lookup.gcr-api-queries-per-100-seconds' is being deprecated, use 'docker.hash-lookup.gcr.throttle' instead (see reference.conf)
[2019-10-01 02:53:02,40] [info] JobExecutionTokenDispenser - Distribution rate: 50 per 1 seconds.
[2019-10-01 02:53:02,43] [info] SingleWorkflowRunnerActor: Version 46.1
[2019-10-01 02:53:02,44] [info] SingleWorkflowRunnerActor: Submitting workflow
[2019-10-01 02:53:02,49] [info] Unspecified type (Unspecified version) workflow c55a06f3-abc1-4db1-8e0f-ea0303caab2c submitted
[2019-10-01 02:53:02,51] [info] SingleWorkflowRunnerActor: Workflow submitted c55a06f3-abc1-4db1-8e0f-ea0303caab2c
[2019-10-01 02:53:02,51] [info] 1 new workflows fetched by cromid-876ccf5: c55a06f3-abc1-4db1-8e0f-ea0303caab2c
[2019-10-01 02:53:02,52] [info] WorkflowManagerActor Starting workflow c55a06f3-abc1-4db1-8e0f-ea0303caab2c
[2019-10-01 02:53:02,53] [info] WorkflowManagerActor Successfully started WorkflowActor-c55a06f3-abc1-4db1-8e0f-ea0303caab2c
[2019-10-01 02:53:02,53] [info] Retrieved 1 workflows from the WorkflowStoreActor
[2019-10-01 02:53:02,55] [info] WorkflowStoreHeartbeatWriteActor configured to flush with batch size 10000 and process rate 2 minutes.
[2019-10-01 02:53:02,64] [info] MaterializeWorkflowDescriptorActor [c55a06f3]: Parsing workflow as WDL draft-2
[2019-10-01 02:53:03,80] [info] WorkflowManagerActor Workflow c55a06f3-abc1-4db1-8e0f-ea0303caab2c failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
Failed to evaluate input 'padding' (reason 1 of 1): For input string: "Int? (optional)"
Failed to evaluate input 'minimum_interval_median_percentile' (reason 1 of 1): For input string: "Float? (optional)"
Failed to evaluate input 'maximum_zeros_in_interval_percentage' (reason 1 of 1): For input string: "Float? (optional)"
Failed to evaluate input 'maximum_chunk_size' (reason 1 of 1): For input string: "Int? (optional)"
Failed to evaluate input 'AnnotateIntervals.use_ssd' (reason 1 of 1): No coercion defined from '"Boolean (optional, default = false)"' of type 'spray.json.JsString' to 'Boolean'.
Failed to evaluate input 'PreprocessIntervals.use_ssd' (reason 1 of 1): No coercion defined from '"Boolean (optional, default = false)"' of type 'spray.json.JsString' to 'Boolean'.
Failed to evaluate input 'mem_gb_for_preprocess_intervals' (reason 1 of 1): For input string: "Int? (optional)"
Failed to evaluate input 'AnnotateIntervals.disk_space_gb' (reason 1 of 1): For input string: "Int? (optional)"
Failed to evaluate input 'extreme_outlier_truncation_percentile' (reason 1 of 1): For input string: "Float? (optional)"
Failed to evaluate input 'CreateReadCountPanelOfNormals.disk_space_gb' (reason 1 of 1): For input string: "Int? (optional)"
Failed to evaluate input 'CreateReadCountPanelOfNormals.use_ssd' (reason 1 of 1): No coercion defined from '"Boolean (optional, default = false)"' of type 'spray.json.JsString' to 'Boolean'.
Failed to evaluate input 'preemptible_attempts' (reason 1 of 1): For input string: "Int? (optional)"
Failed to evaluate input 'PreprocessIntervals.cpu' (reason 1 of 1): For input string: "Int? (optional)"
Failed to evaluate input 'CollectCounts.use_ssd' (reason 1 of 1): No coercion defined from '"Boolean (optional, default = false)"' of type 'spray.json.JsString' to 'Boolean'.
Failed to evaluate input 'do_explicit_gc_correction' (reason 1 of 1): No coercion defined from '"Boolean? (optional)"' of type 'spray.json.JsString' to 'Boolean?'.
Failed to evaluate input 'maximum_zeros_in_sample_percentage' (reason 1 of 1): For input string: "Float? (optional)"
Failed to evaluate input 'mem_gb_for_collect_counts' (reason 1 of 1): For input string: "Int? (optional)"
Failed to evaluate input 'mem_gb_for_annotate_intervals' (reason 1 of 1): For input string: "Int? (optional)"
Failed to evaluate input 'number_of_eigensamples' (reason 1 of 1): For input string: "Int? (optional)"
Failed to evaluate input 'AnnotateIntervals.cpu' (reason 1 of 1): For input string: "Int? (optional)"
Failed to evaluate input 'CreateReadCountPanelOfNormals.cpu' (reason 1 of 1): For input string: "Int? (optional)"
Failed to evaluate input 'mem_gb_for_create_read_count_pon' (reason 1 of 1): For input string: "Int? (optional)"
Failed to evaluate input 'do_impute_zeros' (reason 1 of 1): No coercion defined from '"Boolean? (optional)"' of type 'spray.json.JsString' to 'Boolean?'.
Failed to evaluate input 'CollectCounts.disk_space_gb' (reason 1 of 1): For input string: "Int? (optional)"
Failed to evaluate input 'CollectCounts.cpu' (reason 1 of 1): For input string: "Int? (optional)"
Failed to evaluate input 'bin_length' (reason 1 of 1): For input string: "Int? (optional)"
Failed to evaluate input 'PreprocessIntervals.disk_space_gb' (reason 1 of 1): For input string: "Int? (optional)"
Failed to evaluate input 'feature_query_lookahead' (reason 1 of 1): For input string: "Int? (optional)"
Failed to evaluate input 'extreme_sample_median_percentile' (reason 1 of 1): For input string: "Float? (optional)"
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:235)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:205)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:200)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at akka.actor.FSM.processEvent(FSM.scala:707)
	at akka.actor.FSM.processEvent$(FSM.scala:704)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:156)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:847)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:829)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescriptorActor.scala:156)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:701)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:695)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:156)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
	at akka.actor.ActorCell.invoke(ActorCell.scala:581)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[2019-10-01 02:53:03,81] [info] WorkflowManagerActor WorkflowActor-c55a06f3-abc1-4db1-8e0f-ea0303caab2c is in a terminal state: WorkflowFailedState
[2019-10-01 02:53:07,42] [info] Not triggering log of token queue status. Effective log interval = None
[2019-10-01 02:53:08,41] [info] SingleWorkflowRunnerActor workflow finished with status 'Failed'.
[2019-10-01 02:53:12,32] [info] Workflow polling stopped
[2019-10-01 02:53:12,33] [info] 0 workflows released by cromid-876ccf5
[2019-10-01 02:53:12,34] [info] Shutting down WorkflowStoreActor - Timeout = 5 seconds
[2019-10-01 02:53:12,34] [info] Shutting down WorkflowLogCopyRouter - Timeout = 5 seconds
[2019-10-01 02:53:12,34] [info] Shutting down JobExecutionTokenDispenser - Timeout = 5 seconds
[2019-10-01 02:53:12,34] [info] Aborting all running workflows.
[2019-10-01 02:53:12,34] [info] JobExecutionTokenDispenser stopped
[2019-10-01 02:53:12,35] [info] WorkflowStoreActor stopped
[2019-10-01 02:53:12,35] [info] WorkflowLogCopyRouter stopped
[2019-10-01 02:53:12,35] [info] Shutting down WorkflowManagerActor - Timeout = 3600 seconds
[2019-10-01 02:53:12,35] [info] WorkflowManagerActor All workflows finished
[2019-10-01 02:53:12,35] [info] WorkflowManagerActor stopped
[2019-10-01 02:53:12,65] [info] Connection pools shut down
[2019-10-01 02:53:12,65] [info] Shutting down SubWorkflowStoreActor - Timeout = 1800 seconds
[2019-10-01 02:53:12,65] [info] Shutting down JobStoreActor - Timeout = 1800 seconds
[2019-10-01 02:53:12,65] [info] Shutting down CallCacheWriteActor - Timeout = 1800 seconds
[2019-10-01 02:53:12,65] [info] Shutting down ServiceRegistryActor - Timeout = 1800 seconds
[2019-10-01 02:53:12,65] [info] SubWorkflowStoreActor stopped
[2019-10-01 02:53:12,65] [info] Shutting down DockerHashActor - Timeout = 1800 seconds
[2019-10-01 02:53:12,65] [info] CallCacheWriteActor Shutting down: 0 queued messages to process
[2019-10-01 02:53:12,66] [info] WriteMetadataActor Shutting down: 0 queued messages to process
[2019-10-01 02:53:12,66] [info] KvWriteActor Shutting down: 0 queued messages to process
[2019-10-01 02:53:12,66] [info] JobStoreActor stopped
[2019-10-01 02:53:12,66] [info] Shutting down IoProxy - Timeout = 1800 seconds
[2019-10-01 02:53:12,66] [info] CallCacheWriteActor stopped
[2019-10-01 02:53:12,66] [info] IoProxy stopped
[2019-10-01 02:53:12,66] [info] ServiceRegistryActor stopped
[2019-10-01 02:53:12,67] [info] DockerHashActor stopped
[2019-10-01 02:53:12,69] [info] Database closed
[2019-10-01 02:53:12,69] [info] Stream materializer shut down
[2019-10-01 02:53:12,69] [info] WDL HTTP import resolver closed
Workflow c55a06f3-abc1-4db1-8e0f-ea0303caab2c transitioned to state Failed
```

Any help will be much appreciated.

Thanks.

**Comment by samuelklee** [comment]
@SaraAlthubaiti It looks like you need to either remove the lines corresponding to optional parameters from your `parameters.json` file or populate them with appropriate values.

The support forums at https://gatkforums.broadinstitute.org/ are a better place for getting help with running the tools and diagnosing exceptions. GitHub issues should be reserved for bug reports and feature requests.
