### ISSUE TITLE
NullPointerException error while running VariantEval

### ISSUE THREAD

**Issue by justin-mbca** [broadinstitute/gatk#6212]
**Command**
`gatk VariantEval -eval SimpleExample.vcf.gz -O output_gatk_variantEval.txt`

I got the following error
```
   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

   Warning: VariantEval is a BETA tool and is not yet ready for use in production

   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


14:37:10.767 INFO  VariantEval - Initializing engine
14:37:11.138 INFO  FeatureManager - Using codec VCFCodec to read file file:///Users/justinzhang/daiichi/SimpleExample.vcf.gz
14:37:11.268 INFO  VariantEval - Done initializing engine
14:37:11.278 INFO  VariantEval - Creating 3 combinatorial stratification states
14:37:11.281 INFO  ProgressMeter - Starting traversal
14:37:11.282 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
14:37:11.454 INFO  ProgressMeter -             unmapped              0.0                   250          87719.3
14:37:11.454 INFO  ProgressMeter - Traversal complete. Processed 250 total variants in 0.0 minutes.
14:37:11.454 INFO  VariantEval - Finalizing variant report
14:37:11.455 INFO  VariantEval - Shutting down engine
[October 11, 2019 2:37:11 PM EDT] org.broadinstitute.hellbender.tools.walkers.varianteval.VariantEval done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=386924544
**java.lang.NullPointerException**
	at org.broadinstitute.hellbender.tools.walkers.varianteval.VariantEval.getnProcessedLoci(VariantEval.java:822)
	at org.broadinstitute.hellbender.tools.walkers.varianteval.evaluators.CountVariants.finalizeEvaluation(CountVariants.java:184)
	at org.broadinstitute.hellbender.tools.walkers.varianteval.VariantEval.onTraversalSuccess(VariantEval.java:709)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1050)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
	at org.broadinstitute.hellbender.Main.main(Main.java:292)
```

Any help would be very appreciated!

Justin

**Comment by lbergelson** [comment]
You found a bug!  It looks like the code is expecting a reference or interval to be provided and since there wasn't one it's falling over.  This is definitely a bug and we'll try to fix it for the next release.  In the mean time, providing an interval or reference will allow it to run.

**Comment by lbergelson** [comment]
@droazen I responded to your comments.  This is way to much code to deal with this trivial edge case, but now it's *Done Right™*
