### ISSUE TITLE
Funcotator user-defined data source Error

### ISSUE THREAD

**Issue by bhanugandham** [broadinstitute/gatk#6223]
Hi, recently I was trying expand the annotation data source when using funcotator, however, the document didn't give much information or example. Now I was trying to add CADD to the data source folder. After running the funcotator, I got the error:<br />
<br />
org.broadinstitute.hellbender.exceptions.GATKException: Error initializing feature reader for path file: funcotator_dataSources.v1.6.20190124s/cadd/hg19/cadd.config<br />
        at org.broadinstitute.hellbender.engine.FeatureDataSource.getTribbleFeatureReader(FeatureDataSource.java:353)<br />
        at org.broadinstitute.hellbender.engine.FeatureDataSource.getFeatureReader(FeatureDataSource.java:305)<br />
        at org.broadinstitute.hellbender.engine.FeatureDataSource.&lt;init&gt;(FeatureDataSource.java:256)<br />
        at org.broadinstitute.hellbender.engine.FeatureManager.addToFeatureSources(FeatureManager.java:234)<br />
        at org.broadinstitute.hellbender.engine.GATKTool.addFeatureInputsAfterInitialization(GATKTool.java:957)<br />
        at org.broadinstitute.hellbender.tools.funcotator.dataSources.DataSourceUtils.createAndRegisterFeatureInputs(DataSourceUtils.java:328)<br />
        at org.broadinstitute.hellbender.tools.funcotator.dataSources.DataSourceUtils.createDataSourceFuncotationFactoriesForDataSources(DataSourceUtils.java:277)<br />
        at org.broadinstitute.hellbender.tools.funcotator.Funcotator.onTraversalStart(Funcotator.java:774)<br />
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1037)<br />
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)<br />
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)<br />
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)<br />
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)<br />
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)<br />
        at org.broadinstitute.hellbender.Main.main(Main.java:291)<br />
Caused by: htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: Duplicate key 0, for input source: cadd.config<br />
        at htsjdk.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:263)<br />
        at htsjdk.tribble.TribbleIndexedFeatureReader.&lt;init&gt;(TribbleIndexedFeatureReader.java:102)<br />
        at htsjdk.tribble.TribbleIndexedFeatureReader.&lt;init&gt;(TribbleIndexedFeatureReader.java:127)<br />
        at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:120)<br />
        at org.broadinstitute.hellbender.engine.FeatureDataSource.getTribbleFeatureReader(FeatureDataSource.java:350)<br />
        ... 14 more<br />
Caused by: java.lang.IllegalStateException: Duplicate key 0<br />
        at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)<br />
        at java.util.HashMap.merge(HashMap.java:1254)<br />
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)<br />
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)<br />
        at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)<br />
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)<br />
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)<br />
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)<br />
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)<br />
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)<br />
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br />
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)<br />
        at org.broadinstitute.hellbender.utils.codecs.xsvLocatableTable.XsvLocatableTableCodec.readActualHeader(XsvLocatableTableCodec.java:341)<br />
        at org.broadinstitute.hellbender.utils.codecs.xsvLocatableTable.XsvLocatableTableCodec.readActualHeader(XsvLocatableTableCodec.java:64)<br />
        at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:79)<br />
        at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:37)<br />
        at htsjdk.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:261)<br />
        ... 18 more<br />
<br />
java version:<br />
java -version<br />
       openjdk version "1.8.0_222"<br />
        OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1~deb9u1-b10)<br />
        OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)<br />
<br />
I added the cadd folder into data source folder like the structure mentioned in document:<br />
<br />
cadd<br />
|- hg19<br />
|  |- cadd.config<br />
|  |- InDels_inclAnno.tsv<br />
|  |- InDels_inclAnno.tsv.gz.tbi<br />
|<br />
|- hg38<br />
|  |- cadd.config<br />
|  |- InDels_inclAnno.tsv<br />
|  |- InDels_inclAnno.tsv.gz.tbi<br />
<br />
The config file (cadd.config)<br />
<br />
name = CADD<br />
version = v1.4<br />
src_file = InDels_inclAnno.tsv<br />
origin_location =<br />
preprocessing_script = UNKNOWN<br />
<br />
# Whether this data source is for the b37 reference.<br />
# Required and defaults to false.<br />
isB37DataSource = false<br />
<br />
# Supported types:<br />
# simpleXSV    -- Arbitrary separated value table (e.g. CSV), keyed off Gene Name OR Transcript ID<br />
# locatableXSV -- Arbitrary separated value table (e.g. CSV), keyed off a genome location<br />
# gencode      -- Custom datasource class for GENCODE<br />
#       cosmic       -- Custom datasource class for COSMIC<br />
# vcf          -- Custom datasource class for Variant Call Format (VCF) files<br />
type = locatableXSV<br />
<br />
# Required field for GENCODE files.<br />
# Path to the FASTA file from which to load the sequences for GENCODE transcripts:<br />
gencode_fasta_path =<br />
<br />
# Required field for GENCODE files.<br />
# NCBI build version (either hg19 or hg38):<br />
ncbi_build_version =<br />
<br />
# Required field for simpleXSV files.<br />
# Valid values:<br />
#     GENE_NAME<br />
#     TRANSCRIPT_ID<br />
xsv_key = GENE_NAME<br />
<br />
# Required field for simpleXSV files.<br />
# The 0-based index of the column containing the key on which to match<br />
xsv_key_column =<br />
<br />
# Required field for simpleXSV AND locatableXSV files.<br />
# The delimiter by which to split the XSV file into columns.<br />
xsv_delimiter = \t<br />
<br />
# Required field for simpleXSV files.<br />
# Whether to permissively match the number of columns in the header and data rows<br />
# Valid values:<br />
#     true<br />
#     false<br />
xsv_permissive_cols =<br />
<br />
# Required field for locatableXSV files.<br />
# The 0-based index of the column containing the contig for each row<br />
contig_column = 0<br />
<br />
# Required field for locatableXSV files.<br />
# The 0-based index of the column containing the start position for each row<br />
start_column = 1<br />
<br />
# Required field for locatableXSV files.<br />
# The 0-based index of the column containing the end position for each row<br />
end_column = 1<br />
<br />
A snapshot of InDels_inclAnno.tsv:<br />
Chrom  Pos     Ref     Alt     Type    Length  AnnoType        Consequence     ConsScore       ConsDetail      GC      CpG     motifECount     motifEName<br />
      motifEHIPos     motifEScoreChng oAA     nAA     GeneID  FeatureID       GeneName        CCDS    Intron  Exon    cDNApos relcDNApos      CDSpos  relCDSpo<br />
s       protPos relProtPos      Domain  Dst2Splice      Dst2SplType     minDistTSS      minDistTSE      SIFTcat SIFTval PolyPhenCat     PolyPhenVal     priPhC<br />
ons       mamPhCons       verPhCons       priPhyloP       mamPhyloP       verPhyloP       bStatistic      targetScan      mirSVR-Score    mirSVR-E        mirS<br />
VR-Aln      cHmm_E1 cHmm_E2 cHmm_E3 cHmm_E4 cHmm_E5 cHmm_E6 cHmm_E7 cHmm_E8 cHmm_E9 cHmm_E10        cHmm_E11        cHmm_E12        cHmm_E13        cHmm_E14<br />
        cHmm_E15        cHmm_E16        cHmm_E17        cHmm_E18        cHmm_E19        cHmm_E20        cHmm_E21        cHmm_E22        cHmm_E23        cHmm_E<br />
24        cHmm_E25        GerpRS  GerpRSpval      GerpN   GerpS   tOverlapMotifs  motifDist       EncodeH3K4me1-sum       EncodeH3K4me1-max       EncodeH3K4me<br />
2-sum       EncodeH3K4me2-max       EncodeH3K4me3-sum       EncodeH3K4me3-max       EncodeH3K9ac-sum        EncodeH3K9ac-max        EncodeH3K9me3-sum       En<br />
codeH3K9me3-max       EncodeH3K27ac-sum       EncodeH3K27ac-max       EncodeH3K27me3-sum      EncodeH3K27me3-max      EncodeH3K36me3-sum      EncodeH3K36me3-m<br />
ax      EncodeH3K79me2-sum      EncodeH3K79me2-max      EncodeH4K20me1-sum      EncodeH4K20me1-max      EncodeH2AFZ-sum EncodeH2AFZ-max EncodeDNase-sum Encode<br />
DNase-max EncodetotalRNA-sum      EncodetotalRNA-max      Grantham        Dist2Mutation   Freq100bp       Rare100bp       Sngl100bp       Freq1000bp      Rare<br />
1000bp      Sngl1000bp      Freq10000bp     Rare10000bp     Sngl10000bp     EnsembleRegulatoryFeature       dbscSNV-ada_score       dbscSNV-rf_score        Re<br />
mapOverlapTF  RemapOverlapCL  RawScore        PHRED<br />
<br />
1       10001   T       TC      INS     1       RegulatoryFeature       REGULATORY      4       regulatory      0.448933333333  0.00993288590604        NA<br />
      NA      NA      NA      NA      NA      NA      ENSR00000344265 NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      1869    3670    NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      994     NA      NA      NA      NA      0.008   0.000   0.000   0.000   0.016   0.000   0.024   0.087   0.472   0.000   0.000   0.000   0.000   0.000   0.394   NA      NA      0       0       NA      NA<br />
      NA      NA      NA      GM1     10.04   2.84    8.0     NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      2773    NA      NA      NA      NA      NA      NA      3       2       32      NA      NA      -0.083014       1.567<br />
<br />
The funcotator command:<br />
gatk Funcotator \<br />
&gt; --variant TriLevelv2_bqsr-filtered.vcf \<br />
&gt; --output test_cadd.vcf \<br />
&gt; --reference hg19.fa \<br />
&gt; --data-sources-path /funcotator_dataSources.v1.6.20190124s \<br />
&gt; --ref-version hg19 \<br />
&gt; --output-file-format VCF \<br />
&gt; --java-options '-DGATK_STACKTRACE_ON_USER_EXCEPTION=true' \<br />
&gt; --verbosity DEBUG \<br />
&gt; --disable-sequence-dictionary-validation true \<br />
&gt; --disable-bam-index-caching true<br />
<br />
I am not sure what I missed here, although I am not quite sure about how should to add new data sources. Sincerely appreciate your help!

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/24521/funcotator-user-defined-data-sources/p1

**Comment by bhanugandham** [comment]
HI @jonn-smith 
Creating this issue ticket as discussed. 
Issue: The header of that particular file has a hash mark # before it, because of that the parser wont work properly. A bug seems to have been introduced in the tribble indexing code for TSV files.

**Comment by jonn-smith** [comment]
There were a few issues with this case.

First, the data source was not constructed 100% correctly.  The config file is correct. 

The index file is for the tar.gz version of the source data and not for the uncompressed version that they're using.  The index should correspond to the source data in the file referenced by the config file itself (not a zipped or otherwise transformed version).

Secondly, the source `tsv` data file has the header line for the table commented out.  The Xsv codec is aware of leading hash marks as comments and will ignore any such lines.  Because of this, the leading hash in the table header is ignored and the file cannot be properly parsed.  The fix is simple - just remove the leading hash from the table header (the preceding line with the two hash marks is correctly interpreted as a file header because of the leading hashes acting as comments).

Lastly, even if the user fixed the file they would still need to index it with`IndexFeatureFile`.  At some point the code underlying this in `HTSJDK` was broken such that no Xsv files can currently be indexed.  I have submitted a pull request in `HTSJDK` (https://github.com/samtools/htsjdk/pull/1429) for this and have another ready to go in GATK (#6224) that includes a test for this case so this reversion cannot happen again.

**Comment by cmnbroad** [comment]
@jonn-smith I tried running this with the proposed htsjdk change (since I'm unclear on whats broken there exactly), but the new test you added here seems to fail even with that change.

**Comment by cmnbroad** [comment]
Also, I'm trying to determine if this might be fixed by (and motivate the speeding up of) the fix for https://github.com/broadinstitute/gatk/issues/6161.

**Comment by lbergelson** [comment]
@cmnbroad I think now might be a good time to fix #6161 but it's not sufficient to fix this.  When I added the ability to redirect things in the codec I obviously didn't do a complete job of hitting every spot in the code.  I suspect there may be other places that aren't redirecting correctly as well.
 
I would like to clean up some of the code in the IndexFactory as well.  I'll probably open a small pr for that that removes some ancient bad reflection code.

**Comment by Schahrjar** [comment]
I encountered a similar error while using UniProt variants BED file, available here: [Uniprot FTP](ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/genome_annotation_tracks/UP000005640_9606_beds/UP000005640_9606_variants.bed).

I indexed the BED file (using GATK IndexFeatureFile), but the problem not resolved.

Below is the config:
`name = UniProt
version = 2020_03
src_file = UP000005640_9606_variants.bed
origin_location =
preprocessing_script =

# Whether this data source is for the b37 reference.
# Required and defaults to false.
isB37DataSource = false

# Supported types:
# simpleXSV    -- Arbitrary separated value table (e.g. CSV), keyed off Gene Name OR Transcript ID
# locatableXSV -- Arbitrary separated value table (e.g. CSV), keyed off a genome location
# gencode      -- Custom datasource class for GENCODE
#	cosmic       -- Custom datasource class for COSMIC
# vcf          -- Custom datasource class for Variant Call Format (VCF) files
type = locatableXSV

# Required field for GENCODE files.
# Path to the FASTA file from which to load the sequences for GENCODE transcripts:
gencode_fasta_path =

# Required field for GENCODE files.
# NCBI build version (either hg19 or hg38):
ncbi_build_version =

# Required field for simpleXSV files.
# Valid values:
#     GENE_NAME
#     TRANSCRIPT_ID
xsv_key =

# Required field for simpleXSV files.
# The 0-based index of the column containing the key on which to match
xsv_key_column =

# Required field for simpleXSV AND locatableXSV files.
# The delimiter by which to split the XSV file into columns.
xsv_delimiter = \t

# Required field for simpleXSV files.
# Whether to permissively match the number of columns in the header and data rows
# Valid values:
#     true
#     false
xsv_permissive_cols = true

# Required field for locatableXSV files.
# The 0-based index of the column containing the contig for each row
contig_column = 0

# Required field for locatableXSV files.
# The 0-based index of the column containing the start position for each row
start_column = 1

# Required field for locatableXSV files.
# The 0-based index of the column containing the end position for each row
end_column = 2
`
