### ISSUE TITLE
GATK4 Mutect2 error ：af-only-gnomad.raw.sites.hg19.vcf.gz has invalid uncompressedLength: -795051631, 

### ISSUE THREAD

**Issue by guoyuh** [broadinstitute/gatk#6248]
I have found an error when using GATK4 Mutect2 ,error as follow,thanks and waitting your reply
Using GATK jar /home/vip/biosoft/gatk/gatk-4.0.5.1/gatk-package-4.0.5.1-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx10g -jar /home/vip/biosoft/gatk/gatk-4.0.5.1/gatk-package-4.0.5.1-local.jar Mutect2 -R /data/bigbiosoft/GATK/resources/bundle/hg19/ucsc.hg19.fasta -I 02_bamdst/zhaoxuelan.sorted.algn.bam --tumor zhaoxuelan --germline-resource /home/vip/data/Mutect2/af-only-gnomad.raw.sites.hg19.vcf.gz --max-reads-per-alignment-start 0 -L /home/vip/lxdata/bed/lung9_gene_format.bed -O 03_somatic/zhaoxuelan.sorted.algn.bam.raw.vcf --af-of-alleles-not-in-resource 0.00003125 --min-base-quality-score 20 --read-filter MateOnSameContigOrNoMappedMateReadFilter --create-output-variant-md5
16:46:49.608 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/vip/biosoft/gatk/gatk-4.0.5.1/gatk-package-4.0.5.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
16:46:49.698 INFO  Mutect2 - ------------------------------------------------------------
16:46:49.698 INFO  Mutect2 - The Genome Analysis Toolkit (GATK) v4.0.5.1
16:46:49.698 INFO  Mutect2 - For support and documentation go to https://software.broadinstitute.org/gatk/
16:46:49.698 INFO  Mutect2 - Executing as vip@zjm-System-Product-Name on Linux v4.18.0-25-generic amd64
16:46:49.698 INFO  Mutect2 - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10
16:46:49.699 INFO  Mutect2 - Start Date/Time: November 6, 2019 4:46:49 PM CST
16:46:49.699 INFO  Mutect2 - ------------------------------------------------------------
16:46:49.699 INFO  Mutect2 - ------------------------------------------------------------
16:46:49.699 INFO  Mutect2 - HTSJDK Version: 2.15.1
16:46:49.699 INFO  Mutect2 - Picard Version: 2.18.2
16:46:49.699 INFO  Mutect2 - HTSJDK Defaults.COMPRESSION_LEVEL : 2
16:46:49.699 INFO  Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
16:46:49.700 INFO  Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
16:46:49.700 INFO  Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
16:46:49.700 INFO  Mutect2 - Deflater: IntelDeflater
16:46:49.700 INFO  Mutect2 - Inflater: IntelInflater
16:46:49.700 INFO  Mutect2 - GCS max retries/reopens: 20
16:46:49.700 INFO  Mutect2 - Using google-cloud-java patch 6d11bef1c81f885c26b2b56c8616b7a705171e4f from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes
16:46:49.700 INFO  Mutect2 - Initializing engine
16:46:49.995 INFO  FeatureManager - Using codec VCFCodec to read file file:///home/vip/data/Mutect2/af-only-gnomad.raw.sites.hg19.vcf.gz
16:46:50.064 INFO  Mutect2 - Shutting down engine
[November 6, 2019 4:46:50 PM CST] org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2 done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=2394947584
org.broadinstitute.hellbender.exceptions.GATKException: Error initializing feature reader for path /home/vip/data/Mutect2/af-only-gnomad.raw.sites.hg19.vcf.gz
	at org.broadinstitute.hellbender.engine.FeatureDataSource.getTribbleFeatureReader(FeatureDataSource.java:357)
	at org.broadinstitute.hellbender.engine.FeatureDataSource.getFeatureReader(FeatureDataSource.java:308)
	at org.broadinstitute.hellbender.engine.FeatureDataSource.<init>(FeatureDataSource.java:255)
	at org.broadinstitute.hellbender.engine.FeatureManager.addToFeatureSources(FeatureManager.java:202)
	at org.broadinstitute.hellbender.engine.FeatureManager.initializeFeatureSources(FeatureManager.java:182)
	at org.broadinstitute.hellbender.engine.FeatureManager.<init>(FeatureManager.java:153)
	at org.broadinstitute.hellbender.engine.GATKTool.initializeFeatures(GATKTool.java:415)
	at org.broadinstitute.hellbender.engine.GATKTool.onStartup(GATKTool.java:636)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.onStartup(AssemblyRegionWalker.java:160)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:133)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:180)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:199)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
Caused by: htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: /home/vip/data/Mutect2/af-only-gnomad.raw.sites.hg19.vcf.gz has invalid uncompressedLength: -795051631, for input source: file:///home/vip/data/Mutect2/af-only-gnomad.raw.sites.hg19.vcf.gz
	at htsjdk.tribble.TabixFeatureReader.readHeader(TabixFeatureReader.java:97)
	at htsjdk.tribble.TabixFeatureReader.<init>(TabixFeatureReader.java:82)
	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:106)
	at org.broadinstitute.hellbender.engine.FeatureDataSource.getTribbleFeatureReader(FeatureDataSource.java:353)
	... 14 more
Caused by: htsjdk.samtools.util.RuntimeIOException: /home/vip/data/Mutect2/af-only-gnomad.raw.sites.hg19.vcf.gz has invalid uncompressedLength: -795051631
	at htsjdk.samtools.util.BlockCompressedInputStream.inflateBlock(BlockCompressedInputStream.java:543)
	at htsjdk.samtools.util.BlockCompressedInputStream.processNextBlock(BlockCompressedInputStream.java:532)
	at htsjdk.samtools.util.BlockCompressedInputStream.nextBlock(BlockCompressedInputStream.java:468)
	at htsjdk.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:458)
	at htsjdk.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:196)
	at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:331)
	at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:257)
	at htsjdk.tribble.readers.PositionalBufferedStream.fill(PositionalBufferedStream.java:132)
	at htsjdk.tribble.readers.PositionalBufferedStream.read(PositionalBufferedStream.java:84)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at htsjdk.tribble.readers.LongLineBufferedReader.fill(LongLineBufferedReader.java:140)
	at htsjdk.tribble.readers.LongLineBufferedReader.readLine(LongLineBufferedReader.java:300)
	at htsjdk.tribble.readers.LongLineBufferedReader.readLine(LongLineBufferedReader.java:356)
	at htsjdk.tribble.readers.SynchronousLineReader.readLine(SynchronousLineReader.java:51)
	at htsjdk.tribble.readers.LineIteratorImpl.advance(LineIteratorImpl.java:24)
	at htsjdk.tribble.readers.LineIteratorImpl.advance(LineIteratorImpl.java:11)
	at htsjdk.samtools.util.AbstractIterator.hasNext(AbstractIterator.java:44)
	at htsjdk.variant.vcf.VCFCodec.readActualHeader(VCFCodec.java:89)
	at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:79)
	at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:37)
	at htsjdk.tribble.TabixFeatureReader.readHeader(TabixFeatureReader.java:95)
	... 17 more

**Comment by davidbenjamin** [comment]
@guoyuh Please try the most recent GATK release.  If the error persists we will debug.

**Comment by davidbenjamin** [comment]
We can re-open if the error remains in the current release.

**Comment by iichelhadi** [comment]
running against the same issue! Has anyone found a solution?
