### ISSUE TITLE
SelectVariant raise  OutOfMemoryError

### ISSUE THREAD

**Issue by Fruit-loops** [broadinstitute/gatk#6254]
### Affected tool(s) or class(es)

The Genome Analysis Toolkit (GATK) v4.0.7.0

### Description 

I ran the command line below and get an oom error. I've  got the same error when i set the heap memory larger using the param "--java-option Xmx24g" . This procedure only crashed when I tried to select INDEL. I've uploaded the vcf file for you to test.

command line:
```shell
disk/juntong/software/gatk-4.0.7.0/gatk SelectVariants -V /disk/juntong/huada/V300029595_results/mutect_outputs/V300029595.merged.vcf.gatk.somatic.vcf.gz -O /disk/juntong/huada/V300029595_results/mutect_outputs/V300029595.merged.vcf.gatk.somatic.vcf.gatk.somatic.indel.vcf.gz -select-type INDEL
```

log:
```
Using GATK jar /disk/juntong/software/gatk-4.0.7.0/gatk-package-4.0.7.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /disk/juntong/software/gatk-4.0.7.0/gatk-package-4.0.7.0-local.jar SelectVariants -V /disk/juntong/huada/V300029595_results/mutect_outputs/V300029595.merged.vcf.gatk.somatic.vcf.gz -O /disk/juntong/huada/V300029595_results/mutect_outputs/V300029595.merged.vcf.gatk.somatic.vcf.gatk.somatic.indel.vcf.gz -select-type INDEL
05:06:54.800 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/disk/juntong/software/gatk-4.0.7.0/gatk-package-4.0.7.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
05:06:55.409 INFO  SelectVariants - ------------------------------------------------------------
05:06:55.409 INFO  SelectVariants - The Genome Analysis Toolkit (GATK) v4.0.7.0
05:06:55.409 INFO  SelectVariants - For support and documentation go to https://software.broadinstitute.org/gatk/
05:06:55.410 INFO  SelectVariants - Executing as juntong@train1 on Linux v3.10.0-1062.1.1.el7.x86_64 amd64
05:06:55.410 INFO  SelectVariants - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_222-b10
05:06:55.410 INFO  SelectVariants - Start Date/Time: November 6, 2019 5:06:54 AM EST
05:06:55.410 INFO  SelectVariants - ------------------------------------------------------------
05:06:55.410 INFO  SelectVariants - ------------------------------------------------------------
05:06:55.411 INFO  SelectVariants - HTSJDK Version: 2.16.0
05:06:55.411 INFO  SelectVariants - Picard Version: 2.18.7
05:06:55.411 INFO  SelectVariants - HTSJDK Defaults.COMPRESSION_LEVEL : 2
05:06:55.411 INFO  SelectVariants - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
05:06:55.412 INFO  SelectVariants - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
05:06:55.412 INFO  SelectVariants - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
05:06:55.412 INFO  SelectVariants - Deflater: IntelDeflater
05:06:55.412 INFO  SelectVariants - Inflater: IntelInflater
05:06:55.412 INFO  SelectVariants - GCS max retries/reopens: 20
05:06:55.412 INFO  SelectVariants - Using google-cloud-java patch 6d11bef1c81f885c26b2b56c8616b7a705171e4f from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes
05:06:55.412 INFO  SelectVariants - Initializing engine
05:06:55.796 INFO  FeatureManager - Using codec VCFCodec to read file file:///disk/juntong/huada/V300029595_results/mutect_outputs/V300029595.merged.vcf.gatk.somatic.vcf.gz
05:06:55.962 INFO  SelectVariants - Done initializing engine
05:06:56.099 INFO  ProgressMeter - Starting traversal
05:06:56.099 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
06:39:06.894 INFO  SelectVariants - Shutting down engine
[November 6, 2019 6:39:06 AM EST] org.broadinstitute.hellbender.tools.walkers.variantutils.SelectVariants done. Elapsed time: 92.20 minutes.
Runtime.totalMemory()=29215424512
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3181)
        at java.util.ArrayList.grow(ArrayList.java:265)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:239)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:231)
        at java.util.ArrayList.add(ArrayList.java:462)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:392)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculatePLIndexToAlleleIndices(GenotypeLikelihoods.java:394)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.calculateAnyploidPLcache(GenotypeLikelihoods.java:410)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.initializeAnyploidPLIndexToAlleleIndices(GenotypeLikelihoods.java:518)
        at org.broadinstitute.hellbender.tools.walkers.variantutils.SelectVariants.initalizeAlleleAnyploidIndicesCache(SelectVariants.java:629)
        at org.broadinstitute.hellbender.tools.walkers.variantutils.SelectVariants.apply(SelectVariants.java:563)
        at org.broadinstitute.hellbender.engine.VariantWalkerBase.lambda$traverse$0(VariantWalkerBase.java:151)
        at org.broadinstitute.hellbender.engine.VariantWalkerBase$$Lambda$68/529766927.accept(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
```

#### Steps to reproduce
[vcf_and_index.zip](https://github.com/broadinstitute/gatk/files/3818610/vcf_and_index.zip)

**Comment by davidbenjamin** [comment]
@Fruit-loops this happens for many-allelic sites.  SelectVariants historically assumed every input was a germline site with PL values (genotype likelihoods) for every possible combination of alleles and ploidy and generated an expensive cache of these indices.  For somatic sites this concept is meaningless and for many-allelic sites it's combinatorially expensive.  The PR mentioned above skips the expensive calculation for somatic sites that lack PLs.
