### ISSUE TITLE
java.lang.IllegalArgumentException: Unexpected base in allele bases

### ISSUE THREAD

**Issue by ccartermices** [broadinstitute/gatk#6260]
Hey there~ I have run the following command:

gatk HaplotypeCaller \
-R bbv18h27rm.fa \
-ERC GVCF \
--alleles db_raw_call_bbe_6largest.vcf \
-I bbe_off_xL3_68.concordant_withRG.bam \
-O test_call_off_xL3_68_allele_46samples.vcf.gz

and had some error:
```
Using GATK jar /home/cc/gatk/gatk_dir/gatk/build/libs/gatk-package-4.1.3.0-25-g8d88f6e-SNAPSHOT-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /home/cc/gatk/gatk_dir/gatk/build/libs/gatk-package-4.1.3.0-25-g8d88f6e-SNAPSHOT-local.jar HaplotypeCaller -R /db_students1/genetic_map/snp_calling/bbv18h27rm.fa -ERC GVCF --alleles /db_students1/gatk_out/db_raw_call_bbe_6largest.vcf -I /db_students1/genetic_map/reseqData_mapping_bam/bam/bbe_off_xL3_68.concordant_withRG.bam -O /db_students1/gatk_out/test_call_off_xL3_68_allele_46samples.vcf.gz
17:04:13.440 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/cc/gatk/gatk_dir/gatk/build/libs/gatk-package-4.1.3.0-25-g8d88f6e-SNAPSHOT-local.jar!/com/intel/gkl/native/libgkl_compression.so
Nov 12, 2019 5:04:15 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
17:04:15.137 INFO  HaplotypeCaller - ------------------------------------------------------------
17:04:15.138 INFO  HaplotypeCaller - The Genome Analysis Toolkit (GATK) v4.1.3.0-25-g8d88f6e-SNAPSHOT
17:04:15.138 INFO  HaplotypeCaller - For support and documentation go to https://software.broadinstitute.org/gatk/
17:04:15.138 INFO  HaplotypeCaller - Executing as cc@hr18b on Linux v3.10.0-957.el7.x86_64 amd64
17:04:15.138 INFO  HaplotypeCaller - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_212-b04
17:04:15.138 INFO  HaplotypeCaller - Start Date/Time: November 12, 2019 5:04:13 PM CST
17:04:15.139 INFO  HaplotypeCaller - ------------------------------------------------------------
17:04:15.139 INFO  HaplotypeCaller - ------------------------------------------------------------
17:04:15.139 INFO  HaplotypeCaller - HTSJDK Version: 2.20.3
17:04:15.140 INFO  HaplotypeCaller - Picard Version: 2.20.5
17:04:15.140 INFO  HaplotypeCaller - HTSJDK Defaults.COMPRESSION_LEVEL : 2
17:04:15.140 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
17:04:15.140 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
17:04:15.140 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
17:04:15.140 INFO  HaplotypeCaller - Deflater: IntelDeflater
17:04:15.140 INFO  HaplotypeCaller - Inflater: IntelInflater
17:04:15.141 INFO  HaplotypeCaller - GCS max retries/reopens: 20
17:04:15.141 INFO  HaplotypeCaller - Requester pays: disabled
17:04:15.141 INFO  HaplotypeCaller - Initializing engine
WARNING: BAM index file /db_students1/genetic_map/reseqData_mapping_bam/bam/bbe_off_xL3_68.concordant_withRG.bai is older than BAM /db_students1/genetic_map/reseqData_mapping_bam/bam/bbe_off_xL3_68.concordant_withRG.bam
17:04:15.666 INFO  FeatureManager - Using codec VCFCodec to read file file:///db_students1/gatk_out/db_raw_call_bbe_6largest.vcf
17:04:15.912 INFO  HaplotypeCaller - Done initializing engine
17:04:15.914 INFO  HaplotypeCallerEngine - Tool is in reference confidence mode and the annotation, the following changes will be made to any specified annotations: 'StrandBiasBySample' will be enabled. 'ChromosomeCounts', 'FisherStrand', 'StrandOddsRatio' and 'QualByDepth' annotations have been disabled
17:04:15.948 INFO  HaplotypeCallerEngine - Standard Emitting and Calling confidence set to 0.0 for reference-model confidence output
17:04:15.948 INFO  HaplotypeCallerEngine - All sites annotated with PLs forced to true for reference-model confidence output
17:04:15.960 INFO  NativeLibraryLoader - Loading libgkl_utils.so from jar:file:/home/cc/gatk/gatk_dir/gatk/build/libs/gatk-package-4.1.3.0-25-g8d88f6e-SNAPSHOT-local.jar!/com/intel/gkl/native/libgkl_utils.so
17:04:15.962 INFO  NativeLibraryLoader - Loading libgkl_pairhmm_omp.so from jar:file:/home/cc/gatk/gatk_dir/gatk/build/libs/gatk-package-4.1.3.0-25-g8d88f6e-SNAPSHOT-local.jar!/com/intel/gkl/native/libgkl_pairhmm_omp.so
17:04:16.002 INFO  IntelPairHmm - Flush-to-zero (FTZ) is enabled when running PairHMM
17:04:16.003 INFO  IntelPairHmm - Available threads: 40
17:04:16.003 INFO  IntelPairHmm - Requested threads: 4
17:04:16.003 INFO  PairHMM - Using the OpenMP multi-threaded AVX-accelerated native PairHMM implementation
17:04:16.052 INFO  ProgressMeter - Starting traversal
17:04:16.052 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Regions Processed   Regions/Minute
17:04:16.589 WARN  InbreedingCoeff - InbreedingCoeff will not be calculated; at least 10 samples must have called genotypes
17:04:17.126 WARN  DepthPerSampleHC - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null
17:04:17.126 WARN  StrandBiasBySample - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null
17:04:17.128 WARN  StrandBiasBySample - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null
17:04:17.130 WARN  StrandBiasBySample - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null
17:04:17.132 WARN  StrandBiasBySample - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null
17:04:17.670 WARN  StrandBiasBySample - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null
17:04:17.671 WARN  StrandBiasBySample - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null
17:04:18.317 INFO  VectorLoglessPairHMM - Time spent in setup for JNI call : 9.92553E-4
17:04:18.318 INFO  PairHMM - Total compute time in PairHMM computeLogLikelihoods() : 0.099975122
17:04:18.318 INFO  SmithWatermanAligner - Total compute time in java Smith-Waterman : 1.19 sec
17:04:18.319 INFO  HaplotypeCaller - Shutting down engine
[November 12, 2019 5:04:18 PM CST] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 0.08 minutes.
Runtime.totalMemory()=2102919168
java.lang.IllegalArgumentException: Unexpected base in allele bases 'TACTAGGCGGGACAAGTATCCAAGCGCAAATCTACGCCGACTGAACACGCACCATAATTCAACTTTTACAGTCTCAAAACTGACGTATTCCTCTAACATTTACCACAGGTTCTATCTCGATGCCATGCACAAAACAATCTCTGCACCCTTCTCTAGTACATTTGTGCAGCACTACTTTGTGCTCGGACTACTTTTGAC*TTCGCCCATGAATACTGTGTTGTGCGGCCTTGACGCCATGGGGCATAGAGAAGTCATAAAGAAGTGAAATTTTGTTTTGGGTGTAACTATTGTTCTTTTGTTAGTATATTGATGACGAAATTGTTTACAAGGTAAGTGGGGATTAGAAAAGGATGAGAAGGAACCCTGTAAAAGGTAAAGCACACACAAAAAACATATTGTAAGTTACACTACAATGACTATGTACAACGCAAACCTGTCTATATTAGCAACCGCTAATATTACTAT'
	at htsjdk.variant.variantcontext.Allele.<init>(Allele.java:170)
	at org.broadinstitute.hellbender.utils.haplotype.Haplotype.<init>(Haplotype.java:40)
	at org.broadinstitute.hellbender.utils.haplotype.Haplotype.<init>(Haplotype.java:49)
	at org.broadinstitute.hellbender.utils.haplotype.Haplotype.insertAllele(Haplotype.java:209)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.addGivenAlleles(AssemblyBasedCallerUtils.java:348)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.assembleReads(AssemblyBasedCallerUtils.java:292)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.callRegion(HaplotypeCallerEngine.java:528)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller.apply(HaplotypeCaller.java:240)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:308)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:281)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)
```
How can i handle with this ? Thanks.

**Comment by jamesemery** [comment]
Hey @ccartermices. Looking at that error message it appears that the genotype given alleles has tried to insert a '*' allele into an assembled haplotype. ("TTTTGAC*TTCGC" in the error message). I suspect this is because the code is missing a check to filter symbolic alleles out of GGA inputs. Can you check your input `db_raw_call_bbe_6largest.vcf` for `*` alleles? It should be possible to filter those out of your input file.

**Comment by lbergelson** [comment]
We should patch to give a better error message as well...

**Comment by ccartermices** [comment]
> Hey @ccartermices. Looking at that error message it appears that the genotype given alleles has tried to insert a '*' allele into an assembled haplotype. ("TTTTGAC*TTCGC" in the error message). I suspect this is because the code is missing a check to filter symbolic alleles out of GGA inputs. Can you check your input `db_raw_call_bbe_6largest.vcf` for `\*` alleles? It should be possible to filter those out of your input file.

Thanks，if i want to make a filter on it, should i use which tool? VQSR?

**Comment by davidbenjamin** [comment]
I touch the GGA code more than anyone.  I should fix this.
