### ISSUE TITLE
Using womtool 47 to graph the latest mutect2 wdls throws an exception

### ISSUE THREAD

**Issue by pavlemarinkovic** [broadinstitute/gatk#6261]
### Affected tool(s) or class(es)
_womtool-47, grpah_
or
_version 1.0 wdls_

### Description 

I've been trying to graph mutect2 wdls using the latest womtool, but each time the tool throws an exception.

Command-line:
`java -jar womtool-47.jar graph mutect2.wdl`

Exception:
```
Exception in thread "main" wdl.draft2.parser.WdlParser$SyntaxError: Unrecognized token on line 445, column 42:

        samtools view -h -T ~{ref_fasta} ~{cram} |
                                         ^
	at wdl.draft2.parser.WdlParser.unrecognized_token(WdlParser.java:6975)
	at wdl.draft2.parser.WdlParser.lex(WdlParser.java:7048)
	at wdl.draft2.model.AstTools$.getAst(AstTools.scala:263)
	at wdl.draft2.model.WdlNamespace$.$anonfun$load$1(WdlNamespace.scala:170)
	at scala.util.Try$.apply(Try.scala:213)
	at wdl.draft2.model.WdlNamespace$.load(WdlNamespace.scala:169)
	at wdl.draft2.model.WdlNamespace$.loadUsingSource(WdlNamespace.scala:161)
	at wdl.draft2.model.WdlNamespaceWithWorkflow$.load(WdlNamespace.scala:630)
	at womtool.graph.GraphPrint$.generateWorkflowDigraph(GraphPrint.scala:19)
	at womtool.WomtoolMain$.graph(WomtoolMain.scala:131)
	at womtool.WomtoolMain$.dispatchCommand(WomtoolMain.scala:54)
	at womtool.WomtoolMain$.runWomtool(WomtoolMain.scala:162)
	at womtool.WomtoolMain$.delayedEndpoint$womtool$WomtoolMain$1(WomtoolMain.scala:167)
	at womtool.WomtoolMain$delayedInit$body.apply(WomtoolMain.scala:24)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at womtool.WomtoolMain$.main(WomtoolMain.scala:24)
	at womtool.WomtoolMain.main(WomtoolMain.scala)
```

for multi sample:
```
Exception in thread "main" wdl.draft2.parser.WdlParser$SyntaxError: Unrecognized token on line 31, column 50:

  <title>gatk/mutect2_multi_sample.wdl at master ? broadinstitute/gatk ? GitHub</title>
                                                 ^
	at wdl.draft2.parser.WdlParser.unrecognized_token(WdlParser.java:6975)
	at wdl.draft2.parser.WdlParser.lex(WdlParser.java:7048)
	at wdl.draft2.model.AstTools$.getAst(AstTools.scala:263)
	at wdl.draft2.model.WdlNamespace$.$anonfun$load$1(WdlNamespace.scala:170)
	at scala.util.Try$.apply(Try.scala:213)
	at wdl.draft2.model.WdlNamespace$.load(WdlNamespace.scala:169)
	at wdl.draft2.model.WdlNamespace$.loadUsingSource(WdlNamespace.scala:161)
	at wdl.draft2.model.WdlNamespaceWithWorkflow$.load(WdlNamespace.scala:630)
	at womtool.graph.GraphPrint$.generateWorkflowDigraph(GraphPrint.scala:19)
	at womtool.WomtoolMain$.graph(WomtoolMain.scala:131)
	at womtool.WomtoolMain$.dispatchCommand(WomtoolMain.scala:54)
	at womtool.WomtoolMain$.runWomtool(WomtoolMain.scala:162)
	at womtool.WomtoolMain$.delayedEndpoint$womtool$WomtoolMain$1(WomtoolMain.scala:167)
	at womtool.WomtoolMain$delayedInit$body.apply(WomtoolMain.scala:24)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at womtool.WomtoolMain$.main(WomtoolMain.scala:24)
	at womtool.WomtoolMain.main(WomtoolMain.scala)
```

for pon
```
Exception in thread "main" wdl.draft2.parser.WdlParser$SyntaxError: Unrecognized token on line 151, column 69:

        gatk GenomicsDBImport --genomicsdb-workspace-path pon_db -R ~{ref_fasta} -V ~{sep=' -V ' input_vcfs} -L ~{intervals}
                                                                    ^
	at wdl.draft2.parser.WdlParser.unrecognized_token(WdlParser.java:6975)
	at wdl.draft2.parser.WdlParser.lex(WdlParser.java:7048)
	at wdl.draft2.model.AstTools$.getAst(AstTools.scala:263)
	at wdl.draft2.model.WdlNamespace$.$anonfun$load$1(WdlNamespace.scala:170)
	at scala.util.Try$.apply(Try.scala:213)
	at wdl.draft2.model.WdlNamespace$.load(WdlNamespace.scala:169)
	at wdl.draft2.model.WdlNamespace$.loadUsingSource(WdlNamespace.scala:161)
	at wdl.draft2.model.WdlNamespaceWithWorkflow$.load(WdlNamespace.scala:630)
	at womtool.graph.GraphPrint$.generateWorkflowDigraph(GraphPrint.scala:19)
	at womtool.WomtoolMain$.graph(WomtoolMain.scala:131)
	at womtool.WomtoolMain$.dispatchCommand(WomtoolMain.scala:54)
	at womtool.WomtoolMain$.runWomtool(WomtoolMain.scala:162)
	at womtool.WomtoolMain$.delayedEndpoint$womtool$WomtoolMain$1(WomtoolMain.scala:167)
	at womtool.WomtoolMain$delayedInit$body.apply(WomtoolMain.scala:24)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at womtool.WomtoolMain$.main(WomtoolMain.scala:24)
	at womtool.WomtoolMain.main(WomtoolMain.scala)
```

Am I using womtool wrong, or is there a bug with it, or is this an issue with wdls?

**Comment by davidbenjamin** [comment]
@pavlemarinkovic womtool does not yet support WDL 1.0, which the M2 pipeline uses.  See this discussion: https://github.com/broadinstitute/cromwell/issues/4234.  However, the issue has been resolved in the cromwell repo: https://github.com/broadinstitute/cromwell/pull/5326, so it looks like the next release will fix it for you.
