### ISSUE TITLE
CombineGVCFs v4.1.4.1 java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by bhanugandham** [broadinstitute/gatk#6340]
User Report:

gatk --java-options "-Xmx6g" CombineGVCFs -R $ref -O all.g.vcf --variant gvcf.list
Using GATK jar /mnt/d/software_lin/gatk/gatk-package-4.1.4.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx6g -jar /mnt/d/software_lin/gatk/gatk-package-4.1.4.0-local.jar CombineGVCFs -R /mnt/d/data/gatk_bundle/hg38//Homo_sapiens_assembly38.fasta.gz -O all.g.vcf --variant gvcf.list
22:49:52.449 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/mnt/d/software_lin/gatk/gatk-package-4.1.4.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Dec 19, 2019 10:49:53 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
22:49:53.492 INFO  CombineGVCFs - ------------------------------------------------------------
22:49:53.494 INFO  CombineGVCFs - The Genome Analysis Toolkit (GATK) v4.1.4.0
22:49:53.494 INFO  CombineGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
22:49:53.495 INFO  CombineGVCFs - Executing as jiehuang@DESKTOP-POF1PJ4 on Linux v4.4.0-17763-Microsoft amd64
22:49:53.495 INFO  CombineGVCFs - Java runtime: OpenJDK 64-Bit Server VM v11.0.4+11-post-Ubuntu-1ubuntu218.04.3
22:49:53.496 INFO  CombineGVCFs - Start Date/Time: December 19, 2019 at 10:49:52 PM GMT
22:49:53.496 INFO  CombineGVCFs - ------------------------------------------------------------
22:49:53.497 INFO  CombineGVCFs - ------------------------------------------------------------
22:49:53.498 INFO  CombineGVCFs - HTSJDK Version: 2.20.3
22:49:53.502 INFO  CombineGVCFs - Picard Version: 2.21.1
22:49:53.502 INFO  CombineGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2
22:49:53.523 INFO  CombineGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
22:49:53.524 INFO  CombineGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
22:49:53.550 INFO  CombineGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
22:49:53.550 INFO  CombineGVCFs - Deflater: IntelDeflater
22:49:53.570 INFO  CombineGVCFs - Inflater: IntelInflater
22:49:53.571 INFO  CombineGVCFs - GCS max retries/reopens: 20
22:49:53.595 INFO  CombineGVCFs - Requester pays: disabled
22:49:53.597 INFO  CombineGVCFs - Initializing engine
22:49:53.869 INFO  FeatureManager - Using codec VCFCodec to read file file:///mnt/d/projects/sequencing/gvcf/OPG0005F/OPG0005F.GATK.var.g.vcf
22:49:53.923 INFO  FeatureManager - Using codec VCFCodec to read file file:///mnt/d/projects/sequencing/gvcf/OPG0005M/OPG0005M.GATK.var.g.vcf
22:49:53.939 INFO  FeatureManager - Using codec VCFCodec to read file file:///mnt/d/projects/sequencing/gvcf/OPG0005P/OPG0005P.GATK.var.g.vcf
22:49:54.132 INFO  CombineGVCFs - Done initializing engine
22:49:54.156 INFO  ProgressMeter - Starting traversal
22:49:54.157 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
22:49:54.193 INFO  CombineGVCFs - Shutting down engine
[December 19, 2019 at 10:49:54 PM GMT] org.broadinstitute.hellbender.tools.walkers.CombineGVCFs done. Elapsed time: 0.03 minutes.
Runtime.totalMemory()=156237824
java.lang.ArrayIndexOutOfBoundsException: Index -2 out of bounds for length 256
        at org.broadinstitute.hellbender.utils.BaseUtils.convertIUPACtoN(BaseUtils.java:120)
        at org.broadinstitute.hellbender.utils.fasta.CachingIndexedFastaSequenceFile.getSubsequenceAt(CachingIndexedFastaSequenceFile.java:326)
        at org.broadinstitute.hellbender.engine.ReferenceFileSource.queryAndPrefetch(ReferenceFileSource.java:78)
        at org.broadinstitute.hellbender.engine.ReferenceDataSource.queryAndPrefetch(ReferenceDataSource.java:64)
        at org.broadinstitute.hellbender.engine.ReferenceContext.getBases(ReferenceContext.java:197)
        at org.broadinstitute.hellbender.tools.walkers.CombineGVCFs.createIntermediateVariants(CombineGVCFs.java:216)
        at org.broadinstitute.hellbender.tools.walkers.CombineGVCFs.apply(CombineGVCFs.java:162)
        at org.broadinstitute.hellbender.engine.MultiVariantWalkerGroupedOnStart.apply(MultiVariantWalkerGroupedOnStart.java:131)
        at org.broadinstitute.hellbender.engine.MultiVariantWalkerGroupedOnStart.apply(MultiVariantWalkerGroupedOnStart.java:106)
        at org.broadinstitute.hellbender.engine.MultiVariantWalker.lambda$traverse$1(MultiVariantWalker.java:120)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at org.broadinstitute.hellbender.engine.MultiVariantWalker.traverse(MultiVariantWalker.java:118)
        at org.broadinstitute.hellbender.engine.MultiVariantWalkerGroupedOnStart.traverse(MultiVariantWalkerGroupedOnStart.java:163)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
        at org.broadinstitute.hellbender.Main.main(Main.java:292)

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/62035#Comment_62035

**Comment by bhanugandham** [comment]
@jamesemery 

User shared log file and the first few lines of the GVCF file you requested in a zip file here: https://www.dropbox.com/s/p2smhpm5btsf2cq/jiehuang.zip?dl=0,

**Comment by xingaulag** [comment]
hi @bhanugandham , 

Have you had any idea to figure out this error? I'm also facing to it

**Comment by chen42** [comment]
I am encountering a similar error: 
```
Using GATK jar /nics/d/home/hchen3/bin/gatk-4.1.2.0/gatk-package-4.1.2.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /nics/d/home/hchen3/bin/gatk-4.1.2.0/gatk-package-4.1.2.0-local.jar GenotypeGVCFs -R /lustre/haven/proj/UTHSC0013/Tristan_GATK/reference/genome.fa -V gendb:///lustre/haven/proj/UTHSC0013/Tristan_GATK//DB/chr7 -G StandardAnnotation --use-new-qual-calculator -O /lustre/haven/proj/UTHSC0013/Tristan_GATK//gvcf//merged//joint_called_gvcfs_chr7.vcf
23:15:47.053 WARN  GATKAnnotationPluginDescriptor - Redundant enabled annotation group (StandardAnnotation) is enabled for this tool by default
23:15:47.249 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/nics/d/home/hchen3/bin/gatk-4.1.2.0/gatk-package-4.1.2.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Jan 07, 2020 11:15:49 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
23:15:49.543 INFO  GenotypeGVCFs - ------------------------------------------------------------
23:15:49.545 INFO  GenotypeGVCFs - The Genome Analysis Toolkit (GATK) v4.1.2.0
23:15:49.546 INFO  GenotypeGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
23:15:49.547 INFO  GenotypeGVCFs - Executing as hchen3@acf-knl002 on Linux v3.10.0-514.26.1.el7.x86_64 amd64
23:15:49.548 INFO  GenotypeGVCFs - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_131-b12
23:15:49.548 INFO  GenotypeGVCFs - Start Date/Time: January 7, 2020 11:15:47 PM EST
23:15:49.549 INFO  GenotypeGVCFs - ------------------------------------------------------------
23:15:49.549 INFO  GenotypeGVCFs - ------------------------------------------------------------
23:15:49.551 INFO  GenotypeGVCFs - HTSJDK Version: 2.19.0
23:15:49.551 INFO  GenotypeGVCFs - Picard Version: 2.19.0
23:15:49.552 INFO  GenotypeGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2
23:15:49.552 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
23:15:49.552 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
23:15:49.552 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
23:15:49.552 INFO  GenotypeGVCFs - Deflater: IntelDeflater
23:15:49.553 INFO  GenotypeGVCFs - Inflater: IntelInflater
23:15:49.553 INFO  GenotypeGVCFs - GCS max retries/reopens: 20
23:15:49.553 INFO  GenotypeGVCFs - Requester pays: disabled
23:15:49.553 INFO  GenotypeGVCFs - Initializing engine
WARNING: No valid combination operation found for INFO field DS - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field InbreedingCoeff - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAC - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAF - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field DS - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field InbreedingCoeff - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAC - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAF - the field will NOT be part of INFO fields in the generated VCF records
23:16:27.971 INFO  GenotypeGVCFs - Done initializing engine
23:16:28.168 INFO  ProgressMeter - Starting traversal
23:16:28.169 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
WARNING: No valid combination operation found for INFO field DS - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field InbreedingCoeff - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAC - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAF - the field will NOT be part of INFO fields in the generated VCF records
23:20:28.785 INFO  GenotypeGVCFs - Shutting down engine
GENOMICSDB_TIMER,GenomicsDB iterator next() timer,Wall-clock time(s),0.11700176899999999,Cpu time(s),0.11079876499999991
[January 7, 2020 11:20:29 PM EST] org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 4.71 minutes.
Runtime.totalMemory()=2446327808
java.lang.ArrayIndexOutOfBoundsException: 5
	at org.broadinstitute.hellbender.tools.walkers.ReferenceConfidenceVariantContextMerger.generatePL(ReferenceConfidenceVariantContextMerger.java:652)
	at org.broadinstitute.hellbender.tools.walkers.ReferenceConfidenceVariantContextMerger.mergeRefConfidenceGenotypes(ReferenceConfidenceVariantContextMerger.java:543)
	at org.broadinstitute.hellbender.tools.walkers.ReferenceConfidenceVariantContextMerger.merge(ReferenceConfidenceVariantContextMerger.java:130)
	at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.apply(GenotypeGVCFs.java:310)
	at org.broadinstitute.hellbender.engine.VariantLocusWalker.lambda$traverse$0(VariantLocusWalker.java:136)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
	at org.broadinstitute.hellbender.engine.VariantLocusWalker.traverse(VariantLocusWalker.java:134)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1039)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)
```

**Comment by jamesemery** [comment]
Thank you @chen42. Looking at the exception it looks like it is another issue with a seperate tool (GenotypeGVCFs as opposed to CombineGVCFs). This is clearly a seperate issue and I have created an issue to track it  #6357. It would be helpful to get a snippet of the beginning of your input bam `/lustre/haven/proj/UTHSC0013/Tristan_GATK//gvcf//merged//joint_called_gvcfs_chr7.vcf` in order evaluate what is happening. Here are some instructions for sharing files: https://software.broadinstitute.org/gatk/guide/article?id=1894.

**Comment by chen42** [comment]
@jamesemery You are right. I tried combineGVCFs first and it produced the java.lang.ArrayIndexOutOfBoundsException. I then tried the GenotypeGVCFs from GenomicsDBImport and got the same error again. I think I have since found out I did not index two of the g.vcf files and added those. When I tried it again, combineGVCFs works but GenotypeGVCFs on GenomicsDBImport still fail with the java.lang.ArrayIndexOutOfBoundsException error. GenotypeGVCFs worked on all other chromosomes, just not on chr7 in this case. I will generate a snippet for #6357

**Comment by droazen** [comment]
@jamesemery @bhanugandham Since the initial error was in the codepath that's reading from the reference fasta, I think we need a copy of the reference being used (+ accompanying indices) to see if we can reproduce this error on our end.

**Comment by jamesemery** [comment]
@droazen `-R /mnt/d/data/gatk_bundle/hg38//Homo_sapiens_assembly38.fasta.gz` in the error from the first user. There could be some issue related to the gzipped index but that doesn't look like an unusual reference to me.
