### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in GenotypeGVCFs 

### ISSUE THREAD

**Issue by jamesemery** [broadinstitute/gatk#6357]
A user has encountered the following error when running GenotypeGVCFs on an input: 
```Using GATK jar /nics/d/home/hchen3/bin/gatk-4.1.2.0/gatk-package-4.1.2.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /nics/d/home/hchen3/bin/gatk-4.1.2.0/gatk-package-4.1.2.0-local.jar GenotypeGVCFs -R /lustre/haven/proj/UTHSC0013/Tristan_GATK/reference/genome.fa -V gendb:///lustre/haven/proj/UTHSC0013/Tristan_GATK//DB/chr7 -G StandardAnnotation --use-new-qual-calculator -O /lustre/haven/proj/UTHSC0013/Tristan_GATK//gvcf//merged//joint_called_gvcfs_chr7.vcf
23:15:47.053 WARN  GATKAnnotationPluginDescriptor - Redundant enabled annotation group (StandardAnnotation) is enabled for this tool by default
23:15:47.249 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/nics/d/home/hchen3/bin/gatk-4.1.2.0/gatk-package-4.1.2.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Jan 07, 2020 11:15:49 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
23:15:49.543 INFO  GenotypeGVCFs - ------------------------------------------------------------
23:15:49.545 INFO  GenotypeGVCFs - The Genome Analysis Toolkit (GATK) v4.1.2.0
23:15:49.546 INFO  GenotypeGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
23:15:49.547 INFO  GenotypeGVCFs - Executing as hchen3@acf-knl002 on Linux v3.10.0-514.26.1.el7.x86_64 amd64
23:15:49.548 INFO  GenotypeGVCFs - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_131-b12
23:15:49.548 INFO  GenotypeGVCFs - Start Date/Time: January 7, 2020 11:15:47 PM EST
23:15:49.549 INFO  GenotypeGVCFs - ------------------------------------------------------------
23:15:49.549 INFO  GenotypeGVCFs - ------------------------------------------------------------
23:15:49.551 INFO  GenotypeGVCFs - HTSJDK Version: 2.19.0
23:15:49.551 INFO  GenotypeGVCFs - Picard Version: 2.19.0
23:15:49.552 INFO  GenotypeGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2
23:15:49.552 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
23:15:49.552 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
23:15:49.552 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
23:15:49.552 INFO  GenotypeGVCFs - Deflater: IntelDeflater
23:15:49.553 INFO  GenotypeGVCFs - Inflater: IntelInflater
23:15:49.553 INFO  GenotypeGVCFs - GCS max retries/reopens: 20
23:15:49.553 INFO  GenotypeGVCFs - Requester pays: disabled
23:15:49.553 INFO  GenotypeGVCFs - Initializing engine
WARNING: No valid combination operation found for INFO field DS - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field InbreedingCoeff - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAC - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAF - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field DS - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field InbreedingCoeff - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAC - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAF - the field will NOT be part of INFO fields in the generated VCF records
23:16:27.971 INFO  GenotypeGVCFs - Done initializing engine
23:16:28.168 INFO  ProgressMeter - Starting traversal
23:16:28.169 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
WARNING: No valid combination operation found for INFO field DS - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field InbreedingCoeff - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAC - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAF - the field will NOT be part of INFO fields in the generated VCF records
23:20:28.785 INFO  GenotypeGVCFs - Shutting down engine
GENOMICSDB_TIMER,GenomicsDB iterator next() timer,Wall-clock time(s),0.11700176899999999,Cpu time(s),0.11079876499999991
[January 7, 2020 11:20:29 PM EST] org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 4.71 minutes.
Runtime.totalMemory()=2446327808
java.lang.ArrayIndexOutOfBoundsException: 5
	at org.broadinstitute.hellbender.tools.walkers.ReferenceConfidenceVariantContextMerger.generatePL(ReferenceConfidenceVariantContextMerger.java:652)
	at org.broadinstitute.hellbender.tools.walkers.ReferenceConfidenceVariantContextMerger.mergeRefConfidenceGenotypes(ReferenceConfidenceVariantContextMerger.java:543)
	at org.broadinstitute.hellbender.tools.walkers.ReferenceConfidenceVariantContextMerger.merge(ReferenceConfidenceVariantContextMerger.java:130)
	at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.apply(GenotypeGVCFs.java:310)
	at org.broadinstitute.hellbender.engine.VariantLocusWalker.lambda$traverse$0(VariantLocusWalker.java:136)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
	at org.broadinstitute.hellbender.engine.VariantLocusWalker.traverse(VariantLocusWalker.java:134)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1039)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)
``` 
 Based on the stacktrace I suspect an invalid value has snuck its way into `genotypeIndexMapsByPloidy[]` from `getIndexesOfRelevantAlleles` and that is causing the error.  I suspect it will be necessary to look at the combined input in question to evaluate what is happening.

**Comment by jsalt** [comment]
Hi, I am encountering a similar error attempting to run `GenotypeGVCFs` in `gatk v4.1.2.0`. It runs very briefly and writes a handful of variants from a single scaffold to the output file but then exits with `java.lang.ArrayIndexOutOfBoundsException` (see below). I have also tried adding the `-L` flag and an interval list, which performs similarly but outputs variants from a different scaffold. Any idea why this is happening or what I can do to overcome this problem? I have run `GenomicsDBImport` and `GenotypeGVCFs` successfully in the past (same version, same computer) on a different dataset, so I'm not sure what about this data is causing the problem. Any guidance is much appreciated!

Thanks,
Jessie

 ```
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /home/jsalt/gatk-4.1.2.0/gatk-package-4.1.2.0-local.jar GenotypeGVCFs -R /nfs/data1/jsalt/3RAD/colinus_virginianus_13May2017_V3Fw6_newchrom.fasta -V gendb://odont_cyr_8_snp_db -O odont_cyr_8_snp_db.vcf
14:59:47.866 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/jsalt/gatk-4.1.2.0/gatk-package-4.1.2.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Feb 03, 2020 2:59:59 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
14:59:59.674 INFO  GenotypeGVCFs - ------------------------------------------------------------
14:59:59.675 INFO  GenotypeGVCFs - The Genome Analysis Toolkit (GATK) v4.1.2.0
14:59:59.675 INFO  GenotypeGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
15:00:09.686 INFO  GenotypeGVCFs - Executing as jsalt@mustard on Linux v3.10.0-957.1.3.el7.x86_64 amd64
15:00:09.686 INFO  GenotypeGVCFs - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_192-b01
15:00:09.687 INFO  GenotypeGVCFs - Start Date/Time: February 3, 2020 2:59:47 PM CST
15:00:09.687 INFO  GenotypeGVCFs - ------------------------------------------------------------
15:00:09.687 INFO  GenotypeGVCFs - ------------------------------------------------------------
15:00:09.688 INFO  GenotypeGVCFs - HTSJDK Version: 2.19.0
15:00:09.688 INFO  GenotypeGVCFs - Picard Version: 2.19.0
15:00:09.689 INFO  GenotypeGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2
15:00:09.689 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
15:00:09.689 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
15:00:09.689 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
15:00:09.689 INFO  GenotypeGVCFs - Deflater: IntelDeflater
15:00:09.689 INFO  GenotypeGVCFs - Inflater: IntelInflater
15:00:09.689 INFO  GenotypeGVCFs - GCS max retries/reopens: 20
15:00:09.689 INFO  GenotypeGVCFs - Requester pays: disabled
15:00:09.690 INFO  GenotypeGVCFs - Initializing engine
WARNING: No valid combination operation found for INFO field AC - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field AF - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field AN - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field DS - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field FS - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field InbreedingCoeff - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAC - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAF - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field QD - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field SOR - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field AC - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field AF - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field AN - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field DS - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field FS - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field InbreedingCoeff - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAC - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAF - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field QD - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field QD - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field SOR - the field will NOT be part of INFO fields in the generated VCF records
15:02:24.449 INFO  FeatureManager - Using codec BEDCodec to read file file:///scratch/jsalt-test/ABBA-BABA/vcf/cv-genome-uce-coords-newchrom-500flank.bed
15:02:24.508 INFO  IntervalArgumentCollection - Processing 9612471 bp from intervals
15:02:24.531 INFO  GenotypeGVCFs - Done initializing engine
15:02:24.609 INFO  ProgressMeter - Starting traversal
15:02:24.609 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
WARNING: No valid combination operation found for INFO field AC - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field AF - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field AN - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field DS - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field FS - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field InbreedingCoeff - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAC - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAF - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field QD - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field SOR - the field will NOT be part of INFO fields in the generated VCF records
15:02:25.234 INFO  GenotypeGVCFs - Shutting down engine
GENOMICSDB_TIMER,GenomicsDB iterator next() timer,Wall-clock time(s),0.017439521000000003,Cpu time(s),0.016764516000000004
[February 3, 2020 3:02:25 PM CST] org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 0.40 minutes.
Runtime.totalMemory()=700973056
java.lang.ArrayIndexOutOfBoundsException: 3
        at org.broadinstitute.hellbender.tools.walkers.ReferenceConfidenceVariantContextMerger.generatePL(ReferenceConfidenceVariantContextMerger.java:652)
        at org.broadinstitute.hellbender.tools.walkers.ReferenceConfidenceVariantContextMerger.mergeRefConfidenceGenotypes(ReferenceConfidenceVariantContextMerger.java:543)
        at org.broadinstitute.hellbender.tools.walkers.ReferenceConfidenceVariantContextMerger.merge(ReferenceConfidenceVariantContextMerger.java:130)
        at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.apply(GenotypeGVCFs.java:310)
        at org.broadinstitute.hellbender.engine.VariantLocusWalker.lambda$traverse$0(VariantLocusWalker.java:136)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
        at org.broadinstitute.hellbender.engine.VariantLocusWalker.traverse(VariantLocusWalker.java:134)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1039)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
        at org.broadinstitute.hellbender.Main.main(Main.java:291)
```

**Comment by ldgauthier** [comment]
This would be a lot easier to debug if we got data to reproduce the error: https://gatk.broadinstitute.org/hc/en-us/articles/360035889671

**Comment by erika8181** [comment]
Hi, I encountered a similar error attempting to run GenotypeGVCFs in gatk v4.1.4.1. 
It ran very briefly and writed few variants to the output file but then exited with java.lang.ArrayIndexOutOfBoundsException. 

I solved the problem (I created a merged vcf) by performing bgzip (and tabix) of each gvcf file before running GenomicsDBImport and GenotypeGVCFs.
I don't know if it could be a solution also for your issues.

command:
for P in my_gvcf.list
do
bgzip -c $P.g.vcf > $P\.g.vcf.gz

tabix -p vcf $P.g.vcf.gz
done

gatk --java-options "-Xmx4g -Xms4g" GenomicsDBImport --genomicsdb-workspace-path my_database --sample-name-map sample_map --batch-size 50 --consolidate true --tmp-dir=tmp/ --reader-threads 5 -L file.bed

gatk --java-options "-Xmx12g -Xms12g" GenotypeGVCFs -R hg19.fa -V gendb://my_database -O global.vcf --new-qual --tmp-dir=tmp/

**Comment by ldgauthier** [comment]
Hi @erika8181 ,

I'm glad you were able to find a workaround.  Hopefully that will be helpful for the other users as well.  I've seen pretty strange things when files aren't indexed properly, so it was the tabix step in your solution that got me thinking.  Can you try running GATK IndexFeatureFile on your failing input (non-gzipped) vcfs and then importing?

**Comment by erika8181** [comment]
Hi,

according to your suggestion, I uploaded the gz file both for failing and successful input gvcf

[failed_variants.g.vcf.gz](https://github.com/broadinstitute/gatk/files/4180953/failed_variants.g.vcf.gz)
[successful_variants.g.vcf.gz](https://github.com/broadinstitute/gatk/files/4180957/successful_variants.g.vcf.gz)

Thanks

**Comment by KevinCLydon** [comment]
@erika8181 That failed variants file seems to actually be a VCF, not a GVCF.  Is that the file you intended to upload?

**Comment by MDPostel** [comment]
Hello -- has this issue been solved? I am getting the same error ("gatk java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3"). Additionally, it looks like 0/0s in my g.VCFs are being converted to ./. for some reason. Not sure if this is related. Thanks in advance.

**Comment by sjclare** [comment]
I am having the same issue with exome capture sequencing on 7 samples. The CombineGVCFs always aborts for some reason so GenotypeGVCFs fails. 

I've tried the workaround someone posted but my chromosomes are large are so requires csi indexing. Hopefully it works but specifying intervals is a pain since I'm interested in the whole genome

**Comment by droazen** [comment]
@ldgauthier Is this related to any of the `GenotypeGVCFs` bugs you've fixed recently? @sjclare and @MDPostel, could you try again with the latest GATK release and report whether the issue persists?
