### ISSUE TITLE
Error in CombineGvcfs

### ISSUE THREAD

**Issue by ccartermices** [broadinstitute/gatk#6368]
Hi! I have used HaplotypeCaller to get gvcfs of a sample called xl4_70. They are gvcfs of scf1-128, scf1280-18, scf180-25 ... (use parameter "-L" to help with the division). Then i used CombineGvcfs to combine these 7 gvcfs with a sample into a gvcfs, but i got an error:

 Using GATK jar /home/cc/gatk/gatk_dir/gatk/build/libs/gatk-package-4.1.3.0-25-g8d88f6e-SNAPSHOT-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /home/cc/gatk/gatk_dir/gatk/build/libs/gatk-package-4.1.3.0-25-g8d88f6e-SNAPSHOT-local.jar CombineGVCFs -R /db_students1/cc/genetic_map/snp_calling/bbv18h27rm.fa --variant /db_students1/cc/gatk_out/tmp_vcf/raw_new52_off_xL4_70_1to128.g.vcf.gz --variant /db_students1/cc/gatk_out/tmp_vcf/raw_new52_off_xL4_70_1280to18.g.vcf.gz --variant /db_students1/cc/gatk_out/tmp_vcf/raw_new52_off_xL4_70_180to25.g.vcf.gz --variant /db_students1/cc/gatk_out/tmp_vcf/raw_new52_off_xL4_70_250to35.g.vcf.gz --variant /db_students1/cc/gatk_out/tmp_vcf/raw_new52_off_xL4_70_350to5.g.vcf.gz --variant /db_students1/cc/gatk_out/tmp_vcf/raw_new52_off_xL4_70_50to69.g.vcf.gz --variant /db_students1/cc/gatk_out/tmp_vcf/raw_new52_off_xL4_70_690to999.g.vcf.gz -O /db_students1/cc/gatk_out/raw_new52_off_xL4_70.g.vcf.gz
17:52:22.080 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/cc/gatk/gatk_dir/gatk/build/libs/gatk-package-4.1.3.0-25-g8d88f6e-SNAPSHOT-local.jar!/com/intel/gkl/native/libgkl_compression.so
Jan 11, 2020 5:52:23 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
17:52:23.841 INFO  CombineGVCFs - ------------------------------------------------------------
17:52:23.841 INFO  CombineGVCFs - The Genome Analysis Toolkit (GATK) v4.1.3.0-25-g8d88f6e-SNAPSHOT
17:52:23.841 INFO  CombineGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
17:52:23.842 INFO  CombineGVCFs - Executing as cc@hr18b on Linux v3.10.0-957.el7.x86_64 amd64
17:52:23.842 INFO  CombineGVCFs - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_212-b04
17:52:23.842 INFO  CombineGVCFs - Start Date/Time: January 11, 2020 5:52:22 PM CST
17:52:23.842 INFO  CombineGVCFs - ------------------------------------------------------------
17:52:23.842 INFO  CombineGVCFs - ------------------------------------------------------------
17:52:23.843 INFO  CombineGVCFs - HTSJDK Version: 2.20.3
17:52:23.843 INFO  CombineGVCFs - Picard Version: 2.20.5
17:52:23.843 INFO  CombineGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2
17:52:23.844 INFO  CombineGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
17:52:23.844 INFO  CombineGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
17:52:23.844 INFO  CombineGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
17:52:23.844 INFO  CombineGVCFs - Deflater: IntelDeflater
17:52:23.844 INFO  CombineGVCFs - Inflater: IntelInflater
17:52:23.844 INFO  CombineGVCFs - GCS max retries/reopens: 20
17:52:23.844 INFO  CombineGVCFs - Requester pays: disabled
17:52:23.844 INFO  CombineGVCFs - Initializing engine
17:52:24.462 INFO  FeatureManager - Using codec VCFCodec to read file file:///db_students1/cc/gatk_out/tmp_vcf/raw_new52_off_xL4_70_1to128.g.vcf.gz
17:52:24.561 INFO  FeatureManager - Using codec VCFCodec to read file file:///db_students1/cc/gatk_out/tmp_vcf/raw_new52_off_xL4_70_1280to18.g.vcf.gz
17:52:24.615 INFO  FeatureManager - Using codec VCFCodec to read file file:///db_students1/cc/gatk_out/tmp_vcf/raw_new52_off_xL4_70_180to25.g.vcf.gz
17:52:24.680 INFO  FeatureManager - Using codec VCFCodec to read file file:///db_students1/cc/gatk_out/tmp_vcf/raw_new52_off_xL4_70_250to35.g.vcf.gz
17:52:24.744 INFO  FeatureManager - Using codec VCFCodec to read file file:///db_students1/cc/gatk_out/tmp_vcf/raw_new52_off_xL4_70_350to5.g.vcf.gz
17:52:24.795 INFO  FeatureManager - Using codec VCFCodec to read file file:///db_students1/cc/gatk_out/tmp_vcf/raw_new52_off_xL4_70_50to69.g.vcf.gz
17:52:24.841 INFO  FeatureManager - Using codec VCFCodec to read file file:///db_students1/cc/gatk_out/tmp_vcf/raw_new52_off_xL4_70_690to999.g.vcf.gz
17:53:24.067 INFO  CombineGVCFs - Done initializing engine
17:53:24.121 INFO  ProgressMeter - Starting traversal
17:53:24.122 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
17:53:24.189 WARN  ReferenceConfidenceVariantContextMerger - Detected invalid annotations: When trying to merge variant contexts at location scaffold1159:34 the annotation MLEAC=[2, 0] was not a numerical value and was ignored
17:53:31.218 INFO  CombineGVCFs - Shutting down engine
[January 11, 2020 5:53:31 PM CST] org.broadinstitute.hellbender.tools.walkers.CombineGVCFs done. Elapsed time: 1.15 minutes.
Runtime.totalMemory()=2739404800
java.lang.IllegalStateException: The elements of the input Iterators are not sorted according to the comparator htsjdk.variant.variantcontext.VariantContextComparator
	at htsjdk.samtools.util.MergingIterator.next(MergingIterator.java:107)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.MultiVariantWalker.traverse(MultiVariantWalker.java:118)
	at org.broadinstitute.hellbender.engine.MultiVariantWalkerGroupedOnStart.traverse(MultiVariantWalkerGroupedOnStart.java:122)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)

Who can help me?

**Comment by lbergelson** [comment]
This looks like a bug.  I'm not sure if the issue is in the HaplotypeCaller output or in the way CombineGvcfs is merging things.  Could you run ValidateVariants on each of the vcfs and let us know if they pass?

**Comment by xue-222** [comment]
> 

have you solved now？
