### ISSUE TITLE
Intervals specified with .list should trim whitespace

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#6371]
Using a .list file for intervals doesn't trim white space appropriately and causes interval parsing to fail with strange errors.

For example the following line ending in a space causes an error in an interval .list file:
"20:1-100 " 

This fails with the following error:
```

A USER ERROR has occurred: Badly formed genome unclippedLoc: Failed to parse Genome Location string: 20:1-100 : For input string: "100 "

***********************************************************************
org.broadinstitute.hellbender.exceptions.UserException$MalformedGenomeLoc: Badly formed genome unclippedLoc: Failed to parse Genome Location string: 20:1-100 : For input string: "100 "
	at org.broadinstitute.hellbender.utils.GenomeLocParser.parseGenomeLoc(GenomeLocParser.java:328)
	at org.broadinstitute.hellbender.utils.IntervalUtils.intervalFileToList(IntervalUtils.java:375)
	at org.broadinstitute.hellbender.utils.IntervalUtils.parseIntervalArguments(IntervalUtils.java:279)
	at org.broadinstitute.hellbender.utils.IntervalUtils.loadIntervals(IntervalUtils.java:226)
	at org.broadinstitute.hellbender.cmdline.argumentcollections.IntervalArgumentCollection.parseIntervals(IntervalArgumentCollection.java:174)
	at org.broadinstitute.hellbender.cmdline.argumentcollections.IntervalArgumentCollection.getTraversalParameters(IntervalArgumentCollection.java:155)
	at org.broadinstitute.hellbender.cmdline.argumentcollections.IntervalArgumentCollection.getIntervals(IntervalArgumentCollection.java:111)
	at org.broadinstitute.hellbender.engine.GATKTool.initializeIntervals(GATKTool.java:513)
	at org.broadinstitute.hellbender.engine.GATKTool.onStartup(GATKTool.java:708)
	at org.broadinstitute.hellbender.engine.ReadWalker.onStartup(ReadWalker.java:50)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:137)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
	at org.broadinstitute.hellbender.Main.main(Main.java:292)
Caused by: java.lang.NumberFormatException: For input string: "100 "
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.broadinstitute.hellbender.utils.SimpleInterval.parsePositionThrowOnFailure(SimpleInterval.java:141)
	at org.broadinstitute.hellbender.utils.IntervalUtils.getResolvedIntervals(IntervalUtils.java:1122)
	at org.broadinstitute.hellbender.utils.GenomeLocParser.parseGenomeLoc(GenomeLocParser.java:308)

**Comment by cmnbroad** [comment]
Oh, turns out we do trim it, but we [throw away](https://github.com/broadinstitute/gatk/blob/a000a87cd67f0d786d6824816f70e2c58acffaec/src/main/java/org/broadinstitute/hellbender/utils/IntervalUtils.java#L406) the result and use the raw input.
