### ISSUE TITLE
Java exception in GATK vcf call from bam file

### ISSUE THREAD

**Issue by shashank-bgp** [broadinstitute/gatk#6384]
Hi,
I am trying to generate vcf using GATK pipeline from bam file, but everytime, I am getting the following exception:
01:13:15.801 INFO NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/data1/ngs/programs/gatk-4.0.0.0/gatk-package-4.0.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
01:13:16.075 INFO HaplotypeCaller - ------------------------------------------------------------
01:13:16.075 INFO HaplotypeCaller - The Genome Analysis Toolkit (GATK) v4.0.0.0
01:13:16.075 INFO HaplotypeCaller - For support and documentation go to https://software.broadinstitute.org/gatk/
01:13:16.076 INFO HaplotypeCaller - Executing as shashank@grande on Linux v3.13.0-79-generic amd64
01:13:16.076 INFO HaplotypeCaller - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_72-internal-b15
01:13:16.076 INFO HaplotypeCaller - Start Date/Time: January 18, 2020 1:13:15 AM IST
01:13:16.076 INFO HaplotypeCaller - ------------------------------------------------------------
01:13:16.076 INFO HaplotypeCaller - ------------------------------------------------------------
01:13:16.077 INFO HaplotypeCaller - HTSJDK Version: 2.13.2
01:13:16.077 INFO HaplotypeCaller - Picard Version: 2.17.2
01:13:16.077 INFO HaplotypeCaller - HTSJDK Defaults.COMPRESSION_LEVEL : 1
01:13:16.078 INFO HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
01:13:16.078 INFO HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
01:13:16.078 INFO HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
01:13:16.078 INFO HaplotypeCaller - Deflater: IntelDeflater
01:13:16.078 INFO HaplotypeCaller - Inflater: IntelInflater
01:13:16.078 INFO HaplotypeCaller - GCS max retries/reopens: 20
01:13:16.078 INFO HaplotypeCaller - Using google-cloud-java patch 6d11bef1c81f885c26b2b56c8616b7a705171e4f from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes
01:13:16.078 INFO HaplotypeCaller - Initializing engine
01:13:17.087 INFO HaplotypeCaller - Shutting down engine
[January 18, 2020 1:13:17 AM IST] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=2216689664
java.lang.NullPointerException
at org.broadinstitute.hellbender.utils.SequenceDictionaryUtils.getContigNames(SequenceDictionaryUtils.java:463)
at org.broadinstitute.hellbender.utils.SequenceDictionaryUtils.getCommonContigsByName(SequenceDictionaryUtils.java:457)
at org.broadinstitute.hellbender.utils.SequenceDictionaryUtils.compareDictionaries(SequenceDictionaryUtils.java:234)
at org.broadinstitute.hellbender.utils.SequenceDictionaryUtils.validateDictionaries(SequenceDictionaryUtils.java:150)
at org.broadinstitute.hellbender.utils.SequenceDictionaryUtils.validateDictionaries(SequenceDictionaryUtils.java:98)
at org.broadinstitute.hellbender.engine.GATKTool.validateSequenceDictionaries(GATKTool.java:621)
at org.broadinstitute.hellbender.engine.GATKTool.onStartup(GATKTool.java:563)
at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.onStartup(AssemblyRegionWalker.java:160)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:134)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:152)
at org.broadinstitute.hellbender.Main.mainEntry(Main.java:195)
at org.broadinstitute.hellbender.Main.main(Main.java:275)

I have tried with different versions of Java, still it persists.
Please suggest any solution.
Thank you.

**Comment by lbergelson** [comment]
@shashank-bgp Thanks for opening this as new issue.  Could you try with the latest version of GATK?

**Comment by shashank-bgp** [comment]
I tried with java 11 and above version, but as far as i have read, GATK works particularly with Java 8 version. So it's difficult to say that this is a problem of version.

**Comment by lbergelson** [comment]
Not the newest version of java, the newest version of GATK.  Use java 8 and [Gatk 4.1.4.1](https://github.com/broadinstitute/gatk/releases/download/4.1.4.1/gatk-4.1.4.1.zip).

**Comment by shashank-bgp** [comment]
@lbergelson , sure, i will try this.

**Comment by shashank-bgp** [comment]
Thank you @lbergelson, i figured out to get correct output.
