### ISSUE TITLE
Docker does not supply the right R version for AnalyzeCovariates

### ISSUE THREAD

**Issue by SebastianHollizeck** [broadinstitute/gatk#6393]
### Affected tool(s) or class(es)
AnalyzeCovariates 

### Affected version(s)
- [x] Latest public release version [v4.1.4.0] [hash:cec850f20311f0686fcf88510bc44e529590d78bec7076a603132115943c09e6]

### Description 
AnalyzeCovariates fails with 
```
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /gatk/gatk-package-4.1.4.0-local.jar AnalyzeCovariates -bqsr /researchers/sebastian.hollizeck/lowcWGS/IN-PM01004/Bam/IN-PM01004_rmd.recal.bam.recalTable -plots /researchers/sebastian.hollizeck/lowcWGS/IN-PM01004/Bam/AnalyzeCovariates.pdf
23:15:29.581 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gatk/gatk-package-4.1.4.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Jan 19, 2020 11:15:30 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
23:15:30.435 INFO  AnalyzeCovariates - ------------------------------------------------------------
23:15:30.437 INFO  AnalyzeCovariates - The Genome Analysis Toolkit (GATK) v4.1.4.0
23:15:30.437 INFO  AnalyzeCovariates - For support and documentation go to https://software.broadinstitute.org/gatk/
23:15:30.438 INFO  AnalyzeCovariates - Executing as shollizeck@papr-res-compute204.unix.petermac.org.au on Linux v3.10.0-1062.4.3.el7.x86_64 amd64
23:15:30.438 INFO  AnalyzeCovariates - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_212-8u212-b03-0ubuntu1.16.04.1-b03
23:15:30.438 INFO  AnalyzeCovariates - Start Date/Time: January 19, 2020 11:15:29 PM UTC
23:15:30.439 INFO  AnalyzeCovariates - ------------------------------------------------------------
23:15:30.439 INFO  AnalyzeCovariates - ------------------------------------------------------------
23:15:30.439 INFO  AnalyzeCovariates - HTSJDK Version: 2.20.3
23:15:30.439 INFO  AnalyzeCovariates - Picard Version: 2.21.1
23:15:30.439 INFO  AnalyzeCovariates - HTSJDK Defaults.COMPRESSION_LEVEL : 2
23:15:30.439 INFO  AnalyzeCovariates - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
23:15:30.440 INFO  AnalyzeCovariates - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
23:15:30.440 INFO  AnalyzeCovariates - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
23:15:30.440 INFO  AnalyzeCovariates - Deflater: IntelDeflater
23:15:30.440 INFO  AnalyzeCovariates - Inflater: IntelInflater
23:15:30.440 INFO  AnalyzeCovariates - GCS max retries/reopens: 20
23:15:30.440 INFO  AnalyzeCovariates - Requester pays: disabled
23:15:30.440 INFO  AnalyzeCovariates - Initializing engine
23:15:30.440 INFO  AnalyzeCovariates - Done initializing engine
23:15:30.790 INFO  AnalyzeCovariates - Generating csv file '/tmp/AnalyzeCovariates6611620304443967041.csv'
23:15:30.854 INFO  AnalyzeCovariates - Generating plots file '/researchers/sebastian.hollizeck/lowcWGS/IN-PM01004/Bam/AnalyzeCovariates.pdf'
23:15:31.932 INFO  AnalyzeCovariates - Shutting down engine
[January 19, 2020 11:15:31 PM UTC] org.broadinstitute.hellbender.tools.walkers.bqsr.AnalyzeCovariates done. Elapsed time: 0.04 minutes.
Runtime.totalMemory()=2161115136
org.broadinstitute.hellbender.utils.R.RScriptExecutorException: 
Rscript exited with 1
Command Line: Rscript -e tempLibDir = '/tmp/Rlib.2074992987327687075';source('/tmp/BQSR.6874121927957307421.R'); /tmp/AnalyzeCovariates6611620304443967041.csv /researchers/sebastian.hollizeck/lowcWGS/IN-PM01004/Bam/IN-PM01004_rmd.recal.bam.recalTable /researchers/sebastian.hollizeck/lowcWGS/IN-PM01004/Bam/AnalyzeCovariates.pdf
Stdout: WARNING: ignoring environment value of R_HOME

Stderr: During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_COLLATE failed, using "C" 
3: Setting LC_TIME failed, using "C" 
4: Setting LC_MESSAGES failed, using "C" 
5: Setting LC_MONETARY failed, using "C" 
6: Setting LC_PAPER failed, using "C" 
7: Setting LC_MEASUREMENT failed, using "C" 
Error in readRDS(pfile) : 
  cannot read workspace version 3 written by R 3.6.0; need R 3.5.0 or newer
Calls: source ... library -> find.package -> lapply -> FUN -> readRDS
Execution halted

	at org.broadinstitute.hellbender.utils.R.RScriptExecutor.getScriptException(RScriptExecutor.java:80)
	at org.broadinstitute.hellbender.utils.R.RScriptExecutor.getScriptException(RScriptExecutor.java:19)
	at org.broadinstitute.hellbender.utils.runtime.ScriptExecutor.executeCuratedArgs(ScriptExecutor.java:126)
	at org.broadinstitute.hellbender.utils.R.RScriptExecutor.exec(RScriptExecutor.java:126)
	at org.broadinstitute.hellbender.utils.recalibration.RecalUtils.generatePlots(RecalUtils.java:360)
	at org.broadinstitute.hellbender.tools.walkers.bqsr.AnalyzeCovariates.generatePlots(AnalyzeCovariates.java:329)
	at org.broadinstitute.hellbender.tools.walkers.bqsr.AnalyzeCovariates.doWork(AnalyzeCovariates.java:341)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
	at org.broadinstitute.hellbender.Main.main(Main.java:292)
```

when opening the docker container one can see installed version of R is 3.2.5

```
Singularity broadinstitute_gatk_sha256_cec850f20311f0686fcf88510bc44e529590d78bec7076a603132115943c09e6.sif:~> R --version

R version 3.2.5 (2016-04-14) -- "Very, Very Secure Dishes"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```

#### Steps to reproduce
Run any AnalyzeCovariates

#### Expected behavior
create plots

#### Actual behavior
Docker faceplants

**Comment by droazen** [comment]
Closing -- we're now on R 3.6.2
