### ISSUE TITLE
gcnvkernel module not found after setting up environment

### ISSUE THREAD

**Issue by Mentors4EDU** [broadinstitute/gatk#6467]
### Bug Report

Hi, after installing the conda environment and running `conda activate gatk` without errors, I seem to still have a problem importing the gcnvkernel module. Is there a way I can install it through pip or what is something I may have done wrong? I already went over the README and standard documentation, and don't think I missed a step.

### Affected tool(s) or class(es)
gvnvkernel, other expected modules

#### Expected behavior
Generate output file from my VCF

#### Actual behavior
```
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -DGATK_STACKTRACE_ON_USER_EXCEPTION=true -jar /home/gamer456148/gatk-4.1.4.1/gatk-package-4.1.4.1-local.jar GermlineCNVCaller --input var.vcf --run-mode CASE --contig-ploidy-calls X/prefix-calls --output-prefix regular.vcf --output testfile.vcf
21:21:12.277 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/gamer456148/gatk-4.1.4.1/gatk-package-4.1.4.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
Feb 23, 2020 9:21:12 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
21:21:12.543 INFO  GermlineCNVCaller - ------------------------------------------------------------
21:21:12.544 INFO  GermlineCNVCaller - The Genome Analysis Toolkit (GATK) v4.1.4.1
21:21:12.544 INFO  GermlineCNVCaller - For support and documentation go to https://software.broadinstitute.org/gatk/
21:21:12.544 INFO  GermlineCNVCaller - Executing as gamer456148@gamer456148-Inspiron-15-7579 on Linux v4.15.0-88-generic amd64
21:21:12.544 INFO  GermlineCNVCaller - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_191-b12
21:21:12.544 INFO  GermlineCNVCaller - Start Date/Time: February 23, 2020 9:21:12 PM EST
21:21:12.544 INFO  GermlineCNVCaller - ------------------------------------------------------------
21:21:12.544 INFO  GermlineCNVCaller - ------------------------------------------------------------
21:21:12.544 INFO  GermlineCNVCaller - HTSJDK Version: 2.21.0
21:21:12.544 INFO  GermlineCNVCaller - Picard Version: 2.21.2
21:21:12.544 INFO  GermlineCNVCaller - HTSJDK Defaults.COMPRESSION_LEVEL : 2
21:21:12.544 INFO  GermlineCNVCaller - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
21:21:12.544 INFO  GermlineCNVCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
21:21:12.545 INFO  GermlineCNVCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
21:21:12.545 INFO  GermlineCNVCaller - Deflater: IntelDeflater
21:21:12.545 INFO  GermlineCNVCaller - Inflater: IntelInflater
21:21:12.545 INFO  GermlineCNVCaller - GCS max retries/reopens: 20
21:21:12.545 INFO  GermlineCNVCaller - Requester pays: disabled
21:21:12.545 INFO  GermlineCNVCaller - Initializing engine
21:21:14.339 INFO  GermlineCNVCaller - Shutting down engine
[February 23, 2020 9:21:14 PM EST] org.broadinstitute.hellbender.tools.copynumber.GermlineCNVCaller done. Elapsed time: 0.03 minutes.
Runtime.totalMemory()=281542656
java.lang.RuntimeException: A required Python package ("gcnvkernel") could not be imported into the Python environment. This tool requires that the GATK Python environment is properly established and activated. Please refer to GATK README.md file for instructions on setting up the GATK Python environment.
	at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.checkPythonEnvironmentForPackage(PythonScriptExecutor.java:205)
	at org.broadinstitute.hellbender.tools.copynumber.GermlineCNVCaller.onStartup(GermlineCNVCaller.java:286)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:137)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
	at org.broadinstitute.hellbender.Main.main(Main.java:292)
Caused by: org.broadinstitute.hellbender.utils.python.PythonScriptExecutorException: 
python exited with 1
Command Line: python -c import gcnvkernel

Stdout: 
Stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gamer456148/anaconda3/envs/gatk/lib/python3.6/site-packages/gcnvkernel/__init__.py", line 1, in <module>
    from pymc3 import __version__ as pymc3_version
  File "/home/gamer456148/anaconda3/envs/gatk/lib/python3.6/site-packages/pymc3/__init__.py", line 5, in <module>
    from .distributions import *
  File "/home/gamer456148/anaconda3/envs/gatk/lib/python3.6/site-packages/pymc3/distributions/__init__.py", line 1, in <module>
    from . import timeseries
  File "/home/gamer456148/anaconda3/envs/gatk/lib/python3.6/site-packages/pymc3/distributions/timeseries.py", line 5, in <module>
    from .continuous import get_tau_sd, Normal, Flat
  File "/home/gamer456148/anaconda3/envs/gatk/lib/python3.6/site-packages/pymc3/distributions/continuous.py", line 12, in <module>
    from scipy import stats
  File "/home/gamer456148/anaconda3/envs/gatk/lib/python3.6/site-packages/scipy/stats/__init__.py", line 345, in <module>
    from .morestats import *
  File "/home/gamer456148/anaconda3/envs/gatk/lib/python3.6/site-packages/scipy/stats/morestats.py", line 12, in <module>
    from numpy.testing.decorators import setastest
ModuleNotFoundError: No module named 'numpy.testing.decorators'

	at org.broadinstitute.hellbender.utils.python.PythonExecutorBase.getScriptException(PythonExecutorBase.java:75)
	at org.broadinstitute.hellbender.utils.runtime.ScriptExecutor.executeCuratedArgs(ScriptExecutor.java:126)
	at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeArgs(PythonScriptExecutor.java:170)
	at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeCommand(PythonScriptExecutor.java:79)
	at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.checkPythonEnvironmentForPackage(PythonScriptExecutor.java:198)
	... 7 more
```

----

**Comment by cmnbroad** [comment]
@Mentors4EDU This issue has been fixed for the next release, but see [this comment](https://github.com/broadinstitute/gatk/issues/6396#issuecomment-576770330) for a short term fix. Feel free to reopen this ticket if you still have an issue or questions.
