### ISSUE TITLE
 -L loci.interval_list -L UNMAPPED causes java.nio.channels.ClosedChannelException near the end

### ISSUE THREAD

**Issue by bw2** [broadinstitute/gatk#6475]
### Affected tool(s) or class(es)
gatk PrintReads

### Affected version(s)
v4.1.4.1

### Description 
Command like
```
java -Xms2g -Xmx3g -jar gatk.jar PrintReads --gcs-project-for-requester-pays my-project -R hg38.fa -I gs://some-bucket/data.cram -L loci.interval_list -L UNMAPPED -O data.loci.bam
```
crashes near the end with this error:
```

05:03:04.672 INFO  PrintReads - Shutting down engine
[March 1, 2020 5:03:04 AM EST] org.broadinstitute.hellbender.tools.PrintReads done. Elapsed time: 18.22 minutes.
Runtime.totalMemory()=3094872064
htsjdk.samtools.util.RuntimeEOFException: java.nio.channels.ClosedChannelException
	at htsjdk.samtools.CRAMFileReader.queryUnmapped(CRAMFileReader.java:413)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryUnmapped(SamReader.java:543)
	at org.broadinstitute.hellbender.utils.iterators.SamReaderQueryingIterator.loadNextIterator(SamReaderQueryingIterator.java:129)
	at org.broadinstitute.hellbender.utils.iterators.SamReaderQueryingIterator.loadNextRecord(SamReaderQueryingIterator.java:111)
	at org.broadinstitute.hellbender.utils.iterators.SamReaderQueryingIterator.next(SamReaderQueryingIterator.java:151)
	at org.broadinstitute.hellbender.utils.iterators.SamReaderQueryingIterator.next(SamReaderQueryingIterator.java:29)
	at org.broadinstitute.hellbender.utils.iterators.SAMRecordToReadIterator.next(SAMRecordToReadIterator.java:27)
	at org.broadinstitute.hellbender.utils.iterators.SAMRecordToReadIterator.next(SAMRecordToReadIterator.java:13)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.ReadWalker.traverse(ReadWalker.java:94)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
	at org.broadinstitute.hellbender.Main.main(Main.java:292)
Caused by: java.nio.channels.ClosedChannelException
	at org.broadinstitute.hellbender.utils.nio.SeekableByteChannelPrefetcher.position(SeekableByteChannelPrefetcher.java:416)
	at htsjdk.samtools.seekablestream.SeekablePathStream.seek(SeekablePathStream.java:63)
	at htsjdk.samtools.CRAMFileReader.queryUnmapped(CRAMFileReader.java:402)
	... 23 more
```

#### Steps to reproduce
It looks to me like running with the two -L args (`-L loci.interval_list -L UNMAPPED`) causes this. 
Removing either one of them prevents the error, so my current work-around is to run 
PrintReads separately - once with `-L loci.interval_list` and once with `-L UNMAPPED`

**Comment by lbergelson** [comment]
I can reproduce this locally.  It's possible it's already with the major cram changes in the upcoming version of htsjdk, but I haven't tested that yet.

**Comment by cmnbroad** [comment]
Fix is next version of htsjdk https://github.com/samtools/htsjdk/pull/1533. GATK test to verify this is in https://github.com/broadinstitute/gatk/pull/7066.
