### ISSUE TITLE
HaplotypeCaller might be producing bogus reads with deletions at their alignment start during realignment to best haplotype step.

### ISSUE THREAD

**Issue by jamesemery** [broadinstitute/gatk#6490]
Two users have reported similar errors on the forums: 
https://gatk.broadinstitute.org/hc/en-us/community/posts/360057963511-HaplotypeCaller-error-Read-is-malformed-read-starts-with-deletion
https://gatk.broadinstitute.org/hc/en-us/community/posts/360058147791-read-starts-with-deletion-Cigar-4D150M

When examining the stacktrace, it appears the error is happening at the end of time when we are filling in reference confidence for a site based on reads from the AlleleLikelihoods object. Reads in that pool have been realigned based on their best Haplotype already so its feasible that we have introduced a regression somewhere in that code:
```
org.broadinstitute.hellbender.exceptions.UserException$MalformedRead: Read A01023:5:HMV7LDMXX:2:2473:11406:29324 chrY:13433535-13433720 is malformed: read starts with deletion. Cigar: 37D68M1I81M. Although the SAM spec technically permits such reads, this is often indicative of malformed files.
at org.broadinstitute.hellbender.utils.locusiterator.AlignmentStateMachine.stepForwardOnGenome(AlignmentStateMachine.java:274)
at org.broadinstitute.hellbender.utils.locusiterator.ReadStateManager.addReadsToSample(ReadStateManager.java:258)
at org.broadinstitute.hellbender.utils.locusiterator.ReadStateManager.collectPendingReads(ReadStateManager.java:177)
at org.broadinstitute.hellbender.utils.locusiterator.LocusIteratorByState.lazyLoadNextAlignmentContext(LocusIteratorByState.java:288)
at org.broadinstitute.hellbender.utils.locusiterator.LocusIteratorByState.hasNext(LocusIteratorByState.java:225)
at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.getPileupsOverReference(AssemblyBasedCallerUtils.java:443)
at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.ReferenceConfidenceModel.calculateRefConfidence(ReferenceConfidenceModel.java:195)
at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.callRegion(HaplotypeCallerEngine.java:645)
at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller.apply(HaplotypeCaller.java:212)
at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:200)
at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:173)
at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
at org.broadinstitute.hellbender.Main.main(Main.java:292)
```
This hypothesis is further evidenced by the fact that one user at least claims that their input file validates and that they couldn't find the problem reads by looking at the input files manually. We probably will want to look at an example file in the debugger to catch what is happening at this site. We have refactored a bunch of code adjacent to this function recently so its possible this is a recent regression.

**Comment by davidbenjamin** [comment]
There's a `leftAlignAlindels` in `realignReadsToTheirBestHaplotype`, and `leftAlignIndels` ends with `consolidateCigar`.  I'm pretty sure that in one of my recent PRs I rewrote `consolidateCigar` with a `CigarBuilder`, which automatically shaves leading deletions, but it seems like I must have lost that last improvement (to `consolidateCigar`, that is) during the final rebase.

**Comment by biosinodx** [comment]
I got the same problem with GATK v 4.15.0, and for all my samples, I receive an error message like the following:

A USER ERROR has occurred: Read ST-E00318:149:HVLGNCCXX:7:1101:20791:63349 chr1:38902419-38902480 is malformed: read starts with deletion. Cigar: 3D59M91H. Although the SAM spec technically permits such reads, this is often indicative of malformed files.

This is the bam file (aligned to hg38). Hope it help.
ST-E00318:149:HVLGNCCXX:7:1101:20791:63349      163     chr1    38902422        60      150M    =       38902590        318     TTATTTTTTTTTTTTTGAGATAGAGTCTCGCTTTGTCACCCGGGCTGGAGTACAGTGGCGCAATCTCAGGTCACTGTAACCTCTGCTTCCCAGGTTTAAGCGATTCTCCTGCCTTGGTCTCCTGGGTAGCTTGGATTACAGGTTCACCCC  AAAFFKKKKKKKKKKFF7FAK<F,F7<<,A,<FA<F7<AFA(<A,AFF,A,,7F<FFAAF7(,7AAKKK<F,7AAAF,77,FFKKA,<,,,,7<,7F,7A,A7AK,AA,A,77FK,A,,<<<FF,7,,<,<<FK,<<,,,,<A,,,,,,<  MC:Z:150M       MD:Z:21G19A73A1C6A18G3A2        PG:Z:bwamem     RG:Z:A  NM:i:7  MQ:i:60 UQ:i:89 AS:i:118
ST-E00318:149:HVLGNCCXX:7:1101:20791:63349      83      chr1    38902590        60      150M    =       38902422        -318    TTTTGTATTTTTAATAGAGACGGGGTTTCACCATGTTGGTCGGGCTGGTCTCGAACTCCTGACCTGATGATCCGCCCACCTCGGCCTCCCCAAGTGCTGGGATTACAGGCATAAGCCACCACACCCAGCCTTTGTTATTTTTTTTTAAAG  FF<7KKKKKFAKF<7KKF(<FKKKF<,KKFKKKKKKKKFFA<<KKK7FKKKKKFFFFKAAFKKKFFKKKFAKKFFFKKKKFFKKFAAKKKKKKFKKKKKKKKFKKKKKKKKKKKAKKKKKFFKKKKKKKKKKKKKKKKKK<KKKKFFFAA  MC:Z:150M       MD:Z:150        PG:Z:bwamem     RG:Z:A  NM:i:0  MQ:i:60 UQ:i:0  AS:i:150

**Comment by phpeters** [comment]
Hej,
thanks for working on this issue!
I just wanted to mention that this seems to be a problem on both sides of the alignment. I got the error with the HaplotypeCaller of GATK 4.15.0:
A USER ERROR has occurred: Read read1 is malformed: read ends with deletion. Cigar: 7H62M6I1D.

The entries in the bam file looks like this:

read1	163	2	19326229	60	68M7S	=	19326528	374	AGAGGATGGAGGCCACCGAGACCACAACTTTTCCAATCATTTTTTTTTTTCTGTTTTTTTTTTTTTTTTTTGTTT	=9@:;?>;;?::===>>9?:?>>===>>??>?>>=?>>=:?:???>????00-;;?@????@???@?@?/0.1/.	MC:Z:75M	MD:Z:68	PG:Z:MarkDuplicates	RG:Z:something	NM:i:0	MQ:i:60	UQ:i:0	AS:i:68	XS:i:45
read1	83	2	19326528	60	75M	=	19326229	-374	CTTTATTTAACTTTCGCTGGAGCTCGTGACGTCGAACTTAGAAAAGGATGCCGAACGTAAATTTGCAGTTCCAAA	9??=??>=@?:@??9=:<>>?=:?9>->>9>?9>?>;?<?>????>>>=>;9>?>9><??>??=><@?@@;<@@<	B2:Z:ATCACAGAG	Q2:Z:A6AAAEE6E	BC:Z:ATTGATTCA	MC:Z:68M7S	MD:Z:75	PG:Z:MarkDuplicates	RG:Z:something	NM:i:0	MQ:i:60	UQ:i:0	AS:i:75	XS:i:0	QT:Z:AAAAAEEEE

Thanks a lot and best!
Philipp

**Comment by davidbenjamin** [comment]
@phpeters I expect that the fix in #6498 corrected both leading and trailing deletions, but please let us know if it did not.

**Comment by biosinodx** [comment]
Thanks a lot for taking care of this. I met different error this time. I
git clone it from the master. version info: The Genome Analysis Toolkit
(GATK) v4.1.5.0-16-gf1aea57-SNAPSHOT.

I ran four samples. All return the same problem when just started the
haplotypecaller. Here is the error message.
[March 17, 2020 1:54:08 PM EDT]
org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller
done. Elapsed time: 1.09 minutes.
Runtime.totalMemory()=4182245376
java.lang.IllegalStateException: Smith-Waterman alignment failure. Cigar =
64M40D29M with reference length 133 but expecting reference length of 413
ref =
AGCATCCGACAGCCTGGAGCAGCACCCACACCCCCAGTTGAGCAACTGATGGTCTGGAGCAGCACCCACAACCACAGGTGAACATCAGAGAGTCTGGAGCAGCGCCCACAACCCCAGGCGAGCATCTGACAGCCTGGAGCAGTGCCCAAACACCCAGGTGAGCATCTGACAGCATGGAGCAGCACCCATAGCCCAAGGTGAGCATCTGACAACCTGGAGCAGCACCCACACCCCGAGGTGAGCATCTGACCTCCCGGAGCAGGACCCATACCTCCAGGCGAGCATCTGAACCCATGGAGCAGCACCCACGCCCCCAGGCGAGCATCTGACCGAACAGAGCAGCACCCACAACCCCATGCGAGCATCTGTCAGCCTGGAACAGCACCCACAACCCCAGGTGAGCATCTGACAGC
path
AGCATCCGACAGCCTGGAGCAGCACCCACACCCCCAGTTGAGCAACTGATGGTCTGGAGCAGCACCCACAACCCCAGGTGAGCATCTGACAGC


David Benjamin <notifications@github.com> 于2020年3月17日周二 下午12:49写道：

**Comment by davidbenjamin** [comment]
@biosinodx Are you able to share a small chunk of the bam that exhibits the error for debugging?

**Comment by lindenb** [comment]
Hi, I got the same problem wih **4.1.6.0** : https://gatk.broadinstitute.org/hc/en-us/community/posts/360060174372-Haplotype-Caller-4-1-6-0-java-lang-IllegalStateException-Smith-Waterman-alignment-failure-

```

java.lang.IllegalStateException: Smith-Waterman alignment failure. Cigar = 275M with reference length 275 but expecting referenc
e length of 303 ref = GGACTGGTCATCAGCTACCCCGAGACCAGGACTGGTCATCAGCTACCCCGAGACCAGGACTGGTCATCAGCTACCCCGAGACCAGGACTGGTCATCAGCTACCCCG
AGACCAGGACTGGTCATCAGCTACCCCGAGAACAGGACTGGTCATCAGCTACCCCGAGACCAGGACTGGTCATCAGCTACCCCGAGACCAGGACTGGTCATCAGCTACCCCGAGACCAGGACTGGTCA
TCAGCTACTCCGAGACCAGCATGGAGAGGTTTGCTGATGGTTGGCTGACTGCTAGTGTGAGCACTTGTC path GGACTGGTCATCAGCTACCCCGAGACCAGGACTGGTCATCAGCTACCCCGAGA
CCAGGACTGGTCATCAGCTACCCCGAGACCAGGACTGGTCATCAGCTACCCCGAGAACAGGACTGGTCATCAGCTACCCCGAGAACAGGACTGGTCATCAGCTACCCCGAGACCAGGACTGGTCATCA
GCTACCCCGAGACCAGGACTGGTCATCAGCTACTCCGAGACCAGCATGGAGAGGTTTGCTGATGGTTGGCTGACTGCTAGTGTGAGCACTTGTC
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.readthreading.ReadThreadingAssembler.findBestPaths(ReadTh
readingAssembler.java:354)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.readthreading.ReadThreadingAssembler.assembleKmerGraphsAn
dHaplotypeCall(ReadThreadingAssembler.java:196)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.readthreading.ReadThreadingAssembler.runLocalAssembly(Rea
dThreadingAssembler.java:146)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.assembleReads(AssemblyBasedCalle
rUtils.java:269)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.callRegion(HaplotypeCallerEngine.ja
va:541)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller.apply(HaplotypeCaller.java:212)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:200)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:173)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)

```

**Comment by lindenb** [comment]
@davidbenjamin  here is a link to a minimal bam with the error: https://nextcloud-bird.univ-nantes.fr/index.php/s/CkFc66MsjCNLywr

**Comment by riederd** [comment]
Hi, I got this as well but with Mutect2 (gatk 4.1.6.0):

 java.lang.IllegalStateException: Smith-Waterman alignment failure. Cigar = 348M with reference length 348 but expecting reference length of 378 ref = CATACGCGTATACACACAATATAGGC
ATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAG
GCATTGCATACGCGTATACACACAAAATAGGCATTGTATACGCGTATACACACAAAATAGGCATTGTATACGCGTATACACACAAAATAGGCATTGTATACGCGTATACACACAAAATAGGCATTGTATACGCGTATACAATATAGGCATTGTATACGCGTATACAATATAGGC pat
h CATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAGGC
ATTGCATACGCGTATACACACAAAATAGGCATTGCATACGCGTATACACACAAAATAGGCATTGTATACGCGTATACACACAAAATAGGCATTGTATACGCGTATACACACAAAATAGGCATTGTATACGCGTATACAATATATGCATTGTATACGCGTATACAATATATGC
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.readthreading.ReadThreadingAssembler.findBestPaths(ReadThreadingAssembler.java:354)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.readthreading.ReadThreadingAssembler.assembleKmerGraphsAndHaplotypeCall(ReadThreadingAssembler.java:196)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.readthreading.ReadThreadingAssembler.runLocalAssembly(ReadThreadingAssembler.java:146)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.assembleReads(AssemblyBasedCallerUtils.java:269)
        at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2Engine.callRegion(Mutect2Engine.java:226)
        at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2.apply(Mutect2.java:299)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:200)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:173)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
        at org.broadinstitute.hellbender.Main.main(Main.java:292)

**Comment by riederd** [comment]
BTW: if I use gatk-4.1.4.1 with the same input it works fine.

**Comment by davidbenjamin** [comment]
Thank you @lindenb for the minimal bam.  I will fix it ASAP.
