### ISSUE TITLE
Mutect2 gatk 4.1.6.0: java.lang.IllegalStateException: Smith-Waterman alignment failure

### ISSUE THREAD

**Issue by riederd** [broadinstitute/gatk#6529]
Hi,

I got a java.lang.IllegalStateException: Smith-Waterman alignment failure in Mutect2 (gatk 4.1.6.0).
When running the same input with the same options using gatk 4.1.4.1 the files get processed without error.

Here the exception output:
java.lang.IllegalStateException: Smith-Waterman alignment failure. Cigar = 348M with reference length 348 but expecting reference length of 378 ref = CATACGCGTATACACACAATATAGGC
ATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAG
GCATTGCATACGCGTATACACACAAAATAGGCATTGTATACGCGTATACACACAAAATAGGCATTGTATACGCGTATACACACAAAATAGGCATTGTATACGCGTATACACACAAAATAGGCATTGTATACGCGTATACAATATAGGCATTGTATACGCGTATACAATATAGGC pat
h CATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAGGC
ATTGCATACGCGTATACACACAAAATAGGCATTGCATACGCGTATACACACAAAATAGGCATTGTATACGCGTATACACACAAAATAGGCATTGTATACGCGTATACACACAAAATAGGCATTGTATACGCGTATACAATATATGCATTGTATACGCGTATACAATATATGC
at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.readthreading.ReadThreadingAssembler.findBestPaths(ReadThreadingAssembler.java:354)
at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.readthreading.ReadThreadingAssembler.assembleKmerGraphsAndHaplotypeCall(ReadThreadingAssembler.java:196)
at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.readthreading.ReadThreadingAssembler.runLocalAssembly(ReadThreadingAssembler.java:146)
at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.assembleReads(AssemblyBasedCallerUtils.java:269)
at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2Engine.callRegion(Mutect2Engine.java:226)
at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2.apply(Mutect2.java:299)
at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:200)
at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:173)
at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
at org.broadinstitute.hellbender.Main.main(Main.java:292)

**Comment by nalcala** [comment]
I am running into the same issue in about 10% of my samples (out of ~120)

**Comment by lindenb** [comment]
Same problem. I posted a minimal bam here: https://nextcloud-bird.univ-nantes.fr/index.php/s/CkFc66MsjCNLywr

**Comment by hsiaoyi0504** [comment]
I met the same error when trying to create vcf files for PoN.
