### ISSUE TITLE
GATK 4.1.6.0 haplotypecaller ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Fazulur** [broadinstitute/gatk#6552]
Dear GATK team,

I am getting errors with haplotyper of GATK 4.1.6.0 when i run gatk-variant pipeline from bcbio on one WGS sample. I am getting same error when i run using same version of GATK installed on my machine.

### Error log

[April 15, 2020 8:14:35 AM GMT] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 0.80 minutes.
Runtime.totalMemory()=4151902208
java.lang.ArrayIndexOutOfBoundsException: 6
        at org.broadinstitute.hellbender.utils.GenotypeUtils.computeDiploidGenotypeCounts(GenotypeUtils.java:70)
        at org.broadinstitute.hellbender.tools.walkers.annotator.ExcessHet.calculateEH(ExcessHet.java:86)
        at org.broadinstitute.hellbender.tools.walkers.annotator.ExcessHet.annotate(ExcessHet.java:74)
        at org.broadinstitute.hellbender.tools.walkers.annotator.VariantAnnotatorEngine.annotateContext(VariantAnnotatorEngine.java:293)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerGenotypingEngine.makeAnnotatedCall(HaplotypeCallerGenotypingEngine.java:365)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerGenotypingEngine.assignGenotypeLikelihoods(HaplotypeCallerGenotypingEngine.java:189)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.callRegion(HaplotypeCallerEngine.java:608)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller.apply(HaplotypeCaller.java:212)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:200)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:173)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
        at org.broadinstitute.hellbender.Main.main(Main.java:292)
Using GATK jar BCBIO/v1.2.0_updated/anaconda/share/gatk4-4.1.6.0-0/gatk-package-4.1.6.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms4g -Xmx13g -XX:+UseSerialGC -Djava.io.tmpdir=test-bcbio-1.2.0-wgs-hapmap/scratch/bcbiotx/tmpnhcoi74c -jar BCBIO/v1.2.0_updated/anaconda/share/gatk4-4.1.6.0-0/gatk-package-4.1.6.0-local.jar HaplotypeCaller -R BCBIO/v1.2.0_updated/genomes/Hsapiens/hg38/seq/hg38.fa --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation QualByDepth --annotation ReadPosRankSumTest --annotation RMSMappingQuality --annotation BaseQualityRankSumTest --annotation FisherStrand --annotation MappingQuality --annotation DepthPerAlleleBySample --annotation Coverage -I test-bcbio-1.2.0-wgs-hapmap/scratch/align/HAPMAP_S5_L005/HAPMAP_S5_L005-sort-recal.bam -L test-bcbio-1.2.0-wgs-hapmap/scratch/gatk-haplotype/chrY/HAPMAP_S5_L005-joint-chrY_0_16134738-regions.bed --interval-set-rule INTERSECTION --annotation ClippingRankSumTest --annotation DepthPerSampleHC --native-pair-hmm-threads 1 --emit-ref-confidence GVCF -GQB 10 -GQB 20 -GQB 30 -GQB 40 -GQB 60 -GQB 80 -ploidy 1 --output test-bcbio-1.2.0-wgs-hapmap/scratch/bcbiotx/tmpnhcoi74c/HAPMAP_S5_L005-joint-chrY_0_16134738.vcf.gz

#### Command i used

gatk --java-options '-Xms4g -Xmx13g -XX:+UseSerialGC -Djava.io.tmpdir=test-bcbio-1.2.0-wgs-hapmap/scratch/bcbiotx/tmpv1ztgr87' HaplotypeCaller -R BCBIO/v1.2.0_updated/genomes/Hsapiens/hg38/seq/hg38.fa --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation QualByDepth --annotation ReadPosRankSumTest --annotation RMSMappingQuality --annotation BaseQualityRankSumTest --annotation FisherStrand --annotation MappingQuality --annotation DepthPerAlleleBySample --annotation Coverage -I test-bcbio-1.2.0-wgs-hapmap/scratch/align/HAPMAP_S5_L005/HAPMAP_S5_L005-sort-recal.bam -L chrUn_KI270583v1:1-340 --interval-set-rule INTERSECTION --annotation ClippingRankSumTest --annotation DepthPerSampleHC --native-pair-hmm-threads 1 --emit-ref-confidence GVCF -GQB 10 -GQB 20 -GQB 30 -GQB 40 -GQB 60 -GQB 80 -ploidy 2 --output test-bcbio-1.2.0-wgs-hapmap/scratch/bcbiotx/tmpv1ztgr87/HAPMAP_S5_L005-joint-chrUn_KI270583v1_0_340.vcf.gz

Please help me to resolve this issue.

Thanks In Advance
Fazulur Rehaman

**Comment by droazen** [comment]
@ldgauthier This error is occurring in the calculation of the `ExcessHet` annotation (a PL index goes out-of-bounds while we're trying to get the max likelihood in `GenotypeUtils.computeDiploidGenotypeCounts()`). I know this code has been touched somewhat recently as part of the work on the Gnarly pipeline -- any ideas as to what might be causing it?

**Comment by ldgauthier** [comment]
It's really hard to say without data to debug.  @Fazulur can you upload a piece of the bam that can reproduce the error?  https://gatk.broadinstitute.org/hc/en-us/articles/360035889671

**Comment by Fazulur** [comment]
Dear @ldgauthier,

I uploaded small bam file, command i used & error log to gatk ftp provided in the above link & fille name is
**gatk_snippetbam_arrayboundissue.tar.gz**

Please help me to resolve this issue.

Thanks In Advance
Fazulur Rehaman

**Comment by ldgauthier** [comment]
We really shouldn't be calculating HWE or excess heterozygosity on haploid contigs, and I can fix that.  Can you give me an example of a diploid failure @Fazulur ?

**Comment by Fazulur** [comment]
Dear  @ldgauthier,

Thanks a lot for your quick response. I am getting error only with chrY and not with any diploid ones. 

Please let me know once you fix this issue wtih ChrY.

Thanks In Advance
