### ISSUE TITLE
Mutect2 IndexOutOfBoundException 4.1.7.0

### ISSUE THREAD

**Issue by DanielAmsel** [broadinstitute/gatk#6605]
### Affected tool(s) or class(es)
mutect2

### Affected version(s)
4.1.7.0

### Description 
I several times now observed an IndexOutOfBoundException in Mutect2. 
Seems to be file specific.
I run this in nextflow 19.10.0

I am open for hints. 
Kind regards!

```
Command error:
  14:15:19.210 INFO  ProgressMeter -          17:44868376             34.1               8548240         250606.9
  14:15:29.214 INFO  ProgressMeter -          17:57594001             34.3               8591020         250636.0
  14:15:39.219 INFO  ProgressMeter -          17:70805091             34.4               8635430         250711.9
  14:15:49.219 INFO  ProgressMeter -          17:79595935             34.6               8665160         250363.6
  14:15:59.220 INFO  ProgressMeter -           18:8951018             34.8               8700660         250184.4
  14:16:09.220 INFO  ProgressMeter -          18:18750419             34.9               8733540         249932.1
  14:16:19.220 INFO  ProgressMeter -          18:33362396             35.1               8782590         250142.7
  14:16:29.221 INFO  ProgressMeter -          18:47557520             35.3               8830240         250311.5
  14:16:39.224 INFO  ProgressMeter -          18:61732084             35.4               8877870         250478.0
  14:16:49.230 INFO  ProgressMeter -          18:75390202             35.6               8923700         250591.9
  14:16:59.238 INFO  ProgressMeter -           19:4254509             35.8               8947170         250079.8
  14:17:09.252 INFO  ProgressMeter -          19:13499637             35.9               8978420         249787.8
  14:17:19.268 INFO  ProgressMeter -          19:23216815             36.1               9011160         249539.8
  14:17:29.278 INFO  ProgressMeter -          19:31344990             36.3               9038470         249145.0
  14:17:39.298 INFO  ProgressMeter -          19:41157554             36.4               9071590         248912.2
  14:17:49.867 INFO  ProgressMeter -          19:42798895             36.6               9077130         247866.1
  14:17:59.042 INFO  VectorLoglessPairHMM - Time spent in setup for JNI call : 0.15517662000000002
  14:17:59.043 INFO  PairHMM - Total compute time in PairHMM computeLogLikelihoods() : 13.012444101000002
  14:17:59.043 INFO  SmithWatermanAligner - Total compute time in java Smith-Waterman : 45.65 sec
  14:17:59.043 INFO  Mutect2 - Shutting down engine
  [May 15, 2020 2:17:59 PM UTC] org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2 done. Elapsed time: 36.79 minutes.
  Runtime.totalMemory()=3793223680
  java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.lambda$getGermlineAltAlleleFrequencies$27(SomaticGenotypingEngine.java:351)
        at java.util.stream.ReferencePipeline$6$1.accept(ReferencePipeline.java:244)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.util.stream.DoublePipeline.toArray(DoublePipeline.java:508)
        at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.getGermlineAltAlleleFrequencies(SomaticGenotypingEngine.java:353)
        at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.getNegativeLogPopulationAFAnnotation(SomaticGenotypingEngine.java:336)
        at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.callMutations(SomaticGenotypingEngine.java:155)
        at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2Engine.callRegion(Mutect2Engine.java:252)
        at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2.apply(Mutect2.java:299)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:200)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:173)
  Using at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
  Runninat org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
      jaat org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
  GIN_geat org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
  Using at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
  Runninat org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
      jaat org.broadinstitute.hellbender.Main.main(Main.java:292)
  Using GATK jar /gatk/gatk-package-4.1.7.0-local.jar

Running:
java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /gatk/gatk-package-4.1.7.0-local.jar Mutect2 -R BROAD_hg19.fasta -I recal.bam --f1r2-tar-gz f1r2.tar.gz --germline-resource gnomad.genomes.r2.1.sites.INFO_ANNOTATIONS_FIXED.vcf.bgz --native-pair-hmm-threads 9 -O somatic_varcall.vcf
```

**Comment by droazen** [comment]
@davidbenjamin @takutosato A possible Mutect2 bug for you

**Comment by DanielAmsel** [comment]
Hi, so when I run the tool without the gnomAD reference, everything seems to work.
Let me know if I can be of help or if you have any hints for solving the problem.
Kind regards,
Daniel

**Comment by davidbenjamin** [comment]
@DanielAmsel Are you using an AF-only gnomAD VCF from the GATK best practices google bucket (gs://gatk-best-practices/somatic-b37/af-only-gnomad.raw.sites.vcf for hg19/b37 and gs://gatk-best-practices/somatic-hg38/af-only-gnomad.hg38.vcf.gz for hg38)?

**Comment by DanielAmsel** [comment]
Hi @davidbenjamin, thank you very much for clarification. I used a different VCF file (gnomad.genomes.r2.1.sites.INFO_ANNOTATIONS_FIXED.vcf.bgz)  in combination with the Broad hg19 genome: `ftp://ftp.broadinstitute.org/pub/seq/references/Homo_sapiens_assembly19.fasta`

Now everything works perfectly fine for me.
Thank you very much again!
