### ISSUE TITLE
LiftoverVCF does not liftover INFO/END for SVs

### ISSUE THREAD

**Issue by jjfarrell** [broadinstitute/gatk#6725]
----

### Affected tool(s) or class(es)
GATK LiftoverVcf

### Affected version(s)
gatk/4.1.7.0

### Description 

The LiftoverVcf generates the following error. The error occurs with SVs where the INFO/END is not also lifted over. This results in INFO/END before the site start position which triggers the error.
```
Using GATK jar /share/pkg.7/gatk/4.1.7.0/install/bin/gatk-package-4.1.7.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /share/pkg.7/gatk/4.1.7.0/install/bin/gatk-package-4.1.7.0-local.jar LiftoverVcf -I b37/HG002_SVs_Tier1_v0.6.vcf.gz -O b38/HG002_SVs_Tier1_v0.6.hg38.vcf.gz -CHAIN grch37_to_grch38.over.chain.gz --REJECT b38/HG002_SVs_Tier1_v0.6.rejected.vcf.gz -R /restricted/projectnb/casa/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa
10:20:35.165 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/share/pkg.7/gatk/4.1.7.0/install/bin/gatk-package-4.1.7.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
[Sun Jul 26 10:20:35 EDT 2020] LiftoverVcf  --INPUT b37/HG002_SVs_Tier1_v0.6.vcf.gz --OUTPUT b38/HG002_SVs_Tier1_v0.6.hg38.vcf.gz --CHAIN grch37_to_grch38.over.chain.gz --REJECT b38/HG002_SVs_Tier1_v0.6.rejected.vcf.gz --REFERENCE_SEQUENCE /restricted/projectnb/casa/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa  --WARN_ON_MISSING_CONTIG false --LOG_FAILED_INTERVALS true --WRITE_ORIGINAL_POSITION false --WRITE_ORIGINAL_ALLELES false --LIFTOVER_MIN_MATCH 1.0 --ALLOW_MISSING_FIELDS_IN_HEADER false --RECOVER_SWAPPED_REF_ALT false --TAGS_TO_REVERSE AF --TAGS_TO_DROP MAX_AF --DISABLE_SORT false --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 2 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
Jul 26, 2020 10:20:35 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
[Sun Jul 26 10:20:35 EDT 2020] Executing as farrell@scc-hadoop.bu.edu on Linux 3.10.0-1062.12.1.el7.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_121-b13; Deflater: Intel; Inflater: Intel; Provider GCS is available; Picard version: Version:4.1.7.0
INFO    2020-07-26 10:20:35     LiftoverVcf     Loading up the target reference genome.
INFO    2020-07-26 10:20:56     LiftoverVcf     Lifting variants over and sorting (not yet writing the output file.)
[Sun Jul 26 10:20:56 EDT 2020] picard.vcf.LiftoverVcf done. Elapsed time: 0.36 minutes.
Runtime.totalMemory()=5861015552
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
htsjdk.tribble.TribbleException: Badly formed variant context at location chr1:596697; getEnd() was 596797 but this VariantContext contains an END key with value 532177
        at htsjdk.variant.variantcontext.VariantContext.validateStop(VariantContext.java:1401)
        at htsjdk.variant.variantcontext.VariantContext.validate(VariantContext.java:1383)
        at htsjdk.variant.variantcontext.VariantContext.<init>(VariantContext.java:489)
        at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:647)
        at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:638)
        at picard.util.LiftoverUtils.liftVariant(LiftoverUtils.java:92)
        at picard.vcf.LiftoverVcf.doWork(LiftoverVcf.java:426)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:25)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
        at org.broadinstitute.hellbender.Main.main(Main.java:292)

```

#### Steps to reproduce

Download vcf from here:

ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/analysis/NIST_SVs_Integration_v0.6/HG002_SVs_Tier1_v0.6.vcf.gz

gatk LiftoverVcf \
     -I b37/HG002_SVs_Tier1_v0.6.vcf.gz \
     -O b38/HG002_SVs_Tier1_v0.6.hg38.vcf.gz \
     -CHAIN grch37_to_grch38.over.chain.gz \
     --REJECT b38/HG002_SVs_Tier1_v0.6.rejected.vcf.gz \
     -R /restricted/projectnb/casa/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa

#### Expected behavior
The original b37 vcf has a deletion here:

1 532077 ACATTCATGCTCACTCATACACACCCAGATCATATATACACTCGTGCACACATTCACACTCATACACACCCAAATCATACTCACATTCATGCACACATGTT A
SVLEN=-100;;SVTYPE=DEL;END=532177;sizecat=100to299;

The liftover to hg38 should look like this:
chr1 596697 REF=ACATTCATGCTCACTCATACACACCCAGATCATATATACACTCGTGCACACATTCACACTCATACACACCCAAATCATACTCACATTCATGCACACATGTT
ALT=A
INFO Fields
SVLEN=-100; SVTYPE=DEL;END=596797;sizecat=100to299;

The error message suggests LiftoverVcf  is not updating the INFO/END field from 532177 to 596797 and an error is being triggered since the END is before the start. An incorrect INFO/END will cause problems with tabix and other programs.

#### Actual behavior
It generates an error when the INFO/END is before the start and aborts..

----

## Feature request
Liftover  INFO/END 

### Description
 
The INFO/END position also needs to be updated-not just the site position.

**Comment by cmnbroad** [comment]
Closing and moving to Picard repo since its a Picard tool https://github.com/broadinstitute/picard/issues/1552.
