### ISSUE TITLE
CombineGVCFs java.lang.NullPointerException

### ISSUE THREAD

**Issue by gbrandt6** [broadinstitute/gatk#6766]
### Affected tool(s) or class(es)
CombineGVCFs

### Affected version(s)
- GATK 4.1.8.1 (Latest release as of 08/24/20)

### Description 
User is running CombineGVCFs and getting a java error java.lang.NullPointerException
at org.broadinstitute.hellbender.tools.walkers.annotator.allelespecific.StrandBiasUtils.encode(StrandBiasUtils.java:52). This issue was discussed at the GATK Office Hours meeting.

### Associated forum post
https://gatk.broadinstitute.org/hc/en-us/community/posts/360072644931-Combine-GVCF-generate-java-lang-NullPointerException

Command:
time "$gatk" CombineGVCFs \
-G StandardAnnotation \
-G AS_StandardAnnotation \
-R "$ref_gen"/ucsc.hg19.fasta \
-V /paedwy/disk1/yangyxt/wes/8_samples_20200819/gvcfs/A200272.HC.g.vcf.gz \
-V /paedwy/disk1/yangyxt/wes/8_samples_20200819/gvcfs/A200273.HC.g.vcf.gz \
-V /paedwy/disk1/yangyxt/wes/8_samples_20200819/gvcfs/A200274.HC.g.vcf.gz \
-V /paedwy/disk1/yangyxt/wes/8_samples_20200819/gvcfs/A200313.HC.g.vcf.gz \
-V /paedwy/disk1/yangyxt/wes/8_samples_20200819/gvcfs/A200314.HC.g.vcf.gz \
-V /paedwy/disk1/yangyxt/wes/8_samples_20200819/gvcfs/A200315.HC.g.vcf.gz \
-V /paedwy/disk1/yangyxt/wes/8_samples_20200819/gvcfs/PID20-006.HC.g.vcf.gz \
-V /paedwy/disk1/yangyxt/wes/8_samples_20200819/gvcfs/PID20-007.HC.g.vcf.gz \
-V /paedwy/disk1/yangyxt/wes/backup_gvcfs/all_wes_samples.g.vcf \
-O /paedwy/disk1/yangyxt/wes/backup_gvcfs/all_wes_samples_plus_${sample_batch}.g.vcf.gz && echo "Combine_gvcfs done"

Error Log:
```
12:01:36.798 WARN GATKAnnotationPluginDescriptor - Redundant enabled annotation group (StandardAnnotation) is enabled for this tool by default
12:01:36.824 INFO NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/yangyxt/software/gatk-4.1.8.1/gatk-package-4.1.8.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
Aug 24, 2020 12:01:37 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
12:01:37.108 INFO CombineGVCFs - ------------------------------------------------------------
12:01:37.108 INFO CombineGVCFs - The Genome Analysis Toolkit (GATK) v4.1.8.1
12:01:37.108 INFO CombineGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
12:01:37.108 INFO CombineGVCFs - Executing as yangyxt@paedyl01 on Linux v3.10.0-1062.18.1.el7.x86_64 amd64
12:01:37.108 INFO CombineGVCFs - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_161-b12
12:01:37.108 INFO CombineGVCFs - Start Date/Time: August 24, 2020 12:01:36 PM HKT
12:01:37.108 INFO CombineGVCFs - ------------------------------------------------------------
12:01:37.108 INFO CombineGVCFs - ------------------------------------------------------------
12:01:37.109 INFO CombineGVCFs - HTSJDK Version: 2.23.0
12:01:37.109 INFO CombineGVCFs - Picard Version: 2.22.8
12:01:37.109 INFO CombineGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2
12:01:37.109 INFO CombineGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
12:01:37.109 INFO CombineGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
12:01:37.109 INFO CombineGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
12:01:37.109 INFO CombineGVCFs - Deflater: IntelDeflater
12:01:37.109 INFO CombineGVCFs - Inflater: IntelInflater
12:01:37.109 INFO CombineGVCFs - GCS max retries/reopens: 20
12:01:37.109 INFO CombineGVCFs - Requester pays: disabled
12:01:37.109 INFO CombineGVCFs - Initializing engine
12:01:37.474 INFO FeatureManager - Using codec VCFCodec to read file file:///paedwy/disk1/yangyxt/wes/8_samples_20200819/gvcfs/A200272.HC.g.vcf.gz
12:01:37.645 INFO FeatureManager - Using codec VCFCodec to read file file:///paedwy/disk1/yangyxt/wes/8_samples_20200819/gvcfs/A200273.HC.g.vcf.gz
12:01:37.770 INFO FeatureManager - Using codec VCFCodec to read file file:///paedwy/disk1/yangyxt/wes/8_samples_20200819/gvcfs/A200274.HC.g.vcf.gz
12:01:37.889 INFO FeatureManager - Using codec VCFCodec to read file file:///paedwy/disk1/yangyxt/wes/8_samples_20200819/gvcfs/A200313.HC.g.vcf.gz
12:01:37.955 INFO FeatureManager - Using codec VCFCodec to read file file:///paedwy/disk1/yangyxt/wes/8_samples_20200819/gvcfs/A200314.HC.g.vcf.gz
12:01:38.062 INFO FeatureManager - Using codec VCFCodec to read file file:///paedwy/disk1/yangyxt/wes/8_samples_20200819/gvcfs/A200315.HC.g.vcf.gz
12:01:38.184 INFO FeatureManager - Using codec VCFCodec to read file file:///paedwy/disk1/yangyxt/wes/8_samples_20200819/gvcfs/PID20-006.HC.g.vcf.gz
12:01:38.311 INFO FeatureManager - Using codec VCFCodec to read file file:///paedwy/disk1/yangyxt/wes/8_samples_20200819/gvcfs/PID20-007.HC.g.vcf.gz
12:01:38.417 INFO FeatureManager - Using codec VCFCodec to read file file:///paedwy/disk1/yangyxt/wes/backup_gvcfs/all_wes_samples.g.vcf
12:01:49.097 INFO CombineGVCFs - Done initializing engine
12:01:49.113 INFO ProgressMeter - Starting traversal
12:01:49.113 INFO ProgressMeter - Current Locus Elapsed Minutes Variants Processed Variants/Minute
12:01:49.492 WARN ReferenceConfidenceVariantContextMerger - Detected invalid annotations: When trying to merge variant contexts at location chrM:63 the annotation MLEAC=[2, 0] was not a numerical value and was ignored
12:01:49.505 INFO CombineGVCFs - Shutting down engine
[August 24, 2020 12:01:49 PM HKT] org.broadinstitute.hellbender.tools.walkers.CombineGVCFs done. Elapsed time: 0.21 minutes.
Runtime.totalMemory()=6277824512
java.lang.NullPointerException
at org.broadinstitute.hellbender.tools.walkers.annotator.allelespecific.StrandBiasUtils.encode(StrandBiasUtils.java:52)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
at org.broadinstitute.hellbender.tools.walkers.annotator.allelespecific.StrandBiasUtils.makeRawAnnotationString(StrandBiasUtils.java:46)
at org.broadinstitute.hellbender.tools.walkers.annotator.allelespecific.AS_StrandBiasTest.combineRawData(AS_StrandBiasTest.java:115)
at org.broadinstitute.hellbender.tools.walkers.annotator.VariantAnnotatorEngine.combineAnnotations(VariantAnnotatorEngine.java:210)
at org.broadinstitute.hellbender.tools.walkers.ReferenceConfidenceVariantContextMerger.mergeAttributes(ReferenceConfidenceVariantContextMerger.java:318)
at org.broadinstitute.hellbender.tools.walkers.ReferenceConfidenceVariantContextMerger.merge(ReferenceConfidenceVariantContextMerger.java:142)
at org.broadinstitute.hellbender.tools.walkers.CombineGVCFs.endPreviousStates(CombineGVCFs.java:403)
at org.broadinstitute.hellbender.tools.walkers.CombineGVCFs.createIntermediateVariants(CombineGVCFs.java:217)
at org.broadinstitute.hellbender.tools.walkers.CombineGVCFs.apply(CombineGVCFs.java:162)
at org.broadinstitute.hellbender.engine.MultiVariantWalkerGroupedOnStart.apply(MultiVariantWalkerGroupedOnStart.java:131)
at org.broadinstitute.hellbender.engine.MultiVariantWalkerGroupedOnStart.apply(MultiVariantWalkerGroupedOnStart.java:106)
at org.broadinstitute.hellbender.engine.MultiVariantWalker.lambda$traverse$1(MultiVariantWalker.java:120)
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.Iterator.forEachRemaining(Iterator.java:116)
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
at org.broadinstitute.hellbender.engine.MultiVariantWalker.traverse(MultiVariantWalker.java:118)
at org.broadinstitute.hellbender.engine.MultiVariantWalkerGroupedOnStart.traverse(MultiVariantWalkerGroupedOnStart.java:163)
at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1049)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
at org.broadinstitute.hellbender.Main.main(Main.java:289)
Using GATK jar /home/yangyxt/software/gatk-4.1.8.1/gatk-package-4.1.8.1-local.jar
```

**Comment by droazen** [comment]
@ahaessly It looks like you might have been the last one to touch the relevant lines in `StrandBiasUtils` -- mind looking at this one to check whether your work on the MT pipeline might have triggered this? Thanks!

**Comment by droazen** [comment]
Note that we got a second report for this error here: https://github.com/broadinstitute/gatk/issues/6790

**Comment by ahaessly** [comment]
@gbrandt6 @bhanugandham do we have access to gvcfs that reproduce this problem? just want something real to test a fix with.

**Comment by gbrandt6** [comment]
@ahaessly not yet, I'll reach out to the user and let you know when it is available

**Comment by droazen** [comment]
@gbrandt6 Any update on this one?

**Comment by gbrandt6** [comment]
No update from the user, sent them a reminder just now.

**Comment by ahaessly** [comment]
I'm assuming that one or more of the GVCF files that are being combined are missing the AS_SB_TABLE attribute. what is the correct behavior in this case? Do we sum up just the data that we have? Or since we are missing some data, do we mark this combined value as missing?

**Comment by droazen** [comment]
@ahaessly Maybe @ldgauthier has an opinion on what the behavior should be in that case?

**Comment by droazen** [comment]
@gbrandt6 While you're at it, would you mind asking the user to try running with GATK 4.1.6.0, and reporting back as to whether the same error occurs? The annotation changes for the MT pipeline went in in version 4.1.7.0, so this would help narrow things down a bit.

**Comment by droazen** [comment]
@ldgauthier @ahaessly and I could use your thoughts/intuition as to what might be going wrong here. The `NullPointerException` the user reported is in the `StrandBiasUtils.encode()` method below, and it implies that either the `perAlleleValues` for one of the alleles is itself null, or the `perAlleleValues` for one of the alleles contains a null `Integer`. In `computeSBAnnotation()` we have `perAlleleValues.values().removeIf(Objects::isNull)`, which seems to rule out the former option (perAlleleValues itself being null), and implies that instead one of the individual Integers in the `List<Integer>` perAlleleValues for a particular allele is null. Any ideas on how that could happen?

```
    public static String encode(List<Integer> alleleValues) {
        return String.join(",", alleleValues.stream().map(i -> i.toString()).collect(Collectors.toList()));
    }

    protected static String makeRawAnnotationString(final List<Allele> vcAlleles, final Map<Allele, List<Integer>> perAlleleValues) {
        final List<String> alleleStrings = vcAlleles.stream()
                // does not replace a null value with zero list - only if the key is not in the map
                .map(a -> perAlleleValues.getOrDefault(a, ZERO_LIST))
                .map(StrandBiasUtils::encode)
                .collect(Collectors.toList());
        return String.join(AnnotationUtils.ALLELE_SPECIFIC_RAW_DELIM, alleleStrings);

    }

    public static Map<String, Object> computeSBAnnotation(VariantContext vc, AlleleLikelihoods<GATKRead, Allele> likelihoods, String key) {
        // calculate the annotation from the likelihoods
        // likelihoods can come from HaplotypeCaller or Mutect2 call to VariantAnnotatorEngine
        final Map<String, Object> annotations = new HashMap<>();
        final ReducibleAnnotationData<List<Integer>> myData = new AlleleSpecificAnnotationData<>(vc.getAlleles(),null);
        getStrandCountsFromLikelihoodMap(vc, likelihoods, myData, MIN_COUNT);
        Map<Allele, List<Integer>> perAlleleValues = new LinkedHashMap<>(myData.getAttributeMap());
        perAlleleValues.values().removeIf(Objects::isNull);
        final String annotationString = makeRawAnnotationString(vc.getAlleles(), perAlleleValues);
        annotations.put(key, annotationString);
        return annotations;
    }
```

**Comment by droazen** [comment]
@ahaessly and I have figured out what's triggering this error, and are working on a patch. It should be part of the next GATK release.

**Comment by droazen** [comment]
@gbrandt6 This was fixed in the PR https://github.com/broadinstitute/gatk/pull/6847, which will go out as part of GATK 4.1.9.0

**Comment by gbrandt6** [comment]
Thank you for the update, @droazen

**Comment by niyomiw** [comment]
I still got the same error with version 4.1.9.0. 

> Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/orange/reed/nhouse/Raw_seqs/SEQ9_samples/tmp
11:30:50.248 WARN  GATKAnnotationPluginDescriptor - Redundant enabled annotation group (StandardAnnotation) is enabled for this tool by default
11:30:50.478 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/apps/gatk/4.1.9.0/gatk-package-4.1.9.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Oct 26, 2020 11:30:50 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
11:30:50.791 INFO  CombineGVCFs - ------------------------------------------------------------
11:30:50.791 INFO  CombineGVCFs - The Genome Analysis Toolkit (GATK) v4.1.9.0
11:30:50.792 INFO  CombineGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
11:30:50.792 INFO  CombineGVCFs - Executing as nwijewardena@c3a-s8.ufhpc on Linux v3.10.0-1062.18.1.el7.x86_64 amd64
11:30:50.792 INFO  CombineGVCFs - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_31-b13
11:30:50.792 INFO  CombineGVCFs - Start Date/Time: October 26, 2020 11:30:50 AM EDT
11:30:50.793 INFO  CombineGVCFs - ------------------------------------------------------------
11:30:50.793 INFO  CombineGVCFs - ------------------------------------------------------------
11:30:50.794 INFO  CombineGVCFs - HTSJDK Version: 2.23.0
11:30:50.794 INFO  CombineGVCFs - Picard Version: 2.23.3
11:30:50.794 INFO  CombineGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2
11:30:50.794 INFO  CombineGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
11:30:50.794 INFO  CombineGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
11:30:50.794 INFO  CombineGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
11:30:50.795 INFO  CombineGVCFs - Deflater: IntelDeflater
11:30:50.795 INFO  CombineGVCFs - Inflater: IntelInflater
11:30:50.795 INFO  CombineGVCFs - GCS max retries/reopens: 20
11:30:50.795 INFO  CombineGVCFs - Requester pays: disabled
11:30:50.795 INFO  CombineGVCFs - Initializing engine
11:30:51.784 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_Cam19_01.raw_variants.g.vcf
11:30:51.907 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_AS217_1.raw_variants.g.vcf
11:30:52.003 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_Mon03.raw_variants.g.vcf
11:30:52.117 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_Mon02.raw_variants.g.vcf
11:30:52.208 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_Tur09_1.raw_variants.g.vcf
11:30:52.261 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_Tur11_01.raw_variants.g.vcf
11:30:52.342 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_EU01_1.raw_variants.g.vcf
11:30:52.431 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_EU02_1.raw_variants.g.vcf
11:30:52.549 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_EU03_1.raw_variants.g.vcf
11:30:52.627 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_EU20_1.raw_variants.g.vcf
11:30:52.742 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_Tur12_01.raw_variants.g.vcf
11:30:52.832 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_EU21_1.raw_variants.g.vcf
11:30:52.923 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_UK37_01.raw_variants.g.vcf
11:30:53.028 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_EU22_1.raw_variants.g.vcf
11:30:53.155 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_UK38_01.raw_variants.g.vcf
11:30:53.287 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_Mon01.raw_variants.g.vcf
11:30:53.348 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_UK41_01.raw_variants.g.vcf
11:30:53.440 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_Cam28_07.raw_variants.g.vcf
11:30:53.556 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_Cam34_01.raw_variants.g.vcf
11:30:53.660 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_AS01_1.raw_variants.g.vcf
11:30:53.727 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_AS02_1.raw_variants.g.vcf
11:30:53.805 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_AS184_1.raw_variants.g.vcf
11:30:53.894 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_AS201_1.raw_variants.g.vcf
11:30:54.000 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_AS209_1.raw_variants.g.vcf
11:34:25.030 INFO  CombineGVCFs - Done initializing engine
11:34:25.154 INFO  ProgressMeter - Starting traversal
11:34:25.155 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
11:34:25.473 WARN  ReferenceConfidenceVariantContextMerger - Detected invalid annotations: When trying to merge variant contexts at location DS235882:44 the annotation MLEAC=[1, 0] was not a numerical value and was ignored
11:34:25.944 INFO  CombineGVCFs - Shutting down engine
[October 26, 2020 11:34:25 AM EDT] org.broadinstitute.hellbender.tools.walkers.CombineGVCFs done. Elapsed time: 3.59 minutes.
Runtime.totalMemory()=3738173440
java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at htsjdk.variant.vcf.VCFUtils.parseVcfDouble(VCFUtils.java:262)
	at htsjdk.variant.vcf.AbstractVCFCodec.createGenotypeMap(AbstractVCFCodec.java:808)
	at htsjdk.variant.vcf.AbstractVCFCodec$LazyVCFGenotypesParser.parse(AbstractVCFCodec.java:121)
	at htsjdk.variant.variantcontext.LazyGenotypesContext.decode(LazyGenotypesContext.java:158)
	at htsjdk.variant.variantcontext.LazyGenotypesContext.ensureSampleNameMap(LazyGenotypesContext.java:180)
	at htsjdk.variant.variantcontext.GenotypesContext.getSampleNames(GenotypesContext.java:646)
	at htsjdk.variant.variantcontext.VariantContext.getSampleNames(VariantContext.java:1076)
	at org.broadinstitute.hellbender.tools.walkers.CombineGVCFs.getSamples(CombineGVCFs.java:361)
	at org.broadinstitute.hellbender.tools.walkers.CombineGVCFs.okayToSkipThisSite(CombineGVCFs.java:351)
	at org.broadinstitute.hellbender.tools.walkers.CombineGVCFs.mergeWithNewVCs(CombineGVCFs.java:327)
	at org.broadinstitute.hellbender.tools.walkers.CombineGVCFs.apply(CombineGVCFs.java:169)
	at org.broadinstitute.hellbender.engine.MultiVariantWalkerGroupedOnStart.apply(MultiVariantWalkerGroupedOnStart.java:131)
	at org.broadinstitute.hellbender.engine.MultiVariantWalkerGroupedOnStart.apply(MultiVariantWalkerGroupedOnStart.java:106)
	at org.broadinstitute.hellbender.engine.MultiVariantWalker.lambda$traverse$1(MultiVariantWalker.java:120)
	at org.broadinstitute.hellbender.engine.MultiVariantWalker$$Lambda$110/1374115041.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.MultiVariantWalker.traverse(MultiVariantWalker.java:118)
	at org.broadinstitute.hellbender.engine.MultiVariantWalkerGroupedOnStart.traverse(MultiVariantWalkerGroupedOnStart.java:163)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1049)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
Using GATK jar /apps/gatk/4.1.9.0/gatk-package-4.1.9.0-local.jar

**Comment by droazen** [comment]
@niyomiw That's not a `NullPointerException` -- it's a `NumberFormatException`, and is different from the issue reported in this ticket.

It's possible that one or more of your VCFs are malformed in some way. Could you try running `ValidateVariants` on the inputs?
