### ISSUE TITLE
hard filtering error , gate-4.1.8.1

### ISSUE THREAD

**Issue by elbakrifz** [broadinstitute/gatk#6789]
I was running this following CML :
java -Xmx8G -jar /Users/mac/Downloads/gatk-4.1.8.1/gatk-package-4.1.8.1-local.jar  VariantFiltration \ -R /Users/mac/Desktop/LmjFwholegenome_20070731_V5.2.fasta \ -V /Users/mac/Desktop/NGS-/57variants.vcf \ -o /Users/mac/Desktop/NGS-/59varians_filt.vcf \ --filter-expression "QD < 2.0 || MQ > 50" \  --filter-name "hard_filtering_snp  and I get : A USER ERROR has occurred: Illegal argument value: Positional arguments were provided ', -R{/Users/mac/Desktop/LmjFwholegenome_20070731_V5.2.fasta{ -V{/Users/mac/Desktop/NGS-/57variants.vcf{ -o{/Users/mac/Desktop/NGS-/59varians_filt.vcf{ --filter-expression{QD < 2.0 || MQ > 50{ }' but no positional argument is defined for this tool
how should I fix it and get a filter files ?!

**Comment by elbakrifz** [comment]
when I use this CML:  
 java -Xmx8G -jar /Users/mac/Downloads/gatk-4.1.8.1/gatk-package-4.1.8.1-local.jar  VariantFiltration  -R /Users/mac/Desktop/LmjFwholegenome_20070731_V5.2.fasta  -V /Users/mac/Desktop/NGS-/42variants.vcf   -O /Users/mac/Desktop/NGS-/42varians_filt.vcf  --filter-expression "QD < 2.0 || MQ > 50"   --filter-name "hard_filtering_snp" 

 I get : 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at org.apache.commons.jexl2.JexlArithmetic.toLong(JexlArithmetic.java:906)
	at org.apache.commons.jexl2.JexlArithmetic.compare(JexlArithmetic.java:718)
	at org.apache.commons.jexl2.JexlArithmetic.greaterThan(JexlArithmetic.java:790)
	at org.apache.commons.jexl2.Interpreter.visit(Interpreter.java:796)
	at org.apache.commons.jexl2.parser.ASTGTNode.jjtAccept(ASTGTNode.java:18)
	at org.apache.commons.jexl2.Interpreter.visit(Interpreter.java:1283)
	at org.apache.commons.jexl2.parser.ASTOrNode.jjtAccept(ASTOrNode.java:18)
	at org.apache.commons.jexl2.Interpreter.interpret(Interpreter.java:232)
	at org.apache.commons.jexl2.ExpressionImpl.evaluate(ExpressionImpl.java:65)
	at htsjdk.variant.variantcontext.JEXLMap.evaluateExpression(JEXLMap.java:186)
	at htsjdk.variant.variantcontext.JEXLMap.get(JEXLMap.java:95)
	at htsjdk.variant.variantcontext.JEXLMap.get(JEXLMap.java:15)
	at htsjdk.variant.variantcontext.VariantContextUtils.match(VariantContextUtils.java:338)
	at org.broadinstitute.hellbender.tools.walkers.filters.VariantFiltration.matchesFilter(VariantFiltration.java:453)
	at org.broadinstitute.hellbender.tools.walkers.filters.VariantFiltration.filter(VariantFiltration.java:407)
	at org.broadinstitute.hellbender.tools.walkers.filters.VariantFiltration.apply(VariantFiltration.java:354)
	at org.broadinstitute.hellbender.engine.VariantWalker.lambda$traverse$0(VariantWalker.java:104)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.VariantWalker.traverse(VariantWalker.java:102)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1049)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)

**Comment by droazen** [comment]
You should post these kinds of questions on our support forum (https://gatk.broadinstitute.org/hc/en-us/community/topics), rather than in our github issue tracker. Github issues are for bug reports only.
