### ISSUE TITLE
GenomicsDB Duplicate Sample Name Error

### ISSUE THREAD

**Issue by gbrandt6** [broadinstitute/gatk#6793]
### Affected tool(s) or class(es)
GenomicsDBImport

### Affected version(s)
-4.1.8.1, 4.1.6.0

### Description 
Two users are running GenomicsDBImport and getting a Duplicate Sample Name Error and both have reported that they do not have duplicate sample names in their map files. @nalinigans @mlathara does this look like a user issue or bug with GenomicsDBImport?

### First Example
Please see this link for more info: https://gatk.broadinstitute.org/hc/en-us/community/posts/360072797951--GenomicsDBException-Duplicate-sample-name-found-?page=1#community_comment_360012681791

`gatk --java-options "-Xmx16g -Xms16g" GenomicsDBImport --batch-size 24 --reader-threads 12 --genomicsdb-update-workspace-path /rooted3/langley/work/home/chuck/rad/SFARI/SSC_hg38/WGS/CPRs_100_proto/DB_chr1  --intervals chr1:118739963-147510543  --verbosity DEBUG  -V /rooted3/langley/work/home/chuck/rad/SFARI/SSC_hg38/WGS/phase2_CPRs/SSC00007_CPR/SSC00007.haplotypeCalls.CPR.er.raw.vcf.gz`

```
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx16g -Xms16g -jar /afs/genomecenter.ucdavis.edu/software/gatk/4.1.6.0/lssc0-linux/gatk-package-4.1.6.0-local.jar GenomicsDBImport --batch-size 24 --reader-threads 12 --genomicsdb-update-workspace-path /rooted3/langley/work/home/chuck/rad/SFARI/SSC_hg38/WGS/CPRs_100_proto/DB_chr1 --intervals chr1:118739963-147510543 --verbosity DEBUG -V /rooted3/langley/work/home/chuck/rad/SFARI/SSC_hg38/WGS/phase2_CPRs/SSC00007_CPR/SSC00007.haplotypeCalls.CPR.er.raw.vcf.gz
16:16:35.954 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/afs/genomecenter.ucdavis.edu/software/gatk/4.1.6.0/lssc0-linux/gatk-package-4.1.6.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
16:16:36.003 DEBUG NativeLibraryLoader - Extracting libgkl_compression.so to /tmp/libgkl_compression5245166187604030095.so
Aug 28, 2020 4:16:36 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
16:16:36.284 INFO  GenomicsDBImport - ------------------------------------------------------------
16:16:36.285 INFO  GenomicsDBImport - The Genome Analysis Toolkit (GATK) v4.1.6.0
16:16:36.285 INFO  GenomicsDBImport - For support and documentation go to https://software.broadinstitute.org/gatk/
16:16:36.285 INFO  GenomicsDBImport - Executing as chuck@rooted3 on Linux v4.15.0-66-generic amd64
16:16:36.285 INFO  GenomicsDBImport - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_265-8u265-b01-0ubuntu2~16.04-b01
16:16:36.286 INFO  GenomicsDBImport - Start Date/Time: August 28, 2020 4:16:35 PM PDT
16:16:36.286 INFO  GenomicsDBImport - ------------------------------------------------------------
16:16:36.286 INFO  GenomicsDBImport - ------------------------------------------------------------
16:16:36.287 INFO  GenomicsDBImport - HTSJDK Version: 2.21.2
16:16:36.287 INFO  GenomicsDBImport - Picard Version: 2.21.9
16:16:36.289 INFO  GenomicsDBImport - HTSJDK Defaults.BUFFER_SIZE : 131072
16:16:36.289 INFO  GenomicsDBImport - HTSJDK Defaults.COMPRESSION_LEVEL : 2
16:16:36.289 INFO  GenomicsDBImport - HTSJDK Defaults.CREATE_INDEX : false
16:16:36.289 INFO  GenomicsDBImport - HTSJDK Defaults.CREATE_MD5 : false
16:16:36.289 INFO  GenomicsDBImport - HTSJDK Defaults.CUSTOM_READER_FACTORY :
16:16:36.289 INFO  GenomicsDBImport - HTSJDK Defaults.DISABLE_SNAPPY_COMPRESSOR : false
16:16:36.289 INFO  GenomicsDBImport - HTSJDK Defaults.EBI_REFERENCE_SERVICE_URL_MASK : https://www.ebi.ac.uk/ena/cram/md5/%s
16:16:36.289 INFO  GenomicsDBImport - HTSJDK Defaults.NON_ZERO_BUFFER_SIZE : 131072
16:16:36.290 INFO  GenomicsDBImport - HTSJDK Defaults.REFERENCE_FASTA : null
16:16:36.290 INFO  GenomicsDBImport - HTSJDK Defaults.SAM_FLAG_FIELD_FORMAT : DECIMAL
16:16:36.290 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
16:16:36.290 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
16:16:36.290 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
16:16:36.290 INFO  GenomicsDBImport - HTSJDK Defaults.USE_CRAM_REF_DOWNLOAD : false
16:16:36.290 DEBUG ConfigFactory - Configuration file values:
16:16:36.295 DEBUG ConfigFactory - gcsMaxRetries = 20
16:16:36.295 DEBUG ConfigFactory - gcsProjectForRequesterPays =
16:16:36.295 DEBUG ConfigFactory - gatk_stacktrace_on_user_exception = false
16:16:36.296 DEBUG ConfigFactory - samjdk.use_async_io_read_samtools = false
16:16:36.296 DEBUG ConfigFactory - samjdk.use_async_io_write_samtools = true
16:16:36.296 DEBUG ConfigFactory - samjdk.use_async_io_write_tribble = false
16:16:36.296 DEBUG ConfigFactory - samjdk.compression_level = 2
16:16:36.296 DEBUG ConfigFactory - spark.kryoserializer.buffer.max = 512m
16:16:36.296 DEBUG ConfigFactory - spark.driver.maxResultSize = 0
16:16:36.296 DEBUG ConfigFactory - spark.driver.userClassPathFirst = true
16:16:36.296 DEBUG ConfigFactory - spark.io.compression.codec = lzf
16:16:36.296 DEBUG ConfigFactory - spark.executor.memoryOverhead = 600
16:16:36.297 DEBUG ConfigFactory - spark.driver.extraJavaOptions =
16:16:36.297 DEBUG ConfigFactory - spark.executor.extraJavaOptions =
16:16:36.297 DEBUG ConfigFactory - codec_packages = [htsjdk.variant, htsjdk.tribble, org.broadinstitute.hellbender.utils.codecs]
16:16:36.297 DEBUG ConfigFactory - read_filter_packages = [org.broadinstitute.hellbender.engine.filters]
16:16:36.297 DEBUG ConfigFactory - annotation_packages = [org.broadinstitute.hellbender.tools.walkers.annotator]
16:16:36.297 DEBUG ConfigFactory - cloudPrefetchBuffer = 40
16:16:36.297 DEBUG ConfigFactory - cloudIndexPrefetchBuffer = -1
16:16:36.297 DEBUG ConfigFactory - createOutputBamIndex = true
16:16:36.298 INFO  GenomicsDBImport - Deflater: IntelDeflater
16:16:36.298 INFO  GenomicsDBImport - Inflater: IntelInflater
16:16:36.298 INFO  GenomicsDBImport - GCS max retries/reopens: 20
16:16:36.298 INFO  GenomicsDBImport - Requester pays: disabled
16:16:36.298 INFO  GenomicsDBImport - Initializing engine
16:16:36.523 WARN  GenomicsDBImport - genomicsdb-update-workspace-path was set, so ignoring specified intervals.The tool will use the intervals specified by the initial import
16:16:37.372 DEBUG GenomeLocParser - Prepared reference sequence contig dictionary
16:16:37.372 DEBUG GenomeLocParser -  chr1 (248956422 bp)
16:16:37.373 DEBUG GenomeLocParser -  chr2 (242193529 bp)
16:16:37.373 DEBUG GenomeLocParser -  chr3 (198295559 bp)
16:16:37.373 DEBUG GenomeLocParser -  chr4 (190214555 bp)
16:16:37.373 DEBUG GenomeLocParser -  chr5 (181538259 bp)
16:16:37.373 DEBUG GenomeLocParser -  chr6 (170805979 bp)
16:16:37.373 DEBUG GenomeLocParser -  chr7 (159345973 bp)
...many lines here...
16:16:37.524 DEBUG GenomeLocParser -  HLA-DRB1*15:01:01:01 (11080 bp)
16:16:37.524 DEBUG GenomeLocParser -  HLA-DRB1*15:01:01:02 (11571 bp)
16:16:37.524 DEBUG GenomeLocParser -  HLA-DRB1*15:01:01:03 (11056 bp)
16:16:37.524 DEBUG GenomeLocParser -  HLA-DRB1*15:01:01:04 (11056 bp)
16:16:37.524 DEBUG GenomeLocParser -  HLA-DRB1*15:02:01 (10313 bp)
16:16:37.524 DEBUG GenomeLocParser -  HLA-DRB1*15:03:01:01 (11567 bp)
16:16:37.524 DEBUG GenomeLocParser -  HLA-DRB1*15:03:01:02 (11569 bp)
16:16:37.524 DEBUG GenomeLocParser -  HLA-DRB1*16:02:01 (11005 bp)
16:16:37.546 INFO  IntervalArgumentCollection - Processing 28770581 bp from intervals
16:16:37.548 INFO  GenomicsDBImport - Done initializing engine
16:16:37.548 INFO  GenomicsDBImport - Callset Map JSON file will be re-written to /rooted3/langley/work/home/chuck/rad/SFARI/SSC_hg38/WGS/CPRs_100_proto/DB_chr1/callset.json
16:16:37.548 INFO  GenomicsDBImport - Incrementally importing to array - /rooted3/langley/work/home/chuck/rad/SFARI/SSC_hg38/WGS/CPRs_100_proto/DB_chr1/genomicsdb_array
16:16:37.549 INFO  ProgressMeter - Starting traversal
16:16:37.550 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Batches Processed   Batches/Minute
16:16:38.061 INFO  GenomicsDBImport - Shutting down engine
[August 28, 2020 4:16:38 PM PDT] org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport done. Elapsed time: 0.04 minutes.
Runtime.totalMemory()=16464216064
org.genomicsdb.exception.GenomicsDBException: Duplicate sample name found: SSC00007. Sample was originally in /rooted3/langley/work/home/chuck/rad/SFARI/SSC_hg38/WGS/phase2_CPRs/SSC00007_CPR/SSC00007.haplotypeCalls.CPR.er.raw.vcf.gz
at org.genomicsdb.importer.extensions.CallSetMapExtensions.checkDuplicateCallsetsForIncrementalImport(CallSetMapExtensions.java:270)
at org.genomicsdb.importer.extensions.CallSetMapExtensions.mergeCallsetsForIncrementalImport(CallSetMapExtensions.java:241)
at org.genomicsdb.importer.GenomicsDBImporter.<init>(GenomicsDBImporter.java:222)
at org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport.traverse(GenomicsDBImport.java:743)
at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
at org.broadinstitute.hellbender.Main.main(Main.java:292)
```

### Second Example
This user is running multiple chromosomes at a time in parallel
Please see this link for more info: https://gatk.broadinstitute.org/hc/en-us/community/posts/360072732791-Import-GVCFs-using-GenomicsDBImport-one-chromosome-at-a-time-and-parallel-the-jobs-encounter-a-Duplicate-Sample-Name-Error?page=1#community_comment_360012681711

`time ${gatk} --java-options "-Xmx8g -Xms2g" GenomicsDBImport --tmp-dir /paedwy/disk1/yangyxt/test_tmp --genomicsdb-update-workspace-path ${probe_dir}/genomicdbimport_chr${1} -R ${ref_gen}/ucsc.hg19.fasta --batch-size 0 --sample-name-map ${gvcf}/batch_cohort.sample_map --reader-threads 5 --intervals chr${1}`

```
01:07:01.704 INFO NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/yangyxt/software/gatk-4.1.8.1/gatk-package-4.1.8.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
Aug 29, 2020 1:07:01 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
01:07:02.001 INFO GenomicsDBImport - ------------------------------------------------------------
01:07:02.002 INFO GenomicsDBImport - The Genome Analysis Toolkit (GATK) v4.1.8.1
01:07:02.002 INFO GenomicsDBImport - For support and documentation go to https://software.broadinstitute.org/gatk/
01:07:02.002 INFO GenomicsDBImport - Executing as yangyxt@paedwy01 on Linux v3.10.0-957.10.1.el7.x86_64 amd64
01:07:02.002 INFO GenomicsDBImport - Java runtime: OpenJDK 64-Bit Server VM v11.0.1+13-LTS
01:07:02.003 INFO GenomicsDBImport - Start Date/Time: August 29, 2020 at 1:07:01 AM HKT
01:07:02.003 INFO GenomicsDBImport - ------------------------------------------------------------
01:07:02.003 INFO GenomicsDBImport - ------------------------------------------------------------
01:07:02.004 INFO GenomicsDBImport - HTSJDK Version: 2.23.0
01:07:02.005 INFO GenomicsDBImport - Picard Version: 2.22.8
01:07:02.005 INFO GenomicsDBImport - HTSJDK Defaults.COMPRESSION_LEVEL : 2
01:07:02.005 INFO GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
01:07:02.005 INFO GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
01:07:02.005 INFO GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
01:07:02.005 INFO GenomicsDBImport - Deflater: IntelDeflater
01:07:02.005 INFO GenomicsDBImport - Inflater: IntelInflater
01:07:02.006 INFO GenomicsDBImport - GCS max retries/reopens: 20
01:07:02.006 INFO GenomicsDBImport - Requester pays: disabled
01:07:02.006 INFO GenomicsDBImport - Initializing engine
01:07:02.331 WARN GenomicsDBImport - genomicsdb-update-workspace-path was set, so ignoring specified intervals.The tool will use the intervals specified by the initial import
01:07:02.702 INFO GenomicsDBLibLoader - GenomicsDB native library version : 1.3.0-e701905
01:07:02.868 INFO IntervalArgumentCollection - Processing 135534747 bp from intervals
01:07:02.869 INFO GenomicsDBImport - Done initializing engine
01:07:02.870 INFO GenomicsDBImport - Callset Map JSON file will be re-written to /paedwy/disk1/yangyxt/wes/healthy_bams_for_CNV/using_v6_probe/genomicdbimport_chr10/callset.json
01:07:02.870 INFO GenomicsDBImport - Incrementally importing to workspace - /paedwy/disk1/yangyxt/wes/healthy_bams_for_CNV/using_v6_probe/genomicdbimport_chr10
01:07:02.871 INFO ProgressMeter - Starting traversal
01:07:02.871 INFO ProgressMeter - Current Locus Elapsed Minutes Batches Processed Batches/Minute
01:07:03.006 INFO GenomicsDBImport - Shutting down engine
[August 29, 2020 at 1:07:03 AM HKT] org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=2147483648
org.genomicsdb.exception.GenomicsDBException: Duplicate sample name found: A130489. Sample was originally in /paedwy/disk1/yangyxt/wes/batch11_13/gvcfs/A130489.HC.g.vcf.gz
at org.genomicsdb.importer.extensions.CallSetMapExtensions.checkDuplicateCallsetsForIncrementalImport(CallSetMapExtensions.java:270)
at org.genomicsdb.importer.extensions.CallSetMapExtensions.mergeCallsetsForIncrementalImport(CallSetMapExtensions.java:241)
at org.genomicsdb.importer.GenomicsDBImporter.<init>(GenomicsDBImporter.java:252)
at org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport.traverse(GenomicsDBImport.java:745)
at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1049)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

**Comment by mlathara** [comment]
Hi,

@gbrandt6 can you let me know how to access the bug report files that the user pushed to [ftp](https://gatk.broadinstitute.org/hc/en-us/community/posts/360072797951/comments/360012763332)? Thanks!

**Comment by mlathara** [comment]
Haven't heard back from the users yet, but so far our investigation seems to indicate this is user error rather than a bug. One of the users did provide some files from their workspace as a bug report, and they indeed had a duplicate sample that they were [trying to import again](https://gatk.broadinstitute.org/hc/en-us/community/posts/360072797951/comments/360012763572).

The other user [has not responded](https://gatk.broadinstitute.org/hc/en-us/community/posts/360072732791/comments/360012681711) to the request for bug report (AFAIK).

**Comment by gbrandt6** [comment]
Thanks for the update @mlathara. I have not seen a response yet from the second user so it looks like user error.

**Comment by droazen** [comment]
Closing as resolved
