### ISSUE TITLE
FilterMutectCalls: alpha must be greater than 0 but got NaN

### ISSUE THREAD

**Issue by gbrandt6** [broadinstitute/gatk#6850]
### Affected tool(s) or class(es)
FilterMutectCalls and possibly Mutect2

### Affected version(s)
GATK 4.1.7.0, still occurs in 4.1.8.1

### Description 
User running Mutect2 in mitochondrial mode and ERC BP_RESOLUTION. Mutect2 is successful, however filter mutect calls has error message
`java.lang.IllegalArgumentException: alpha must be greater than 0 but got NaN`

Possible similar issue: #6202 
Complete stack trace:

```
Running:

    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx22G -Djava.io.tmpdir=/nobackup/lnsingh/MTRNA/tmp -jar /nobackupp16/swbuild/hsp/COVID19/anaconda3/envs/COVIRT_GATK/share/gatk4-4.1.7.0-0/gatk-package-4.1.7.0-local.jar FilterMutectCalls --disable-read-filter MappingQualityReadFilter --disable-read-filter MappingQualityNotZeroReadFilter --disable-read-filter MappingQualityAvailableReadFilter --mitochondria-mode true -R /nobackup/lnsingh/MTRNA/lib/rCRS.fa -V /nobackup/lnsingh/MTRNA/out/COVSUBJ_0121_1_N_HA_filtered.humanspliced.gvcf.gz -L MT -O /nobackup/lnsingh/MTRNA/out/COVSUBJ_0121_1_N_HA_filtered.humanspliced.filtered.gvcf.gz

07:33:14.927 WARN  GATKReadFilterPluginDescriptor - Disabled filter (MappingQualityReadFilter) is not enabled by this tool

07:33:14.928 WARN  GATKReadFilterPluginDescriptor - Disabled filter (MappingQualityNotZeroReadFilter) is not enabled by this tool

07:33:14.928 WARN  GATKReadFilterPluginDescriptor - Disabled filter (MappingQualityAvailableReadFilter) is not enabled by this tool

07:33:15.003 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/nobackupp16/swbuild/hsp/COVID19/anaconda3/envs/COVIRT_GATK/share/gatk4-4.1.7.0-0/gatk-package-4.1.7.0-local.jar!/com/intel/gkl/native/libgkl_compression.so

Sep 20, 2020 7:33:15 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine

INFO: Failed to detect whether we are running on Google Compute Engine.

07:33:15.360 INFO  FilterMutectCalls - ------------------------------------------------------------

07:33:15.361 INFO  FilterMutectCalls - The Genome Analysis Toolkit (GATK) v4.1.7.0

07:33:15.361 INFO  FilterMutectCalls - For support and documentation go to https://software.broadinstitute.org/gatk/

07:33:15.361 INFO  FilterMutectCalls - Executing as lnsingh@pfe26 on Linux v4.12.14-122.23.1.20200609-nasa amd64

07:33:15.361 INFO  FilterMutectCalls - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_152-release-1056-b12

07:33:15.361 INFO  FilterMutectCalls - Start Date/Time: September 20, 2020 7:33:14 AM PDT

07:33:15.361 INFO  FilterMutectCalls - ------------------------------------------------------------

07:33:15.361 INFO  FilterMutectCalls - ------------------------------------------------------------

07:33:15.362 INFO  FilterMutectCalls - HTSJDK Version: 2.21.2

07:33:15.362 INFO  FilterMutectCalls - Picard Version: 2.21.9

07:33:15.362 INFO  FilterMutectCalls - HTSJDK Defaults.COMPRESSION_LEVEL : 2

07:33:15.362 INFO  FilterMutectCalls - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false

07:33:15.362 INFO  FilterMutectCalls - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true

07:33:15.362 INFO  FilterMutectCalls - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false

07:33:15.362 INFO  FilterMutectCalls - Deflater: IntelDeflater

07:33:15.362 INFO  FilterMutectCalls - Inflater: IntelInflater

07:33:15.363 INFO  FilterMutectCalls - GCS max retries/reopens: 20

07:33:15.363 INFO  FilterMutectCalls - Requester pays: disabled

07:33:15.363 INFO  FilterMutectCalls - Initializing engine

07:33:16.008 INFO  FeatureManager - Using codec VCFCodec to read file file:///nobackup/lnsingh/MTRNA/out/COVSUBJ_0121_1_N_HA_filtered.humanspliced.gvcf.gz

07:33:16.053 INFO  IntervalArgumentCollection - Processing 16569 bp from intervals

07:33:16.059 INFO  FilterMutectCalls - Done initializing engine

07:33:16.157 INFO  ProgressMeter - Starting traversal

07:33:16.157 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute

07:33:16.158 INFO  FilterMutectCalls - Starting pass 0 through the variants

07:33:17.341 INFO  FilterMutectCalls - Finished pass 0 through the variants

07:33:17.404 INFO  FilterMutectCalls - Shutting down engine

[September 20, 2020 7:33:17 AM PDT] org.broadinstitute.hellbender.tools.walkers.mutect.filtering.FilterMutectCalls done. Elapsed time: 0.04 minutes.

Runtime.totalMemory()=1256194048

java.lang.IllegalArgumentException: alpha must be greater than 0 but got NaN

at org.broadinstitute.hellbender.utils.Utils.validateArg(Utils.java:727)

at org.broadinstitute.hellbender.utils.param.ParamUtils.isPositive(ParamUtils.java:165)

at org.broadinstitute.hellbender.tools.walkers.readorientation.BetaDistributionShape.<init>(BetaDistributionShape.java:13)

at org.broadinstitute.hellbender.tools.walkers.mutect.clustering.BinomialCluster.getFuzzyBinomial(BinomialCluster.java:43)

at org.broadinstitute.hellbender.tools.walkers.mutect.clustering.BinomialCluster.<init>(BinomialCluster.java:17)

at org.broadinstitute.hellbender.tools.walkers.mutect.clustering.SomaticClusteringModel.initializeClusters(SomaticClusteringModel.java:184)

at org.broadinstitute.hellbender.tools.walkers.mutect.clustering.SomaticClusteringModel.learnAndClearAccumulatedData(SomaticClusteringModel.java:325)

at org.broadinstitute.hellbender.tools.walkers.mutect.filtering.Mutect2FilteringEngine.learnParameters(Mutect2FilteringEngine.java:153)

at org.broadinstitute.hellbender.tools.walkers.mutect.filtering.FilterMutectCalls.afterNthPass(FilterMutectCalls.java:165)

at org.broadinstitute.hellbender.engine.MultiplePassVariantWalker.traverse(MultiplePassVariantWalker.java:44)

at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)

at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)

at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)

at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)

at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)

at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)

at org.broadinstitute.hellbender.Main.main(Main.java:292)
```

**Comment by GATKSupportTeam** [comment]
<i>(related to <a href='https://broadinstitute.zendesk.com/agent/tickets/25264'>Zendesk ticket #25264</a>)</i>

**Comment by droazen** [comment]
@fleharty @davidbenjamin ^^^

**Comment by davidbenjamin** [comment]
@gbrandt6 I will need all the inputs to FilterMutectCalls to debug this.

**Comment by gbrandt6** [comment]
I have just asked the user for a bug report and will let you know when it is available.
