### ISSUE TITLE
CollectReadCounts java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by theisaacwong** [broadinstitute/gatk#6865]
### Affected tool(s) or class(es)
CollectReadCounts 

### Affected version(s)
- [x] Latest public release version [4.1.8.1]
- [x] Latest master branch as of [10/6/2020]

### Description 
GATK CollectReadCounts successfully processes some reads but then throws an ArrayIndexOutOfBoundsException in the middle of the file. Console output below. I was able to successfully run CollectReadCounts on ~16k other crams, but received the same error on 3 of them (although the last coordinate reported by ProgressMeter was different for each). The error does not occur if I subset out chromosome 6 reads from the main cram file and run CollectReadCounts on each file separately. I don't see any obvious formatting issue with my crams from a quick skim over lines immediately following the last reported coordinate. 
```
> java -jar gatk-package-4.1.8.1-local.jar CollectReadCounts \
    -I input.cram \
    --read-index input.cram.crai \
    -L my_intervals.bed \
    --interval-merging-rule OVERLAPPING_ONLY \
    --reference hg38.fa \
    --format TSV \
    -O output.tsv

16:56:30.581 INFO  CollectReadCounts - ------------------------------------------------------------
16:56:30.581 INFO  CollectReadCounts - The Genome Analysis Toolkit (GATK) v4.1.8.1
16:56:30.581 INFO  CollectReadCounts - For support and documentation go to https://software.broadinstitute.org/gatk/
16:56:30.582 INFO  CollectReadCounts - Executing as isaac@LAPTOP-K5UOQS3A on Linux v4.19.104-microsoft-standard amd64
16:56:30.582 INFO  CollectReadCounts - Java runtime: Java HotSpot(TM) 64-Bit Server VM v14.0.1+7
16:56:30.582 INFO  CollectReadCounts - Start Date/Time: October 6, 2020 at 4:56:30 PM EDT
16:56:30.582 INFO  CollectReadCounts - ------------------------------------------------------------
16:56:30.582 INFO  CollectReadCounts - ------------------------------------------------------------
16:56:30.583 INFO  CollectReadCounts - HTSJDK Version: 2.23.0
16:56:30.584 INFO  CollectReadCounts - Picard Version: 2.22.8
16:56:30.584 INFO  CollectReadCounts - HTSJDK Defaults.COMPRESSION_LEVEL : 2
16:56:30.584 INFO  CollectReadCounts - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
16:56:30.584 INFO  CollectReadCounts - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
16:56:30.584 INFO  CollectReadCounts - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
16:56:30.584 INFO  CollectReadCounts - Deflater: IntelDeflater
16:56:30.584 INFO  CollectReadCounts - Inflater: IntelInflater
16:56:30.584 INFO  CollectReadCounts - GCS max retries/reopens: 20
16:56:30.584 INFO  CollectReadCounts - Requester pays: disabled
16:56:30.584 INFO  CollectReadCounts - Initializing engine
16:56:31.199 INFO  FeatureManager - Using codec BEDCodec to read file file:///mgh/terra_aux_files/regeneron/aux_capture_uniques_hg38_chr_sorted.bed
16:56:31.242 INFO  IntervalArgumentCollection - Processing 2960236 bp from intervals
16:56:31.254 INFO  CollectReadCounts - Done initializing engine
16:56:31.263 INFO  CollectReadCounts - Collecting read counts...
16:56:31.263 INFO  ProgressMeter - Starting traversal
16:56:31.263 INFO  ProgressMeter -        Current Locus  Elapsed Minutes       Reads Processed     Reads/Minute
16:56:42.883 INFO  ProgressMeter -           1:28433062              0.2                  7000          36147.7
16:56:53.532 INFO  ProgressMeter -           1:94237401              0.4                 13000          35026.3
16:57:08.438 INFO  ProgressMeter -          1:192716273              0.6                 21000          33893.7
16:57:19.009 INFO  ProgressMeter -           2:24820506              0.8                 31000          38957.0
16:57:29.031 INFO  ProgressMeter -           2:94856959              1.0                 44000          45700.0
16:57:39.223 INFO  ProgressMeter -          2:136329636              1.1                 59000          52089.5
16:57:49.667 INFO  ProgressMeter -          2:233747942              1.3                 65000          49742.4
16:58:01.608 INFO  ProgressMeter -           3:57654674              1.5                 71000          47152.6
16:58:12.449 INFO  ProgressMeter -          3:179974096              1.7                 84000          49809.3
16:58:23.282 INFO  ProgressMeter -           4:82276408              1.9                 98000          52491.1
16:58:33.462 INFO  ProgressMeter -           5:20304602              2.0                106000          52046.3
16:58:44.217 INFO  ProgressMeter -          5:141241407              2.2                114000          51446.4
16:58:54.298 INFO  ProgressMeter -           6:28447738              2.4                122000          51176.3
16:59:03.028 INFO  CollectReadCounts - Shutting down engine
[October 6, 2020 at 4:59:03 PM EDT] org.broadinstitute.hellbender.tools.copynumber.CollectReadCounts done. Elapsed time: 2.55 minutes.
Runtime.totalMemory()=981467136
java.lang.ArrayIndexOutOfBoundsException
        at java.base/java.util.zip.CRC32.update(CRC32.java:76)
        at htsjdk.samtools.cram.io.CRC32InputStream.read(CRC32InputStream.java:54)
        at htsjdk.samtools.cram.io.InputStreamUtils.readFully(InputStreamUtils.java:75)
        at htsjdk.samtools.cram.structure.block.Block.read(Block.java:283)
        at htsjdk.samtools.cram.structure.SliceBlocks.<init>(SliceBlocks.java:75)
        at htsjdk.samtools.cram.structure.Slice.<init>(Slice.java:155)
        at htsjdk.samtools.cram.structure.Container.<init>(Container.java:154)
        at htsjdk.samtools.cram.build.CramSpanContainerIterator$Boundary.next(CramSpanContainerIterator.java:97)
        at htsjdk.samtools.cram.build.CramSpanContainerIterator.next(CramSpanContainerIterator.java:57)
        at htsjdk.samtools.CRAMIterator.nextContainer(CRAMIterator.java:97)
        at htsjdk.samtools.CRAMIterator.hasNext(CRAMIterator.java:204)
        at htsjdk.samtools.CRAMFileReader$CRAMIntervalIteratorBase.getNextRecord(CRAMFileReader.java:527)
        at htsjdk.samtools.CRAMFileReader$CRAMIntervalIteratorBase.next(CRAMFileReader.java:521)
        at htsjdk.samtools.CRAMFileReader$CRAMIntervalIteratorBase.next(CRAMFileReader.java:472)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:574)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:553)
        at org.broadinstitute.hellbender.utils.iterators.SamReaderQueryingIterator.loadNextRecord(SamReaderQueryingIterator.java:114)
        at org.broadinstitute.hellbender.utils.iterators.SamReaderQueryingIterator.next(SamReaderQueryingIterator.java:151)
        at org.broadinstitute.hellbender.utils.iterators.SamReaderQueryingIterator.next(SamReaderQueryingIterator.java:29)
        at org.broadinstitute.hellbender.utils.iterators.SAMRecordToReadIterator.next(SAMRecordToReadIterator.java:27)
        at org.broadinstitute.hellbender.utils.iterators.SAMRecordToReadIterator.next(SAMRecordToReadIterator.java:13)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at org.broadinstitute.hellbender.engine.ReadWalker.traverse(ReadWalker.java:94)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1049)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

#### Steps to reproduce
Unfortunately, I am unable to share sequence information. 

#### Expected behavior
CollectReadCounts should count a read as falling into a given interval independently of other reads.

#### Actual behavior
Something about inputting my entire cram file at once throws an ArrayIndexOutOfBoundsException

**Comment by cmnbroad** [comment]
@theisaacwong Thanks for reporting this. it might be hard to debug this without access to the input file. It looks like the issue might be with the cram file itself - do you know how the file was created (GATK, etc. ?)

**Comment by theisaacwong** [comment]
The problem was indeed a corrupted cram file. Changing query intervals was seemingly able to skip over the problematic area and generate an output file.
