### ISSUE TITLE
About Variants to table output 

### ISSUE THREAD

**Issue by praneetha92** [broadinstitute/gatk#6897]
Hi,
I am working on GATK VariantsToTable tool and my VCF file consists of 12 chromosomes but the output shows only one chromosome. Could you please help me out.
OS:-Ubuntu 20.04
GATK version:-4.1.9.0
Java:-open jdk version 11.0.8
Command:-gatk VariantsToTable -R '/home/india/Downloads/Reference.fasta' -V '/home/india/Downloads/Galaxy57-[Merged_file.vcf].vcf' -F CHROM -F POS -F REF -F ALT -GF AD -GF DP -GF GQ -GF PL -O bothbulks_new.table

Using GATK jar /home/india/Downloads/gatk-4.1.9.0/gatk-package-4.1.9.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /home/india/Downloads/gatk-4.1.9.0/gatk-package-4.1.9.0-local.jar VariantsToTable -R /home/india/Downloads/Reference.fasta -V /home/india/Downloads/Galaxy57-[Merged_file.vcf].vcf -F CHROM -F POS -F REF -F ALT -GF AD -GF DP -GF GQ -GF PL -O bothbulks_new.table
16:46:03.294 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/india/Downloads/gatk-4.1.9.0/gatk-package-4.1.9.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Oct 16, 2020 4:46:04 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
16:46:04.315 INFO  VariantsToTable - ------------------------------------------------------------
16:46:04.316 INFO  VariantsToTable - The Genome Analysis Toolkit (GATK) v4.1.9.0
16:46:04.316 INFO  VariantsToTable - For support and documentation go to https://software.broadinstitute.org/gatk/
16:46:04.317 INFO  VariantsToTable - Executing as india@india-HP-ProBook-445-G1 on Linux v5.4.0-26-generic amd64
16:46:04.317 INFO  VariantsToTable - Java runtime: OpenJDK 64-Bit Server VM v11.0.8+10-post-Ubuntu-0ubuntu120.04
16:46:04.317 INFO  VariantsToTable - Start Date/Time: 16 October 2020 at 4:46:02 PM IST
16:46:04.318 INFO  VariantsToTable - ------------------------------------------------------------
16:46:04.318 INFO  VariantsToTable - ------------------------------------------------------------
16:46:04.320 INFO  VariantsToTable - HTSJDK Version: 2.23.0
16:46:04.320 INFO  VariantsToTable - Picard Version: 2.23.3
16:46:04.320 INFO  VariantsToTable - HTSJDK Defaults.COMPRESSION_LEVEL : 2
16:46:04.321 INFO  VariantsToTable - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
16:46:04.321 INFO  VariantsToTable - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
16:46:04.321 INFO  VariantsToTable - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
16:46:04.321 INFO  VariantsToTable - Deflater: IntelDeflater
16:46:04.322 INFO  VariantsToTable - Inflater: IntelInflater
16:46:04.322 INFO  VariantsToTable - GCS max retries/reopens: 20
16:46:04.322 INFO  VariantsToTable - Requester pays: disabled
16:46:04.322 INFO  VariantsToTable - Initializing engine
16:46:04.805 INFO  FeatureManager - Using codec VCFCodec to read file file:///home/india/Downloads/Galaxy57-%5BMerged_file.vcf%5D.vcf
16:46:04.896 INFO  VariantsToTable - Done initializing engine
16:46:04.917 WARN  VariantsToTable - Allele-specific fields will only be split if splitting multi-allelic variants is specified (`--split-multi-allelic` or `-SMA`
16:46:04.918 INFO  ProgressMeter - Starting traversal
16:46:04.918 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
16:46:05.217 INFO  VariantsToTable - Shutting down engine
[16 October 2020 at 4:46:05 PM IST] org.broadinstitute.hellbender.tools.walkers.variantutils.VariantsToTable done. Elapsed time: 0.04 minutes.
Runtime.totalMemory()=132120576
htsjdk.tribble.TribbleException: partial missing values for GL field
	at htsjdk.variant.variantcontext.GenotypeLikelihoods.parseDeprecatedGLString(GenotypeLikelihoods.java:269)
	at htsjdk.variant.variantcontext.GenotypeLikelihoods.fromGLField(GenotypeLikelihoods.java:78)
	at htsjdk.variant.vcf.AbstractVCFCodec.createGenotypeMap(AbstractVCFCodec.java:817)
	at htsjdk.variant.vcf.AbstractVCFCodec$LazyVCFGenotypesParser.parse(AbstractVCFCodec.java:121)
	at htsjdk.variant.variantcontext.LazyGenotypesContext.decode(LazyGenotypesContext.java:158)
	at htsjdk.variant.variantcontext.LazyGenotypesContext.ensureSampleNameMap(LazyGenotypesContext.java:180)
	at htsjdk.variant.variantcontext.GenotypesContext.containsSample(GenotypesContext.java:659)
	at htsjdk.variant.variantcontext.VariantContext.hasGenotype(VariantContext.java:1093)
	at org.broadinstitute.hellbender.tools.walkers.variantutils.VariantsToTable.addGenotypeFieldsToRecords(VariantsToTable.java:371)
	at org.broadinstitute.hellbender.tools.walkers.variantutils.VariantsToTable.extractFields(VariantsToTable.java:362)
	at org.broadinstitute.hellbender.tools.walkers.variantutils.VariantsToTable.apply(VariantsToTable.java:263)
	at org.broadinstitute.hellbender.engine.VariantWalker.lambda$traverse$0(VariantWalker.java:104)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.broadinstitute.hellbender.engine.VariantWalker.traverse(VariantWalker.java:102)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1049)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
@GATKSupportTeam

**Comment by ldgauthier** [comment]
Hi @praneetha92 ,

Where did this file come from?  GATK doesn't produce GLs anymore.  It looks like there are the wrong number of likelihoods for one of your genotypes.  Unfortunately our validation tool doesn't check this, but can you try vcf-validator?  You can find it here: https://vcftools.github.io/perl_module.html#vcf-validator

**Comment by praneetha92** [comment]
Hi,
I got the VCF file from BCF tools merge in galaxy.
