### ISSUE TITLE
ArrayIndexOutOfBoundsException: -87 in ValidateVariants

### ISSUE THREAD

**Issue by Zepeng-Mu** [broadinstitute/gatk#6911]
Hi, I encountered the following error while running GATK.
It is hard for me to say what exactly is wrong, and extensive searching has not been helpul

Thanks in advance!

```
gatk ValidateVariants -V ../../data/geno/phased/chr1-22.phased.rename.reheader.vcf.gz -R ../../../../index/hg19.fa.gz
Using GATK jar ~/tools/gatk-4.1.8.0/gatk-package-4.1.8.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /home/zepengmu/tools/gatk-4.1.8.0/gatk-package-4.1.8.0-local.jar ValidateVariants -V ../../data/geno/phased/chr1-22.phased.rename.reheader.vcf.gz -R ../../../../index/hg19.fa.gz
19:53:34.379 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/zepengmu/tools/gatk-4.1.8.0/gatk-package-4.1.8.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Oct 25, 2020 7:53:34 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
19:53:34.606 INFO  ValidateVariants - ------------------------------------------------------------
19:53:34.606 INFO  ValidateVariants - The Genome Analysis Toolkit (GATK) v4.1.8.0
19:53:34.606 INFO  ValidateVariants - For support and documentation go to https://software.broadinstitute.org/gatk/
19:53:34.607 INFO  ValidateVariants - Executing as zepengmu@midway2-login1.rcc.local on Linux v3.10.0-1127.8.2.el7.x86_64 amd64
19:53:34.607 INFO  ValidateVariants - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_45-b14
19:53:34.607 INFO  ValidateVariants - Start Date/Time: October 25, 2020 7:53:34 PM CDT
19:53:34.607 INFO  ValidateVariants - ------------------------------------------------------------
19:53:34.607 INFO  ValidateVariants - ------------------------------------------------------------
19:53:34.607 INFO  ValidateVariants - HTSJDK Version: 2.22.0
19:53:34.607 INFO  ValidateVariants - Picard Version: 2.22.8
19:53:34.608 INFO  ValidateVariants - HTSJDK Defaults.COMPRESSION_LEVEL : 2
19:53:34.608 INFO  ValidateVariants - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
19:53:34.608 INFO  ValidateVariants - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
19:53:34.608 INFO  ValidateVariants - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
19:53:34.608 INFO  ValidateVariants - Deflater: IntelDeflater
19:53:34.608 INFO  ValidateVariants - Inflater: IntelInflater
19:53:34.608 INFO  ValidateVariants - GCS max retries/reopens: 20
19:53:34.608 INFO  ValidateVariants - Requester pays: disabled
19:53:34.608 INFO  ValidateVariants - Initializing engine
19:53:35.169 INFO  FeatureManager - Using codec VCFCodec to read file file://chr1-22.phased.rename.reheader.vcf.gz
19:53:35.594 INFO  ValidateVariants - Done initializing engine
19:53:35.594 WARN  ValidateVariants - IDS validation cannot be done because no DBSNP file was provided
19:53:35.594 WARN  ValidateVariants - Other possible validations will still be performed
19:53:35.594 INFO  ProgressMeter - Starting traversal
19:53:35.595 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
19:53:35.660 INFO  ValidateVariants - Shutting down engine
[October 25, 2020 7:53:35 PM CDT] org.broadinstitute.hellbender.tools.walkers.variantutils.ValidateVariants done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=2114453504
java.lang.ArrayIndexOutOfBoundsException: -87
	at org.broadinstitute.hellbender.utils.BaseUtils.convertIUPACtoN(BaseUtils.java:123)
	at org.broadinstitute.hellbender.utils.fasta.CachingIndexedFastaSequenceFile.getSubsequenceAt(CachingIndexedFastaSequenceFile.java:340)
	at org.broadinstitute.hellbender.engine.ReferenceFileSource.queryAndPrefetch(ReferenceFileSource.java:78)
	at org.broadinstitute.hellbender.engine.ReferenceDataSource.queryAndPrefetch(ReferenceDataSource.java:64)
	at org.broadinstitute.hellbender.engine.ReferenceContext.getBases(ReferenceContext.java:197)
	at org.broadinstitute.hellbender.tools.walkers.variantutils.ValidateVariants.apply(ValidateVariants.java:236)
	at org.broadinstitute.hellbender.engine.VariantWalker.lambda$traverse$0(VariantWalker.java:104)
	at org.broadinstitute.hellbender.engine.VariantWalker$$Lambda$76/1710491273.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.VariantWalker.traverse(VariantWalker.java:102)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1049)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
	at org.broadinstitute.hellbender.Main.main(Main.java:292)
```

**Comment by droazen** [comment]
@Zepeng-Mu There seems to be an unsupported character in your reference fasta. Can you verify the integrity hash of your reference? Could you also try re-generating the fasta index using `samtools faidx`?

**Comment by Zepeng-Mu** [comment]
Hi, thanks for the quick reply! The reason is indeed in the fasta file. I unzipped it when running another program but then re-zipped using gzip instead of bgzip. The error message disappears when I used bgzip to compress my fasta file again.
Thanks again!
