### ISSUE TITLE
CombineGVCFs java.lang.NullPointerException in v4.1.9.0

### ISSUE THREAD

**Issue by niyomiw** [broadinstitute/gatk#6913]
Hi, 

I have the same issue reported here https://github.com/broadinstitute/gatk/issues/6766 that relates to CombineGVCFs. It was supposed to be fixed with the new version 4.1.9.0, however. I still get the same error when I tried it with the current version. 

Here is the error report 

> Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/orange/reed/nhouse/Raw_seqs/SEQ9_samples/tmp
11:30:50.248 WARN  GATKAnnotationPluginDescriptor - Redundant enabled annotation group (StandardAnnotation) is enabled for this tool by default
11:30:50.478 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/apps/gatk/4.1.9.0/gatk-package-4.1.9.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Oct 26, 2020 11:30:50 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
11:30:50.791 INFO  CombineGVCFs - ------------------------------------------------------------
11:30:50.791 INFO  CombineGVCFs - The Genome Analysis Toolkit (GATK) v4.1.9.0
11:30:50.792 INFO  CombineGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
11:30:50.792 INFO  CombineGVCFs - Executing as nwijewardena@c3a-s8.ufhpc on Linux v3.10.0-1062.18.1.el7.x86_64 amd64
11:30:50.792 INFO  CombineGVCFs - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_31-b13
11:30:50.792 INFO  CombineGVCFs - Start Date/Time: October 26, 2020 11:30:50 AM EDT
11:30:50.793 INFO  CombineGVCFs - ------------------------------------------------------------
11:30:50.793 INFO  CombineGVCFs - ------------------------------------------------------------
11:30:50.794 INFO  CombineGVCFs - HTSJDK Version: 2.23.0
11:30:50.794 INFO  CombineGVCFs - Picard Version: 2.23.3
11:30:50.794 INFO  CombineGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2
11:30:50.794 INFO  CombineGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
11:30:50.794 INFO  CombineGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
11:30:50.794 INFO  CombineGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
11:30:50.795 INFO  CombineGVCFs - Deflater: IntelDeflater
11:30:50.795 INFO  CombineGVCFs - Inflater: IntelInflater
11:30:50.795 INFO  CombineGVCFs - GCS max retries/reopens: 20
11:30:50.795 INFO  CombineGVCFs - Requester pays: disabled
11:30:50.795 INFO  CombineGVCFs - Initializing engine
11:30:51.784 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_Cam19_01.raw_variants.g.vcf
11:30:51.907 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_AS217_1.raw_variants.g.vcf
11:30:52.003 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_Mon03.raw_variants.g.vcf
11:30:52.117 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_Mon02.raw_variants.g.vcf
11:30:52.208 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_Tur09_1.raw_variants.g.vcf
11:30:52.261 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_Tur11_01.raw_variants.g.vcf
11:30:52.342 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_EU01_1.raw_variants.g.vcf
11:30:52.431 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_EU02_1.raw_variants.g.vcf
11:30:52.549 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_EU03_1.raw_variants.g.vcf
11:30:52.627 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_EU20_1.raw_variants.g.vcf
11:30:52.742 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_Tur12_01.raw_variants.g.vcf
11:30:52.832 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_EU21_1.raw_variants.g.vcf
11:30:52.923 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_UK37_01.raw_variants.g.vcf
11:30:53.028 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_EU22_1.raw_variants.g.vcf
11:30:53.155 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_UK38_01.raw_variants.g.vcf
11:30:53.287 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_Mon01.raw_variants.g.vcf
11:30:53.348 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_UK41_01.raw_variants.g.vcf
11:30:53.440 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_Cam28_07.raw_variants.g.vcf
11:30:53.556 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_Cam34_01.raw_variants.g.vcf
11:30:53.660 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_AS01_1.raw_variants.g.vcf
11:30:53.727 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_AS02_1.raw_variants.g.vcf
11:30:53.805 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_AS184_1.raw_variants.g.vcf
11:30:53.894 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_AS201_1.raw_variants.g.vcf
11:30:54.000 INFO  FeatureManager - Using codec VCFCodec to read file file:///orange/reed/nhouse/Raw_seqs/SEQ1_samples/SEQ1_gvcf/renamed_seq1trimq10_LHA_AS209_1.raw_variants.g.vcf
11:34:25.030 INFO  CombineGVCFs - Done initializing engine
11:34:25.154 INFO  ProgressMeter - Starting traversal
11:34:25.155 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
11:34:25.473 WARN  ReferenceConfidenceVariantContextMerger - Detected invalid annotations: When trying to merge variant contexts at location DS235882:44 the annotation MLEAC=[1, 0] was not a numerical value and was ignored
11:34:25.944 INFO  CombineGVCFs - Shutting down engine
[October 26, 2020 11:34:25 AM EDT] org.broadinstitute.hellbender.tools.walkers.CombineGVCFs done. Elapsed time: 3.59 minutes.
Runtime.totalMemory()=3738173440
java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at htsjdk.variant.vcf.VCFUtils.parseVcfDouble(VCFUtils.java:262)
	at htsjdk.variant.vcf.AbstractVCFCodec.createGenotypeMap(AbstractVCFCodec.java:808)
	at htsjdk.variant.vcf.AbstractVCFCodec$LazyVCFGenotypesParser.parse(AbstractVCFCodec.java:121)
	at htsjdk.variant.variantcontext.LazyGenotypesContext.decode(LazyGenotypesContext.java:158)
	at htsjdk.variant.variantcontext.LazyGenotypesContext.ensureSampleNameMap(LazyGenotypesContext.java:180)
	at htsjdk.variant.variantcontext.GenotypesContext.getSampleNames(GenotypesContext.java:646)
	at htsjdk.variant.variantcontext.VariantContext.getSampleNames(VariantContext.java:1076)
	at org.broadinstitute.hellbender.tools.walkers.CombineGVCFs.getSamples(CombineGVCFs.java:361)
	at org.broadinstitute.hellbender.tools.walkers.CombineGVCFs.okayToSkipThisSite(CombineGVCFs.java:351)
	at org.broadinstitute.hellbender.tools.walkers.CombineGVCFs.mergeWithNewVCs(CombineGVCFs.java:327)
	at org.broadinstitute.hellbender.tools.walkers.CombineGVCFs.apply(CombineGVCFs.java:169)
	at org.broadinstitute.hellbender.engine.MultiVariantWalkerGroupedOnStart.apply(MultiVariantWalkerGroupedOnStart.java:131)
	at org.broadinstitute.hellbender.engine.MultiVariantWalkerGroupedOnStart.apply(MultiVariantWalkerGroupedOnStart.java:106)
	at org.broadinstitute.hellbender.engine.MultiVariantWalker.lambda$traverse$1(MultiVariantWalker.java:120)
	at org.broadinstitute.hellbender.engine.MultiVariantWalker$$Lambda$110/1374115041.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.MultiVariantWalker.traverse(MultiVariantWalker.java:118)
	at org.broadinstitute.hellbender.engine.MultiVariantWalkerGroupedOnStart.traverse(MultiVariantWalkerGroupedOnStart.java:163)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1049)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
Using GATK jar /apps/gatk/4.1.9.0/gatk-package-4.1.9.0-local.jar

I was planning on Combining 25 samples at a time (per library), out of 250 (Not sure if this was even the right move). But the issue comes up for only certain libraries. All the samples (250) were processed exactly the same way. Not sure what is causing it to throw out this error for some only.

**Comment by droazen** [comment]
@niyomiw That's not a `NullPointerException` -- it's a `NumberFormatException`, and is different from the issue resolved in https://github.com/broadinstitute/gatk/issues/6766.

It's possible that one or more of your VCFs are malformed in some way. Could you try running `ValidateVariants` on the inputs?

**Comment by niyomiw** [comment]
Oh I'm so sorry about that. I ran ValidateVariants on a few samples (running the whole batch now). This is the error I get when I don't specify the --validate-GVCF or --validation-type-to-exclude ALLELES 

> A USER ERROR has occurred: Input renamed_seq1trimq10_LHA_AS02_1.raw_variants.g.vcf fails strict validation of type ALL: one or more of the ALT allele(s) for the record at position DS235882:56737 are not observed at all in the sample genotypes

The position in the gvcf

> DS235882        56737   .       A       T,<NON_REF>     0       .       BaseQRankSum=-3.172;DP=29;ExcessHet=3.0103;MLEAC=0,0;MLEAF=0.00,0.00;MQRankSum=-1.507;RAW_MQandDP=97098,29;Re
adPosRankSum=-0.312        GT:AD:DP:GQ:PL:SB       0/0:27,2,0:29:67:0,67,1051,81,1056,1070:13,14,1,1

When I exclude the Alleles, I get no errors for the samples I checked thus far. This error cannot be causing the initial problem because I got the same error (in different position) on some gvcfs that are currently working fine with CombineGVCFs.

**Comment by droazen** [comment]
@niyomiw The error you're getting suggests that there might be a sample record in your GVCF for which the GQ value is completely missing (ie., not even a `.` to indicate a missing value). Can you check your VCF for such a record?

**Comment by niyomiw** [comment]
Found something weird  in the vcf

> DS235882        28690   .       C       T,<NON_REF>     0.01    .       DP=1;MLEAC=0,0;MLEAF=NaN,NaN;RAW_MQandDP=2401,1 GT      ./.

This is all the information for this position. Not sure what caused it. You think re-running the Haplotype caller might fix it?

**Comment by gbrandt6** [comment]
@niyomiw Please post this issue on the GATK forum: https://gatk.broadinstitute.org/hc/en-us/community/topics and we can help to get it resolved.

**Comment by droazen** [comment]
@gbrandt6 Did this one get resolved on the forum?

**Comment by gbrandt6** [comment]
There are no posts regarding this issue, haven't heard from the user.

**Comment by niyomiw** [comment]
Hi,

Sorry I never got around to post this on the forum. I had to put it in the back burner for a little bit because I never figured out what the issue was. I will post it soon when I get a chance.

Thank you for checking in. I really appreciate it.


Best,

Niyomi House

PhD Candidate

Florida Museum of Natural History

1659 Museum Road

University of Florida

Gainesville, FL 32611-7800

Phone: 906-362-1162

E-mail: nwijewardena@ufl.edu

________________________________
