### ISSUE TITLE
Exception in thread "Thread-1" htsjdk.samtools.util.RuntimeIOException: java.nio.file.NoSuchFileException: Rlib.7359270660945146060

### ISSUE THREAD

**Issue by woaishiye** [broadinstitute/gatk#6948]
### Instructions
GATK version: 4.1.1.0-VariantRecalibrator-ApplyVQSR

I am using VariantRecalibrator and ApplyVQSR to do VQSR for my variant set, and below is my complete scripts:
java -Xmx3990m -Djava.io.tmpdir=/gss1/home/ldl20190322/a_haoxiaoshuai/JavaTmpDir -jar /gss1/home/ldl20190322/a_haoxiaoshuai/z_software/gatk/gatk-4.1.1.0/gatk-package-4.1.1.0-local.jar VariantRecalibrator -R Gmax_275_v2.0.fa --variant Ztem.gatk.vcf.gz --resource:hapmap,known=false,training=true,truth=true,prior=10.0 final.intersected.snp.vcf.gz -an QD -an MQ -an MQRankSum -an ReadPosRankSum -an FS -an SOR -an DP -mode SNP -O Ztem.gatk.snp.recal --tranches-file Ztem.gatk.snp.tranches --rscript-file Ztem.gatk.snp.plots.R -tranche 90.0 -tranche 92.0 -tranche 94.0 -tranche 96.0 -tranche 97.0 -tranche 98.0 -tranche 99.0 -tranche 99.9
java -Xmx3990m -Djava.io.tmpdir=/gss1/home/ldl20190322/a_haoxiaoshuai/JavaTmpDir -jar /gss1/home/ldl20190322/a_haoxiaoshuai/z_software/gatk/gatk-4.1.1.0/gatk-package-4.1.1.0-local.jar ApplyVQSR -R Gmax_275_v2.0.fa -V Ztem.gatk.vcf.gz --truth-sensitivity-filter-level 99.0 --tranches-file Ztem.gatk.snp.tranches --recal-file Ztem.gatk.snp.recal -mode SNP -O Ztem.gatk.snp.vcf.gz

And after it finished, i got some mistakes in the log file， and i dont konw what was wrong with my script, please help me. below is the message of the mistakes and i just omitted some no use information in the log file:
                                                              .
                                                              .
                                                              .
15:51:14.040 INFO  VariantRecalibratorEngine - Evaluating full set of 3660 variants...
15:51:15.156 INFO  VariantRecalibratorEngine - Evaluating full set of 3660 variants...
15:51:15.373 INFO  VariantRecalibrator - Building FS x ReadPosRankSum plot...
15:51:15.374 INFO  VariantRecalibratorEngine - Evaluating full set of 3660 variants...
15:51:16.493 INFO  VariantRecalibratorEngine - Evaluating full set of 3660 variants...
15:51:16.722 INFO  VariantRecalibrator - Building MQRankSum x ReadPosRankSum plot...
15:51:16.722 INFO  VariantRecalibratorEngine - Evaluating full set of 3600 variants...
15:51:17.819 INFO  VariantRecalibratorEngine - Evaluating full set of 3600 variants...
15:51:18.045 INFO  VariantRecalibrator - Executing: Rscript /gss1/home/ldl20190322/a_haoxiaoshuai/a_project/WGS_Z/e_vqsr_plot/Ztem.gatk.snp.plots.R
15:51:38.589 INFO  VariantRecalibrator - Executing: Rscript (resource)org/broadinstitute/hellbender/tools/walkers/vqsr/plot_Tranches.R /gss1/home/ldl20190322/a_haoxiaoshuai/a_project/WGS_Z/e_vqsr_plot/Ztem.gatk.snp.tranches 2.15
15:51:39.227 INFO  VariantRecalibrator - Shutting down engine
[November 9, 2020 3:51:39 PM CST] org.broadinstitute.hellbender.tools.walkers.vqsr.VariantRecalibrator done. Elapsed time: 9.43 minutes.
Runtime.totalMemory()=2029518848
Exception in thread "Thread-1" htsjdk.samtools.util.RuntimeIOException: java.nio.file.NoSuchFileException: /gss1/home/ldl20190322/a_haoxiaoshuai/JavaTmpDir/Rlib.7359270660945146060
	at htsjdk.samtools.util.IOUtil.recursiveDelete(IOUtil.java:1346)
	at org.broadinstitute.hellbender.utils.io.IOUtils.deleteRecursively(IOUtils.java:1061)
	at org.broadinstitute.hellbender.utils.io.DeleteRecursivelyOnExitPathHook.runHooks(DeleteRecursivelyOnExitPathHook.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.NoSuchFileException: /gss1/home/ldl20190322/a_haoxiaoshuai/JavaTmpDir/Rlib.7359270660945146060
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.nio.file.Files.walkFileTree(Files.java:2662)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at htsjdk.samtools.util.IOUtil.recursiveDelete(IOUtil.java:1344)
	... 3 more
15:51:41.426 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gss1/home/ldl20190322/a_haoxiaoshuai/z_software/gatk/gatk-4.1.1.0/gatk-package-4.1.1.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Nov 09, 2020 3:51:43 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
15:51:43.109 INFO  ApplyVQSR - ------------------------------------------------------------
15:51:43.109 INFO  ApplyVQSR - The Genome Analysis Toolkit (GATK) v4.1.1.0
15:51:43.109 INFO  ApplyVQSR - For support and documentation go to https://software.broadinstitute.org/gatk/
15:51:43.109 INFO  ApplyVQSR - Executing as ldl20190322@compute20 on Linux v2.6.32-642.el6.x86_64 amd64
15:51:43.109 INFO  ApplyVQSR - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_261-b12
15:51:43.109 INFO  ApplyVQSR - Start Date/Time: November 9, 2020 3:51:41 PM CST
15:51:43.109 INFO  ApplyVQSR - ------------------------------------------------------------
15:51:43.109 INFO  ApplyVQSR - ------------------------------------------------------------
15:51:43.110 INFO  ApplyVQSR - HTSJDK Version: 2.19.0
15:51:43.110 INFO  ApplyVQSR - Picard Version: 2.19.0
15:51:43.110 INFO  ApplyVQSR - HTSJDK Defaults.COMPRESSION_LEVEL : 2
15:51:43.110 INFO  ApplyVQSR - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
15:51:43.110 INFO  ApplyVQSR - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
15:51:43.110 INFO  ApplyVQSR - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
15:51:43.110 INFO  ApplyVQSR - Deflater: IntelDeflater
15:51:43.110 INFO  ApplyVQSR - Inflater: IntelInflater
                                                              .
                                                              .
                                                              .

----

### Affected tool(s) or class(es)
_Tool/class name(s), special parameters?_

### Affected version(s)
- [ ] Latest public release version [version?]
- [ ] Latest master branch as of [date of test?]

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._

#### Steps to reproduce
_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem. (The support team may follow up to ask you to upload data to reproduce the issue.)_

#### Expected behavior
_Tell us what should happen_

#### Actual behavior
_Tell us what happens instead_

----

### Tool(s) or class(es) involved
_Tool/class name(s), special parameters?_

### Description
_Specify whether you want a modification of an existing behavior or addition of a new capability._
_Provide **examples**, **screenshots**, where appropriate._

----

### Tool(s) or class(es) involved
_Tool/class name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

**Comment by droazen** [comment]
@woaishiye Could you try running with the most recent GATK release and see if the issue still persists? This issue with the temp file deletion shutdown hook was believed to be fixed a number of releases ago.
