### ISSUE TITLE
Limit number of alternate alleles when merging variant contexts

### ISSUE THREAD

**Issue by karenfeng** [broadinstitute/gatk#6962]
### Tool(s) or class(es) involved

[ReferenceConfidenceVariantContextMerger](https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/tools/walkers/ReferenceConfidenceVariantContextMerger.java)

### Description

In the case that VariantContexts with too many alternate alleles are passed to the joint genotyper, the genotype calculator used in the merger can experience an OOM:
```
java.lang.OutOfMemoryError: Java heap space at org.broadinstitute.hellbender.tools.walkers.genotyper.GenotypeLikelihoodCalculator.genotypeIndexMap(GenotypeLikelihoodCalculator.java:522)
at org.broadinstitute.hellbender.tools.walkers.ReferenceConfidenceVariantContextMerger.mergeRefConfidenceGenotypes(ReferenceConfidenceVariantContextMerger.java:541)
at org.broadinstitute.hellbender.tools.walkers.ReferenceConfidenceVariantContextMerger.merge(ReferenceConfidenceVariantContextMerger.java:130)
at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFsEngine.callRegion(GenotypeGVCFsEngine.java:116)
```

For a ~ reasonable number of alternate alleles, this site is filtered by the [genotyping engine](https://github.com/broadinstitute/gatk/blob/48afe160c9cfba5a82e40a6be9c8a555066271d1/src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngine.java#L380-L388), but it would be helpful if the merger also had a limit to avoid fatal errors.

**Comment by ldgauthier** [comment]
Hi @karenfeng ,

Sorry about the problem, but I really like your suggestion.  What would you want the expected behavior to be?  The site is dropped entirely and a warning is written to the log?  Would it be acceptable if the PLs were dropped, but the rest of the variant was retained?

**Comment by karenfeng** [comment]
Thanks for the quick response @ldgauthier! I think either behavior makes sense; the former is consistent with the genotyping engine, so I have a slight preference in that direction.

**Comment by ldgauthier** [comment]
Skipping does look like it would be consistent with what's going to happen downstream anyways.  Do you have some data I can use for testing?

**Comment by karenfeng** [comment]
I can't pin down a public dataset with this many real alternate alleles, but in my unit testing with fake alternate alleles `(T, TT, ..., n*T)` I found that the merger encountered an OOM when the number of alternate alleles was 2000. I'm not sure where the exact cutoff is though.
