### ISSUE TITLE
java.lang.NullPointerException when running MarkDuplicatesSpark with "--read-name-regex null"

### ISSUE THREAD

**Issue by U201412486** [broadinstitute/gatk#7001]
Hi,
  I run the code below to to skip optical duplicate detection during marking duplicate.
`java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=trueDsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /gatk-4.1.8.0/gatk-package-4.1.8.0-local.jar MarkDuplicatesSpark --spark-master local[28] --conf spark.local.dir=/datatmp/ -I ./A.sort.bam -O ./A.sort.bam.Mdup.bam -M ./A.sort.bam.Md.metrics.txt  --tmp-dir /datatmp/ --conf spark.network.timeout=200h --conf spark.executor.heartbeatInterval=100h --read-name-regex null`
It reports the error below.
`20/12/15 11:43:00 ERROR Executor: Exception in task 15.0 in stage 7.0 (TID 12538)
java.lang.NullPointerException
        at org.broadinstitute.hellbender.tools.spark.transforms.markduplicates.MarkDuplicatesSparkUtils.lambda$handleFragments$12(MarkDuplicatesSparkUtils.java:395)
        at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:372)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:479)
        at java.util.stream.ReferencePipeline.max(ReferencePipeline.java:515)
        at org.broadinstitute.hellbender.tools.spark.transforms.markduplicates.MarkDuplicatesSparkUtils.handleFragments(MarkDuplicatesSparkUtils.java:396)
        at org.broadinstitute.hellbender.tools.spark.transforms.markduplicates.MarkDuplicatesSparkUtils.lambda$markDuplicateRecords$fa45b352$1(MarkDuplicatesSparkUtils.java:304)
        at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$3$1.apply(JavaRDDLike.scala:143)
        at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$3$1.apply(JavaRDDLike.scala:143)
        at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
        at org.apache.spark.shuffle.sort.UnsafeShuffleWriter.write(UnsafeShuffleWriter.java:187)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
        at org.apache.spark.scheduler.Task.run(Task.scala:123)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
`

Can you give me some advice?
Thanks,
sun

**Comment by jamesemery** [comment]
@U201412486 Thanks for reporting this! It looks like the issue was the `--read-name-regex null` not working with spark. I have a patch to fix it but in the meantime you should be able to run without nulling out the regex and it should fail gracefully and simply ignore counting OpticalDuplicates for reads that don't conform to the default regex.

**Comment by U201412486** [comment]
@jamesemery Thanks for you reply.
  I did not get your idea. I can run without nulling out the regex successfully.Will it ignore counting OpticalDuplicates without nulling out the regex ?

**Comment by jamesemery** [comment]
@U201412486 Unfortunately it will still try to call OpticalDuplicates in that case correct (unless the regex doesn't apply to the reads correctly). Optical duplicate marking does not change the regular duplicate marking behavior and primarily gets included in the metrics so it should be possible to simply ignore the outputs. If you really want no reported Optical Duplicates you could also set the optical duplicates pixel distance to 0 (or -1) which should prevent anything from being marked as such since nothing will be in range to be counted.

**Comment by U201412486** [comment]
@jamesemery That is to say,I can add the parameter of "--duplicate-tagging-policy"  to mark the  optical duplicate. Then I can select the bam file without the  optical duplicate.Is this right?
  Thanks for your reply.
