### ISSUE TITLE
BaseRecalibrator：A USER ERROR has occurred: Number of read groups must be >= 1, but is 0

### ISSUE THREAD

**Issue by Ning-310** [broadinstitute/gatk#7031]
### Instructions
gatk --java-options "-Xmx12G -Djava.io.tmpdir=/data/nws/WES/1align_out/200919_A00682_0446_AHCVMJDSXY/tmp -DGATK_STACKTRACE_ON_USER_EXCEPTION=true" BaseRecalibrator -R /data/nws/WES/reference/Homo_sapiens_assembly38.fasta -I /data/nws/WES/1align_out/200919_A00682_0446_AHCVMJDSXY/Set12-3_L1_361361.sorted.marked.bam -O recal_data.table  --known-sites /data/nws/WES/reference/dbsnp_146.hg38.vcf  --known-sites /data/nws/WES/reference/1000G_phase1.snps.high_confidence.hg38.vcf  --known-sites /data/nws/WES/reference/Mills_and_1000G_gold_standard.indels.hg38.vcf 1>/data/nws/WES/1align_out/200919_A00682_0446_AHCVMJDSXY/Set12-3_L1_361361.BaseRecalibrator.log 2>&1

Using GATK jar /usr/local/gatk-4.1.3.0/gatk-package-4.1.3.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx12G -Djava.io.tmpdir=/data/nws/WES/1align_out/200919_A00682_0446_AHCVMJDSXY/tmp -DGATK_STACKTRACE_ON_USER_EXCEPTION=true -jar /usr/local/gatk-4.1.3.0/gatk-package-4.1.3.0-local.jar BaseRecalibrator -R /data/nws/WES/reference/Homo_sapiens_assembly38.fasta -I /data/nws/WES/1align_out/200919_A00682_0446_AHCVMJDSXY/Set12-3_L1_361361.sorted.marked.bam -O recal_data.table --known-sites /data/nws/WES/reference/dbsnp_146.hg38.vcf --known-sites /data/nws/WES/reference/1000G_phase1.snps.high_confidence.hg38.vcf --known-sites /data/nws/WES/reference/Mills_and_1000G_gold_standard.indels.hg38.vcf
15:45:57.013 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/local/gatk-4.1.3.0/gatk-package-4.1.3.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
15:46:12.281 INFO  BaseRecalibrator - ------------------------------------------------------------
15:46:12.282 INFO  BaseRecalibrator - The Genome Analysis Toolkit (GATK) v4.1.3.0
15:46:12.282 INFO  BaseRecalibrator - For support and documentation go to https://software.broadinstitute.org/gatk/
15:46:27.292 INFO  BaseRecalibrator - Executing as nws@cuckoolab on Linux v3.10.0-1127.19.1.el7.x86_64 amd64
15:46:27.292 INFO  BaseRecalibrator - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_262-b10
15:46:27.294 INFO  BaseRecalibrator - Start Date/Time: 2021年1月8日 下午03时45分56秒
15:46:27.294 INFO  BaseRecalibrator - ------------------------------------------------------------
15:46:27.294 INFO  BaseRecalibrator - ------------------------------------------------------------
15:46:27.295 INFO  BaseRecalibrator - HTSJDK Version: 2.20.1
15:46:27.295 INFO  BaseRecalibrator - Picard Version: 2.20.5
15:46:27.296 INFO  BaseRecalibrator - HTSJDK Defaults.COMPRESSION_LEVEL : 2
15:46:27.296 INFO  BaseRecalibrator - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
15:46:27.296 INFO  BaseRecalibrator - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
15:46:27.296 INFO  BaseRecalibrator - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
15:46:27.296 INFO  BaseRecalibrator - Deflater: IntelDeflater
15:46:27.296 INFO  BaseRecalibrator - Inflater: IntelInflater
15:46:27.296 INFO  BaseRecalibrator - GCS max retries/reopens: 20
15:46:27.296 INFO  BaseRecalibrator - Requester pays: disabled
15:46:27.297 INFO  BaseRecalibrator - Initializing engine
15:46:28.062 INFO  FeatureManager - Using codec VCFCodec to read file file:///data/nws/WES/reference/dbsnp_146.hg38.vcf
15:46:28.075 INFO  FeatureManager - Using codec VCFCodec to read file file:///data/nws/WES/reference/1000G_phase1.snps.high_confidence.hg38.vcf
15:46:28.127 INFO  FeatureManager - Using codec VCFCodec to read file file:///data/nws/WES/reference/Mills_and_1000G_gold_standard.indels.hg38.vcf
15:46:28.213 INFO  BaseRecalibrator - Done initializing engine
15:46:28.216 INFO  BaseRecalibrator - Shutting down engine
[2021年1月8日 下午03时46分28秒] org.broadinstitute.hellbender.tools.walkers.bqsr.BaseRecalibrator done. Elapsed time: 0.52 minutes.
Runtime.totalMemory()=1488977920
***********************************************************************

A USER ERROR has occurred: Number of read groups must be >= 1, but is 0

***********************************************************************
org.broadinstitute.hellbender.exceptions.UserException: Number of read groups must be >= 1, but is 0
	at org.broadinstitute.hellbender.utils.recalibration.BaseRecalibrationEngine.<init>(BaseRecalibrationEngine.java:96)
	at org.broadinstitute.hellbender.tools.walkers.bqsr.BaseRecalibrator.onTraversalStart(BaseRecalibrator.java:144)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1046)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)

**Comment by droazen** [comment]
@Ning-310 Can you check your `Set12-3_L1_361361.sorted.marked.bam` and confirm that all reads are assigned to a read group? Also, can you try running with the latest GATK release (4.1.9.0), and see if the issue persists?

**Comment by droazen** [comment]
Possible dupe of #6242
