### ISSUE TITLE
MarkDuplicatesSpark throw an error

### ISSUE THREAD

**Issue by seahearman** [broadinstitute/gatk#7035]
## Bug Report
when I run the MarkDuplicatesSpark, it throws me an error: basically it shows the spark engine stopped when run this function. 
the part of the error log is here:
`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/rnaseq_pipeline_app/Apps/GATK/gatk-4.1.9.0/gatk-package-4.1.9.0-local.jar) to method java.nio.Bits.unaligned()
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
21/01/12 15:50:31 INFO SparkContext: Running Spark version 2.4.5
21/01/12 15:50:31 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
21/01/12 15:50:31 INFO SparkContext: Submitted application: MarkDuplicatesSpark
21/01/12 15:50:31 INFO SecurityManager: Changing view acls to: root
21/01/12 15:50:31 INFO SecurityManager: Changing modify acls to: root
21/01/12 15:50:31 INFO SecurityManager: Changing view acls groups to: 
21/01/12 15:50:31 INFO SecurityManager: Changing modify acls groups to: 
21/01/12 15:50:31 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
21/01/12 15:50:31 INFO Utils: Successfully started service 'sparkDriver' on port 36657.
21/01/12 15:50:31 INFO SparkEnv: Registering MapOutputTracker
21/01/12 15:50:31 INFO SparkEnv: Registering BlockManagerMaster
21/01/12 15:50:31 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
21/01/12 15:50:31 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
21/01/12 15:50:31 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-273b4c87-579e-4d57-81de-aa47a79634bb
21/01/12 15:50:31 INFO MemoryStore: MemoryStore started with capacity 9.2 GB
21/01/12 15:50:31 INFO SparkEnv: Registering OutputCommitCoordinator
21/01/12 15:50:31 INFO Utils: Successfully started service 'SparkUI' on port 4040.
21/01/12 15:50:31 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://fdbd4e9f571c4f8489ec11d570585d56000000.internal.cloudapp.net:4040
21/01/12 15:50:31 INFO Executor: Starting executor ID driver on host localhost
21/01/12 15:50:32 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 46619.
21/01/12 15:50:32 INFO NettyBlockTransferService: Server created on fdbd4e9f571c4f8489ec11d570585d56000000.internal.cloudapp.net:46619
21/01/12 15:50:32 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
21/01/12 15:50:32 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, fdbd4e9f571c4f8489ec11d570585d56000000.internal.cloudapp.net, 46619, None)
21/01/12 15:50:32 INFO BlockManagerMasterEndpoint: Registering block manager fdbd4e9f571c4f8489ec11d570585d56000000.internal.cloudapp.net:46619 with 9.2 GB RAM, BlockManagerId(driver, fdbd4e9f571c4f8489ec11d570585d56000000.internal.cloudapp.net, 46619, None)
21/01/12 15:50:32 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, fdbd4e9f571c4f8489ec11d570585d56000000.internal.cloudapp.net, 46619, None)
21/01/12 15:50:32 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, fdbd4e9f571c4f8489ec11d570585d56000000.internal.cloudapp.net, 46619, None)
15:50:32.214 INFO  MarkDuplicatesSpark - Spark verbosity set to INFO (see --spark-verbosity argument)
21/01/12 15:50:32 INFO GoogleHadoopFileSystemBase: GHFS version: 1.9.4-hadoop3
21/01/12 15:50:32 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 172.9 KB, free 9.2 GB)
21/01/12 15:50:33 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 35.5 KB, free 9.2 GB)
21/01/12 15:50:33 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on fdbd4e9f571c4f8489ec11d570585d56000000.internal.cloudapp.net:46619 (size: 35.5 KB, free: 9.2 GB)
21/01/12 15:50:33 INFO SparkContext: Created broadcast 0 from newAPIHadoopFile at PathSplitSource.java:96
21/01/12 15:50:33 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 172.9 KB, free 9.2 GB)
21/01/12 15:50:33 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 35.5 KB, free 9.2 GB)
21/01/12 15:50:33 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on fdbd4e9f571c4f8489ec11d570585d56000000.internal.cloudapp.net:46619 (size: 35.5 KB, free: 9.2 GB)
21/01/12 15:50:33 INFO SparkContext: Created broadcast 1 from newAPIHadoopFile at PathSplitSource.java:96
21/01/12 15:50:33 INFO FileInputFormat: Total input files to process : 1
21/01/12 15:50:33 INFO SparkUI: Stopped Spark web UI at http://fdbd4e9f571c4f8489ec11d570585d56000000.internal.cloudapp.net:4040
21/01/12 15:50:33 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
21/01/12 15:50:33 INFO MemoryStore: MemoryStore cleared
21/01/12 15:50:33 INFO BlockManager: BlockManager stopped
21/01/12 15:50:33 INFO BlockManagerMaster: BlockManagerMaster stopped
21/01/12 15:50:33 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
21/01/12 15:50:33 INFO SparkContext: Successfully stopped SparkContext
15:50:33.855 INFO  MarkDuplicatesSpark - Shutting down engine
[January 12, 2021 at 3:50:33 PM EST] org.broadinstitute.hellbender.tools.spark.transforms.markduplicates.MarkDuplicatesSpark done. Elapsed time: 0.06 minutes.
Runtime.totalMemory()=1065353216
java.lang.IllegalArgumentException: Unsupported class file major version 55
	at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:166)
	at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:148)
	at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:136)
	at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:237)
	at org.apache.spark.util.ClosureCleaner$.getClassReader(ClosureCleaner.scala:49)
	at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:517)
	at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:500)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:134)
	at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:134)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:236)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap$$anon$1.foreach(HashMap.scala:134)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at org.apache.spark.util.FieldAccessFinder$$anon$3.visitMethodInsn(ClosureCleaner.scala:500)
	at org.apache.xbean.asm6.ClassReader.readCode(ClassReader.java:2175)
	at org.apache.xbean.asm6.ClassReader.readMethod(ClassReader.java:1238)
	at org.apache.xbean.asm6.ClassReader.accept(ClassReader.java:631)
	at org.apache.xbean.asm6.ClassReader.accept(ClassReader.java:355)
	at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:307)
	at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:306)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:306)
	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:162)
	at org.apache.spark.SparkContext.clean(SparkContext.scala:2326)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2100)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2126)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:990)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:385)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:989)
	at org.apache.spark.RangePartitioner$.sketch(Partitioner.scala:309)
	at org.apache.spark.RangePartitioner.<init>(Partitioner.scala:171)
	at org.apache.spark.RangePartitioner.<init>(Partitioner.scala:151)
	at org.apache.spark.rdd.OrderedRDDFunctions$$anonfun$sortByKey$1.apply(OrderedRDDFunctions.scala:62)
	at org.apache.spark.rdd.OrderedRDDFunctions$$anonfun$sortByKey$1.apply(OrderedRDDFunctions.scala:61)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:385)
	at org.apache.spark.rdd.OrderedRDDFunctions.sortByKey(OrderedRDDFunctions.scala:61)
	at org.apache.spark.api.java.JavaPairRDD.sortByKey(JavaPairRDD.scala:936)
	at org.broadinstitute.hellbender.utils.spark.SparkUtils.sortUsingElementsAsKeys(SparkUtils.java:165)
	at org.broadinstitute.hellbender.utils.spark.SparkUtils.sortReadsAccordingToHeader(SparkUtils.java:143)
	at org.broadinstitute.hellbender.utils.spark.SparkUtils.querynameSortReadsIfNecessary(SparkUtils.java:306)
	at org.broadinstitute.hellbender.tools.spark.transforms.markduplicates.MarkDuplicatesSpark.mark(MarkDuplicatesSpark.java:206)
	at org.broadinstitute.hellbender.tools.spark.transforms.markduplicates.MarkDuplicatesSpark.mark(MarkDuplicatesSpark.java:270)
	at org.broadinstitute.hellbender.tools.spark.transforms.markduplicates.MarkDuplicatesSpark.runTool(MarkDuplicatesSpark.java:351)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:546)
	at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:31)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
21/01/12 15:50:33 INFO ShutdownHookManager: Shutdown hook called`

**Comment by droazen** [comment]
@seahearman This kind of error usually indicates that you are using a newer version of Java than we support (we support Java 8). What version of Java are you running, and if it's newer than 8 can you try running with 8 and see if the error goes away?
