### ISSUE TITLE
Funcotator to annotate VCF files with structural variants

### ISSUE THREAD

**Issue by lconde-ucl** [broadinstitute/gatk#7040]
Hi, 

I was wondering if it's possible to use funcotator to annotate a VCF with structural variants. I'm trying to use funcotator (GATK 4.1.9.0) to annotate a VCF from manta but it fails with the first variant (SVTYPE=DEL):

```
[...]
17:07:32.003 ERROR GencodeFuncotationFactory - Problem creating a GencodeFuncotation on transcript ENST00000378191.5 for variant: chr1:4709859-185537688(G* -> <DEL>): Variant overlaps transcript but is not completely contained 
within it. Funcotator cannot currently handle this case. Transcript: ENST00000378191.5  Variant: [VC Unknown @ chr1:4709859-185537688 Q. of type=SYMBOLIC alleles=[G*, <DEL>] attr={CIEND=[0, 4], CIPOS=[0, 4], END=185537688, HOML
EN=4, HOMSEQ=TCCT, SOMATIC=true, SOMATICSCORE=141, SVLEN=-180827829, SVTYPE=DEL} GT=PR:SR       68,0:94,0       38,23:94,24 filters=
17:07:32.003 WARN  GencodeFuncotationFactory - Creating default GencodeFuncotation on transcript ENST00000378191.5 for problem variant: chr1:4709859-185537688(G* -> <DEL>)
17:07:32.009 INFO  VcfFuncotationFactory - ClinVar_VCF 20180429_hg38 cache hits/total: 0/0
17:07:32.010 INFO  VcfFuncotationFactory - dbSNP 9606_b151 cache hits/total: 0/0
17:07:32.010 INFO  VcfFuncotationFactory - gnomAD_exome 2.1 cache hits/total: 0/0
17:07:32.010 INFO  VcfFuncotationFactory - gnomAD_genome 2.1 cache hits/total: 0/0
17:07:32.136 INFO  Funcotator - Shutting down engine
[14 January 2021 17:07:32 GMT] org.broadinstitute.hellbender.tools.funcotator.Funcotator done. Elapsed time: 0.77 minutes.
Runtime.totalMemory()=1426182144
java.lang.ArrayIndexOutOfBoundsException: 0
        at org.broadinstitute.hellbender.tools.funcotator.FuncotatorUtils.getNonOverlappingAltAlleleBaseString(FuncotatorUtils.java:294)
        at org.broadinstitute.hellbender.tools.funcotator.dataSources.gencode.GencodeFuncotationFactory.getGenomeChangeString(GencodeFuncotationFactory.java:2346)
        at org.broadinstitute.hellbender.tools.funcotator.dataSources.gencode.GencodeFuncotationFactory.createGencodeFuncotationBuilderWithTrivialFieldsPopulated(GencodeFuncotationFactory.java:2214)
        at org.broadinstitute.hellbender.tools.funcotator.dataSources.gencode.GencodeFuncotationFactory.createDefaultFuncotationsOnProblemVariant(GencodeFuncotationFactory.java:923)
[...]
```

I've seen that FuncotateSegments works for segment files with CNVs, but I was wondering if there is (or there are plans to add) support for VCF files with SVs.

Thanks
Lucia

**Comment by ldgauthier** [comment]
Hi Lucia,

Funcotator or FuncotateSegments support for SVs in VCFs is on our roadmap, but not top priority.  I took a crack at FuncotateSegments on VCFs a few months ago and it wasn't entirely trivial.  Development for Funcotator is on hold right now, but we may get back to it at the end of the summer.  Sorry I don't have good news for you.

-Laura
