### ISSUE TITLE
Mutect2 error when running inside a pipeline in parallel with intervals

### ISSUE THREAD

**Issue by Akazhiel** [broadinstitute/gatk#7059]
Upon running Mutect2 using the germline and pon provided by gatk inside a pipeline while running in parallel. If I use an intervals BED file I get the following error:

```
org.broadinstitute.hellbender.exceptions.GATKException: Error initializing feature reader for path /media/AGROS/hg19/af-only-gnomad.raw.sites.vcf.gz
	at org.broadinstitute.hellbender.engine.FeatureDataSource.getTribbleFeatureReader(FeatureDataSource.java:383)
	at org.broadinstitute.hellbender.engine.FeatureDataSource.getFeatureReader(FeatureDataSource.java:335)
	at org.broadinstitute.hellbender.engine.FeatureDataSource.<init>(FeatureDataSource.java:282)
	at org.broadinstitute.hellbender.engine.FeatureManager.addToFeatureSources(FeatureManager.java:246)
	at org.broadinstitute.hellbender.engine.FeatureManager.initializeFeatureSources(FeatureManager.java:209)
	at org.broadinstitute.hellbender.engine.FeatureManager.<init>(FeatureManager.java:156)
	at org.broadinstitute.hellbender.engine.GATKTool.initializeFeatures(GATKTool.java:488)
	at org.broadinstitute.hellbender.engine.GATKTool.onStartup(GATKTool.java:709)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.onStartup(AssemblyRegionWalker.java:79)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:138)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
Caused by: htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: /media/AGROS/hg19/af-only-gnomad.raw.sites.vcf.gz (Device or resource busy), for input source: /media/AGROS/hg19/af-only-gnomad.raw.sites.vcf.gz
	at htsjdk.tribble.TabixFeatureReader.readHeader(TabixFeatureReader.java:97)
	at htsjdk.tribble.TabixFeatureReader.<init>(TabixFeatureReader.java:82)
	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:117)
	at org.broadinstitute.hellbender.engine.FeatureDataSource.getTribbleFeatureReader(FeatureDataSource.java:380)
	... 14 more
Caused by: java.io.FileNotFoundException: /media/AGROS/hg19/af-only-gnomad.raw.sites.vcf.gz (Device or resource busy)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at htsjdk.samtools.seekablestream.SeekableFileStream.<init>(SeekableFileStream.java:47)
	at htsjdk.samtools.seekablestream.SeekableStreamFactory$DefaultSeekableStreamFactory.getStreamFor(SeekableStreamFactory.java:111)
	at htsjdk.tribble.TabixFeatureReader.readHeader(TabixFeatureReader.java:94)
	... 17 more
```

Which doesn't happen when running it without the intervals file.

I am using the latest version of GATK4 available in conda.

**Comment by fleharty** [comment]
@Akazhiel It looks like the problem is with your gnomad vcf.

Caused by: htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: /media/AGROS/hg19/af-only-gnomad.raw.sites.vcf.gz (Device or resource busy), for input source: /media/AGROS/hg19/af-only-gnomad.raw.sites.vcf.gz

Can you verify that `/media/AGROS/hg19/af-only-gnomad.raw.sites.vcf.gz` is not actually busy?
