### ISSUE TITLE
HaplotypeCaller: CRAMException: Attempt to unmapped with non zero alignment start (0) or span (150)

### ISSUE THREAD

**Issue by jjfarrell** [broadinstitute/gatk#7076]
### Affected tool(s) or class(es)
HaplotypeCaller

### Affected version(s)
gatk-package-4.1.9.0-33-g31df35b-SNAPSHOT-local.jar

### Description 

When run on the 30x 1000 genomes samples, I am getting this error. Not an issue on other crams we have.

 ```
/restricted/projectnb/genpro/github/gatk/gatk  HaplotypeCaller   -L chr22  -R /restricted/projectnb/casa/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa -I  cram/HG00096.final.cram  -O test.g.vcf.gz
Using GATK jar /rprojectnb2/genpro/github/gatk/build/libs/gatk-package-4.1.9.0-33-g31df35b-SNAPSHOT-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /rprojectnb2/genpro/github/gatk/build/libs/gatk-package-4.1.9.0-33-g31df35b-SNAPSHOT-local.jar HaplotypeCaller -L chr22 -R /restricted/projectnb/casa/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa -I cram/HG00096.final.cram -O test.g.vcf.gz
14:39:56.283 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/rprojectnb2/genpro/github/gatk/build/libs/gatk-package-4.1.9.0-33-g31df35b-SNAPSHOT-local.jar!/com/intel/gkl/native/libgkl_compression.so
Feb 10, 2021 2:39:56 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
14:39:56.484 INFO  HaplotypeCaller - ------------------------------------------------------------
14:39:56.484 INFO  HaplotypeCaller - The Genome Analysis Toolkit (GATK) v4.1.9.0-33-g31df35b-SNAPSHOT
14:39:56.484 INFO  HaplotypeCaller - For support and documentation go to https://software.broadinstitute.org/gatk/
14:39:56.485 INFO  HaplotypeCaller - Executing as farrell@scc-hadoop.bu.edu on Linux v3.10.0-1160.6.1.el7.x86_64 amd64
14:39:56.485 INFO  HaplotypeCaller - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_121-b13
14:39:56.485 INFO  HaplotypeCaller - Start Date/Time: February 10, 2021 2:39:56 PM EST
14:39:56.485 INFO  HaplotypeCaller - ------------------------------------------------------------
14:39:56.485 INFO  HaplotypeCaller - ------------------------------------------------------------
14:39:56.486 INFO  HaplotypeCaller - HTSJDK Version: 2.23.0
14:39:56.486 INFO  HaplotypeCaller - Picard Version: 2.23.3
14:39:56.486 INFO  HaplotypeCaller - HTSJDK Defaults.COMPRESSION_LEVEL : 2
14:39:56.486 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
14:39:56.486 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
14:39:56.486 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
14:39:56.486 INFO  HaplotypeCaller - Deflater: IntelDeflater
14:39:56.486 INFO  HaplotypeCaller - Inflater: IntelInflater
14:39:56.486 INFO  HaplotypeCaller - GCS max retries/reopens: 20
14:39:56.487 INFO  HaplotypeCaller - Requester pays: disabled
14:39:56.487 INFO  HaplotypeCaller - Initializing engine
14:39:57.467 INFO  HaplotypeCaller - Shutting down engine
[February 10, 2021 2:39:57 PM EST] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=1681391616
htsjdk.samtools.cram.CRAMException: Attempt to unmapped with non zero alignment start (0) or span (150)
        at htsjdk.samtools.cram.BAIEntry.<init>(BAIEntry.java:60)
        at htsjdk.samtools.cram.BAIEntry.<init>(BAIEntry.java:83)
        at htsjdk.samtools.cram.CRAIIndex.openCraiFileAsBaiStream(CRAIIndex.java:89)
        at htsjdk.samtools.SamIndexes.asBaiSeekableStreamOrNull(SamIndexes.java:91)
        at htsjdk.samtools.CRAMFileReader.initWithStreams(CRAMFileReader.java:202)
        at htsjdk.samtools.CRAMFileReader.<init>(CRAMFileReader.java:193)
        at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:422)
        at htsjdk.samtools.SamReaderFactory.open(SamReaderFactory.java:105)
        at org.broadinstitute.hellbender.engine.ReadsPathDataSource.<init>(ReadsPathDataSource.java:245)
        at org.broadinstitute.hellbender.engine.ReadsPathDataSource.<init>(ReadsPathDataSource.java:181)
        at org.broadinstitute.hellbender.engine.GATKTool.initializeReads(GATKTool.java:456)
        at org.broadinstitute.hellbender.engine.GATKTool.onStartup(GATKTool.java:705)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.onStartup(AssemblyRegionWalker.java:79)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:138)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
```
#### Steps to reproduce
`gatk  HaplotypeCaller   -L chr22  -R /restricted/projectnb/casa/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa -I  cram/HG00096.final.cram  -O test.g.vcf.gz`

The cram is HG0096.final.cram found here:

https://www.internationalgenome.org/data-portal/data-collection/30x-grch38

#### Expected behavior
When I run an earlier version v4.1.7.0, it runs without an error....

```
gatk HaplotypeCaller   -L chr22  -R /restricted/projectnb/casa/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa -I  cram/HG00096.final.cram  -O test.g.vcf.gz
Using GATK jar /share/pkg.7/gatk/4.1.7.0/install/bin/gatk-package-4.1.7.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /share/pkg.7/gatk/4.1.7.0/install/bin/gatk-package-4.1.7.0-local.jar HaplotypeCaller -L chr22 -R /restricted/projectnb/casa/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa -I cram/HG00096.final.cram -O test.g.vcf.gz
14:40:45.497 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/share/pkg.7/gatk/4.1.7.0/install/bin/gatk-package-4.1.7.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Feb 10, 2021 2:40:45 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
14:40:45.786 INFO  HaplotypeCaller - ------------------------------------------------------------
14:40:45.787 INFO  HaplotypeCaller - The Genome Analysis Toolkit (GATK) v4.1.7.0
14:40:45.787 INFO  HaplotypeCaller - For support and documentation go to https://software.broadinstitute.org/gatk/
14:40:45.788 INFO  HaplotypeCaller - Executing as farrell@scc-hadoop.bu.edu on Linux v3.10.0-1160.6.1.el7.x86_64 amd64
14:40:45.788 INFO  HaplotypeCaller - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_121-b13
14:40:45.789 INFO  HaplotypeCaller - Start Date/Time: February 10, 2021 2:40:45 PM EST
14:40:45.789 INFO  HaplotypeCaller - ------------------------------------------------------------
14:40:45.789 INFO  HaplotypeCaller - ------------------------------------------------------------
14:40:45.791 INFO  HaplotypeCaller - HTSJDK Version: 2.21.2
14:40:45.791 INFO  HaplotypeCaller - Picard Version: 2.21.9
14:40:45.791 INFO  HaplotypeCaller - HTSJDK Defaults.COMPRESSION_LEVEL : 2
14:40:45.791 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
14:40:45.791 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
14:40:45.792 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
14:40:45.792 INFO  HaplotypeCaller - Deflater: IntelDeflater
14:40:45.792 INFO  HaplotypeCaller - Inflater: IntelInflater
14:40:45.792 INFO  HaplotypeCaller - GCS max retries/reopens: 20
14:40:45.792 INFO  HaplotypeCaller - Requester pays: disabled
14:40:45.792 INFO  HaplotypeCaller - Initializing engine
14:40:47.694 INFO  IntervalArgumentCollection - Processing 50818468 bp from intervals
14:40:47.714 INFO  HaplotypeCaller - Done initializing engine
14:40:47.826 INFO  HaplotypeCallerEngine - Disabling physical phasing, which is supported only for reference-model confidence output
14:40:47.864 INFO  NativeLibraryLoader - Loading libgkl_utils.so from jar:file:/share/pkg.7/gatk/4.1.7.0/install/bin/gatk-package-4.1.7.0-local.jar!/com/intel/gkl/native/libgkl_utils.so
14:40:47.868 INFO  NativeLibraryLoader - Loading libgkl_pairhmm_omp.so from jar:file:/share/pkg.7/gatk/4.1.7.0/install/bin/gatk-package-4.1.7.0-local.jar!/com/intel/gkl/native/libgkl_pairhmm_omp.so
14:40:47.921 INFO  IntelPairHmm - Flush-to-zero (FTZ) is enabled when running PairHMM
14:40:47.922 INFO  IntelPairHmm - Available threads: 1
14:40:47.922 INFO  IntelPairHmm - Requested threads: 4
14:40:47.922 WARN  IntelPairHmm - Using 1 available threads, but 4 were requested
14:40:47.922 INFO  PairHMM - Using the OpenMP multi-threaded AVX-accelerated native PairHMM implementation
14:40:48.005 INFO  ProgressMeter - Starting traversal
14:40:48.006 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Regions Processed   Regions/Minute
14:40:51.792 WARN  InbreedingCoeff - InbreedingCoeff will not be calculated; at least 10 samples must have called genotypes
14:40:58.312 INFO  ProgressMeter -       chr22:10659064              0.2                 35790         208384.3
14:41:09.992 INFO  ProgressMeter -       chr22:10687910              0.4                 35990          98217.0

```

----

**Comment by jjfarrell** [comment]
I found this related issue in picard: [https://github.com/broadinstitute/picard/issues/1624]

I reindexed the cram with samtools 1.10  and it worked fined.

**Comment by cmnbroad** [comment]
@jjfarrell Thanks for the update. This error message indicates an invalid index file - older versions of GATK/HTSJDK didn't report these. Reindexing is the correct remedy.
