### ISSUE TITLE
 BaseRecalibrator:  cigar is completely soft-clipped

### ISSUE THREAD

**Issue by guandailu** [broadinstitute/gatk#7092]
gatk --java-options "-Xmx8G -XX:ParallelGCThreads=16 -Djava.io.tmpdir=/group/zhougrp2/dguan/tmp" BaseRecalibrator --spark-runner LOCAL -I 11_cigar/SAMN06242676_cigar.bam --known-sites /group/zhougrp2/dguan/00_ref/gallus_gallus.vcf.gz -L /group/zhougrp2/dguan/00_ref/chicken_chr.list -O 12_bqsr/SAMN06242676_bqsr.table -R /group/zhougrp2/dguan/00_ref/Gallus_gallus.GRCg6a.dna.toplevel.fa --tmp-dir /group/zhougrp2/dguan/tmp

00:59:52.106 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/dguan/anaconda3/envs/Chicken_GTEx/share/gatk4-4.2.0.0-0/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Feb 22, 2021 12:59:52 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
00:59:52.360 INFO  BaseRecalibrator - ------------------------------------------------------------
00:59:52.361 INFO  BaseRecalibrator - The Genome Analysis Toolkit (GATK) v4.2.0.0
00:59:52.361 INFO  BaseRecalibrator - For support and documentation go to https://software.broadinstitute.org/gatk/
00:59:52.361 INFO  BaseRecalibrator - Executing as dguan@c11-95 on Linux v4.15.0-122-generic amd64
00:59:52.361 INFO  BaseRecalibrator - Java runtime: OpenJDK 64-Bit Server VM v10.0.2+13
00:59:52.362 INFO  BaseRecalibrator - Start Date/Time: February 22, 2021 at 12:59:52 AM PST
00:59:52.362 INFO  BaseRecalibrator - ------------------------------------------------------------
00:59:52.362 INFO  BaseRecalibrator - ------------------------------------------------------------
00:59:52.363 INFO  BaseRecalibrator - HTSJDK Version: 2.24.0
00:59:52.363 INFO  BaseRecalibrator - Picard Version: 2.25.0
00:59:52.363 INFO  BaseRecalibrator - Built for Spark Version: 2.4.5
00:59:52.363 INFO  BaseRecalibrator - HTSJDK Defaults.COMPRESSION_LEVEL : 2
00:59:52.363 INFO  BaseRecalibrator - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
00:59:52.363 INFO  BaseRecalibrator - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
00:59:52.363 INFO  BaseRecalibrator - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
00:59:52.363 INFO  BaseRecalibrator - Deflater: IntelDeflater
00:59:52.363 INFO  BaseRecalibrator - Inflater: IntelInflater
00:59:52.364 INFO  BaseRecalibrator - GCS max retries/reopens: 20
00:59:52.364 INFO  BaseRecalibrator - Requester pays: disabled
00:59:52.364 INFO  BaseRecalibrator - Initializing engine
00:59:52.791 INFO  FeatureManager - Using codec VCFCodec to read file file:///group/zhougrp2/dguan/00_ref/gallus_gallus.vcf.gz
00:59:52.898 INFO  IntervalArgumentCollection - Processing 1050156598 bp from intervals
00:59:52.899 WARN  IndexUtils - Feature file "file:///group/zhougrp2/dguan/00_ref/gallus_gallus.vcf.gz" appears to contain no sequence dictionary. Attempting to retrieve a sequence dictionary from the associated index file
00:59:52.991 INFO  BaseRecalibrator - Done initializing engine
00:59:52.995 INFO  BaseRecalibrationEngine - The covariates being used here:
00:59:52.995 INFO  BaseRecalibrationEngine -    ReadGroupCovariate
00:59:52.995 INFO  BaseRecalibrationEngine -    QualityScoreCovariate
00:59:52.995 INFO  BaseRecalibrationEngine -    ContextCovariate
00:59:52.995 INFO  BaseRecalibrationEngine -    CycleCovariate
00:59:53.018 INFO  ProgressMeter - Starting traversal
00:59:53.019 INFO  ProgressMeter -        Current Locus  Elapsed Minutes       Reads Processed     Reads/Minute
01:00:03.047 INFO  ProgressMeter -              MT:4148              0.2                257000        1538001.2
01:00:13.085 INFO  ProgressMeter -              MT:6740              0.3                544000        1626632.1
01:00:23.103 INFO  ProgressMeter -              MT:7601              0.5                776000        1547718.0
01:00:33.103 INFO  ProgressMeter -              MT:8567              0.7                995000        1489372.3
01:00:43.125 INFO  ProgressMeter -              MT:9640              0.8               1244000        1489671.7
01:00:53.131 INFO  ProgressMeter -             MT:10923              1.0               1479000        1476244.3
01:01:03.141 INFO  ProgressMeter -             MT:13851              1.2               1803000        1542739.8
01:01:13.169 INFO  ProgressMeter -             MT:15853              1.3               2095000        1568329.0
01:01:23.180 INFO  ProgressMeter -            Z:2156900              1.5               2415000        1607125.0
01:01:33.184 INFO  ProgressMeter -           Z:15840013              1.7               2759000        1652673.1
01:01:43.208 INFO  ProgressMeter -           Z:33730372              1.8               3091000        1683123.4
01:01:53.232 INFO  ProgressMeter -           Z:55850726              2.0               3423000        1708467.5
01:02:03.242 INFO  ProgressMeter -              1:33940              2.2               3756000        1730569.9
01:02:13.259 INFO  ProgressMeter -           1:11334850              2.3               4089000        1749429.5
01:02:23.260 INFO  ProgressMeter -           1:26798501              2.5               4415000        1763167.2
01:02:33.276 INFO  ProgressMeter -           1:35708792              2.7               4730000        1770916.5
01:02:43.298 INFO  ProgressMeter -           1:48033895              2.8               5065000        1784728.5
01:02:53.307 INFO  ProgressMeter -           1:51709943              3.0               5413000        1801451.0
01:03:03.326 INFO  ProgressMeter -           1:58832330              3.2               5748000        1812229.7
01:03:13.359 INFO  ProgressMeter -           1:67564701              3.3               6075000        1819407.0
01:03:23.361 INFO  ProgressMeter -           1:77621333              3.5               6419000        1831026.8
01:03:33.377 INFO  ProgressMeter -           1:81044471              3.7               6779000        1845822.9
01:03:43.387 INFO  ProgressMeter -           1:88766011              3.8               7112000        1852340.6
01:03:53.399 INFO  ProgressMeter -           1:88779506              4.0               7462000        1862551.0
01:04:03.417 INFO  ProgressMeter -           1:88796600              4.2               7830000        1876213.1
01:04:13.421 INFO  ProgressMeter -          1:105457469              4.3               8162000        1880630.7
01:04:23.424 INFO  ProgressMeter -          1:113374016              4.5               8501000        1886281.7
01:04:33.436 INFO  ProgressMeter -          1:127147605              4.7               8817000        1886547.5
01:04:43.443 INFO  ProgressMeter -          1:138965591              4.8               9139000        1888067.1
01:04:53.461 INFO  ProgressMeter -          1:167660481              5.0               9446000        1886427.0
01:05:03.469 INFO  ProgressMeter -          1:177656998              5.2               9765000        1887260.4
01:05:13.487 INFO  ProgressMeter -          1:196220855              5.3              10066000        1884618.7
01:05:23.512 INFO  ProgressMeter -            2:3516013              5.5              10398000        1887725.3
01:05:33.540 INFO  ProgressMeter -           2:10356903              5.7              10722000        1889222.7
01:05:43.566 INFO  ProgressMeter -           2:20977535              5.8              11049000        1891164.1
01:05:53.589 INFO  ProgressMeter -           2:32842632              6.0              11379000        1893507.2
01:06:03.601 INFO  ProgressMeter -           2:43766841              6.2              11698000        1893993.8
01:06:13.626 INFO  ProgressMeter -           2:60526155              6.3              12003000        1892188.0
01:06:23.660 INFO  ProgressMeter -           2:84202964              6.5              12303000        1889668.2
01:06:33.661 INFO  ProgressMeter -          2:100884719              6.7              12628000        1891164.7
01:06:43.675 INFO  ProgressMeter -          2:111204571              6.8              12960000        1893560.3
01:06:53.704 INFO  ProgressMeter -          2:124686475              7.0              13287000        1895052.1
01:07:03.731 INFO  ProgressMeter -          2:137071793              7.2              13620000        1897323.5
01:07:13.742 INFO  ProgressMeter -            3:2716333              7.3              13947000        1898743.7
01:07:23.753 INFO  ProgressMeter -           3:10577374              7.5              14284000        1901436.1
01:07:33.774 INFO  ProgressMeter -           3:18728067              7.7              14612000        1902790.0
01:07:43.777 INFO  ProgressMeter -           3:31144576              7.8              14935000        1903525.8
01:07:53.794 INFO  ProgressMeter -           3:37727932              8.0              15293000        1908547.5
01:08:03.805 INFO  ProgressMeter -           3:46115674              8.2              15627000        1910445.7
01:08:13.819 INFO  ProgressMeter -           3:60896805              8.3              15939000        1909624.6
01:08:23.839 INFO  ProgressMeter -           3:66954967              8.5              16266000        1910575.2
01:08:33.861 INFO  ProgressMeter -           3:81506288              8.7              16589000        1911024.7
01:08:43.881 INFO  ProgressMeter -           3:96291777              8.8              16929000        1913378.6
01:08:53.889 INFO  ProgressMeter -          3:109934446              9.0              17254000        1914030.9
01:09:03.910 INFO  ProgressMeter -            4:3304206              9.2              17601000        1917007.0
01:09:13.913 INFO  ProgressMeter -           4:14216531              9.3              17918000        1916725.8
01:09:23.946 INFO  ProgressMeter -           4:29771360              9.5              18245000        1917411.4
01:09:33.971 INFO  ProgressMeter -           4:39357784              9.7              18573000        1918199.6
01:09:43.975 INFO  ProgressMeter -           4:49948970              9.8              18893000        1918217.1
01:09:53.990 INFO  ProgressMeter -           4:61122642             10.0              19223000        1919197.3
01:10:04.009 INFO  ProgressMeter -           4:77404115             10.2              19546000        1919442.2
01:10:14.027 INFO  ProgressMeter -           4:90982301             10.4              19859000        1918719.2
01:10:24.037 INFO  ProgressMeter -            5:5319910             10.5              20215000        1922132.2
01:10:34.043 INFO  ProgressMeter -           5:13428416             10.7              20557000        1924140.1
01:10:44.052 INFO  ProgressMeter -           5:18554429             10.9              20887000        1924971.5
01:10:54.053 INFO  ProgressMeter -           5:23247594             11.0              21241000        1927979.5
01:11:04.057 INFO  ProgressMeter -           5:25901452             11.2              21588000        1930263.3
01:11:14.089 INFO  ProgressMeter -           5:32482380             11.4              21916000        1930729.5
01:11:24.106 INFO  ProgressMeter -           5:38674297             11.5              22249000        1931652.6
01:11:34.133 INFO  ProgressMeter -           5:49679881             11.7              22573000        1931754.3
01:11:44.145 INFO  ProgressMeter -           5:53234595             11.9              22925000        1934259.1
04:10:15.659 INFO  ProgressMeter -            6:1726401            190.4              23183000         121774.0
04:10:25.671 INFO  ProgressMeter -           6:10206926            190.5              23517000         123420.2
04:10:31.341 INFO  BaseRecalibrator - Shutting down engine
[February 22, 2021 at 4:10:31 AM PST] org.broadinstitute.hellbender.tools.walkers.bqsr.BaseRecalibrator done. Elapsed time: 190.65 minutes.
Runtime.totalMemory()=1268776960
java.lang.IllegalStateException: cigar is completely soft-clipped
        at org.broadinstitute.hellbender.utils.Utils.validate(Utils.java:814)
        at org.broadinstitute.hellbender.utils.read.CigarBuilder.make(CigarBuilder.java:129)
        at org.broadinstitute.hellbender.utils.read.CigarBuilder.make(CigarBuilder.java:143)
        at org.broadinstitute.hellbender.utils.recalibration.BaseRecalibrationEngine.consolidateCigar(BaseRecalibrationEngine.java:293)
        at org.broadinstitute.hellbender.transformers.ReadTransformer.lambda$andThen$f85d1091$1(ReadTransformer.java:20)
        at org.broadinstitute.hellbender.transformers.ReadTransformer.lambda$andThen$f85d1091$1(ReadTransformer.java:20)
        at org.broadinstitute.hellbender.transformers.ReadTransformer.lambda$andThen$f85d1091$1(ReadTransformer.java:20)
        at org.broadinstitute.hellbender.transformers.ReadTransformer.lambda$andThen$f85d1091$1(ReadTransformer.java:20)
        at org.broadinstitute.hellbender.utils.recalibration.BaseRecalibrationEngine.processRead(BaseRecalibrationEngine.java:118)
        at org.broadinstitute.hellbender.tools.walkers.bqsr.BaseRecalibrator.apply(BaseRecalibrator.java:189)
        at org.broadinstitute.hellbender.engine.ReadWalker.lambda$traverse$0(ReadWalker.java:96)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at org.broadinstitute.hellbender.engine.ReadWalker.traverse(ReadWalker.java:94)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1058)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
Using GATK jar /home/dguan/anaconda3/envs/Chicken_GTEx/share/gatk4-4.2.0.0-0/gatk-package-4.2.0.0-local.jar

**Comment by droazen** [comment]
@davidbenjamin Could this be related to recent changes in the Cigar parsing code?

**Comment by davidbenjamin** [comment]
@droazen It's possible.  @guandailu Are you able to share a minimal set of inputs that reproduces the error?

**Comment by asortiz** [comment]
I have the same problem. Did you fix the error?

**Comment by guandailu** [comment]
Running https://github.com/tseemann/samclip before this step can fix it
