### ISSUE TITLE
FilterMutectCalls: Error initializing feature reader

### ISSUE THREAD

**Issue by Ning-310** [broadinstitute/gatk#7114]
Using GATK jar /usr/local/gatk-4.1.3.0/gatk-package-4.1.3.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /usr/local/gatk-4.1.3.0/gatk-package-4.1.3.0-local.jar FilterMutectCalls -R /data/nws/WES/reference/Homo_sapiens_assembly38.fasta -V /data/nws/WES/GenomicsDBImport/200924_A00679_0401_AHKGKKDSXY/Set13-3_L3_379X79.somatic.vcf.gz --contamination-table /data/nws/WES/GenomicsDBImport/200924_A00679_0401_AHKGKKDSXY/Set13-3_L3_379X79.getpileupsummaries.calculatecontamination.table -O /data/nws/WES/GenomicsDBImport/200924_A00679_0401_AHKGKKDSXY/Set13-3_L3_379X79.somatic.filterMutectCalls.vcf.gz
22:08:32.885 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/local/gatk-4.1.3.0/gatk-package-4.1.3.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
22:08:48.358 INFO  FilterMutectCalls - ------------------------------------------------------------
22:08:48.359 INFO  FilterMutectCalls - The Genome Analysis Toolkit (GATK) v4.1.3.0
22:08:48.359 INFO  FilterMutectCalls - For support and documentation go to https://software.broadinstitute.org/gatk/
22:09:03.373 INFO  FilterMutectCalls - Executing as nws@cuckoolab on Linux v3.10.0-1127.19.1.el7.x86_64 amd64
22:09:03.374 INFO  FilterMutectCalls - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_262-b10
22:09:03.374 INFO  FilterMutectCalls - Start Date/Time: 2021年2月28日 下午10时08分32秒
22:09:03.374 INFO  FilterMutectCalls - ------------------------------------------------------------
22:09:03.374 INFO  FilterMutectCalls - ------------------------------------------------------------
22:09:03.376 INFO  FilterMutectCalls - HTSJDK Version: 2.20.1
22:09:03.376 INFO  FilterMutectCalls - Picard Version: 2.20.5
22:09:03.376 INFO  FilterMutectCalls - HTSJDK Defaults.COMPRESSION_LEVEL : 2
22:09:03.376 INFO  FilterMutectCalls - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
22:09:03.376 INFO  FilterMutectCalls - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
22:09:03.377 INFO  FilterMutectCalls - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
22:09:03.377 INFO  FilterMutectCalls - Deflater: IntelDeflater
22:09:03.377 INFO  FilterMutectCalls - Inflater: IntelInflater
22:09:03.377 INFO  FilterMutectCalls - GCS max retries/reopens: 20
22:09:03.377 INFO  FilterMutectCalls - Requester pays: disabled
22:09:03.378 INFO  FilterMutectCalls - Initializing engine
22:09:04.031 INFO  FeatureManager - Using codec VCFCodec to read file file:///data/nws/WES/GenomicsDBImport/200924_A00679_0401_AHKGKKDSXY/Set13-3_L3_379X79.somatic.vcf.gz
22:09:04.071 INFO  FilterMutectCalls - Shutting down engine
[2021年2月28日 下午10时09分04秒] org.broadinstitute.hellbender.tools.walkers.mutect.filtering.FilterMutectCalls done. Elapsed time: 0.52 minutes.
Runtime.totalMemory()=1552416768
org.broadinstitute.hellbender.exceptions.GATKException: Error initializing feature reader for path /data/nws/WES/GenomicsDBImport/200924_A00679_0401_AHKGKKDSXY/Set13-3_L3_379X79.somatic.vcf.gz
	at org.broadinstitute.hellbender.engine.FeatureDataSource.getTribbleFeatureReader(FeatureDataSource.java:375)
	at org.broadinstitute.hellbender.engine.FeatureDataSource.getFeatureReader(FeatureDataSource.java:327)
	at org.broadinstitute.hellbender.engine.FeatureDataSource.<init>(FeatureDataSource.java:277)
	at org.broadinstitute.hellbender.engine.VariantWalker.initializeDrivingVariants(VariantWalker.java:58)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.initializeFeatures(VariantWalkerBase.java:67)
	at org.broadinstitute.hellbender.engine.GATKTool.onStartup(GATKTool.java:706)
	at org.broadinstitute.hellbender.engine.VariantWalker.onStartup(VariantWalker.java:45)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:137)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)
Caused by: htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: Did not inflate expected amount, for input source: /data/nws/WES/GenomicsDBImport/200924_A00679_0401_AHKGKKDSXY/Set13-3_L3_379X79.somatic.vcf.gz
	at htsjdk.tribble.TabixFeatureReader.readHeader(TabixFeatureReader.java:97)
	at htsjdk.tribble.TabixFeatureReader.<init>(TabixFeatureReader.java:82)
	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:117)
	at org.broadinstitute.hellbender.engine.FeatureDataSource.getTribbleFeatureReader(FeatureDataSource.java:372)
	... 12 more
Caused by: htsjdk.samtools.SAMFormatException: Did not inflate expected amount
	at htsjdk.samtools.util.BlockGunzipper.unzipBlock(BlockGunzipper.java:147)
	at htsjdk.samtools.util.BlockGunzipper.unzipBlock(BlockGunzipper.java:96)
	at htsjdk.samtools.util.BlockCompressedInputStream.inflateBlock(BlockCompressedInputStream.java:550)
	at htsjdk.samtools.util.BlockCompressedInputStream.processNextBlock(BlockCompressedInputStream.java:532)
	at htsjdk.samtools.util.BlockCompressedInputStream.nextBlock(BlockCompressedInputStream.java:468)
	at htsjdk.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:458)
	at htsjdk.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:196)
	at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:331)
	at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:257)
	at htsjdk.tribble.readers.PositionalBufferedStream.fill(PositionalBufferedStream.java:132)
	at htsjdk.tribble.readers.PositionalBufferedStream.read(PositionalBufferedStream.java:84)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at htsjdk.tribble.readers.LongLineBufferedReader.fill(LongLineBufferedReader.java:140)
	at htsjdk.tribble.readers.LongLineBufferedReader.readLine(LongLineBufferedReader.java:300)
	at htsjdk.tribble.readers.LongLineBufferedReader.readLine(LongLineBufferedReader.java:356)
	at htsjdk.tribble.readers.SynchronousLineReader.readLine(SynchronousLineReader.java:51)
	at htsjdk.tribble.readers.LineIteratorImpl.advance(LineIteratorImpl.java:24)
	at htsjdk.tribble.readers.LineIteratorImpl.advance(LineIteratorImpl.java:11)
	at htsjdk.samtools.util.AbstractIterator.hasNext(AbstractIterator.java:44)
	at htsjdk.variant.vcf.VCFCodec.readActualHeader(VCFCodec.java:89)
	at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:79)
	at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:37)
	at htsjdk.tribble.TabixFeatureReader.readHeader(TabixFeatureReader.java:95)
	... 15 more

**Comment by droazen** [comment]
@Ning-310 The error you're getting here ("Did not inflate expected amount") implies that your input file is likely corrupt. Can you try running the tool `PrintBGZFBlockInformation` to validate the compressed blocks in your `.vcf.gz`?
