### ISSUE TITLE
CalibrateDragstrModel fails with a non zero alignment start or span

### ISSUE THREAD

**Issue by ahaessly** [broadinstitute/gatk#7152]
### Affected tool(s) or class(es)
CalibrateDragstrModel

### Affected version(s)
Custom build: us.gcr.io/broad-dsde-methods/broad-gatk-snapshots/dragen_final_test_v2

### Description 
An exception occurs on some AoU crams when running CalibrateDragstrModel
We have tried reindexing the cram.
This data is not public but @ahaessly can be a resource to help with debugging and testing.

htsjdk.samtools.cram.CRAMException: Attempt to unmapped with non zero alignment start (0) or span (-2147483647)
	at htsjdk.samtools.cram.BAIEntry.<init>(BAIEntry.java:60)
	at htsjdk.samtools.cram.BAIEntry.<init>(BAIEntry.java:83)
	at htsjdk.samtools.cram.CRAIIndex.openCraiFileAsBaiStream(CRAIIndex.java:89)
	at htsjdk.samtools.SamIndexes.asBaiSeekableStreamOrNull(SamIndexes.java:91)
	at htsjdk.samtools.CRAMFileReader.initWithStreams(CRAMFileReader.java:202)
	at htsjdk.samtools.CRAMFileReader.<init>(CRAMFileReader.java:193)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:422)
	at htsjdk.samtools.SamReaderFactory.open(SamReaderFactory.java:105)
	at org.broadinstitute.hellbender.engine.ReadsPathDataSource.<init>(ReadsPathDataSource.java:245)
	at org.broadinstitute.hellbender.engine.ReadsPathDataSource.<init>(ReadsPathDataSource.java:181)
	at org.broadinstitute.hellbender.engine.GATKTool.initializeReads(GATKTool.java:459)
	at org.broadinstitute.hellbender.engine.GATKTool.onStartup(GATKTool.java:708)
	at org.broadinstitute.hellbender.tools.dragstr.CalibrateDragstrModel.onStartup(CalibrateDragstrModel.java:108)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:138)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
Using GATK jar /gatk/gatk-package-4.1.9.0-15-g8f07c46-SNAPSHOT-local.jar

#### Steps to reproduce
    gatk --java-options "-Xmx7g -DGATK_STACKTRACE_ON_USER_EXCEPTION=true -Dsamjdk.reference_fasta=~{ref_fasta}" \
      CalibrateDragstrModel \
        -R ~{ref_fasta} \
        -I ~{alignment} \
        -str ~{str_table_file} \
        -O ~{out_file_name} \
        ~{parallel_args} \
        --verbosity DEBUG

#### Expected behavior
CalibrateDragstrModel should finish successfully

#### Actual behavior
See stack trace above

**Comment by cmnbroad** [comment]
@ahaessly This error message indicates a corrupt .crai index file - you should see the same message if you try to read the file with any other GATK tool. Regenerating the index should fix it. Also, let me know if you happen to know what software/version created the index.

**Comment by droazen** [comment]
@cmnbroad According to the report, they've already tried reindexing (that was my first suggestion as well...)

**Comment by jamesemery** [comment]
@ahaessly It looks like you are still running on a somewhat old snapshot of the DRAGEN code. It might be worth updating to master and re-running since we fixed some other errors related to this tool since 4.2 that you might want anyway.

**Comment by ahaessly** [comment]
Is this in the gatk repo or a different repo?

**Comment by jamesemery** [comment]
@ahaessly The particular fix I have in mind actually went in before 4.2.0.0 which is explicitly fixing another (and possibly unrelated bug) with crams and that tool. I would suggest using broadinstitute/gatk:4.2.0.0 as your docker image, i'm not sure if it will fix this bug but it should fix another one you might hit.

**Comment by cmnbroad** [comment]
Oh, I missed that they had already tried reindexing. @ahaessly can you find out what tool and what version was used to reindex this file ?  We've had several reports of this error message in the last month or two, but reindexing has usually fixed it. I had been assuming that the corrupt index files were created by older versions of GATK/Picard tools, but it would super helpful to know if current versions of either samtools or GATK/Picard is creating these, and will help determine if we need to relax this check.

**Comment by ahaessly** [comment]
Thanks for all the help. Using the 4.2.0.0 docker resolved the problem!
