### ISSUE TITLE
CalibrateDragstrModel java.lang.IllegalArgumentException: Start cannot exceed end.

### ISSUE THREAD

**Issue by jjfarrell** [broadinstitute/gatk#7182]
### Affected tool(s) or class(es)
_Tool/class name(s), special parameters?_
 CalibrateDragstrModel
### Affected version(s)
- [ ] Latest public release version [gatk/4.2.0.0]

### Description 

gatk 4.2.0.0  CalibrateDragstrModel  produces the following stacktrace....

```
13:55:31.187 INFO  CalibrateDragstrModel - Initializing engine
13:55:33.395 INFO  CalibrateDragstrModel - Done initializing engine
13:55:33.396 INFO  ProgressMeter - Starting traversal
13:55:33.396 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Records Processed   Records/Minute
13:55:42.364 INFO  CalibrateDragstrModel - Shutting down engine
[April 4, 2021 1:55:42 PM EDT] org.broadinstitute.hellbender.tools.dragstr.CalibrateDragstrModel done. Elapsed time: 0.19 minutes.
Runtime.totalMemory()=2384986112
java.lang.IllegalArgumentException: Start cannot exceed end.
        at htsjdk.samtools.util.IntervalTree.put(IntervalTree.java:74)
        at htsjdk.samtools.util.IntervalTree.merge(IntervalTree.java:137)
        at org.broadinstitute.hellbender.tools.dragstr.CalibrateDragstrModel$ShardReadBuffer.add(CalibrateDragstrModel.java:949)
        at org.broadinstitute.hellbender.tools.dragstr.CalibrateDragstrModel$1.tryAdvance(CalibrateDragstrModel.java:798)
        at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.broadinstitute.hellbender.tools.dragstr.CalibrateDragstrModel.collectCaseStatsSequencial(CalibrateDragstrModel.java:459)
        at org.broadinstitute.hellbender.tools.dragstr.CalibrateDragstrModel.traverse(CalibrateDragstrModel.java:159)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1058)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

#### Steps to reproduce

This is test script (test.sh) that is used.
```
module load gatk
CRAM=$1
SAMPLE=$(basename $CRAM)
SAMPLE=${SAMPLE/\.cram/}
mkdir -p gvcf.STR/$SAMPLE
mkdir -p gvcf.STR/$SAMPLE/tmp
gatk --java-options "-Xmx16G" ComposeSTRTableFile  -R /restricted/projectnb/casa/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa -O  gvcf.STR/$SAMPLE/$SAMPLE.STR.table -I $CRAM
gatk --java-options "-Xmx16G" CalibrateDragstrModel  -R /restricted/projectnb/casa/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa --str-table-path gvcf.STR/$SAMPLE/$SAMPLE.STR.table -O  gvcf.STR/$SAMPLE/$SAMPLE.Dragstr.model -I $CRAM

```
The script runs the ComposeSTRTableFile  to produce the  table that is then read by CalibrateDragstrModel. 
```
./test.sh  /restricted/projectnb/casa/wgs.hg38/adni/cram/ADNI_002_S_0413.hg38.realign.bqsr.cram
Using GATK jar /share/pkg.7/gatk/4.2.0.0/install/bin/gatk-package-4.2.0.0-local.jar defined in environment variable GATK_LOCAL_JAR
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx16G -jar /share/pkg.7/gatk/4.2.0.0/install/bin/gatk-package-4.2.0.0-local.jar ComposeSTRTableFile -R /restricted/projectnb/casa/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa -O gvcf.STR/ADNI_002_S_0413.hg38.realign.bqsr/ADNI_002_S_0413.hg38.realign.bqsr.STR.table -I /restricted/projectnb/casa/wgs.hg38/adni/cram/ADNI_002_S_0413.hg38.realign.bqsr.cram
13:44:55.228 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/share/pkg.7/gatk/4.2.0.0/install/bin/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Apr 04, 2021 1:44:55 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
13:44:55.456 INFO  ComposeSTRTableFile - ------------------------------------------------------------
13:44:55.458 INFO  ComposeSTRTableFile - The Genome Analysis Toolkit (GATK) v4.2.0.0
13:44:55.458 INFO  ComposeSTRTableFile - For support and documentation go to https://software.broadinstitute.org/gatk/
13:44:55.459 INFO  ComposeSTRTableFile - Executing as farrell@scc-hadoop.bu.edu on Linux v3.10.0-1160.15.2.el7.x86_64 amd64
13:44:55.459 INFO  ComposeSTRTableFile - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_121-b13
13:44:55.460 INFO  ComposeSTRTableFile - Start Date/Time: April 4, 2021 1:44:55 PM EDT
13:44:55.460 INFO  ComposeSTRTableFile - ------------------------------------------------------------
13:44:55.460 INFO  ComposeSTRTableFile - ------------------------------------------------------------
13:44:55.461 INFO  ComposeSTRTableFile - HTSJDK Version: 2.24.0
13:44:55.461 INFO  ComposeSTRTableFile - Picard Version: 2.25.0
13:44:55.461 INFO  ComposeSTRTableFile - Built for Spark Version: 2.4.5
13:44:55.462 INFO  ComposeSTRTableFile - HTSJDK Defaults.COMPRESSION_LEVEL : 2
13:44:55.462 INFO  ComposeSTRTableFile - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
13:44:55.462 INFO  ComposeSTRTableFile - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
13:44:55.462 INFO  ComposeSTRTableFile - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
13:44:55.462 INFO  ComposeSTRTableFile - Deflater: IntelDeflater
13:44:55.462 INFO  ComposeSTRTableFile - Inflater: IntelInflater
13:44:55.463 INFO  ComposeSTRTableFile - GCS max retries/reopens: 20
13:44:55.463 INFO  ComposeSTRTableFile - Requester pays: disabled
13:44:55.463 INFO  ComposeSTRTableFile - Initializing engine
13:44:57.975 INFO  ComposeSTRTableFile - Done initializing engine
13:44:57.976 INFO  ProgressMeter - Starting traversal
13:44:57.976 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Records Processed   Records/Minute
13:45:08.048 INFO  ProgressMeter -        chr1:42998284              0.2                105000         625682.8
13:45:18.106 INFO  ProgressMeter -        chr1:90943284              0.3                212000         631924.1
13:45:28.147 INFO  ProgressMeter -       chr1:153945581              0.5                310000         616506.5
13:45:38.154 INFO  ProgressMeter -       chr1:202615984              0.7                421000         628702.3
13:45:48.225 INFO  ProgressMeter -         chr2:1941070              0.8                531000         634055.1
13:45:58.240 INFO  ProgressMeter -        chr2:49659608              1.0                639000         636211.3
13:46:08.286 INFO  ProgressMeter -       chr2:103513820              1.2                756000         645152.1
13:46:18.327 INFO  ProgressMeter -       chr2:153034723              1.3                867000         647409.5
13:46:28.385 INFO  ProgressMeter -       chr2:201423682              1.5                974000         646395.8
13:46:38.450 INFO  ProgressMeter -        chr3:11175996              1.7               1092000         652109.0
13:46:48.537 INFO  ProgressMeter -        chr3:61344338              1.8               1204000         653395.0
13:46:58.559 INFO  ProgressMeter -       chr3:112871812              2.0               1316000         654824.1
13:47:08.644 INFO  ProgressMeter -       chr3:162593171              2.2               1426000         654789.2
13:47:18.713 INFO  ProgressMeter -        chr4:14055098              2.3               1540000         656548.4
13:47:28.742 INFO  ProgressMeter -        chr4:66479382              2.5               1658000         659830.5
13:47:38.833 INFO  ProgressMeter -       chr4:116310391              2.7               1768000         659471.8
13:47:48.885 INFO  ProgressMeter -       chr4:166670242              2.8               1880000         660000.4
13:47:58.933 INFO  ProgressMeter -        chr5:25414046              3.0               1989000         659493.7
13:48:09.000 INFO  ProgressMeter -        chr5:76365488              3.2               2096000         658350.0
13:48:19.058 INFO  ProgressMeter -       chr5:126855973              3.4               2207000         658540.6
13:48:29.058 INFO  ProgressMeter -       chr5:177743197              3.5               2322000         660031.0
13:48:39.091 INFO  ProgressMeter -        chr6:46449492              3.7               2439000         661830.5
13:48:49.151 INFO  ProgressMeter -        chr6:97010127              3.9               2547000         661060.5
13:48:59.155 INFO  ProgressMeter -       chr6:146751123              4.0               2658000         661254.3
13:49:09.192 INFO  ProgressMeter -        chr7:25868131              4.2               2771000         661823.5
13:49:19.268 INFO  ProgressMeter -        chr7:77163995              4.4               2889000         663395.7
13:49:29.286 INFO  ProgressMeter -       chr7:128622064              4.5               3006000         664774.6
13:49:39.333 INFO  ProgressMeter -        chr8:20402621              4.7               3122000         665773.4
13:49:49.377 INFO  ProgressMeter -        chr8:70681881              4.9               3234000         665888.8
13:49:59.436 INFO  ProgressMeter -       chr8:121545299              5.0               3347000         666160.2
13:50:09.497 INFO  ProgressMeter -        chr9:27336801              5.2               3459000         666217.3
13:50:19.517 INFO  ProgressMeter -        chr9:92332709              5.4               3566000         665420.6
13:50:29.548 INFO  ProgressMeter -        chr10:4876459              5.5               3684000         666642.5
13:50:39.583 INFO  ProgressMeter -       chr10:52932295              5.7               3796000         666733.0
13:50:49.591 INFO  ProgressMeter -      chr10:104451896              5.9               3915000         668060.2
13:50:59.644 INFO  ProgressMeter -       chr11:23152548              6.0               4029000         668404.9
13:51:09.683 INFO  ProgressMeter -       chr11:73613080              6.2               4138000         667945.5
13:51:19.694 INFO  ProgressMeter -      chr11:122361866              6.4               4246000         667405.4
13:51:29.754 INFO  ProgressMeter -       chr12:37376295              6.5               4356000         667114.2
13:51:39.779 INFO  ProgressMeter -       chr12:87787512              6.7               4471000         667640.6
13:51:49.840 INFO  ProgressMeter -       chr13:19555804              6.9               4587000         668231.9
13:51:59.894 INFO  ProgressMeter -       chr13:69848941              7.0               4700000         668376.3
13:52:09.962 INFO  ProgressMeter -       chr14:22490612              7.2               4808000         667799.4
13:52:19.979 INFO  ProgressMeter -       chr14:72879509              7.4               4922000         668140.3
13:52:29.993 INFO  ProgressMeter -       chr15:31216833              7.5               5030000         667675.5
13:52:40.030 INFO  ProgressMeter -       chr15:82734767              7.7               5149000         668624.6
13:52:50.039 INFO  ProgressMeter -       chr16:30074394              7.9               5270000         669827.3
13:53:00.047 INFO  ProgressMeter -       chr16:86860982              8.0               5383000         669985.7
13:53:10.116 INFO  ProgressMeter -       chr17:48023279              8.2               5507000         671395.7
13:53:20.206 INFO  ProgressMeter -       chr18:16344776              8.4               5630000         672600.2
13:53:30.209 INFO  ProgressMeter -       chr18:68075874              8.5               5740000         672351.6
13:53:40.253 INFO  ProgressMeter -       chr19:40111935              8.7               5871000         674471.0
13:53:50.326 INFO  ProgressMeter -       chr20:33030731              8.9               5993000         675459.1
13:54:00.362 INFO  ProgressMeter -       chr21:27087627              9.0               6111000         676013.0
13:54:10.423 INFO  ProgressMeter -       chr22:41712333              9.2               6226000         676191.6
13:54:20.447 INFO  ProgressMeter -        chrX:39799780              9.4               6342000         676514.9
13:54:30.520 INFO  ProgressMeter -        chrX:91818371              9.5               6453000         676246.2
13:54:40.591 INFO  ProgressMeter -       chrX:143619069              9.7               6568000         676399.8
13:54:50.640 INFO  ProgressMeter - chrUn_KI270743v1:125398              9.9               6674000         675662.2
13:55:00.673 INFO  ProgressMeter - chr20_KI270869v1_alt:62679             10.0               6792000         676161.8
13:55:10.679 INFO  ProgressMeter - chr19_GL949752v1_alt:485077             10.2               6910000         676673.7
13:55:26.149 INFO  ProgressMeter - HLA-DRB1*11:01:02:3272             10.5               6938356         662718.7
13:55:26.149 INFO  ProgressMeter - Traversal complete. Processed 6938356 total records in 10.5 minutes.
13:55:26.149 INFO  ComposeSTRTableFile - Shutting down engine
[April 4, 2021 1:55:26 PM EDT] org.broadinstitute.hellbender.tools.dragstr.ComposeSTRTableFile done. Elapsed time: 10.52 minutes.
Runtime.totalMemory()=1128792064
Using GATK jar /share/pkg.7/gatk/4.2.0.0/install/bin/gatk-package-4.2.0.0-local.jar defined in environment variable GATK_LOCAL_JAR
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx16G -jar /share/pkg.7/gatk/4.2.0.0/install/bin/gatk-package-4.2.0.0-local.jar CalibrateDragstrModel -R /restricted/projectnb/casa/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa --str-table-path gvcf.STR/ADNI_002_S_0413.hg38.realign.bqsr/ADNI_002_S_0413.hg38.realign.bqsr.STR.table -O gvcf.STR/ADNI_002_S_0413.hg38.realign.bqsr/ADNI_002_S_0413.hg38.realign.bqsr.Dragstr.model -I /restricted/projectnb/casa/wgs.hg38/adni/cram/ADNI_002_S_0413.hg38.realign.bqsr.cram
13:55:30.890 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/share/pkg.7/gatk/4.2.0.0/install/bin/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Apr 04, 2021 1:55:31 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
13:55:31.182 INFO  CalibrateDragstrModel - ------------------------------------------------------------
13:55:31.183 INFO  CalibrateDragstrModel - The Genome Analysis Toolkit (GATK) v4.2.0.0
13:55:31.183 INFO  CalibrateDragstrModel - For support and documentation go to https://software.broadinstitute.org/gatk/
13:55:31.183 INFO  CalibrateDragstrModel - Executing as farrell@scc-hadoop.bu.edu on Linux v3.10.0-1160.15.2.el7.x86_64 amd64
13:55:31.184 INFO  CalibrateDragstrModel - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_121-b13
13:55:31.184 INFO  CalibrateDragstrModel - Start Date/Time: April 4, 2021 1:55:30 PM EDT
13:55:31.184 INFO  CalibrateDragstrModel - ------------------------------------------------------------
13:55:31.184 INFO  CalibrateDragstrModel - ------------------------------------------------------------
13:55:31.185 INFO  CalibrateDragstrModel - HTSJDK Version: 2.24.0
13:55:31.185 INFO  CalibrateDragstrModel - Picard Version: 2.25.0
13:55:31.185 INFO  CalibrateDragstrModel - Built for Spark Version: 2.4.5
13:55:31.185 INFO  CalibrateDragstrModel - HTSJDK Defaults.COMPRESSION_LEVEL : 2
13:55:31.186 INFO  CalibrateDragstrModel - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
13:55:31.186 INFO  CalibrateDragstrModel - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
13:55:31.186 INFO  CalibrateDragstrModel - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
13:55:31.186 INFO  CalibrateDragstrModel - Deflater: IntelDeflater
13:55:31.186 INFO  CalibrateDragstrModel - Inflater: IntelInflater
13:55:31.186 INFO  CalibrateDragstrModel - GCS max retries/reopens: 20
13:55:31.186 INFO  CalibrateDragstrModel - Requester pays: disabled
13:55:31.187 WARN  CalibrateDragstrModel -

   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

   Warning: CalibrateDragstrModel is a BETA tool and is not yet ready for use in production

   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


13:55:31.187 INFO  CalibrateDragstrModel - Initializing engine
13:55:33.395 INFO  CalibrateDragstrModel - Done initializing engine
13:55:33.396 INFO  ProgressMeter - Starting traversal
13:55:33.396 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Records Processed   Records/Minute
13:55:42.364 INFO  CalibrateDragstrModel - Shutting down engine
[April 4, 2021 1:55:42 PM EDT] org.broadinstitute.hellbender.tools.dragstr.CalibrateDragstrModel done. Elapsed time: 0.19 minutes.
Runtime.totalMemory()=2384986112
java.lang.IllegalArgumentException: Start cannot exceed end.
        at htsjdk.samtools.util.IntervalTree.put(IntervalTree.java:74)
        at htsjdk.samtools.util.IntervalTree.merge(IntervalTree.java:137)
        at org.broadinstitute.hellbender.tools.dragstr.CalibrateDragstrModel$ShardReadBuffer.add(CalibrateDragstrModel.java:949)
        at org.broadinstitute.hellbender.tools.dragstr.CalibrateDragstrModel$1.tryAdvance(CalibrateDragstrModel.java:798)
        at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.broadinstitute.hellbender.tools.dragstr.CalibrateDragstrModel.collectCaseStatsSequencial(CalibrateDragstrModel.java:459)
        at org.broadinstitute.hellbender.tools.dragstr.CalibrateDragstrModel.traverse(CalibrateDragstrModel.java:159)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1058)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

#### Expected behavior

Runs to completed and writes out model file.

#### Actual behavior
_Tell us what happens instead_

The following error occurs....
```
13:55:33.396 INFO  ProgressMeter - Starting traversal
13:55:33.396 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Records Processed   Records/Minute
13:55:42.364 INFO  CalibrateDragstrModel - Shutting down engine
[April 4, 2021 1:55:42 PM EDT] org.broadinstitute.hellbender.tools.dragstr.CalibrateDragstrModel done. Elapsed time: 0.19 minutes.
Runtime.totalMemory()=2384986112
java.lang.IllegalArgumentException: Start cannot exceed end.
        at htsjdk.samtools.util.IntervalTree.put(IntervalTree.java:74)
        at htsjdk.samtools.util.IntervalTree.merge(IntervalTree.java:137)
        at org.broadinstitute.hellbender.tools.dragstr.CalibrateDragstrModel$ShardReadBuffer.add(CalibrateDragstrModel.java:949)
        at org.broadinstitute.hellbender.tools.dragstr.CalibrateDragstrModel$1.tryAdvance(CalibrateDragstrModel.java:798)
        at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.broadinstitute.hellbender.tools.dragstr.CalibrateDragstrModel.collectCaseStatsSequencial(CalibrateDragstrModel.java:459)
        at org.broadinstitute.hellbender.tools.dragstr.CalibrateDragstrModel.traverse(CalibrateDragstrModel.java:159)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1058)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)

```

**Comment by droazen** [comment]
@vruano Could you look into this one?

**Comment by vruano** [comment]
We have run this tools successfully with a number of crams and bam at this point so we will need access to the data to reproduce the issue on our end. Would that be possible @jjfarrell?

**Comment by jjfarrell** [comment]
@vruano Yes, I located a cram that I can upload that produces the error.  Where should I transfer it to?

**Comment by jjfarrell** [comment]
@vruano The HGDP crams also seem to trigger this error. 

 ftp:/­/­ftp.­1000genomes.­ebi.­ac.­uk/­vol1/­ftp/­data_collections/­HGDP/­data/­Brahui/­HGDP00001/­alignment/­HGDP00001.­alt_bwamem_GRCh38DH.­20181023.­Brahui.­cram


```
14:32:34.745 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/share/pkg.7/gatk/4.2.0.0/install/bin/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Apr 17, 2021 2:32:34 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
14:32:34.877 INFO  CalibrateDragstrModel - ------------------------------------------------------------
14:32:34.877 INFO  CalibrateDragstrModel - The Genome Analysis Toolkit (GATK) v4.2.0.0
14:32:34.877 INFO  CalibrateDragstrModel - For support and documentation go to https://software.broadinstitute.org/gatk/
14:32:34.877 INFO  CalibrateDragstrModel - Executing as farrell@scc-gh3.scc.bu.edu on Linux v3.10.0-1160.15.2.el7.x86_64 amd64
14:32:34.877 INFO  CalibrateDragstrModel - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_172-b11
14:32:34.877 INFO  CalibrateDragstrModel - Start Date/Time: April 17, 2021 2:32:34 PM EDT
14:32:34.878 INFO  CalibrateDragstrModel - ------------------------------------------------------------
14:32:34.878 INFO  CalibrateDragstrModel - ------------------------------------------------------------
14:32:34.878 INFO  CalibrateDragstrModel - HTSJDK Version: 2.24.0
14:32:34.878 INFO  CalibrateDragstrModel - Picard Version: 2.25.0
14:32:34.878 INFO  CalibrateDragstrModel - Built for Spark Version: 2.4.5
14:32:34.878 INFO  CalibrateDragstrModel - HTSJDK Defaults.COMPRESSION_LEVEL : 2
14:32:34.878 INFO  CalibrateDragstrModel - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
14:32:34.878 INFO  CalibrateDragstrModel - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
14:32:34.878 INFO  CalibrateDragstrModel - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
14:32:34.878 INFO  CalibrateDragstrModel - Deflater: IntelDeflater
14:32:34.878 INFO  CalibrateDragstrModel - Inflater: IntelInflater
14:32:34.878 INFO  CalibrateDragstrModel - GCS max retries/reopens: 20
14:32:34.878 INFO  CalibrateDragstrModel - Requester pays: disabled
14:32:34.878 WARN  CalibrateDragstrModel -

   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

   Warning: CalibrateDragstrModel is a BETA tool and is not yet ready for use in production

   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


14:32:34.878 INFO  CalibrateDragstrModel - Initializing engine
14:32:35.872 INFO  CalibrateDragstrModel - Done initializing engine
14:32:35.873 INFO  ProgressMeter - Starting traversal
14:32:35.873 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Records Processed   Records/Minute
14:32:45.984 INFO  ProgressMeter -         chr1:5189104              0.2                 11000          65288.4
14:32:56.548 INFO  ProgressMeter -        chr1:13417603              0.3                 32000          92865.8
14:33:06.690 INFO  ProgressMeter -        chr1:21830601              0.5                 52000         101246.1
14:33:17.110 INFO  ProgressMeter -        chr1:30280825              0.7                 74000         107670.3
14:33:27.173 INFO  ProgressMeter -        chr1:39222124              0.9                 96000         112282.9
14:33:37.209 INFO  ProgressMeter -        chr1:48032218              1.0                117000         114451.5
14:33:47.610 INFO  ProgressMeter -        chr1:58221955              1.2                140000         117094.4
14:33:58.024 INFO  ProgressMeter -        chr1:68352622              1.4                163000         119049.1
14:34:08.265 INFO  ProgressMeter -        chr1:78966000              1.5                186000         120789.7
14:34:18.658 INFO  ProgressMeter -        chr1:89573604              1.7                209000         122002.2
14:34:28.995 INFO  ProgressMeter -        chr1:99868217              1.9                232000         123053.0
14:34:39.092 INFO  ProgressMeter -       chr1:110027593              2.1                255000         124169.2
14:34:49.313 INFO  ProgressMeter -       chr1:119754059              2.2                276000         124100.7
14:35:00.568 INFO  ProgressMeter -       chr1:124503573              2.4                283000         117350.3
14:35:12.149 INFO  ProgressMeter -       chr1:143220639              2.6                284000         109037.9
14:35:22.478 INFO  ProgressMeter -       chr1:148693116              2.8                297000         106959.6
14:35:32.538 INFO  ProgressMeter -       chr1:157918426              2.9                320000         108680.3
14:35:42.655 INFO  ProgressMeter -       chr1:167460404              3.1                341000         109539.5
14:35:52.948 INFO  ProgressMeter -       chr1:177364639              3.3                363000         110516.3
14:36:03.122 INFO  ProgressMeter -       chr1:187166684              3.5                385000         111460.7
14:36:13.203 INFO  ProgressMeter -       chr1:198094376              3.6                410000         113191.9
14:36:23.296 INFO  ProgressMeter -       chr1:207347266              3.8                432000         113972.6
14:36:33.321 INFO  ProgressMeter -       chr1:216824456              4.0                453000         114467.2
14:36:43.529 INFO  ProgressMeter -       chr1:225819400              4.1                473000         114594.9
14:36:53.704 INFO  ProgressMeter -       chr1:235080870              4.3                494000         114959.0
14:37:03.729 INFO  ProgressMeter -       chr1:244961323              4.5                518000         116032.5
14:37:09.228 INFO  CalibrateDragstrModel - Shutting down engine
[April 17, 2021 2:37:09 PM EDT] org.broadinstitute.hellbender.tools.dragstr.CalibrateDragstrModel done. Elapsed time: 4.58 minutes.
Runtime.totalMemory()=2153775104
java.lang.IllegalArgumentException: Start cannot exceed end.
        at htsjdk.samtools.util.IntervalTree.put(IntervalTree.java:74)
        at htsjdk.samtools.util.IntervalTree.merge(IntervalTree.java:137)
        at org.broadinstitute.hellbender.tools.dragstr.CalibrateDragstrModel$ShardReadBuffer.add(CalibrateDragstrModel.java:949)
        at org.broadinstitute.hellbender.tools.dragstr.CalibrateDragstrModel$1.tryAdvance(CalibrateDragstrModel.java:798)
        at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.broadinstitute.hellbender.tools.dragstr.CalibrateDragstrModel.collectCaseStatsSequencial(CalibrateDragstrModel.java:459)
        at org.broadinstitute.hellbender.tools.dragstr.CalibrateDragstrModel.traverse(CalibrateDragstrModel.java:159)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1058)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
Using GATK jar /share/pkg.7/gatk/4.2.0.0/install/bin/gatk-package-4.2.0.0-local.jar defined in environment variable GATK_LOCAL_JAR
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx16G -jar /share/pkg.7/gatk/4.2.0.0/install/bin/gatk-package-4.2.0.0-local.jar CalibrateDragstrModel --tmp-dir tmp -R /restricte
d/projectnb/casa/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa --str-table-path gvcf.STR/HGDP00001.alt_bwamem_GRCh38DH.20181023.Brahui/HGDP00001.alt_bwamem_GRCh38DH.20181023.Brahui.STR.table -O gvcf.STR/HGDP00001.alt_bwamem_GRCh38DH.20181023.Brahui/HGDP00001.alt_bwamem_GRCh38DH.20181023.Brahui
.Dragstr.model -I ../pop/Brahui/HGDP00001/alignment/HGDP00001.alt_bwamem_GRCh38DH.20181023.Brahui.cram
```

**Comment by jjfarrell** [comment]
@vruano There are two pipelines that produce crams that generate this error and one pipeline that does not.  The two pipelines that get this error both include indel realignment step while the other does not.  Could the indel realignment step be the source of the  problematic reads being encountered?

**Comment by droazen** [comment]
@vruano Was this fixed in your PR https://github.com/broadinstitute/gatk/pull/7212? Can this be closed?

**Comment by vruano** [comment]
If you want a proper test using the empirical data that cause the report, you cannot close otherwise the new code does exactly check for the offending condition and so it should be now fixed.
