### ISSUE TITLE
DenoiseReadCounts crashes in somatic CNV workflow

### ISSUE THREAD

**Issue by LN908** [broadinstitute/gatk#7258]
Hello, I made a PoN with my samples and created an hdf5 PoN. This was made using 

##Preprocess
``
gatk PreprocessIntervals -R ref/hs37d5.fa  --bin-length 10000 --padding 0 -O preprocessed_intervals.interval_list
``

##annotate
``
gatk AnnotateIntervals -R ref/hs37d5.fa -L preprocessed_intervals.interval_list --interval-merging-rule OVERLAPPING_ONLY -O annotated_intervals.tsv
``

##PoN
``
gatk --java-options "-Xmx6500m" CreateReadCountPanelOfNormals -I MD0078B1.counts.hdf5 -I MD1341B1.counts.hdf5 --minimum-interval-median-percentile 5.0 -O sandbox/cnvponC.pon.hdf5
``

When I use DenoiseReadCounts on the .counts.hdf5 for the tumour samples, I get an error.
This is the command I used: 
``
gatk DenoiseReadCounts -I BT1813.counts.hdf5 --count-panel-of-normals cnvponC2.pon.hdf5 --standardized-copy-ratios BT1813.standardizedCR.tsv --denoised-copy-ratios BT1813.denoisedCR.tsv
``

I know that some of these errors are expected but I don't see any other errors and I'm not sure why it stopped running. Any help would be appreciated thank you!

##Affected Version: gatk/4.0.1.2

##Bug Report

Using GATK jar /hpf/tools/centos6/gatk/4.0.1.2/gatk-package-4.0.1.2-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -jar /hpf/tools/centos6/gatk/4.0.1.2/gatk-package-4.0.1.2-local.jar DenoiseReadCounts -I BT1813.counts.hdf5 --count-panel-of-normals cnvponC2.pon.hdf5 --standardized-copy-ratios BT1813.standardizedCR.tsv --denoised-copy-ratios BT1813.denoisedCR.tsv
20:08:44.839 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/hpf/tools/centos6/gatk/4.0.1.2/gatk-package-4.0.1.2-local.jar!/com/intel/gkl/native/libgkl_compression.so
20:08:45.222 INFO  DenoiseReadCounts - ------------------------------------------------------------
20:08:45.222 INFO  DenoiseReadCounts - The Genome Analysis Toolkit (GATK) v4.0.1.2
20:08:45.222 INFO  DenoiseReadCounts - For support and documentation go to https://software.broadinstitute.org/gatk/
20:08:45.222 INFO  DenoiseReadCounts - Executing as lnegm@qlogin11.ccm.sickkids.ca on Linux v3.10.0-957.27.2.el7.x86_64 amd64
20:08:45.222 INFO  DenoiseReadCounts - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_91-b14
20:08:45.222 INFO  DenoiseReadCounts - Start Date/Time: May 18, 2021 8:08:44 PM EDT
20:08:45.222 INFO  DenoiseReadCounts - ------------------------------------------------------------
20:08:45.222 INFO  DenoiseReadCounts - ------------------------------------------------------------
20:08:45.222 INFO  DenoiseReadCounts - HTSJDK Version: 2.14.1
20:08:45.223 INFO  DenoiseReadCounts - Picard Version: 2.17.2
20:08:45.223 INFO  DenoiseReadCounts - HTSJDK Defaults.COMPRESSION_LEVEL : 1
20:08:45.223 INFO  DenoiseReadCounts - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
20:08:45.223 INFO  DenoiseReadCounts - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
20:08:45.223 INFO  DenoiseReadCounts - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
20:08:45.223 INFO  DenoiseReadCounts - Deflater: IntelDeflater
20:08:45.223 INFO  DenoiseReadCounts - Inflater: IntelInflater
20:08:45.223 INFO  DenoiseReadCounts - GCS max retries/reopens: 20
20:08:45.223 INFO  DenoiseReadCounts - Using google-cloud-java patch 6d11bef1c81f885c26b2b56c8616b7a705171e4f from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes
20:08:45.223 INFO  DenoiseReadCounts - Initializing engine
20:08:45.223 INFO  DenoiseReadCounts - Done initializing engine
log4j:WARN No appenders could be found for logger (org.broadinstitute.hdf5.HDF5Library).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
20:08:45.300 INFO  DenoiseReadCounts - Reading read-counts file (BT1813.counts.hdf5)...
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 0:
  #000: /mnt/scr1/abyrne/HDFJava-platypus-2.11/native/HDF5-prefix/src/HDF5/src/H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: /mnt/scr1/abyrne/HDFJava-platypus-2.11/native/HDF5-prefix/src/HDF5/src/H5Fint.c line 1085 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: /mnt/scr1/abyrne/HDFJava-platypus-2.11/native/HDF5-prefix/src/HDF5/src/H5Fsuper.c line 277 in H5F_super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file
20:08:49.800 INFO  DenoiseReadCounts - Shutting down engine
[May 18, 2021 8:08:49 PM EDT] org.broadinstitute.hellbender.tools.copynumber.DenoiseReadCounts done. Elapsed time: 0.08 minutes.
Runtime.totalMemory()=1789919232
org.broadinstitute.hdf5.HDF5LibException: exception when opening '/hpf/largeprojects/tabori/projects/bmmrd/CNA_project/gatk_cna/gatk/analysis/lgg/cnvponC2.pon.hdf5' with READ_ONLY mode: Not an HDF5 file
        at org.broadinstitute.hdf5.HDF5File.open(HDF5File.java:490)
        at org.broadinstitute.hdf5.HDF5File.<init>(HDF5File.java:82)
        at org.broadinstitute.hdf5.HDF5File.<init>(HDF5File.java:66)
        at org.broadinstitute.hellbender.tools.copynumber.DenoiseReadCounts.doWork(DenoiseReadCounts.java:188)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:136)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:153)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:195)
        at org.broadinstitute.hellbender.Main.main(Main.java:277)
Caused by: ncsa.hdf.hdf5lib.exceptions.HDF5FileInterfaceException: Not an HDF5 file
        at ncsa.hdf.hdf5lib.H5._H5Fopen(Native Method)
        at ncsa.hdf.hdf5lib.H5.H5Fopen(H5.java:2795)
        at org.broadinstitute.hdf5.HDF5File.open(HDF5File.java:487)
        ... 9 more

**Comment by mkyriak** [comment]
@LN908 Did you manage to figure out how to resole this error?

Thank you!
