### ISSUE TITLE
4.2.0.0 : HC  java.lang.IllegalStateException: Padded span must contain active span

### ISSUE THREAD

**Issue by lindenb** [broadinstitute/gatk#7289]
### Affected tool(s) or class(es)

HC  java.lang.IllegalStateException: Padded span must contain active span

### Affected version(s)
- [X] Latest public release version [version?]
- [ ] Latest master branch as of [date of test?]

### Description

```
Runtime.totalMemory()=2494038016
java.lang.IllegalStateException: Padded span must contain active span.
        at org.broadinstitute.hellbender.utils.Utils.validate(Utils.java:814)
        at org.broadinstitute.hellbender.engine.AssemblyRegion.<init>(AssemblyRegion.java:104)
        at org.broadinstitute.hellbender.engine.AssemblyRegion.<init>(AssemblyRegion.java:80)
        at org.broadinstitute.hellbender.utils.activityprofile.ActivityProfile.popNextReadyAssemblyRegion(ActivityProfile.java:332)
        at org.broadinstitute.hellbender.utils.activityprofile.ActivityProfile.popReadyAssemblyRegions(ActivityProfile.java:277)
        at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.loadNextAssemblyRegion(AssemblyRegionIterator.java:159)
        at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.next(AssemblyRegionIterator.java:112)
        at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.next(AssemblyRegionIterator.java:35)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:192)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:173)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1058)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

#### Steps to reproduce

see attachement.

```
gatk  HaplotypeCaller  -I jeter.bam -L jeter.bed --seconds-between-progress-updates 600 --minimum-mapping-quality 30  -R  hs37d5_all_chr.fasta -O jeter.vcf.gz
```

#### Expected behavior

no exception

#### Actual behavior

```
  java.lang.IllegalStateException: Padded span must contain active span
```

**Comment by jamesemery** [comment]
Hello @lindenb. 

I think I found what is going on here and its a bug on our part that we didn't provide a better error for this issue. In the bed file you uploaded this is the offending interval:
`GL000223.1  178912  180554`
Unfortunately this is the length of that interval in the hg37 decoy sequence dictionary is as follows:
`@SQ     SN:GL000223.1   LN:180455`
So it seems the issue here is that something got mangled and you are requesting a bad interval. It turns out we were using a codepath that failed to check that the interval was valid when specified as a bed file and active region padding code was using the correct interval based on the dictionary. This should be an easy fix on your end. I am making a branch that should trigger a better check and error message.

**Comment by lindenb** [comment]
@jamesemery  Oh I see ! My bad , sorry, I messed-up something when  the boundaries of the exons where extended by 100bp. Thank you for your time !
