### ISSUE TITLE
My output is empty 

### ISSUE THREAD

**Issue by WanessaMGoes** [broadinstitute/gatk#7332]
I performed a DepthOfCoverage analysis using the latest version of GATK (4.2.0) within the docker environment. I have provided only the required arguments and files, as shown in the line below:
gatk DepthOfCoverage -R assembly-Pacbio.genome.fasta -O Coverage_Pacbio -I Alignment_sorted_Pacbio.bam -L scaffolds-Pacbio-Chr-sizes.interval_list

The execution came to an end and apparently without a problem:

17:04:50.881 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gatk/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Jun 29, 2021 5:04:51 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
17:04:51.384 INFO  DepthOfCoverage - ------------------------------------------------------------
17:04:51.385 INFO  DepthOfCoverage - The Genome Analysis Toolkit (GATK) v4.2.0.0
17:04:51.385 INFO  DepthOfCoverage - For support and documentation go to https://software.broadinstitute.org/gatk/
17:04:51.385 INFO  DepthOfCoverage - Executing as root@d84100edcb97 on Linux v5.4.0-77-generic amd64
17:04:51.385 INFO  DepthOfCoverage - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_242-8u242-b08-0ubuntu3~18.04-b08
17:04:51.386 INFO  DepthOfCoverage - Start Date/Time: June 29, 2021 5:04:50 PM GMT
17:04:51.386 INFO  DepthOfCoverage - ------------------------------------------------------------
17:04:51.386 INFO  DepthOfCoverage - ------------------------------------------------------------
17:04:51.387 INFO  DepthOfCoverage - HTSJDK Version: 2.24.0
17:04:51.387 INFO  DepthOfCoverage - Picard Version: 2.25.0
17:04:51.387 INFO  DepthOfCoverage - Built for Spark Version: 2.4.5
17:04:51.387 INFO  DepthOfCoverage - HTSJDK Defaults.COMPRESSION_LEVEL : 2
17:04:51.387 INFO  DepthOfCoverage - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
17:04:51.387 INFO  DepthOfCoverage - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
17:04:51.387 INFO  DepthOfCoverage - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
17:04:51.387 INFO  DepthOfCoverage - Deflater: IntelDeflater
17:04:51.387 INFO  DepthOfCoverage - Inflater: IntelInflater
17:04:51.388 INFO  DepthOfCoverage - GCS max retries/reopens: 20
17:04:51.388 INFO  DepthOfCoverage - Requester pays: disabled
17:04:51.388 WARN  DepthOfCoverage - 

   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

   Warning: DepthOfCoverage is a BETA tool and is not yet ready for use in production

   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

17:04:51.388 INFO  DepthOfCoverage - Initializing engine
17:04:51.869 INFO  FeatureManager - Using codec IntervalListCodec to read file file:///gatk/my_data/Lama-PacbioV1-Chr-sizes.interval_list
17:04:51.898 INFO  IntervalArgumentCollection - Processing 31430935 bp from intervals
17:04:51.907 INFO  DepthOfCoverage - Done initializing engine
17:04:52.058 INFO  ProgressMeter - Starting traversal
17:04:52.058 INFO  ProgressMeter -        Current Locus  Elapsed Minutes        Loci Processed      Loci/Minute
17:06:19.219 INFO  FeatureManager - Using codec IntervalListCodec to read file file:///gatk/my_data/Lama-PacbioV1-Chr-sizes.interval_list
17:06:19.368 INFO  ProgressMeter - Lama-PacBio.Chr01:1001              1.5                  1000            687.2
17:06:29.368 INFO  ProgressMeter - Lama-PacBio.Chr08:1676524              1.6               4676000        2883156.9
17:06:39.369 INFO  ProgressMeter - Lama-PacBio.Chr17:545310              1.8               9925000        5549291.3
17:06:49.558 INFO  ProgressMeter - Lama-PacBio.Chr20:3003652              2.0              14424000        7365509.5
17:06:59.558 INFO  ProgressMeter - Lama-PacBio.Chr26:426929              2.1              19191000        9031058.8
17:07:09.558 INFO  ProgressMeter - Lama-PacBio.Chr30:1051399              2.3              24396000       10645527.3
17:07:19.559 INFO  ProgressMeter - Lama-PacBio.Chr34:95733              2.5              29543000       12017410.1
17:07:23.141 INFO  DepthOfCoverage - 1031666 read(s) filtered by: WellformedReadFilter 
0 read(s) filtered by: NotDuplicateReadFilter 
0 read(s) filtered by: NotSecondaryAlignmentReadFilter 
0 read(s) filtered by: MappedReadFilter 
1031666 total reads filtered
17:07:23.142 INFO  ProgressMeter - Lama-PacBio.Chr34:1982733              2.5              31430935       12482169.5
17:07:23.142 INFO  ProgressMeter - Traversal complete. Processed 31430935 total loci in 2.5 minutes.
17:07:23.142 INFO  DepthOfCoverage - Shutting down engine
[June 29, 2021 5:07:23 PM GMT] org.broadinstitute.hellbender.tools.walkers.coverage.DepthOfCoverage done. Elapsed time: 2.54 minutes.
Runtime.totalMemory()=244318208
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.broadinstitute.hellbender.tools.walkers.coverage.CoverageOutputWriter.printIntervalTable(CoverageOutputWriter.java:616)
		at org.broadinstitute.hellbender.tools.walkers.coverage.CoverageOutputWriter.writeOutputIntervalStatistics(CoverageOutputWriter.java:364)
	at org.broadinstitute.hellbender.tools.walkers.coverage.DepthOfCoverage.onTraversalSuccess(DepthOfCoverage.java:397)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1062)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)

But my output files are empty. what am I doing wrong?

**Comment by droazen** [comment]
@WanessaMGoes It looks like most/all of your reads are getting filtered out by GATK's `WellformedReadFilter`:

```
17:07:23.141 INFO DepthOfCoverage - 1031666 read(s) filtered by: WellformedReadFilter
```

Could you try running `ValidateSamFile` on your bam, and paste the result here?

**Comment by droazen** [comment]
@jonn-smith Could you comment on whether GATK's `WellformedReadFilter` would have issues with PacBio reads?
