### ISSUE TITLE
ReblockGVCF exception

### ISSUE THREAD

**Issue by jjfarrell** [broadinstitute/gatk#7334]
----

### Affected tool(s) or class(es)
ReblockGVCF 

### Affected version(s)
4.2.0.0

### Description 
When running ReblockGVCF the following exception occurs:

`java.lang.IllegalArgumentException: cannot add a genotype with GQ=-1 because it's not within bounds [0,20)
`

#### Steps to reproduce

Using a gVCF created with 4.2.0.0 HaplotypeCaller...

`gatk ReblockGVCF -R /restricted/projectnb/casa/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa -V gvcf.gather/GARDWGSN00001.autosome.g.vcf.gz -drop-low-quals -rgq-threshold 20 -do-qual-approx -O gvcf.reblock_gq20/GARDWGSN00001.autosome.g.vcf.gz`

#### Expected behavior
Should run to completion and create reblocked GVCF.

#### Actual behavior
```
Reblocking gvcf.gather/GARDWGSN00001.autosome.g.vcf.gz to gvcf.reblock_gq20/GARDWGSN00001.autosome.g.vcf.gz
Using GATK jar /share/pkg.7/gatk/4.2.0.0/install/bin/gatk-package-4.2.0.0-local.jar defined in environment variable GATK_LOCAL_JAR
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /share/pkg.7/gatk/4.2.0.0/install/bin/gatk-package-4.2.0.0-local.jar ReblockGVCF -R /restricted/projectnb/casa/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa -V gvcf.gather/GARDWGSN00001.autosome.g.vcf.gz -drop-low-quals -rgq-threshold 20 -do-qual-approx -O gvcf.reblock_gq20/GARDWGSN00001.autosome.g.vcf.gz
11:25:55.531 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/share/pkg.7/gatk/4.2.0.0/install/bin/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Jun 30, 2021 11:25:55 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
11:25:55.708 INFO  ReblockGVCF - ------------------------------------------------------------
11:25:55.709 INFO  ReblockGVCF - The Genome Analysis Toolkit (GATK) v4.2.0.0
11:25:55.709 INFO  ReblockGVCF - For support and documentation go to https://software.broadinstitute.org/gatk/
11:25:55.709 INFO  ReblockGVCF - Executing as farrell@scc-hadoop.bu.edu on Linux v3.10.0-1160.25.1.el7.x86_64 amd64
11:25:55.709 INFO  ReblockGVCF - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_121-b13
11:25:55.709 INFO  ReblockGVCF - Start Date/Time: June 30, 2021 11:25:55 AM EDT
11:25:55.710 INFO  ReblockGVCF - ------------------------------------------------------------
11:25:55.710 INFO  ReblockGVCF - ------------------------------------------------------------
11:25:55.710 INFO  ReblockGVCF - HTSJDK Version: 2.24.0
11:25:55.710 INFO  ReblockGVCF - Picard Version: 2.25.0
11:25:55.710 INFO  ReblockGVCF - Built for Spark Version: 2.4.5
11:25:55.710 INFO  ReblockGVCF - HTSJDK Defaults.COMPRESSION_LEVEL : 2
11:25:55.710 INFO  ReblockGVCF - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
11:25:55.711 INFO  ReblockGVCF - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
11:25:55.711 INFO  ReblockGVCF - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
11:25:55.711 INFO  ReblockGVCF - Deflater: IntelDeflater
11:25:55.711 INFO  ReblockGVCF - Inflater: IntelInflater
11:25:55.711 INFO  ReblockGVCF - GCS max retries/reopens: 20
11:25:55.711 INFO  ReblockGVCF - Requester pays: disabled
11:25:55.711 WARN  ReblockGVCF - 

   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

   Warning: ReblockGVCF is a BETA tool and is not yet ready for use in production

   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


11:25:55.711 INFO  ReblockGVCF - Initializing engine
11:25:56.290 INFO  FeatureManager - Using codec VCFCodec to read file file:///rprojectnb2/kageproj/gatk/gvcf.gather/GARDWGSN00001.autosome.g.vcf.gz
11:25:56.569 INFO  ReblockGVCF - Done initializing engine
11:25:56.690 INFO  ProgressMeter - Starting traversal
11:25:56.690 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
11:26:06.694 INFO  ProgressMeter -         chr1:5066659              0.2                771000        4624612.6
11:26:16.711 INFO  ProgressMeter -        chr1:12628456              0.3               1886000        5652065.3
11:26:26.103 INFO  ReblockGVCF - Shutting down engine
[June 30, 2021 11:26:26 AM EDT] org.broadinstitute.hellbender.tools.walkers.variantutils.ReblockGVCF done. Elapsed time: 0.51 minutes.
Runtime.totalMemory()=3303538688
java.lang.IllegalArgumentException: cannot add a genotype with GQ=-1 because it's not within bounds [0,20)
	at org.broadinstitute.hellbender.utils.variant.writers.HomRefBlock.add(HomRefBlock.java:99)
	at org.broadinstitute.hellbender.utils.variant.writers.GVCFBlockCombiner.createNewBlock(GVCFBlockCombiner.java:168)
	at org.broadinstitute.hellbender.utils.variant.writers.GVCFBlockCombiner.addHomRefSite(GVCFBlockCombiner.java:137)
	at org.broadinstitute.hellbender.utils.variant.writers.GVCFBlockCombiner.submit(GVCFBlockCombiner.java:200)
	at org.broadinstitute.hellbender.utils.variant.writers.GVCFWriter.add(GVCFWriter.java:91)
	at org.broadinstitute.hellbender.tools.walkers.variantutils.ReblockGVCF.apply(ReblockGVCF.java:229)
	at org.broadinstitute.hellbender.engine.VariantWalker.lambda$traverse$0(VariantWalker.java:104)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.VariantWalker.traverse(VariantWalker.java:102)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1058)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

This exception appears related to this issue #7108.  ReblockGVCF will need to be able to deal with any negative GQ values introduced with the bug.

**Comment by droazen** [comment]
@ldgauthier Any insight into this error? Does this tool actually need to handle negative GQs?

**Comment by droazen** [comment]
We believe that in GATK 4.2.1 we've fixed the underlying issue where HaplotypeCaller could in rare cases emit negative GQs. Recommend updating to that version and re-testing.

**Comment by jjfarrell** [comment]
WIth the  4.2.2.0 ReblockGVCF it is running fine. This was without rerunning the HaplotypeCaller to create the gvcf just the reblock. 

```
Using GATK jar /share/pkg.7/gatk/4.2.2.0/install/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar defined in environment variable GATK_LOCAL_JAR
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /share/pkg.7/gatk/4.2.2.0/install/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar ReblockGVCF -R /restricted/projectnb/casa/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa -V gvcf.gather/GARDWGSN00001.autosome.g.vcf.gz -drop-low-quals -rgq-threshold 20 -do-qual-approx -O g1.test.reblock.g.vcf.gz
00:54:40.318 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/share/pkg.7/gatk/4.2.2.0/install/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Aug 25, 2021 12:54:40 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
00:54:40.501 INFO  ReblockGVCF - ------------------------------------------------------------
00:54:40.501 INFO  ReblockGVCF - The Genome Analysis Toolkit (GATK) v4.2.2.0
00:54:40.501 INFO  ReblockGVCF - For support and documentation go to https://software.broadinstitute.org/gatk/
00:54:40.501 INFO  ReblockGVCF - Executing as farrell@scc-hadoop.bu.edu on Linux v3.10.0-1160.36.2.el7.x86_64 amd64
00:54:40.502 INFO  ReblockGVCF - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_121-b13
00:54:40.502 INFO  ReblockGVCF - Start Date/Time: August 25, 2021 12:54:40 AM EDT
00:54:40.502 INFO  ReblockGVCF - ------------------------------------------------------------
00:54:40.502 INFO  ReblockGVCF - ------------------------------------------------------------
00:54:40.503 INFO  ReblockGVCF - HTSJDK Version: 2.24.1
00:54:40.503 INFO  ReblockGVCF - Picard Version: 2.25.4
00:54:40.503 INFO  ReblockGVCF - Built for Spark Version: 2.4.5
00:54:40.503 INFO  ReblockGVCF - HTSJDK Defaults.COMPRESSION_LEVEL : 2
00:54:40.503 INFO  ReblockGVCF - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
00:54:40.503 INFO  ReblockGVCF - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
00:54:40.503 INFO  ReblockGVCF - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
00:54:40.504 INFO  ReblockGVCF - Deflater: IntelDeflater
00:54:40.504 INFO  ReblockGVCF - Inflater: IntelInflater
00:54:40.504 INFO  ReblockGVCF - GCS max retries/reopens: 20
00:54:40.504 INFO  ReblockGVCF - Requester pays: disabled
00:54:40.504 INFO  ReblockGVCF - Initializing engine
00:54:41.208 INFO  FeatureManager - Using codec VCFCodec to read file file:///rprojectnb2/kageproj/gatk/gvcf.gather/GARDWGSN00001.autosome.g.vcf.gz
00:54:41.674 INFO  ReblockGVCF - Done initializing engine
00:54:41.966 INFO  ProgressMeter - Starting traversal
00:54:41.967 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
00:54:51.980 INFO  ProgressMeter -         chr1:3039527              0.2                463000        2774393.3
00:55:01.985 INFO  ProgressMeter -         chr1:6740228              0.3               1022000        3063243.1
00:55:11.985 INFO  ProgressMeter -        chr1:10231108              0.5               1536000        3070157.9
00:55:21.988 INFO  ProgressMeter -        chr1:13973284              0.7               2050000        3073386.5
00:55:31.991 INFO  ProgressMeter -        chr1:18048840              0.8               2602000        3120964.4
00:55:41.993 INFO  ProgressMeter -        chr1:22137599              1.0               3179000        3177676.0
00:55:51.995 INFO  ProgressMeter -        chr1:26410070              1.2               3797000        3253270.1
```
