### ISSUE TITLE
VariantRecalibrator exception: Gaussian mean vector does not have the same size as the list of annotations

### ISSUE THREAD

**Issue by jjfarrell** [broadinstitute/gatk#7380]
### Affected tool(s) or class(es)
VariantRecalibrator

### Affected version(s)
GATK 4.2.0.0 

### Description 

When running VariantRecalibrator on a joint-called gVCF with 2000 samples, the following  java.lang.IllegalStateException occurs: **Gaussian mean vector does not have the same size as the list of annotations**

```
17:56:38.072 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/share/pkg.7/gatk/4.2.0.0/install/bin/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Jul 28, 2021 5:56:38 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
17:56:38.485 INFO  VariantRecalibrator - ------------------------------------------------------------
17:56:38.487 INFO  VariantRecalibrator - The Genome Analysis Toolkit (GATK) v4.2.0.0
17:56:38.487 INFO  VariantRecalibrator - For support and documentation go to https://software.broadinstitute.org/gatk/
17:56:38.488 INFO  VariantRecalibrator - Executing as farrell@scc-hadoop.bu.edu on Linux v3.10.0-1160.25.1.el7.x86_64 amd64
17:56:38.488 INFO  VariantRecalibrator - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_121-b13
17:56:38.488 INFO  VariantRecalibrator - Start Date/Time: July 28, 2021 5:56:38 PM EDT
17:56:38.489 INFO  VariantRecalibrator - ------------------------------------------------------------
17:56:38.489 INFO  VariantRecalibrator - ------------------------------------------------------------
17:56:38.490 INFO  VariantRecalibrator - HTSJDK Version: 2.24.0
17:56:38.491 INFO  VariantRecalibrator - Picard Version: 2.25.0
17:56:38.491 INFO  VariantRecalibrator - Built for Spark Version: 2.4.5
17:56:38.491 INFO  VariantRecalibrator - HTSJDK Defaults.COMPRESSION_LEVEL : 2
17:56:38.491 INFO  VariantRecalibrator - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
17:56:38.491 INFO  VariantRecalibrator - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
17:56:38.492 INFO  VariantRecalibrator - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
17:56:38.492 INFO  VariantRecalibrator - Deflater: IntelDeflater
17:56:38.492 INFO  VariantRecalibrator - Inflater: IntelInflater
17:56:38.493 INFO  VariantRecalibrator - GCS max retries/reopens: 20
17:56:38.493 INFO  VariantRecalibrator - Requester pays: disabled
17:56:38.493 INFO  VariantRecalibrator - Initializing engine
17:56:39.282 INFO  FeatureManager - Using codec VCFCodec to read file file:///rprojectnb2/kageproj/gatk/bundle/hapmap_3.3.hg38.vcf.gz
17:56:39.525 INFO  FeatureManager - Using codec VCFCodec to read file file:///rprojectnb2/kageproj/gatk/bundle/1000G_omni2.5.hg38.vcf.gz
17:56:39.697 INFO  FeatureManager - Using codec VCFCodec to read file file:///rprojectnb2/kageproj/gatk/bundle/1000G_phase1.snps.high_confidence.hg38.vcf.gz
17:56:39.842 INFO  FeatureManager - Using codec VCFCodec to read file file:///rprojectnb2/kageproj/gatk/bundle/Homo_sapiens_assembly38.dbsnp138.vcf.gz
17:56:40.069 INFO  FeatureManager - Using codec VCFCodec to read file file:///rprojectnb2/kageproj/gatk/pVCF/chr1/chr1.raw.excessHet.sites.vcf.gz
17:56:40.425 INFO  VariantRecalibrator - Done initializing engine
17:56:40.429 WARN  VariantDataManager - Ignoring duplicate annotations for recalibration %s.
17:56:40.435 INFO  TrainingSet - Found hapmap track:    Known = false   Training = true         Truth = true    Prior = Q15.0
17:56:40.435 INFO  TrainingSet - Found omni track:      Known = false   Training = true         Truth = true    Prior = Q12.0
17:56:40.435 INFO  TrainingSet - Found 1000G track:     Known = false   Training = true         Truth = false   Prior = Q10.0
17:56:40.435 INFO  TrainingSet - Found dbsnp track:     Known = true    Training = false        Truth = false   Prior = Q7.0
17:56:40.493 WARN  GATKVariantContextUtils - Can't determine output variant file format from output file extension "recal". Defaulting to VCF.
17:56:40.564 INFO  ProgressMeter - Starting traversal
17:56:40.565 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
17:56:50.617 INFO  ProgressMeter -         chr1:5730512              0.2                135000         805890.0
17:57:00.619 INFO  ProgressMeter -        chr1:12628969              0.3                260000         777938.5
17:57:10.655 INFO  ProgressMeter -        chr1:19030187              0.5                383000         763708.9
17:57:20.735 INFO  ProgressMeter -        chr1:25887500              0.7                499000         745350.9
17:57:30.749 INFO  ProgressMeter -        chr1:31774030              0.8                597000         713787.5
17:57:40.910 INFO  ProgressMeter -        chr1:38622987              1.0                706000         701963.7
17:57:50.935 INFO  ProgressMeter -        chr1:47429934              1.2                846000         721330.1
17:58:00.976 INFO  ProgressMeter -        chr1:62443927              1.3               1082000         807362.3
17:58:10.983 INFO  ProgressMeter -        chr1:79526193              1.5               1343000         891204.1
17:58:20.988 INFO  ProgressMeter -        chr1:96712774              1.7               1612000         963126.0
17:58:31.010 INFO  ProgressMeter -       chr1:110646765              1.8               1836000         997428.6
17:58:41.021 INFO  ProgressMeter -       chr1:120823640              2.0               1996000         994230.2
17:58:51.025 INFO  ProgressMeter -       chr1:124965170              2.2               2451000        1127242.1
17:59:01.028 INFO  ProgressMeter -       chr1:155145889              2.3               2665000        1138378.1
17:59:11.035 INFO  ProgressMeter -       chr1:168906400              2.5               2886000        1150801.8
17:59:21.095 INFO  ProgressMeter -       chr1:181872914              2.7               3084000        1152681.7
17:59:31.126 INFO  ProgressMeter -       chr1:191815045              2.8               3244000        1141182.0
17:59:41.149 INFO  ProgressMeter -       chr1:207096513              3.0               3490000        1159577.6
17:59:51.185 INFO  ProgressMeter -       chr1:223751053              3.2               3752000        1180988.4
18:00:01.226 INFO  ProgressMeter -       chr1:234867695              3.3               3939000        1177807.3
18:00:11.325 INFO  ProgressMeter -       chr1:241265890              3.5               4051000        1153254.9
18:00:19.710 INFO  ProgressMeter -       chr1:248946151              3.7               4191033        1147468.5
18:00:19.710 INFO  ProgressMeter - Traversal complete. Processed 4191033 total variants in 3.7 minutes.
18:00:20.037 INFO  VariantDataManager - AS_QD:   mean = 2.28     standard deviation = 1.28
18:00:20.683 INFO  VariantDataManager - AS_ReadPosRankSum:       mean = 0.00     standard deviation = 0.72
18:00:21.439 INFO  VariantDataManager - AS_MQRankSum:    mean = -0.01    standard deviation = 0.28
18:00:22.020 INFO  VariantDataManager - AS_FS:   mean = 1.05     standard deviation = 2.85
18:00:22.582 INFO  VariantDataManager - AS_MQ:   mean = 59.91    standard deviation = 1.09
18:00:23.143 INFO  VariantDataManager - AS_SOR:          mean = 0.71     standard deviation = 0.21
18:00:26.222 INFO  VariantDataManager - Annotation order is: [AS_MQ, AS_QD, AS_SOR, AS_FS, AS_MQRankSum, AS_ReadPosRankSum]
18:00:26.386 INFO  VariantDataManager - Training with 753407 variants after standard deviation thresholding.
18:00:26.395 INFO  GaussianMixtureModel - Initializing model with 100 k-means iterations...
18:01:22.416 INFO  VariantRecalibratorEngine - Finished iteration 0.
18:01:47.017 INFO  VariantRecalibratorEngine - Finished iteration 5.    Current change in mixture coefficients = 0.37631
18:02:11.930 INFO  VariantRecalibratorEngine - Finished iteration 10.   Current change in mixture coefficients = 0.15152
18:02:32.290 INFO  VariantRecalibratorEngine - Finished iteration 15.   Current change in mixture coefficients = 0.13806
18:02:47.679 INFO  VariantRecalibratorEngine - Finished iteration 20.   Current change in mixture coefficients = 0.09381
18:03:04.296 INFO  VariantRecalibratorEngine - Finished iteration 25.   Current change in mixture coefficients = 0.03326
18:03:21.508 INFO  VariantRecalibratorEngine - Finished iteration 30.   Current change in mixture coefficients = 0.00632
18:03:38.996 INFO  VariantRecalibratorEngine - Finished iteration 35.   Current change in mixture coefficients = 0.00181
18:03:38.996 INFO  VariantRecalibratorEngine - Convergence after 35 iterations!
18:03:40.687 INFO  VariantRecalibratorEngine - Evaluating full set of 3826009 variants...
18:03:57.261 INFO  VariantDataManager - Selected worst 164578 scoring variants --> variants with LOD <= -5.0000.
18:03:57.263 INFO  GaussianMixtureModel - Initializing model with 100 k-means iterations...
18:04:05.276 INFO  VariantRecalibratorEngine - Finished iteration 0.
18:04:07.160 INFO  VariantRecalibratorEngine - Finished iteration 5.    Current change in mixture coefficients = 0.47495
18:04:09.021 INFO  VariantRecalibratorEngine - Finished iteration 10.   Current change in mixture coefficients = 0.07996
18:04:10.871 INFO  VariantRecalibratorEngine - Finished iteration 15.   Current change in mixture coefficients = 0.02188
18:04:12.690 INFO  VariantRecalibratorEngine - Finished iteration 20.   Current change in mixture coefficients = 0.00815
18:04:14.555 INFO  VariantRecalibratorEngine - Finished iteration 25.   Current change in mixture coefficients = 0.00334
18:04:15.663 INFO  VariantRecalibratorEngine - Convergence after 28 iterations!
18:04:15.938 INFO  VariantRecalibratorEngine - Evaluating full set of 3826009 variants...
18:04:20.008 INFO  VariantRecalibrator - Shutting down engine
[July 28, 2021 6:04:20 PM EDT] org.broadinstitute.hellbender.tools.walkers.vqsr.VariantRecalibrator done. Elapsed time: 7.70 minutes.
Runtime.totalMemory()=105907224576
java.lang.IllegalStateException: Gaussian mean vector does not have the same size as the list of annotations
        at org.broadinstitute.hellbender.tools.walkers.vqsr.VariantRecalibrator.makeMeansTable(VariantRecalibrator.java:986)
        at org.broadinstitute.hellbender.tools.walkers.vqsr.VariantRecalibrator.writeModelReport(VariantRecalibrator.java:887)
        at org.broadinstitute.hellbender.tools.walkers.vqsr.VariantRecalibrator.onTraversalSuccess(VariantRecalibrator.java:680)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1062)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
Using GATK jar /share/pkg.7/gatk/4.2.0.0/install/bin/gatk-package-4.2.0.0-local.jar defined in environment variable GATK_LOCAL_JAR
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms100g -jar /share/pkg.7/gatk/4.2.0.0/install/bin/gatk-package-4.2.0.0-local.jar VariantRecalibrator -V /rprojectnb2/kageproj/gatk/pVCF/chr1/chr1.raw.excessHet.sites.vcf.gz -O snps.recal --tranches-file snps.tranches --trust-all-polymorphic -tranche 100.0 -tranche 99.95 -tranche 99.9 -tranche 99.8 -tranche 99.6 -tranche 99.5 -tranche 99.4 -tranche 99.3 -tranche 99.0 -tranche 98.0 -tranche 97.0 -tranche 90.0 -an AS_QD -an AS_ReadPosRankSum -an AS_MQRankSum -an AS_FS -an AS_MQ -an AS_SOR -an AS_MQ --use-allele-specific-annotations -mode SNP --output-model snps.model --max-gaussians 6 -resource:hapmap,known=false,training=true,truth=true,prior=15 /rprojectnb2/kageproj/gatk/bundle/hapmap_3.3.hg38.vcf.gz -resource:omni,known=false,training=true,truth=true,prior=12 /rprojectnb2/kageproj/gatk/bundle/1000G_omni2.5.hg38.vcf.gz -resource:1000G,known=false,training=true,truth=false,prior=10 /rprojectnb2/kageproj/gatk/bundle/1000G_phase1.snps.high_confidence.hg38.vcf.gz -resource:dbsnp,known=true,training=false,truth=false,prior=7 /rprojectnb2/kageproj/gatk/bundle/Homo_sapiens_assembly38.dbsnp138.vcf.gz
```

#### Steps to reproduce
 gatk --java-options -Xms100g       VariantRecalibrator       -V /rprojectnb2/kageproj/gatk/pVCF/chr1/chr1.raw.excessHet.sites.vcf.gz       -O snps.recal       --tranches-file snps.tranches       --trust-all-polymorphic        -tranche 100.0 -tranche 99.95 -tranche 99.9 -tranche 99.8 -tranche 99.6 -tranche 99.5 -tranche 99.4 -tranche 99.3 -tranche 99.0 -tranche 98.0 -tranche 97.0 -tranche 90.0         -an AS_QD -an AS_ReadPosRankSum -an AS_MQRankSum -an  AS_FS -an AS_MQ -an  AS_SOR -an AS_MQ       --use-allele-specific-annotations       -mode SNP       --output-model snps.model        --max-gaussians 6       -resource:hapmap,known=false,training=true,truth=true,prior=15 /rprojectnb2/kageproj/gatk/bundle/hapmap_3.3.hg38.vcf.gz       -resource:omni,known=false,training=true,truth=true,prior=12 /rprojectnb2/kageproj/gatk/bundle/1000G_omni2.5.hg38.vcf.gz       -resource:1000G,known=false,training=true,truth=false,prior=10 /rprojectnb2/kageproj/gatk/bundle/1000G_phase1.snps.high_confidence.hg38.vcf.gz       -resource:dbsnp,known=true,training=false,truth=false,prior=7 /rprojectnb2/kageproj/gatk/bundle/Homo_sapiens_assembly38.dbsnp138.vcf.gz

The input VCF was generated with the dragen-gatk HaplotypeCaller  with Allele Specific annotations. 

#### Expected behavior
The program should complete and generate files for the ApplySNPRecalibration task. 

#### Actual behavior
The following exception occurs: java.lang.IllegalStateException: Gaussian mean vector does not have the same size as the list of annotations.

**Comment by droazen** [comment]
@ldgauthier Happen to recognize or have any insight into this error?

**Comment by jjfarrell** [comment]
In preparing the VCF that generated the error, I had applied a hard filter on the excessHets variants before running the VQSR.  If  the excessHets are not filtered out, the VQSR runs fine.  I traced the error to having AS_MQ in the model without the excessHet variants in the vcf.

It would be nice to have a better error message.
