### ISSUE TITLE
Request created from: No results of  CollectvariantCallingMetrics

### ISSUE THREAD

**Issue by GATKSupportTeam** [broadinstitute/gatk#7383]
This request was created from a contribution made by FranBC on July 23, 2021 18:59 UTC.
This user is receiveing a NullPointerException error when running CollectvariantCallingMetrics and has verified that the vcf headers match the reference. The user uploaded their file to the GATK FTP server as "CollectVariantCallingMetrics_dbsnp155_FranBC2.tar.gz"

Link: [https://gatk.broadinstitute.org/hc/en-us/community/posts/360074951711-No-results-of-CollectvariantCallingMetrics#community\_comment\_4404056347547](https://gatk.broadinstitute.org/hc/en-us/community/posts/360074951711-No-results-of-CollectvariantCallingMetrics#community_comment_4404056347547)

\--

Dear GATK Team,

I am having a similar issue to Yenan, when using CollectVariantCallingMetrics, was a cause/workaround ever found for this?

I have no problem when using this tool with the GRCh38 dbSNP (build 138) vcf file provided in the resource bundle, however whenever I try a different dbSNP build, it throws this error:

\[Fri Jul 23 13:25:03 CEST 2021\] picard.vcf.CollectVariantCallingMetrics done. Elapsed time: 70.55 minutes.

Runtime.totalMemory()=1623195648

To get help, see [http://broadinstitute.github.io/picard/index.html#GettingHelp](http://broadinstitute.github.io/picard/index.html#GettingHelp)

java.lang.NullPointerException: Cannot invoke "htsjdk.samtools.SAMSequenceRecord.getSequenceLength()" because the return value of "htsjdk.samtools.SAMSequenceDictionary.getSequence(String)" is null

at picard.util.DbSnpBitSetUtil.loadVcf(DbSnpBitSetUtil.java:163)

at picard.util.DbSnpBitSetUtil.createSnpAndIndelBitSets(DbSnpBitSetUtil.java:131)

at picard.vcf.CollectVariantCallingMetrics.doWork(CollectVariantCallingMetrics.java:101)

at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)

at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:37)

at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)

at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)

at org.broadinstitute.hellbender.Main.main(Main.java:289)

As a bit of a background, I am trying to use the latest dbSNP release (build 155, GRCh38, GCF\_000001405.39) and have tried using GATK version 4.1.9.0 and the latest 4.2.0.0, both having the same problem.

To prepare the dbSNP file for use with the best practices workflow, I renamed the NCBI chromosome accession numbers  to UCSC style names using bcftools annotate, updated the vcf headers using UpdateVcfSequenceDictionary, and indexed the file using IndexFeatureFile.

The dbSNP file worked well with both HaplotypeCaller and GenotypeGVCFs, with the rsids overlapping perfectly with those obtained when using the dbSNP resource bundle version.

Any help with this would be greatly appreciated!<br><br><i>(created from <a href='https://broadinstitute.zendesk.com/agent/tickets/171466'>Zendesk ticket #171466</a>)<br>gz#171466</i>

**Comment by gbrandt6** [comment]
I went through the bug report (CollectVariantCallingMetrics_dbsnp155_FranBC2.tar.gz) and found that there were some contigs in the dbsnp file that were not present in the hg38 reference dictionary. However, it was pretty tricky to problem solve without knowing which contig caused the issue. All I had to go off of was the progress meter with the last contig read. If there is a better error message this issue would be easy to diagnose and solve @lbergelson

**Comment by gbrandt6** [comment]
I deleted my previous comment because I did recreate their issue and I was not able to find a contig in the DBSNP VCF that was not present in the fasta sequence dictionary. Would you be able to add a better error message for this case @lbergelson so that we can troubleshoot and find the culprit?
