### ISSUE TITLE
ModuleNotFoundError: No module named 'gatktool'

### ISSUE THREAD

**Issue by mdayii** [broadinstitute/gatk#7397]
Dear all,

I installed the latest version of gatk as follows;

download the latest version of gatk (https://github.com/broadinstitute/gatk/releases)

followed this (https://gatk.broadinstitute.org/hc/en-us/articles/360035889851--How-to-Install-and-use-Conda-for-GATK4) (conda env create -n gatk4 -f gatkcondaenv.yml)

installation was completed as below;

Pip subprocess output:
Processing ./gatkPythonPackageArchive.zip
Building wheels for collected packages: gatkpythonpackages
  Building wheel for gatkpythonpackages (setup.py): started
  Building wheel for gatkpythonpackages (setup.py): finished with status 'done'
  Created wheel for gatkpythonpackages: filename=gatkpythonpackages-0.1-py3-none-any.whl size=117482 sha256=5e0f0b2eb6027268eb5814acd8c8b57d265b7aeb371702c736dd4723aa1beee4
  Stored in directory: /tmp/pip-ephem-wheel-cache-gyc4oo9g/wheels/86/46/5d/d5d2d327a9cdc718f906fa1d0cd6e18392bd4eea267f327437
Successfully built gatkpythonpackages
Installing collected packages: gatkpythonpackages
Successfully installed gatkpythonpackages-0.1

done

when I started to run this command;

gatk  CNNScoreVariants -V 21002.HaplotypeCaller.output.g.vcf.gz  -R hg19.fa -O annotated.vcf
it gives an error as below;

java.lang.RuntimeException: A required Python package ("gatktool") could not be imported into the Python environment. This tool requires that the GATK Python environment is properly established and activated. Please refer to GATK README.md file for instructions on setting up the GATK Python environment.
        at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.checkPythonEnvironmentForPackage(PythonScriptExecutor.java:205)
        at org.broadinstitute.hellbender.utils.python.StreamingPythonScriptExecutor.start(StreamingPythonScriptExecutor.java:121)
        at org.broadinstitute.hellbender.tools.walkers.vqsr.CNNScoreVariants.onTraversalStart(CNNScoreVariants.java:302)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1046)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
        at org.broadinstitute.hellbender.Main.main(Main.java:292)
Caused by: org.broadinstitute.hellbender.utils.python.PythonScriptExecutorException: 
python exited with 1
Command Line: python -c import gatktool

Stdout: 
Stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'gatktool'

        at org.broadinstitute.hellbender.utils.python.PythonExecutorBase.getScriptException(PythonExecutorBase.java:75)
        at org.broadinstitute.hellbender.utils.runtime.ScriptExecutor.executeCuratedArgs(ScriptExecutor.java:126)
        at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeArgs(PythonScriptExecutor.java:170)
        at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeCommand(PythonScriptExecutor.java:79)
        at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.checkPythonEnvironmentForPackage(PythonScriptExecutor.java:198)
when I checked gatktool python package, it is installed in the python packages by conda.

after activate gatk4 , I checked with pip install gatktool, and it says the package already installed.

Anyone experienced this error?

**Comment by cmnbroad** [comment]
@mdayii The most likely reason for this is that you're not running gatk from within the shell that has the conda env activated. One test you might try is to start `python` from the same shell where you activated the conda env, and see if the command `import gatktool` succeeds.

**Comment by mdayii** [comment]
Thank you for fast reply.

@python from the same shell where you activated the conda env, and see if the command import gatktool succeeds.

Yes, this works well.

but when I run the command below and submit the job to HPC ;

conda activate gatk4 ; gatk CNNScoreVariants -V 21002.HaplotypeCaller.output.g.vcf.gz  -R hg19.fa -O annotated.vcf

same error happened.



another point is that when I run the command (gatk CNNScoreVariants -V 21002.HaplotypeCaller.output.g.vcf.gz -R hg19.fa -O annotated.vcf) without HPC by setting memory as qlogin -l s_vmem=16G -l mem_req=16G


it produces this:

Runtime.totalMemory()=2132803584
org.broadinstitute.hellbender.exceptions.GATKException: Exception waiting for ack from Python: org.broadinstitute.hellbender.exceptions.GATKException: Expected message of length 3 but only found 0 bytes
	at org.broadinstitute.hellbender.utils.runtime.StreamingProcessController.waitForAck(StreamingProcessController.java:233)
	at org.broadinstitute.hellbender.utils.python.StreamingPythonScriptExecutor.waitForAck(StreamingPythonScriptExecutor.java:216)
	at org.broadinstitute.hellbender.utils.python.StreamingPythonScriptExecutor.waitForPreviousBatchCompletion(StreamingPythonScriptExecutor.java:293)
	at org.broadinstitute.hellbender.tools.walkers.vqsr.CNNScoreVariants.sendBatchIfReady(CNNScoreVariants.java:416)
	at org.broadinstitute.hellbender.tools.walkers.vqsr.CNNScoreVariants.firstPassApply(CNNScoreVariants.java:336)
	at org.broadinstitute.hellbender.engine.TwoPassVariantWalker.nthPassApply(TwoPassVariantWalker.java:17)
	at org.broadinstitute.hellbender.engine.MultiplePassVariantWalker.lambda$traverse$0(MultiplePassVariantWalker.java:40)
	at org.broadinstitute.hellbender.engine.MultiplePassVariantWalker.lambda$traverseVariants$1(MultiplePassVariantWalker.java:77)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.MultiplePassVariantWalker.traverseVariants(MultiplePassVariantWalker.java:75)
	at org.broadinstitute.hellbender.engine.MultiplePassVariantWalker.traverse(MultiplePassVariantWalker.java:40)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
	at org.broadinstitute.hellbender.Main.main(Main.java:292)
Caused by: java.util.concurrent.ExecutionException: org.broadinstitute.hellbender.exceptions.GATKException: Expected message of length 3 but only found 0 bytes
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.broadinstitute.hellbender.utils.runtime.StreamingProcessController.waitForAck(StreamingProcessController.java:228)
	... 26 more
Caused by: org.broadinstitute.hellbender.exceptions.GATKException: Expected message of length 3 but only found 0 bytes
	at org.broadinstitute.hellbender.utils.runtime.StreamingProcessController.getBytesFromStream(StreamingProcessController.java:261)
	at org.broadinstitute.hellbender.utils.runtime.StreamingProcessController.lambda$waitForAck$0(StreamingProcessController.java:208)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


but if I change memory as below: it works. 
qlogin -l s_vmem=20G -l mem_req=20G

**Comment by cmnbroad** [comment]
@mdayii I'd suggest that you search the gatk [forum](https://gatk.broadinstitute.org/hc/en-us/community/topics) for similar topics, or post this issue there, to see if anyone there can help with the config.

**Comment by mdayii** [comment]
@cmnbroad 
Sorry It is not possible to sign up to the forum that you mentioned. The sign up bottom is not active.

**Comment by droazen** [comment]
@gbrandt6 Could you please comment on the issues @mdayii is having with signing up for the GATK forum? Thanks

**Comment by gbrandt6** [comment]
@mdayii @droazen It looks like there is something wrong with our site, I am looking into it now. Thanks for the heads up!

**Comment by gbrandt6** [comment]
@mdayii could you please share a description and screenshot of the issue you are seeing? Our site is working fine. One thing you should check is that cookies are enabled with your browser.

**Comment by mdayii** [comment]
<img width="905" alt="Screen Shot 2021-08-17 at 14 05 57" src="https://user-images.githubusercontent.com/75674296/129715691-2e21ec32-6d0b-48f9-93b5-df98b9b8d3d2.png">

gbrandt6; I added screenshot. Thank you.

**Comment by gbrandt6** [comment]
@mdayii I see, yes. You will need to allow cookies to be able to sign up.

**Comment by mdayii** [comment]
Thank you. It is now okay.

**Comment by gbrandt6** [comment]
Great!
