### ISSUE TITLE
IllegalArgumentException: Illegal base [ ] seen in the allele when running FastaAlternateReferenceMaker

### ISSUE THREAD

**Issue by YanisChrys** [broadinstitute/gatk#7433]
I use these steps to produce variant calls for haploid data:
HaplotypeCaller in GVCF mode -> CombineGVCFs -> GenotypeGVCFs
and I then create a snpmask file by adding to it any sites I don't want and keep all called SNPs and INDELs inside per sample vcf files. I then try to create a consensus sequence by running in GATK v 4.2.1.0:

```
gatk FastaAlternateReferenceMaker \
  -R myref.fasta \
  -V persamplevariants.vcf \
  -O new.fasta \
  --line-width 80 \
  --snp-mask mask.vcf \
  --snp-mask-priority 
```

But I get this error:

`
java.lang.IllegalArgumentException: Illegal base [ ] seen in the allele
	at htsjdk.variant.variantcontext.Allele.create(Allele.java:251)
	at htsjdk.variant.variantcontext.Allele.create(Allele.java:402)
	at org.broadinstitute.hellbender.tools.walkers.fasta.FastaAlternateReferenceMaker.lambda$handlePosition$0(FastaAlternateReferenceMaker.java:176)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.broadinstitute.hellbender.tools.walkers.fasta.FastaAlternateReferenceMaker.handlePosition(FastaAlternateReferenceMaker.java:176)
	at org.broadinstitute.hellbender.tools.walkers.fasta.FastaAlternateReferenceMaker.apply(FastaAlternateReferenceMaker.java:141)
	at org.broadinstitute.hellbender.engine.ReferenceWalker.traverse(ReferenceWalker.java:55)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1085)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
`

By narrowing down on where this happens I find it happens here:

```
chrom	16798	.	TAGC	*	41.94	.	AC=1;AF=1.00;AN=1;BaseQRankSum=-5.240e-01;DP=29;FS=3.663;MQ=36.43;MQRankSum=-1.282e+00;QD=1.40;ReadPosRankSum=0.00;SOR=0.446	GT:AD:DP:GQ:PL	1:0,6:29:99:810,0

chrom	16799	.	A	*	0	LowQual	AC=1;AF=1.00;AN=1;DP=29;FS=3.663;QD=0.00;SOR=0.446	GT:AD:DP:GQ:PL	1:0,6:29:99:810,0

chrom	**16800**	.	G	*	3727.44	.	AC=1;AF=1.00;AN=1;BaseQRankSum=0.00;DP=29;FS=2.256;MQ=42.17;MQRankSum=1.88;QD=21.42;ReadPosRankSum=-6.100e-02;SOR=0.920	GT:AD:DP:GQ:PL	1:0,6:29:99:810,0

chrom	16801	.	C	*	0	LowQual	AC=1;AF=1.00;AN=1;DP=29;FS=3.663;QD=0.00;SOR=0.446	GT:AD:DP:GQ:PL	1:0,6:29:99:810,0

chrom	16802	.	A	*	0	LowQual	AC=1;AF=1.00;AN=1;DP=29;FS=4.509;QD=0.00;SOR=0.378	GT:AD:DP:GQ:PL	1:0,6:29:99:810,0

chrom	16804	.	CAGA	.	379.83	.	AN=1;BaseQRankSum=0.00;DP=48;FS=0.000;MQ=42.50;MQRankSum=-6.740e-01;QD=29.22;ReadPosRankSum=0.524;SOR=0.836	GT:AD:DP:PL	0:48:48:0
```

The problem is at position 16800. I have gotten this error again in similar positions where a deletion has happened and the bases after it are called in contradictory ways or with low quality and I was wondering how I could fix it for all my samples.
Could BaseQRankSum have anything to do with it?

**Comment by YanisChrys** [comment]
This is happening again in a different sample in a much less obvious position (20140) after much more stringent filtering where the position no longer has called neighbors:

```
NC_017236.1	20122	.	G	GCGCC	1582.09	PASS	AC=1;AF=1.00;AN=1;BaseQRankSum=-2.530e-01;DP=10;FS=4.928;MQ=38.94;MQRankSum=1.49;QD=24.72;ReadPosRankSum=1.53;SOR=1.195	GT:AD:DP:GQ:PL	1:4,6:10:90:90,0
NC_017236.1	20140	.	C	*	4007.40	PASS	AC=1;AF=1.00;AN=1;BaseQRankSum=0.554;DP=7;FS=4.361;MQ=51.52;MQRankSum=0.471;QD=10.36;ReadPosRankSum=0.925;SOR=0.717	GT:AD:DP:GQ:PL	1:0,4:7:99:180,0
NC_017236.1	20162	.	TTG	T	2347.59	PASS	AC=1;AF=1.00;AN=1;DP=11;FS=0.000;MQ=35.03;QD=27.04;SOR=0.970	GT:AD:DP:GQ:PL	1:0,11:11:99:495,0

```

This time the Exception looks like this:

```
java.lang.IllegalArgumentException: Illegal base [ ] seen in the allele
	at htsjdk.variant.variantcontext.Allele.create(Allele.java:251)
	at htsjdk.variant.variantcontext.Allele.create(Allele.java:402)
	at org.broadinstitute.hellbender.tools.walkers.fasta.FastaAlternateReferenceMaker.lambda$handlePosition$0(FastaAlternateReferenceMaker.java:176)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.broadinstitute.hellbender.tools.walkers.fasta.FastaAlternateReferenceMaker.handlePosition(FastaAlternateReferenceMaker.java:176)
	at org.broadinstitute.hellbender.tools.walkers.fasta.FastaAlternateReferenceMaker.apply(FastaAlternateReferenceMaker.java:141)
	at org.broadinstitute.hellbender.engine.ReferenceWalker.traverse(ReferenceWalker.java:55)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1085)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
```
 
 I suspect that something goes very wrong when I do the (joint) variant calling because this is happening on published samples too that I'm also trying to call again. Is there an option on HaplotypeCaller or GenotypeGVCFs that I can use that might fix this?

**Comment by GATKSupportTeam** [comment]
<i>(related to <a href='https://broadinstitute.zendesk.com/agent/tickets/178907'>Zendesk ticket #178907</a>)</i>

**Comment by YanisChrys** [comment]
An update/unwanted solve:
Caveat: I'm sorry I didn't provide more information about this issue beforehand, in fact, I create the vcf file by calling:

```
gatk SelectVariants \
  -R REF.fasta \
  -V allsites.allsamples.vcf \
  -O sample.vcf \
  --remove-unused-alternates \
  --exclude-filtered \
  --sample-name "sample" \
  -select 'vc.getGenotype("sample").hasAD() && vc.isVariant() && (vc.getGenotype("sample").getAD().1 > 2.0)'
```

(some of the select checks might be redundant but I wanted to be on the safe side)
**The error doesn't happen when I remove "--remove-unused-alternates"**
This is very unfortunate as I need that to force the sites to be biallelic and to filter my variants and I will have to find a workaround.

Does it happen because it's looking for an alternate that's no longer there? Could it be a dictionary mismatch/confusion?

**Comment by lbergelson** [comment]
@YanisChrys Hey, I haven't gotten a chance to look into this properly yet.  The bit about `--remove-unused-alleles` sounds important. It seems likely we're breaking some (bad) assumptions the tool makes when we remove alleles midway through and it's falling over because of that.

**Comment by YanisChrys** [comment]
Hi, after a lot of trial and error that's what I figured as well. It would be interesting to know what assumptions are broken and if there is a way to avoid it or even to make the --remove-unused-alternates option compatible with FastaAlternateReferenceMaker.
What I still don't know is if the tool grabs the correct alternate when it sees more than 1 at a site. If yes, the above option is almost unnecessary, but it would be nice if it worked.
