### ISSUE TITLE
GenotypeGVCFs null exception 

### ISSUE THREAD

**Issue by jjfarrell** [broadinstitute/gatk#7437]
### Affected tool(s) or class(es)
GATK GenotypeGVCFs

### Affected version(s)
GATK 4.2.2.0

### Description 

When running GenotypeGVCFs,
1. multiple warnings of **No valid combination operation found for INFO field** 
2. AS_VarDP warnings:
      ```
      WARN  ReferenceConfidenceVariantContextMerger - Detected invalid annotations: When trying to merge variant contexts at location chr16:10185 the annotation AS_VarDP=59|115|0 was not a numerical value and was ignored
            WARN  ReferenceConfidenceVariantContextMerger - Reducible annotation 'AS_VarDP' detected, add -G StandardAnnotation -G AS_StandardAnnotation to the command to annotate in the final VC with this annotation.
```

3. java.lang.NullPointerException occurs. 
4. No variants output into VCF

This is the log:
 java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx60g -jar /share/pkg.7/gatk/4.2.0.0/install/bin/gatk-package-4.2.0.0-local.jar GenotypeGVCFs -R /restricted/projectnb/casa/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa -G StandardAnnotation -G AS_StandardAnnotation -V gendb:///restricted/projectnb/kageproj/gatk/genomicsdb/genomicsDB.chr16 -L chr16:1-105581 --use-new-qual-calculator --only-output-calls-starting-in-intervals TRUE --genomicsdb-shared-posixfs-optimizations TRUE --tmp-dir tmp -O chr16-1-105581.vcf.gz
00:05:54.259 WARN  GATKAnnotationPluginDescriptor - Redundant enabled annotation group (StandardAnnotation) is enabled for this tool by default
00:05:54.319 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/share/pkg.7/gatk/4.2.0.0/install/bin/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Aug 25, 2021 12:05:54 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
00:05:54.582 INFO  GenotypeGVCFs - ------------------------------------------------------------
00:05:54.583 INFO  GenotypeGVCFs - The Genome Analysis Toolkit (GATK) v4.2.0.0
00:05:54.583 INFO  GenotypeGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
00:05:54.583 INFO  GenotypeGVCFs - Executing as farrell@scc-hadoop.bu.edu on Linux v3.10.0-1160.36.2.el7.x86_64 amd64
00:05:54.583 INFO  GenotypeGVCFs - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_121-b13
00:05:54.584 INFO  GenotypeGVCFs - Start Date/Time: August 25, 2021 12:05:54 AM EDT
00:05:54.584 INFO  GenotypeGVCFs - ------------------------------------------------------------
00:05:54.584 INFO  GenotypeGVCFs - ------------------------------------------------------------
00:05:54.584 INFO  GenotypeGVCFs - HTSJDK Version: 2.24.0
00:05:54.585 INFO  GenotypeGVCFs - Picard Version: 2.25.0
00:05:54.585 INFO  GenotypeGVCFs - Built for Spark Version: 2.4.5
00:05:54.585 INFO  GenotypeGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2
00:05:54.585 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
00:05:54.585 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
00:05:54.585 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
00:05:54.585 INFO  GenotypeGVCFs - Deflater: IntelDeflater
00:05:54.585 INFO  GenotypeGVCFs - Inflater: IntelInflater
00:05:54.585 INFO  GenotypeGVCFs - GCS max retries/reopens: 20
00:05:54.585 INFO  GenotypeGVCFs - Requester pays: disabled
00:05:54.585 INFO  GenotypeGVCFs - Initializing engine
00:05:55.815 INFO  GenomicsDBLibLoader - GenomicsDB native library version : 1.3.2-e18fa63
00:05:56.228 info  NativeGenomicsDB - pid=40375 tid=40376 No valid combination operation found for INFO field AC  - the field will NOT be part of INFO fields in the generated VCF records
00:05:56.228 info  NativeGenomicsDB - pid=40375 tid=40376 No valid combination operation found for INFO field AF  - the field will NOT be part of INFO fields in the generated VCF records
00:05:56.228 info  NativeGenomicsDB - pid=40375 tid=40376 No valid combination operation found for INFO field AN  - the field will NOT be part of INFO fields in the generated VCF records
00:05:56.228 info  NativeGenomicsDB - pid=40375 tid=40376 No valid combination operation found for INFO field AS_BaseQRankSum  - the field will NOT be part of INFO fields in the generated VCF records
00:05:56.228 info  NativeGenomicsDB - pid=40375 tid=40376 No valid combination operation found for INFO field AS_FS  - the field will NOT be part of INFO fields in the generated VCF records
00:05:56.228 info  NativeGenomicsDB - pid=40375 tid=40376 No valid combination operation found for INFO field AS_InbreedingCoeff  - the field will NOT be part of INFO fields in the generated VCF records
00:05:56.228 info  NativeGenomicsDB - pid=40375 tid=40376 No valid combination operation found for INFO field AS_MQ  - the field will NOT be part of INFO fields in the generated VCF records
00:05:56.228 info  NativeGenomicsDB - pid=40375 tid=40376 No valid combination operation found for INFO field AS_MQRankSum  - the field will NOT be part of INFO fields in the generated VCF records
00:05:56.228 info  NativeGenomicsDB - pid=40375 tid=40376 No valid combination operation found for INFO field AS_QD  - the field will NOT be part of INFO fields in the generated VCF records
00:05:56.229 info  NativeGenomicsDB - pid=40375 tid=40376 No valid combination operation found for INFO field AS_ReadPosRankSum  - the field will NOT be part of INFO fields in the generated VCF records
00:05:56.230 info  NativeGenomicsDB - pid=40375 tid=40376 No valid combination operation found for INFO field AS_SOR  - the field will NOT be part of INFO fields in the generated VCF records
00:05:56.230 info  NativeGenomicsDB - pid=40375 tid=40376 No valid combination operation found for INFO field DRAGstrInfo  - the field will NOT be part of INFO fields in the generated VCF records
00:05:56.230 info  NativeGenomicsDB - pid=40375 tid=40376 No valid combination operation found for INFO field DRAGstrParams  - the field will NOT be part of INFO fields in the generated VCF records
00:05:56.230 info  NativeGenomicsDB - pid=40375 tid=40376 No valid combination operation found for INFO field FS  - the field will NOT be part of INFO fields in the generated VCF records
00:05:56.230 info  NativeGenomicsDB - pid=40375 tid=40376 No valid combination operation found for INFO field InbreedingCoeff  - the field will NOT be part of INFO fields in the generated VCF records
00:05:56.230 info  NativeGenomicsDB - pid=40375 tid=40376 No valid combination operation found for INFO field QD  - the field will NOT be part of INFO fields in the generated VCF records
00:05:56.230 info  NativeGenomicsDB - pid=40375 tid=40376 No valid combination operation found for INFO field SOR  - the field will NOT be part of INFO fields in the generated VCF records
00:05:56.776 INFO  IntervalArgumentCollection - Processing 105581 bp from intervals
00:05:56.847 INFO  GenotypeGVCFs - Done initializing engine
00:05:57.036 INFO  ProgressMeter - Starting traversal
00:05:57.036 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
00:07:26.967 WARN  ReferenceConfidenceVariantContextMerger - Detected invalid annotations: When trying to merge variant contexts at location chr16:10185 the annotation AS_VarDP=59|115|0 was not a numerical value and was ignored
00:07:26.967 WARN  ReferenceConfidenceVariantContextMerger - Reducible annotation 'AS_VarDP' detected, add -G StandardAnnotation -G AS_StandardAnnotation to the command to annotate in the final VC with this annotation.
00:07:26.991 INFO  GenotypeGVCFs - Shutting down engine
GENOMICSDB_TIMER,GenomicsDB iterator next() timer,Wall-clock time(s),0.02938786500000001,Cpu time(s),0.029037034000000003
[August 25, 2021 12:07:27 AM EDT] org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 1.55 minutes.
Runtime.totalMemory()=1807745024
java.lang.NullPointerException
        at java.util.HashMap.putMapEntries(HashMap.java:500)
        at java.util.HashMap.putAll(HashMap.java:784)
        at org.broadinstitute.hellbender.tools.walkers.annotator.VariantAnnotatorEngine.combineAnnotations(VariantAnnotatorEngine.java:211)
        at org.broadinstitute.hellbender.tools.walkers.ReferenceConfidenceVariantContextMerger.mergeAttributes(ReferenceConfidenceVariantContextMerger.java:318)
        at org.broadinstitute.hellbender.tools.walkers.ReferenceConfidenceVariantContextMerger.merge(ReferenceConfidenceVariantContextMerger.java:142)
        at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFsEngine.callRegion(GenotypeGVCFsEngine.java:130)
        at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.apply(GenotypeGVCFs.java:281)
        at org.broadinstitute.hellbender.engine.VariantLocusWalker.lambda$traverse$0(VariantLocusWalker.java:135)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
        at org.broadinstitute.hellbender.engine.VariantLocusWalker.traverse(VariantLocusWalker.java:132)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1058)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
```


#### Steps to reproduce

1. reblock gvcf for 10 samples with 4.2.2.0 from chr16
2. imported the 10 gvcfs from chr16 into genomicsdb 
3. genotypeGVCFs with following 
gatk --java-options "-Xmx60g"  GenotypeGVCFs \
   -R /restricted/projectnb/casa/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa \
   -G StandardAnnotation -G AS_StandardAnnotation\
   -V $DB \
   -L $INTERVAL\
   --use-new-qual-calculator\
   --only-output-calls-starting-in-intervals TRUE\
   --genomicsdb-shared-posixfs-optimizations TRUE\
   --tmp-dir tmp\
   -O $VCF


#### Expected behavior
Run GenotypeGVCFs without exceptions and no warnings about INFO fields.

#### Actual behavior
Null exception with No Variants output to VCF just header.

**Comment by jjfarrell** [comment]
I also tried the following approach which did not generate an error:

1. imported the 10 not-reblocked gvcfs from chr16 into genomicsdb 
2. GenotypeGVCFs with the same command line as number 3 above. 

So the error appears to be related to the reblocking of the gvcfs.

```
gendb:///restricted/projectnb/kageproj/gatk/genomicsdb/genomicsDB.chr16
Using GATK jar /share/pkg.7/gatk/4.2.0.0/install/bin/gatk-package-4.2.0.0-local.jar defined in environment variable GATK_LOCAL_JAR
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx60g -jar /share/pkg.7/gatk/4.2.0.0/install/bin/gatk-package-4.2.0.0-local.jar GenotypeGVCFs -R /restricted/projectnb/casa/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa -G StandardAnnotation -G AS_StandardAnnotation -V gendb:///restricted/projectnb/kageproj/gatk/genomicsdb/genomicsDB.chr16 -L chr16:105582-211160 --use-new-qual-calculator --only-output-calls-starting-in-intervals TRUE --genomicsdb-shared-posixfs-optimizations TRUE --tmp-dir tmp -O chr16-105582-211160.vcf.gz
07:46:18.893 WARN  GATKAnnotationPluginDescriptor - Redundant enabled annotation group (StandardAnnotation) is enabled for this tool by default
07:46:18.944 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/share/pkg.7/gatk/4.2.0.0/install/bin/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Aug 25, 2021 7:46:19 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
07:46:19.128 INFO  GenotypeGVCFs - ------------------------------------------------------------
07:46:19.128 INFO  GenotypeGVCFs - The Genome Analysis Toolkit (GATK) v4.2.0.0
07:46:19.128 INFO  GenotypeGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
07:46:19.129 INFO  GenotypeGVCFs - Executing as farrell@scc-hadoop.bu.edu on Linux v3.10.0-1160.36.2.el7.x86_64 amd64
07:46:19.129 INFO  GenotypeGVCFs - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_121-b13
07:46:19.129 INFO  GenotypeGVCFs - Start Date/Time: August 25, 2021 7:46:18 AM EDT
07:46:19.129 INFO  GenotypeGVCFs - ------------------------------------------------------------
07:46:19.129 INFO  GenotypeGVCFs - ------------------------------------------------------------
07:46:19.130 INFO  GenotypeGVCFs - HTSJDK Version: 2.24.0
07:46:19.130 INFO  GenotypeGVCFs - Picard Version: 2.25.0
07:46:19.130 INFO  GenotypeGVCFs - Built for Spark Version: 2.4.5
07:46:19.130 INFO  GenotypeGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2
07:46:19.130 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
07:46:19.130 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
07:46:19.130 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
07:46:19.130 INFO  GenotypeGVCFs - Deflater: IntelDeflater
07:46:19.130 INFO  GenotypeGVCFs - Inflater: IntelInflater
07:46:19.131 INFO  GenotypeGVCFs - GCS max retries/reopens: 20
07:46:19.131 INFO  GenotypeGVCFs - Requester pays: disabled
07:46:19.131 INFO  GenotypeGVCFs - Initializing engine
07:46:20.165 INFO  GenomicsDBLibLoader - GenomicsDB native library version : 1.3.2-e18fa63
07:46:21.133 info  NativeGenomicsDB - pid=33555 tid=33556 No valid combination operation found for INFO field AS_InbreedingCoeff  - the field will NOT be part of INFO fields in the generated VCF records
07:46:21.133 info  NativeGenomicsDB - pid=33555 tid=33556 No valid combination operation found for INFO field AS_QD  - the field will NOT be part of INFO fields in the generated VCF records
07:46:21.134 info  NativeGenomicsDB - pid=33555 tid=33556 No valid combination operation found for INFO field DRAGstrInfo  - the field will NOT be part of INFO fields in the generated VCF records
07:46:21.134 info  NativeGenomicsDB - pid=33555 tid=33556 No valid combination operation found for INFO field DRAGstrParams  - the field will NOT be part of INFO fields in the generated VCF records
07:46:21.134 info  NativeGenomicsDB - pid=33555 tid=33556 No valid combination operation found for INFO field InbreedingCoeff  - the field will NOT be part of INFO fields in the generated VCF records
07:46:21.134 info  NativeGenomicsDB - pid=33555 tid=33556 No valid combination operation found for INFO field MLEAC  - the field will NOT be part of INFO fields in the generated VCF records
07:46:21.134 info  NativeGenomicsDB - pid=33555 tid=33556 No valid combination operation found for INFO field MLEAF  - the field will NOT be part of INFO fields in the generated VCF records
07:46:22.360 INFO  IntervalArgumentCollection - Processing 105579 bp from intervals
07:46:22.437 INFO  GenotypeGVCFs - Done initializing engine
07:46:22.622 INFO  ProgressMeter - Starting traversal
07:46:22.622 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
07:47:22.095 INFO  ProgressMeter -         chr16:106932              1.0                  1000           1008.9
GENOMICSDB_TIMER,GenomicsDB iterator next() timer,Wall-clock time(s),3.17483201399997,Cpu time(s),3.128232945999995
07:47:30.073 INFO  ProgressMeter -         chr16:210348              1.1                 77671          69091.0
07:47:30.074 INFO  ProgressMeter - Traversal complete. Processed 77671 total variants in 1.1 minutes.
07:47:30.084 INFO  GenotypeGVCFs - Shutting down engine
[August 25, 2021 7:47:30 AM EDT] org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 1.19 minutes.
Runtime.totalMemory()=2166882304

```

**Comment by ldgauthier** [comment]
No -- I think I can get the branch merged this week.
