### ISSUE TITLE
GnarlyGenotyper parse AS_RAW_MQ spanning deletions

### ISSUE THREAD

**Issue by vladsaveliev** [broadinstitute/gatk#7483]
### Affected tool(s) or class(es)
GnarlyGenotyper

### Affected version(s)
4.2.2.0, 4.2.1.0

### Description

I've got 2 GVCFs, one with a SNP on chr7:2377548:

```
chr7	2377548	.	A	G,<NON_REF>	292.04	.	AS_QUALapprox=|338|0;AS_RAW_BaseQRankSum=|1.0,1|NaN;AS_RAW_MQ=35536.00|25290.00|0.00;AS_RAW_MQRankSum=|-0.8,1|NaN;AS_RAW_ReadPosRankSum=|-2.3,1|NaN;AS_SB_TABLE=3,7|0,8|0,0;AS_VarDP=10|10|0;BaseQRankSum=1.006;DP=22;MQRankSum=-0.752;QUALapprox=338;RAW_GT_COUNT=0,1,0;RAW_MQandDP=72828,22;ReadPosRankSum=-2.285;VarDP=20	GT:AD:DP:GQ:PL:SB	0/1:10,10,0:20:99:338,0,387,341,416,762:3,7,0,8
```

Another one with an upstream indel event spanning chr7:2377548:

```
chr7	2377531	.	AGGAGGAAGGAGCAGGCACGAGCGCTCCTGGGATGCTGTGTTCTGTGAATGACCCTGGGTGTCATGGAGGAAGGAGCAGGCGCGAGCTCTCCTGGGAATCCGTGTTCTGTGAATGACCCTGGGTGTCAAGGAGGAAGGAGCAGGCGCGAGCGCTCCTGGGATGCTGTGTTCTGTGAATGACCCTGGGTGTCAT	A,TGGAGGAAGGAGCAGGCACGAGCGCTCCTGGGATGCTGTGTTCTGTGAATGACCCTGGGTGTCATGGAGGAAGGAGCAGGCGCGAGCTCTCCTGGGAATCCGTGTTCTGTGAATGACCCTGGGTGTCAAGGAGGAAGGAGCAGGCGCGAGCGCTCCTGGGATGCTGTGTTCTGTGAATGACCCTGGGTGTCAT,<NON_REF>	0	.	AS_QUALapprox=|851|0|0;AS_RAW_BaseQRankSum=|||;AS_RAW_MQ=0.00|12289.00|0.00|0.00;AS_RAW_MQRankSum=|||;AS_RAW_ReadPosRankSum=|||;AS_SB_TABLE=0,0|1,4|0,0|0,0;AS_VarDP=0|26|1|0;DP=49;QUALapprox=853;RAW_GT_COUNT=0,0,1;RAW_MQandDP=144241,49;VarDP=27	GT:AD:DP:GQ:PL:SB	1/2:0,26,1,0:27:2:853,2,347,878,0,989,875,282,907,1161:0,0,1,4
```

When merged into a GenomicsDB, they give an empty string in the `AS_RAW_MQ` array:

```
chr7    2377548 .       A       G,*,<NON_REF>   .       .       AS_QUALapprox=|338|0|0;AS_RAW_BaseQRankSum=|1.000,1||;AS_RAW_MQ=35536.000|25290.000||0.000;AS_RAW_MQRankSum=|-0.800,1||;AS_RAW_ReadPosRankSum=|-2.300,1||;AS_SB_TABLE=3,7|0,8||0,0;AS_VarDP=10|10|0|0;BaseQRankSum=1.006;DP=71;MQRankSum=-0.752;QUALapprox=338;RAW_GT_COUNT=0,1,0;RAW_MQandDP=72828,22;ReadPosRankSum=-2.285;VarDP=20   GT:AD:GQ:PL:SB:D
P       ./.:10,10,0,0:99:338,0,387,341,416,762,341,416,762,762:3,7,0,8:20       ./.:0,0,26,0:2:853,875,1161,2,282,347,875,1161,282,1161:0,0,1,4:27
```

Which leads to a GnarlyGenotyper error:

```
gatk GnarlyGenotyper -R Homo_sapiens_assembly38.fasta -O gnarlied.vcf.gz --only-output-calls-starting-in-intervals --keep-all-sites -V gendb.gs://mybucket/genomicsdbs/interval_20_outof_50 -L 0020-scattered.interval_list
<...>
java.lang.IllegalStateException: Something went wrong:
	at org.broadinstitute.hellbender.tools.walkers.gnarlyGenotyper.GnarlyGenotyperEngine.finalizeGenotype(GnarlyGenotyperEngine.java:147)
	at org.broadinstitute.hellbender.tools.walkers.gnarlyGenotyper.GnarlyGenotyperEngine.finalizeGenotype(GnarlyGenotyperEngine.java:78)
	at org.broadinstitute.hellbender.tools.walkers.gnarlyGenotyper.GnarlyGenotyper.apply(GnarlyGenotyper.java:298)
	at org.broadinstitute.hellbender.engine.VariantWalker.lambda$traverse$0(VariantWalker.java:104)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at org.broadinstitute.hellbender.engine.VariantWalker.traverse(VariantWalker.java:102)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1085)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
Caused by: java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at org.broadinstitute.hellbender.tools.walkers.annotator.allelespecific.AS_RMSMappingQuality.parseRawDataString(AS_RMSMappingQuality.java:172)
	at org.broadinstitute.hellbender.tools.walkers.annotator.allelespecific.AS_RMSMappingQuality.finalizeRawData(AS_RMSMappingQuality.java:196)
	at org.broadinstitute.hellbender.tools.walkers.gnarlyGenotyper.GnarlyGenotyperEngine.finalizeGenotype(GnarlyGenotyperEngine.java:137)
	... 23 more
```

Note that GenotypeGVCFs doesn't throw such error.

**Comment by droazen** [comment]
@ldgauthier Thoughts on this one?

**Comment by ldgauthier** [comment]
Thanks for the test data @vladsaveliev !  I already had a fix for this in a branch.  We can probably get it merged in time for the up coming release.
