### ISSUE TITLE
[mutect2] "no normal.pileup" error in mutect2.wdl tumor only mode

### ISSUE THREAD

**Issue by jkobject** [broadinstitute/gatk#7494]
Hello, more information on the parameters and runtime can be found here: #7492 

the stacktrace is now:
```
...
22:14:59.985 INFO ProgressMeter - chrUn_JTFH01001653v1_decoy:301 116.6 2161460 18530.7
22:15:11.142 INFO ProgressMeter - chrUn_JTFH01001673v1_decoy:301 116.8 2161540 18501.9
Using GATK jar /root/gatk.jar defined in environment variable GATK_LOCAL_JAR
Running:
java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx15500m -jar /root/gatk.jar Mutect2 -R gs://genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.fasta -I gs://cclebams/hg38_wes/CDS-02waxZ.hg38.bam -tumor TUHR14TKB --germline-resource gs://depmapomicsdata/gnomad.genomes.r3.0.sites.vcf.bgz -pon gs://depmapomicsdata/1000g_pon.hg38.vcf.gz -L gs://fc-secure-d2a2d895-a7af-4117-bdc7-652d7d268324/cec2a1a6-ffc3-4f1b-ba94-27ae918c56e9/Mutect2/b389d86b-8b0b-4d77-8224-a5a3e3a0b4e5/call-SplitIntervals/cacheCopy/glob-0fc990c5ca95eebc97c4c204e3e303e1/0004-scattered.interval_list -O output.vcf.gz --f1r2-tar-gz f1r2.tar.gz --gcs-project-for-requester-pays broad-firecloud-ccle
ln: failed to access '/cromwell_root/*normal-pileups.table': No such file or directory
ln: failed to access '/cromwell_root/*tumor-pileups.table': No such file or directory
2021/10/05 22:15:24 Starting delocalization.
...
```

I run mutect2 in tumor only mode. 
Interestingly, this error always only happen at the last shard only (every other shard runs to completion)

Thanks!

**Comment by jkobject** [comment]
Actually, for some other samples, I get this error:
(not necesarrily the last shard, but every other shards seem to work till completion)
```
23:24:11.540 INFO VectorLoglessPairHMM - Time spent in setup for JNI call : 0.34203589
23:24:11.546 INFO PairHMM - Total compute time in PairHMM computeLogLikelihoods() : 104.303087949
23:24:11.546 INFO SmithWatermanAligner - Total compute time in java Smith-Waterman : 78.48 sec
23:24:11.553 INFO Mutect2 - Shutting down engine
[October 5, 2021 11:24:11 PM GMT] org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2 done. Elapsed time: 172.32 minutes.
Runtime.totalMemory()=4052746240
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:657)
at java.util.ArrayList.get(ArrayList.java:433)
at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.lambda$getGermlineAltAlleleFrequencies$27(SomaticGenotypingEngine.java:352)
at java.util.stream.ReferencePipeline$6$1.accept(ReferencePipeline.java:244)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
at java.util.stream.DoublePipeline.toArray(DoublePipeline.java:530)
at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.getGermlineAltAlleleFrequencies(SomaticGenotypingEngine.java:354)
at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.getNegativeLogPopulationAFAnnotation(SomaticGenotypingEngine.java:337)
at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.callMutations(SomaticGenotypingEngine.java:155)
at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2Engine.callRegion(Mutect2Engine.java:259)
at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2.apply(Mutect2.java:306)
at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:200)
at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:173)
at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1085)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
at org.broadinstitute.hellbender.Main.main(Main.java:289)
Using GATK jar /root/gatk.jar defined in environment variable GATK_LOCAL_JAR
```

**Comment by fleharty** [comment]
@davidbenjamin Could you take a look at this?

**Comment by jkobject** [comment]
yes I think this is the reason of that error. but the reason the tool crash seems to be related to memory. I have run with 16 vs 32 and only the later runs to completion on a set of 30 WES (no specificly deep sequencing but they are cell line genomes)

**Comment by lbergelson** [comment]
It's weird, usually java should output an error message if it runs out of memory.  The exception would be when java is assigned so much memory that the SYSTEM kills it instead of java killing itself.  
You could try adding `dmesg | tail -100` to your wdl after m2 runs to see if there are any messages from the OOMkiller.  

What's your total available memory on the machine and your -Xmx setting? You typically need to leave some memory room for the OS and other native sofware.  (although by default our pipelines SHOULD have that configured correctly.)

**Comment by jkobject** [comment]
yes I left the rest to the pipeline, I had initially increased hard drive and boot disk size but it worked without that. 
Let me share the workspace with you so you can have a look.
