### ISSUE TITLE
[MUTECT2] Java can throw Null Pointer exception when bed is not based on the same reference as bam file

### ISSUE THREAD

**Issue by grafitos** [broadinstitute/gatk#7496]
### Affected tool(s) or class(es)

Mutect2
`
java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx130g -jar /gatk/gatk-package-4.1.8.1-local.jar Mutect2 -R /ucsc.hg19.fasta -I my.bam -L /test.bed --f1r2-tar-gz DD.f1r2.tar.gz --force-active --genotype-germline-sites --kmer-size 10 --kmer-size 20 --recover-all-dangling-branches --max-reads-per-alignment-start 0 --native-pair-hmm-threads 33 -O DD.vcf.gz
`

### Affected version(s)
Using GATK jar /gatk/gatk-package-4.1.8.1-local.jar

### Description 
When bed is created with a reference genome that is not the same as  the bam file, an null pointer can occurs. The error is not catched by GATK, and the error is difficult to understand.

Here a discussion about it.
https://gatk.broadinstitute.org/hc/en-us/community/posts/360077477391-Haplotype-caller-fails-to-run-GATK-4-1-8-0-and-GATK-4-2-0-0-

The case below occurs when provided bed has been made with the wrong genome reference.
`
14:25:55.254 INFO NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gatk/gatk-package-4.1.8.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
Oct 07, 2021 2:25:55 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
14:25:55.525 INFO Mutect2 - ------------------------------------------------------------
14:25:55.525 INFO Mutect2 - The Genome Analysis Toolkit (GATK) v4.1.8.1
14:25:55.525 INFO Mutect2 - For support and documentation go to https://software.broadinstitute.org/gatk/
14:25:55.525 INFO Mutect2 - Executing as toto on Linux v5.4.123-1.el7.elrepo.x86_64 amd64
14:25:55.525 INFO Mutect2 - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_242-8u242-b08-0ubuntu3~18.04-b08
14:25:55.526 INFO Mutect2 - Start Date/Time: October 7, 2021 2:25:55 PM GMT
14:25:55.526 INFO Mutect2 - ------------------------------------------------------------
14:25:55.526 INFO Mutect2 - ------------------------------------------------------------
14:25:55.526 INFO Mutect2 - HTSJDK Version: 2.23.0
14:25:55.526 INFO Mutect2 - Picard Version: 2.22.8
14:25:55.526 INFO Mutect2 - HTSJDK Defaults.COMPRESSION_LEVEL : 2
14:25:55.526 INFO Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
14:25:55.527 INFO Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
14:25:55.527 INFO Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
14:25:55.527 INFO Mutect2 - Deflater: IntelDeflater
14:25:55.527 INFO Mutect2 - Inflater: IntelInflater
14:25:55.527 INFO Mutect2 - GCS max retries/reopens: 20
14:25:55.527 INFO Mutect2 - Requester pays: disabled
14:25:55.527 INFO Mutect2 - Initializing engine
14:25:55.994 INFO FeatureManager - Using codec BEDCodec to read file file:///test.bed
14:25:56.086 INFO IntervalArgumentCollection - Processing 3896357 bp from intervals
14:25:56.115 INFO Mutect2 - Shutting down engine
[October 7, 2021 2:25:56 PM GMT] org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2 done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=2102919168
**java.lang.NullPointerException**
at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:325)
at java.util.ComparableTimSort.sort(ComparableTimSort.java:202)
at java.util.Arrays.sort(Arrays.java:1312)
at java.util.Arrays.sort(Arrays.java:1506)
at java.util.ArrayList.sort(ArrayList.java:1462)
at java.util.Collections.sort(Collections.java:143)
at org.broadinstitute.hellbender.utils.IntervalUtils.sortAndMergeIntervals(IntervalUtils.java:467)
at org.broadinstitute.hellbender.utils.IntervalUtils.getIntervalsWithFlanks(IntervalUtils.java:965)
at org.broadinstitute.hellbender.utils.IntervalUtils.getIntervalsWithFlanks(IntervalUtils.java:980)
at org.broadinstitute.hellbender.engine.MultiIntervalLocalReadShard.(MultiIntervalLocalReadShard.java:59)
at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.makeReadShards(AssemblyRegionWalker.java:104)
at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.onStartup(AssemblyRegionWalker.java:84)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:138)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)

#### Expected behavior
Exception should be catched by GATK to provide a meaningful message

#### Actual behavior
NullPointerException is thrown by java

### Tool(s) or class(es) involved
I think this method https://github.com/broadinstitute/gatk/blob/95852a1e70300b932bad153c845003a097abbbe1/src/main/java/org/broadinstitute/hellbender/utils/GenomeLocParser.java#L517 could return null, and is not correctly handled by caller method.

**Comment by lbergelson** [comment]
@grafitos I just want to say thank you for this really excellent bug report.  I wish all of them had a detailed stack trace and included the problematic line of code :)
