### ISSUE TITLE
gatk haplotypecaller return error 

### ISSUE THREAD

**Issue by milkcookie** [broadinstitute/gatk#7499]
Dear all:
 I have a error flow:
INFO  14:49:42,880 HelpFormatter - ------------------------------------------------------------------------------------
INFO  14:49:42,883 HelpFormatter - The Genome Analysis Toolkit (GATK) v3.8-1-0-gf15c1c3ef, Compiled 2018/02/19 05:43:50
INFO  14:49:42,884 HelpFormatter - Copyright (c) 2010-2016 The Broad Institute
INFO  14:49:42,884 HelpFormatter - For support and documentation go to https://software.broadinstitute.org/gatk
INFO  14:49:42,884 HelpFormatter - [Sat Oct 09 14:49:42 CST 2021] Executing on Linux 2.6.32-696.el6.x86_64 amd64
INFO  14:49:42,884 HelpFormatter - Java HotSpot(TM) 64-Bit Server VM 1.8.0_11-b12
INFO  14:49:42,889 HelpFormatter - Program Args: -T HaplotypeCaller -R /share/Onc_Soft_DB/database/capsmart/hg19/hg19_20210805/hg19.rm_CRLF2_P2RY8.fix_PRSS1_MUC16.fasta -I /share/Onc_RD_Pipeline/OncDir/zhuangll/210927-commercial-tissue-zhangaiyuan/germline/Z19W06700-F1WA/2.Realign/Z19W06700-F1WA.bam -L /share/Onc_Soft_DB/database/capsmart/bed/gene102.snpindel.capsmart.bed -U -o /share/Onc_RD_Pipeline/OncDir/yanhs/test/GATK/Z19W06700-F1WA.HaplotypeCaller.raw.vcf -stand_call_conf 50 -A RMSMappingQuality -A BaseCounts
INFO  14:49:42,892 HelpFormatter - Executing as yanhs3941@compute-0-76 on Linux 2.6.32-696.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_11-b12.
INFO  14:49:42,892 HelpFormatter - Date/Time: 2021/10/09 14:49:42
INFO  14:49:42,892 HelpFormatter - ------------------------------------------------------------------------------------
INFO  14:49:42,892 HelpFormatter - ------------------------------------------------------------------------------------
INFO  14:49:42,922 NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/share/Onc_Soft_DB/software/GATK3.8/GenomeAnalysisTK.jar!/com/intel/gkl/native/libgkl_compression.so
INFO  14:49:42,957 GenomeAnalysisEngine - Deflater: IntelDeflater
INFO  14:49:42,958 GenomeAnalysisEngine - Inflater: IntelInflater
INFO  14:49:42,958 GenomeAnalysisEngine - Strictness is SILENT
INFO  14:49:43,125 GenomeAnalysisEngine - Downsampling Se

the error is :
maxAltAlleles (6), the following will be dropped: TAAC.
WARN  14:59:10,944 HaplotypeCallerGenotypingEngine - location chr12:21623284-21623286: too many alternative alleles found (8) larger than the maximum requested with -maxAltAlleles (6), the following will be dropped: C, CA.
INFO  14:59:13,453 ProgressMeter -  chr12:21624342      1.0358131E7     9.5 m           55.0 s       49.5%    19.2 m       9.7 m
WARN  14:59:37,613 HaplotypeCallerGenotypingEngine - location chr12:133237753-133237756: too many alternative alleles found (9) larger than the maximum requested with -maxAltAlleles (6), the following will be dropped: G, TAAA, GAAAAAAA.
INFO  14:59:43,454 ProgressMeter -  chr13:32892450      1.0955099E7    10.0 m           54.0 s       54.0%    18.5 m       8.5 m
INFO  15:00:13,456 ProgressMeter -  chr13:32912251      1.0976428E7    10.5 m           57.0 s       55.2%    19.0 m       8.5 m
##### ERROR stack trace
java.lang.IllegalStateException: Never found start -1 or stop -1 given cigar 17I
        at org.broadinstitute.gatk.utils.sam.AlignmentUtils.getBasesCoveringRefInterval(AlignmentUtils.java:204)
        at org.broadinstitute.gatk.utils.sam.AlignmentUtils.countBasesAtPileupPosition(AlignmentUtils.java:1418)
        at org.broadinstitute.gatk.tools.walkers.annotator.BaseCounts.getBaseCounts(BaseCounts.java:93)
        at org.broadinstitute.gatk.tools.walkers.annotator.BaseCounts.annotate(BaseCounts.java:78)
        at org.broadinstitute.gatk.tools.walkers.annotator.VariantAnnotatorEngine.annotateContextForActiveRegion(VariantAnnotatorEngine.java:315)
        at org.broadinstitute.gatk.tools.walkers.annotator.VariantAnnotatorEngine.annotateContextForActiveRegion(VariantAnnotatorEngine.java:260)
        at org.broadinstitute.gatk.tools.walkers.haplotypecaller.HaplotypeCallerGenotypingEngine.annotateCall(HaplotypeCallerGenotypingEngine.java:328)
        at org.broadinstitute.gatk.tools.walkers.haplotypecaller.HaplotypeCallerGenotypingEngine.assignGenotypeLikelihoods(HaplotypeCallerGenotypin

I use phone so Ican't write well, what does never found start -1 mean?
thanks

**Comment by milkcookie** [comment]
my gatk version is v3.8-1-0
