### ISSUE TITLE
GATK concordance java.lang.NullPointerException

### ISSUE THREAD

**Issue by GATKSupportTeam** [broadinstitute/gatk#7562]
A GATK user is getting a java.lang.NullPointerException when running Concordance. It seems that their eval VCF has contigs that do not match the truth dataset. It would be helpful to add a better error message for this case.

This request was created from a contribution made by Priyadarshini Thirunavukkarasu on November 11, 2021 10:19 UTC.

Link: [https://gatk.broadinstitute.org/hc/en-us/community/posts/4410110105755-GATK-concordance](https://gatk.broadinstitute.org/hc/en-us/community/posts/4410110105755-GATK-concordance)

\--

Hello

I am running GATK/4.2.2.0-foss-2018b-Java-1.8 in the cluster. After running the given below code, I am not able to find the output file (summary file). This is the link, where the code is given \[[https://gatk.broadinstitute.org/hc/en-us/articles/4405451404699-Concordance#--summary\](/hc/en-us/articles/4405451404699-Concordance#--summary)](https://gatk.broadinstitute.org/hc/en-us/articles/4405451404699-Concordance#--summary](/hc/en-us/articles/4405451404699-Concordance#--summary)). Please also find the log file below. Is the summary file required as input file to run the below script? Please advice

 gatk Concordance \\  
  
   -R /scicore/home/cichon/GROUP/memory\_optimization/data/reference/gch38.fa \\  
  
   -eval /scicore/home/cichon/GROUP/memory\_optimization/variants/filtered/sample1\_affect.filtered.vcf \\  
  
   --truth /scicore/home/cichon/GROUP/memory\_optimization/variants/filtered/NA12878.vcf.gz \\  
  
   --summary /scicore/home/cichon/GROUP/memory\_optimization/variants/filtered/summary.tsv    
11:26:21.545 INFO NativeLibraryLoader - Loading libgkl\_compression.so from jar:file:/scicore/soft/apps/GATK/4.2.2.0-foss-2018b-Java-1.8/gatk-package-4.2.2.0-local.jar!/com/intel/gkl/native/libgkl\_compression.so  
  
Nov 11, 2021 11:26:21 AM shaded.cloud\_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine  
  
INFO: Failed to detect whether we are running on Google Compute Engine.  
  
11:26:21.681 INFO Concordance - ------------------------------------------------------------  
  
11:26:21.682 INFO Concordance - The Genome Analysis Toolkit (GATK) v4.2.2.0  
  
11:26:21.682 INFO Concordance - For support and documentation go to [https://software.broadinstitute.org/gatk/](https://software.broadinstitute.org/gatk/)  
  
11:26:21.682 INFO Concordance - Executing as [thirun0000@shi85.cluster.bc2.ch](mailto:thirun0000@shi85.cluster.bc2.ch) on Linux v3.10.0-1062.18.1.el7.x86\_64 amd64  
  
11:26:21.682 INFO Concordance - Java runtime: OpenJDK 64-Bit Server VM v1.8.0\_212-b03  
  
11:26:21.682 INFO Concordance - Start Date/Time: November 11, 2021 11:26:21 AM CET  
  
11:26:21.682 INFO Concordance - ------------------------------------------------------------  
  
11:26:21.682 INFO Concordance - ------------------------------------------------------------  
  
11:26:21.683 INFO Concordance - HTSJDK Version: 2.24.1  
  
11:26:21.683 INFO Concordance - Picard Version: 2.25.4  
  
11:26:21.683 INFO Concordance - Built for Spark Version: 2.4.5  
  
11:26:21.683 INFO Concordance - HTSJDK Defaults.COMPRESSION\_LEVEL : 2  
  
11:26:21.683 INFO Concordance - HTSJDK Defaults.USE\_ASYNC\_IO\_READ\_FOR\_SAMTOOLS : false  
  
11:26:21.683 INFO Concordance - HTSJDK Defaults.USE\_ASYNC\_IO\_WRITE\_FOR\_SAMTOOLS : true  
  
11:26:21.683 INFO Concordance - HTSJDK Defaults.USE\_ASYNC\_IO\_WRITE\_FOR\_TRIBBLE : false  
  
11:26:21.683 INFO Concordance - Deflater: IntelDeflater  
  
11:26:21.684 INFO Concordance - Inflater: IntelInflater  
  
11:26:21.684 INFO Concordance - GCS max retries/reopens: 20  
  
11:26:21.684 INFO Concordance - Requester pays: disabled  
  
11:26:21.684 INFO Concordance - Initializing engine  
  
11:26:22.217 INFO FeatureManager - Using codec VCFCodec to read file file:///scicore/home/cichon/GROUP/memory\_optimization/variants/filtered/NA12878.vcf.gz  
  
11:26:22.497 INFO FeatureManager - Using codec VCFCodec to read file file:///scicore/home/cichon/GROUP/memory\_optimization/variants/filtered/sample1\_affect.filtered.vcf  
  
11:26:22.663 INFO Concordance - Done initializing engine  
  
11:26:22.672 INFO ProgressMeter - Starting traversal  
  
11:26:22.672 INFO ProgressMeter - Current Locus Elapsed Minutes Records Processed Records/Minute  
  
11:26:22.682 INFO Concordance - Shutting down engine  
  
\[November 11, 2021 11:26:22 AM CET\] org.broadinstitute.hellbender.tools.walkers.validation.Concordance done. Elapsed time: 0.02 minutes.  
  
Runtime.totalMemory()=559939584  
  
java.lang.NullPointerException  
  
at htsjdk.variant.variantcontext.VariantContextComparator.compare(VariantContextComparator.java:87)  
  
at org.broadinstitute.hellbender.engine.AbstractConcordanceWalker$ConcordanceIterator.next(AbstractConcordanceWalker.java:192)  
  
at org.broadinstitute.hellbender.engine.AbstractConcordanceWalker$ConcordanceIterator.next(AbstractConcordanceWalker.java:174)  
  
at java.util.Iterator.forEachRemaining(Iterator.java:116)  
  
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)  
  
at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)  
  
at org.broadinstitute.hellbender.engine.AbstractConcordanceWalker.traverse(AbstractConcordanceWalker.java:132)  
  
at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1085)  
  
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)  
  
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)  
  
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)  
  
at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)  
  
at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)  
  
at org.broadinstitute.hellbender.Main.main(Main.java:289)  
  
Using GATK jar /scicore/soft/apps/GATK/4.2.2.0-foss-2018b-Java-1.8/gatk-package-4.2.2.0-local.jar  
  
Running:  
  
java -Dsamjdk.use\_async\_io\_read\_samtools=false -Dsamjdk.use\_async\_io\_write\_samtools=true -Dsamjdk.use\_async\_io\_write\_tribble=false -Dsamjdk.compression\_level=2 -jar /scicore/soft/apps/GATK/4.2.2.0-foss-2018b-Java-1.8/gatk-package-4.2.2.0-local.jar Concordance -R /scicore/home/cichon/GROUP/memory\_optimization/data/reference/gch38.fa -eval /scicore/home/cichon/GROUP/memory\_optimization/variants/filtered/sample1\_affect.filtered.vcf --truth /scicore/home/cichon/GROUP/memory\_optimization/variants/filtered/NA12878.vcf.gz --summary /scicore/home/cichon/GROUP/memory\_optimization/variants/filtered/summary.tsv  
Thanks

Priya<br><br><i>(created from <a href='https://broadinstitute.zendesk.com/agent/tickets/214165'>Zendesk ticket #214165</a>)<br>gz#214165</i>

**Comment by droazen** [comment]
@GATKSupportTeam @gbrandt6 We suspect that this issue might be caused by either one VCF having a contig not in the other VCF, or one of the VCFs having a contig not in the reference sequence dictionary. Could you please ask the user to check their VCFs for such a contig?

**Comment by gbrandt6** [comment]
Yes, the user has confirmed there are contigs in their eval VCF that are not in the truth VCF. This bug report is to improve the error message for this case.
