### ISSUE TITLE
Request created from: "Did not inflate expected amount" Error

### ISSUE THREAD

**Issue by GATKSupportTeam** [broadinstitute/gatk#7582]
This user is noticing that when running BQSR with the default inflater, some blocks have compression errors that result in issues while running HaplotypeCaller.

This request was created from a contribution made by Jacob Wang on November 02, 2021 08:27 UTC.

Link: [https://gatk.broadinstitute.org/hc/en-us/community/posts/4409429876123--Did-not-inflate-expected-amount-Error](https://gatk.broadinstitute.org/hc/en-us/community/posts/4409429876123--Did-not-inflate-expected-amount-Error)

\--

Hi! I'm doing WGS analysis of a pedigree of three individuals using GATK 4.2.0.0. Everything went on well for the first individual. However, in the step of generating gvcf file from bam file, I encountered the error \[htsjdk.samtools.SAMFormatException: Did not inflate expected amount\] in the other two of the individuals. Please help me! Thank you in advance!

a) GATK version used:

GATK 4.2.0.0

b) Exact command used:

java -jar /home/ngs/biosoft/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar \\  
  
HaplotypeCaller \\  
  
\-R /media/ngs/NGS0/Database/RefSeq/Homo\_sapiens\_NCBI\_GRCh38Decoy/Homo\_sapiens/NCBI/GRCh38Decoy/Sequence/WholeGenomeFasta/NewIndex/genome.fa \\  
  
\-I /media/ngs/BAM5T/WGS\_analysis/Data/9\_BQSRBam/Ped-San-3\_merged\_realigned\_bqsr.bam \\  
  
\-ERC GVCF \\  
  
\-O /media/ngs/BAM5T/WGS\_analysis/Data/10\_gvcf/Ped-San-3\_merged\_realigned\_bqsr.g.vcf

c) Entire error log:

14:14:32.075 INFO NativeLibraryLoader - Loading libgkl\_compression.so from jar:file:/home/ngs/biosoft/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl\_compression.so  
  
Nov 01, 2021 2:14:32 PM shaded.cloud\_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine  
  
INFO: Failed to detect whether we are running on Google Compute Engine.  
  
14:14:32.573 INFO HaplotypeCaller - ------------------------------------------------------------  
  
14:14:32.573 INFO HaplotypeCaller - The Genome Analysis Toolkit (GATK) v4.2.0.0  
  
14:14:32.573 INFO HaplotypeCaller - For support and documentation go to [https://software.broadinstitute.org/gatk/](https://software.broadinstitute.org/gatk/)  
  
14:14:32.573 INFO HaplotypeCaller - Executing as ngs@ngs-linux on Linux v5.8.0-59-generic amd64  
  
14:14:32.573 INFO HaplotypeCaller - Java runtime: OpenJDK 64-Bit Server VM v1.8.0\_292-8u292-b10-0ubuntu1~20.04-b10  
  
14:14:32.573 INFO HaplotypeCaller - Start Date/Time: 2021年11月1日 下午02时14分31秒  
  
14:14:32.573 INFO HaplotypeCaller - ------------------------------------------------------------  
  
14:14:32.573 INFO HaplotypeCaller - ------------------------------------------------------------  
  
14:14:32.574 INFO HaplotypeCaller - HTSJDK Version: 2.24.0  
  
14:14:32.574 INFO HaplotypeCaller - Picard Version: 2.25.0  
  
14:14:32.574 INFO HaplotypeCaller - Built for Spark Version: 2.4.5  
  
14:14:32.574 INFO HaplotypeCaller - HTSJDK Defaults.COMPRESSION\_LEVEL : 2  
  
14:14:32.574 INFO HaplotypeCaller - HTSJDK Defaults.USE\_ASYNC\_IO\_READ\_FOR\_SAMTOOLS : false  
  
14:14:32.574 INFO HaplotypeCaller - HTSJDK Defaults.USE\_ASYNC\_IO\_WRITE\_FOR\_SAMTOOLS : true  
  
14:14:32.574 INFO HaplotypeCaller - HTSJDK Defaults.USE\_ASYNC\_IO\_WRITE\_FOR\_TRIBBLE : false  
  
14:14:32.574 INFO HaplotypeCaller - Deflater: IntelDeflater  
  
14:14:32.574 INFO HaplotypeCaller - Inflater: IntelInflater  
  
14:14:32.574 INFO HaplotypeCaller - GCS max retries/reopens: 20  
  
14:14:32.574 INFO HaplotypeCaller - Requester pays: disabled  
  
14:14:32.574 INFO HaplotypeCaller - Initializing engine  
  
14:14:36.824 INFO HaplotypeCaller - Done initializing engine  
  
14:14:36.826 INFO HaplotypeCallerEngine - Tool is in reference confidence mode and the annotation, the following changes will be made to any specified annotations: 'StrandBiasBySample' will be enabled. 'ChromosomeCounts', 'FisherStrand', 'StrandOddsRatio' and 'QualByDepth' annotations have been disabled  
  
14:14:36.866 INFO HaplotypeCallerEngine - Standard Emitting and Calling confidence set to 0.0 for reference-model confidence output  
  
14:14:36.866 INFO HaplotypeCallerEngine - All sites annotated with PLs forced to true for reference-model confidence output  
  
14:14:36.876 INFO NativeLibraryLoader - Loading libgkl\_utils.so from jar:file:/home/ngs/biosoft/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl\_utils.so  
  
14:14:36.878 INFO NativeLibraryLoader - Loading libgkl\_pairhmm\_omp.so from jar:file:/home/ngs/biosoft/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl\_pairhmm\_omp.so  
  
14:14:36.927 INFO IntelPairHmm - Flush-to-zero (FTZ) is enabled when running PairHMM  
  
14:14:36.928 INFO IntelPairHmm - Available threads: 8  
  
14:14:36.928 INFO IntelPairHmm - Requested threads: 4  
  
14:14:36.928 INFO PairHMM - Using the OpenMP multi-threaded AVX-accelerated native PairHMM implementation  
  
14:14:37.228 INFO ProgressMeter - Starting traversal  
  
14:14:37.228 INFO ProgressMeter - Current Locus Elapsed Minutes Regions Processed Regions/Minute  
  
14:14:38.715 WARN InbreedingCoeff - InbreedingCoeff will not be calculated at position chr1:10439 and possibly subsequent; at least 10 samples must have called genotypes  
  
14:14:47.243 INFO ProgressMeter - chr1:186172 0.2 920 5511.7  
  
14:14:57.278 INFO ProgressMeter - chr1:830665 0.3 3650 10922.7  
  
14:15:05.692 WARN DepthPerSampleHC - Annotation will not be calculated at position chr1:977935 and possibly subsequent; genotype for sample 8939{JXM}-3 is not called  
  
14:15:05.692 WARN StrandBiasBySample - Annotation will not be calculated at position chr1:977935 and possibly subsequent; genotype for sample 8939{JXM}-3 is not called  
  
14:15:07.307 INFO ProgressMeter - chr1:1001168 0.5 4640 9255.6  
  
14:15:17.364 INFO ProgressMeter - chr1:1225127 0.7 5890 8805.1  
  
...................................................................................

23:42:13.843 INFO ProgressMeter - chr6:61885746 567.6 5518770 9722.8  
  
23:42:23.883 INFO ProgressMeter - chr6:62348074 567.8 5520940 9723.8  
  
23:42:33.905 INFO ProgressMeter - chr6:63002985 567.9 5523550 9725.5  
  
23:42:43.959 INFO ProgressMeter - chr6:63445408 568.1 5525630 9726.3  
  
23:42:53.980 INFO ProgressMeter - chr6:64097380 568.3 5528160 9727.9  
  
23:43:03.981 INFO ProgressMeter - chr6:64620666 568.4 5530460 9729.1  
  
23:43:14.001 INFO ProgressMeter - chr6:65092981 568.6 5532720 9730.2  
  
23:43:24.023 INFO ProgressMeter - chr6:65484919 568.8 5534570 9730.6  
  
23:43:34.123 INFO ProgressMeter - chr6:65881517 568.9 5536530 9731.2  
  
23:43:44.137 INFO ProgressMeter - chr6:66376712 569.1 5538770 9732.2  
  
23:43:54.146 INFO ProgressMeter - chr6:66759727 569.3 5540620 9732.6  
  
23:44:04.211 INFO ProgressMeter - chr6:67127862 569.4 5542540 9733.2  
  
23:44:10.555 WARN DepthPerSampleHC - Annotation will not be calculated at position chr6:67407399 and possibly subsequent; genotype for sample 8939{JXM}-3 is not called  
  
23:44:10.555 WARN StrandBiasBySample - Annotation will not be calculated at position chr6:67407399 and possibly subsequent; genotype for sample 8939{JXM}-3 is not called  
  
23:44:10.556 WARN DepthPerSampleHC - Annotation will not be calculated at position chr6:67407415 and possibly subsequent; genotype for sample 8939{JXM}-3 is not called  
  
23:44:10.556 WARN StrandBiasBySample - Annotation will not be calculated at position chr6:67407415 and possibly subsequent; genotype for sample 8939{JXM}-3 is not called  
  
23:44:14.224 INFO ProgressMeter - chr6:67607778 569.6 5544800 9734.3  
  
23:44:24.280 INFO ProgressMeter - chr6:68147283 569.8 5547230 9735.7  
  
23:44:30.026 INFO VectorLoglessPairHMM - Time spent in setup for JNI call : 27.307544954  
  
23:44:30.027 INFO PairHMM - Total compute time in PairHMM computeLogLikelihoods() : 4768.198119518001  
  
23:44:30.027 INFO SmithWatermanAligner - Total compute time in java Smith-Waterman : 4695.36 sec  
  
23:44:30.027 INFO HaplotypeCaller - Shutting down engine  
  
\[2021年11月1日 下午11时44分30秒\] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 569.97 minutes.  
  
Runtime.totalMemory()=742916096  
  
htsjdk.samtools.SAMFormatException: Did not inflate expected amount  
  
at htsjdk.samtools.util.BlockGunzipper.unzipBlock(BlockGunzipper.java:147)  
  
at htsjdk.samtools.util.BlockGunzipper.unzipBlock(BlockGunzipper.java:96)  
  
at htsjdk.samtools.util.BlockCompressedInputStream.inflateBlock(BlockCompressedInputStream.java:550)  
  
at htsjdk.samtools.util.BlockCompressedInputStream.processNextBlock(BlockCompressedInputStream.java:532)  
  
at htsjdk.samtools.util.BlockCompressedInputStream.nextBlock(BlockCompressedInputStream.java:468)  
  
at htsjdk.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:458)  
  
at htsjdk.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:196)  
  
at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:331)  
  
at java.io.DataInputStream.read(DataInputStream.java:149)  
  
at htsjdk.samtools.util.BinaryCodec.readBytesOrFewer(BinaryCodec.java:421)  
  
at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:394)  
  
at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:380)  
  
at htsjdk.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:282)  
  
at htsjdk.samtools.BAMFileReader$BAMFileIterator.getNextRecord(BAMFileReader.java:866)  
  
at htsjdk.samtools.BAMFileReader$BAMFileIndexIterator.getNextRecord(BAMFileReader.java:1005)  
  
at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:840)  
  
at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:834)  
  
at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:802)  
  
at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.advance(BAMFileReader.java:1058)  
  
at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.next(BAMFileReader.java:1048)  
  
at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.next(BAMFileReader.java:1012)  
  
at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:591)  
  
at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:570)  
  
at org.broadinstitute.hellbender.utils.iterators.SamReaderQueryingIterator.loadNextRecord(SamReaderQueryingIterator.java:119)  
  
at org.broadinstitute.hellbender.utils.iterators.SamReaderQueryingIterator.next(SamReaderQueryingIterator.java:156)  
  
at org.broadinstitute.hellbender.utils.iterators.SamReaderQueryingIterator.next(SamReaderQueryingIterator.java:29)  
  
at org.broadinstitute.hellbender.utils.iterators.SAMRecordToReadIterator.next(SAMRecordToReadIterator.java:27)  
  
at org.broadinstitute.hellbender.utils.iterators.SAMRecordToReadIterator.next(SAMRecordToReadIterator.java:13)  
  
at org.broadinstitute.hellbender.utils.iterators.ReadTransformingIterator.next(ReadTransformingIterator.java:42)  
  
at org.broadinstitute.hellbender.utils.iterators.ReadTransformingIterator.next(ReadTransformingIterator.java:14)  
  
at org.broadinstitute.hellbender.utils.iterators.ReadFilteringIterator.loadNextRead(ReadFilteringIterator.java:53)  
  
at org.broadinstitute.hellbender.utils.iterators.ReadFilteringIterator.next(ReadFilteringIterator.java:47)  
  
at org.broadinstitute.hellbender.utils.iterators.ReadFilteringIterator.next(ReadFilteringIterator.java:13)  
  
at org.broadinstitute.hellbender.utils.iterators.ReadTransformingIterator.next(ReadTransformingIterator.java:42)  
  
at org.broadinstitute.hellbender.utils.iterators.ReadTransformingIterator.next(ReadTransformingIterator.java:14)  
  
at org.broadinstitute.hellbender.utils.iterators.PushToPullIterator.fillCache(PushToPullIterator.java:72)  
  
at org.broadinstitute.hellbender.utils.iterators.PushToPullIterator.advanceToNextElement(PushToPullIterator.java:58)  
  
at org.broadinstitute.hellbender.utils.iterators.PushToPullIterator.next(PushToPullIterator.java:52)  
  
at org.broadinstitute.hellbender.utils.iterators.ReadCachingIterator.next(ReadCachingIterator.java:42)  
  
at org.broadinstitute.hellbender.utils.iterators.ReadCachingIterator.next(ReadCachingIterator.java:17)  
  
at htsjdk.samtools.util.PeekableIterator.advance(PeekableIterator.java:71)  
  
at htsjdk.samtools.util.PeekableIterator.next(PeekableIterator.java:57)  
  
at org.broadinstitute.hellbender.utils.locusiterator.ReadStateManager.collectPendingReads(ReadStateManager.java:160)  
  
at org.broadinstitute.hellbender.utils.locusiterator.LocusIteratorByState.lazyLoadNextAlignmentContext(LocusIteratorByState.java:315)  
  
at org.broadinstitute.hellbender.utils.locusiterator.LocusIteratorByState.hasNext(LocusIteratorByState.java:252)  
  
at org.broadinstitute.hellbender.utils.locusiterator.IntervalAlignmentContextIterator.advanceAlignmentContext(IntervalAlignmentContextIterator.java:104)  
  
at org.broadinstitute.hellbender.utils.locusiterator.IntervalAlignmentContextIterator.advanceAlignmentContextToCurrentInterval(IntervalAlignmentContextIterator.java:99)  
  
at org.broadinstitute.hellbender.utils.locusiterator.IntervalAlignmentContextIterator.next(IntervalAlignmentContextIterator.java:69)  
  
at org.broadinstitute.hellbender.utils.locusiterator.IntervalAlignmentContextIterator.next(IntervalAlignmentContextIterator.java:21)  
  
at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.loadNextAssemblyRegion(AssemblyRegionIterator.java:120)  
  
at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.next(AssemblyRegionIterator.java:112)  
  
at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.next(AssemblyRegionIterator.java:35)  
  
at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:192)  
  
at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:173)  
  
at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1058)  
  
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)  
  
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)  
  
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)  
  
at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)  
  
at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)  
  
at org.broadinstitute.hellbender.Main.main(Main.java:289)<br><br><i>(created from <a href='https://broadinstitute.zendesk.com/agent/tickets/210082'>Zendesk ticket #210082</a>)<br>gz#210082</i>

**Comment by greekkey** [comment]
First, my current solution: adding the --use-jdk-deflater & --use-jdk-inflater options in both of the steps of BQSR and gvcf calling, forcing the software use jdk-deflater/inflater instead of the Intel's deflater/inflater (default in GATK4).

**Comment by greekkey** [comment]
The error is probably caused by the incompatibility of the intel and jdk deflaters/inflaters.

**Comment by greekkey** [comment]
I encountered the error mentioned above when I was calling variants from whole genome sequencing data of three individuals in a pedigree, using GATK4 following the best practice. It happeded in the step of generating gvcf from the bam files after BQSR. Very interesting, it happened in two of three samples, at different position; for the other sample, gvcf was generated successfully.

**Comment by greekkey** [comment]
The same error was reported in other modules of GATK4. For eacmple, in GenomicsDBimport [Ref.1]. And I encountered it again when I check the bams with ValidateSamFile.

[1] https://gatk.broadinstitute.org/hc/en-us/community/posts/360076477211-GenomicsDBimport-not-importing-all-the-batches?page=1#community_comment_4411519756827

**Comment by greekkey** [comment]
One thing to address is that just use the --use-jdk-deflater/inflater options in the step where the error information was given, in my case, HaplotypeCaller, was not help. (In [Ref1], the author tried using --use-jdk-deflater/inflater options in GenomicsDBimport. Although the author said "the error was solved", actually it was not solved, because he/she mentioned that it was still "end of the error log")

**Comment by greekkey** [comment]
I would suggest adding the --use-jdk-deflater & --use-jdk-inflater options in all the steps to avoid this kind of error, which seems to be random.
