### ISSUE TITLE
Request created from: GermlineCNVCaller prefix string too short

### ISSUE THREAD

**Issue by GATKSupportTeam** [broadinstitute/gatk#7591]
The first issue in this post has been solved by updating GATK versions but there appears to be a bug causing an "unrecognized argument" error when running GermlineCNVCaller. 

This request was created from a contribution made by Ahmed S. Chakroun on December 05, 2021 13:52 UTC.

Link: [https://gatk.broadinstitute.org/hc/en-us/community/posts/4412031649691-GermlineCNVCaller-prefix-string-too-short](https://gatk.broadinstitute.org/hc/en-us/community/posts/4412031649691-GermlineCNVCaller-prefix-string-too-short)

\--

Hi everybody,

Unfortunately, I am getting stuck because the filename length of my hd5 is too short (< 3) to be used as prefix by the GermlineCNVCaller. So, I am posting just to check that nothing is left for me to do at this level of the analysis I am running other than renaming my input files and re-running everything from the scratch :-(

Accordingly, here is the needed info:

GATK version used: 4.2.0.0  
  
openjdk version "11.0.11" 2021-04-20  
  
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)  
  
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

Command:

gatk GermlineCNVCaller \\  
  
\--run-mode COHORT \\  
  
\-L Twist\_Exome\_Target\_hg38\_preprocessed\_annotated\_gc-filtered.interval\_list \\  
  
\-imr OVERLAPPING\_ONLY \\  
  
\--contig-ploidy-calls ploidy-calls \\  
  
\--annotated-intervals Twist\_Exome\_Target\_hg38\_preprocessed\_annotated.interval\_list \\  
  
\-I 13-20.counts.hd5 \\  
  
\-I 722.counts.hd5 \\  
  
\-I D19047.counts.hd5 \\  
  
\-I F24F1.counts.hd5 \\  
  
\-I NS.counts.hd5 \\  
  
\-I TBC039.counts.hd5 \\  
  
\-I VP.counts.hd5 \\  
  
\-I WES002.counts.hd5 \\  
  
\-I WES02.counts.hd5 \\  
  
\-I 17062-T1-.counts.hd5 \\  
  
\-I 18001-M1-.counts.hd5 \\  
  
\-I 516.counts.hd5 \\  
  
\-I 533.counts.hd5 \\  
  
\-I NBH.counts.hd5 \\  
  
\-I ADN492.counts.hd5 \\  
  
\-I WES607.counts.hd5 \\  
  
\--class-coherence-length 1000.0 \\  
  
\--cnv-coherence-length 1000.0 \\  
  
\--enable-bias-factors true \\  
  
\--interval-psi-scale 1.0E-6 \\  
  
\--log-mean-bias-standard-deviation 0.01 \\  
  
\--sample-psi-scale 1.0E-6 \\  
  
\--output cohort16 \\  
  
\--output-prefix cohort16 \\  
  
\--verbosity DEBUG \\  
  
\--java-options '-DGATK\_STACKTRACE\_ON\_USER\_EXCEPTION=true'

Error:

java.lang.IllegalArgumentException: Prefix string "NS" too short: length must be at least 3  
  
at java.base/java.io.File.createTempFile(File.java:2104)  
  
at org.broadinstitute.hellbender.utils.io.IOUtils.createTempFileInDirectory(IOUtils.java:685)  
  
at org.broadinstitute.hellbender.utils.io.IOUtils.createTempFile(IOUtils.java:666)  
  
at org.broadinstitute.hellbender.tools.copynumber.GermlineCNVCaller.lambda$writeIntervalSubsetReadCountFiles$1(GermlineCNVCaller.java:430)  
  
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)  
  
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)  
  
at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)  
  
at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)  
  
at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699)  
  
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)  
  
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)  
  
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)  
  
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)  
  
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)  
  
at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)  
  
at org.broadinstitute.hellbender.tools.copynumber.GermlineCNVCaller.writeIntervalSubsetReadCountFiles(GermlineCNVCaller.java:429)  
  
at org.broadinstitute.hellbender.tools.copynumber.GermlineCNVCaller.doWork(GermlineCNVCaller.java:319)  
  
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)  
  
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)  
  
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)  
  
at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)  
  
at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)  
  
at org.broadinstitute.hellbender.Main.main(Main.java:289)

I look forward to receiving your comments.

Ahmed.<br><br><i>(created from <a href='https://broadinstitute.zendesk.com/agent/tickets/224760'>Zendesk ticket #224760</a>)<br>gz#224760</i>

**Comment by samuelklee** [comment]
Can the user check if they updated their conda/Docker environment when switching versions? The second issue is most likely being caused by changes introduced in https://github.com/broadinstitute/gatk/pull/7450.

**Comment by PamelaBretscher** [comment]
Updating the Conda environment solved the issue!
