### ISSUE TITLE
GenotypeGVCFs with the Error "Did not inflate expected amount" and "java.util.zip.DataFormatException: invalid code lengths set"

### ISSUE THREAD

**Issue by Twojarshub** [broadinstitute/gatk#7614]
Hello,

I use GATK(4.2.0.0)  HaplotypeCaller call SNPs and CombineGVCFs combining the .g.vcf files.  everything goes well.
However, when I use GenotypeGVCFs, I encounter an error [htsjdk.samtools.SAMFormatException: Did not inflate expected amount]. And I see the same Error in [#7582](https://github.com/broadinstitute/gatk/issues/7582), I try to add two parameters --use-jdk-deflater & --use-jdk-inflater, but I get the new Error [java.util.zip.DataFormatException: invalid code lengths set]

----

### Version and Tools
GATK 4.2.0.0 GenotypeGVCFs

### The commend 
java -Xmx10g -jar /home/software/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar GenotypeGVCFs --use-jdk-inflater true --use-jdk-deflater true -R ref.rename.fa -V test.vcf.gz -O test_geno.vcf.gz

### Error log 1.

21:12:43.028 INFO  GenotypeGVCFs - Shutting down engine
[2021年12月20日 下午09时12分43秒] org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 6.12 minutes.
Runtime.totalMemory()=4856479744
htsjdk.samtools.SAMFormatException: Did not inflate expected amount
	at htsjdk.samtools.util.BlockGunzipper.unzipBlock(BlockGunzipper.java:147)
	at htsjdk.samtools.util.BlockGunzipper.unzipBlock(BlockGunzipper.java:96)
	at htsjdk.samtools.util.BlockCompressedInputStream.inflateBlock(BlockCompressedInputStream.java:550)
	at htsjdk.samtools.util.BlockCompressedInputStream.processNextBlock(BlockCompressedInputStream.java:532)
	at htsjdk.samtools.util.BlockCompressedInputStream.nextBlock(BlockCompressedInputStream.java:468)
	at htsjdk.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:458)
	at htsjdk.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:196)
	at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:331)
	at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:257)
	at htsjdk.tribble.readers.PositionalBufferedStream.fill(PositionalBufferedStream.java:132)
	at htsjdk.tribble.readers.PositionalBufferedStream.read(PositionalBufferedStream.java:84)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at htsjdk.tribble.readers.LongLineBufferedReader.fill(LongLineBufferedReader.java:140)
	at htsjdk.tribble.readers.LongLineBufferedReader.readLine(LongLineBufferedReader.java:300)
	at htsjdk.tribble.readers.LongLineBufferedReader.readLine(LongLineBufferedReader.java:356)
	at htsjdk.tribble.readers.SynchronousLineReader.readLine(SynchronousLineReader.java:51)
	at htsjdk.tribble.TabixFeatureReader$FeatureIterator.readNextRecord(TabixFeatureReader.java:170)
	at htsjdk.tribble.TabixFeatureReader$FeatureIterator.next(TabixFeatureReader.java:205)
	at htsjdk.tribble.TabixFeatureReader$FeatureIterator.next(TabixFeatureReader.java:149)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:490)
	at org.broadinstitute.hellbender.engine.VariantLocusWalker.traverse(VariantLocusWalker.java:132)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1058)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)

### Error log 2.
[2021年12月20日 下午08时36分52秒] org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 7.54 minutes.
Runtime.totalMemory()=4957667328
htsjdk.samtools.util.RuntimeIOException: java.util.zip.DataFormatException: invalid code lengths set
	at htsjdk.samtools.util.BlockGunzipper.unzipBlock(BlockGunzipper.java:161)
	at htsjdk.samtools.util.BlockGunzipper.unzipBlock(BlockGunzipper.java:96)
	at htsjdk.samtools.util.BlockCompressedInputStream.inflateBlock(BlockCompressedInputStream.java:550)
	at htsjdk.samtools.util.BlockCompressedInputStream.processNextBlock(BlockCompressedInputStream.java:532)
	at htsjdk.samtools.util.BlockCompressedInputStream.nextBlock(BlockCompressedInputStream.java:468)
	at htsjdk.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:458)
	at htsjdk.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:196)
	at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:331)
	at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:257)
	at htsjdk.tribble.readers.PositionalBufferedStream.fill(PositionalBufferedStream.java:132)
	at htsjdk.tribble.readers.PositionalBufferedStream.read(PositionalBufferedStream.java:84)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at htsjdk.tribble.readers.LongLineBufferedReader.fill(LongLineBufferedReader.java:140)
	at htsjdk.tribble.readers.LongLineBufferedReader.readLine(LongLineBufferedReader.java:300)
	at htsjdk.tribble.readers.LongLineBufferedReader.readLine(LongLineBufferedReader.java:356)
	at htsjdk.tribble.readers.SynchronousLineReader.readLine(SynchronousLineReader.java:51)
	at htsjdk.tribble.TabixFeatureReader$FeatureIterator.readNextRecord(TabixFeatureReader.java:170)
	at htsjdk.tribble.TabixFeatureReader$FeatureIterator.next(TabixFeatureReader.java:205)
	at htsjdk.tribble.TabixFeatureReader$FeatureIterator.next(TabixFeatureReader.java:149)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:490)
	at org.broadinstitute.hellbender.engine.VariantLocusWalker.traverse(VariantLocusWalker.java:132)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1058)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
Caused by: java.util.zip.DataFormatException: invalid code lengths set
	at java.util.zip.Inflater.inflateBytes(Native Method)

Thanks for any help!

**Comment by lbergelson** [comment]
Hello, sorry you're having this problem.  I'm not sure exactly what's going on here.  It sounds like it's a corrupted .gz file.  You said these were created by HaplotypeCaller and then CombineGvcfs? I have a few questions and suggestions.

1.  Were there any other steps in the pipeline that touch the vcfs?
1a.  Are you sure the combine stage completed without error?  This could potentially be caused by a failure in the step beforehand that silently truncates a file.
2.  Did you run all steps of the pipeline with  --use-jdk-deflater & --use-jdk-inflate or just the final one that crashes?
3.  Can you try running PrintBGZFBlockInformation on the file and see what the output of that says?
4.  Is it reproducible on a small file you could share with us?
5.  It might be worth trying with the newest version of GATK because we upgraded to a new version of the intel deflater in 4.2.1.0 which fixed a lot of issues possibly including this one.

**Comment by greekkey** [comment]
@Twojarshub  Hi! Have you solved the problem? As I mentioned in my post, just adding "--use-jdk-inflater true --use-jdk-deflater true" in the step of GenotypeGVCFs could not solve the problem. In my case, I restarted from one step ahead (BQSR) with those options and could finish the pipelines without an error. Please try!

**Comment by lbergelson** [comment]
@greekkey I would be really interested if the problem had resolved if you ran without that option using 4.2.4.1.  We updated the compression library and I'm hoping that it's fixed whatever was causing the problem but I'm not able to reproduce it so it's hard to know.  

What OS/hardware are you running on @greekkey? I'm wondering if this is a problem on a specific OSX version or something which we're not testing on.

**Comment by greekkey** [comment]
@lbergelson OK. I will try the new version with my previous data as well as some new data later. 

My OS is Ubuntu 20.04.3 LTS 64-bit, GNOME version is 3.36.8. The major hardware info are Intel® Core™ i7-4770 CPU @ 3.40GHz × 8 , Intel® HD Graphics 4600 (HSW GT2), (memory) 31.3 GiB, (local HDD) 1.1 TB.

**Comment by lbergelson** [comment]
Thank you for the information information. That hardware seems pretty
standard. I wouldn't expect it to be causing this issue.
