### ISSUE TITLE
FuncotateSegments java.lang.IllegalArgumentException: Invalid interval in FuncotateSegments

### ISSUE THREAD

**Issue by GATKSupportTeam** [broadinstitute/gatk#7676]
This request was created from a contribution made by tc on February 09, 2022 17:49 UTC.

Link: [https://gatk.broadinstitute.org/hc/en-us/community/posts/4418364848795-java-lang-IllegalArgumentException-Invalid-interval-in-FuncotateSegments](https://gatk.broadinstitute.org/hc/en-us/community/posts/4418364848795-java-lang-IllegalArgumentException-Invalid-interval-in-FuncotateSegments)

\--

Hi,

I tried to annotated a called segment file after following the somatic CNV detection workflow of GATK:

gatk --java-options "-Xmx10g -Djava.io.tmpdir=/lscratch/$SLURM\_JOBID" FuncotateSegments \\  
  
\--data-sources-path funcotator\_dataSources.v1.7.20200521s/ \\  
  
\--ref-version hg19 \\  
  
\--output-file-format SEG \\  
  
\-R hs37d5.fa \\  
  
\--segments sample.called.seg \\  
  
\-O sample.seg.funcotated.tsv \\  
  
\--transcript-list funcotator\_dataSources.v1.7.20200521s/transcriptList.exact\_uniprot\_matches.AKT1\_CRLF2\_FGFR1.txt

But I got the following error message:

12:37:55.534 INFO  FuncotateSegments - The following datasources support funcotation on segments:   
  
12:37:55.535 INFO  FuncotateSegments -  Gencode 34 CANONICAL  
  
12:37:55.542 INFO  FuncotatorEngine - VCF sequence dictionary detected as B37 in HG19 annotation mode.  Performing conversion.  
  
12:37:55.542 WARN  FuncotatorEngine - WARNING: You are using B37 as a reference.  Funcotator will convert your variants to GRCh37, and this will be fine in the vast majority of cases.  There MAY be some errors (e.g. in the Y chromosome, but possibly in other places as well) due to changes between the two references.  
  
12:37:55.679 INFO  ProgressMeter - Starting traversal  
  
12:37:55.679 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Features Processed  Features/Minute  
  
12:37:56.198 WARN  FuncotatorUtils - Reference allele is different than the reference coding sequence (strand: -, alt = G, ref G != T reference coding seq) @\[chr1:13839497\]!  Substituting given allele for sequence code (TTC->GTC)  
  
12:37:56.213 INFO  FuncotateSegments - Shutting down engine  
  
\[February 9, 2022 12:37:56 PM EST\] org.broadinstitute.hellbender.tools.funcotator.FuncotateSegments done. Elapsed time: 0.24 minutes.  
  
Runtime.totalMemory()=3139436544  
  
java.lang.IllegalArgumentException: Invalid interval. Contig:chr1 start:29534 end:14501  
  
    at org.broadinstitute.hellbender.utils.Utils.validateArg(Utils.java:804)  
  
    at org.broadinstitute.hellbender.utils.SimpleInterval.validatePositions(SimpleInterval.java:59)  
  
    at org.broadinstitute.hellbender.utils.SimpleInterval.<init>(SimpleInterval.java:35)  
  
    at org.broadinstitute.hellbender.tools.funcotator.dataSources.gencode.segment.SegmentExonUtils.findInclusiveExonIndex(SegmentExonUtils.java:95)  
  
    at org.broadinstitute.hellbender.tools.funcotator.dataSources.gencode.segment.SegmentExonUtils.determineSegmentExonPosition(SegmentExonUtils.java:63)  
  
    at org.broadinstitute.hellbender.tools.funcotator.dataSources.gencode.GencodeFuncotationFactory.createSegmentFuncotations(GencodeFuncotationFactory.java:2938)  
  
    at org.broadinstitute.hellbender.tools.funcotator.dataSources.gencode.GencodeFuncotationFactory.createSegmentFuncotations(GencodeFuncotationFactory.java:2914)  
  
    at org.broadinstitute.hellbender.tools.funcotator.dataSources.gencode.GencodeFuncotationFactory.createFuncotationsOnSegment(GencodeFuncotationFactory.java:2866)  
  
    at org.broadinstitute.hellbender.tools.funcotator.DataSourceFuncotationFactory.determineFuncotations(DataSourceFuncotationFactory.java:239)  
  
    at org.broadinstitute.hellbender.tools.funcotator.DataSourceFuncotationFactory.createFuncotations(DataSourceFuncotationFactory.java:211)  
  
    at org.broadinstitute.hellbender.tools.funcotator.DataSourceFuncotationFactory.createFuncotations(DataSourceFuncotationFactory.java:182)  
  
    at org.broadinstitute.hellbender.tools.funcotator.FuncotatorEngine.lambda$createFuncotationMapForSegment$2(FuncotatorEngine.java:218)  
  
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)  
  
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)  
  
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)  
  
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)  
  
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)  
  
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)  
  
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)  
  
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)  
  
    at org.broadinstitute.hellbender.tools.funcotator.FuncotatorEngine.createFuncotationMapForSegment(FuncotatorEngine.java:221)  
  
    at org.broadinstitute.hellbender.tools.funcotator.FuncotateSegments.apply(FuncotateSegments.java:191)  
  
    at org.broadinstitute.hellbender.tools.funcotator.FuncotateSegments.apply(FuncotateSegments.java:59)  
  
    at org.broadinstitute.hellbender.engine.FeatureWalker.lambda$traverse$0(FeatureWalker.java:99)  
  
    at java.util.Iterator.forEachRemaining(Iterator.java:116)  
  
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)  
  
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)  
  
    at org.broadinstitute.hellbender.engine.FeatureWalker.traverse(FeatureWalker.java:97)  
  
    at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1085)  
  
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)  
  
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)  
  
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)  
  
    at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)  
  
    at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)  
  
    at org.broadinstitute.hellbender.Main.main(Main.java:289)

Here's how my called segment file looks like:

CONTIG    START    END    NUM\_POINTS\_COPY\_RATIO    MEAN\_LOG2\_COPY\_RATIO    CALL  
  
1    14645    13839497    2764    -0.121225    0  
  
1    13839498    55529537    8713    -0.060943    0  
  
1    55534430    142797736    6763    0.050711    0  
  
1    142803161    143164144    9    -1.797248    -  
  
1    143186822    156929235    3970    -0.077460    0  
  
1    156929872    224009136    8811    0.024671    0  
  
1    224116102    224116470    1    -4.545156    -  
  
1    224124170    249230997    3307    0.004490    0  
  
2    41203    137402680    14122    -0.000470    0  
  
2    137402681    215911009    8594    0.077261    0  
  
2    215914005    243081349    4299    -0.032370    0

I used GATK/4.2.4.1. Would you please kindly let me know the cause for the invalid interval error?Thanks a lot!<br><br><i>(created from <a href='https://broadinstitute.zendesk.com/agent/tickets/271141'>Zendesk ticket #271141</a>)<br> gz#271141</i>

**Comment by asalimih** [comment]
I'm having a similar issue on gatk 4.2.6.1
```
17:14:13.170 INFO  FuncotateSegments - The following datasources support funcotation on segments:
17:14:13.171 INFO  FuncotateSegments -  Gencode 34 CANONICAL
17:14:13.209 INFO  FuncotatorEngine - VCF sequence dictionary detected as B37 in HG19 annotation mode.  Performing conversion.
17:14:13.209 WARN  FuncotatorEngine - WARNING: You are using B37 as a reference.  Funcotator will convert your variants to GRCh37, and this will be fine in the vast majority of cases.  There MAY be some errors (e.g. in the Y chromosome, but possibly in other places as well) due to changes between the two references.
17:14:13.411 INFO  ProgressMeter - Starting traversal
17:14:13.412 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Features Processed  Features/Minute
17:14:15.391 INFO  FuncotateSegments - Shutting down engine
[September 11, 2022 5:14:15 PM GMT] org.broadinstitute.hellbender.tools.funcotator.FuncotateSegments done. Elapsed time: 0.30 minutes.
Runtime.totalMemory()=1752170496
java.lang.IllegalArgumentException: Invalid interval. Contig:chr1 start:917445 end:911649
        at org.broadinstitute.hellbender.utils.Utils.validateArg(Utils.java:804)
        at org.broadinstitute.hellbender.utils.SimpleInterval.validatePositions(SimpleInterval.java:59)
        at org.broadinstitute.hellbender.utils.SimpleInterval.<init>(SimpleInterval.java:35)
        at org.broadinstitute.hellbender.tools.funcotator.dataSources.gencode.segment.SegmentExonUtils.findInclusiveExonIndex(SegmentExonUtils.java:95)
        at org.broadinstitute.hellbender.tools.funcotator.dataSources.gencode.segment.SegmentExonUtils.determineSegmentExonPosition(SegmentExonUtils.java:63)
        at org.broadinstitute.hellbender.tools.funcotator.dataSources.gencode.GencodeFuncotationFactory.createSegmentFuncotations(GencodeFuncotationFactory.java:2939)
        at org.broadinstitute.hellbender.tools.funcotator.dataSources.gencode.GencodeFuncotationFactory.createSegmentFuncotations(GencodeFuncotationFactory.java:2914)
        at org.broadinstitute.hellbender.tools.funcotator.dataSources.gencode.GencodeFuncotationFactory.createFuncotationsOnSegment(GencodeFuncotationFactory.java:2866)
        at org.broadinstitute.hellbender.tools.funcotator.DataSourceFuncotationFactory.determineFuncotations(DataSourceFuncotationFactory.java:239)
        at org.broadinstitute.hellbender.tools.funcotator.DataSourceFuncotationFactory.createFuncotations(DataSourceFuncotationFactory.java:211)
        at org.broadinstitute.hellbender.tools.funcotator.DataSourceFuncotationFactory.createFuncotations(DataSourceFuncotationFactory.java:182)
        at org.broadinstitute.hellbender.tools.funcotator.FuncotatorEngine.lambda$createFuncotationMapForSegment$2(FuncotatorEngine.java:223)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at org.broadinstitute.hellbender.tools.funcotator.FuncotatorEngine.createFuncotationMapForSegment(FuncotatorEngine.java:226)
        at org.broadinstitute.hellbender.tools.funcotator.FuncotateSegments.apply(FuncotateSegments.java:191)
        at org.broadinstitute.hellbender.tools.funcotator.FuncotateSegments.apply(FuncotateSegments.java:59)
        at org.broadinstitute.hellbender.engine.FeatureWalker.lambda$traverse$0(FeatureWalker.java:99)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
        at org.broadinstitute.hellbender.engine.FeatureWalker.traverse(FeatureWalker.java:97)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1085)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
Using GATK jar /gatk/gatk-package-4.2.6.1-local.jar

```
