### ISSUE TITLE
Yet another hg19 / b37 conversion bug!

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#7761]
The automatic conversion from `b37` to `hg19` yet again has resulted in a bug:

On output of a compressed vcf (`.vcf.gz`), HTSJDK is unable to index the resulting file because the reference dictionary is valid for `b37`, but we have converted the variants to use `hg19` contigs.  These contigs are not in `b37` and a null pointer exception is thrown.  Three exceptions are actually being thrown, but this is the output stack trace:

```
java.lang.NullPointerException
	at htsjdk.tribble.index.tabix.TabixIndexCreator.finalizeFeature(TabixIndexCreator.java:106)
	at htsjdk.tribble.index.tabix.TabixIndexCreator.finalizeIndex(TabixIndexCreator.java:129)
	at htsjdk.variant.variantcontext.writer.IndexingVariantContextWriter.close(IndexingVariantContextWriter.java:177)
	at htsjdk.variant.variantcontext.writer.VCFWriter.close(VCFWriter.java:233)
	at org.broadinstitute.hellbender.tools.funcotator.vcfOutput.VcfOutputRenderer.close(VcfOutputRenderer.java:137)
	at org.broadinstitute.hellbender.tools.funcotator.Funcotator.closeTool(Funcotator.java:893)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1064)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

To fix this we must put a "reverse transformer" in to put the variants back into the basis of `b37` on output.  This should happen for both `VCF` and `MAF` output so it is consistent.  Many of our tests will have to change to accommodate this, and this is a bandaid for the real fix (which is just having a separate datasource for `b37` in the first place).

**Comment by jonn-smith** [comment]
It's worth noting that the "true" fix for this is to have distinct datasources for each reference.  In this case, two sets of datasources - one for B37 and one for HG19 - would be needed.

**Comment by shengqh** [comment]
> It's worth noting that the "true" fix for this is to have distinct datasources for each reference. In this case, two sets of datasources - one for B37 and one for HG19 - would be needed.

Do you have any plan to providing B37 data source? We are using BROAD B37 in our pipeline but Funcotator didn't work.
