### ISSUE TITLE
GatherTranches fails due to what seems like an integer overflow

### ISSUE THREAD

**Issue by LindoNkambule** [broadinstitute/gatk#7859]
### Affected tool(s) or class(es)
GatherTranches

### Affected version(s)
Latest public release version 4.2.6.1

### Description 
I ran `VariantRecalibrator` in scattered (using intervals) mode and now trying to gather the scattered tranches into a single file but somehow the number of novel variants is < 0. This is the exact error:
`Invalid tranche - no. variants is < 0 : known 90357410 novel -1894637320`

#### Steps to reproduce
```
inputs_cmdl = ' '.join([f'--input {t}' for t in tranches])
j.command(
        f"""set -euo pipefail
        gatk --java-options -Xms6g \\
          GatherTranches \\
          --mode SNP \\
          {inputs_cmdl} \\
          --output {j.out_tranches}"""
)
```

#### Expected behavior
Gathered scattered VQSLOD tranches into a single file

#### Actual behavior
Fails because of what seems like an integer overflow according to @ldgauthier
```
org.broadinstitute.hellbender.exceptions.GATKException: Invalid tranche - no. variants is < 0 : known 90357410 novel -1894637320
	at org.broadinstitute.hellbender.tools.walkers.vqsr.Tranche.<init>(Tranche.java:37)
	at org.broadinstitute.hellbender.tools.walkers.vqsr.VQSLODTranche.<init>(VQSLODTranche.java:37)
	at org.broadinstitute.hellbender.tools.walkers.vqsr.VQSLODTranche.mergeAndConvertTranches(VQSLODTranche.java:205)
	at org.broadinstitute.hellbender.tools.walkers.vqsr.VQSLODTranche.mergeAndConvertTranches(VQSLODTranche.java:139)
	at org.broadinstitute.hellbender.tools.walkers.vqsr.GatherTranches.doWork(GatherTranches.java:80)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
```
----

### Description 
Use a data type like `long` that can store larger values instead of `int` ?

**Comment by droazen** [comment]
@LindoNkambule For your dataset, do you expect an extremely large number of novel variants (on the order of 2 billion+)? How many total variants are in your dataset?

@ldgauthier Have you ever encountered an error like this?

**Comment by droazen** [comment]
(Never mind -- I see that there is already a proposed PR to fix this!)
