### ISSUE TITLE
FilterFuncotations Error, ShouldNeverReachHereException, FuncotationMap

### ISSUE THREAD

**Issue by GATKSupportTeam** [broadinstitute/gatk#7865]
This request was created from a contribution made by Joyce Anon on April 25, 2022 06:30 UTC.

Link: [https://gatk.broadinstitute.org/hc/en-us/community/posts/5573282748699-Error-ShouldNeverReachHereException-FuncotationMap-in-FilterFuncotations](https://gatk.broadinstitute.org/hc/en-us/community/posts/5573282748699-Error-ShouldNeverReachHereException-FuncotationMap-in-FilterFuncotations)

\--

FilterFuncotations stops with an error. The input file with the reference genome seems to pass ValidateVariants (no errors). It looks like "FuncotationMap" doesn't have enough values to go with the keys. I started with a .vcf file downloaded from Nebula Genomics, and sequentially used CNNScoreVariants, FilterVariantTranches (CNN\_1D), and Funcotator, with default settings.

I am trying to find the most pathogenic variants. I considered using FilterVcf to remove synonymous and intron variants, but it doesn't look like it can do that. So then I tried FilterFuncotations, but it returns an error. What I want is some way to sort the variants by severity, to find the most pathogenic ones, but I don't know how to do that.

GATK version: 4.2.6.1  
  
Java runtime: OpenJDK 64-Bit Server VM v11.0.14.1+1-Ubuntu-0ubuntu1.20.04

Excerpt:  
  
\[April 25, 2022 at 2:00:35 AM EDT\] org.broadinstitute.hellbender.tools.funcotator.FilterFuncotations done. Elapsed time: 0.03 minutes.  
  
Runtime.totalMemory()=319815680  
  
org.broadinstitute.hellbender.exceptions.GATKException$ShouldNeverReachHereException: Cannot parse the funcotation attribute.  Num values: 31   Num keys: 53

Copied from the terminal:  
  
(gatk) aru@BioinformaticsVM:/mnt/sdb/gatk$ ./gatk FilterFuncotations --allele-frequency-data-source gnomad -O ./output/nebulaFilterFuncotations.vcf --ref-version hg38 -V ./output/nebulaFuncotatorAnnotated.vcf --java-options '-DGATK\_STACKTRACE\_ON\_USER\_EXCEPTION=true'  
  
Using GATK jar /mnt/sdb/gatk/gatk-package-4.2.6.1-local.jar  
  
Running:  
  
    java -Dsamjdk.use\_async\_io\_read\_samtools=false -Dsamjdk.use\_async\_io\_write\_samtools=true -Dsamjdk.use\_async\_io\_write\_tribble=false -Dsamjdk.compression\_level=2 -DGATK\_STACKTRACE\_ON\_USER\_EXCEPTION=true -jar /mnt/sdb/gatk/gatk-package-4.2.6.1-local.jar FilterFuncotations --allele-frequency-data-source gnomad -O ./output/nebulaFilterFuncotations.vcf --ref-version hg38 -V ./output/nebulaFuncotatorAnnotated.vcf  
  
02:00:34.173 INFO  NativeLibraryLoader - Loading libgkl\_compression.so from jar:file:/mnt/sdb/gatk/gatk-package-4.2.6.1-local.jar!/com/intel/gkl/native/libgkl\_compression.so  
  
02:00:34.368 INFO  FilterFuncotations - ------------------------------------------------------------  
  
02:00:34.369 INFO  FilterFuncotations - The Genome Analysis Toolkit (GATK) v4.2.6.1  
  
02:00:34.369 INFO  FilterFuncotations - For support and documentation go to [https://software.broadinstitute.org/gatk/](https://software.broadinstitute.org/gatk/)  
  
02:00:34.369 INFO  FilterFuncotations - Executing as aru@BioinformaticsVM on Linux v5.13.0-39-generic amd64  
  
02:00:34.369 INFO  FilterFuncotations - Java runtime: OpenJDK 64-Bit Server VM v11.0.14.1+1-Ubuntu-0ubuntu1.20.04  
  
02:00:34.369 INFO  FilterFuncotations - Start Date/Time: April 25, 2022 at 2:00:34 AM EDT  
  
02:00:34.369 INFO  FilterFuncotations - ------------------------------------------------------------  
  
02:00:34.369 INFO  FilterFuncotations - ------------------------------------------------------------  
  
02:00:34.370 INFO  FilterFuncotations - HTSJDK Version: 2.24.1  
  
02:00:34.371 INFO  FilterFuncotations - Picard Version: 2.27.1  
  
02:00:34.371 INFO  FilterFuncotations - Built for Spark Version: 2.4.5  
  
02:00:34.371 INFO  FilterFuncotations - HTSJDK Defaults.COMPRESSION\_LEVEL : 2  
  
02:00:34.371 INFO  FilterFuncotations - HTSJDK Defaults.USE\_ASYNC\_IO\_READ\_FOR\_SAMTOOLS : false  
  
02:00:34.371 INFO  FilterFuncotations - HTSJDK Defaults.USE\_ASYNC\_IO\_WRITE\_FOR\_SAMTOOLS : true  
  
02:00:34.371 INFO  FilterFuncotations - HTSJDK Defaults.USE\_ASYNC\_IO\_WRITE\_FOR\_TRIBBLE : false  
  
02:00:34.371 INFO  FilterFuncotations - Deflater: IntelDeflater  
  
02:00:34.371 INFO  FilterFuncotations - Inflater: IntelInflater  
  
02:00:34.371 INFO  FilterFuncotations - GCS max retries/reopens: 20  
  
02:00:34.371 INFO  FilterFuncotations - Requester pays: disabled  
  
02:00:34.372 WARN  FilterFuncotations - 

   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

   Warning: FilterFuncotations is an EXPERIMENTAL tool and should not be used for production

   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

02:00:34.372 INFO  FilterFuncotations - Initializing engine  
  
02:00:34.518 INFO  FeatureManager - Using codec VCFCodec to read file file:///mnt/sdb/gatk/./output/nebulaFuncotatorAnnotated.vcf  
  
02:00:34.815 INFO  FilterFuncotations - Done initializing engine  
  
02:00:35.260 INFO  ProgressMeter - Starting traversal  
  
02:00:35.261 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute  
  
02:00:35.262 INFO  FilterFuncotations - Starting pass 0 through the variants  
  
02:00:35.778 ERROR FuncotationMap - Keys:  Gencode\_34\_hugoSymbol, Gencode\_34\_ncbiBuild, Gencode\_34\_chromosome, Gencode\_34\_start, Gencode\_34\_end, Gencode\_34\_variantClassification, Gencode\_34\_secondaryVariantClassification, Gencode\_34\_variantType, Gencode\_34\_refAllele, Gencode\_34\_tumorSeqAllele1, Gencode\_34\_tumorSeqAllele2, Gencode\_34\_genomeChange, Gencode\_34\_annotationTranscript, Gencode\_34\_transcriptStrand, Gencode\_34\_transcriptExon, Gencode\_34\_transcriptPos, Gencode\_34\_cDnaChange, Gencode\_34\_codonChange, Gencode\_34\_proteinChange, Gencode\_34\_gcContent, Gencode\_34\_referenceContext, Gencode\_34\_otherTranscripts, ACMGLMMLof\_LOF\_Mechanism, ACMGLMMLof\_Mode\_of\_Inheritance, ACMGLMMLof\_Notes, ACMG\_recommendation\_Disease\_Name, ClinVar\_VCF\_AF\_ESP, ClinVar\_VCF\_AF\_EXAC, ClinVar\_VCF\_AF\_TGP, ClinVar\_VCF\_ALLELEID, ClinVar\_VCF\_CLNDISDB, ClinVar\_VCF\_CLNDISDBINCL, ClinVar\_VCF\_CLNDN, ClinVar\_VCF\_CLNDNINCL, ClinVar\_VCF\_CLNHGVS, ClinVar\_VCF\_CLNREVSTAT, ClinVar\_VCF\_CLNSIG, ClinVar\_VCF\_CLNSIGCONF, ClinVar\_VCF\_CLNSIGINCL, ClinVar\_VCF\_CLNVC, ClinVar\_VCF\_CLNVCSO, ClinVar\_VCF\_CLNVI, ClinVar\_VCF\_DBVARID, ClinVar\_VCF\_GENEINFO, ClinVar\_VCF\_MC, ClinVar\_VCF\_ORIGIN, ClinVar\_VCF\_RS, ClinVar\_VCF\_SSR, ClinVar\_VCF\_ID, ClinVar\_VCF\_FILTER, LMMKnown\_LMM\_FLAGGED, LMMKnown\_ID, LMMKnown\_FILTER  
  
02:00:35.778 ERROR FuncotationMap - Values:  , , , , , , , , , , , , , , , , , , , , , , , , , , , , false, ,   
  
02:00:35.793 INFO  FilterFuncotations - Shutting down engine  
  
\[April 25, 2022 at 2:00:35 AM EDT\] org.broadinstitute.hellbender.tools.funcotator.FilterFuncotations done. Elapsed time: 0.03 minutes.  
  
Runtime.totalMemory()=319815680  
  
org.broadinstitute.hellbender.exceptions.GATKException$ShouldNeverReachHereException: Cannot parse the funcotation attribute.  Num values: 31   Num keys: 53  
  
    at org.broadinstitute.hellbender.tools.funcotator.FuncotationMap.createAsAllTableFuncotationsFromVcf(FuncotationMap.java:224)  
  
    at org.broadinstitute.hellbender.tools.funcotator.FuncotatorUtils.lambda$createAlleleToFuncotationMapFromFuncotationVcfAttribute$5(FuncotatorUtils.java:2256)  
  
    at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:178)  
  
    at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)  
  
    at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)  
  
    at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)  
  
    at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699)  
  
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)  
  
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)  
  
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)  
  
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)  
  
    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)  
  
    at org.broadinstitute.hellbender.tools.funcotator.FuncotatorUtils.createAlleleToFuncotationMapFromFuncotationVcfAttribute(FuncotatorUtils.java:2255)  
  
    at org.broadinstitute.hellbender.tools.funcotator.filtrationRules.ArHetvarFilter.buildArHetByGene(ArHetvarFilter.java:77)  
  
    at org.broadinstitute.hellbender.tools.funcotator.filtrationRules.ArHetvarFilter.firstPassApply(ArHetvarFilter.java:50)  
  
    at org.broadinstitute.hellbender.tools.funcotator.FilterFuncotations.firstPassApply(FilterFuncotations.java:161)  
  
    at org.broadinstitute.hellbender.engine.TwoPassVariantWalker.nthPassApply(TwoPassVariantWalker.java:17)  
  
    at org.broadinstitute.hellbender.engine.MultiplePassVariantWalker.lambda$traverse$0(MultiplePassVariantWalker.java:40)  
  
    at org.broadinstitute.hellbender.engine.MultiplePassVariantWalker.lambda$traverseVariants$1(MultiplePassVariantWalker.java:77)  
  
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)  
  
    at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)  
  
    at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)  
  
    at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)  
  
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)  
  
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)  
  
    at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)  
  
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)  
  
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)  
  
    at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)  
  
    at org.broadinstitute.hellbender.engine.MultiplePassVariantWalker.traverseVariants(MultiplePassVariantWalker.java:75)  
  
    at org.broadinstitute.hellbender.engine.MultiplePassVariantWalker.traverse(MultiplePassVariantWalker.java:40)  
  
    at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1085)  
  
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)  
  
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)  
  
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)  
  
    at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)  
  
    at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)  
  
    at org.broadinstitute.hellbender.Main.main(Main.java:289)<br><br><i>(created from <a href='https://broadinstitute.zendesk.com/agent/tickets/282401'>Zendesk ticket #282401</a>)<br> gz#282401</i>

**Comment by droazen** [comment]
@GATKSupportTeam Can you ask the user to provide an example `FUNCOTATION` attribute from their VCF? This error indicates that one or more of the FUNCOTATION attributes are malformed, so it would help to be able to inspect one.

**Comment by gbrandt6** [comment]
Yes, I have asked the user to upload their data for testing.

**Comment by gbrandt6** [comment]
Yes, I got the data today.

**Comment by gbrandt6** [comment]
The user's uploaded data is named Joyce1NebulaFuncotatorAnnotated.vcf and Joyce1NebulaFuncotatorAnnotated.vcf.idx.
