### ISSUE TITLE
GenotypeGVCFs stuck at Starting traversal for coulple of days!!!

### ISSUE THREAD

**Issue by Bowen1992** [broadinstitute/gatk#7866]
### Instructions

The github issue tracker is for bug reports, feature requests, and API documentation requests. General questions about how to use the GATK, how to interpret the output, etc. should be asked on the [official support forum](http://gatkforums.broadinstitute.org/gatk).
- Search the existing github issues to see if your issue (or something similar) has already been reported.  If the issue already exists, you may comment there to inquire about the progress.
- Determine whether your issue is a **bug report**, a **feature request**, or a **documentation request** (for tool/class javadoc only -- for forum docs please post there)
- Consider if your "issue" is better addressed on the GATK forum: http://gatkforums.broadinstitute.org/gatk  Post there if you have questions about expected tool behavior, output format, unexpected results, or generally any question that does not fit into the categories above
- Use a **concise** yet **descriptive** title
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate
- Delete the other template blocks and this header.

----

### Affected tool(s) or class(es)
_Tool/class name(s), special parameters?_

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._
**GenotypeGVCFs stuck at Starting traversal for coulple of days:**

Using GATK jar /public/software/apps/gatk/gatk-4.1.9.0/gatk-package-4.1.9.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx50G -Djava.io.tmpdir=./tmp -jar /public/software/apps/gatk/gatk-4.1.9.0/gatk-package-4.1.9.0-local.jar GenotypeGVCFs -R /public/home/gaoshibin/B73_REF/Zea_mays.AGPv4.dna.toplevel.fa -V gendb://./CHR4_gvcf_database -G StandardAnnotation -O fat_ALL_MATERIALS_chr4.g.vcf.gz
11:58:13.194 WARN  GATKAnnotationPluginDescriptor - Redundant enabled annotation group (StandardAnnotation) is enabled for this tool by default
11:58:14.522 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/public/software/apps/gatk/gatk-4.1.9.0/gatk-package-4.1.9.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
May 20, 2022 11:58:19 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
11:58:19.059 INFO  GenotypeGVCFs - ------------------------------------------------------------
11:58:19.060 INFO  GenotypeGVCFs - The Genome Analysis Toolkit (GATK) v4.1.9.0
11:58:19.060 INFO  GenotypeGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
11:58:19.060 INFO  GenotypeGVCFs - Executing as gaoshibin@fat1 on Linux v3.10.0-693.el7.x86_64 amd64
11:58:19.060 INFO  GenotypeGVCFs - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_211-b12
11:58:19.060 INFO  GenotypeGVCFs - Start Date/Time: 2022年5月20日 上午11时58分13秒
11:58:19.060 INFO  GenotypeGVCFs - ------------------------------------------------------------
11:58:19.060 INFO  GenotypeGVCFs - ------------------------------------------------------------
11:58:19.061 INFO  GenotypeGVCFs - HTSJDK Version: 2.23.0
11:58:19.061 INFO  GenotypeGVCFs - Picard Version: 2.23.3
11:58:19.061 INFO  GenotypeGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2
11:58:19.061 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
11:58:19.061 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
11:58:19.061 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
11:58:19.061 INFO  GenotypeGVCFs - Deflater: IntelDeflater
11:58:19.061 INFO  GenotypeGVCFs - Inflater: IntelInflater
11:58:19.062 INFO  GenotypeGVCFs - GCS max retries/reopens: 20
11:58:19.062 INFO  GenotypeGVCFs - Requester pays: disabled
11:58:19.062 INFO  GenotypeGVCFs - Initializing engine
11:58:27.760 INFO  GenomicsDBLibLoader - GenomicsDB native library version : 1.3.2-e18fa63
12:26:28.692 info  NativeGenomicsDB - pid=228304 tid=228306 No valid combination operation found for INFO field InbreedingCoeff  - the field will NOT be part of INFO fields in the generated VCF records
12:26:28.734 info  NativeGenomicsDB - pid=228304 tid=228306 No valid combination operation found for INFO field MLEAC  - the field will NOT be part of INFO fields in the generated VCF records
12:26:28.734 info  NativeGenomicsDB - pid=228304 tid=228306 No valid combination operation found for INFO field MLEAF  - the field will NOT be part of INFO fields in the generated VCF records
12:57:29.524 INFO  GenotypeGVCFs - Done initializing engine
12:57:32.773 INFO  ProgressMeter - Starting traversal
12:57:32.773 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute

#### Steps to reproduce
_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem. (The support team may follow up to ask you to upload data to reproduce the issue.)_

#### Expected behavior
_Tell us what should happen_

#### Actual behavior
_Tell us what happens instead_

----

### Tool(s) or class(es) involved
_Tool/class name(s), special parameters?_

### Description
_Specify whether you want a modification of an existing behavior or addition of a new capability._
_Provide **examples**, **screenshots**, where appropriate._

----

### Tool(s) or class(es) involved
_Tool/class name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

**Comment by droazen** [comment]
@Bowen1992 Could you please try running with the latest GATK release (`4.2.6.1`) and reporting whether the issue persists?

**Comment by Bowen1992** [comment]
I tried the latest GATK release and also reported errors.
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx50G -Djava.io.tmpdir=./tmp -jar /public/home/gaoshibin/software/GATK/gatk-4.2.6.1/gatk-package-4.2.6.1-local.jar GenotypeGVCFs -R /public/home/gaoshibin/B73_REF/Zea_mays.AGPv4.dna.toplevel.fa -V gendb://./CHR7_gvcf_database -G StandardAnnotation --genomicsdb-shared-posixfs-optimizations true -O new_ALL_MATERIALS_chr7.g.vcf.gz
17:49:50.404 WARN  GATKAnnotationPluginDescriptor - Redundant enabled annotation group (StandardAnnotation) is enabled for this tool by default
17:49:50.653 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/public/home/gaoshibin/software/GATK/gatk-4.2.6.1/gatk-package-4.2.6.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
17:49:51.271 INFO  GenotypeGVCFs - ------------------------------------------------------------
17:49:51.273 INFO  GenotypeGVCFs - The Genome Analysis Toolkit (GATK) v4.2.6.1
17:49:51.273 INFO  GenotypeGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
17:49:51.273 INFO  GenotypeGVCFs - Executing as gaoshibin@comput6 on Linux v3.10.0-693.el7.x86_64 amd64
17:49:51.274 INFO  GenotypeGVCFs - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_211-b12
17:49:51.274 INFO  GenotypeGVCFs - Start Date/Time: 2022年5月22日 下午05时49分50秒
17:49:51.274 INFO  GenotypeGVCFs - ------------------------------------------------------------
17:49:51.275 INFO  GenotypeGVCFs - ------------------------------------------------------------
17:49:51.276 INFO  GenotypeGVCFs - HTSJDK Version: 2.24.1
17:49:51.276 INFO  GenotypeGVCFs - Picard Version: 2.27.1
17:49:51.276 INFO  GenotypeGVCFs - Built for Spark Version: 2.4.5
17:49:51.277 INFO  GenotypeGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2
17:49:51.277 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
17:49:51.277 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
17:49:51.277 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
17:49:51.278 INFO  GenotypeGVCFs - Deflater: IntelDeflater
17:49:51.278 INFO  GenotypeGVCFs - Inflater: IntelInflater
17:49:51.278 INFO  GenotypeGVCFs - GCS max retries/reopens: 20
17:49:51.278 INFO  GenotypeGVCFs - Requester pays: disabled
17:49:51.278 INFO  GenotypeGVCFs - Initializing engine
17:49:52.385 INFO  GenomicsDBLibLoader - GenomicsDB native library version : 1.4.3-6069e4a
17:52:35.478 info  NativeGenomicsDB - pid=66560 tid=66565 No valid combination operation found for INFO field InbreedingCoeff  - the field will NOT be part of INFO fields in the generated VCF records
17:52:35.487 info  NativeGenomicsDB - pid=66560 tid=66565 No valid combination operation found for INFO field MLEAC  - the field will NOT be part of INFO fields in the generated VCF records
17:52:35.487 info  NativeGenomicsDB - pid=66560 tid=66565 No valid combination operation found for INFO field MLEAF  - the field will NOT be part of INFO fields in the generated VCF records
17:55:56.179 INFO  GenotypeGVCFs - Done initializing engine
17:55:56.692 INFO  ProgressMeter - Starting traversal
17:55:56.704 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
07:43:39.738 INFO  ProgressMeter -               7:1067           2267.7                  1000              0.4
07:44:22.642 INFO  ProgressMeter -               7:2069           2268.4                  2000              0.9
07:45:48.820 INFO  GenotypeGVCFs - Shutting down engine
GENOMICSDB_TIMER,GenomicsDB iterator next() timer,Wall-clock time(s),6.764015676999995,Cpu time(s),6.525572708
[2022年5月24日 上午07时45分51秒] org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 2,276.03 minutes.
Runtime.totalMemory()=2278555648
java.lang.IllegalStateException: Genotype has no likelihoods: [CAU-SICAU-Y1035 A*/T GQ 80 DP 10]
        at org.broadinstitute.hellbender.utils.GenotypeUtils.computeDiploidGenotypeCounts(GenotypeUtils.java:89)
        at org.broadinstitute.hellbender.tools.walkers.annotator.ExcessHet.calculateEH(ExcessHet.java:96)
        at org.broadinstitute.hellbender.tools.walkers.annotator.ExcessHet.annotate(ExcessHet.java:84)
        at org.broadinstitute.hellbender.tools.walkers.annotator.VariantAnnotatorEngine.addInfoAnnotations(VariantAnnotatorEngine.java:355)
        at org.broadinstitute.hellbender.tools.walkers.annotator.VariantAnnotatorEngine.annotateContext(VariantAnnotatorEngine.java:334)
        at org.broadinstitute.hellbender.tools.walkers.annotator.VariantAnnotatorEngine.annotateContext(VariantAnnotatorEngine.java:306)
        at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFsEngine.regenotypeVC(GenotypeGVCFsEngine.java:185)
        at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFsEngine.callRegion(GenotypeGVCFsEngine.java:135)
        at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.apply(GenotypeGVCFs.java:283)
        at org.broadinstitute.hellbender.engine.VariantLocusWalker.lambda$traverse$0(VariantLocusWalker.java:135)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
        at org.broadinstitute.hellbender.engine.VariantLocusWalker.traverse(VariantLocusWalker.java:132)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1085)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)

**Comment by yeyun1999** [comment]
@Bowen1992 **I got the same error, do you have a solution now?**

Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx76800m -jar /home/zwc1988/miniconda3/envs/gatk/share/gatk4-4.2.6.1-0/gatk-package-4.2.6.1-local.jar GenotypeGVCFs -R data/ref/CL200105941_L02.fa -V gendb://results/genotype/genodb/group2 -O results/genotype/vcfs/group2.vcf.gz --tmp-dir ./tmp
18:24:10.205 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/zwc1988/miniconda3/envs/gatk/share/gatk4-4.2.6.1-0/gatk-package-4.2.6.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
18:24:10.451 INFO  GenotypeGVCFs - ------------------------------------------------------------
18:24:10.452 INFO  GenotypeGVCFs - The Genome Analysis Toolkit (GATK) v4.2.6.1
18:24:10.452 INFO  GenotypeGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
18:24:10.452 INFO  GenotypeGVCFs - Executing as zwc1988@fat01 on Linux v3.10.0-957.el7.x86_64 amd64
18:24:10.453 INFO  GenotypeGVCFs - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_312-b07
18:24:10.453 INFO  GenotypeGVCFs - Start Date/Time: June 19, 2022 6:24:10 PM CST
18:24:10.453 INFO  GenotypeGVCFs - ------------------------------------------------------------
18:24:10.453 INFO  GenotypeGVCFs - ------------------------------------------------------------
18:24:10.454 INFO  GenotypeGVCFs - HTSJDK Version: 2.24.1
18:24:10.454 INFO  GenotypeGVCFs - Picard Version: 2.27.1
18:24:10.454 INFO  GenotypeGVCFs - Built for Spark Version: 2.4.5
18:24:10.454 INFO  GenotypeGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2
18:24:10.455 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
18:24:10.455 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
18:24:10.455 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
18:24:10.455 INFO  GenotypeGVCFs - Deflater: IntelDeflater
18:24:10.455 INFO  GenotypeGVCFs - Inflater: IntelInflater
18:24:10.455 INFO  GenotypeGVCFs - GCS max retries/reopens: 20
18:24:10.455 INFO  GenotypeGVCFs - Requester pays: disabled
18:24:10.456 INFO  GenotypeGVCFs - Initializing engine
18:24:13.851 INFO  GenomicsDBLibLoader - GenomicsDB native library version : 1.4.3-6069e4a
18:24:15.434 info  NativeGenomicsDB - pid=225671 tid=225691 No valid combination operation found for INFO field InbreedingCoeff  - the field will NOT be part of INFO fields in the generated VCF records
18:24:15.434 info  NativeGenomicsDB - pid=225671 tid=225691 No valid combination operation found for INFO field MLEAC  - the field will NOT be part of INFO fields in the generated VCF records
18:24:15.434 info  NativeGenomicsDB - pid=225671 tid=225691 No valid combination operation found for INFO field MLEAF  - the field will NOT be part of INFO fields in the generated VCF records
18:24:15.434 info  NativeGenomicsDB - pid=225671 tid=225691 No valid combination operation found for INFO field AC  - the field will NOT be part of INFO fields in the generated VCF records
18:24:15.434 info  NativeGenomicsDB - pid=225671 tid=225691 No valid combination operation found for INFO field AF  - the field will NOT be part of INFO fields in the generated VCF records
18:24:15.434 info  NativeGenomicsDB - pid=225671 tid=225691 No valid combination operation found for INFO field AN  - the field will NOT be part of INFO fields in the generated VCF records
18:24:15.434 info  NativeGenomicsDB - pid=225671 tid=225691 No valid combination operation found for INFO field FS  - the field will NOT be part of INFO fields in the generated VCF records
18:24:15.435 info  NativeGenomicsDB - pid=225671 tid=225691 No valid combination operation found for INFO field QD  - the field will NOT be part of INFO fields in the generated VCF records
18:24:15.435 info  NativeGenomicsDB - pid=225671 tid=225691 No valid combination operation found for INFO field SOR  - the field will NOT be part of INFO fields in the generated VCF records
18:24:22.489 INFO  GenotypeGVCFs - Done initializing engine
18:24:24.770 INFO  ProgressMeter - Starting traversal
18:24:24.771 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
18:25:30.829 INFO  GenotypeGVCFs - Shutting down engine
GENOMICSDB_TIMER,GenomicsDB iterator next() timer,Wall-clock time(s),0.055026962999999963,Cpu time(s),0.049579712000000026
[June 19, 2022 6:25:30 PM CST] org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 1.35 minutes.
Runtime.totalMemory()=3063414784
java.lang.IllegalStateException: Genotype has no likelihoods: [10 G/G GQ 15 DP 5]
	at org.broadinstitute.hellbender.utils.GenotypeUtils.computeDiploidGenotypeCounts(GenotypeUtils.java:89)
	at org.broadinstitute.hellbender.tools.walkers.annotator.ExcessHet.calculateEH(ExcessHet.java:96)
	at org.broadinstitute.hellbender.tools.walkers.annotator.ExcessHet.annotate(ExcessHet.java:84)
	at org.broadinstitute.hellbender.tools.walkers.annotator.VariantAnnotatorEngine.addInfoAnnotations(VariantAnnotatorEngine.java:355)
	at org.broadinstitute.hellbender.tools.walkers.annotator.VariantAnnotatorEngine.annotateContext(VariantAnnotatorEngine.java:334)
	at org.broadinstitute.hellbender.tools.walkers.annotator.VariantAnnotatorEngine.annotateContext(VariantAnnotatorEngine.java:306)
	at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFsEngine.regenotypeVC(GenotypeGVCFsEngine.java:185)
	at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFsEngine.callRegion(GenotypeGVCFsEngine.java:135)
	at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.apply(GenotypeGVCFs.java:283)
	at org.broadinstitute.hellbender.engine.VariantLocusWalker.lambda$traverse$0(VariantLocusWalker.java:135)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:490)
	at org.broadinstitute.hellbender.engine.VariantLocusWalker.traverse(VariantLocusWalker.java:132)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1085)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)

**Comment by kuaileshizuihao** [comment]
> I tried the latest GATK release and also reported errors. Running: java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx50G -Djava.io.tmpdir=./tmp -jar /public/home/gaoshibin/software/GATK/gatk-4.2.6.1/gatk-package-4.2.6.1-local.jar GenotypeGVCFs -R /public/home/gaoshibin/B73_REF/Zea_mays.AGPv4.dna.toplevel.fa -V gendb://./CHR7_gvcf_database -G StandardAnnotation --genomicsdb-shared-posixfs-optimizations true -O new_ALL_MATERIALS_chr7.g.vcf.gz 17:49:50.404 WARN GATKAnnotationPluginDescriptor - Redundant enabled annotation group (StandardAnnotation) is enabled for this tool by default 17:49:50.653 INFO NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/public/home/gaoshibin/software/GATK/gatk-4.2.6.1/gatk-package-4.2.6.1-local.jar!/com/intel/gkl/native/libgkl_compression.so 17:49:51.271 INFO GenotypeGVCFs - ------------------------------------------------------------ 17:49:51.273 INFO GenotypeGVCFs - The Genome Analysis Toolkit (GATK) v4.2.6.1 17:49:51.273 INFO GenotypeGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/ 17:49:51.273 INFO GenotypeGVCFs - Executing as gaoshibin@comput6 on Linux v3.10.0-693.el7.x86_64 amd64 17:49:51.274 INFO GenotypeGVCFs - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_211-b12 17:49:51.274 INFO GenotypeGVCFs - Start Date/Time: 2022年5月22日 下午05时49分50秒 17:49:51.274 INFO GenotypeGVCFs - ------------------------------------------------------------ 17:49:51.275 INFO GenotypeGVCFs - ------------------------------------------------------------ 17:49:51.276 INFO GenotypeGVCFs - HTSJDK Version: 2.24.1 17:49:51.276 INFO GenotypeGVCFs - Picard Version: 2.27.1 17:49:51.276 INFO GenotypeGVCFs - Built for Spark Version: 2.4.5 17:49:51.277 INFO GenotypeGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2 17:49:51.277 INFO GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false 17:49:51.277 INFO GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true 17:49:51.277 INFO GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false 17:49:51.278 INFO GenotypeGVCFs - Deflater: IntelDeflater 17:49:51.278 INFO GenotypeGVCFs - Inflater: IntelInflater 17:49:51.278 INFO GenotypeGVCFs - GCS max retries/reopens: 20 17:49:51.278 INFO GenotypeGVCFs - Requester pays: disabled 17:49:51.278 INFO GenotypeGVCFs - Initializing engine 17:49:52.385 INFO GenomicsDBLibLoader - GenomicsDB native library version : 1.4.3-6069e4a 17:52:35.478 info NativeGenomicsDB - pid=66560 tid=66565 No valid combination operation found for INFO field InbreedingCoeff - the field will NOT be part of INFO fields in the generated VCF records 17:52:35.487 info NativeGenomicsDB - pid=66560 tid=66565 No valid combination operation found for INFO field MLEAC - the field will NOT be part of INFO fields in the generated VCF records 17:52:35.487 info NativeGenomicsDB - pid=66560 tid=66565 No valid combination operation found for INFO field MLEAF - the field will NOT be part of INFO fields in the generated VCF records 17:55:56.179 INFO GenotypeGVCFs - Done initializing engine 17:55:56.692 INFO ProgressMeter - Starting traversal 17:55:56.704 INFO ProgressMeter - Current Locus Elapsed Minutes Variants Processed Variants/Minute 07:43:39.738 INFO ProgressMeter - 7:1067 2267.7 1000 0.4 07:44:22.642 INFO ProgressMeter - 7:2069 2268.4 2000 0.9 07:45:48.820 INFO GenotypeGVCFs - Shutting down engine GENOMICSDB_TIMER,GenomicsDB iterator next() timer,Wall-clock time(s),6.764015676999995,Cpu time(s),6.525572708 [2022年5月24日 上午07时45分51秒] org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 2,276.03 minutes. Runtime.totalMemory()=2278555648 java.lang.IllegalStateException: Genotype has no likelihoods: [CAU-SICAU-Y1035 A*/T GQ 80 DP 10] at org.broadinstitute.hellbender.utils.GenotypeUtils.computeDiploidGenotypeCounts(GenotypeUtils.java:89) at org.broadinstitute.hellbender.tools.walkers.annotator.ExcessHet.calculateEH(ExcessHet.java:96) at org.broadinstitute.hellbender.tools.walkers.annotator.ExcessHet.annotate(ExcessHet.java:84) at org.broadinstitute.hellbender.tools.walkers.annotator.VariantAnnotatorEngine.addInfoAnnotations(VariantAnnotatorEngine.java:355) at org.broadinstitute.hellbender.tools.walkers.annotator.VariantAnnotatorEngine.annotateContext(VariantAnnotatorEngine.java:334) at org.broadinstitute.hellbender.tools.walkers.annotator.VariantAnnotatorEngine.annotateContext(VariantAnnotatorEngine.java:306) at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFsEngine.regenotypeVC(GenotypeGVCFsEngine.java:185) at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFsEngine.callRegion(GenotypeGVCFsEngine.java:135) at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.apply(GenotypeGVCFs.java:283) at org.broadinstitute.hellbender.engine.VariantLocusWalker.lambda$traverse$0(VariantLocusWalker.java:135) at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.Iterator.forEachRemaining(Iterator.java:116) at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423) at org.broadinstitute.hellbender.engine.VariantLocusWalker.traverse(VariantLocusWalker.java:132) at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1085) at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140) at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192) at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211) at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160) at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203) at org.broadinstitute.hellbender.Main.main(Main.java:289)


I have the same problem when joint calling for ~7500 sample on human genome (the genome has beed splited to 3000 fragment). I tried to solve this problem for 1 week, but did not finished. I wonder whether you have deal with the problem and could you kindly offer me some suggestion. Thank you!
