### ISSUE TITLE
IllegalStateException: Genotype has no likelihoods

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#7933]
I think we're having a very similar issue as #7639, though we're using v4.2.6.1. We're running GenotypeGVCFs with a command similar to:
```
java8 -Xmx120g -Xms120g -Xss2m \
    -jar GenomeAnalysisTK4.jar GenotypeGVCFs \
    -R 128_Mmul_10.fasta \
    --variant gendb:///home/exacloud/gscratch/prime-seq/cachedData/92a51eab-e10f-103a-8ff9-f8f3fc866871/WGS_v2_db03_500.gdb \
    -O /home/exacloud/gscratch/prime-seq/workDir/4570d7bc-e1e5-103a-8ff9-f8f3fc866871/Job493.work/WGS_v2_db03_500.temp.vcf.gz \
    --annotate-with-num-discovered-alleles \
    -stand-call-conf 30 \
    --max-alternate-alleles 6 \
    --genomicsdb-max-alternate-alleles 9 \
    --force-output-intervals WGS-WXS.whitelist.v2.3.sort.merge.bed \
    -L X:117601765-123544428 \
    --only-output-calls-starting-in-intervals \
    --genomicsdb-shared-posixfs-optimizations
```

the exception is:
```
09 Jul 2022 14:35:24,661 DEBUG: 	java.lang.IllegalStateException: Genotype has no likelihoods: [29446 T*|C GQ 60 DP 10 AD 8,0 {PGT=0|1, PID=117659384_CAGATCGATGGATCT_C, PS=117659384, SB=[1, 7, 0, 2]}]
09 Jul 2022 14:35:24,667 DEBUG: 		at org.broadinstitute.hellbender.utils.GenotypeUtils.computeDiploidGenotypeCounts(GenotypeUtils.java:89)
09 Jul 2022 14:35:24,673 DEBUG: 		at org.broadinstitute.hellbender.tools.walkers.annotator.ExcessHet.calculateEH(ExcessHet.java:96)
09 Jul 2022 14:35:24,679 DEBUG: 		at org.broadinstitute.hellbender.tools.walkers.annotator.ExcessHet.annotate(ExcessHet.java:84)
09 Jul 2022 14:35:24,684 DEBUG: 		at org.broadinstitute.hellbender.tools.walkers.annotator.VariantAnnotatorEngine.addInfoAnnotations(VariantAnnotatorEngine.java:355)
09 Jul 2022 14:35:24,690 DEBUG: 		at org.broadinstitute.hellbender.tools.walkers.annotator.VariantAnnotatorEngine.annotateContext(VariantAnnotatorEngine.java:334)
09 Jul 2022 14:35:24,696 DEBUG: 		at org.broadinstitute.hellbender.tools.walkers.annotator.VariantAnnotatorEngine.annotateContext(VariantAnnotatorEngine.java:306)
09 Jul 2022 14:35:24,701 DEBUG: 		at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFsEngine.regenotypeVC(GenotypeGVCFsEngine.java:185)
09 Jul 2022 14:35:24,709 DEBUG: 		at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFsEngine.callRegion(GenotypeGVCFsEngine.java:135)
09 Jul 2022 14:35:24,714 DEBUG: 		at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.apply(GenotypeGVCFs.java:283)
09 Jul 2022 14:35:24,720 DEBUG: 		at org.broadinstitute.hellbender.engine.VariantLocusWalker.lambda$null$1(VariantLocusWalker.java:161)
09 Jul 2022 14:35:24,726 DEBUG: 		at java.util.Iterator.forEachRemaining(Iterator.java:116)
09 Jul 2022 14:35:24,731 DEBUG: 		at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
09 Jul 2022 14:35:24,738 DEBUG: 		at java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:590)
09 Jul 2022 14:35:24,743 DEBUG: 		at org.broadinstitute.hellbender.engine.VariantLocusWalker.lambda$traverse$2(VariantLocusWalker.java:151)
09 Jul 2022 14:35:24,749 DEBUG: 		at java.util.Iterator.forEachRemaining(Iterator.java:116)
09 Jul 2022 14:35:24,755 DEBUG: 		at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
09 Jul 2022 14:35:24,761 DEBUG: 		at java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:590)
09 Jul 2022 14:35:24,767 DEBUG: 		at org.broadinstitute.hellbender.engine.VariantLocusWalker.traverse(VariantLocusWalker.java:148)
09 Jul 2022 14:35:24,773 DEBUG: 		at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1085)
09 Jul 2022 14:35:24,780 DEBUG: 		at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
09 Jul 2022 14:35:24,786 DEBUG: 		at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
09 Jul 2022 14:35:24,792 DEBUG: 		at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
09 Jul 2022 14:35:24,798 DEBUG: 		at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
09 Jul 2022 14:35:24,804 DEBUG: 		at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
09 Jul 2022 14:35:24,813 DEBUG: 		at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

I thought this was fixed in the prior version. Is this a new error or a regression?

**Comment by bbimber** [comment]
FWIW, I repeated the same command this morning using GATK 4.2.6.0 and got the "No likelihood sum exceeded zero -- method was called for variant data with no variant information" error, which seems like the reason you released 4.2.6.1.

**Comment by droazen** [comment]
@bbimber Can you try running `GenotypeGVCFs` without the `--force-output-intervals` argument and report whether the same error occurs?

**Comment by kray02** [comment]
replying for @bbimber : we made a smaller test case on 4.2.6.0, and get the error: "Genotype has no likelihoods:" ..., the error does not occur without --force-output-intervals.

**Comment by bbimber** [comment]
Closing in favor of #7938
