### ISSUE TITLE
Investigate GATK error message with docker --network none

### ISSUE THREAD

**Issue by GATKSupportTeam** [broadinstitute/gatk#7983]
This error message occurs when removing the network when running GATK in a docker container. GATK tools still run to completion, but the error message is disruptive. 
```
$> docker run --rm --network none broadinstitute/gatk gatk -version

2022-08-03 20:37:23,349 main ERROR Could not determine local host name java.net.UnknownHostException: de2c81c88ddc: de2c81c88ddc: Temporary failure in name resolution
at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
at org.apache.logging.log4j.core.util.NetUtils.getLocalHostname(NetUtils.java:54)
at org.apache.logging.log4j.core.LoggerContext.lambda$setConfiguration$0(LoggerContext.java:620)
at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:620)
at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:699)
at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:716)
at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:270)
at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:599)
at org.broadinstitute.hellbender.utils.Utils.<clinit>(Utils.java:72)
at org.broadinstitute.hellbender.Main.<clinit>(Main.java:45)
Caused by: java.net.UnknownHostException: de2c81c88ddc: Temporary failure in name resolution
at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
...13 more

The Genome Analysis Toolkit (GATK) v4.2.6.1
HTSJDK Version: 2.24.1
Picard Version: 2.27.1
Using GATK jar /gatk/gatk-package-4.2.6.1-local.jar
Running:
java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /gatk/gatk-package-4.2.6.1-local.jar -version
```

This request was created from a contribution made by Pryce Turner on July 29, 2022 03:44 UTC.

Link: [https://gatk.broadinstitute.org/hc/en-us/community/posts/360078378372--Could-not-determine-local-host-name-#community\_comment\_7692552841755](https://gatk.broadinstitute.org/hc/en-us/community/posts/360078378372--Could-not-determine-local-host-name-#community_comment_7692552841755)

\--

Hey 417227834892,

Were you ever able to solve this? I'm running into the same issue with HaplotypeCaller. It still runs, but the error output is potentially disruptive.

Thanks!<br><br><i>(created from <a href='https://broadinstitute.zendesk.com/agent/tickets/292152'>Zendesk ticket #292152</a>)<br> gz#292152</i>

**Comment by pryce-turner** [comment]
Just wanted to highlight something from the thread that's hopefully salient: this issue does not occur when using Podman with exactly the same image/params.

**Comment by droazen** [comment]
This appears to be a log4j issue that we don't have direct control over, unfortunately.

**Comment by lbergelson** [comment]
I opened a log4j issue.  Maybe someone will fix it in the future.  https://issues.apache.org/jira/browse/LOG4J2-3602
