### ISSUE TITLE
ApplyVQSR  exception 

### ISSUE THREAD

**Issue by jjfarrell** [broadinstitute/gatk#8054]
### Affected tool(s) or class(es)
 ApplyVQSR 

### Affected version(s)
gatk-4.2.6.1

### Description 

Getting the following  error. However, the chr6.raw.excessHet.vcf.gz does not contain that multiallelic variant site.  This variant is the nearest at that location but the error is for a variant at  chr6:26914009 with different alleles =[G*, GTGTA, GTGTATA, GTGTGTA] . 

`chr6    26914005        .       A       ATG,G   15390.7 PASS    AC=278,2;AF=0.04,0.0002879;AN=6948;AS_BaseQRankSum=-0.2,0.4;AS_FS=0.522,0;AS_InbreedingCoeff=-0.0012,0.1805;AS_MQ=58.75,59.2;AS_MQRankSum=0,-3.2;AS_QD=2.56,0.02;AS_ReadPosRankSum=0.1,0.3;AS_SOR=0.652,0.724;BaseQRankSum=-0.152;DP=118313;ExcessHet=2.9774;FS=0.518;InbreedingCoeff=0.0016;MLEAC=278,2;MLEAF=0.04,0.0002879;MQ=56.9;MQRankSum=-0.962;QD=2.57;ReadPosRankSum=0.193;SOR=0.712
`

 ```
org.broadinstitute.hellbender.exceptions.GATKException: Exception thrown at chr6:26914009 [VC chr6.raw.excessHet.vcf.gz @ chr6:26914009 Q276902.75 of type=INDEL alleles=[G*, GTGTA, GTGTATA, GTGTGTA] attr={AC=[4269, 29, 5], AF=[0.620, 4.209e-03, 
#### Steps to reproduce
/share/pkg.7/gatk/4.2.6.1/install/gatk-4.2.6.1/gatk --java-options -Xms5g       ApplyVQSR       -O indel.recalibrated.vcf.gz       -V chr6.raw.excessHet.vcf.gz       -AS       --recal-file /restricted/projectnb/kageproj/gatk/pVCF.vqsr/indels.recal       --use-allele-specific-annotations       --tranches-file /restricted/projectnb/kageproj/gatk/pVCF.vqsr/indels.tranches       --truth-sensitivity-filter-level 99.0       --create-output-variant-index true       -mode INDEL
```

#### Expected behavior
Create recalibrated vcf file

#### Actual behavior
```
Caused by:
  Process `ApplyRecalibrationIndels` terminated with an error exit status (3)

Command executed:

  #!/bin/bash
  /share/pkg.7/gatk/4.2.6.1/install/gatk-4.2.6.1/gatk --java-options -Xms5g       ApplyVQSR       -O indel.recalibrated.vcf.gz       -V chr6.raw.excessHet.vcf.gz       -AS       --recal-file /restricted/projectnb/kageproj/gatk/pVCF.vqsr/indels.recal       --use-allele-specific-annotations       --tranches-file /restricted/projectnb/kageproj/gatk/pVCF.vqsr/indels.tranches       --truth-sensitivity-filter-level 99.0       --create-output-variant-index true       -mode INDEL

Command exit status:
  3

Command output:
  (empty)

Command error:
  23:21:52.354 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
  23:22:02.735 INFO  ProgressMeter -         chr6:1162012              0.2                 25000         144494.8
  23:22:12.789 INFO  ProgressMeter -         chr6:2449556              0.3                 53000         155623.0
  23:22:23.019 INFO  ProgressMeter -         chr6:3663394              0.5                 82000         160448.7
  23:22:33.257 INFO  ProgressMeter -         chr6:4991347              0.7                112000         164291.1
  23:22:43.683 INFO  ProgressMeter -         chr6:6325045              0.9                141000         164832.0
  23:22:53.824 INFO  ProgressMeter -         chr6:7646289              1.0                171000         166913.4
  23:23:03.973 INFO  ProgressMeter -         chr6:9029926              1.2                200000         167553.3
  23:23:14.220 INFO  ProgressMeter -        chr6:10374988              1.4                229000         167835.2
  23:23:24.322 INFO  ProgressMeter -        chr6:11782077              1.5                259000         168971.8
  23:23:34.465 INFO  ProgressMeter -        chr6:13360174              1.7                290000         170404.5
  23:23:44.556 INFO  ProgressMeter -        chr6:14757971              1.9                319000         170585.2
  23:23:54.657 INFO  ProgressMeter -        chr6:16217652              2.0                350000         171704.7
  23:24:04.905 INFO  ProgressMeter -        chr6:17737681              2.2                381000         172461.9
  23:24:15.102 INFO  ProgressMeter -        chr6:19070725              2.4                409000         171911.3
  23:24:25.321 INFO  ProgressMeter -        chr6:20580950              2.5                441000         172978.5
  23:24:36.315 INFO  ProgressMeter -        chr6:22100346              2.7                472000         172724.0
  23:24:46.346 INFO  ProgressMeter -        chr6:23531348              2.9                502000         173112.4
  23:24:56.432 INFO  ProgressMeter -        chr6:24734131              3.1                531000         173078.8
  23:25:06.662 INFO  ProgressMeter -        chr6:26183595              3.2                559000         172612.6
  23:25:11.087 INFO  ApplyVQSR - Shutting down engine
  [October 12, 2022 11:25:11 PM EDT] org.broadinstitute.hellbender.tools.walkers.vqsr.ApplyVQSR done. Elapsed time: 3.33 minutes.
  Runtime.totalMemory()=8242331648
  org.broadinstitute.hellbender.exceptions.GATKException: Exception thrown at chr6:26914009 [VC chr6.raw.excessHet.vcf.gz @ chr6:26914009 Q276902.75 of type=INDEL alleles=[G*, GTGTA, GTGTATA, GTGTGTA] attr={AC=[4269, 29, 5], AF=[0.620, 4.209e-03, 7.257e-04], AN=6890, AS_BaseQRankSum=[0.500, 0.500, 0.500], AS_FS=[0.544, 0.000, 0.000], AS_InbreedingCoeff=[0.0312, 0.0151, 0.0858], AS_MQ=[59.29, 57.89, 58.81], AS_MQRankSum=[0.000, -3.800, -3.800], AS_QD=[3.94, 0.05, 0.01], AS_ReadPosRankSum=[0.200, 0.300, 0.300], AS_SOR=[0.747, 0.705, 0.739], BaseQRankSum=0.515, DP=121924, ExcessHet=0.1315, FS=0.552, InbreedingCoeff=0.0304, MLEAC=[4273, 28, 5], MLEAF=[0.620, 4.064e-03, 7.257e-04], MQ=57.54, MQRankSum=-1.059e+00, QD=3.98, ReadPosRankSum=0.244, SOR=0.780} GT=GT:AD:DP:GQ:PGT:PID:PL:PS31/1:0,15,0,0:18:45:.:.:106,45,0,569,45,106,569,45,106,1060,419 f1/1:0,17,0,0:17:51:.:.:113,51,0,522,51,113,522,51,113,113       0/1:11,11,0,0:25:40:.:.:62,0,40,424,424,464,424,424,464,464rs.v1/1:0,22,0,0:27:67:.:.:129,67,0,947,67,129,947,67,129,1292)     0/1:13,7,0,0:24:40:.:.:60,0,40,295,530,335,295,530,335,335      0/1:12,13,0,0:25:40:.:.:62,0,40,519,497,559,519,497,559,559rg.b1/1:0,13,0,0:14:39:.:.:100,39,0,463,40,101,463,40,101,101ly(Appl0/1:7,7,0,0:14:40:.:.:61,0,40,294,279,334,294,279,334,334       0/1:10,9,0,0:22:40:.:.:62,0,40,237,385,277,237,385,277,277      0/0:27,0,0,0:27:60    1/1:0,13,0,0:18:40:.:.:102,40,0,547,40,102,547,40,102,102iantWalk0|1:19,19,0,0:39:40:0|1:26913991_T_TGA:62,0,40,798,798,838,798,798,838,838:26913991     0/1:15,10,0,0:26:40:.:.:60,0,40,420,620,460,420,620,460,460     1|1:0,37,0,0:38:99:1|1:26913991_T_TGA:172,111,0,1652,111,172,1652,111,172,172:26913991 0/1:11,9,0,0:22:40:.:.:62,0,40,378,454,418,378,454,418,418      1/1:0,18,0,0:18:56:.:.:117,56,0,457,73,134,457,73,134,134       0/1:13,11,0,0:24:40:.:.:62,0,40,369,546,409,369,546,409,409    0/1:12,7,0,0:19:40:.:.:47,0,40,281,489,321,281,489,321,321      0/1:17,7,0,0:25:40:.:.:54,0,40,280,678,320,280,678,320,320      0/0:34,0,0,0:34:60      1/1:0,18,0,0:19:55:.:.:118,55,0,800,55,118,800,55,118,118      1/1:0,
```
```

        at org.broadinstitute.hellbender.engine.MultiVariantWalker.lambda$traverse$1(MultiVariantWalker.java:145)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.broadinstitute.hellbender.engine.MultiVariantWalker.traverse(MultiVariantWalker.java:136)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1085)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
  Caused by: org.broadinstitute.hellbender.exceptions.UserException: Encountered input allele which isn't found in the input recal file. Please make sure VariantRecalibrator and ApplyVQSR were run on the same set of input variants with flag -AS. First seen at: [VC chr6.raw.excessHet.vcf.gz @ chr6:26914009 Q276902.75 of type=INDEL alleles=[G*, GTGTA, GTGTATA, GTGTGTA] attr={AC=[4269, 29, 5], AF=[0.620, 4.209e-03, 7.257e-04], AN=6890, AS_BaseQRankSum=[0.500, 0.500, 0.500], AS_FS=[0.544, 0.000, 0.000], AS_InbreedingCoeff=[0.0312, 0.0151, 0.0858], AS_MQ=[59.29, 57.89, 58.81], AS_MQRankSum=[0.000, -3.800, -3.800], AS_QD=[3.94, 0.05, 0.01], AS_ReadPosRankSum=[0.200, 0.300, 0.300], AS_SOR=[0.747, 0.705, 0.739], 
```

**Comment by ldgauthier** [comment]
HI @jjfarrell,

Can I get a `SelectVariants -L chr6:26914009 -ip 10` from /restricted/projectnb/kageproj/gatk/pVCF.vqsr/indels.recal  and chr6.raw.excessHet.vcf.gz?  That will make this much easier to debug.

**Comment by ldgauthier** [comment]
@jjfarrell did you ever figure this one out?  It's going to be really hard to debug without the snippets I asked for above.

**Comment by jjfarrell** [comment]
@ldgauthier 

Yes, I found the issue.  I went back and looked at the earlier  concatenate step before the recalibration and found the issue. 

There was a premature end of file warning for one of the scatter vcfs.  bcftools tools kept concatenating and tabix ran fine.  I reran that region and concatenated the chromosomes together. The ApplyVQSR then worked fine.
