### ISSUE TITLE
TransferReadTags unable to find an existing read in the unmapped bam

### ISSUE THREAD

**Issue by alexbarrera** [broadinstitute/gatk#8147]
### Affected tool(s) or class(es)
TransferReadTags

### Affected version(s)
- [X] Latest public release version [gatk-4.3.0.0]

### Description 
When traversing the reads in both aligned (target) and unaligned (the one with the desired tag) BAMs an error is thrown complaining about a read `found in the aligned bam is not found in the unmapped bam`. However the reads exists. It looks like the `traverse` function that uses the lexicographic order difference between both query names will find a _negative_ `diff` and assume that the read in the aligned BAM is missing in the uBAM. However, with Illumina read headers it seems almost guaranteed that this is going to be an issue since the y-coord (the last colon-separated field in the header) often has numbers with different number of digits. The lexicographical comparison will fail to adjust when comparing two read names where the length of the read in the target BAM is larger than the length of the read in the uBAM. 

This is the `traverse` function that throws the error:
https://github.com/broadinstitute/gatk/blob/2b0a558fdb9fdf654e796d5d69a092e26345583b/src/main/java/org/broadinstitute/hellbender/tools/walkers/qc/TransferReadTags.java#L109-L145 

#### Steps to reproduce
Run `TransferReadTags` with an Illumina sequenced aligned BAM. I can provide dummy files if needed, but should be easy to reproduce. The following example should help illustrate the issue:

```sh
$ /data/reddylab/software/gatk/gatk-4.3.0.0/gatk TransferReadTags     \
--output /data/reddylab/Alex/tmp/TEST_BAM.with_umis.bam     \
--read-tags RX     \
--unmapped-sam /data/reddylab/Alex/tmp/TEST_BAM.umi.nsorted.ubam     \
--input /data/reddylab/Alex/tmp/TEST_BAM.nsorted.bam
```

Produces the following output:
```
Using GATK jar /gpfs/fs1/data/reddylab/software/gatk/gatk-4.3.0.0/gatk-package-4.3.0.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /gpfs/fs1/data/reddylab/software/gatk/gatk-4.3.0.0/gatk-package-4.3.0.0-local.jar TransferReadTags --output /data/reddylab/Alex/tmp/TEST_BAM.with_umis.bam --read-tags RX --unmapped-sam /data/reddylab/Alex/tmp/TEST_BAM.umi.nsorted.ubam --input /data/reddylab/Alex/tmp/TEST_BAM.nsorted.bam
13:08:15.961 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gpfs/fs1/data/reddylab/software/gatk/gatk-4.3.0.0/gatk-package-4.3.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
13:08:16.213 INFO  TransferReadTags - ------------------------------------------------------------
13:08:16.213 INFO  TransferReadTags - The Genome Analysis Toolkit (GATK) v4.3.0.0
13:08:16.213 INFO  TransferReadTags - For support and documentation go to https://software.broadinstitute.org/gatk/
13:08:16.214 INFO  TransferReadTags - Executing as aeb84@x1-01-2.genome.duke.edu on Linux v3.10.0-1160.31.1.el7.x86_64 amd64
13:08:16.214 INFO  TransferReadTags - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_92-b15
13:08:16.214 INFO  TransferReadTags - Start Date/Time: January 5, 2023 1:08:15 PM EST
13:08:16.214 INFO  TransferReadTags - ------------------------------------------------------------
13:08:16.214 INFO  TransferReadTags - ------------------------------------------------------------
13:08:16.215 INFO  TransferReadTags - HTSJDK Version: 3.0.1
13:08:16.215 INFO  TransferReadTags - Picard Version: 2.27.5
13:08:16.215 INFO  TransferReadTags - Built for Spark Version: 2.4.5
13:08:16.215 INFO  TransferReadTags - HTSJDK Defaults.COMPRESSION_LEVEL : 2
13:08:16.215 INFO  TransferReadTags - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
13:08:16.215 INFO  TransferReadTags - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
13:08:16.216 INFO  TransferReadTags - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
13:08:16.216 INFO  TransferReadTags - Deflater: IntelDeflater
13:08:16.216 INFO  TransferReadTags - Inflater: IntelInflater
13:08:16.216 INFO  TransferReadTags - GCS max retries/reopens: 20
13:08:16.216 INFO  TransferReadTags - Requester pays: disabled
13:08:16.216 WARN  TransferReadTags -

   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

   Warning: TransferReadTags is an EXPERIMENTAL tool and should not be used for production

   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


13:08:16.217 INFO  TransferReadTags - Initializing engine
13:08:16.658 INFO  TransferReadTags - Done initializing engine
13:08:16.710 WARN  ReadUtils - Skipping index file creation for: /data/reddylab/Alex/tmp/TEST_BAM.with_umis.bam. Index file creation requires reads in coordinate sorted order.
13:08:16.739 INFO  ProgressMeter - Starting traversal
13:08:16.739 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Records Processed   Records/Minute
13:08:16.741 INFO  TransferReadTags - Shutting down engine
[January 5, 2023 1:08:16 PM EST] org.broadinstitute.hellbender.tools.walkers.qc.TransferReadTags done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=2612002816
java.lang.IllegalStateException: A read found in the aligned bam is not found in the unmapped bam. This tool assumes reads in both input files are query-name sorted lexicographically (i.e. by Picard SortSam but not by samtools sort): aligned read = A00257:933:HG2MVDSX5:1:1101:1045:11130, unmapped read = A00257:933:HG2MVDSX5:1:1101:1045:8531
        at org.broadinstitute.hellbender.tools.walkers.qc.TransferReadTags.traverse(TransferReadTags.java:142)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1095)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

But inspecting the BAMs (both aligned and unaligned, and queryname sorted) reveals the problem:
```sh
$ paste -d"\t" <(samtools view /data/reddylab/Alex/tmp/TEST_BAM.nsorted.bam | head -n 20 | cut -f1) <(samtools view /data/reddylab/Alex/tmp/TEST_BAM.umi.nsorted.ubam   | head -n 20 | cut -f1)
A00257:933:HG2MVDSX5:1:1101:1045:2863   A00257:933:HG2MVDSX5:1:1101:1045:2863
A00257:933:HG2MVDSX5:1:1101:1045:2863   A00257:933:HG2MVDSX5:1:1101:1045:2957
A00257:933:HG2MVDSX5:1:1101:1045:2957   A00257:933:HG2MVDSX5:1:1101:1045:3051
A00257:933:HG2MVDSX5:1:1101:1045:2957   A00257:933:HG2MVDSX5:1:1101:1045:3302
A00257:933:HG2MVDSX5:1:1101:1045:3646   A00257:933:HG2MVDSX5:1:1101:1045:3646
A00257:933:HG2MVDSX5:1:1101:1045:3646   A00257:933:HG2MVDSX5:1:1101:1045:4711
A00257:933:HG2MVDSX5:1:1101:1045:5306   A00257:933:HG2MVDSX5:1:1101:1045:5306
A00257:933:HG2MVDSX5:1:1101:1045:5306   A00257:933:HG2MVDSX5:1:1101:1045:6277
A00257:933:HG2MVDSX5:1:1101:1045:6277   A00257:933:HG2MVDSX5:1:1101:1045:7717
A00257:933:HG2MVDSX5:1:1101:1045:6277   A00257:933:HG2MVDSX5:1:1101:1045:8375
A00257:933:HG2MVDSX5:1:1101:1045:7717   A00257:933:HG2MVDSX5:1:1101:1045:8531
A00257:933:HG2MVDSX5:1:1101:1045:7717   A00257:933:HG2MVDSX5:1:1101:1045:9283
A00257:933:HG2MVDSX5:1:1101:1045:8531   A00257:933:HG2MVDSX5:1:1101:1045:10316
A00257:933:HG2MVDSX5:1:1101:1045:8531   A00257:933:HG2MVDSX5:1:1101:1045:11130
A00257:933:HG2MVDSX5:1:1101:1045:11130  A00257:933:HG2MVDSX5:1:1101:1045:11882
A00257:933:HG2MVDSX5:1:1101:1045:11130  A00257:933:HG2MVDSX5:1:1101:1045:12007
A00257:933:HG2MVDSX5:1:1101:1045:12007  A00257:933:HG2MVDSX5:1:1101:1045:12665
A00257:933:HG2MVDSX5:1:1101:1045:12007  A00257:933:HG2MVDSX5:1:1101:1045:12727
A00257:933:HG2MVDSX5:1:1101:1045:12665  A00257:933:HG2MVDSX5:1:1101:1045:13260
A00257:933:HG2MVDSX5:1:1101:1045:12665  A00257:933:HG2MVDSX5:1:1101:1045:13322
```

The error above makes sense since the lexicographic difference between `A00257:933:HG2MVDSX5:1:1101:1045:11130` and `A00257:933:HG2MVDSX5:1:1101:1045:8531` is `-7`, the result of `ord("1") - ord("8")`.

#### Expected behavior
The `traverse` function above should keep advancing through the uBAM. Assuming the BAMs to be queryname sorted, the `traverse` function could check the lengths of the names when the `diff` is not zero in https://github.com/broadinstitute/gatk/blob/2b0a558fdb9fdf654e796d5d69a092e26345583b/src/main/java/org/broadinstitute/hellbender/tools/walkers/qc/TransferReadTags.java#L121, advancing the `unmappedSamIterator` if the name of the `currentTargetRead` is larger than the name of `currentUnmappedRead`. 

#### Actual behavior
An `java.lang.IllegalStateException:  A read found in the aligned bam is not found in the unmapped bam.` exception is raised when in fact the read might exist

**Comment by jamesemery** [comment]
hey @alexbarrera thanks for writing in. This is a known issue that we are aware of and we have unfortunately dealt with on several occasions (lexocographic vs. numerical sorting of readnames). Would it be possible for you to re-sort your bam using SortSam with -SO queryname to clear this up in your use-case as a workaround?

**Comment by lbergelson** [comment]
Agh, we should really fix this.  It's so annoying.

**Comment by alexbarrera** [comment]
Hi team,
Thanks for the quick response. I ended up trying my proposed solution using a custom script and I found a counter example in which the hack didn't work. I will try using SortSam with -SO.
Thanks
