### ISSUE TITLE
FilterAlignmentArtifacts Exception

### ISSUE THREAD

**Issue by fo40225** [broadinstitute/gatk#8221]
### Affected tool(s) or class(es)
_Tool/class name(s), special parameters?_

FilterAlignmentArtifacts

### Affected version(s)
- [x] Latest public release version [version?]
- [ ] Latest master branch as of [date of test?]

4.3.0.0

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._

```
Using GATK jar /gatk-4.3.0.0/gatk-package-4.3.0.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -XX:+UseNUMA -jar /gatk-4.3.0.0/gatk-package-4.3.0.0-local.jar FilterAlignmentArtifacts -R /raid/bundle/hg38/Homo_sapiens_assembly38.fasta.gz -O WGS-NA12878.FilterAlignmentArtifacts.vcf --tmp-dir . -V WGS-NA12878.filtered.vcf -I WGS-NA12878.sorted.dedup.recal.bam --bwa-mem-index-image /raid/bundle/hg38/Homo_sapiens_assembly38.fasta.img
11:24:09.761 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gatk-4.3.0.0/gatk-package-4.3.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
11:24:09.942 INFO  FilterAlignmentArtifacts - ------------------------------------------------------------
11:24:09.942 INFO  FilterAlignmentArtifacts - The Genome Analysis Toolkit (GATK) v4.3.0.0
11:24:09.943 INFO  FilterAlignmentArtifacts - For support and documentation go to https://software.broadinstitute.org/gatk/
11:24:09.943 INFO  FilterAlignmentArtifacts - Executing as root@D52BV-2U on Linux v4.15.0-202-generic amd64
11:24:09.943 INFO  FilterAlignmentArtifacts - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_352-8u352-ga-1~18.04-b08
11:24:09.943 INFO  FilterAlignmentArtifacts - Start Date/Time: February 24, 2023 11:24:09 AM CST
11:24:09.943 INFO  FilterAlignmentArtifacts - ------------------------------------------------------------
11:24:09.943 INFO  FilterAlignmentArtifacts - ------------------------------------------------------------
11:24:09.943 INFO  FilterAlignmentArtifacts - HTSJDK Version: 3.0.1
11:24:09.943 INFO  FilterAlignmentArtifacts - Picard Version: 2.27.5
11:24:09.943 INFO  FilterAlignmentArtifacts - Built for Spark Version: 2.4.5
11:24:09.943 INFO  FilterAlignmentArtifacts - HTSJDK Defaults.COMPRESSION_LEVEL : 2
11:24:09.944 INFO  FilterAlignmentArtifacts - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
11:24:09.944 INFO  FilterAlignmentArtifacts - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
11:24:09.944 INFO  FilterAlignmentArtifacts - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
11:24:09.944 INFO  FilterAlignmentArtifacts - Deflater: IntelDeflater
11:24:09.944 INFO  FilterAlignmentArtifacts - Inflater: IntelInflater
11:24:09.944 INFO  FilterAlignmentArtifacts - GCS max retries/reopens: 20
11:24:09.944 INFO  FilterAlignmentArtifacts - Requester pays: disabled
11:24:09.944 WARN  FilterAlignmentArtifacts -

   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

   Warning: FilterAlignmentArtifacts is an EXPERIMENTAL tool and should not be used for production

   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


11:24:09.944 INFO  FilterAlignmentArtifacts - Initializing engine
11:24:10.534 INFO  FeatureManager - Using codec VCFCodec to read file file:///raid/tmp/82/68cd46b704bab21cb8661465e5c2b8/WGS-NA12878.filtered.vcf
11:24:10.814 INFO  FilterAlignmentArtifacts - Done initializing engine
11:24:10.816 INFO  NativeLibraryLoader - Loading libgkl_utils.so from jar:file:/gatk-4.3.0.0/gatk-package-4.3.0.0-local.jar!/com/intel/gkl/native/libgkl_utils.so
11:24:10.817 INFO  NativeLibraryLoader - Loading libgkl_smithwaterman.so from jar:file:/gatk-4.3.0.0/gatk-package-4.3.0.0-local.jar!/com/intel/gkl/native/libgkl_smithwaterman.so
11:24:10.818 INFO  IntelSmithWaterman - Using CPU-supported AVX-512 instructions
11:24:10.818 INFO  SmithWatermanAligner - Using AVX accelerated SmithWaterman implementation
11:24:10.957 INFO  NativeLibraryLoader - Loading libgkl_pairhmm_omp.so from jar:file:/gatk-4.3.0.0/gatk-package-4.3.0.0-local.jar!/com/intel/gkl/native/libgkl_pairhmm_omp.so
11:24:10.980 INFO  IntelPairHmm - Using CPU-supported AVX-512 instructions
11:24:10.980 INFO  IntelPairHmm - Flush-to-zero (FTZ) is enabled when running PairHMM
11:24:10.981 INFO  IntelPairHmm - Available threads: 80
11:24:10.981 INFO  IntelPairHmm - Requested threads: 4
11:24:10.981 INFO  PairHMM - Using the OpenMP multi-threaded AVX-accelerated native PairHMM implementation
11:24:10.981 INFO  ProgressMeter - Starting traversal
11:24:10.981 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
11:25:26.222 INFO  ProgressMeter -        chr1:32527418              1.3                  1000            797.5
11:26:14.235 INFO  ProgressMeter -       chr1:103944651              2.1                  2000            973.6
11:26:59.367 INFO  ProgressMeter -       chr1:121884881              2.8                  3000           1069.0
11:28:22.595 INFO  ProgressMeter -       chr1:124412677              4.2                  4000            953.8
11:30:27.936 INFO  ProgressMeter -       chr1:146326436              6.3                  5000            795.9
11:31:16.814 INFO  ProgressMeter -       chr1:151781328              7.1                  6000            845.4
11:31:47.039 INFO  ProgressMeter -       chr1:222591703              7.6                  7000            920.9
11:32:23.165 INFO  ProgressMeter -        chr2:33832294              8.2                  8000            975.2
11:32:57.177 INFO  ProgressMeter -        chr2:90283356              8.8                  9000           1026.2
11:34:06.535 INFO  ProgressMeter -        chr2:93744700              9.9                 10000           1007.5
11:34:46.020 INFO  ProgressMeter -       chr2:146056068             10.6                 11000           1039.3
11:35:13.013 INFO  ProgressMeter -       chr2:223829124             11.0                 12000           1087.6
11:35:42.553 INFO  ProgressMeter -        chr3:48697488             11.5                 13000           1127.9
11:36:21.282 INFO  ProgressMeter -        chr3:90843805             12.2                 14000           1150.2
11:37:04.483 INFO  ProgressMeter -       chr3:126063949             12.9                 15000           1163.5
11:37:30.408 INFO  ProgressMeter -       chr3:197942385             13.3                 16000           1200.9
11:38:59.639 INFO  ProgressMeter -        chr4:50255565             14.8                 17000           1147.8
11:39:36.590 INFO  ProgressMeter -       chr4:101429151             15.4                 18000           1166.8
11:40:00.242 INFO  ProgressMeter -       chr4:183754454             15.8                 19000           1200.9
11:40:45.735 INFO  ProgressMeter -        chr5:44061370             16.6                 20000           1206.3
11:41:43.218 INFO  ProgressMeter -        chr5:97352621             17.5                 21000           1197.4
11:42:07.417 INFO  ProgressMeter -       chr5:177567279             17.9                 22000           1226.3
11:42:39.874 INFO  ProgressMeter -        chr6:49337585             18.5                 23000           1244.5
11:43:46.344 INFO  ProgressMeter -        chr6:60312359             19.6                 24000           1225.2
11:44:35.360 INFO  ProgressMeter -        chr6:90960518             20.4                 25000           1225.1
11:45:14.799 INFO  ProgressMeter -       chr6:149557726             21.1                 26000           1234.4
11:45:48.671 INFO  ProgressMeter -        chr7:33074426             21.6                 27000           1248.4
11:46:41.613 INFO  ProgressMeter -        chr7:61821403             22.5                 28000           1243.9
11:47:36.447 INFO  ProgressMeter -        chr7:74936078             23.4                 29000           1238.0
11:48:06.693 INFO  ProgressMeter -       chr7:130526773             23.9                 30000           1253.7
11:48:44.870 INFO  ProgressMeter -         chr8:2170008             24.6                 31000           1262.0
11:49:43.193 INFO  ProgressMeter -        chr8:40122804             25.5                 32000           1253.1
11:50:14.565 INFO  ProgressMeter -       chr8:114246113             26.1                 33000           1266.3
11:50:45.837 INFO  ProgressMeter -        chr9:30721411             26.6                 34000           1279.1
11:51:38.133 INFO  ProgressMeter -        chr9:42226537             27.5                 35000           1274.9
11:52:55.998 INFO  ProgressMeter -        chr9:61142307             28.8                 36000           1252.2
11:53:45.998 INFO  ProgressMeter -        chr9:79405584             29.6                 37000           1250.7
11:54:24.284 INFO  ProgressMeter -       chr9:136913295             30.2                 38000           1257.4
11:55:07.341 INFO  ProgressMeter -       chr10:38976947             30.9                 39000           1260.5
11:56:48.154 INFO  ProgressMeter -       chr10:41846780             32.6                 40000           1226.3
11:58:04.280 INFO  ProgressMeter -       chr10:72810461             33.9                 41000           1209.9
11:58:35.758 INFO  ProgressMeter -      chr10:131932646             34.4                 42000           1220.5
11:59:11.668 INFO  ProgressMeter -       chr11:51648288             35.0                 43000           1228.2
12:00:13.755 INFO  ProgressMeter -       chr11:54939541             36.0                 44000           1220.7
12:00:42.440 INFO  ProgressMeter -      chr11:114799311             36.5                 45000           1232.1
12:01:25.679 INFO  ProgressMeter -       chr12:34896416             37.2                 46000           1235.1
12:02:31.209 INFO  ProgressMeter -       chr12:50140284             38.3                 47000           1226.0
12:02:53.689 INFO  ProgressMeter -      chr12:131033221             38.7                 48000           1239.9
12:04:01.601 INFO  ProgressMeter -       chr13:17109942             39.8                 49000           1229.8
12:04:59.560 INFO  ProgressMeter -       chr13:46525159             40.8                 50000           1225.2
12:05:29.198 INFO  ProgressMeter -       chr14:18913241             41.3                 51000           1234.8
12:06:07.871 INFO  ProgressMeter -       chr14:41610661             41.9                 52000           1239.6
12:06:37.168 INFO  ProgressMeter -      chr14:106195249             42.4                 53000           1248.9
12:07:43.734 INFO  ProgressMeter -       chr15:41554151             43.5                 54000           1240.1
12:08:13.840 INFO  ProgressMeter -        chr16:1196747             44.0                 55000           1248.6
12:08:59.918 INFO  ProgressMeter -       chr16:50255402             44.8                 56000           1249.6
12:09:26.233 INFO  ProgressMeter -       chr17:21320609             45.3                 57000           1259.6
12:11:01.286 INFO  ProgressMeter -       chr17:26850239             46.8                 58000           1238.3
12:11:43.213 INFO  ProgressMeter -       chr17:53286770             47.5                 59000           1241.1
12:12:19.288 INFO  ProgressMeter -       chr18:15544697             48.1                 60000           1246.4
12:13:22.049 INFO  ProgressMeter -       chr18:34336595             49.2                 61000           1240.2
12:13:51.002 INFO  ProgressMeter -       chr19:15985764             49.7                 62000           1248.3
12:14:29.274 INFO  ProgressMeter -       chr19:54444499             50.3                 63000           1252.4
12:15:17.402 INFO  ProgressMeter -       chr20:26553705             51.1                 64000           1252.3
12:17:04.504 INFO  ProgressMeter -       chr20:29573718             52.9                 65000           1228.9
12:18:23.620 INFO  ProgressMeter -       chr20:30705782             54.2                 66000           1217.5
12:20:09.590 INFO  ProgressMeter -        chr21:5249184             56.0                 67000           1196.9
12:22:03.446 INFO  ProgressMeter -       chr21:10481328             57.9                 68000           1175.0
12:23:03.667 INFO  ProgressMeter -       chr22:11316842             58.9                 69000           1171.9
12:24:57.983 INFO  ProgressMeter -       chr22:16127710             60.8                 70000           1151.6
12:26:31.457 INFO  ProgressMeter -       chr22:25997978             62.3                 71000           1138.9
12:27:09.230 INFO  ProgressMeter -        chrX:29806474             63.0                 72000           1143.4
12:27:53.073 INFO  ProgressMeter -        chrX:67820874             63.7                 73000           1146.0
12:29:03.144 INFO  ProgressMeter -        chrX:86707912             64.9                 74000           1140.8
12:30:07.160 INFO  ProgressMeter -       chrX:114791793             65.9                 75000           1137.5
12:30:59.264 INFO  ProgressMeter -       chrX:141227354             66.8                 76000           1137.6
12:31:52.052 INFO  ProgressMeter -       chrX:153138333             67.7                 77000           1137.6
12:33:18.782 INFO  FilterAlignmentArtifacts - Shutting down engine
[February 24, 2023 12:33:18 PM CST] org.broadinstitute.hellbender.tools.walkers.realignmentfilter.FilterAlignmentArtifacts done. Elapsed time: 69.15 minutes.
Runtime.totalMemory()=12185501696
org.broadinstitute.hellbender.exceptions.GATKException: Exception thrown at chr1_KI270708v1_random:2666 [VC /raid/tmp/82/68cd46b704bab21cb8661465e5c2b8/WGS-NA12878.filtered.vcf @ chr1_KI270708v1_random:2666 Q. of type=SNP alleles=[T*, A] attr={AS_FilterStatus=SITE, AS_SB_TABLE=[7, 9|3, 11], DP=30, ECNT=2, GERMQ=13, MBQ=[33, 37], MFRL=[317, 323], MMQ=[48, 47], MPOS=47, POPAF=7.30, ROQ=83, TLOD=47.80} GT=GT:AD:AF:DP:F1R2:F2R1:FAD:SB  0/1:16,14:0.486:30:8,9:5,4:15,14:7,9,3,11 filters=
        at org.broadinstitute.hellbender.engine.MultiVariantWalker.lambda$traverse$1(MultiVariantWalker.java:145)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
        at org.broadinstitute.hellbender.engine.MultiVariantWalker.traverse(MultiVariantWalker.java:136)
        at org.broadinstitute.hellbender.engine.MultiVariantWalkerGroupedOnStart.traverse(MultiVariantWalkerGroupedOnStart.java:165)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1095)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
Caused by: java.lang.IllegalStateException: Padded span must contain active span.
        at org.broadinstitute.hellbender.utils.Utils.validate(Utils.java:814)
        at org.broadinstitute.hellbender.engine.AssemblyRegion.<init>(AssemblyRegion.java:109)
        at org.broadinstitute.hellbender.engine.AssemblyRegion.<init>(AssemblyRegion.java:85)
        at org.broadinstitute.hellbender.engine.AssemblyRegion.<init>(AssemblyRegion.java:120)
        at org.broadinstitute.hellbender.tools.walkers.realignmentfilter.FilterAlignmentArtifacts.makeAssemblyRegionFromVariantReads(FilterAlignmentArtifacts.java:280)
        at org.broadinstitute.hellbender.tools.walkers.realignmentfilter.FilterAlignmentArtifacts.apply(FilterAlignmentArtifacts.java:212)
        at org.broadinstitute.hellbender.engine.MultiVariantWalkerGroupedOnStart.apply(MultiVariantWalkerGroupedOnStart.java:133)
        at org.broadinstitute.hellbender.engine.MultiVariantWalkerGroupedOnStart.apply(MultiVariantWalkerGroupedOnStart.java:108)
        at org.broadinstitute.hellbender.engine.MultiVariantWalker.lambda$traverse$1(MultiVariantWalker.java:139)
        ... 21 more
```

#### Steps to reproduce
_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem. (The support team may follow up to ask you to upload data to reproduce the issue.)_

```
/gatk-4.3.0.0/gatk FilterAlignmentArtifacts -R /raid/bundle/hg38/Homo_sapiens_assembly38.fasta.gz -O WGS-NA12878.FilterAlignmentArtifacts.vcf --java-options "-XX:+UseNUMA" --tmp-dir .     -V WGS-NA12878.filtered.vcf     -I WGS-NA12878.sorted.dedup.recal.bam     --bwa-mem-index-image /raid/bundle/hg38/Homo_sapiens_assembly38.fasta.img
```

#### Expected behavior
_Tell us what should happen_

No Crash

#### Actual behavior
_Tell us what happens instead_

Crash

**Comment by droazen** [comment]
@fo40225 Can you check the definition of the `chr1_KI270708v1_random` contig in the header of your inputs (reference fasta, vcf, bam, and BWA index), and make sure that it's defined as having the same length everywhere (should be 127682 bases for hg38).

**Comment by fo40225** [comment]
```
user@D52BV-2U:/raid/tmp/82/68cd46b704bab21cb8661465e5c2b8$ grep chr1_KI270708v1_random WGS-NA12878.filtered.vcf | head
##contig=<ID=chr1_KI270708v1_random,length=127682>
chr1_KI270708v1_random  2512    .       T       C       .       clustered_events;map_qual       AS_FilterStatus=map_qual;AS_SB_TABLE=17,15|3,0;DP=38;ECNT=3;GERMQ=62;MBQ=35,33;MFRL=317,355;MMQ=60,29;MPOS=25;POPAF=7.30;ROQ=16;TLOD=7.54 GT:AD:AF:DP:F1R2:F2R1:FAD:SB    0/1:32,3:0.117:35:15,3:13,0:29,3:17,15,3,0
chr1_KI270708v1_random  2530    .       C       G       .       clustered_events;haplotype;map_qual;weak_evidence       AS_FilterStatus=weak_evidence,map_qual;AS_SB_TABLE=17,17|2,0;DP=36;ECNT=3;GERMQ=72;MBQ=34,35;MFRL=319,339;MMQ=60,27;MPOS=39;POPAF=7.30;ROQ=44;TLOD=4.63   GT:AD:AF:DP:F1R2:F2R1:FAD:PGT:PID:PS:SB 0|1:34,2:0.079:36:16,2:12,0:34,2:0|1:2530_C_G:2530:17,17,2,0
chr1_KI270708v1_random  2538    .       T       C       .       clustered_events;haplotype;map_qual;weak_evidence       AS_FilterStatus=weak_evidence,map_qual;AS_SB_TABLE=18,19|2,0;DP=39;ECNT=3;GERMQ=80;MBQ=34,32;MFRL=319,339;MMQ=60,27;MPOS=47;POPAF=7.30;ROQ=27;TLOD=4.56   GT:AD:AF:DP:F1R2:F2R1:FAD:PGT:PID:PS:SB 0|1:37,2:0.075:39:17,2:8,0:36,2:0|1:2530_C_G:2530:18,19,2,0
chr1_KI270708v1_random  2666    .       T       A       .       PASS    AS_FilterStatus=SITE;AS_SB_TABLE=7,9|3,11;DP=30;ECNT=2;GERMQ=13;MBQ=33,37;MFRL=317,323;MMQ=48,47;MPOS=47;POPAF=7.30;ROQ=83;TLOD=47.80     GT:AD:AF:DP:F1R2:F2R1:FAD:SB    0/1:16,14:0.486:30:8,9:5,4:15,14:7,9,3,11
chr1_KI270708v1_random  2778    .       C       T       .       map_qual        AS_FilterStatus=map_qual;AS_SB_TABLE=11,13|5,2;DP=31;ECNT=2;GERMQ=30;MBQ=34,34;MFRL=351,355;MMQ=42,24;MPOS=63;POPAF=7.30;ROQ=36;TLOD=14.50        GT:AD:AF:DP:F1R2:F2R1:FAD:SB    0/1:24,7:0.234:31:6,0:8,5:24,7:11,13,5,2
chr1_KI270708v1_random  2908    .       C       T       .       clustered_events;map_qual;weak_evidence AS_FilterStatus=weak_evidence,map_qual;AS_SB_TABLE=17,8|1,2;DP=28;ECNT=5;GERMQ=46;MBQ=34,38;MFRL=335,360;MMQ=48,22;MPOS=5;POPAF=7.30;ROQ=40;TLOD=3.55     GT:AD:AF:DP:F1R2:F2R1:FAD:SB    0/1:25,3:0.131:28:13,0:12,3:25,3:17,8,1,2
chr1_KI270708v1_random  2977    .       G       T       .       clustered_events;map_qual;weak_evidence AS_FilterStatus=weak_evidence,map_qual;AS_SB_TABLE=12,14|0,2;DP=30;ECNT=5;GERMQ=54;MBQ=34,34;MFRL=336,390;MMQ=40,27;MPOS=31;POPAF=7.30;ROQ=23;TLOD=4.97   GT:AD:AF:DP:F1R2:F2R1:FAD:SB    0/1:26,2:0.101:28:8,1:12,1:25,2:12,14,0,2
chr1_KI270708v1_random  2988    .       C       T       .       clustered_events;map_qual       AS_FilterStatus=map_qual;AS_SB_TABLE=11,16|0,4;DP=31;ECNT=5;GERMQ=46;MBQ=20,34;MFRL=336,390;MMQ=43,27;MPOS=44;POPAF=7.30;ROQ=67;TLOD=9.19 GT:AD:AF:DP:F1R2:F2R1:FAD:SB    0/1:27,4:0.161:31:8,1:9,3:25,4:11,16,0,4
chr1_KI270708v1_random  3023    .       G       A       .       clustered_events;map_qual;weak_evidence AS_FilterStatus=weak_evidence,map_qual;AS_SB_TABLE=8,21|1,2;DP=33;ECNT=5;GERMQ=55;MBQ=34,33;MFRL=338,360;MMQ=43,22;MPOS=30;POPAF=7.30;ROQ=34;TLOD=3.40    GT:AD:AF:DP:F1R2:F2R1:FAD:SB    0/1:29,3:0.122:32:7,0:10,3:27,3:8,21,1,2
user@D52BV-2U:/raid/tmp/82/68cd46b704bab21cb8661465e5c2b8$ /samtools-1.17/samtools view -H WGS-NA12878.sorted.dedup.recal.bam | grep chr1_KI270708v1_random | head
@SQ     SN:chr1_KI270708v1_random       LN:127682
user@D52BV-2U:/raid/tmp/82/68cd46b704bab21cb8661465e5c2b8$ grep chr1_KI270708v1_random /raid/bundle/hg38/Homo_sapiens_assembly38.fasta.fai
chr1_KI270708v1_random  127682  3119381772      100     101
```

I don't know how to check img.
