### ISSUE TITLE
Issue with SplitNCigarReads - Attempt to add record to closed writer

### ISSUE THREAD

**Issue by danieljrichard** [broadinstitute/gatk#8232]
I've been trying repeatedly to run SplitNCigarReads on a mapped RNA-seq bam file (from STAR), but receive the following error:

[March 2, 2023 at 8:40:36 AM EST] org.broadinstitute.hellbender.tools.walkers.rnaseq.SplitNCigarReads done. Elapsed time: 1.23 minutes.
Runtime.totalMemory()=5184159744
htsjdk.samtools.util.RuntimeIOException: Attempt to add record to closed writer.
	at htsjdk.samtools.util.AbstractAsyncWriter.write(AbstractAsyncWriter.java:57)
	at htsjdk.samtools.AsyncSAMFileWriter.addAlignment(AsyncSAMFileWriter.java:58)
	at org.broadinstitute.hellbender.utils.read.SAMFileGATKReadWriter.addRead(SAMFileGATKReadWriter.java:21)
	at org.broadinstitute.hellbender.tools.walkers.rnaseq.OverhangFixingManager.writeReads(OverhangFixingManager.java:358)
	at org.broadinstitute.hellbender.tools.walkers.rnaseq.OverhangFixingManager.flush(OverhangFixingManager.java:338)
	at org.broadinstitute.hellbender.tools.walkers.rnaseq.SplitNCigarReads.closeTool(SplitNCigarReads.java:192)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1101)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)

I've run the following command:

/cold/gatk-4.3.0.0/./gatk	 --java-options "-Xmx25g" SplitNCigarReads \
	 -R /cold/base/Homo_sapiens.GRCh38.dna.primary_assembly.fa -I subset_TINY_rehead.bam \
	  --tmp-dir /thing -O thing.bam

I've tried setting --tmp-dir, as well as the system varliable TEMP_DIR, but all to no avail. Any suggestions/work-arounds?

**Comment by lbergelson** [comment]
Hi @danieljrichard.  I suspect the error message you're seeing is a not the underlying problem.  Sometimes when the tool crashes there are errors during standard shutdown cleanup that hide the real problem.  There's a [recent patch](https://github.com/broadinstitute/gatk/commit/f7dea3c08b126c56b851c4d381cfdb5513e0584f) which makes it so that should happen much less but it's not in any currently released version.

Are you able to build the current master branch of gatk and repeat your test with that version?  I suspect it will clarify what's going on.

**Comment by danieljrichard** [comment]
Hi @lbergelson 
Thanks for the response!
I tried building the current gatk from the master branch, and now the error message says something a little different.

java.lang.ClassCastException: class htsjdk.samtools.BAMRecord cannot be cast to class java.lang.Comparable (htsjdk.samtools.BAMRecord is in unnamed module of loader 'app'; java.lang.Comparable is in module java.base of loader 'bootstrap')
	at java.base/java.util.Arrays$NaturalOrder.compare(Arrays.java:105)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.base/java.util.TimSort.sort(TimSort.java:234)
	at java.base/java.util.ArraysParallelSortHelpers$FJObject$Sorter.compute(ArraysParallelSortHelpers.java:145)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.Arrays.parallelSort(Arrays.java:1183)
	at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:247)
	at htsjdk.samtools.util.SortingCollection.add(SortingCollection.java:182)
	at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:202)
	at htsjdk.samtools.AsyncSAMFileWriter.synchronouslyWrite(AsyncSAMFileWriter.java:36)
	at htsjdk.samtools.AsyncSAMFileWriter.synchronouslyWrite(AsyncSAMFileWriter.java:16)
	at htsjdk.samtools.util.AbstractAsyncWriter$WriterRunnable.run(AbstractAsyncWriter.java:123)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: htsjdk.samtools.util.RuntimeIOException: Attempt to add record to closed writer.
		at htsjdk.samtools.util.AbstractAsyncWriter.write(AbstractAsyncWriter.java:57)
		at htsjdk.samtools.AsyncSAMFileWriter.addAlignment(AsyncSAMFileWriter.java:58)
		at org.broadinstitute.hellbender.utils.read.SAMFileGATKReadWriter.addRead(SAMFileGATKReadWriter.java:21)
		at org.broadinstitute.hellbender.tools.walkers.rnaseq.OverhangFixingManager.writeReads(OverhangFixingManager.java:358)
		at org.broadinstitute.hellbender.tools.walkers.rnaseq.OverhangFixingManager.flush(OverhangFixingManager.java:338)
		at org.broadinstitute.hellbender.tools.walkers.rnaseq.SplitNCigarReads.closeTool(SplitNCigarReads.java:192)
		at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1095)
		at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:149)
		at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:198)
		at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:217)
		at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
		at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
		at org.broadinstitute.hellbender.Main.main(Main.java:289)


Still have no idea why it's doing this though. Trying ValidateSamFile on my file in question doesn't turn up anything meaningful.

**Comment by lbergelson** [comment]
Thanks, that's a more useful error message I think.  What version of java are you running?  The current version of GATK requires java 8.  It sounds like you're running a java that includes a module system which is java 9+.  However, the situation is changing very soon, we are upgrading gatk to use java 17.

**Comment by danieljrichard** [comment]
Hi,
This is what I get from java -version

openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu122.04, mixed mode)

So are you saying I'd need to downgrade my java version and try again?

**Comment by lbergelson** [comment]
Yes, you need to use java 8 at the moment.  You don't have to remove your existing java installation, you can add a second one.  It's annoying, which is why we're finally updating to java 17 (the newest long term release).  You'll have the opposite problem then though... Sorry!

**Comment by danieljrichard** [comment]
Hi again,
I tried installing java8 and switching to this version prior to running gatk. It runs and looks to be running the right Java, but spits out roughly the same error:

Thoughts?

/cold/drichard/gatk/./gatk       --java-options "-Xmx25g" SplitNCigarReads \
         -R /cold/drichard/VARIANTS/Homo_sapiens.GRCh38.dna.primary_assembly.fa -I subset_TINY_rehead.bam \
          --tmp-dir /thing -O thing.bam
Using GATK jar /cold/drichard/gatk/build/libs/gatk-package-4.3.0.0-44-g227bbca-SNAPSHOT-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx25g -jar /cold/drichard/gatk/build/libs/gatk-package-4.3.0.0-44-g227bbca-SNAPSHOT-local.jar SplitNCigarReads -R /cold/drichard/VARIANTS/Homo_sapiens.GRCh38.dna.primary_assembly.fa -I subset_TINY_rehead.bam --tmp-dir /thing -O thing.bam
15:34:59.974 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/cold/drichard/gatk/build/libs/gatk-package-4.3.0.0-44-g227bbca-SNAPSHOT-local.jar!/com/intel/gkl/native/libgkl_compression.so
15:35:00.220 INFO  SplitNCigarReads - ------------------------------------------------------------
15:35:00.226 INFO  SplitNCigarReads - The Genome Analysis Toolkit (GATK) v4.3.0.0-44-g227bbca-SNAPSHOT
15:35:00.226 INFO  SplitNCigarReads - For support and documentation go to https://software.broadinstitute.org/gatk/
15:35:00.226 INFO  SplitNCigarReads - Executing as drichard@illuvatar on Linux v5.19.0-32-generic amd64
15:35:00.226 INFO  SplitNCigarReads - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_362-8u362-ga-0ubuntu1~22.04-b09
15:35:00.226 INFO  SplitNCigarReads - Start Date/Time: March 2, 2023 3:34:59 PM EST
15:35:00.226 INFO  SplitNCigarReads - ------------------------------------------------------------
15:35:00.226 INFO  SplitNCigarReads - ------------------------------------------------------------
15:35:00.227 INFO  SplitNCigarReads - HTSJDK Version: 3.0.1
15:35:00.228 INFO  SplitNCigarReads - Picard Version: 2.27.5
15:35:00.228 INFO  SplitNCigarReads - Built for Spark Version: 2.4.5
15:35:00.228 INFO  SplitNCigarReads - HTSJDK Defaults.COMPRESSION_LEVEL : 2
15:35:00.228 INFO  SplitNCigarReads - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
15:35:00.228 INFO  SplitNCigarReads - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
15:35:00.228 INFO  SplitNCigarReads - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
15:35:00.228 INFO  SplitNCigarReads - Deflater: IntelDeflater
15:35:00.228 INFO  SplitNCigarReads - Inflater: IntelInflater
15:35:00.228 INFO  SplitNCigarReads - GCS max retries/reopens: 20
15:35:00.228 INFO  SplitNCigarReads - Requester pays: disabled
15:35:00.229 INFO  SplitNCigarReads - Initializing engine
15:35:00.848 INFO  SplitNCigarReads - Done initializing engine
15:35:00.865 WARN  ReadUtils - Skipping index file creation for: thing.bam. Index file creation requires reads in coordinate sorted order.
15:35:00.893 INFO  ProgressMeter - Starting traversal
15:35:00.893 INFO  ProgressMeter -        Current Locus  Elapsed Minutes       Reads Processed     Reads/Minute
15:35:11.329 INFO  ProgressMeter -           1:65226145              0.2                 53000         304743.7
15:35:21.942 INFO  ProgressMeter -          1:153991192              0.4                107000         305002.6
15:35:31.997 INFO  ProgressMeter -          1:222669039              0.5                126000         243055.6
15:35:42.174 INFO  ProgressMeter -          11:57816875              0.7                192000         279063.0
15:35:52.178 INFO  ProgressMeter -          12:54282575              0.9                268000         313542.0
15:36:02.325 INFO  ProgressMeter -         12:122061657              1.0                299000         292030.2
15:36:12.557 INFO  ProgressMeter -          15:93026953              1.2                400000         334896.2
15:36:22.569 INFO  ProgressMeter -          16:90167524              1.4                471000         346001.3
15:36:32.586 INFO  ProgressMeter -            18:712376              1.5                525000         343537.7
15:36:42.599 INFO  ProgressMeter -           2:55530936              1.7                594000         350421.8
15:36:52.762 INFO  ProgressMeter -          2:241655733              1.9                643000         344867.7
15:37:03.073 INFO  ProgressMeter -           21:8393136              2.0               1417000         695864.3
15:37:13.074 INFO  ProgressMeter -           21:8443153              2.2               2249000        1020880.6
15:37:23.272 INFO  ProgressMeter -          3:120411863              2.4               2532000        1067011.3
15:37:33.340 INFO  ProgressMeter -          4:186611513              2.5               2585000        1017402.8
15:37:43.528 INFO  ProgressMeter -          5:177616134              2.7               2641000         974329.0
15:37:53.980 INFO  ProgressMeter -          6:149409677              2.9               2726000         944958.3
15:38:04.090 INFO  ProgressMeter -          7:128659559              3.1               2797000         916063.0
15:38:14.096 INFO  ProgressMeter -          9:133019868              3.2               2880000         894396.0
15:38:24.255 INFO  ProgressMeter -    KI270733.1:130912              3.4               3282000         968322.5
15:38:34.425 INFO  ProgressMeter -    GL000220.1:115140              3.6               4314000        1212183.7
15:38:44.573 INFO  ProgressMeter -             unmapped              3.7               5276000        1415236.1
15:38:44.689 WARN  IntelInflater - Zero Bytes Written : 0
15:38:44.691 INFO  SplitNCigarReads - 0 read(s) filtered by: AllowAllReadsReadFilter 

15:38:45.179 INFO  OverhangFixingManager - Overhang Fixing Manager saved 434 reads in the first pass
15:38:45.182 INFO  SplitNCigarReads - Starting traversal pass 2
15:38:54.809 INFO  ProgressMeter -           1:67424901              3.9               5368000        1376916.3
15:39:05.144 INFO  ProgressMeter -          1:153935839              4.1               5421000        1331662.9
15:39:15.368 INFO  ProgressMeter -          1:210675831              4.2               5438000        1282169.2
15:39:25.463 INFO  ProgressMeter -         10:119579965              4.4               5479000        1242549.2
15:39:35.700 INFO  ProgressMeter -         11:118752077              4.6               5530000        1207397.2
15:39:46.028 INFO  ProgressMeter -          12:58875536              4.8               5592000        1176709.9
15:39:56.079 INFO  ProgressMeter -          13:37022394              4.9               5628000        1143956.7
15:40:06.117 INFO  ProgressMeter -          16:14727212              5.1               5728000        1125992.7
15:40:16.383 INFO  SplitNCigarReads - Shutting down engine
[March 2, 2023 3:40:16 PM EST] org.broadinstitute.hellbender.tools.walkers.rnaseq.SplitNCigarReads done. Elapsed time: 5.27 minutes.
Runtime.totalMemory()=3432513536
java.lang.ClassCastException: htsjdk.samtools.BAMRecord cannot be cast to java.lang.Comparable
	at java.util.Arrays$NaturalOrder.compare(Arrays.java:102)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.ArraysParallelSortHelpers$FJObject$Sorter.compute(ArraysParallelSortHelpers.java:145)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.Arrays.parallelSort(Arrays.java:1180)
	at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:247)
	at htsjdk.samtools.util.SortingCollection.add(SortingCollection.java:182)
	at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:202)
	at htsjdk.samtools.AsyncSAMFileWriter.synchronouslyWrite(AsyncSAMFileWriter.java:36)
	at htsjdk.samtools.AsyncSAMFileWriter.synchronouslyWrite(AsyncSAMFileWriter.java:16)
	at htsjdk.samtools.util.AbstractAsyncWriter$WriterRunnable.run(AbstractAsyncWriter.java:123)
	at java.lang.Thread.run(Thread.java:750)
	Suppressed: htsjdk.samtools.util.RuntimeIOException: Attempt to add record to closed writer.
		at htsjdk.samtools.util.AbstractAsyncWriter.write(AbstractAsyncWriter.java:57)
		at htsjdk.samtools.AsyncSAMFileWriter.addAlignment(AsyncSAMFileWriter.java:58)
		at org.broadinstitute.hellbender.utils.read.SAMFileGATKReadWriter.addRead(SAMFileGATKReadWriter.java:21)
		at org.broadinstitute.hellbender.tools.walkers.rnaseq.OverhangFixingManager.writeReads(OverhangFixingManager.java:358)
		at org.broadinstitute.hellbender.tools.walkers.rnaseq.OverhangFixingManager.flush(OverhangFixingManager.java:338)
		at org.broadinstitute.hellbender.tools.walkers.rnaseq.SplitNCigarReads.closeTool(SplitNCigarReads.java:192)
		at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1095)
		at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:149)
		at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:198)
		at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:217)
		at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
		at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
		at org.broadinstitute.hellbender.Main.main(Main.java:289)

**Comment by lbergelson** [comment]
Thanks for running the tests. I was hopeful that that would fix it but it
sounds something else is going on that needs investigation.

**Comment by danieljrichard** [comment]
Just wanted to add - I just tried installing the GATK docker as described here: https://gatk.broadinstitute.org/hc/en-us/articles/360035889991--How-to-Run-GATK-in-a-Docker-container

As I'd think that all software dependencies and whatnot should be fine. However, I still get the same error message:

/gatk/./gatk --java-options "-Xmx25g" SplitNCigarReads \
>  -R Homo_sapiens.GRCh38.dna.primary_assembly.fa -I subset_TINY_rehead.bam \
>   --tmp-dir /gatk/my_data/temp -O thing.bam
Using GATK jar /gatk/gatk-package-4.1.3.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx25g -jar /gatk/gatk-package-4.1.3.0-local.jar SplitNCigarReads -R Homo_sapiens.GRCh38.dna.primary_assembly.fa -I subset_TINY_rehead.bam --tmp-dir /gatk/my_data/temp -O thing.bam

21:12:14.158 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gatk/gatk-package-4.1.3.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Mar 02, 2023 9:12:16 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
21:12:16.383 INFO  SplitNCigarReads - ------------------------------------------------------------
21:12:16.384 INFO  SplitNCigarReads - The Genome Analysis Toolkit (GATK) v4.1.3.0
21:12:16.384 INFO  SplitNCigarReads - For support and documentation go to https://software.broadinstitute.org/gatk/
21:12:16.384 INFO  SplitNCigarReads - Executing as root@9d399eec0e24 on Linux v5.19.0-32-generic amd64
21:12:16.384 INFO  SplitNCigarReads - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_191-8u191-b12-0ubuntu0.16.04.1-b12
21:12:16.384 INFO  SplitNCigarReads - Start Date/Time: March 2, 2023 9:12:14 PM UTC
21:12:16.385 INFO  SplitNCigarReads - ------------------------------------------------------------
21:12:16.385 INFO  SplitNCigarReads - ------------------------------------------------------------
21:12:16.385 INFO  SplitNCigarReads - HTSJDK Version: 2.20.1
21:12:16.385 INFO  SplitNCigarReads - Picard Version: 2.20.5
21:12:16.385 INFO  SplitNCigarReads - HTSJDK Defaults.COMPRESSION_LEVEL : 2
21:12:16.385 INFO  SplitNCigarReads - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
21:12:16.385 INFO  SplitNCigarReads - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
21:12:16.385 INFO  SplitNCigarReads - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
21:12:16.385 INFO  SplitNCigarReads - Deflater: IntelDeflater
21:12:16.386 INFO  SplitNCigarReads - Inflater: IntelInflater
21:12:16.386 INFO  SplitNCigarReads - GCS max retries/reopens: 20
21:12:16.386 INFO  SplitNCigarReads - Requester pays: disabled
21:12:16.386 INFO  SplitNCigarReads - Initializing engine
WARNING: BAM index file /gatk/my_data/subset_TINY_rehead.bam.bai is older than BAM /gatk/my_data/subset_TINY_rehead.bam
21:12:16.896 INFO  SplitNCigarReads - Done initializing engine
21:12:16.913 WARN  ReadUtils - Skipping index file creation for: thing.bam. Index file creation requires reads in coordinate sorted order.
21:12:16.948 INFO  ProgressMeter - Starting traversal
21:12:16.949 INFO  ProgressMeter -        Current Locus  Elapsed Minutes       Reads Processed     Reads/Minute
21:12:26.953 INFO  ProgressMeter -           1:65226145              0.2                 53000         317904.6
21:12:36.957 INFO  ProgressMeter -          1:155259605              0.3                109000         326869.3
21:12:47.100 INFO  ProgressMeter -          1:244701896              0.5                132000         262677.9
21:12:57.124 INFO  ProgressMeter -          11:72229208              0.7                206000         307661.7
21:13:07.325 INFO  ProgressMeter -          12:76056153              0.8                281000         334683.2
21:13:17.357 INFO  ProgressMeter -          14:90256593              1.0                345000         342669.8
21:13:27.369 INFO  ProgressMeter -          16:89562379              1.2                470000         400454.4
21:13:37.704 INFO  ProgressMeter -          19:35164186              1.3                561000         416816.3
21:13:47.910 INFO  ProgressMeter -          2:203190998              1.5                631000         416222.3
21:13:57.913 INFO  ProgressMeter -           21:8218424              1.7               1119000         664989.5
21:14:07.919 INFO  ProgressMeter -           21:8437578              1.8               1978000        1069478.2
21:14:17.969 INFO  ProgressMeter -          22:29264542              2.0               2489000        1234021.1
21:14:28.000 INFO  ProgressMeter -           4:22438299              2.2               2556000        1170240.4
21:14:38.145 INFO  ProgressMeter -          5:176347230              2.4               2640000        1121852.8
21:14:48.499 INFO  ProgressMeter -          6:142445365              2.5               2725000        1078851.9
21:14:58.586 INFO  ProgressMeter -          7:128659559              2.7               2797000        1038252.4
21:15:08.662 INFO  ProgressMeter -          9:128421421              2.9               2869000        1002486.7
21:15:19.013 INFO  ProgressMeter -    KI270733.1:130912              3.0               3282000        1081603.6
21:15:29.012 INFO  ProgressMeter -    GL000220.1:114679              3.2               4258000        1330188.5
21:15:39.014 INFO  ProgressMeter -             unmapped              3.4               5175000        1536641.9
21:15:40.046 INFO  SplitNCigarReads - Finished first pass through the reads
21:15:40.613 INFO  OverhangFixingManager - Overhang Fixing Manager saved 434 reads in the first pass
WARNING: BAM index file /gatk/my_data/subset_TINY_rehead.bam.bai is older than BAM /gatk/my_data/subset_TINY_rehead.bam
21:15:40.627 INFO  SplitNCigarReads - Starting second pass through the reads
21:15:49.553 INFO  ProgressMeter -           1:52446384              3.5               5365000        1514089.6
21:16:00.221 INFO  ProgressMeter -          1:151676272              3.7               5420000        1456525.9
21:16:10.407 INFO  ProgressMeter -          1:210675831              3.9               5438000        1397596.1
21:16:20.508 INFO  ProgressMeter -         10:126252122              4.1               5482000        1350473.6
21:16:30.624 INFO  ProgressMeter -            12:763575              4.2               5535000        1309155.4
21:16:40.899 INFO  ProgressMeter -          12:98644570              4.4               5601000        1273195.7
21:16:50.938 INFO  ProgressMeter -          14:70584526              4.6               5656000        1238589.9
21:17:01.113 INFO  ProgressMeter -          16:51645883              4.7               5764000        1217043.7
21:17:05.994 INFO  SplitNCigarReads - Shutting down engine
[March 2, 2023 9:17:05 PM UTC] org.broadinstitute.hellbender.tools.walkers.rnaseq.SplitNCigarReads done. Elapsed time: 4.86 minutes.
Runtime.totalMemory()=3214934016
htsjdk.samtools.util.RuntimeIOException: Attempt to add record to closed writer.
	at htsjdk.samtools.util.AbstractAsyncWriter.write(AbstractAsyncWriter.java:57)
	at htsjdk.samtools.AsyncSAMFileWriter.addAlignment(AsyncSAMFileWriter.java:53)
	at org.broadinstitute.hellbender.utils.read.SAMFileGATKReadWriter.addRead(SAMFileGATKReadWriter.java:21)
	at org.broadinstitute.hellbender.tools.walkers.rnaseq.OverhangFixingManager.writeReads(OverhangFixingManager.java:358)
	at org.broadinstitute.hellbender.tools.walkers.rnaseq.OverhangFixingManager.flush(OverhangFixingManager.java:338)
	at org.broadinstitute.hellbender.tools.walkers.rnaseq.SplitNCigarReads.closeTool(SplitNCigarReads.java:196)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1052)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)
