### ISSUE TITLE
request memory-related exit status (137) for `java.lang.OutOfMemoryError: Java heap space`

### ISSUE THREAD

**Issue by sorelfitzgibbon** [broadinstitute/gatk#8264]
### Tool(s) or class(es) involved
LearnReadOrientation (& others I believe)

### Description
Wondering if you would consider modifying the exit status for 'java.lang.OutOfMemoryError` to reflect it being a memory-related error, perhaps `137`?  This would help with pipelines that will retry with more memory in response to a memory-related  error.

The exit status is currently a generic `1`:

```
Command exit status:
  1

...
  [March 23, 2023 at 5:50:17 AM GMT] org.broadinstitute.hellbender.tools.walkers.readorientation.LearnReadOrientationModel done. Elapsed time: 2,210.83 minutes.
  Runtime.totalMemory()=7796817920
  Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at org.apache.commons.math3.linear.Array2DRowRealMatrix.<init>(Array2DRowRealMatrix.java:61)
        at org.broadinstitute.hellbender.tools.walkers.readorientation.LearnReadOrientationModelEngine.<init>(LearnReadOrientationModelEngine.java:131)
        at org.broadinstitute.hellbender.tools.walkers.readorientation.LearnReadOrientationModel.doWork(LearnReadOrientationModel.java:163)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:149)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:198)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:217)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
  Using GATK jar /gatk/gatk-package-4.4.0.0-local.jar
```

**Comment by droazen** [comment]
This is a good suggestion @sorelfitzgibbon ! We've opened a PR to make this change here: https://github.com/broadinstitute/gatk/pull/8277
