### ISSUE TITLE
Minimap2 aligned reads are broken in HaplotypeCaller due to being mis-identified as FlowBased reads and crashing.

### ISSUE THREAD

**Issue by jamesemery** [broadinstitute/gatk#8335]
It seems that a [few users](https://gatk.broadinstitute.org/hc/en-us/community/posts/11440622639387-Unable-to-trim-uncertain-bases-without-flow-order-information?page=1#community_comment_12925222020763) have complained when they try to use LongReads that their minimap2 bams are failing with the message: 
`org.broadinstitute.hellbender.exceptions.GATKException: Unable to trim uncertain bases without flow order information`

It looks like in `AssemblyBasedCallerUtils.java:147` we are calling `FlowBasedReadUtils.isFlow(originalRead)` on every read and the presence of the `tp` read tag in reads is considered sufficient to flag reads as being flow based which finally causes them to fail. This check was probably misguided, we should really be checking flow-based identity (at this stage anyway) from the readgroup in the header to prevent any spurious read tags from god knows what aligners don't cause problems like this again. Alternatively we should thread the "isFlowBased" check down into this part of the code so its opt-in to treat flow based reads specially when clipping here.

**Comment by ilyasoifer** [comment]
@jamesemery looks unfortunate. Will fix this of course.

**Comment by regeneron-mpds** [comment]
This problem seems to appear in GATK v4.4 as well. With pacbio input data, I get the following error with HaplotypeCaller (defalt arguments).

```
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /.../gatk4-4.4.0.0-0/gatk-package-4.4.0.0-local.jar HaplotypeCaller -R /.../chr.fa -I /.../pacbio.bam -O /.../variants.vcf
13:51:11.105 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/.../share/gatk4-4.4.0.0-0/gatk-package-4.4.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
13:51:11.146 INFO  HaplotypeCaller - ------------------------------------------------------------
13:51:11.149 INFO  HaplotypeCaller - The Genome Analysis Toolkit (GATK) v4.4.0.0
13:51:11.149 INFO  HaplotypeCaller - For support and documentation go to https://software.broadinstitute.org/gatk/
13:51:11.149 INFO  HaplotypeCaller - Executing as xxx
13:51:11.149 INFO  HaplotypeCaller - Java runtime: OpenJDK 64-Bit Server VM v17.0.3-internal+0-adhoc..src
13:51:11.149 INFO  HaplotypeCaller - Start Date/Time: September 27, 2023 at 1:51:11 PM EDT
13:51:11.149 INFO  HaplotypeCaller - ------------------------------------------------------------
13:51:11.149 INFO  HaplotypeCaller - ------------------------------------------------------------
13:51:11.150 INFO  HaplotypeCaller - HTSJDK Version: 3.0.5
13:51:11.150 INFO  HaplotypeCaller - Picard Version: 3.0.0
13:51:11.150 INFO  HaplotypeCaller - Built for Spark Version: 3.3.1
13:51:11.151 INFO  HaplotypeCaller - HTSJDK Defaults.COMPRESSION_LEVEL : 2
13:51:11.151 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
13:51:11.151 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
13:51:11.151 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
13:51:11.151 INFO  HaplotypeCaller - Deflater: IntelDeflater
13:51:11.151 INFO  HaplotypeCaller - Inflater: IntelInflater
13:51:11.151 INFO  HaplotypeCaller - GCS max retries/reopens: 20
13:51:11.152 INFO  HaplotypeCaller - Requester pays: disabled
13:51:11.152 INFO  HaplotypeCaller - Initializing engine
13:51:11.571 INFO  HaplotypeCaller - Done initializing engine
13:51:11.631 INFO  HaplotypeCallerEngine - Disabling physical phasing, which is supported only for reference-model confidence output
13:51:11.640 INFO  NativeLibraryLoader - Loading libgkl_utils.so from jar:file:/.../gatk4-4.4.0.0-0/gatk-package-4.4.0.0-local.jar!/com/intel/gkl/native/libgkl_utils.so
13:51:11.657 INFO  NativeLibraryLoader - Loading libgkl_pairhmm_omp.so from jar:file:/.../gatk4-4.4.0.0-0/gatk-package-4.4.0.0-local.jar!/com/intel/gkl/native/libgkl_pairhmm_omp.so
13:51:11.686 INFO  IntelPairHmm - Using CPU-supported AVX-512 instructions
13:51:11.686 INFO  IntelPairHmm - Flush-to-zero (FTZ) is enabled when running PairHMM
13:51:11.710 INFO  IntelPairHmm - Available threads: 64
13:51:11.710 INFO  IntelPairHmm - Requested threads: 4
13:51:11.710 INFO  PairHMM - Using the OpenMP multi-threaded AVX-accelerated native PairHMM implementation
13:51:11.762 INFO  ProgressMeter - Starting traversal
13:51:11.762 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Regions Processed   Regions/Minute
13:51:12.939 INFO  VectorLoglessPairHMM - Time spent in setup for JNI call : 0.0
13:51:12.940 INFO  PairHMM - Total compute time in PairHMM computeLogLikelihoods() : 0.0
13:51:12.940 INFO  SmithWatermanAligner - Total compute time in java Smith-Waterman : 0.00 sec
13:51:12.941 INFO  HaplotypeCaller - Shutting down engine
[September 27, 2023 at 1:51:12 PM EDT] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 0.03 minutes.
Runtime.totalMemory()=1224736768
org.broadinstitute.hellbender.exceptions.GATKException: Unable to trim uncertain bases without flow order information
        at org.broadinstitute.hellbender.utils.read.FlowBasedRead.hardClipUncertainBases(FlowBasedRead.java:1039)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.finalizeRegion(AssemblyBasedCallerUtils.java:142)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.assembleReads(AssemblyBasedCallerUtils.java:334)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.callRegion(HaplotypeCallerEngine.java:633)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller.apply(HaplotypeCaller.java:271)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:200)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:173)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1098)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:149)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:198)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:217)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
```
