### ISSUE TITLE
FilterMutectCalls fails under mitochondria mode

### ISSUE THREAD

**Issue by elcortegano** [broadinstitute/gatk#8455]
I'm using GATK 4.2.1.0-0 tool `Mutect2` to call mutations in a mitochondrion genome, and later processing the VCFs with  `FilterMutectCalls` enabling as well the mitochondria mode (`--mitochondria-mode true`).

For some reason, this results in **some** of the VCFs to return the following error:

> java.lang.IllegalArgumentException: log10p: Log10-probability must be 0 or less
> 	at org.broadinstitute.hellbender.utils.Utils.validateArg(Utils.java:798)
> 	at org.broadinstitute.hellbender.utils.MathUtils.log10BinomialProbability(MathUtils.java:646)
> 	at org.broadinstitute.hellbender.utils.MathUtils.binomialProbability(MathUtils.java:639)
> 	at org.broadinstitute.hellbender.tools.walkers.mutect.clustering.SomaticClusteringModel.lambda$calculateQuantileBackgroundResponsibilities$10(SomaticClusteringModel.java:271)
> 	at org.broadinstitute.hellbender.utils.MathUtils.applyToArray(MathUtils.java:1035)
> 	at org.broadinstitute.hellbender.tools.walkers.mutect.clustering.SomaticClusteringModel.calculateQuantileBackgroundResponsibilities(SomaticClusteringModel.java:271)
> 	at org.broadinstitute.hellbender.tools.walkers.mutect.clustering.SomaticClusteringModel.initializeClusters(SomaticClusteringModel.java:165)
> 	at org.broadinstitute.hellbender.tools.walkers.mutect.clustering.SomaticClusteringModel.learnAndClearAccumulatedData(SomaticClusteringModel.java:325)
> 	at org.broadinstitute.hellbender.tools.walkers.mutect.filtering.Mutect2FilteringEngine.learnParameters(Mutect2FilteringEngine.java:153)
> 	at org.broadinstitute.hellbender.tools.walkers.mutect.filtering.FilterMutectCalls.afterNthPass(FilterMutectCalls.java:165)
> 	at org.broadinstitute.hellbender.engine.MultiplePassVariantWalker.traverse(MultiplePassVariantWalker.java:44)
> 	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1085)
> 	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
> 	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
> 	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
> 	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
> 	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
> 	at org.broadinstitute.hellbender.Main.main(Main.java:289)

For those files experiencing the error, it disappears when disabling the mitochondria mode for `FilterMutectCalls`.

I wonder how this problem could be solved so that all VCFs can be filtering in a consistent way, enabling the mitochondria mode. I am happy to share the VCF and reference sequence used it that helps reproducing/solving the issue.

Thank you,
Eugenio

**Comment by meganshand** [comment]
Hi @elcortegano, could you please provide a minimal example VCF and reference that has this issue?

**Comment by elcortegano** [comment]
Hi @meganshand , sure, please find those attached below.

[files.zip](https://github.com/broadinstitute/gatk/files/12280438/files.zip)

GATK was run with: 

    gatk FilterMutectCalls --mitochondria-mode true -V FVB_4.mutect2.vcf -O test.vcf -R NC_005089.1.fa

**Comment by meganshand** [comment]
@elcortegano Thank you for reporting this and providing the test data! The fix was just merged so the next release of GATK should resolve this issue for you.
