### ISSUE TITLE
No plots generated by the gatk AnalyzeCovariates

### ISSUE THREAD

**Issue by vinit-aai** [broadinstitute/gatk#8456]
Using GATK jar /root/miniconda3/envs/denovo/share/gatk4-4.4.0.0-0/gatk-package-4.4.0.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /root/miniconda3/envs/denovo/share/gatk4-4.4.0.0-0/gatk-package-4.4.0.0-local.jar AnalyzeCovariates -before ./sample_analysis/SRR25308851/SRR25308851_before_recal_data.table -after ./sample_analysis/SRR25308851/SRR25308851_after_recal_data.table -plots ./sample_analysis/SRR25308851/SRR25308851_recalibration_plots.pdf
22:13:29.955 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/root/miniconda3/envs/denovo/share/gatk4-4.4.0.0-0/gatk-package-4.4.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
22:13:29.979 INFO  AnalyzeCovariates - ------------------------------------------------------------
22:13:29.981 INFO  AnalyzeCovariates - The Genome Analysis Toolkit (GATK) v4.4.0.0
22:13:29.981 INFO  AnalyzeCovariates - For support and documentation go to https://software.broadinstitute.org/gatk/
22:13:29.981 INFO  AnalyzeCovariates - Executing as root@ip-172-31-23-160 on Linux v5.19.0-1029-aws amd64
22:13:29.981 INFO  AnalyzeCovariates - Java runtime: OpenJDK 64-Bit Server VM v19.0.2+7-Ubuntu-0ubuntu322.04
22:13:29.981 INFO  AnalyzeCovariates - Start Date/Time: August 7, 2023 at 10:13:29 PM UTC
22:13:29.981 INFO  AnalyzeCovariates - ------------------------------------------------------------
22:13:29.981 INFO  AnalyzeCovariates - ------------------------------------------------------------
22:13:29.982 INFO  AnalyzeCovariates - HTSJDK Version: 3.0.5
22:13:29.982 INFO  AnalyzeCovariates - Picard Version: 3.0.0
22:13:29.982 INFO  AnalyzeCovariates - Built for Spark Version: 3.3.1
22:13:29.982 INFO  AnalyzeCovariates - HTSJDK Defaults.COMPRESSION_LEVEL : 2
22:13:29.982 INFO  AnalyzeCovariates - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
22:13:29.983 INFO  AnalyzeCovariates - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
22:13:29.983 INFO  AnalyzeCovariates - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
22:13:29.983 INFO  AnalyzeCovariates - Deflater: IntelDeflater
22:13:29.983 INFO  AnalyzeCovariates - Inflater: IntelInflater
22:13:29.983 INFO  AnalyzeCovariates - GCS max retries/reopens: 20
22:13:29.983 INFO  AnalyzeCovariates - Requester pays: disabled
22:13:29.984 INFO  AnalyzeCovariates - Initializing engine
22:13:29.984 INFO  AnalyzeCovariates - Done initializing engine
22:13:30.002 INFO  AnalyzeCovariates - Generating csv file '/tmp/AnalyzeCovariates13996065741193890473.csv'
22:13:30.002 INFO  AnalyzeCovariates - Generating plots file './sample_analysis/SRR25308851/SRR25308851_recalibration_plots.pdf'
22:13:30.518 INFO  AnalyzeCovariates - Shutting down engine
[August 7, 2023 at 10:13:30 PM UTC] org.broadinstitute.hellbender.tools.walkers.bqsr.AnalyzeCovariates done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=113246208
org.broadinstitute.hellbender.utils.R.RScriptExecutorException:
Rscript exited with 1
Command Line: Rscript -e tempLibDir = '/tmp/Rlib.10708586791705723928';source('/tmp/BQSR.12372590345390592260.R'); /tmp/AnalyzeCovariates13996065741193890473.csv /attach/data/vinit/human_exome/test/./sample_analysis/SRR25308851/SRR25308851_before_recal_data.table /attach/data/vinit/human_exome/test/./sample_analysis/SRR25308851/SRR25308851_recalibration_plots.pdf
Stdout:
Stderr:
Attaching package: ‘gplots’

The following object is masked from ‘package:stats’:

    lowess

Error in names(x) <- value :
  'names' attribute [6] must be the same length as the vector [1]
Calls: source ... finishTable -> .gsa.assignGATKTableToEnvironment -> colnames<-
In addition: Warning messages:
1: In type.convert.default(d[, i]) :
  'as.is' should be specified by the caller; using TRUE
2: In type.convert.default(d[, i]) :
  'as.is' should be specified by the caller; using TRUE
3: In type.convert.default(d[, i]) :
  'as.is' should be specified by the caller; using TRUE
4: In type.convert.default(d[, i]) :
  'as.is' should be specified by the caller; using TRUE
5: In type.convert.default(d[, i]) :
  'as.is' should be specified by the caller; using TRUE
Execution halted

        at org.broadinstitute.hellbender.utils.R.RScriptExecutor.getScriptException(RScriptExecutor.java:79)
        at org.broadinstitute.hellbender.utils.R.RScriptExecutor.getScriptException(RScriptExecutor.java:18)
        at org.broadinstitute.hellbender.utils.runtime.ScriptExecutor.executeCuratedArgs(ScriptExecutor.java:112)
        at org.broadinstitute.hellbender.utils.R.RScriptExecutor.exec(RScriptExecutor.java:125)
        at org.broadinstitute.hellbender.utils.recalibration.RecalUtils.generatePlots(RecalUtils.java:360)
        at org.broadinstitute.hellbender.tools.walkers.bqsr.AnalyzeCovariates.generatePlots(AnalyzeCovariates.java:329)
        at org.broadinstitute.hellbender.tools.walkers.bqsr.AnalyzeCovariates.doWork(AnalyzeCovariates.java:341)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:149)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:198)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:217)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)

The above error occurs when generating plot using:
```
gatk AnalyzeCovariates \
    -before /sample_analysis/SRR25308851/SRR25308851_before_recal_data.table \
    -after /sample_analysis/SRR25308851/SRR25308851_after_recal_data.table \
    -plots /sample_analysis/SRR25308851/SRR25308851_recalibration_plots.pdf
```

SRR12882_before_recal_data.table and SRR12882_after_recal_data.table files are proper, generated using gatk BaseRecalibrator

**Comment by takutosato** [comment]
Hi @vinit-aai, sorry it's been a while since you reported this. Would you be able to share recalibration table files you mentioned above?
