### ISSUE TITLE
Issue in running docker

### ISSUE THREAD

**Issue by fi1d18** [broadinstitute/gatk#8462]
Hi

I have pulled your docker and I am certain bam files are in the path but gate can not locate them

```
(gatk) root@34684eaa046e:/gatk/data/Continuum/WES/vcf# java -d64 -XX:+UseSerialGC -Xmx3G -jar /gatk/gatk.jar CollectSequencingArtifactMetrics -I NG-27280_CLTSS_LTS_001A_lib506241_7636_2_MarkedDup.bam -O NG-27280_CLTSS_LTS_001A_lib506241_7636_2_MarkedDup --FILE_EXTENSION .txt -R GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz
12:49:41.698 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gatk/gatk-package-4.1.3.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
[Thu Aug 10 12:49:41 UTC 2023] CollectSequencingArtifactMetrics  --FILE_EXTENSION .txt --INPUT NG-27280_CLTSS_LTS_001A_lib506241_7636_2_MarkedDup.bam --OUTPUT NG-27280_CLTSS_LTS_001A_lib506241_7636_2_MarkedDup --REFERENCE_SEQUENCE GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz  --MINIMUM_QUALITY_SCORE 20 --MINIMUM_MAPPING_QUALITY 30 --MINIMUM_INSERT_SIZE 60 --MAXIMUM_INSERT_SIZE 600 --INCLUDE_UNPAIRED false --INCLUDE_DUPLICATES false --INCLUDE_NON_PF_READS false --TANDEM_READS false --USE_OQ true --CONTEXT_SIZE 1 --ASSUME_SORTED true --STOP_AFTER 0 --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 2 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
Aug 10, 2023 12:49:43 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
[Thu Aug 10 12:49:43 UTC 2023] Executing as root@34684eaa046e on Linux 4.15.0-208-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_191-8u191-b12-0ubuntu0.16.04.1-b12; Deflater: Intel; Inflater: Intel; Provider GCS is available; Picard version: Version:4.1.3.0
[Thu Aug 10 12:49:43 UTC 2023] picard.analysis.artifacts.CollectSequencingArtifactMetrics done. Elapsed time: 0.03 minutes.
Runtime.totalMemory()=2076049408
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
htsjdk.samtools.SAMException: Cannot read non-existent file: file:///gatk/data/Continuum/WES/vcf/NG-27280_CLTSS_LTS_001A_lib506241_7636_2_MarkedDup.bam
    at htsjdk.samtools.util.IOUtil.assertFileIsReadable(IOUtil.java:483)
    at htsjdk.samtools.util.IOUtil.assertFileIsReadable(IOUtil.java:470)
    at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:95)
    at picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:84)
    at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
    at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:25)
    at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
    at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
    at org.broadinstitute.hellbender.Main.main(Main.java:291)
(gatk) root@34684eaa046e:/gatk/data/Continuum/WES/vcf# ls
GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz
(gatk) root@34684eaa046e:/gatk/data/Continuum/WES/vcf# 
```
Please help me
Thanks

**Comment by fi1d18** [comment]
Thanks a lot

I am trying to run `mutect2` in **tumour-only** mode for which I need a panel of normal (PON)

I have tried **somatic-hg38_1000g_pon.hg38.vcf.vcf** which gives 

`./gatk Mutect2 -R resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta -I /data/Continuum/WES/testAlignmentBROADGenome/results/NG-27280_CLTSS_LTS_001A_lib506241_7636_2_MarkedDup_PicMD.bam -O 3.mt2.vcf -tumor NG-27280_CLTSS_LTS_001A_lib506241_7636_2_MarkedDup_PicMD.targeted_sequencing.sample_name --af-of-alleles-not-in-resource 2.5e-06 --germline-resource af-only-gnomad.hg38.vcf.gz -pon somatic-hg38_1000g_pon.hg38.vcf.vcf`

    A USER ERROR has occurred: Cannot read file:///data/somatic-hg38_1000g_pon.hg38.vcf.vcf because no suitable codecs found

I know **gatk4_mutect2_4136_pon.vcf.gz** locates here

[https://gdc.cancer.gov/about-data/gdc-data-processing/gdc-reference-files][1]

I have downloaded `gdc_dtt-ui_v1.0.0_linux_x86_64.AppImage.zip`

But when clicking says select an application to open this, I even tried gdc-client

I got confused how to use this to download `gatk4_mutect2_4136_pon.vcf.gz`

The only thing I need is downloading


  [1]: https://gdc.cancer.gov/about-data/gdc-data-processing/gdc-reference-files

Please help me to finally manage mutect2 to run

**Comment by fi1d18** [comment]
Thanks this worked

`docker run -v /data/Continuum/WES/:/gatk/vcf -it broadinstitute/gatk:latest`
