### ISSUE TITLE
GenomicsDBImport met java.lang.NumberFormatException: For input string: "G"

### ISSUE THREAD

**Issue by ld9866** [broadinstitute/gatk#8517]
Dear developer:
We installed the gatk4.4 and we want to used the GenomicsDBImport. However, we encountered a problem that made me feel very confused and could not be solved. We had not encountered this problem before, because I was relatively familiar with GATK.
Best day!

Code:
/home/test/Software/gatk-4.4.0.0/gatk GenomicsDBImport \
> -V /home/test/Software/gatk-4.4.0.0/test/SRR11306995.gvcf.gz \
> -V /home/test/Software/gatk-4.4.0.0/test/SRR11306996.gvcf.gz \
> --intervals NC_010443.5 \
> --genomicsdb-workspace-path /home/test/Software/gatk-4.4.0.0/test/02

Erro:
10:19:39.332 INFO  GenomicsDBImport - ------------------------------------------------------------
10:19:39.334 INFO  GenomicsDBImport - The Genome Analysis Toolkit (GATK) v4.4.0.0
10:19:39.335 INFO  GenomicsDBImport - For support and documentation go to https://software.broadinstitute.org/gatk/
10:19:39.335 INFO  GenomicsDBImport - Executing as test@yang301 on Linux v5.15.0-71-generic amd64
10:19:39.335 INFO  GenomicsDBImport - Java runtime: OpenJDK 64-Bit Server VM v17.0.3+7
10:19:39.335 INFO  GenomicsDBImport - Start Date/Time: 
10:19:39.335 INFO  GenomicsDBImport - ------------------------------------------------------------
10:19:39.335 INFO  GenomicsDBImport - ------------------------------------------------------------
10:19:39.336 INFO  GenomicsDBImport - HTSJDK Version: 3.0.5
10:19:39.336 INFO  GenomicsDBImport - Picard Version: 3.0.0
10:19:39.336 INFO  GenomicsDBImport - Built for Spark Version: 3.3.1
10:19:39.336 INFO  GenomicsDBImport - HTSJDK Defaults.COMPRESSION_LEVEL : 2
10:19:39.337 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
10:19:39.337 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
10:19:39.337 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
10:19:39.337 INFO  GenomicsDBImport - Deflater: IntelDeflater
10:19:39.337 INFO  GenomicsDBImport - Inflater: IntelInflater
10:19:39.337 INFO  GenomicsDBImport - GCS max retries/reopens: 20
10:19:39.338 INFO  GenomicsDBImport - Requester pays: disabled
10:19:39.338 INFO  GenomicsDBImport - Initializing engine
10:19:39.489 INFO  IntervalArgumentCollection - Processing 100 bp from intervals
10:19:39.490 INFO  GenomicsDBImport - Done initializing engine
10:19:39.948 INFO  GenomicsDBLibLoader - GenomicsDB native library version : 1.4.4-ce4e1b9
10:19:39.951 INFO  GenomicsDBImport - Vid Map JSON file will be written to /home/test/Software/gatk-4.4.0.0/test/./02/vidmap.json
10:19:39.951 INFO  GenomicsDBImport - Callset Map JSON file will be written to /home/test/Software/gatk-4.4.0.0/test/./02/callset.json
10:19:39.951 INFO  GenomicsDBImport - Complete VCF Header will be written to /home/test/Software/gatk-4.4.0.0/test/./02/vcfheader.vcf
10:19:39.951 INFO  GenomicsDBImport - Importing to workspace - /home/test/Software/gatk-4.4.0.0/test/./02
10:19:40.060 INFO  GenomicsDBImport - Importing batch 1 with 2 samples
10:19:40.075 INFO  GenomicsDBImport - Shutting down engine
org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=285212672
java.lang.NumberFormatException: For input string: "G"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at htsjdk.tribble.readers.TabixReader.getIntv(TabixReader.java:337)
	at htsjdk.tribble.readers.TabixReader.access$500(TabixReader.java:48)
	at htsjdk.tribble.readers.TabixReader$IteratorImpl.next(TabixReader.java:438)
	at htsjdk.tribble.readers.TabixIteratorLineReader.readLine(TabixIteratorLineReader.java:46)
	at htsjdk.tribble.TabixFeatureReader$FeatureIterator.readNextRecord(TabixFeatureReader.java:170)
	at htsjdk.tribble.TabixFeatureReader$FeatureIterator.<init>(TabixFeatureReader.java:159)
	at htsjdk.tribble.TabixFeatureReader.query(TabixFeatureReader.java:133)
	at org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport$1.query(GenomicsDBImport.java:971)
	at org.genomicsdb.importer.GenomicsDBImporter.<init>(GenomicsDBImporter.java:167)
	at org.genomicsdb.importer.GenomicsDBImporter.lambda$null$4(GenomicsDBImporter.java:732)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by zhengluo-lz** [comment]
Hi,
Have you found a solution to this bug?

**Comment by ld9866** [comment]
Hello, I later thought it was caused by the low sequencing quality of some individuals, and this problem would only occur in some individuals.
So I suggest you check to see if this is just a subset of individuals?

**Comment by lbergelson** [comment]
This is some sort of problem with either a corrupt VCF or its index.   I suspect it's a problem with the index.  Try reindexing the compressed vcf and see if that fixes it.
