### ISSUE TITLE
BQSR failed to disable both MappedReadFilter and MappingQualityNotZeroReadFilter together

### ISSUE THREAD

**Issue by nathanLauHKGI** [broadinstitute/gatk#8523]
gatk --java-options "-Xmx4g -DGATK_STACKTRACE_ON_USER_EXCEPTION=true" BaseRecalibrator -I /mnt/fq2bam/sample1.markdup.sorted.bam \
-R /mnt/fq2bam/inputs/reference/files/Homo_sapiens_assembly38.fasta \
--known-sites /mnt/fq2bam/inputs/resources/files/Homo_sapiens_assembly38.known_indels.vcf.gz \
--known-sites /mnt/fq2bam/inputs/resources/files/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz \
--known-sites /mnt/fq2bam/inputs/resources/files/Homo_sapiens_assembly38.dbsnp138.vcf.gz \
-L chr1 \
-DF MappingQualityNotZeroReadFilter \
-DF MappedReadFilter \
-O /mnt/fq2bam/sample1_BQSR001.recal_data.table

I got the following error

java.lang.IllegalStateException: No cigar elements left after removing leading and trailing deletions.
        at org.broadinstitute.hellbender.utils.Utils.validate(Utils.java:814)
        at org.broadinstitute.hellbender.utils.read.CigarBuilder.make(CigarBuilder.java:138)
        at org.broadinstitute.hellbender.utils.read.CigarBuilder.make(CigarBuilder.java:143)
        at org.broadinstitute.hellbender.utils.recalibration.BaseRecalibrationEngine.consolidateCigar(BaseRecalibrationEngine.java:293)
        at org.broadinstitute.hellbender.transformers.ReadTransformer.lambda$andThen$f85d1091$1(ReadTransformer.java:20)
        at org.broadinstitute.hellbender.transformers.ReadTransformer.lambda$andThen$f85d1091$1(ReadTransformer.java:20)
        at org.broadinstitute.hellbender.transformers.ReadTransformer.lambda$andThen$f85d1091$1(ReadTransformer.java:20)
        at org.broadinstitute.hellbender.transformers.ReadTransformer.lambda$andThen$f85d1091$1(ReadTransformer.java:20)
        at org.broadinstitute.hellbender.utils.recalibration.BaseRecalibrationEngine.processRead(BaseRecalibrationEngine.java:118)
        at org.broadinstitute.hellbender.tools.walkers.bqsr.BaseRecalibrator.apply(BaseRecalibrator.java:189)
        at org.broadinstitute.hellbender.engine.ReadWalker.lambda$traverse$0(ReadWalker.java:100)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
        at org.broadinstitute.hellbender.engine.ReadWalker.traverse(ReadWalker.java:98)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1085)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)

When i use -DF MappingQualityNotZeroReadFilter and -DF MappedReadFilter independently, it works fine. But we would like to keep both MQ=0 and unmapped reads, please let me know how can i achieve this?

**Comment by nathanLauHKGI** [comment]
In this case, i am confused. Please find attached samtools stats file.

sample1.markdup.sorted.stats is before BQSR and ApplyBQSR
sample1.stats is after BQSR and ApplyBQSR

As you can see, after BQSR and ApplyBQSR only 1 in 10 remain. do you have any ideas?

[sample1.markdup.sorted.stats.txt](https://github.com/broadinstitute/gatk/files/12657987/sample1.markdup.sorted.stats.txt)
[sample1.stats.txt](https://github.com/broadinstitute/gatk/files/12657988/sample1.stats.txt)

**Comment by nathanLauHKGI** [comment]
please find the following command

gatk --java-options "-Xmx4g -Dsamjdk.compression_level=5 -DGATK_STACKTRACE_ON_USER_EXCEPTION=true" ApplyBQSR \
--create-output-bam-index \
--preserve-qscores-less-than 6 \
--static-quantized-quals 10 \
--static-quantized-quals 20 \
--static-quantized-quals 30 \
chr1 \
-I /mnt/fq2bam/sample1.markdup.sorted.bam \
-R /mnt/fq2bam/inputs/reference/files/Homo_sapiens_assembly38.fasta \
--bqsr-recal-file /mnt/fq2bam/sample1.recal_data.table \
-O /mnt/fq2bam/sample1_BQSR001.final.bam

**Comment by nathanLauHKGI** [comment]
the interval parameter is chr1 in the above command. Please find attached log file for chr1 interval
[error_ApplyBQSR001.log](https://github.com/broadinstitute/gatk/files/12658564/error_ApplyBQSR001.log)

**Comment by nathanLauHKGI** [comment]
I can try but currently apply interval parameters on 25 jobs in parallel. In fact, another samples works fine

**Comment by nathanLauHKGI** [comment]
I understand now. I can reproduce in my data. 

I have difficulty to find this info in the manual
https://gatk.broadinstitute.org/hc/en-us/articles/5257859334043-ApplyBQSR

Thank you very much, your help is much appreciated
