### ISSUE TITLE
Couldn't create GenomicsDBFeatureReader

### ISSUE THREAD

**Issue by zhaohongqiangsoliva** [broadinstitute/gatk#8527]
### Instructions

I'm running on :
gatk 4.3.0.0. 
88 cpu 
128G mem 
538 samples

Chrom 11-22 don't have problems, but 1-11 don't work.
What should I do?
thanks

```
java  -DGATK_STACKTRACE_ON_USER_EXCEPTION=true  -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /home/solivehong/miniconda3/envs/bio_base/share/gatk4-4.3.0.0-0/gatk-package-4.3.0.0-local.jar GenotypeGVCFs -R /data/reference/update_gatk_v0/Homo_sapiens_assembly38.fasta  -V gendb://Genomicsdb.2 -O /storage/project/collaborators/UH_Burdentest/1.running/genotypeGvcf/UH_Burdentest2222.vcf --tmp-dir /storage/GenomesDbimport/Agilent_WES/tmp -L chr2 -G StandardAnnotation --only-output-calls-starting-in-intervals --use-new-qual-calculator -D /data/reference/update_gatk_v0//Homo_sapiens_assembly38.dbsnp138.vcf
20:09:21.335 WARN  GATKAnnotationPluginDescriptor - Redundant enabled annotation group (StandardAnnotation) is enabled for this tool by default
20:09:21.383 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/solivehong/miniconda3/envs/bio_base/share/gatk4-4.3.0.0-0/gatk-package-4.3.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
20:09:21.521 INFO  GenotypeGVCFs - ------------------------------------------------------------
20:09:21.521 INFO  GenotypeGVCFs - The Genome Analysis Toolkit (GATK) v4.3.0.0
20:09:21.521 INFO  GenotypeGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
20:09:21.521 INFO  GenotypeGVCFs - Executing as solivehong@solivehong on Linux v5.10.0-25-amd64 amd64
20:09:21.521 INFO  GenotypeGVCFs - Java runtime: OpenJDK 64-Bit Server VM v11.0.13+7-b1751.21
20:09:21.522 INFO  GenotypeGVCFs - Start Date/Time: September 23, 2023 at 8:09:21 PM CST
20:09:21.522 INFO  GenotypeGVCFs - ------------------------------------------------------------
20:09:21.522 INFO  GenotypeGVCFs - ------------------------------------------------------------
20:09:21.522 INFO  GenotypeGVCFs - HTSJDK Version: 3.0.1
20:09:21.523 INFO  GenotypeGVCFs - Picard Version: 2.27.5
20:09:21.523 INFO  GenotypeGVCFs - Built for Spark Version: 2.4.5
20:09:21.523 INFO  GenotypeGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2
20:09:21.523 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
20:09:21.523 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
20:09:21.523 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
20:09:21.523 INFO  GenotypeGVCFs - Deflater: IntelDeflater
20:09:21.523 INFO  GenotypeGVCFs - Inflater: IntelInflater
20:09:21.523 INFO  GenotypeGVCFs - GCS max retries/reopens: 20
20:09:21.523 INFO  GenotypeGVCFs - Requester pays: disabled
20:09:21.523 INFO  GenotypeGVCFs - Initializing engine
20:09:21.752 INFO  FeatureManager - Using codec VCFCodec to read file file:///data/reference/update_gatk_v0/Homo_sapiens_assembly38.dbsnp138.vcf
20:09:22.176 INFO  GenomicsDBLibLoader - GenomicsDB native library version : 1.4.3-6069e4a
20:09:23.523 info  NativeGenomicsDB - pid=1332903 tid=1332904 No valid combination operation found for INFO field AC  - the field will NOT be part of INFO fields in the generated VCF records
20:09:23.523 info  NativeGenomicsDB - pid=1332903 tid=1332904 No valid combination operation found for INFO field AF  - the field will NOT be part of INFO fields in the generated VCF records
20:09:23.523 info  NativeGenomicsDB - pid=1332903 tid=1332904 No valid combination operation found for INFO field AN  - the field will NOT be part of INFO fields in the generated VCF records
20:09:23.523 info  NativeGenomicsDB - pid=1332903 tid=1332904 No valid combination operation found for INFO field AS_BaseQRankSum  - the field will NOT be part of INFO fields in the generated VCF records
20:09:23.523 info  NativeGenomicsDB - pid=1332903 tid=1332904 No valid combination operation found for INFO field AS_FS  - the field will NOT be part of Iation operation found for INFO field AS_MQ  - the field will NOT be part of INFO fields in the generated VCF records
20:09:23.523 info  NativeGenomicsDB - pid=1332903 tid=1332904 No valid combination operation found for INFO field AS_MQRankSum  - the field will NOT be part of INFO fields in the generated VCF records
20:09:23.523 info  NativeGenomicsDB - pid=1332903 tid=1332904 No valid combination operation found for INFO field AS_QD  - the field will NOT be part of INFO fields in the generated VCF records
20:09:23.524 info  NativeGenomicsDB - pid=1332903 tid=1332904 No valid combination operation found for INFO field AS_ReadPosRankSum  - the field will NOT be part of INFO fields in the generated VCF records
20:09:23.524 info  NativeGenomicsDB - pid=1332903 tid=1332904 No valid combination operation found for INFO field AS_SOR  - the field will NOT be part of INFO fields in the generated VCF records
20:09:23.524 info  NativeGenomicsDB - pid=1332903 tid=1332904 No valid combination operation found for INFO field FS  - the field will NOT be part of INFO fields in the generated VCF records
20:09:23.524 info  NativeGenomicsDB - pid=1332903 tid=1332904 No valid combination operation found for INFO field InbreedingCoeff  - the field will NOT be part of INFO fields in the generated VCF records
20:09:23.524 info  NativeGenomicsDB - pid=1332903 tid=1332904 No valid combination operation found for INFO field QD  - the field will NOT be part of INFO fields in the generated VCF records
20:09:23.524 info  NativeGenomicsDB - pid=1332903 tid=1332904 No valid combination operation found for INFO field SOR  - the field will NOT be part of INFO fields in the generated VCF records
20:09:23.528 INFO  GenotypeGVCFs - Shutting down engine
[September 23, 2023 at 8:09:23 PM CST] org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 0.04 minutes.
Runtime.totalMemory()=2801795072
***********************************************************************

A USER ERROR has occurred: Couldn't create GenomicsDBFeatureReader

***********************************************************************
org.broadinstitute.hellbender.exceptions.UserException: Couldn't create GenomicsDBFeatureReader
        at org.broadinstitute.hellbender.engine.FeatureDataSource.getGenomicsDBFeatureReader(FeatureDataSource.java:463)
        at org.broadinstitute.hellbender.engine.FeatureDataSource.getFeatureReader(FeatureDataSource.java:365)
        at org.broadinstitute.hellbender.engine.FeatureDataSource.<init>(FeatureDataSource.java:319)
        at org.broadinstitute.hellbender.engine.FeatureDataSource.<init>(FeatureDataSource.java:291)
        at org.broadinstitute.hellbender.engine.VariantLocusWalker.initialize        at org.broadinstitute.hellbender.engine.VariantWalkerBase.initializeFava:726)
        at org.broadinstitute.hellbender.engine.VariantLocusWalker.onStartup(VariantLocusWalker.java:63)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:138)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
Caused by: java.io.IOException: GenomicsDB JNI Error: Broad combine GVCFs exception : No sample/CallSet name specified in JSON file/Protobuf object for TileDB row 72
        at org.genomicsdb.reader.GenomicsDBQueryStream.jniGenomicsDBInit(Native Method)
        at org.genomicsdb.reader.GenomicsDBQueryStream.<init>(GenomicsDBQueryStream.java:209)
        at org.genomicsdb.reader.GenomicsDBQueryStream.<init>(GenomicsDBQueryStream.java:182)
        at org.genomicsdb.reader.GenomicsDBQueryStream.<init>(GenomicsDBQueryStream.java:91)
        at org.genomicsdb.reader.GenomicsDBFeatureReader.generateHeadersForQuery(GenomicsDBFeatureReader.java:200)
        at org.genomicsdb.reader.GenomicsDBFeatureReader.<init>(GenomicsDBFeatureReader.java:85)
        at org.broadinstitute.hellbender.engine.FeatureDataSource.getGenomicsDBFeatureReader(FeatureDataSource.java:460)

```

**Comment by CHENG-KH** [comment]
I have the same error. Have you solved it yet?

**Comment by zhaohongqiangsoliva** [comment]
@CHENG-KH i just rerunning DBimport ,actually i restart all work with warp jointgenotype.Because i feels the other settings are wrong too
