### ISSUE TITLE
LeftAlignIndels Alignments added out of order issue when reads are fed in coordinate sorted order.

### ISSUE THREAD

**Issue by gokalpcelik** [broadinstitute/gatk#8975]
Hi team. 
This is an old topic from the forum 

[LeftAlignIndels Alignments added out of order... Offending records are at [chr7:55268881] and [chr7:55268881]](https://gatk.broadinstitute.org/hc/en-us/community/posts/20834436731547-LeftAlignIndels-Alignments-added-out-of-order-Offending-records-are-at-chr7-55268881-and-chr7-55268881)

```
java.lang.IllegalArgumentException: Alignments added out of order in SAMFileWriterImpl.addAlignment for file:///Users/jcovino/Desktop/PLAA_2390/broken.bam. Sort order is coordinate. Offending records are at [chr7:55268881] and [chr7:55268881]
at htsjdk.samtools.SAMFileWriterImpl.assertPresorted(SAMFileWriterImpl.java:212)
at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:199)
at htsjdk.samtools.AsyncSAMFileWriter.synchronouslyWrite(AsyncSAMFileWriter.java:36)
at htsjdk.samtools.AsyncSAMFileWriter.synchronouslyWrite(AsyncSAMFileWriter.java:16)
at htsjdk.samtools.util.AbstractAsyncWriter$WriterRunnable.run(AbstractAsyncWriter.java:123)
at java.base/java.lang.Thread.run(Thread.java:840)
```

The only current solution to this problem is feeding reads in queryname sorted way. When reads are coordinate sorted this error occurs. 

There is a request from users that this tool should be able to work with coordinate sorted reads.

**Comment by standage** [comment]
I have a BAM file that is triggering this behavior. I can't share the file, but there are a pair of reads aligning to the same starting position, one of which contains an ambiguous `N` character. It looks like half of the two reads are composed of very low complexity sequence: AT and GT dinucleotides. I suspect one or both of these observations are relevant.

Unfortunately in my case, sorting reads by name doesn't resolve the issue. I tested with dozens of GATK4 versions, and it seems that the 4.1.0 release is the first release with the problematic behavior: 4.0.12 handles the file with no problems.
