### ISSUE TITLE
Haplotypecaller error 

### ISSUE THREAD

**Issue by polymerase2010** [broadinstitute/gatk#8984]
When I use gatk haplotypecaller to get vcf from WES bam file, it stopped at somewhere of chr4.  The error information is "java.lang.IllegalStateException: Never found start 0 or stop -1 given cigar 23M90D98M". Counld you help me to debug it?

My gatk version is 4.1.6.0.

All error information is as bellows:

14:47:36.134 INFO  ProgressMeter -       chr3:195451651             47.5                141130           2974.2
14:47:46.204 INFO  ProgressMeter -       chr3:195937445             47.6                141450           2970.4
14:47:56.209 INFO  ProgressMeter -       chr3:197401760             47.8                142070           2973.0
14:48:06.317 INFO  ProgressMeter -          chr4:944918             48.0                142740           2976.5
14:48:12.491 INFO  VectorLoglessPairHMM - Time spent in setup for JNI call : 1.403408197
14:48:12.491 INFO  PairHMM - Total compute time in PairHMM computeLogLikelihoods() : 110.672423397
14:48:12.491 INFO  SmithWatermanAligner - Total compute time in java Smith-Waterman : 120.18 sec
14:48:12.492 INFO  HaplotypeCaller - Shutting down engine
[September 13, 2024 at 2:48:12 PM CST] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 48.27 minutes.
Runtime.totalMemory()=708837376
java.lang.IllegalStateException: Never found start 0 or stop -1 given cigar 23M90D98M
        at org.broadinstitute.hellbender.utils.read.AlignmentUtils.getBasesCoveringRefInterval(AlignmentUtils.java:204)
        at org.broadinstitute.hellbender.utils.haplotype.Haplotype.trim(Haplotype.java:95)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyResultSet.trimDownHaplotypes(AssemblyResultSet.java:135)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyResultSet.calculateOriginalByTrimmedHaplotypes(AssemblyResultSet.java:111)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyResultSet.trimTo(AssemblyResultSet.java:73)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.callRegion(HaplotypeCallerEngine.java:558)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller.apply(HaplotypeCaller.java:212)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:200)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:173)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
        at org.broadinstitute.hellbender.Main.main(Main.java:292)
Using GATK jar /mnt/h/linuxdir/software/gatk/build/libs/gatk-package-4.1.6.0-SNAPSHOT-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /mnt/h/linuxdir/software/gatk/build/libs/gatk-package-4.1.6.0-SNAPSHOT-local.jar HaplotypeCaller -R /mnt/h/linuxdir/database/genome/human/refseq/hg19.fa -I /mnt/g/XY10023566/bwa/XY10023566.sorted.markdup.BQSR.bam -O /mnt/g/XY10023566/gatk/XY10023566.HaplotypeCaller.vcf.gz -L /mnt/h/linuxdir/database/genome/human/S07604624_hs_hg19/S07604624_Covered.bed -L /mnt/h/linuxdir/database/genome/human/grch37_exon_chrM.bed --alleles /mnt/h/linuxdir/wespipeline2.0/interestedsite/interested.sort.merged.vcf.gz

**Comment by droazen** [comment]
@polymerase2010 I see that you're running GATK 4.1.6.0, which is almost 5 years old. Can you try the latest release (4.6.0.0), and see if the error goes away? There have been many fixes and improvements to HaplotypeCaller in the past 5 years.

**Comment by polymerase2010** [comment]
Thank you for your suggestion. Haplotypecaller successed and no error reported when I used gatk v4.5.0.0.
