### ISSUE TITLE
Enabling PDHMM causes GVCF mode to fail.

### ISSUE THREAD

**Issue by gokalpcelik** [broadinstitute/gatk#9041]
Hi team.

Enabling `--use-pdhmm true` for HaplotypeCaller results in the below error message thrown when `-ERC GVCF` is enabled. 

```
java.lang.IllegalArgumentException: refHaplotype cannot be null
	at org.broadinstitute.hellbender.utils.Utils.nonNull(Utils.java:643)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.ReferenceConfidenceModel.calculateRefConfidence(ReferenceConfidenceModel.java:216)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.callRegion(HaplotypeCallerEngine.java:1018)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller.apply(HaplotypeCaller.java:284)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:200)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:173)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1119)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:150)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:203)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:222)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:166)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:209)
	at org.broadinstitute.hellbender.Main.main(Main.java:306)

```
This happens under 4.6.0.0 and 4.6.1.0. I have not tested older versions.

**Comment by pantastheo** [comment]
I get the exact same error with `-ERC GVCF` when enabling  `--dragen-378-concordance-mode`, which by default sets `--use-pdhmm true`. Tested on 4.6.1.0.

**Comment by pantastheo** [comment]
Hi team, any plans to add a fix for this?

**Comment by pantastheo** [comment]
Hi @gokalpcelik many thanks for the quick reply. I understand, however I am just wondering what would be the best way to insure compatibility of HC gvcf output with the latest DRAGEN gvcf products going forward?
Will `--dragen-mode` be enough?
