### ISSUE TITLE
Scorevariants python package not found when running NVScoreVariants

### ISSUE THREAD

**Issue by poconnel3** [broadinstitute/gatk#9066]
code: /sc/ww/projects/yy/xx/GATK/gatk-4.6.1.0/gatk NVScoreVariants -V 110-01.trimmed.sam.sorted.bam.dedup.bam.RG.bam.calibrated.bam.corrected.bam.raw_variants.vcf -R ../reference/hg38.analysisSet.fa --tensor-type read_tensor -I 110-01.trimmed.sam.sorted.bam.dedup.bam.RG.bam.calibrated.bam.corrected.bam -O 2Dout.vcf

output: 
Using GATK jar /sc/arion/projects/ISDS/oconnp06/GATK/gatk-4.6.1.0/gatk-package-4.6.1.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /sc/arion/projects/ISDS/oconnp06/GATK/gatk-4.6.1.0/gatk-package-4.6.1.0-local.jar NVScoreVariants -V 110-01.trimmed.sam.sorted.bam.dedup.bam.RG.bam.calibrated.bam.corrected.bam.raw_variants.vcf -R ../reference/hg38.analysisSet.fa --tensor-type read_tensor -I 110-01.trimmed.sam.sorted.bam.dedup.bam.RG.bam.calibrated.bam.corrected.bam -O 2Dout.vcf
17:15:03.393 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/sc/arion/projects/ISDS/oconnp06/GATK/gatk-4.6.1.0/gatk-package-4.6.1.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
SLF4J(W): Class path contains multiple SLF4J providers.
SLF4J(W): Found provider [org.apache.logging.slf4j.SLF4JServiceProvider@5657967b]
SLF4J(W): Found provider [ch.qos.logback.classic.spi.LogbackServiceProvider@61394494]
SLF4J(W): See https://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J(I): Actual provider is of type [org.apache.logging.slf4j.SLF4JServiceProvider@5657967b]
17:15:03.622 INFO  NVScoreVariants - ------------------------------------------------------------
17:15:03.629 INFO  NVScoreVariants - The Genome Analysis Toolkit (GATK) v4.6.1.0
17:15:03.629 INFO  NVScoreVariants - For support and documentation go to https://software.broadinstitute.org/gatk/
17:15:03.629 INFO  NVScoreVariants - Executing as oconnp06@li04e03 on Linux v5.14.0-427.13.1.el9_4.x86_64 amd64
17:15:03.629 INFO  NVScoreVariants - Java runtime: Java HotSpot(TM) 64-Bit Server VM v21.0.4+8-LTS-274
17:15:03.630 INFO  NVScoreVariants - Start Date/Time: December 31, 2024, 5:15:03 PM EST
17:15:03.630 INFO  NVScoreVariants - ------------------------------------------------------------
17:15:03.630 INFO  NVScoreVariants - ------------------------------------------------------------
17:15:03.632 INFO  NVScoreVariants - HTSJDK Version: 4.1.3
17:15:03.632 INFO  NVScoreVariants - Picard Version: 3.3.0
17:15:03.633 INFO  NVScoreVariants - Built for Spark Version: 3.5.0
17:15:03.638 INFO  NVScoreVariants - HTSJDK Defaults.COMPRESSION_LEVEL : 2
17:15:03.638 INFO  NVScoreVariants - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
17:15:03.639 INFO  NVScoreVariants - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
17:15:03.639 INFO  NVScoreVariants - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
17:15:03.639 INFO  NVScoreVariants - Deflater: IntelDeflater
17:15:03.639 INFO  NVScoreVariants - Inflater: IntelInflater
17:15:03.640 INFO  NVScoreVariants - GCS max retries/reopens: 20
17:15:03.640 INFO  NVScoreVariants - Requester pays: disabled
17:15:03.640 WARN  NVScoreVariants - 

   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

   Warning: NVScoreVariants is a BETA tool and is not yet ready for use in production

   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

17:15:03.641 INFO  NVScoreVariants - Initializing engine
17:15:03.749 INFO  NVScoreVariants - Shutting down engine
[December 31, 2024, 5:15:03 PM EST] org.broadinstitute.hellbender.tools.walkers.vqsr.NVScoreVariants done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=234881024
java.lang.RuntimeException: A required Python package ("scorevariants") could not be imported into the Python environment. This tool requires that the GATK Python environment is properly established and activated. Please refer to GATK README.md file for instructions on setting up the GATK Python environment.
	at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.checkPythonEnvironmentForPackage(PythonScriptExecutor.java:228)
	at org.broadinstitute.hellbender.tools.walkers.vqsr.NVScoreVariants.onStartup(NVScoreVariants.java:109)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:148)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:203)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:222)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:166)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:209)
	at org.broadinstitute.hellbender.Main.main(Main.java:306)
Caused by: org.broadinstitute.hellbender.utils.python.PythonScriptExecutorException: 
python exited with 1
Command Line: python -c import scorevariants

Stdout: 
Stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'scorevariants'

I cannot run from a docker image as I am on a HPC. I am running in an active GATK conda env set up based on the 4.6.1 .yml file. 

active environment : gatk
    active env location : /sc/arion/projects/ISDS/oconnp06/test-env/envs/gatk
            shell level : 2
       user config file : /hpc/users/oconnp06/.condarc
 populated config files : /hpc/users/oconnp06/.condarc
          conda version : 24.5.0
    conda-build version : 24.5.1
         python version : 3.12.4.final.0
                 solver : classic
       virtual packages : __archspec=1=sapphirerapids
                          __conda=24.5.0=0
                          __glibc=2.34=0
                          __linux=5.14.0=0
                          __unix=0=0
       base environment : /hpc/packages/minerva-rocky9/anaconda3/2024.06  (read only)
      conda av data dir : /hpc/packages/minerva-rocky9/anaconda3/2024.06/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /sc/arion/projects/ISDS/oconnp06/test-env/pkgs
       envs directories : /sc/arion/projects/ISDS/oconnp06/test-env/envs
                          /hpc/users/oconnp06/.conda/envs
                          /hpc/packages/minerva-rocky9/anaconda3/2024.06/envs
               platform : linux-64
             user-agent : conda/24.5.0 requests/2.31.0 CPython/3.12.4 Linux/5.14.0-427.13.1.el9_4.x86_64 rocky/9.4 glibc/2.34
                UID:GID : 25908:31426
             netrc file : None
           offline mode : False

Please advise how I can run NVScoreVariants from GATK Version 4.6.1

**Comment by poconnel3** [comment]
Issue resolved. My HPC was not allowing me to activate my gatk conda env. I corrected this and it now runs.
