### ISSUE TITLE
ReadsSparkSinkUnitTest.readsSinkADAMTest fails when rerun

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#977]
`ReadsSparkSinkUnitTest.readsSinkADAMTest()` leaves files that it doesn't clean up.  

If you run it twice, it fails the second time, because it won't overwrite an existing file.

This should be fixed by automatically deleting the output files.  (It also shouldn't write them to the main hellbender directory in the first place...)

```
org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory ReadsSparkSinkUnitTest1_ADAM already exists
	at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:146)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply$mcV$sp(PairRDDFunctions.scala:1011)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply(PairRDDFunctions.scala:998)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply(PairRDDFunctions.scala:998)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:286)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopDataset(PairRDDFunctions.scala:998)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply$mcV$sp(PairRDDFunctions.scala:938)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply(PairRDDFunctions.scala:930)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply(PairRDDFunctions.scala:930)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:286)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopFile(PairRDDFunctions.scala:930)
	at org.apache.spark.api.java.JavaPairRDD.saveAsNewAPIHadoopFile(JavaPairRDD.scala:809)
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink.writeReadsADAM(ReadsSparkSink.java:101)
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink.writeReads(ReadsSparkSink.java:83)
	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSinkUnitTest.readsSinkADAMTest(ReadsSparkSinkUnitTest.java:76)
```

**Comment by droazen** [comment]
Looks like the test in question does call `deleteOnExit()`, but fails because the output is a directory. Would calling `Utils.deleteRecursivelyOnExit()` instead fix this?
